# Generate unified .json with all extracted arguments 

- Clean duplicated arguments 
- Display summary statistics per SDG (totals/means, duplicates removed totals/means)
- Display summary statistics (same metrics over the whole set)

In [44]:
import os, re, json
from collections import OrderedDict
import pandas as pd
from typing import List, Optional, Tuple
import csv
import itertools

def process_sdg_runs(
    input_dir, output_dir, output_dir_stats,
    prefix,
    model_name,
    ods_range=(0, 17),
    unified_basename=None,
    interactive=True   # allow disabling manual review
):

    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(output_dir_stats, exist_ok=True)

    # 1. match files of interest
    model_part = re.escape(model_name) if model_name else r".+?"
    pattern = re.compile(rf"^{re.escape(prefix)}_ArgsSGD(\d+)_({model_part})\.json$")

    files = []
    for fn in os.listdir(input_dir):
        m = pattern.match(fn)
        if not m:
            continue
        ods_num = int(m.group(1))
        if ods_num < ods_range[0] or ods_num > ods_range[1]:
            continue
        files.append((ods_num, fn))

    if not files:
        raise FileNotFoundError(f"No files found in '{input_dir}' for prefix='{prefix}'"
                                + (f" and model='{model_name}'" if model_name else ""))

    # 2. Process per ODS (each .json file)
    files.sort(key=lambda x: (x[0], x[1]))

    unified_records = []
    per_sdg_stats = []

    for ods_num, fn in files:
        path = os.path.join(input_dir, fn)
        with open(path, "r", encoding="utf-8") as f:
            pages = json.load(f)

        seen_args = OrderedDict()
        not_valid_args = set()

        # Per-page stats
        page_counts_kept = []
        page_counts_removed = []
        page_counts_original = []
        page_counts_not_valid = []

        for item in pages:
            page = item.get("page")
            section = item.get("section")
            args: List[str] = item.get("arguments", []) or []

            def unique_in_order(seq):
                seen = set()
                out = []
                for s in seq:
                    if s not in seen:
                        out.append(s)
                        seen.add(s)
                return out

            args_original_unique = unique_in_order(args)
            page_original = len(args_original_unique)

            kept_args = []
            removed_here = 0
            not_valid_here = 0

            for a in args_original_unique:
                if a not in seen_args:
                    # manual revision
                    if interactive:
                        print(f"\n[ODS {ods_num} | page {page}] Argument candidate:\n  {a}")
                        resp = input("Keep this argument? (1=yes, 0=no): ").strip()
                        if resp == "0":
                            not_valid_args.add(a)
                            not_valid_here += 1
                            continue
                    kept_args.append(a)
                    seen_args[a] = True
                else:
                    removed_here += 1

            unified_records.append({
                "ods": ods_num,
                "page": page,
                "section": section,
                "arguments": kept_args,
                "source_file": fn,
            })

            page_counts_original.append(page_original)
            page_counts_kept.append(len(kept_args))
            page_counts_removed.append(removed_here)
            page_counts_not_valid.append(not_valid_here)

        # Per-SDG summary row
        pages_count = len(pages)
        total_kept = sum(page_counts_kept)
        total_removed = sum(page_counts_removed)
        total_original = sum(page_counts_original)
        total_not_valid = sum(page_counts_not_valid)

        per_sdg_stats.append({
            "prefix": prefix.replace("_", " ").strip(),
            "model": model_name,
            "ods": ods_num,
            "pages": pages_count,
            "total_args": total_original,
            "total_args_kept": total_kept,
            "total_dupes_removed": total_removed,
            "total_not_valid_args": total_not_valid,
        })

    per_sdg_df = pd.DataFrame(per_sdg_stats).sort_values(["ods"]).reset_index(drop=True)

    if unified_basename is None:
        unified_basename = f"{prefix}_AllArgs"

    unified_json_path = os.path.join(output_dir, f"{unified_basename}_{model_name}.json")
    per_sdg_csv_path = os.path.join(output_dir_stats, f"{unified_basename}_perSDG_summary.csv")

    # Save unified JSON
    with open(unified_json_path, "w", encoding="utf-8") as f:
        json.dump(unified_records, f, indent=2, ensure_ascii=False)

    # Append stats (instead of overwrite)
    if os.path.exists(per_sdg_csv_path):
        existing = pd.read_csv(per_sdg_csv_path)
        per_sdg_df = pd.concat([existing, per_sdg_df], ignore_index=True)
    per_sdg_df.to_csv(per_sdg_csv_path, index=False, encoding="utf-8")


    print(f"\nProcessed {len(per_sdg_df)} SDGs for prefix='{prefix}', model='{model_name}'")
    print(per_sdg_df.to_string(index=False))

    return {
        "unified_json": unified_json_path,
        "per_sdg_summary_csv": per_sdg_csv_path,
        "per_sdg_summary_df": per_sdg_df,
    }

import pandas as pd
import os

def save_overall_summary(res, output_dir_stats, model_name, unified_basename="AllArgs_overall_summary"):
    df = res["per_sdg_summary_df"]
    df = df[df["model"] == model_name]

    # Compute overall metrics
    overall_row = {
        "prefix": df["prefix"].iloc[0],
        "model": df["model"].iloc[0],
        "ods_max": df["ods"].max(),
        "pages_max": df["pages"].max(),
        "total_args": df["total_args"].sum(),
        "total_args_kept": df["total_args_kept"].sum(),
        "total_dupes_removed": df["total_dupes_removed"].sum(),
        "total_not_valid_args": df["total_not_valid_args"].sum(),
    }
    overall_df = pd.DataFrame([overall_row])
    overall_csv_path = os.path.join(output_dir_stats, f"{unified_basename}.csv")

    # Append if exists
    if os.path.exists(overall_csv_path):
        existing = pd.read_csv(overall_csv_path)
        overall_df = pd.concat([existing, overall_df], ignore_index=True)

    overall_df.to_csv(overall_csv_path, index=False, encoding="utf-8")

    print("\nUpdated overall summary:")

    return overall_df

def export_arguments_txt(json_path, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    # 1. Flat list of all arguments
    all_args = []
    for item in data:
        all_args.extend(item.get("arguments", []))

    flat_txt_path = os.path.join(output_dir, os.path.basename(json_path).replace(".json", "_arguments.txt"))
    with open(flat_txt_path, "w", encoding="utf-8") as f:
        for arg in all_args:
            f.write("'" + arg.strip() + "',\n")

    # 2. Dictionary by goal (ods)
    args_by_goal = {}
    for item in data:
        ods = item.get("ods")
        if ods not in args_by_goal:
            args_by_goal[ods] = []
        args_by_goal[ods].extend(item.get("arguments", []))

    dict_txt_path = os.path.join(output_dir, os.path.basename(json_path).replace(".json", "_by_goal.txt"))
    with open(dict_txt_path, "w", encoding="utf-8") as f:
        json.dump(args_by_goal, f, indent=2, ensure_ascii=False)

    print(f"Saved:\n - Flat arguments: {flat_txt_path}\n - Grouped by goal: {dict_txt_path}")
    return flat_txt_path, dict_txt_path


def create_relationship_csvs(path_by_goal, output_dir, model_name, prefix):
    # 1. Load arguments by goal
    with open(path_by_goal, "r", encoding="utf-8") as f:
        args_by_goal = json.load(f)

    os.makedirs(output_dir, exist_ok=True)

    # 2. Map args to unique IDs
    id_map = {}
    for goal, args in args_by_goal.items():
        for i, arg in enumerate(args):
            id_map[(goal, i)] = f"{goal}_{i}"

    intra_rows = []
    cross_rows = []

    # 3. Intra-goal relationships
    for goal, args in args_by_goal.items():
        for i, j in itertools.combinations(range(len(args)), 2):
            arg1, arg2 = args[i], args[j]
            id1, id2 = id_map[(goal, i)], id_map[(goal, j)]
            intra_rows.append([arg1, arg2, id1, id2, ""])

    # 4. Inter-goal relationships
    goals = list(args_by_goal.keys())
    for g1_idx in range(len(goals)):
        for g2_idx in range(g1_idx + 1, len(goals)):
            g1, g2 = goals[g1_idx], goals[g2_idx]
            for i, arg1 in enumerate(args_by_goal[g1]):
                for j, arg2 in enumerate(args_by_goal[g2]):
                    id1, id2 = id_map[(g1, i)], id_map[(g2, j)]
                    cross_rows.append([arg1, arg2, id1, id2, ""])

    # 5. Save CSVs
    intra_path = os.path.join(output_dir, "intra_goal" + prefix + model_name + ".csv")
    with open(intra_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["SDGarg1", "SDGarg2", "id_arg1", "id_arg2", "rel"])
        writer.writerows(intra_rows)

    cross_path = os.path.join(output_dir, "cross_goal" + prefix + model_name + ".csv")
    with open(cross_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["SDGarg1", "SDGarg2", "id_arg1", "id_arg2", "rel"])
        writer.writerows(cross_rows)

    print(f"Relationships intra-goal: {len(intra_rows)}")
    print(f"Relationships cross-goal: {len(cross_rows)}")

    return intra_path, cross_path

## GLOBAL SDG 2023 report

### Relevant sections to extract text from the Full report


| Section Title                                      | Pages  |
| -------------------------------------------------- | ------ |
| 1\_Executive Summary                               | 2      |
| 2\_How to Achieve the SDGs: The SDSN Framework     | 20     |
| 3\_The SDG Index and Dashboards                    | 6      |
| 4\_Government Efforts and Commitments for the SDGs | 12     |
| 5\_Lessons Learned and Next Steps                  | 13     |
| **Total**                                          | **53** |

### Qwen2.5-3b

In [ ]:
path_extracted_data = "Data\\Extracted Arguments No Keywords (all text)\\"
path_output = "Data\\Processed Arguments No Keywords\\"
path_output_stats = "Data\\Processed Arguments No Keywords\\Stats\\"
path_output_txt = "Data\\Processed Arguments No Keywords\\Args\\"
path_output_rels = "Data\\Relationships No Keywords\\"
prefix = 'GLOBAL_SGD2023_'
model_name="qwen2.5-3b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

print(f'Stats by SDG for {model_name} in document {prefix}:')
display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

Stats by SDG for qwen2.5-3b in document GLOBAL_SGD2023_:

,prefix,model,ods,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,0,53,42,32,0,10
1,GLOBAL SGD2023,qwen2.5-3b,1,53,21,9,0,12
2,GLOBAL SGD2023,qwen2.5-3b,2,53,14,2,0,12
3,GLOBAL SGD2023,qwen2.5-3b,3,53,17,12,0,5
4,GLOBAL SGD2023,qwen2.5-3b,4,53,16,5,0,11
5,GLOBAL SGD2023,qwen2.5-3b,5,53,10,2,0,8
6,GLOBAL SGD2023,qwen2.5-3b,6,53,11,7,0,4
7,GLOBAL SGD2023,qwen2.5-3b,7,53,15,10,0,5
8,GLOBAL SGD2023,qwen2.5-3b,8,53,12,9,0,3
9,GLOBAL SGD2023,qwen2.5-3b,9,53,7,4,0,3
10,GLOBAL SGD2023,qwen2.5-3b,10,53,19,13,0,6
11,GLOBAL SGD2023,qwen2.5-3b,11,53,10,8,0,2
12,GLOBAL SGD2023,qwen2.5-3b,12,53,11,10,0,1
13,GLOBAL SGD2023,qwen2.5-3b,13,53,10,9,0,1
14,GLOBAL SGD2023,qwen2.5-3b,14,53,4,3,0,1
15,GLOBAL SGD2023,qwen2.5-3b,15,53,1,1,0,0
16,GLOBAL SGD2023,qwen2.5-3b,16,53,14,10,0,4
17,GLOBAL SGD2023,qwen2.5-3b,17,53,17,15,0,2

Stats overall for qwen2.5-3b in document GLOBAL_SGD2023_:

Updated overall summary:

,prefix,model,ods_max,pages_max,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,17,53,251,161,0,90

In [41]:
path_output_rels = "Data\\Relationships No Keywords\\"
create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

Relationships intra-goal: 1058
Relationships cross-goal: 11822

('Data\\Relationships No Keywords\\intra_goalGLOBAL_SGD2023_qwen2.5-3b.csv',
 'Data\\Relationships No Keywords\\cross_goalGLOBAL_SGD2023_qwen2.5-3b.csv')

### Gemma3 4B

In [ ]:
path_extracted_data = "Data\\Extracted Arguments No Keywords (all text)\\"
path_output = "Data\\Processed Arguments No Keywords\\"
path_output_stats = "Data\\Processed Arguments No Keywords\\Stats\\"
path_output_rels = "Data\\Relationships No Keywords\\"
prefix = 'GLOBAL_SGD2023_'
model_name="gemma3-4b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')0

display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

[ODS 0 | page 7] Argument candidate:
  At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.

[ODS 0 | page 7] Argument candidate:
  None of their objectives are beyond our reach.

[ODS 0 | page 7] Argument candidate:
  The SDGs are still achievable.

[ODS 0 | page 7] Argument candidate:
  It is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.

[ODS 0 | page 7] Argument candidate:
  To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.

[ODS 0 | page 7] Argument candidate:
  The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 7] Argument candidate:
  Greatly increase funding to national and subnational governments and private businesses, especially in LICs and LMICs, to carry out needed SDG investments.

[ODS 0 | page 7] Argument candidate:
  Revise the credit rating system and debt sustainability metrics to facilitate long-term sustainable development.

[ODS 0 | page 7] Argument candidate:
  Revise liquidity structures for LICs and LMICs, especially regarding sovereign debts, to forestall self-fulfilling banking and balance-of-payments crises

[ODS 0 | page 7] Argument candidate:
  Create ambitious, internationally-agreed upon criteria for sustainable finance that are mandatory for all public financial institutions.

[ODS 0 | page 7] Argument candidate:
  Align private business investment flows with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 7] Argument candidate:
  Reform current institutional frameworks and develop new mechanisms to improve the quality and speed of deployment of international cooperation, and monitor progress in an open and timely manner.

[ODS 0 | page 7] Argument candidate:
  All countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national SDG strategies and commit to strengthening multilateralism.

[ODS 0 | page 7] Argument candidate:
  National governments must ensure both domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation – by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 7] Argument candidate:
  Achieving the SDGs requires global cooperation guided by the United Nations Charter.

[ODS 0 | page 8] Argument candidate:
  Further investment is needed in statistical capacity and data literacy to support long-term pathways for key SDG transformations.

[ODS 0 | page 8] Argument candidate:
  At the halfway mark to 2030, there remains a great deal of work to be done to improve the data and methods underlying the SDG indicator framework.

[ODS 0 | page 8] Argument candidate:
  investing in statistical capacity, science, and data literacy are important priorities for achieving the SDGs.

[ODS 0 | page 8] Argument candidate:
  All UN Member States and UN agencies can count on the continued efforts and energies of the SDSN around the world to support all governments, businesses, and civil society in embracing and aligning with the SDGs

[ODS 0 | page 13] Argument candidate:
  UN Member States should adopt an SDG Stimulus, to close the massive financing gap faced by many developing economies.

[ODS 0 | page 13] Argument candidate:
  Increased funding from the multilateral development banks (MDBs) and public development banks (PDBs) to low- and middle-income countries, linked to investments in the SDGs;

[ODS 0 | page 13] Argument candidate:
  Enhancement of relief for countries facing debt distress;

[ODS 0 | page 13] Argument candidate:
  Expansion of liquidity by the International Monetary Fund (IMF) and major central banks;

[ODS 0 | page 13] Argument candidate:
  Empowerment and expansion of the specialized global funds;

[ODS 0 | page 13] Argument candidate:
  Expansion of private philanthropy with a focus on ultra-high-net-worth individuals.

[ODS 0 | page 13] Argument candidate:
  UN Member States must endorse a deep and overdue reform of the global financial architecture.

[ODS 0 | page 13] Argument candidate:
  Greatly increased funding for national and subnational governments and private businesses in the emerging economies, especially the low-income countries (LICs) and lower-middle-income countries (LMICs), to carry out needed SDG actions;

[ODS 0 | page 13] Argument candidate:
  Revision of the credit-rating system and debt-sustainability metrics to facilitate long-term sustainable development;

[ODS 0 | page 13] Argument candidate:
  Revision of the liquidity structures for LICs and LMICs, especially regarding sovereign debt, to forestall self-fulfilling banking and balance-of-payments crises;

[ODS 0 | page 13] Argument candidate:
  Creation of ambitious, internationally-agreed criteria for sustainable finance that are mandatory for all public financial institutions in high-income countries (HICs), middle-income countries (MICs), and LICs alike.

[ODS 0 | page 13] Argument candidate:
  Alignment of private business investment flows in all countries with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 13] Argument candidate:
  A reform of current institutional frameworks and development of new and innovative mechanisms to improve the quality and speed of deployment of international cooperation, and the monitoring of progress in an open and timely manner.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of ‘leave no one behind’.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should present, at regular intervals, their national SDG frameworks in the form of Voluntary National Reviews (VNRs).

[ODS 0 | page 14] Argument candidate:
  All UN Member States should recommit to peaceful cooperation, in the service of the SDGs and all other multilateral agreements.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should commit to accelerating SDG progress to 2030, and to setting even more ambitious SDG targets to 2050, incorporating the recent Kunming-Montreal Biodiversity Framework and the High Seas Treaty.

[ODS 0 | page 15] Argument candidate:
  national governments on all continents have fallen short in integrating the SDGs into national policies and public investments

[ODS 0 | page 15] Argument candidate:
  they are grounded in the Universal Declaration of Human Rights, which celebrates its 75th anniversary this year

[ODS 0 | page 15] Argument candidate:
  that "All human beings are born free and equal in dignity and rights … and should act towards one another in a spirit of brotherhood"

[ODS 0 | page 15] Argument candidate:
  that "it is essential to promote the development of friendly relations between nations"

[ODS 0 | page 15] Argument candidate:
  social justice and sustainable development require the full realization of the rights of all people

[ODS 0 | page 15] Argument candidate:
  includes equality of opportunities for girls and women (SDG 5)

[ODS 0 | page 15] Argument candidate:
  respect for the rights and voice of Indigenous peoples around the world

[ODS 0 | page 15] Argument candidate:
  a much larger role for young people, who will face the consequences of our (in)actions throughout the 21st century

[ODS 0 | page 15] Argument candidate:
  They are not only a public policy framework; they are an ethical imperative

[ODS 0 | page 15] Argument candidate:
  Members of the SDSN Leadership Council offer the following assessments and recommendations to the UN Member States, the United Nations Agencies, international finance institutions, business, and civil society, based on more than a decade of research, measurement, advising, and partnerships across the world

[ODS 0 | page 16] Argument candidate:
  Dire shortfalls in meeting the SDGs to reaching a disastrous 2.8°C warming by 2100.

[ODS 0 | page 16] Argument candidate:
  Current Nationally Determined Contribution (NDC) targets, if implemented, would still lead to around 2.4°C warming by 2100.

[ODS 0 | page 16] Argument candidate:
  Biodiversity targets (SDG 15 and targets agreed under the CBD) are also at grave risk.

[ODS 0 | page 16] Argument candidate:
  Global resource consumption assessments for rare earth elements are critical.

[ODS 0 | page 16] Argument candidate:
  Ocean goods and services (SDG 14 and the High Seas Treaty) are at severe risk due to full- to over-exploitation

[ODS 0 | page 17] Argument candidate:
  Providing quality education (SDG 4) for all children is perhaps the single most important key to achieving sustainable development in the long term.

[ODS 0 | page 17] Argument candidate:
  The UN General Assembly’s Transforming Education Summit held in September 2022 was a critical meeting to spur national and global efforts to transform education to give all people the skills and knowledge to end poverty, protect the environment, and build peaceful and inclusive societies.

[ODS 0 | page 17] Argument candidate:
  And yet, the truth remains that hundreds of millions of children are either out of school entirely or receiving such an under-funded and under-resourced education that they are failing to achieve basic literacy and numeracy even after several years of education.

[ODS 0 | page 18] Argument candidate:
  The latest scientific assessments indicate that six of the nine planetary boundaries have been breached.

[ODS 0 | page 18] Argument candidate:
  Scientists have identified a large number of extremely dangerous potential tipping points, with linkages and dependencies across the different planetary boundaries.

[ODS 0 | page 18] Argument candidate:
  Human-induced global warming could hit several tipping points that may in turn lead to further feedbacks (amplifications) of the warming.

[ODS 0 | page 19] Argument candidate:
  Unless the SDGs are actively pursued, geophysical tipping points combined with technological disruptions could ignite disastrous social conflicts within and between nations.

[ODS 0 | page 19] Argument candidate:
  We firmly believe that international cooperation together with the achievement of the SDGs is the best preventative to this dire and growing risk, and represent an opportunity to create positive social tipping points: for example, through equal access to high-quality education (SDG 4), and by fighting all forms of inequalities, including income and wealth inequalities (SDG 10).

[ODS 0 | page 19] Argument candidate:
  Although all governments are in principle committed to economic justice as enshrined in the Universal Declaration of Human Rights, and to the SDG tenets of ‘leave no one behind’ and ‘reach the furthest behind first’, too few are living up to these commitments, especially as powerful groups block adequate public support for weaker groups.

[ODS 0 | page 19] Argument candidate:
  The report’s recommendations include calling for more racially-disaggregated SDG indicators and for dialogue with stakeholders on how to use these indicators to better allocate resources and prioritize the inclusion of marginalized peoples.

[ODS 0 | page 20] Argument candidate:
  the SDGs are woefully underfunded at home and internationally

[ODS 0 | page 20] Argument candidate:
  None of their objectives are beyond our reach

[ODS 0 | page 20] Argument candidate:
  the world must devote an increased portion of current output to building up sustainable capital assets for the future

[ODS 0 | page 20] Argument candidate:
  the world must both shift its current investment patterns and increase the overall investment flow in order to build the future we want

[ODS 0 | page 20] Argument candidate:
  Human capital: The skills and health of a productive citizenry, supported by universal health access and coverage, quality education, shared data and knowledge, promotion of a culture of peace and non-violence, global citizenship, and the appreciation of cultural diversity

[ODS 0 | page 20] Argument candidate:
  Natural capital: The capacity and healthy functioning of ecosystems, to be protected by ending human-induced climate change, protecting biodiversity, sustainably managing freshwater resources, and eliminating toxic pollutants

[ODS 0 | page 21] Argument candidate:
  To achieve the SDGs, the world must invest boldly, amply, and consistently in all eight kinds of capital.

[ODS 0 | page 21] Argument candidate:
  Governments too must take the lead in protecting natural capital, while civil society especially must promote social and cultural capital, including mutual understanding across cultures and nations.

[ODS 0 | page 21] Argument candidate:
  Crucially, national government must also work with subnational governments to implement the SDG agenda at the local level, including sustainable urban infrastructure, delivery of social services, and ensuring safe communities.

[ODS 0 | page 21] Argument candidate:
  Virtually all governments of the world have embraced the SDGs in principle. 188 of 193 UN Member States have submitted VNRs for comment by the other nations.

[ODS 0 | page 21] Argument candidate:
  Only five countries, notably the United States, Haiti, Myanmar, South Sudan, and Yemen, have never presented VNRs.

[ODS 0 | page 22] Argument candidate:
  The greatest responsibility for achieving the SDGs and safeguarding the planetary boundaries lies with the G20 members.

[ODS 0 | page 22] Argument candidate:
  With the 2022 Inflation Reduction Act, the Biden government announced its intention to reduce carbon emissions by roughly 40 percent from 2005 levels by 2030, although there are growing concerns that outcomes will lag behind these goals, due in part to the legislation’s lack of an agreed national financing strategy other than tax credits.

[ODS 0 | page 22] Argument candidate:
  The European Union – the world’s second-largest economy and its major lignite producer – has produced the European Green Deal (EGD), which is exemplary in many regards.

[ODS 0 | page 22] Argument candidate:
  Many EU member states demonstrate a high or moderate SDG commitment.

[ODS 0 | page 22] Argument candidate:
  The EGD embraces an EU-wide set of goals, timelines to 2050, and financing strategies across major dimensions of the SDGs: energy decarbonization, climate resilience, circular economy (to cut pollution), sustainable agriculture (the ‘farm-to-fork’ strategy), digital access, and innovation.

[ODS 0 | page 22] Argument candidate:
  The European Regional Development Fund, which provides the EU cohesion funds, is also directed towards the EGD.

[ODS 0 | page 22] Argument candidate:
  The SDSN Framework in the context of international cooperation.

[ODS 0 | page 23] Argument candidate:
  China has reiterated its support for the SDGs, such as in greening its Belt and Road Initiative and launching the Global Development Initiative as a worldwide effort.

[ODS 0 | page 23] Argument candidate:
  At the midpoint of the 2030 Agenda, all countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national strategies, using the principles of the 2030 Agenda (transformative, integrated, inclusive, leaving no one behind) as a yardstick.

[ODS 0 | page 23] Argument candidate:
  Four basic failures stand out: First, implementation is largely left to the national level and on a voluntary basis, without effective multilateral enforcement mechanisms in place.

[ODS 0 | page 23] Argument candidate:
  Developed countries are not being held to account, neither for their adverse spillovers, nor for ensuring adequate flows of financing for sustainable development.

[ODS 0 | page 23] Argument candidate:
  There are no assessments or recommendations by the respective secretariats or decision-making bodies on the adequacy or further enhancement of national implementation, let alone measures of enforcement.

[ODS 0 | page 24] Argument candidate:
  Greatly increase funding to national and subnational governments and private businesses in the emerging economies, especially the LICs and LMICs, to carry out the needed investments.

[ODS 0 | page 24] Argument candidate:
  Revise liquidity structures for LICs,LMICs, and SIDS, especially regarding sovereign debts, to forestall self-fulfilling banking and balance-of-payments crises.

[ODS 0 | page 24] Argument candidate:
  Create ambitious and internationally-agreed upon criteria for sustainable finance that are mandatory for all public financial institutions in HICs, MICs, and LICs alike.

[ODS 0 | page 24] Argument candidate:
  Align private business investment flows in all countries with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 24] Argument candidate:
  Reform current institutional frameworks and develop new, innovative mechanisms to improve the quality and speed of deployment of international cooperation, and monitor progress in an open and timely manner.

[ODS 0 | page 25] Argument candidate:
  Overhauling global governance mechanisms and the global financial architecture is fundamental to unlocking needed investments for sustainable development and ending non-sustainable practices.

[ODS 0 | page 25] Argument candidate:
  The SDGs call for lasting, long-term, directed change.

[ODS 0 | page 25] Argument candidate:
  For governments to combine the objectives of economic development, social inclusion, transparency, energy decarbonization, climate adaptation, water resources and sanitation, biodiversity conservation, digital access, gender equality, circular economy, over-harvesting, universal education, is daunting.

[ODS 0 | page 26] Argument candidate:
  Long-term investment plans are essential for national success in meeting the SDGs.

[ODS 0 | page 26] Argument candidate:
  SDSN has recommended six inter-related long-term transformations: Universal quality education and innovation-based economy, Universal health access and coverage, Zero-carbon energy systems, Sustainable ecosystems, sustainable agriculture, and climate resilience, Sustainable cities, Transformation to universal digital access and services

[ODS 0 | page 26] Argument candidate:
  None can be solved by the private sector alone; indeed, governments will have to take the lead to design policy and financial frameworks within which business can profitably invest and innovate.

[ODS 0 | page 26] Argument candidate:
  The Sustainable Development Report 2023 identifies five levers to be deployed to bring about the necessary transformations: governance, economy and finance, individual and collective action, science and technology, and capacity building.

[ODS 0 | page 26] Argument candidate:
  Planning for the long term, however, illuminates the global financial architecture’s Achilles heel. While the high-income countries (HICs) and upper-middle income countries (UMICs) can and should, in principle, finance these transformations via a combination of budget outlays, public-sector borrowing, and private financing (equity and debt), this is surely not true of the low-Income countries (LICs) and the lower middle-income countries

[ODS 0 | page 27] Argument candidate:
  Increased funding from the Multilateral Development Banks (MDBs) and Public Development Banks (PDBs) to developing countries, linked to investments in the SDGs

[ODS 0 | page 27] Argument candidate:
  an additional US$500 billion per year by 2025 of SDG finance

[ODS 0 | page 27] Argument candidate:

,prefix,model,ods,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL_SGD2023_,qwen2.5-3b,0,53,42,32,0,10
1,GLOBAL_SGD2023_,qwen2.5-3b,1,53,21,9,0,12
2,GLOBAL_SGD2023_,qwen2.5-3b,2,53,14,2,0,12
3,GLOBAL_SGD2023_,qwen2.5-3b,3,53,17,12,0,5
4,GLOBAL_SGD2023_,qwen2.5-3b,4,53,16,5,0,11
5,GLOBAL_SGD2023_,qwen2.5-3b,5,53,10,2,0,8
6,GLOBAL_SGD2023_,qwen2.5-3b,6,53,11,7,0,4
7,GLOBAL_SGD2023_,qwen2.5-3b,7,53,15,10,0,5
8,GLOBAL_SGD2023_,qwen2.5-3b,8,53,12,9,0,3
9,GLOBAL_SGD2023_,qwen2.5-3b,9,53,7,4,0,3
10,GLOBAL_SGD2023_,qwen2.5-3b,10,53,19,13,0,6
11,GLOBAL_SGD2023_,qwen2.5-3b,11,53,10,8,0,2
12,GLOBAL_SGD2023_,qwen2.5-3b,12,53,11,10,0,1
13,GLOBAL_SGD2023_,qwen2.5-3b,13,53,10,9,0,1
14,GLOBAL_SGD2023_,qwen2.5-3b,14,53,4,3,0,1
15,GLOBAL_SGD2023_,qwen2.5-3b,15,53,1,1,0,0
16,GLOBAL_SGD2023_,qwen2.5-3b,16,53,14,10,0,4
17,GLOBAL_SGD2023_,qwen2.5-3b,17,53,17,15,0,2
18,GLOBAL SGD2023,gemma3-4b,0,53,304,167,1,136
19,GLOBAL SGD2023,gemma3-4b,1,53,199,48,0,151
20,GLOBAL SGD2023,gemma3-4b,2,53,248,27,0,221
21,GLOBAL SGD2023,gemma3-4b,3,53,228,36,0,192
22,GLOBAL SGD2023,gemma3-4b,4,53,229,27,1,201
23,GLOBAL SGD2023,gemma3-4b,5,53,181,23,0,158
24,GLOBAL SGD2023,gemma3-4b,6,53,221,26,0,195
25,GLOBAL SGD2023,gemma3-4b,7,53,246,26,0,220
26,GLOBAL SGD2023,gemma3-4b,8,53,252,36,0,216
27,GLOBAL SGD2023,gemma3-4b,9,53,241,37,0,204
28,GLOBAL SGD2023,gemma3-4b,10,53,229,46,0,183
29,GLOBAL SGD2023,gemma3-4b,11,53,247,19,0,228
30,GLOBAL SGD2023,gemma3-4b,12,53,239,24,0,215
31,GLOBAL SGD2023,gemma3-4b,13,53,168,36,0,132
32,GLOBAL SGD2023,gemma3-4b,14,53,221,21,0,200
33,GLOBAL SGD2023,gemma3-4b,15,53,182,19,0,163
34,GLOBAL SGD2023,gemma3-4b,16,53,220,41,0,179
35,GLOBAL SGD2023,gemma3-4b,17,53,238,47,0,191

Stats overall for gemma3-4b in document GLOBAL_SGD2023_:

Updated overall summary:

,prefix,model,ods_max,pages_max,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,17,53,251,161,0,90
1,GLOBAL_SGD2023_,qwen2.5-3b,17,53,4344,867,2,3475

In [46]:
save_overall_summary(res, path_output_stats, model_name)

Updated overall summary:

,prefix,model,ods_max,pages_max,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,17,53,251,161,0,90
1,GLOBAL SGD2023,gemma3-4b,17,53,4093,706,2,3385

### Gemma3 27B

In [ ]:
path_extracted_data = "Data\\Extracted Arguments No Keywords (all text)\\"
path_output = "Data\\Processed Arguments No Keywords\\"
path_output_stats = "Data\\Processed Arguments No Keywords\\Stats\\"
path_output_rels = "Data\\Relationships No Keywords\\"
prefix = 'GLOBAL_SGD2023_'
model_name="gemma3-27b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')
display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats)

### Llama 3.3 70B

In [ ]:
path_extracted_data = "Data\\Extracted Arguments No Keywords (all text)\\"
path_output = "Data\\Processed Arguments No Keywords\\"
path_output_stats = "Data\\Processed Arguments No Keywords\\Stats\\"
path_output_rels = "Data\\Relationships No Keywords\\"
prefix = 'GLOBAL_SGD2023_'
model_name="llama3.3-70b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')
display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats)

### Deepseek r1 70B

In [ ]:
path_extracted_data = "Data\\Extracted Arguments No Keywords (all text)\\"
path_output = "Data\\Processed Arguments No Keywords\\"
path_output_stats = "Data\\Processed Arguments No Keywords\\Stats\\"
path_output_rels = "Data\\Relationships No Keywords\\"
prefix = 'GLOBAL_SGD2023_'
model_name="deepseek-r1-70b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')
display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats)

## GLOBAL SDG 2025 report

| Section                                                | Pages  |
| ------------------------------------------------------ | ------ |
| 1\_Executive Summary                                   | 2      |
| 2\_Financing for Development                           | 9      |
| 3\_The SDG Index and Dashboards                        | 6      |
| 4\_Commitment to the SDGs and UN-Based Multilateralism | 10     |
| **Total**                                              | **27** |