# TFM: Análisis de Políticas de Sostenibilidad mediante técnicas de Argumentacion Computacional

## Clasificación de relaciones con raruidol/ArgumentMining-EN-ARI-AIF-RoBERTa_L

Model page: https://huggingface.co/raruidol/ArgumentMining-EN-ARI-AIF-RoBERTa_L

# No keywords

In [1]:
import os
import re
import math
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import gc

process_rel_path = r"/kaggle/working/TFM/Data/Relationships No Keywords"
hf_model_repo = "raruidol/ArgumentMining-EN-ARI-AIF-RoBERTa_L"
model_name = "robertaL"  

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tokenizer = AutoTokenizer.from_pretrained(hf_model_repo)
model = AutoModelForSequenceClassification.from_pretrained(hf_model_repo).to(device)
model.eval()

tokenizer_config.json:   0%|          | 0.00/381 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/945 [00:00<?, ?B/s]

2025-08-24 11:27:40.187663: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1756034860.508187      36 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1756034860.598141      36 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

pytorch_model.bin:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 1024, padding_idx=1)
      (position_embeddings): Embedding(514, 1024, padding_idx=1)
      (token_type_embeddings): Embedding(1, 1024)
      (LayerNorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-23): 24 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSdpaSelfAttention(
              (query): Linear(in_features=1024, out_features=1024, bias=True)
              (key): Linear(in_features=1024, out_features=1024, bias=True)
              (value): Linear(in_features=1024, out_features=1024, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=1024, out_features=1024, bias=True)
              (LayerNorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): RobertaIntermediate(
            (dense): Linear(in_features=1024, out_features=4096, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): RobertaOutput(
            (dense): Linear(in_features=4096, out_features=1024, bias=True)
            (LayerNorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
  )
  (classifier): RobertaClassificationHead(
    (dense): Linear(in_features=1024, out_features=1024, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (out_proj): Linear(in_features=1024, out_features=4, bias=True)
  )
)

In [2]:
!git clone https://github.com/camipalo/TFM.git

Cloning into 'TFM'...
remote: Enumerating objects: 2147, done.
remote: Counting objects: 100% (227/227), done.
remote: Compressing objects: 100% (115/115), done.
remote: Total 2147 (delta 176), reused 162 (delta 112), pack-reused 1920 (from 1)
Receiving objects: 100% (2147/2147), 69.26 MiB | 14.79 MiB/s, done.
Resolving deltas: 100% (1815/1815), done.
Updating files: 100% (1008/1008), done.

In [3]:
# --- compute max token length across all input pairs ---
def compute_max_length(input_dir, prefix_substring, tokenizer, safety_limit=512):
    max_len = 0
    files = [f for f in os.listdir(input_dir) if f.endswith(".csv") and prefix_substring in f]
    for fn in files:
        path = os.path.join(input_dir, fn)
        df = pd.read_csv(path)
        if "SDGarg1" not in df.columns or "SDGarg2" not in df.columns:
            continue
        for a, b in zip(df["SDGarg1"], df["SDGarg2"]):
            a = str(a) if pd.notna(a) else ""
            b = str(b) if pd.notna(b) else ""
            tokens = tokenizer(a, b, truncation=False, padding=False)["input_ids"]
            max_len = max(max_len, len(tokens))
    return min(max_len, safety_limit)

### Labels
id2label = getattr(model.config, "id2label", None) or {0: "Inference", 1: "Conflict", 2: "Rephrase"}
id2label = {int(k): str(v) for k, v in id2label.items()}

# Map model labels -> desired labels
LABEL_MAP = {
    "inference": "Support",
    "conflict": "Attack",
    "rephrase": "Rephrase",
    "none": "No Relationship",
    "0": "Support",
    "1": "Attack",
    "2": "Rephrase",
    "-1": "No Relationship",
}

VALID_OUT = {"Support", "Attack", "Rephrase", "No Relationship"}

def preprocess_text(s: str) -> str:
    if not isinstance(s, str):
        return ""
    s = s.strip()
    s = re.sub(r"\s+", " ", s)
    return s

@torch.no_grad()
def predict_labels(pairs):
    if not pairs:
        return []
    enc = tokenizer(
        [preprocess_text(a) for a, _ in pairs],
        [preprocess_text(b) for _, b in pairs],
        truncation=True, padding=True, max_length=MAX_LENGTH, return_tensors="pt"
    ).to(device)
    logits = model(**enc).logits  # [batch, num_labels]
    preds = torch.argmax(logits, dim=-1).tolist()
    raw = [id2label.get(int(p), "none") for p in preds]
    mapped = []
    for r in raw:
        key = str(r).strip().lower()
        mapped.append(LABEL_MAP.get(key, "No Relationship"))
    return mapped

def free_cuda():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        
def classify_relationships_hf(input_dir: str, prefix_substring: str):
    files = [f for f in os.listdir(input_dir) if f.endswith(".csv") and prefix_substring in f]
    if not files:
        print(f"No CSVs found in '{input_dir}' containing '{prefix_substring}'.")
        return

    for fn in files:
        path = os.path.join(input_dir, fn)
        print(f"\nProcessing: {path}")
        df = pd.read_csv(path)

        if "SDGarg1" not in df.columns or "SDGarg2" not in df.columns:
            print(f"  Skipped (missing SDGarg1/SDGarg2): {fn}")
            continue

        # init column
        df[rel_col] = ""

        n = len(df)
        total_done = 0
        first_examples = []

        batches = math.ceil(n / BATCH_SIZE)
        for bi in range(batches):
            s = bi * BATCH_SIZE
            e = min((bi + 1) * BATCH_SIZE, n)
            chunk = df.iloc[s:e]
            pairs = list(zip(chunk["SDGarg1"].astype(str).tolist(),
                             chunk["SDGarg2"].astype(str).tolist()))
            try:
                labels = predict_labels(pairs)
            except Exception as ex:
                print(f"  Batch {bi+1}/{batches} error: {ex}. Marking 'No Relationship'.")
                labels = ["No Relationship"] * len(pairs)

            df.loc[chunk.index, rel_col] = labels

            # collect first 5 examples
            for (a1, a2), lab in zip(pairs, labels):
                if len(first_examples) < 5:
                    first_examples.append((a1, a2, lab))
                elif len(first_examples) == 5:
                    print("Check first 5 predictions labels:\n")
                    for a1, a2, lab in first_examples:
                        print(f"- Arg1: {a1[:]} \n-Arg2: {a2[:]} \nLabel: {lab}\n\n")
                    first_examples.append((a1, a2, lab))

            total_done += len(pairs)
            if total_done % 50 < BATCH_SIZE:  
                print(f"  Progress: {total_done}/{n} relations classified...")

        # handle missing args
        mask_nan = df["SDGarg1"].isna() | df["SDGarg2"].isna()
        df.loc[mask_nan, rel_col] = "No Relationship"

        # Ensure valid set
        bad = ~df[rel_col].isin(VALID_OUT)
        if bad.any():
            df.loc[bad, rel_col] = "No Relationship"

        df.to_csv(path, index=False, encoding="utf-8")
        free_cuda()
        print(f"Saved: {path}")
        return df

## GLOBAL SDG 2023

#### Qwen2.5 3B extraction

In [4]:
prefix = "intra_goalGLOBAL_SGD2023_qwen2.5-3b"   
rel_col = f"rel_{model_name}"
BATCH_SIZE = 250
MAX_LENGTH = compute_max_length(process_rel_path, prefix, tokenizer)
print(f"Using MAX_LENGTH = {MAX_LENGTH}")

args_classified = classify_relationships_hf(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_robertaL"].value_counts()

Using MAX_LENGTH = 171

Processing: /kaggle/working/TFM/Data/Relationships No Keywords/intra_goalGLOBAL_SGD2023_qwen2.5-3b.csv
Check first 5 predictions labels:

- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
-Arg2: According to major international studies, few teenagers can differentiate between a fact and an opinion.
Label: No Relationship


- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
-Arg2: As the world’s nations prepare to meet in September to review the progress the world has made so far towards achieving the SDGs, at the midpoint of the 2030 Agenda, SDSN emphasizes six areas for immediate action.
Label: Support


- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
-Arg2: All UN Member States should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of 'leave no one behind'.
Label: Support


- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
-Arg2: The SDGs are not only a public policy framework; they are an ethical imperative. They are grounded in the Universal Declaration of Human Rights, which celebrates its 75th anniversary this year.
Label: Support


- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
-Arg2: The current loss of species rate is 1,000–10,000 times more than the natural extinction rate.
Label: No Relationship


  Progress: 250/1058 relations classified...
  Progress: 500/1058 relations classified...
  Progress: 750/1058 relations classified...
  Progress: 1000/1058 relations classified...
  Progress: 1058/1058 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships No Keywords/intra_goalGLOBAL_SGD2023_qwen2.5-3b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_llama,rel_robertaL
639,Zero-carbon energy systems: the transition by ...,Use of unilateral coercive measures,7_0,7_9,NaN,No Relationship,No Relationship
910,Grave dangers of social tipping points,"The GFA includes multilateral institutions, na...",16_0,16_3,NaN,No Relationship,No Relationship
142,The SDGs are not only a public policy framewor...,Rich European countries top the overall SDG In...,0_4,0_29,NaN,No Relationship,Support
736,And global cooperation has ebbed as geopolitic...,Governments are only now learning how to desig...,10_1,10_8,NaN,No Relationship,No Relationship
976,"UN Member States should adopt an SDG Stimulus,...",SDG 17 (Partnerships for the Goals) calls for ...,17_1,17_11,NaN,Support,Rephrase

rel_robertaL
Support            616
No Relationship    378
Rephrase            47
Attack              17
Name: count, dtype: int64

In [5]:
prefix = "cross_goalGLOBAL_SGD2023_qwen2.5-3b"   
rel_col = f"rel_{model_name}"
BATCH_SIZE = 250
MAX_LENGTH = compute_max_length(process_rel_path, prefix, tokenizer)
print(f"Using MAX_LENGTH = {MAX_LENGTH}")

args_classified = classify_relationships_hf(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_robertaL"].value_counts()

Using MAX_LENGTH = 181

Processing: /kaggle/working/TFM/Data/Relationships No Keywords/cross_goalGLOBAL_SGD2023_qwen2.5-3b.csv
Check first 5 predictions labels:

- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
-Arg2: only limited progress is being made on the environmental and biodiversity goals, including SDG 12 (Responsible Consumption and Production), SDG 13 (Climate Action), SDG 14 (Life Below Water), and SDG 15 (Life on Land)
Label: Support


- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
-Arg2: And global cooperation has ebbed as geopolitical tensions have risen.
Label: No Relationship


- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
-Arg2: The interconnected environmental, social, and health challenges can be characterized as a planetary health crisis, caused by human activities such as industrialization, urbanization, deforestation, and the burning of fossil fuels.
Label: No Relationship


- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
-Arg2: 12. Sachs JD, Schmidt-Traub G., 2020. Speaking truth to power about the SDGs, Nature. https://www.nature.com/articles/d41586-020-02373-7
Label: Support


- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
-Arg2: Deep, chronic, and crippling under-investment in virtually all low-income countries (LICs) and lower-middle-income countries (LMICs). In 2022, Investment per person in the LICs averaged a meagre US$175 per person, compared with US$11,535 per person in the HICs. (Table 1.1)
Label: Support


  Progress: 250/11822 relations classified...
  Progress: 500/11822 relations classified...
  Progress: 750/11822 relations classified...
  Progress: 1000/11822 relations classified...
  Progress: 1250/11822 relations classified...
  Progress: 1500/11822 relations classified...
  Progress: 1750/11822 relations classified...
  Progress: 2000/11822 relations classified...
  Progress: 2250/11822 relations classified...
  Progress: 2500/11822 relations classified...
  Progress: 2750/11822 relations classified...
  Progress: 3000/11822 relations classified...
  Progress: 3250/11822 relations classified...
  Progress: 3500/11822 relations classified...
  Progress: 3750/11822 relations classified...
  Progress: 4000/11822 relations classified...
  Progress: 4250/11822 relations classified...
  Progress: 4500/11822 relations classified...
  Progress: 4750/11822 relations classified...
  Progress: 5000/11822 relations classified...
  Progress: 5250/11822 relations classified...
  Progress: 5500/11822 relations classified...
  Progress: 5750/11822 relations classified...
  Progress: 6000/11822 relations classified...
  Progress: 6250/11822 relations classified...
  Progress: 6500/11822 relations classified...
  Progress: 6750/11822 relations classified...
  Progress: 7000/11822 relations classified...
  Progress: 7250/11822 relations classified...
  Progress: 7500/11822 relations classified...
  Progress: 7750/11822 relations classified...
  Progress: 8000/11822 relations classified...
  Progress: 8250/11822 relations classified...
  Progress: 8500/11822 relations classified...
  Progress: 8750/11822 relations classified...
  Progress: 9000/11822 relations classified...
  Progress: 9250/11822 relations classified...
  Progress: 9500/11822 relations classified...
  Progress: 9750/11822 relations classified...
  Progress: 10000/11822 relations classified...
  Progress: 10250/11822 relations classified...
  Progress: 10500/11822 relations classified...
  Progress: 10750/11822 relations classified...
  Progress: 11000/11822 relations classified...
  Progress: 11250/11822 relations classified...
  Progress: 11500/11822 relations classified...
  Progress: 11750/11822 relations classified...
  Progress: 11822/11822 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships No Keywords/cross_goalGLOBAL_SGD2023_qwen2.5-3b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_llama,rel_robertaL
434,Investing in the SDGs is an investment agenda....,The SDG Index acknowledges Bhutan’s recent pro...,0_6,3_10,NaN,Support,Support
2782,47 countries have submitted a VNR this year: o...,Only limited progress is being made on the env...,0_19,12_0,NaN,No Relationship,No Relationship
3869,"For these reasons, we end our message with two...",SDG 17 (Partnerships for the Goals) calls for ...,0_14,17_11,NaN,No Relationship,No Relationship
4637,"12. Sachs JD, Schmidt-Traub G., 2020. Speaking...",the COVID-19 pandemic has had lasting impacts ...,1_3,10_11,NaN,No Relationship,No Relationship
10485,HICs tend to generate the largest negative spi...,"UN Member States should adopt an SDG Stimulus,...",10_9,17_1,NaN,Support,No Relationship

rel_robertaL
Support            5670
No Relationship    5516
Rephrase            452
Attack              184
Name: count, dtype: int64

In [6]:
pd.crosstab(
    args_classified["rel_llama"],
    args_classified["rel_robertaL"],
    margins=True,        # adds totals
    margins_name="Total" # name for totals row/col
)

rel_robertaL     Attack  No Relationship  Rephrase  Support  Total
rel_llama
Attack               96              600        51      795   1542
No Relationship      34             3934        91     1246   5305
Rephrase              0                6       118       13    137
Support              54              976       192     3616   4838
Total               184             5516       452     5670  11822

#### Gemma3 27B extraction

In [7]:
prefix = "intra_goalGLOBAL_SGD2023_gemma3-27b"   
rel_col = f"rel_{model_name}"
BATCH_SIZE = 250
MAX_LENGTH = compute_max_length(process_rel_path, prefix, tokenizer)
print(f"Using MAX_LENGTH = {MAX_LENGTH}")

args_classified = classify_relationships_hf(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_robertaL"].value_counts()

Using MAX_LENGTH = 213

Processing: /kaggle/working/TFM/Data/Relationships No Keywords/intra_goalGLOBAL_SGD2023_gemma3-27b.csv
Check first 5 predictions labels:

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: Despite this alarming development, the SDGs are still achievable.
Label: Attack


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
Label: Support


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.
Label: Support


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: National governments must ensure both domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation – by building a global governance and financial architecture that delivers the SDGs.
Label: Support


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: Achieving the SDGs requires global cooperation guided by the United Nations Charter.
Label: Attack


  Progress: 250/4188 relations classified...
  Progress: 500/4188 relations classified...
  Progress: 750/4188 relations classified...
  Progress: 1000/4188 relations classified...
  Progress: 1250/4188 relations classified...
  Progress: 1500/4188 relations classified...
  Progress: 1750/4188 relations classified...
  Progress: 2000/4188 relations classified...
  Progress: 2250/4188 relations classified...
  Progress: 2500/4188 relations classified...
  Progress: 2750/4188 relations classified...
  Progress: 3000/4188 relations classified...
  Progress: 3250/4188 relations classified...
  Progress: 3500/4188 relations classified...
  Progress: 3750/4188 relations classified...
  Progress: 4000/4188 relations classified...
  Progress: 4188/4188 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships No Keywords/intra_goalGLOBAL_SGD2023_gemma3-27b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_llama,rel_robertaL
651,"Despite significant efforts in some places, na...",Achieving the SDGs will require a transformati...,0_14,0_29,NaN,Support,Support
1386,"At the global level, averaging across countrie...",The poor are consequently languishing in poverty.,1_0,1_9,NaN,Support,Support
2464,"Global warming as of 2022 stood at 1.2°C, with...",Human-induced global warming could hit several...,13_2,13_8,NaN,Support,Support
3386,These fora are critical to encourage internati...,"There are no magic numbers, but rather a suite...",16_19,16_26,NaN,Support,Support
3746,And global cooperation has ebbed as geopolitic...,We therefore consider that promoting multilate...,17_9,17_33,NaN,Support,Support

rel_robertaL
Support            3117
No Relationship     710
Rephrase            248
Attack              113
Name: count, dtype: int64

In [8]:
prefix = "cross_goalGLOBAL_SGD2023_gemma3-27b"   
rel_col = f"rel_{model_name}"
BATCH_SIZE = 250
MAX_LENGTH = compute_max_length(process_rel_path, prefix, tokenizer)
print(f"Using MAX_LENGTH = {MAX_LENGTH}")

args_classified = classify_relationships_hf(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_robertaL"].value_counts()

Using MAX_LENGTH = 262

Processing: /kaggle/working/TFM/Data/Relationships No Keywords/cross_goalGLOBAL_SGD2023_gemma3-27b.csv
Check first 5 predictions labels:

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: At the global level, averaging across countries, not a single SDG is currently projected to be met by 2030, with the poorest countries struggling the most.
Label: Rephrase


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: As called for by United Nations Secretary-General António Guterres, the SDG Stimulus plan has five main components:
Label: Support


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: Greatly increased funding for national and subnational governments and private businesses in the emerging economies, especially the low-income countries (LICs) and lower-middle-income countries (LMICs), to carry out needed SDG actions;
Label: Support


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: According to the annual SDG Index, global achievement of the SDGs rose only slightly, from 64 percent in 2015 to 66 percent in 2019 – far too slowly to meet the goals by 2030, and with highly uneven progress within and between countries.
Label: Rephrase


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: Then with the onset of the pandemic, progress stopped.
Label: Support


  Progress: 250/50097 relations classified...
  Progress: 500/50097 relations classified...
  Progress: 750/50097 relations classified...
  Progress: 1000/50097 relations classified...
  Progress: 1250/50097 relations classified...
  Progress: 1500/50097 relations classified...
  Progress: 1750/50097 relations classified...
  Progress: 2000/50097 relations classified...
  Progress: 2250/50097 relations classified...
  Progress: 2500/50097 relations classified...
  Progress: 2750/50097 relations classified...
  Progress: 3000/50097 relations classified...
  Progress: 3250/50097 relations classified...
  Progress: 3500/50097 relations classified...
  Progress: 3750/50097 relations classified...
  Progress: 4000/50097 relations classified...
  Progress: 4250/50097 relations classified...
  Progress: 4500/50097 relations classified...
  Progress: 4750/50097 relations classified...
  Progress: 5000/50097 relations classified...
  Progress: 5250/50097 relations classified...
  Progress: 5500/50097 relations classified...
  Progress: 5750/50097 relations classified...
  Progress: 6000/50097 relations classified...
  Progress: 6250/50097 relations classified...
  Progress: 6500/50097 relations classified...
  Progress: 6750/50097 relations classified...
  Progress: 7000/50097 relations classified...
  Progress: 7250/50097 relations classified...
  Progress: 7500/50097 relations classified...
  Progress: 7750/50097 relations classified...
  Progress: 8000/50097 relations classified...
  Progress: 8250/50097 relations classified...
  Progress: 8500/50097 relations classified...
  Progress: 8750/50097 relations classified...
  Progress: 9000/50097 relations classified...
  Progress: 9250/50097 relations classified...
  Progress: 9500/50097 relations classified...
  Progress: 9750/50097 relations classified...
  Progress: 10000/50097 relations classified...
  Progress: 10250/50097 relations classified...
  Progress: 10500/50097 relations classified...
  Progress: 10750/50097 relations classified...
  Progress: 11000/50097 relations classified...
  Progress: 11250/50097 relations classified...
  Progress: 11500/50097 relations classified...
  Progress: 11750/50097 relations classified...
  Progress: 12000/50097 relations classified...
  Progress: 12250/50097 relations classified...
  Progress: 12500/50097 relations classified...
  Progress: 12750/50097 relations classified...
  Progress: 13000/50097 relations classified...
  Progress: 13250/50097 relations classified...
  Progress: 13500/50097 relations classified...
  Progress: 13750/50097 relations classified...
  Progress: 14000/50097 relations classified...
  Progress: 14250/50097 relations classified...
  Progress: 14500/50097 relations classified...
  Progress: 14750/50097 relations classified...
  Progress: 15000/50097 relations classified...
  Progress: 15250/50097 relations classified...
  Progress: 15500/50097 relations classified...
  Progress: 15750/50097 relations classified...
  Progress: 16000/50097 relations classified...
  Progress: 16250/50097 relations classified...
  Progress: 16500/50097 relations classified...
  Progress: 16750/50097 relations classified...
  Progress: 17000/50097 relations classified...
  Progress: 17250/50097 relations classified...
  Progress: 17500/50097 relations classified...
  Progress: 17750/50097 relations classified...
  Progress: 18000/50097 relations classified...
  Progress: 18250/50097 relations classified...
  Progress: 18500/50097 relations classified...
  Progress: 18750/50097 relations classified...
  Progress: 19000/50097 relations classified...
  Progress: 19250/50097 relations classified...
  Progress: 19500/50097 relations classified...
  Progress: 19750/50097 relations classified...
  Progress: 20000/50097 relations classified...
  Progress: 20250/50097 relations classified...
  Progress: 20500/50097 relations classified...
  Progress: 20750/50097 relations classified...
  Progress: 21000/50097 relations classified...
  Progress: 21250/50097 relations classified...
  Progress: 21500/50097 relations classified...
  Progress: 21750/50097 relations classified...
  Progress: 22000/50097 relations classified...
  Progress: 22250/50097 relations classified...
  Progress: 22500/50097 relations classified...
  Progress: 22750/50097 relations classified...
  Progress: 23000/50097 relations classified...
  Progress: 23250/50097 relations classified...
  Progress: 23500/50097 relations classified...
  Progress: 23750/50097 relations classified...
  Progress: 24000/50097 relations classified...
  Progress: 24250/50097 relations classified...
  Progress: 24500/50097 relations classified...
  Progress: 24750/50097 relations classified...
  Progress: 25000/50097 relations classified...
  Progress: 25250/50097 relations classified...
  Progress: 25500/50097 relations classified...
  Progress: 25750/50097 relations classified...
  Progress: 26000/50097 relations classified...
  Progress: 26250/50097 relations classified...
  Progress: 26500/50097 relations classified...
  Progress: 26750/50097 relations classified...
  Progress: 27000/50097 relations classified...
  Progress: 27250/50097 relations classified...
  Progress: 27500/50097 relations classified...
  Progress: 27750/50097 relations classified...
  Progress: 28000/50097 relations classified...
  Progress: 28250/50097 relations classified...
  Progress: 28500/50097 relations classified...
  Progress: 28750/50097 relations classified...
  Progress: 29000/50097 relations classified...
  Progress: 29250/50097 relations classified...
  Progress: 29500/50097 relations classified...
  Progress: 29750/50097 relations classified...
  Progress: 30000/50097 relations classified...
  Progress: 30250/50097 relations classified...
  Progress: 30500/50097 relations classified...
  Progress: 30750/50097 relations classified...
  Progress: 31000/50097 relations classified...
  Progress: 31250/50097 relations classified...
  Progress: 31500/50097 relations classified...
  Progress: 31750/50097 relations classified...
  Progress: 32000/50097 relations classified...
  Progress: 32250/50097 relations classified...
  Progress: 32500/50097 relations classified...
  Progress: 32750/50097 relations classified...
  Progress: 33000/50097 relations classified...
  Progress: 33250/50097 relations classified...
  Progress: 33500/50097 relations classified...
  Progress: 33750/50097 relations classified...
  Progress: 34000/50097 relations classified...
  Progress: 34250/50097 relations classified...
  Progress: 34500/50097 relations classified...
  Progress: 34750/50097 relations classified...
  Progress: 35000/50097 relations classified...
  Progress: 35250/50097 relations classified...
  Progress: 35500/50097 relations classified...
  Progress: 35750/50097 relations classified...
  Progress: 36000/50097 relations classified...
  Progress: 36250/50097 relations classified...
  Progress: 36500/50097 relations classified...
  Progress: 36750/50097 relations classified...
  Progress: 37000/50097 relations classified...
  Progress: 37250/50097 relations classified...
  Progress: 37500/50097 relations classified...
  Progress: 37750/50097 relations classified...
  Progress: 38000/50097 relations classified...
  Progress: 38250/50097 relations classified...
  Progress: 38500/50097 relations classified...
  Progress: 38750/50097 relations classified...
  Progress: 39000/50097 relations classified...
  Progress: 39250/50097 relations classified...
  Progress: 39500/50097 relations classified...
  Progress: 39750/50097 relations classified...
  Progress: 40000/50097 relations classified...
  Progress: 40250/50097 relations classified...
  Progress: 40500/50097 relations classified...
  Progress: 40750/50097 relations classified...
  Progress: 41000/50097 relations classified...
  Progress: 41250/50097 relations classified...
  Progress: 41500/50097 relations classified...
  Progress: 41750/50097 relations classified...
  Progress: 42000/50097 relations classified...
  Progress: 42250/50097 relations classified...
  Progress: 42500/50097 relations classified...
  Progress: 42750/50097 relations classified...
  Progress: 43000/50097 relations classified...
  Progress: 43250/50097 relations classified...
  Progress: 43500/50097 relations classified...
  Progress: 43750/50097 relations classified...
  Progress: 44000/50097 relations classified...
  Progress: 44250/50097 relations classified...
  Progress: 44500/50097 relations classified...
  Progress: 44750/50097 relations classified...
  Progress: 45000/50097 relations classified...
  Progress: 45250/50097 relations classified...
  Progress: 45500/50097 relations classified...
  Progress: 45750/50097 relations classified...
  Progress: 46000/50097 relations classified...
  Progress: 46250/50097 relations classified...
  Progress: 46500/50097 relations classified...
  Progress: 46750/50097 relations classified...
  Progress: 47000/50097 relations classified...
  Progress: 47250/50097 relations classified...
  Progress: 47500/50097 relations classified...
  Progress: 47750/50097 relations classified...
  Progress: 48000/50097 relations classified...
  Progress: 48250/50097 relations classified...
  Progress: 48500/50097 relations classified...
  Progress: 48750/50097 relations classified...
  Progress: 49000/50097 relations classified...
  Progress: 49250/50097 relations classified...
  Progress: 49500/50097 relations classified...
  Progress: 49750/50097 relations classified...
  Progress: 50000/50097 relations classified...
  Progress: 50097/50097 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships No Keywords/cross_goalGLOBAL_SGD2023_gemma3-27b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_llama,rel_robertaL
23186,"In the SDGs, universal health care (UHC) is co...",Countries must further expand and transform ed...,3_12,4_9,NaN,No Relationship,Support
47720,The SDG Index and Dashboards also include unof...,"Second, developed countries are not being held...",14_6,17_16,NaN,Attack,Support
17541,Greatly increased funding for national and sub...,More ambitious policies and actions on climate...,1_2,13_26,NaN,Support,Rephrase
13732,Achieving the SDGs will require a transformati...,We firmly believe that international cooperati...,0_29,17_11,NaN,Support,Support
31997,Although on average the world has made some pr...,Questions explored policy measures to address ...,6_6,13_25,NaN,Support,Rephrase

rel_robertaL
Support            25808
No Relationship    22354
Rephrase            1338
Attack               597
Name: count, dtype: int64

#### Gemma3 4B extraction

In [9]:
prefix = "intra_goalGLOBAL_SGD2023_gemma3-4b"   
rel_col = f"rel_{model_name}"
BATCH_SIZE = 250
MAX_LENGTH = compute_max_length(process_rel_path, prefix, tokenizer)
print(f"Using MAX_LENGTH = {MAX_LENGTH}")

args_classified = classify_relationships_hf(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_robertaL"].value_counts()

Using MAX_LENGTH = 270

Processing: /kaggle/working/TFM/Data/Relationships No Keywords/intra_goalGLOBAL_SGD2023_gemma3-4b.csv
Check first 5 predictions labels:

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: None of their objectives are beyond our reach.
Label: Attack


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: The SDGs are still achievable.
Label: Attack


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: It is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
Label: Support


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.
Label: Support


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: Greatly increase funding to national and subnational governments and private businesses, especially in LICs and LMICs, to carry out needed SDG investments.
Label: Support


  Progress: 250/22914 relations classified...
  Progress: 500/22914 relations classified...
  Progress: 750/22914 relations classified...
  Progress: 1000/22914 relations classified...
  Progress: 1250/22914 relations classified...
  Progress: 1500/22914 relations classified...
  Progress: 1750/22914 relations classified...
  Progress: 2000/22914 relations classified...
  Progress: 2250/22914 relations classified...
  Progress: 2500/22914 relations classified...
  Progress: 2750/22914 relations classified...
  Progress: 3000/22914 relations classified...
  Progress: 3250/22914 relations classified...
  Progress: 3500/22914 relations classified...
  Progress: 3750/22914 relations classified...
  Progress: 4000/22914 relations classified...
  Progress: 4250/22914 relations classified...
  Progress: 4500/22914 relations classified...
  Progress: 4750/22914 relations classified...
  Progress: 5000/22914 relations classified...
  Progress: 5250/22914 relations classified...
  Progress: 5500/22914 relations classified...
  Progress: 5750/22914 relations classified...
  Progress: 6000/22914 relations classified...
  Progress: 6250/22914 relations classified...
  Progress: 6500/22914 relations classified...
  Progress: 6750/22914 relations classified...
  Progress: 7000/22914 relations classified...
  Progress: 7250/22914 relations classified...
  Progress: 7500/22914 relations classified...
  Progress: 7750/22914 relations classified...
  Progress: 8000/22914 relations classified...
  Progress: 8250/22914 relations classified...
  Progress: 8500/22914 relations classified...
  Progress: 8750/22914 relations classified...
  Progress: 9000/22914 relations classified...
  Progress: 9250/22914 relations classified...
  Progress: 9500/22914 relations classified...
  Progress: 9750/22914 relations classified...
  Progress: 10000/22914 relations classified...
  Progress: 10250/22914 relations classified...
  Progress: 10500/22914 relations classified...
  Progress: 10750/22914 relations classified...
  Progress: 11000/22914 relations classified...
  Progress: 11250/22914 relations classified...
  Progress: 11500/22914 relations classified...
  Progress: 11750/22914 relations classified...
  Progress: 12000/22914 relations classified...
  Progress: 12250/22914 relations classified...
  Progress: 12500/22914 relations classified...
  Progress: 12750/22914 relations classified...
  Progress: 13000/22914 relations classified...
  Progress: 13250/22914 relations classified...
  Progress: 13500/22914 relations classified...
  Progress: 13750/22914 relations classified...
  Progress: 14000/22914 relations classified...
  Progress: 14250/22914 relations classified...
  Progress: 14500/22914 relations classified...
  Progress: 14750/22914 relations classified...
  Progress: 15000/22914 relations classified...
  Progress: 15250/22914 relations classified...
  Progress: 15500/22914 relations classified...
  Progress: 15750/22914 relations classified...
  Progress: 16000/22914 relations classified...
  Progress: 16250/22914 relations classified...
  Progress: 16500/22914 relations classified...
  Progress: 16750/22914 relations classified...
  Progress: 17000/22914 relations classified...
  Progress: 17250/22914 relations classified...
  Progress: 17500/22914 relations classified...
  Progress: 17750/22914 relations classified...
  Progress: 18000/22914 relations classified...
  Progress: 18250/22914 relations classified...
  Progress: 18500/22914 relations classified...
  Progress: 18750/22914 relations classified...
  Progress: 19000/22914 relations classified...
  Progress: 19250/22914 relations classified...
  Progress: 19500/22914 relations classified...
  Progress: 19750/22914 relations classified...
  Progress: 20000/22914 relations classified...
  Progress: 20250/22914 relations classified...
  Progress: 20500/22914 relations classified...
  Progress: 20750/22914 relations classified...
  Progress: 21000/22914 relations classified...
  Progress: 21250/22914 relations classified...
  Progress: 21500/22914 relations classified...
  Progress: 21750/22914 relations classified...
  Progress: 22000/22914 relations classified...
  Progress: 22250/22914 relations classified...
  Progress: 22500/22914 relations classified...
  Progress: 22750/22914 relations classified...
  Progress: 22914/22914 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships No Keywords/intra_goalGLOBAL_SGD2023_gemma3-4b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_robertaL
8617,Long-term investment plans are essential for n...,The IMF should build its national reviews (Art...,0_64,0_74,NaN,Support
9539,The World Bank and the other MDBs should put t...,no single G20 country has adopted a sufficient...,0_73,0_123,NaN,No Relationship
22025,All UN Member States and UN agencies can count...,It is widely recognized that the world needs t...,17_4,17_19,NaN,No Relationship
8778,SDSN has recommended six inter-related long-te...,UN Specialized Agencies: the Food and Agricult...,0_65,0_134,NaN,Support
4604,includes equality of opportunities for girls a...,Governments are only now establishing R&D fund...,0_30,0_90,NaN,No Relationship

rel_robertaL
Support            12040
No Relationship     9586
Rephrase             874
Attack               414
Name: count, dtype: int64

In [10]:
prefix = "cross_goalGLOBAL_SGD2023_gemma3-4b"   
rel_col = f"rel_{model_name}"
BATCH_SIZE = 250
MAX_LENGTH = compute_max_length(process_rel_path, prefix, tokenizer)
print(f"Using MAX_LENGTH = {MAX_LENGTH}")

args_classified = classify_relationships_hf(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_robertaL"].value_counts()

Using MAX_LENGTH = 270

Processing: /kaggle/working/TFM/Data/Relationships No Keywords/cross_goalGLOBAL_SGD2023_gemma3-4b.csv
Check first 5 predictions labels:

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: The world is off track, but that is all the more reason to double down on the SDGs.
Label: Support


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: It is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
Label: Support


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: Revise liquidity structures for LICs and LMICs, especially regarding sovereign debts, to forestall self-fulfilling banking and balance-of-payments crises.
Label: No Relationship


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: Create ambitious, internationally-agreed upon criteria for sustainable finance that are mandatory for all public financial institutions.
Label: No Relationship


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: Align private business investment flows with the SDGs, through improved national planning, regulation, reporting, and oversight.
Label: Support


  Progress: 250/225951 relations classified...
  Progress: 500/225951 relations classified...
  Progress: 750/225951 relations classified...
  Progress: 1000/225951 relations classified...
  Progress: 1250/225951 relations classified...
  Progress: 1500/225951 relations classified...
  Progress: 1750/225951 relations classified...
  Progress: 2000/225951 relations classified...
  Progress: 2250/225951 relations classified...
  Progress: 2500/225951 relations classified...
  Progress: 2750/225951 relations classified...
  Progress: 3000/225951 relations classified...
  Progress: 3250/225951 relations classified...
  Progress: 3500/225951 relations classified...
  Progress: 3750/225951 relations classified...
  Progress: 4000/225951 relations classified...
  Progress: 4250/225951 relations classified...
  Progress: 4500/225951 relations classified...
  Progress: 4750/225951 relations classified...
  Progress: 5000/225951 relations classified...
  Progress: 5250/225951 relations classified...
  Progress: 5500/225951 relations classified...
  Progress: 5750/225951 relations classified...
  Progress: 6000/225951 relations classified...
  Progress: 6250/225951 relations classified...
  Progress: 6500/225951 relations classified...
  Progress: 6750/225951 relations classified...
  Progress: 7000/225951 relations classified...
  Progress: 7250/225951 relations classified...
  Progress: 7500/225951 relations classified...
  Progress: 7750/225951 relations classified...
  Progress: 8000/225951 relations classified...
  Progress: 8250/225951 relations classified...
  Progress: 8500/225951 relations classified...
  Progress: 8750/225951 relations classified...
  Progress: 9000/225951 relations classified...
  Progress: 9250/225951 relations classified...
  Progress: 9500/225951 relations classified...
  Progress: 9750/225951 relations classified...
  Progress: 10000/225951 relations classified...
  Progress: 10250/225951 relations classified...
  Progress: 10500/225951 relations classified...
  Progress: 10750/225951 relations classified...
  Progress: 11000/225951 relations classified...
  Progress: 11250/225951 relations classified...
  Progress: 11500/225951 relations classified...
  Progress: 11750/225951 relations classified...
  Progress: 12000/225951 relations classified...
  Progress: 12250/225951 relations classified...
  Progress: 12500/225951 relations classified...
  Progress: 12750/225951 relations classified...
  Progress: 13000/225951 relations classified...
  Progress: 13250/225951 relations classified...
  Progress: 13500/225951 relations classified...
  Progress: 13750/225951 relations classified...
  Progress: 14000/225951 relations classified...
  Progress: 14250/225951 relations classified...
  Progress: 14500/225951 relations classified...
  Progress: 14750/225951 relations classified...
  Progress: 15000/225951 relations classified...
  Progress: 15250/225951 relations classified...
  Progress: 15500/225951 relations classified...
  Progress: 15750/225951 relations classified...
  Progress: 16000/225951 relations classified...
  Progress: 16250/225951 relations classified...
  Progress: 16500/225951 relations classified...
  Progress: 16750/225951 relations classified...
  Progress: 17000/225951 relations classified...
  Progress: 17250/225951 relations classified...
  Progress: 17500/225951 relations classified...
  Progress: 17750/225951 relations classified...
  Progress: 18000/225951 relations classified...
  Progress: 18250/225951 relations classified...
  Progress: 18500/225951 relations classified...
  Progress: 18750/225951 relations classified...
  Progress: 19000/225951 relations classified...
  Progress: 19250/225951 relations classified...
  Progress: 19500/225951 relations classified...
  Progress: 19750/225951 relations classified...
  Progress: 20000/225951 relations classified...
  Progress: 20250/225951 relations classified...
  Progress: 20500/225951 relations classified...
  Progress: 20750/225951 relations classified...
  Progress: 21000/225951 relations classified...
  Progress: 21250/225951 relations classified...
  Progress: 21500/225951 relations classified...
  Progress: 21750/225951 relations classified...
  Progress: 22000/225951 relations classified...
  Progress: 22250/225951 relations classified...
  Progress: 22500/225951 relations classified...
  Progress: 22750/225951 relations classified...
  Progress: 23000/225951 relations classified...
  Progress: 23250/225951 relations classified...
  Progress: 23500/225951 relations classified...
  Progress: 23750/225951 relations classified...
  Progress: 24000/225951 relations classified...
  Progress: 24250/225951 relations classified...
  Progress: 24500/225951 relations classified...
  Progress: 24750/225951 relations classified...
  Progress: 25000/225951 relations classified...
  Progress: 25250/225951 relations classified...
  Progress: 25500/225951 relations classified...
  Progress: 25750/225951 relations classified...
  Progress: 26000/225951 relations classified...
  Progress: 26250/225951 relations classified...
  Progress: 26500/225951 relations classified...
  Progress: 26750/225951 relations classified...
  Progress: 27000/225951 relations classified...
  Progress: 27250/225951 relations classified...
  Progress: 27500/225951 relations classified...
  Progress: 27750/225951 relations classified...
  Progress: 28000/225951 relations classified...
  Progress: 28250/225951 relations classified...
  Progress: 28500/225951 relations classified...
  Progress: 28750/225951 relations classified...
  Progress: 29000/225951 relations classified...
  Progress: 29250/225951 relations classified...
  Progress: 29500/225951 relations classified...
  Progress: 29750/225951 relations classified...
  Progress: 30000/225951 relations classified...
  Progress: 30250/225951 relations classified...
  Progress: 30500/225951 relations classified...
  Progress: 30750/225951 relations classified...
  Progress: 31000/225951 relations classified...
  Progress: 31250/225951 relations classified...
  Progress: 31500/225951 relations classified...
  Progress: 31750/225951 relations classified...
  Progress: 32000/225951 relations classified...
  Progress: 32250/225951 relations classified...
  Progress: 32500/225951 relations classified...
  Progress: 32750/225951 relations classified...
  Progress: 33000/225951 relations classified...
  Progress: 33250/225951 relations classified...
  Progress: 33500/225951 relations classified...
  Progress: 33750/225951 relations classified...
  Progress: 34000/225951 relations classified...
  Progress: 34250/225951 relations classified...
  Progress: 34500/225951 relations classified...
  Progress: 34750/225951 relations classified...
  Progress: 35000/225951 relations classified...
  Progress: 35250/225951 relations classified...
  Progress: 35500/225951 relations classified...
  Progress: 35750/225951 relations classified...
  Progress: 36000/225951 relations classified...
  Progress: 36250/225951 relations classified...
  Progress: 36500/225951 relations classified...
  Progress: 36750/225951 relations classified...
  Progress: 37000/225951 relations classified...
  Progress: 37250/225951 relations classified...
  Progress: 37500/225951 relations classified...
  Progress: 37750/225951 relations classified...
  Progress: 38000/225951 relations classified...
  Progress: 38250/225951 relations classified...
  Progress: 38500/225951 relations classified...
  Progress: 38750/225951 relations classified...
  Progress: 39000/225951 relations classified...
  Progress: 39250/225951 relations classified...
  Progress: 39500/225951 relations classified...
  Progress: 39750/225951 relations classified...
  Progress: 40000/225951 relations classified...
  Progress: 40250/225951 relations classified...
  Progress: 40500/225951 relations classified...
  Progress: 40750/225951 relations classified...
  Progress: 41000/225951 relations classified...
  Progress: 41250/225951 relations classified...
  Progress: 41500/225951 relations classified...
  Progress: 41750/225951 relations classified...
  Progress: 42000/225951 relations classified...
  Progress: 42250/225951 relations classified...
  Progress: 42500/225951 relations classified...
  Progress: 42750/225951 relations classified...
  Progress: 43000/225951 relations classified...
  Progress: 43250/225951 relations classified...
  Progress: 43500/225951 relations classified...
  Progress: 43750/225951 relations classified...
  Progress: 44000/225951 relations classified...
  Progress: 44250/225951 relations classified...
  Progress: 44500/225951 relations classified...
  Progress: 44750/225951 relations classified...
  Progress: 45000/225951 relations classified...
  Progress: 45250/225951 relations classified...
  Progress: 45500/225951 relations classified...
  Progress: 45750/225951 relations classified...
  Progress: 46000/225951 relations classified...
  Progress: 46250/225951 relations classified...
  Progress: 46500/225951 relations classified...
  Progress: 46750/225951 relations classified...
  Progress: 47000/225951 relations classified...
  Progress: 47250/225951 relations classified...
  Progress: 47500/225951 relations classified...
  Progress: 47750/225951 relations classified...
  Progress: 48000/225951 relations classified...
  Progress: 48250/225951 relations classified...
  Progress: 48500/225951 relations classified...
  Progress: 48750/225951 relations classified...
  Progress: 49000/225951 relations classified...
  Progress: 49250/225951 relations classified...
  Progress: 49500/225951 relations classified...
  Progress: 49750/225951 relations classified...
  Progress: 50000/225951 relations classified...
  Progress: 50250/225951 relations classified...
  Progress: 50500/225951 relations classified...
  Progress: 50750/225951 relations classified...
  Progress: 51000/225951 relations classified...
  Progress: 51250/225951 relations classified...
  Progress: 51500/225951 relations classified...
  Progress: 51750/225951 relations classified...
  Progress: 52000/225951 relations classified...
  Progress: 52250/225951 relations classified...
  Progress: 52500/225951 relations classified...
  Progress: 52750/225951 relations classified...
  Progress: 53000/225951 relations classified...
  Progress: 53250/225951 relations classified...
  Progress: 53500/225951 relations classified...
  Progress: 53750/225951 relations classified...
  Progress: 54000/225951 relations classified...
  Progress: 54250/225951 relations classified...
  Progress: 54500/225951 relations classified...
  Progress: 54750/225951 relations classified...
  Progress: 55000/225951 relations classified...
  Progress: 55250/225951 relations classified...
  Progress: 55500/225951 relations classified...
  Progress: 55750/225951 relations classified...
  Progress: 56000/225951 relations classified...
  Progress: 56250/225951 relations classified...
  Progress: 56500/225951 relations classified...
  Progress: 56750/225951 relations classified...
  Progress: 57000/225951 relations classified...
  Progress: 57250/225951 relations classified...
  Progress: 57500/225951 relations classified...
  Progress: 57750/225951 relations classified...
  Progress: 58000/225951 relations classified...
  Progress: 58250/225951 relations classified...
  Progress: 58500/225951 relations classified...
  Progress: 58750/225951 relations classified...
  Progress: 59000/225951 relations classified...
  Progress: 59250/225951 relations classified...
  Progress: 59500/225951 relations classified...
  Progress: 59750/225951 relations classified...
  Progress: 60000/225951 relations classified...
  Progress: 60250/225951 relations classified...
  Progress: 60500/225951 relations classified...
  Progress: 60750/225951 relations classified...
  Progress: 61000/225951 relations classified...
  Progress: 61250/225951 relations classified...
  Progress: 61500/225951 relations classified...
  Progress: 61750/225951 relations classified...
  Progress: 62000/225951 relations classified...
  Progress: 62250/225951 relations classified...
  Progress: 62500/225951 relations classified...
  Progress: 62750/225951 relations classified...
  Progress: 63000/225951 relations classified...
  Progress: 63250/225951 relations classified...
  Progress: 63500/225951 relations classified...
  Progress: 63750/225951 relations classified...
  Progress: 64000/225951 relations classified...
  Progress: 64250/225951 relations classified...
  Progress: 64500/225951 relations classified...
  Progress: 64750/225951 relations classified...
  Progress: 65000/225951 relations classified...
  Progress: 65250/225951 relations classified...
  Progress: 65500/225951 relations classified...
  Progress: 65750/225951 relations classified...
  Progress: 66000/225951 relations classified...
  Progress: 66250/225951 relations classified...
  Progress: 66500/225951 relations classified...
  Progress: 66750/225951 relations classified...
  Progress: 67000/225951 relations classified...
  Progress: 67250/225951 relations classified...
  Progress: 67500/225951 relations classified...
  Progress: 67750/225951 relations classified...
  Progress: 68000/225951 relations classified...
  Progress: 68250/225951 relations classified...
  Progress: 68500/225951 relations classified...
  Progress: 68750/225951 relations classified...
  Progress: 69000/225951 relations classified...
  Progress: 69250/225951 relations classified...
  Progress: 69500/225951 relations classified...
  Progress: 69750/225951 relations classified...
  Progress: 70000/225951 relations classified...
  Progress: 70250/225951 relations classified...
  Progress: 70500/225951 relations classified...
  Progress: 70750/225951 relations classified...
  Progress: 71000/225951 relations classified...
  Progress: 71250/225951 relations classified...
  Progress: 71500/225951 relations classified...
  Progress: 71750/225951 relations classified...
  Progress: 72000/225951 relations classified...
  Progress: 72250/225951 relations classified...
  Progress: 72500/225951 relations classified...
  Progress: 72750/225951 relations classified...
  Progress: 73000/225951 relations classified...
  Progress: 73250/225951 relations classified...
  Progress: 73500/225951 relations classified...
  Progress: 73750/225951 relations classified...
  Progress: 74000/225951 relations classified...
  Progress: 74250/225951 relations classified...
  Progress: 74500/225951 relations classified...
  Progress: 74750/225951 relations classified...
  Progress: 75000/225951 relations classified...
  Progress: 75250/225951 relations classified...
  Progress: 75500/225951 relations classified...
  Progress: 75750/225951 relations classified...
  Progress: 76000/225951 relations classified...
  Progress: 76250/225951 relations classified...
  Progress: 76500/225951 relations classified...
  Progress: 76750/225951 relations classified...
  Progress: 77000/225951 relations classified...
  Progress: 77250/225951 relations classified...
  Progress: 77500/225951 relations classified...
  Progress: 77750/225951 relations classified...
  Progress: 78000/225951 relations classified...
  Progress: 78250/225951 relations classified...
  Progress: 78500/225951 relations classified...
  Progress: 78750/225951 relations classified...
  Progress: 79000/225951 relations classified...
  Progress: 79250/225951 relations classified...
  Progress: 79500/225951 relations classified...
  Progress: 79750/225951 relations classified...
  Progress: 80000/225951 relations classified...
  Progress: 80250/225951 relations classified...
  Progress: 80500/225951 relations classified...
  Progress: 80750/225951 relations classified...
  Progress: 81000/225951 relations classified...
  Progress: 81250/225951 relations classified...
  Progress: 81500/225951 relations classified...
  Progress: 81750/225951 relations classified...
  Progress: 82000/225951 relations classified...
  Progress: 82250/225951 relations classified...
  Progress: 82500/225951 relations classified...
  Progress: 82750/225951 relations classified...
  Progress: 83000/225951 relations classified...
  Progress: 83250/225951 relations classified...
  Progress: 83500/225951 relations classified...
  Progress: 83750/225951 relations classified...
  Progress: 84000/225951 relations classified...
  Progress: 84250/225951 relations classified...
  Progress: 84500/225951 relations classified...
  Progress: 84750/225951 relations classified...
  Progress: 85000/225951 relations classified...
  Progress: 85250/225951 relations classified...
  Progress: 85500/225951 relations classified...
  Progress: 85750/225951 relations classified...
  Progress: 86000/225951 relations classified...
  Progress: 86250/225951 relations classified...
  Progress: 86500/225951 relations classified...
  Progress: 86750/225951 relations classified...
  Progress: 87000/225951 relations classified...
  Progress: 87250/225951 relations classified...
  Progress: 87500/225951 relations classified...
  Progress: 87750/225951 relations classified...
  Progress: 88000/225951 relations classified...
  Progress: 88250/225951 relations classified...
  Progress: 88500/225951 relations classified...
  Progress: 88750/225951 relations classified...
  Progress: 89000/225951 relations classified...
  Progress: 89250/225951 relations classified...
  Progress: 89500/225951 relations classified...
  Progress: 89750/225951 relations classified...
  Progress: 90000/225951 relations classified...
  Progress: 90250/225951 relations classified...
  Progress: 90500/225951 relations classified...
  Progress: 90750/225951 relations classified...
  Progress: 91000/225951 relations classified...
  Progress: 91250/225951 relations classified...
  Progress: 91500/225951 relations classified...
  Progress: 91750/225951 relations classified...
  Progress: 92000/225951 relations classified...
  Progress: 92250/225951 relations classified...
  Progress: 92500/225951 relations classified...
  Progress: 92750/225951 relations classified...
  Progress: 93000/225951 relations classified...
  Progress: 93250/225951 relations classified...
  Progress: 93500/225951 relations classified...
  Progress: 93750/225951 relations classified...
  Progress: 94000/225951 relations classified...
  Progress: 94250/225951 relations classified...
  Progress: 94500/225951 relations classified...
  Progress: 94750/225951 relations classified...
  Progress: 95000/225951 relations classified...

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_robertaL
113650,not a single SDG is projected to be met at the...,The HICs’ somewhat better performance on pilla...,2_1,3_33,NaN,No Relationship
192637,Revision of the liquidity structures for LICs ...,Many countries continue to provide substantial...,9_6,13_22,NaN,No Relationship
201267,"LICs, LMICs, and SIDS are highly vulnerable to...",This is driven in part by the moderate or low ...,10_22,13_30,NaN,Support
215380,Food systems account for a quarter of greenhou...,It is also vital to share fairly and globally ...,12_21,17_24,NaN,Support
186746,"At the midpoint of the 2030 Agenda, all countr...",Governments are only now establishing R&D fund...,8_19,16_29,NaN,No Relationship

rel_robertaL
No Relationship    116729
Support             98293
Rephrase             7259
Attack               3670
Name: count, dtype: int64

#### Llama3.3 70B extraction

In [11]:
prefix = "intra_goalGLOBAL_SGD2023_llama3.3-70b"   
rel_col = f"rel_{model_name}"
BATCH_SIZE = 250
MAX_LENGTH = compute_max_length(process_rel_path, prefix, tokenizer)
print(f"Using MAX_LENGTH = {MAX_LENGTH}")

args_classified = classify_relationships_hf(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_robertaL"].value_counts()

Using MAX_LENGTH = 247

Processing: /kaggle/working/TFM/Data/Relationships No Keywords/intra_goalGLOBAL_SGD2023_llama3.3-70b.csv
Check first 5 predictions labels:

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: Since the outbreak of the pandemic in 2020 and other simultaneous crises, SDG progress has stalled globally.
Label: Rephrase


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: The world is off track, but that is all the more reason to double down on the SDGs.
Label: Support


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
Label: Support


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.
Label: Support


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.
Label: Support


  Progress: 250/12011 relations classified...
  Progress: 500/12011 relations classified...
  Progress: 750/12011 relations classified...
  Progress: 1000/12011 relations classified...
  Progress: 1250/12011 relations classified...
  Progress: 1500/12011 relations classified...
  Progress: 1750/12011 relations classified...
  Progress: 2000/12011 relations classified...
  Progress: 2250/12011 relations classified...
  Progress: 2500/12011 relations classified...
  Progress: 2750/12011 relations classified...
  Progress: 3000/12011 relations classified...
  Progress: 3250/12011 relations classified...
  Progress: 3500/12011 relations classified...
  Progress: 3750/12011 relations classified...
  Progress: 4000/12011 relations classified...
  Progress: 4250/12011 relations classified...
  Progress: 4500/12011 relations classified...
  Progress: 4750/12011 relations classified...
  Progress: 5000/12011 relations classified...
  Progress: 5250/12011 relations classified...
  Progress: 5500/12011 relations classified...
  Progress: 5750/12011 relations classified...
  Progress: 6000/12011 relations classified...
  Progress: 6250/12011 relations classified...
  Progress: 6500/12011 relations classified...
  Progress: 6750/12011 relations classified...
  Progress: 7000/12011 relations classified...
  Progress: 7250/12011 relations classified...
  Progress: 7500/12011 relations classified...
  Progress: 7750/12011 relations classified...
  Progress: 8000/12011 relations classified...
  Progress: 8250/12011 relations classified...
  Progress: 8500/12011 relations classified...
  Progress: 8750/12011 relations classified...
  Progress: 9000/12011 relations classified...
  Progress: 9250/12011 relations classified...
  Progress: 9500/12011 relations classified...
  Progress: 9750/12011 relations classified...
  Progress: 10000/12011 relations classified...
  Progress: 10250/12011 relations classified...
  Progress: 10500/12011 relations classified...
  Progress: 10750/12011 relations classified...
  Progress: 11000/12011 relations classified...
  Progress: 11250/12011 relations classified...
  Progress: 11500/12011 relations classified...
  Progress: 11750/12011 relations classified...
  Progress: 12000/12011 relations classified...
  Progress: 12011/12011 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships No Keywords/intra_goalGLOBAL_SGD2023_llama3.3-70b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_llama,rel_robertaL
7481,According to the UNEP Emissions Gap Report 202...,governments to combine the objectives of econo...,13_5,13_29,NaN,No Relationship,No Relationship
7088,5. Sustainable cities,SDSN recognizes this gap in the practical mean...,11_3,11_7,NaN,Support,Support
9612,We commend global leaders who “oppose the use ...,The SDG Index is prepared by an independent gr...,16_21,16_37,NaN,No Relationship,No Relationship
10396,"Moreover, societal polarization, populism, and...",Both sides – importers and exporters – must wo...,17_10,17_49,NaN,Support,Support
10905,"Second, developed countries are not being held...",All UN Member States and United Nations agenci...,17_20,17_43,NaN,No Relationship,Attack

rel_robertaL
Support            8625
No Relationship    2465
Rephrase            635
Attack              286
Name: count, dtype: int64

In [12]:
prefix = "cross_goalGLOBAL_SGD2023_llama3.3-70b"   
rel_col = f"rel_{model_name}"
BATCH_SIZE = 250
MAX_LENGTH = compute_max_length(process_rel_path, prefix, tokenizer)
print(f"Using MAX_LENGTH = {MAX_LENGTH}")

args_classified = classify_relationships_hf(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_robertaL"].value_counts()

Using MAX_LENGTH = 296

Processing: /kaggle/working/TFM/Data/Relationships No Keywords/cross_goalGLOBAL_SGD2023_llama3.3-70b.csv
Check first 5 predictions labels:

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: At the global level, averaging across countries, not a single SDG is currently projected to be met by 2030, with the poorest countries struggling the most.
Label: Rephrase


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: The grim reality is that at the midpoint of the 2030 Agenda, the SDGs are far off track.
Label: Rephrase


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: Similarly, extreme poverty can lead to a collapse of tax revenues, followed by government bankruptcy and further economic collapse, a syndrome that now threatens dozens of poor countries.
Label: No Relationship


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: In 2022, Investment per person in the LICs averaged a meagre US$175 per person, compared with US$11,535 per person in the HICs. (Table 1.1). In fact, investment as a share of GDP was lower in the LICs (20.9%) than in all other income categories. The poor are consequently languishing in poverty.
Label: No Relationship


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: Deep, chronic, and crippling under-investment in virtually all low-income countries (LICs) and lower-middle-income countries (LMICs).
Label: Support


  Progress: 250/101515 relations classified...
  Progress: 500/101515 relations classified...
  Progress: 750/101515 relations classified...
  Progress: 1000/101515 relations classified...
  Progress: 1250/101515 relations classified...
  Progress: 1500/101515 relations classified...
  Progress: 1750/101515 relations classified...
  Progress: 2000/101515 relations classified...
  Progress: 2250/101515 relations classified...
  Progress: 2500/101515 relations classified...
  Progress: 2750/101515 relations classified...
  Progress: 3000/101515 relations classified...
  Progress: 3250/101515 relations classified...
  Progress: 3500/101515 relations classified...
  Progress: 3750/101515 relations classified...
  Progress: 4000/101515 relations classified...
  Progress: 4250/101515 relations classified...
  Progress: 4500/101515 relations classified...
  Progress: 4750/101515 relations classified...
  Progress: 5000/101515 relations classified...
  Progress: 5250/101515 relations classified...
  Progress: 5500/101515 relations classified...
  Progress: 5750/101515 relations classified...
  Progress: 6000/101515 relations classified...
  Progress: 6250/101515 relations classified...
  Progress: 6500/101515 relations classified...
  Progress: 6750/101515 relations classified...
  Progress: 7000/101515 relations classified...
  Progress: 7250/101515 relations classified...
  Progress: 7500/101515 relations classified...
  Progress: 7750/101515 relations classified...
  Progress: 8000/101515 relations classified...
  Progress: 8250/101515 relations classified...
  Progress: 8500/101515 relations classified...
  Progress: 8750/101515 relations classified...
  Progress: 9000/101515 relations classified...
  Progress: 9250/101515 relations classified...
  Progress: 9500/101515 relations classified...
  Progress: 9750/101515 relations classified...
  Progress: 10000/101515 relations classified...
  Progress: 10250/101515 relations classified...
  Progress: 10500/101515 relations classified...
  Progress: 10750/101515 relations classified...
  Progress: 11000/101515 relations classified...
  Progress: 11250/101515 relations classified...
  Progress: 11500/101515 relations classified...
  Progress: 11750/101515 relations classified...
  Progress: 12000/101515 relations classified...
  Progress: 12250/101515 relations classified...
  Progress: 12500/101515 relations classified...
  Progress: 12750/101515 relations classified...
  Progress: 13000/101515 relations classified...
  Progress: 13250/101515 relations classified...
  Progress: 13500/101515 relations classified...
  Progress: 13750/101515 relations classified...
  Progress: 14000/101515 relations classified...
  Progress: 14250/101515 relations classified...
  Progress: 14500/101515 relations classified...
  Progress: 14750/101515 relations classified...
  Progress: 15000/101515 relations classified...
  Progress: 15250/101515 relations classified...
  Progress: 15500/101515 relations classified...
  Progress: 15750/101515 relations classified...
  Progress: 16000/101515 relations classified...
  Progress: 16250/101515 relations classified...
  Progress: 16500/101515 relations classified...
  Progress: 16750/101515 relations classified...
  Progress: 17000/101515 relations classified...
  Progress: 17250/101515 relations classified...
  Progress: 17500/101515 relations classified...
  Progress: 17750/101515 relations classified...
  Progress: 18000/101515 relations classified...
  Progress: 18250/101515 relations classified...
  Progress: 18500/101515 relations classified...
  Progress: 18750/101515 relations classified...
  Progress: 19000/101515 relations classified...
  Progress: 19250/101515 relations classified...
  Progress: 19500/101515 relations classified...
  Progress: 19750/101515 relations classified...
  Progress: 20000/101515 relations classified...
  Progress: 20250/101515 relations classified...
  Progress: 20500/101515 relations classified...
  Progress: 20750/101515 relations classified...
  Progress: 21000/101515 relations classified...
  Progress: 21250/101515 relations classified...
  Progress: 21500/101515 relations classified...
  Progress: 21750/101515 relations classified...
  Progress: 22000/101515 relations classified...
  Progress: 22250/101515 relations classified...
  Progress: 22500/101515 relations classified...
  Progress: 22750/101515 relations classified...
  Progress: 23000/101515 relations classified...
  Progress: 23250/101515 relations classified...
  Progress: 23500/101515 relations classified...
  Progress: 23750/101515 relations classified...
  Progress: 24000/101515 relations classified...
  Progress: 24250/101515 relations classified...
  Progress: 24500/101515 relations classified...
  Progress: 24750/101515 relations classified...
  Progress: 25000/101515 relations classified...
  Progress: 25250/101515 relations classified...
  Progress: 25500/101515 relations classified...
  Progress: 25750/101515 relations classified...
  Progress: 26000/101515 relations classified...
  Progress: 26250/101515 relations classified...
  Progress: 26500/101515 relations classified...
  Progress: 26750/101515 relations classified...
  Progress: 27000/101515 relations classified...
  Progress: 27250/101515 relations classified...
  Progress: 27500/101515 relations classified...
  Progress: 27750/101515 relations classified...
  Progress: 28000/101515 relations classified...
  Progress: 28250/101515 relations classified...
  Progress: 28500/101515 relations classified...
  Progress: 28750/101515 relations classified...
  Progress: 29000/101515 relations classified...
  Progress: 29250/101515 relations classified...
  Progress: 29500/101515 relations classified...
  Progress: 29750/101515 relations classified...
  Progress: 30000/101515 relations classified...
  Progress: 30250/101515 relations classified...
  Progress: 30500/101515 relations classified...
  Progress: 30750/101515 relations classified...
  Progress: 31000/101515 relations classified...
  Progress: 31250/101515 relations classified...
  Progress: 31500/101515 relations classified...
  Progress: 31750/101515 relations classified...
  Progress: 32000/101515 relations classified...
  Progress: 32250/101515 relations classified...
  Progress: 32500/101515 relations classified...
  Progress: 32750/101515 relations classified...
  Progress: 33000/101515 relations classified...
  Progress: 33250/101515 relations classified...
  Progress: 33500/101515 relations classified...
  Progress: 33750/101515 relations classified...
  Progress: 34000/101515 relations classified...
  Progress: 34250/101515 relations classified...
  Progress: 34500/101515 relations classified...
  Progress: 34750/101515 relations classified...
  Progress: 35000/101515 relations classified...
  Progress: 35250/101515 relations classified...
  Progress: 35500/101515 relations classified...
  Progress: 35750/101515 relations classified...
  Progress: 36000/101515 relations classified...
  Progress: 36250/101515 relations classified...
  Progress: 36500/101515 relations classified...
  Progress: 36750/101515 relations classified...
  Progress: 37000/101515 relations classified...
  Progress: 37250/101515 relations classified...
  Progress: 37500/101515 relations classified...
  Progress: 37750/101515 relations classified...
  Progress: 38000/101515 relations classified...
  Progress: 38250/101515 relations classified...
  Progress: 38500/101515 relations classified...
  Progress: 38750/101515 relations classified...
  Progress: 39000/101515 relations classified...
  Progress: 39250/101515 relations classified...
  Progress: 39500/101515 relations classified...
  Progress: 39750/101515 relations classified...
  Progress: 40000/101515 relations classified...
  Progress: 40250/101515 relations classified...
  Progress: 40500/101515 relations classified...
  Progress: 40750/101515 relations classified...
  Progress: 41000/101515 relations classified...
  Progress: 41250/101515 relations classified...
  Progress: 41500/101515 relations classified...
  Progress: 41750/101515 relations classified...
  Progress: 42000/101515 relations classified...
  Progress: 42250/101515 relations classified...
  Progress: 42500/101515 relations classified...
  Progress: 42750/101515 relations classified...
  Progress: 43000/101515 relations classified...
  Progress: 43250/101515 relations classified...
  Progress: 43500/101515 relations classified...
  Progress: 43750/101515 relations classified...
  Progress: 44000/101515 relations classified...
  Progress: 44250/101515 relations classified...
  Progress: 44500/101515 relations classified...
  Progress: 44750/101515 relations classified...
  Progress: 45000/101515 relations classified...
  Progress: 45250/101515 relations classified...
  Progress: 45500/101515 relations classified...
  Progress: 45750/101515 relations classified...
  Progress: 46000/101515 relations classified...
  Progress: 46250/101515 relations classified...
  Progress: 46500/101515 relations classified...
  Progress: 46750/101515 relations classified...
  Progress: 47000/101515 relations classified...
  Progress: 47250/101515 relations classified...
  Progress: 47500/101515 relations classified...
  Progress: 47750/101515 relations classified...
  Progress: 48000/101515 relations classified...
  Progress: 48250/101515 relations classified...
  Progress: 48500/101515 relations classified...
  Progress: 48750/101515 relations classified...
  Progress: 49000/101515 relations classified...
  Progress: 49250/101515 relations classified...
  Progress: 49500/101515 relations classified...
  Progress: 49750/101515 relations classified...
  Progress: 50000/101515 relations classified...
  Progress: 50250/101515 relations classified...
  Progress: 50500/101515 relations classified...
  Progress: 50750/101515 relations classified...
  Progress: 51000/101515 relations classified...
  Progress: 51250/101515 relations classified...
  Progress: 51500/101515 relations classified...
  Progress: 51750/101515 relations classified...
  Progress: 52000/101515 relations classified...
  Progress: 52250/101515 relations classified...
  Progress: 52500/101515 relations classified...
  Progress: 52750/101515 relations classified...
  Progress: 53000/101515 relations classified...
  Progress: 53250/101515 relations classified...
  Progress: 53500/101515 relations classified...
  Progress: 53750/101515 relations classified...
  Progress: 54000/101515 relations classified...
  Progress: 54250/101515 relations classified...
  Progress: 54500/101515 relations classified...
  Progress: 54750/101515 relations classified...
  Progress: 55000/101515 relations classified...
  Progress: 55250/101515 relations classified...
  Progress: 55500/101515 relations classified...
  Progress: 55750/101515 relations classified...
  Progress: 56000/101515 relations classified...
  Progress: 56250/101515 relations classified...
  Progress: 56500/101515 relations classified...
  Progress: 56750/101515 relations classified...
  Progress: 57000/101515 relations classified...
  Progress: 57250/101515 relations classified...
  Progress: 57500/101515 relations classified...
  Progress: 57750/101515 relations classified...
  Progress: 58000/101515 relations classified...
  Progress: 58250/101515 relations classified...
  Progress: 58500/101515 relations classified...
  Progress: 58750/101515 relations classified...
  Progress: 59000/101515 relations classified...
  Progress: 59250/101515 relations classified...
  Progress: 59500/101515 relations classified...
  Progress: 59750/101515 relations classified...
  Progress: 60000/101515 relations classified...
  Progress: 60250/101515 relations classified...
  Progress: 60500/101515 relations classified...
  Progress: 60750/101515 relations classified...
  Progress: 61000/101515 relations classified...
  Progress: 61250/101515 relations classified...
  Progress: 61500/101515 relations classified...
  Progress: 61750/101515 relations classified...
  Progress: 62000/101515 relations classified...
  Progress: 62250/101515 relations classified...
  Progress: 62500/101515 relations classified...
  Progress: 62750/101515 relations classified...
  Progress: 63000/101515 relations classified...
  Progress: 63250/101515 relations classified...
  Progress: 63500/101515 relations classified...
  Progress: 63750/101515 relations classified...
  Progress: 64000/101515 relations classified...
  Progress: 64250/101515 relations classified...
  Progress: 64500/101515 relations classified...
  Progress: 64750/101515 relations classified...
  Progress: 65000/101515 relations classified...
  Progress: 65250/101515 relations classified...
  Progress: 65500/101515 relations classified...
  Progress: 65750/101515 relations classified...
  Progress: 66000/101515 relations classified...
  Progress: 66250/101515 relations classified...
  Progress: 66500/101515 relations classified...
  Progress: 66750/101515 relations classified...
  Progress: 67000/101515 relations classified...
  Progress: 67250/101515 relations classified...
  Progress: 67500/101515 relations classified...
  Progress: 67750/101515 relations classified...
  Progress: 68000/101515 relations classified...
  Progress: 68250/101515 relations classified...
  Progress: 68500/101515 relations classified...
  Progress: 68750/101515 relations classified...
  Progress: 69000/101515 relations classified...
  Progress: 69250/101515 relations classified...
  Progress: 69500/101515 relations classified...
  Progress: 69750/101515 relations classified...
  Progress: 70000/101515 relations classified...
  Progress: 70250/101515 relations classified...
  Progress: 70500/101515 relations classified...
  Progress: 70750/101515 relations classified...
  Progress: 71000/101515 relations classified...
  Progress: 71250/101515 relations classified...
  Progress: 71500/101515 relations classified...
  Progress: 71750/101515 relations classified...
  Progress: 72000/101515 relations classified...
  Progress: 72250/101515 relations classified...
  Progress: 72500/101515 relations classified...
  Progress: 72750/101515 relations classified...
  Progress: 73000/101515 relations classified...
  Progress: 73250/101515 relations classified...
  Progress: 73500/101515 relations classified...
  Progress: 73750/101515 relations classified...
  Progress: 74000/101515 relations classified...
  Progress: 74250/101515 relations classified...
  Progress: 74500/101515 relations classified...
  Progress: 74750/101515 relations classified...
  Progress: 75000/101515 relations classified...
  Progress: 75250/101515 relations classified...
  Progress: 75500/101515 relations classified...
  Progress: 75750/101515 relations classified...
  Progress: 76000/101515 relations classified...
  Progress: 76250/101515 relations classified...
  Progress: 76500/101515 relations classified...
  Progress: 76750/101515 relations classified...
  Progress: 77000/101515 relations classified...
  Progress: 77250/101515 relations classified...
  Progress: 77500/101515 relations classified...
  Progress: 77750/101515 relations classified...
  Progress: 78000/101515 relations classified...
  Progress: 78250/101515 relations classified...
  Progress: 78500/101515 relations classified...
  Progress: 78750/101515 relations classified...
  Progress: 79000/101515 relations classified...
  Progress: 79250/101515 relations classified...
  Progress: 79500/101515 relations classified...
  Progress: 79750/101515 relations classified...
  Progress: 80000/101515 relations classified...
  Progress: 80250/101515 relations classified...
  Progress: 80500/101515 relations classified...
  Progress: 80750/101515 relations classified...
  Progress: 81000/101515 relations classified...
  Progress: 81250/101515 relations classified...
  Progress: 81500/101515 relations classified...
  Progress: 81750/101515 relations classified...
  Progress: 82000/101515 relations classified...
  Progress: 82250/101515 relations classified...
  Progress: 82500/101515 relations classified...
  Progress: 82750/101515 relations classified...
  Progress: 83000/101515 relations classified...
  Progress: 83250/101515 relations classified...
  Progress: 83500/101515 relations classified...
  Progress: 83750/101515 relations classified...
  Progress: 84000/101515 relations classified...
  Progress: 84250/101515 relations classified...
  Progress: 84500/101515 relations classified...
  Progress: 84750/101515 relations classified...
  Progress: 85000/101515 relations classified...
  Progress: 85250/101515 relations classified...
  Progress: 85500/101515 relations classified...
  Progress: 85750/101515 relations classified...
  Progress: 86000/101515 relations classified...
  Progress: 86250/101515 relations classified...
  Progress: 86500/101515 relations classified...
  Progress: 86750/101515 relations classified...
  Progress: 87000/101515 relations classified...
  Progress: 87250/101515 relations classified...
  Progress: 87500/101515 relations classified...
  Progress: 87750/101515 relations classified...
  Progress: 88000/101515 relations classified...
  Progress: 88250/101515 relations classified...
  Progress: 88500/101515 relations classified...
  Progress: 88750/101515 relations classified...
  Progress: 89000/101515 relations classified...
  Progress: 89250/101515 relations classified...
  Progress: 89500/101515 relations classified...
  Progress: 89750/101515 relations classified...
  Progress: 90000/101515 relations classified...
  Progress: 90250/101515 relations classified...
  Progress: 90500/101515 relations classified...
  Progress: 90750/101515 relations classified...
  Progress: 91000/101515 relations classified...
  Progress: 91250/101515 relations classified...
  Progress: 91500/101515 relations classified...
  Progress: 91750/101515 relations classified...
  Progress: 92000/101515 relations classified...
  Progress: 92250/101515 relations classified...
  Progress: 92500/101515 relations classified...
  Progress: 92750/101515 relations classified...
  Progress: 93000/101515 relations classified...
  Progress: 93250/101515 relations classified...
  Progress: 93500/101515 relations classified...
  Progress: 93750/101515 relations classified...
  Progress: 94000/101515 relations classified...

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_robertaL
9373,Non-traditional statistics and science-based p...,Although on average the world has made some pr...,0_108,6_7,NaN,No Relationship
36667,"At the mid-point of the SDG agenda, we are far...",International cooperation is trapped by bureau...,0_58,17_23,NaN,Attack
24217,Since the outbreak of the pandemic in 2020 and...,incorporating recent international agreements ...,0_1,14_7,NaN,No Relationship
62522,The International Commission on the Futures of...,"Working together with the IMF and the MDBs, th...",4_12,17_30,NaN,No Relationship
72630,National government must also work with subnat...,Many urban organizations and associations have...,9_7,11_10,NaN,Support

rel_robertaL
No Relationship    53172
Support            44980
Rephrase            2509
Attack               854
Name: count, dtype: int64

#### Deepseek r1 70B extraction

In [4]:
prefix = "intra_goalGLOBAL_SGD2023_deepseek-r1-70b"   
rel_col = f"rel_{model_name}"
BATCH_SIZE = 250
MAX_LENGTH = compute_max_length(process_rel_path, prefix, tokenizer)
print(f"Using MAX_LENGTH = {MAX_LENGTH}")

args_classified = classify_relationships_hf(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_robertaL"].value_counts()

Using MAX_LENGTH = 372

Processing: /kaggle/working/TFM/Data/Relationships No Keywords/intra_goalGLOBAL_SGD2023_deepseek-r1-70b.csv
Check first 5 predictions labels:

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: Despite this alarming development, the SDGs are still achievable. None of their objectives are beyond our reach.
Label: Attack


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: The world is off track, but that is all the more reason to double down on the SDGs.
Label: Support


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
Label: Support


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.
Label: Support


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: All countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national SDG strategies and commit to strengthening multilateralism.
Label: Support


  Progress: 250/17113 relations classified...
  Progress: 500/17113 relations classified...
  Progress: 750/17113 relations classified...
  Progress: 1000/17113 relations classified...
  Progress: 1250/17113 relations classified...
  Progress: 1500/17113 relations classified...
  Progress: 1750/17113 relations classified...
  Progress: 2000/17113 relations classified...
  Progress: 2250/17113 relations classified...
  Progress: 2500/17113 relations classified...
  Progress: 2750/17113 relations classified...
  Progress: 3000/17113 relations classified...
  Progress: 3250/17113 relations classified...
  Progress: 3500/17113 relations classified...
  Progress: 3750/17113 relations classified...
  Progress: 4000/17113 relations classified...
  Progress: 4250/17113 relations classified...
  Progress: 4500/17113 relations classified...
  Progress: 4750/17113 relations classified...
  Progress: 5000/17113 relations classified...
  Progress: 5250/17113 relations classified...
  Progress: 5500/17113 relations classified...
  Progress: 5750/17113 relations classified...
  Progress: 6000/17113 relations classified...
  Progress: 6250/17113 relations classified...
  Progress: 6500/17113 relations classified...
  Progress: 6750/17113 relations classified...
  Progress: 7000/17113 relations classified...
  Progress: 7250/17113 relations classified...
  Progress: 7500/17113 relations classified...
  Progress: 7750/17113 relations classified...
  Progress: 8000/17113 relations classified...
  Progress: 8250/17113 relations classified...
  Progress: 8500/17113 relations classified...
  Progress: 8750/17113 relations classified...
  Progress: 9000/17113 relations classified...
  Progress: 9250/17113 relations classified...
  Progress: 9500/17113 relations classified...
  Progress: 9750/17113 relations classified...
  Progress: 10000/17113 relations classified...
  Progress: 10250/17113 relations classified...
  Progress: 10500/17113 relations classified...
  Progress: 10750/17113 relations classified...
  Progress: 11000/17113 relations classified...
  Progress: 11250/17113 relations classified...
  Progress: 11500/17113 relations classified...
  Progress: 11750/17113 relations classified...
  Progress: 12000/17113 relations classified...
  Progress: 12250/17113 relations classified...
  Progress: 12500/17113 relations classified...
  Progress: 12750/17113 relations classified...
  Progress: 13000/17113 relations classified...
  Progress: 13250/17113 relations classified...
  Progress: 13500/17113 relations classified...
  Progress: 13750/17113 relations classified...
  Progress: 14000/17113 relations classified...
  Progress: 14250/17113 relations classified...
  Progress: 14500/17113 relations classified...
  Progress: 14750/17113 relations classified...
  Progress: 15000/17113 relations classified...
  Progress: 15250/17113 relations classified...
  Progress: 15500/17113 relations classified...
  Progress: 15750/17113 relations classified...
  Progress: 16000/17113 relations classified...
  Progress: 16250/17113 relations classified...
  Progress: 16500/17113 relations classified...
  Progress: 16750/17113 relations classified...
  Progress: 17000/17113 relations classified...
  Progress: 17113/17113 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships No Keywords/intra_goalGLOBAL_SGD2023_deepseek-r1-70b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_robertaL
4855,"At their core, the SDGs are an investment agenda.","Finally, the SDG Index contributes to global e...",0_39,0_137,NaN,Support
6107,Some other G20 countries have shown weak commi...,Global infrastructure programs like China’s Be...,0_53,0_66,NaN,Support
6431,Many of them lack an adequately high SDG commi...,The SDG Index is a flagship instrument to prom...,0_56,0_132,NaN,Support
11716,1. Universal quality education and innovation-...,5. Private capital markets continue to direct ...,9_0,9_4,NaN,No Relationship
6378,Many of them lack an adequately high SDG commi...,The SDG Academy is also building partnerships ...,0_56,0_79,NaN,Support

rel_robertaL
Support            11430
No Relationship     4690
Rephrase             676
Attack               317
Name: count, dtype: int64

In [5]:
prefix = "cross_goalGLOBAL_SGD2023_deepseek-r1-70b"   
rel_col = f"rel_{model_name}"
BATCH_SIZE = 250
MAX_LENGTH = compute_max_length(process_rel_path, prefix, tokenizer)
print(f"Using MAX_LENGTH = {MAX_LENGTH}")

args_classified = classify_relationships_hf(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_robertaL"].value_counts()

Using MAX_LENGTH = 398

Processing: /kaggle/working/TFM/Data/Relationships No Keywords/cross_goalGLOBAL_SGD2023_deepseek-r1-70b.csv
Check first 5 predictions labels:

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.
Label: Support


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: The grim reality is that at the midpoint of the 2030 Agenda, the SDGs are far off track.
Label: Rephrase


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: At the global level, averaging across countries, not a single SDG is currently projected to be met by 2030, with the poorest countries struggling the most.
Label: Rephrase


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: 1. Increased funding from the multilateral develop-ment banks (MDBs) and public development banks (PDBs) to low- and middle-income countries, linked to investments in the SDGs;
Label: Support


- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
-Arg2: 2. Enhancement of relief for countries facing debt distress;
Label: No Relationship


  Progress: 250/135515 relations classified...
  Progress: 500/135515 relations classified...
  Progress: 750/135515 relations classified...
  Progress: 1000/135515 relations classified...
  Progress: 1250/135515 relations classified...
  Progress: 1500/135515 relations classified...
  Progress: 1750/135515 relations classified...
  Progress: 2000/135515 relations classified...
  Progress: 2250/135515 relations classified...
  Progress: 2500/135515 relations classified...
  Progress: 2750/135515 relations classified...
  Progress: 3000/135515 relations classified...
  Progress: 3250/135515 relations classified...
  Progress: 3500/135515 relations classified...
  Progress: 3750/135515 relations classified...
  Progress: 4000/135515 relations classified...
  Progress: 4250/135515 relations classified...
  Progress: 4500/135515 relations classified...
  Progress: 4750/135515 relations classified...
  Progress: 5000/135515 relations classified...
  Progress: 5250/135515 relations classified...
  Progress: 5500/135515 relations classified...
  Progress: 5750/135515 relations classified...
  Progress: 6000/135515 relations classified...
  Progress: 6250/135515 relations classified...
  Progress: 6500/135515 relations classified...
  Progress: 6750/135515 relations classified...
  Progress: 7000/135515 relations classified...
  Progress: 7250/135515 relations classified...
  Progress: 7500/135515 relations classified...
  Progress: 7750/135515 relations classified...
  Progress: 8000/135515 relations classified...
  Progress: 8250/135515 relations classified...
  Progress: 8500/135515 relations classified...
  Progress: 8750/135515 relations classified...
  Progress: 9000/135515 relations classified...
  Progress: 9250/135515 relations classified...
  Progress: 9500/135515 relations classified...
  Progress: 9750/135515 relations classified...
  Progress: 10000/135515 relations classified...
  Progress: 10250/135515 relations classified...
  Progress: 10500/135515 relations classified...
  Progress: 10750/135515 relations classified...
  Progress: 11000/135515 relations classified...
  Progress: 11250/135515 relations classified...
  Progress: 11500/135515 relations classified...
  Progress: 11750/135515 relations classified...
  Progress: 12000/135515 relations classified...
  Progress: 12250/135515 relations classified...
  Progress: 12500/135515 relations classified...
  Progress: 12750/135515 relations classified...
  Progress: 13000/135515 relations classified...
  Progress: 13250/135515 relations classified...
  Progress: 13500/135515 relations classified...
  Progress: 13750/135515 relations classified...
  Progress: 14000/135515 relations classified...
  Progress: 14250/135515 relations classified...
  Progress: 14500/135515 relations classified...
  Progress: 14750/135515 relations classified...
  Progress: 15000/135515 relations classified...
  Progress: 15250/135515 relations classified...
  Progress: 15500/135515 relations classified...
  Progress: 15750/135515 relations classified...
  Progress: 16000/135515 relations classified...
  Progress: 16250/135515 relations classified...
  Progress: 16500/135515 relations classified...
  Progress: 16750/135515 relations classified...
  Progress: 17000/135515 relations classified...
  Progress: 17250/135515 relations classified...
  Progress: 17500/135515 relations classified...
  Progress: 17750/135515 relations classified...
  Progress: 18000/135515 relations classified...
  Progress: 18250/135515 relations classified...
  Progress: 18500/135515 relations classified...
  Progress: 18750/135515 relations classified...
  Progress: 19000/135515 relations classified...
  Progress: 19250/135515 relations classified...
  Progress: 19500/135515 relations classified...
  Progress: 19750/135515 relations classified...
  Progress: 20000/135515 relations classified...
  Progress: 20250/135515 relations classified...
  Progress: 20500/135515 relations classified...
  Progress: 20750/135515 relations classified...
  Progress: 21000/135515 relations classified...
  Progress: 21250/135515 relations classified...
  Progress: 21500/135515 relations classified...
  Progress: 21750/135515 relations classified...
  Progress: 22000/135515 relations classified...
  Progress: 22250/135515 relations classified...
  Progress: 22500/135515 relations classified...
  Progress: 22750/135515 relations classified...
  Progress: 23000/135515 relations classified...
  Progress: 23250/135515 relations classified...
  Progress: 23500/135515 relations classified...
  Progress: 23750/135515 relations classified...
  Progress: 24000/135515 relations classified...
  Progress: 24250/135515 relations classified...
  Progress: 24500/135515 relations classified...
  Progress: 24750/135515 relations classified...
  Progress: 25000/135515 relations classified...
  Progress: 25250/135515 relations classified...
  Progress: 25500/135515 relations classified...
  Progress: 25750/135515 relations classified...
  Progress: 26000/135515 relations classified...
  Progress: 26250/135515 relations classified...
  Progress: 26500/135515 relations classified...
  Progress: 26750/135515 relations classified...
  Progress: 27000/135515 relations classified...
  Progress: 27250/135515 relations classified...
  Progress: 27500/135515 relations classified...
  Progress: 27750/135515 relations classified...
  Progress: 28000/135515 relations classified...
  Progress: 28250/135515 relations classified...
  Progress: 28500/135515 relations classified...
  Progress: 28750/135515 relations classified...
  Progress: 29000/135515 relations classified...
  Progress: 29250/135515 relations classified...
  Progress: 29500/135515 relations classified...
  Progress: 29750/135515 relations classified...
  Progress: 30000/135515 relations classified...
  Progress: 30250/135515 relations classified...
  Progress: 30500/135515 relations classified...
  Progress: 30750/135515 relations classified...
  Progress: 31000/135515 relations classified...
  Progress: 31250/135515 relations classified...
  Progress: 31500/135515 relations classified...
  Progress: 31750/135515 relations classified...
  Progress: 32000/135515 relations classified...
  Progress: 32250/135515 relations classified...
  Progress: 32500/135515 relations classified...
  Progress: 32750/135515 relations classified...
  Progress: 33000/135515 relations classified...
  Progress: 33250/135515 relations classified...
  Progress: 33500/135515 relations classified...
  Progress: 33750/135515 relations classified...
  Progress: 34000/135515 relations classified...
  Progress: 34250/135515 relations classified...
  Progress: 34500/135515 relations classified...
  Progress: 34750/135515 relations classified...
  Progress: 35000/135515 relations classified...
  Progress: 35250/135515 relations classified...
  Progress: 35500/135515 relations classified...
  Progress: 35750/135515 relations classified...
  Progress: 36000/135515 relations classified...
  Progress: 36250/135515 relations classified...
  Progress: 36500/135515 relations classified...
  Progress: 36750/135515 relations classified...
  Progress: 37000/135515 relations classified...
  Progress: 37250/135515 relations classified...
  Progress: 37500/135515 relations classified...
  Progress: 37750/135515 relations classified...
  Progress: 38000/135515 relations classified...
  Progress: 38250/135515 relations classified...
  Progress: 38500/135515 relations classified...
  Progress: 38750/135515 relations classified...
  Progress: 39000/135515 relations classified...
  Progress: 39250/135515 relations classified...
  Progress: 39500/135515 relations classified...
  Progress: 39750/135515 relations classified...
  Progress: 40000/135515 relations classified...
  Progress: 40250/135515 relations classified...
  Progress: 40500/135515 relations classified...
  Progress: 40750/135515 relations classified...
  Progress: 41000/135515 relations classified...
  Progress: 41250/135515 relations classified...
  Progress: 41500/135515 relations classified...
  Progress: 41750/135515 relations classified...
  Progress: 42000/135515 relations classified...
  Progress: 42250/135515 relations classified...
  Progress: 42500/135515 relations classified...
  Progress: 42750/135515 relations classified...
  Progress: 43000/135515 relations classified...
  Progress: 43250/135515 relations classified...
  Progress: 43500/135515 relations classified...
  Progress: 43750/135515 relations classified...
  Progress: 44000/135515 relations classified...
  Progress: 44250/135515 relations classified...
  Progress: 44500/135515 relations classified...
  Progress: 44750/135515 relations classified...
  Progress: 45000/135515 relations classified...
  Progress: 45250/135515 relations classified...
  Progress: 45500/135515 relations classified...
  Progress: 45750/135515 relations classified...
  Progress: 46000/135515 relations classified...
  Progress: 46250/135515 relations classified...
  Progress: 46500/135515 relations classified...
  Progress: 46750/135515 relations classified...
  Progress: 47000/135515 relations classified...
  Progress: 47250/135515 relations classified...
  Progress: 47500/135515 relations classified...
  Progress: 47750/135515 relations classified...
  Progress: 48000/135515 relations classified...
  Progress: 48250/135515 relations classified...
  Progress: 48500/135515 relations classified...
  Progress: 48750/135515 relations classified...
  Progress: 49000/135515 relations classified...
  Progress: 49250/135515 relations classified...
  Progress: 49500/135515 relations classified...
  Progress: 49750/135515 relations classified...
  Progress: 50000/135515 relations classified...
  Progress: 50250/135515 relations classified...
  Progress: 50500/135515 relations classified...
  Progress: 50750/135515 relations classified...
  Progress: 51000/135515 relations classified...
  Progress: 51250/135515 relations classified...
  Progress: 51500/135515 relations classified...
  Progress: 51750/135515 relations classified...
  Progress: 52000/135515 relations classified...
  Progress: 52250/135515 relations classified...
  Progress: 52500/135515 relations classified...
  Progress: 52750/135515 relations classified...
  Progress: 53000/135515 relations classified...
  Progress: 53250/135515 relations classified...
  Progress: 53500/135515 relations classified...
  Progress: 53750/135515 relations classified...
  Progress: 54000/135515 relations classified...
  Progress: 54250/135515 relations classified...
  Progress: 54500/135515 relations classified...
  Progress: 54750/135515 relations classified...
  Progress: 55000/135515 relations classified...
  Progress: 55250/135515 relations classified...
  Progress: 55500/135515 relations classified...
  Progress: 55750/135515 relations classified...
  Progress: 56000/135515 relations classified...
  Progress: 56250/135515 relations classified...
  Progress: 56500/135515 relations classified...
  Progress: 56750/135515 relations classified...
  Progress: 57000/135515 relations classified...
  Progress: 57250/135515 relations classified...
  Progress: 57500/135515 relations classified...
  Progress: 57750/135515 relations classified...
  Progress: 58000/135515 relations classified...
  Progress: 58250/135515 relations classified...
  Progress: 58500/135515 relations classified...
  Progress: 58750/135515 relations classified...
  Progress: 59000/135515 relations classified...
  Progress: 59250/135515 relations classified...
  Progress: 59500/135515 relations classified...
  Progress: 59750/135515 relations classified...
  Progress: 60000/135515 relations classified...
  Progress: 60250/135515 relations classified...
  Progress: 60500/135515 relations classified...
  Progress: 60750/135515 relations classified...
  Progress: 61000/135515 relations classified...
  Progress: 61250/135515 relations classified...
  Progress: 61500/135515 relations classified...
  Progress: 61750/135515 relations classified...
  Progress: 62000/135515 relations classified...
  Progress: 62250/135515 relations classified...
  Progress: 62500/135515 relations classified...
  Progress: 62750/135515 relations classified...
  Progress: 63000/135515 relations classified...
  Progress: 63250/135515 relations classified...
  Progress: 63500/135515 relations classified...
  Progress: 63750/135515 relations classified...
  Progress: 64000/135515 relations classified...
  Progress: 64250/135515 relations classified...
  Progress: 64500/135515 relations classified...
  Progress: 64750/135515 relations classified...
  Progress: 65000/135515 relations classified...
  Progress: 65250/135515 relations classified...
  Progress: 65500/135515 relations classified...
  Progress: 65750/135515 relations classified...
  Progress: 66000/135515 relations classified...
  Progress: 66250/135515 relations classified...
  Progress: 66500/135515 relations classified...
  Progress: 66750/135515 relations classified...
  Progress: 67000/135515 relations classified...
  Progress: 67250/135515 relations classified...
  Progress: 67500/135515 relations classified...
  Progress: 67750/135515 relations classified...
  Progress: 68000/135515 relations classified...
  Progress: 68250/135515 relations classified...
  Progress: 68500/135515 relations classified...
  Progress: 68750/135515 relations classified...
  Progress: 69000/135515 relations classified...
  Progress: 69250/135515 relations classified...
  Progress: 69500/135515 relations classified...
  Progress: 69750/135515 relations classified...
  Progress: 70000/135515 relations classified...
  Progress: 70250/135515 relations classified...
  Progress: 70500/135515 relations classified...
  Progress: 70750/135515 relations classified...
  Progress: 71000/135515 relations classified...
  Progress: 71250/135515 relations classified...
  Progress: 71500/135515 relations classified...
  Progress: 71750/135515 relations classified...
  Progress: 72000/135515 relations classified...
  Progress: 72250/135515 relations classified...
  Progress: 72500/135515 relations classified...
  Progress: 72750/135515 relations classified...
  Progress: 73000/135515 relations classified...
  Progress: 73250/135515 relations classified...
  Progress: 73500/135515 relations classified...
  Progress: 73750/135515 relations classified...
  Progress: 74000/135515 relations classified...
  Progress: 74250/135515 relations classified...
  Progress: 74500/135515 relations classified...
  Progress: 74750/135515 relations classified...
  Progress: 75000/135515 relations classified...
  Progress: 75250/135515 relations classified...
  Progress: 75500/135515 relations classified...
  Progress: 75750/135515 relations classified...
  Progress: 76000/135515 relations classified...
  Progress: 76250/135515 relations classified...
  Progress: 76500/135515 relations classified...
  Progress: 76750/135515 relations classified...
  Progress: 77000/135515 relations classified...
  Progress: 77250/135515 relations classified...
  Progress: 77500/135515 relations classified...
  Progress: 77750/135515 relations classified...
  Progress: 78000/135515 relations classified...
  Progress: 78250/135515 relations classified...
  Progress: 78500/135515 relations classified...
  Progress: 78750/135515 relations classified...
  Progress: 79000/135515 relations classified...
  Progress: 79250/135515 relations classified...
  Progress: 79500/135515 relations classified...
  Progress: 79750/135515 relations classified...
  Progress: 80000/135515 relations classified...
  Progress: 80250/135515 relations classified...
  Progress: 80500/135515 relations classified...
  Progress: 80750/135515 relations classified...
  Progress: 81000/135515 relations classified...
  Progress: 81250/135515 relations classified...
  Progress: 81500/135515 relations classified...
  Progress: 81750/135515 relations classified...
  Progress: 82000/135515 relations classified...
  Progress: 82250/135515 relations classified...
  Progress: 82500/135515 relations classified...
  Progress: 82750/135515 relations classified...
  Progress: 83000/135515 relations classified...
  Progress: 83250/135515 relations classified...
  Progress: 83500/135515 relations classified...
  Progress: 83750/135515 relations classified...
  Progress: 84000/135515 relations classified...
  Progress: 84250/135515 relations classified...
  Progress: 84500/135515 relations classified...
  Progress: 84750/135515 relations classified...
  Progress: 85000/135515 relations classified...
  Progress: 85250/135515 relations classified...
  Progress: 85500/135515 relations classified...
  Progress: 85750/135515 relations classified...
  Progress: 86000/135515 relations classified...
  Progress: 86250/135515 relations classified...
  Progress: 86500/135515 relations classified...
  Progress: 86750/135515 relations classified...
  Progress: 87000/135515 relations classified...
  Progress: 87250/135515 relations classified...
  Progress: 87500/135515 relations classified...
  Progress: 87750/135515 relations classified...
  Progress: 88000/135515 relations classified...
  Progress: 88250/135515 relations classified...
  Progress: 88500/135515 relations classified...
  Progress: 88750/135515 relations classified...
  Progress: 89000/135515 relations classified...
  Progress: 89250/135515 relations classified...
  Progress: 89500/135515 relations classified...
  Progress: 89750/135515 relations classified...
  Progress: 90000/135515 relations classified...
  Progress: 90250/135515 relations classified...
  Progress: 90500/135515 relations classified...
  Progress: 90750/135515 relations classified...
  Progress: 91000/135515 relations classified...
  Progress: 91250/135515 relations classified...
  Progress: 91500/135515 relations classified...
  Progress: 91750/135515 relations classified...
  Progress: 92000/135515 relations classified...
  Progress: 92250/135515 relations classified...
  Progress: 92500/135515 relations classified...
  Progress: 92750/135515 relations classified...
  Progress: 93000/135515 relations classified...
  Progress: 93250/135515 relations classified...
  Progress: 93500/135515 relations classified...
  Progress: 93750/135515 relations classified...
  Progress: 94000/135515 relations classified...
  Progress: 94250/135515 relations classified...
  Progress: 94500/135515 relations classified...
  Progress: 94750/135515 relations classified...
  Progress: 95000/135515 relations classified...
  Progress: 95250/135515 relations classified...

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_robertaL
55874,"According to the OECD, only one in 10 students...",Open sharing of data and knowledge across thes...,0_109,17_53,NaN,Support
89948,"The SDSN’s flagship educational initiative, th...",National governments must ensure both the dome...,4_8,17_20,NaN,No Relationship
122524,We also need responsible business leadership l...,Current geopolitical tensions are hindering SD...,12_5,17_15,NaN,Support
60587,"Education builds human capital, which in turn ...",An estimated 1.8 billion people depend on drin...,1_22,6_1,NaN,No Relationship
29783,"The collaboration with SDSN is ongoing, with t...",More than half of the 192 local and regional g...,0_139,11_14,NaN,Support

rel_robertaL
No Relationship    70902
Support            59883
Rephrase            3156
Attack              1574
Name: count, dtype: int64