# TFM: Análisis de Políticas de Sostenibilidad mediante técnicas de Argumentacion Computacional

## Clasificación de relaciones con MoritzLaurer/DeBERTa-v3-base-mnli-fever-anli from microsoft/DeBERTa-v3-base

Model page: https://huggingface.co/MoritzLaurer/DeBERTa-v3-base-mnli-fever-anli

Entailment is calculated in both directions (forward probs (Arg1->Arg2) and backward probs (Arg2->Arg1)), then the label is decided with the following criteria:
   
Bidirectional decision:
  - Rephrase: high entailment both ways, low contradiction
  - Attack: contradiction high either way
  - Support: entailment high at least one way, and not clearly neutral/contradictory
  - No Relationship: otherwise

# No keywords

In [1]:
import os
import re
import math
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import gc

process_rel_path = r"/kaggle/working/TFM/Data/Relationships No Keywords"

model_name = "MoritzLaurer/DeBERTa-v3-base-mnli-fever-anli"
device = "cuda" if torch.cuda.is_available() else "cpu"
BATCH_SIZE = 50                 
MODEL_TAG = "deberta"      
VALID_OUT = {"Support", "Attack", "Rephrase", "No Relationship"}

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name).to(device)
model.eval()

# figure out label 
id2label = {int(k): v.lower() for k, v in model.config.id2label.items()}
label2id = {v: int(k) for k, v in id2label.items()}

print(f'DeBERTa v3 base mnli labels {label2id}')

IDX_ENT = label2id["entailment"]
IDX_CON = label2id["contradiction"]
IDX_NEU = label2id["neutral"]

# Heuristic thresholds 
ENT_THR       = 0.50   
CONTR_THR     = 0.50   
REPHRASE_THR  = 0.75  
MAX_NEUTRAL   = 0.70   

# Margins: “X wins by at least this much”
SUPPORT_MARGIN = 0.10  # p_ent - p_con must exceed this (either direction)
ATTACK_MARGIN  = 0.10  # p_con - p_ent must exceed this (either direction)

tokenizer_config.json: 0.00B [00:00, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/23.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/286 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

2025-08-25 13:39:14.239681: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1756129154.570518      19 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1756129154.664623      19 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

model.safetensors:   0%|          | 0.00/369M [00:00<?, ?B/s]

DeBERTa v3 base mnli labels {'entailment': 0, 'neutral': 1, 'contradiction': 2}

In [2]:
!git clone https://github.com/camipalo/TFM.git

Cloning into 'TFM'...
remote: Enumerating objects: 2459, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 2459 (delta 9), reused 6 (delta 5), pack-reused 2444 (from 2)
Receiving objects: 100% (2459/2459), 97.50 MiB | 17.15 MiB/s, done.
Resolving deltas: 100% (2065/2065), done.
Updating files: 100% (1061/1061), done.

In [3]:
def preprocess_text(s):
    if not isinstance(s, str):
        return ""
    s = s.strip().lower()
    s = re.sub(r"\s+", " ", s)
    return s

@torch.no_grad()
def nli_probs(pairs, max_length: int):
    if not pairs:
        return np.zeros((0,3)), np.zeros((0,3))

    a1 = [preprocess_text(x[0]) for x in pairs]
    a2 = [preprocess_text(x[1]) for x in pairs]

    # forward: premise=a1, hypothesis=a2
    enc_f = tokenizer(a1, a2, return_tensors="pt", padding=True, truncation=True,
                      max_length=max_length).to(device)
    logits_f = model(**enc_f).logits
    prob_f = torch.softmax(logits_f, dim=-1).detach().cpu().numpy()

    # backward: premise=a2, hypothesis=a1
    enc_b = tokenizer(a2, a1, return_tensors="pt", padding=True, truncation=True,
                      max_length=max_length).to(device)
    logits_b = model(**enc_b).logits
    prob_b = torch.softmax(logits_b, dim=-1).detach().cpu().numpy()

    return prob_f, prob_b

def decide_label(p_ent_f, p_con_f, p_neu_f, p_ent_b, p_con_b, p_neu_b):
    # 1) Hard guard: if both sides look very neutral, say NR
    if max(p_neu_f, p_neu_b) >= MAX_NEUTRAL:
        return "No Relationship"

    # 2) Rephrase: bi-directional entailment and low contradiction
    if min(p_ent_f, p_ent_b) >= REPHRASE_THR and max(p_con_f, p_con_b) <= (1 - REPHRASE_THR):
        return "Rephrase"

    # 3) Attack: contradiction wins with margin OR strong contradiction
    if (
        (p_con_f - p_ent_f) >= ATTACK_MARGIN or
        (p_con_b - p_ent_b) >= ATTACK_MARGIN or
        p_con_f >= CONTR_THR or
        p_con_b >= CONTR_THR
    ):
        return "Attack"

    # 4) Support: entailment wins with margin OR clears lowered threshold
    if (
        (p_ent_f - p_con_f) >= SUPPORT_MARGIN or
        (p_ent_b - p_con_b) >= SUPPORT_MARGIN or
        p_ent_f >= ENT_THR or
        p_ent_b >= ENT_THR
    ):
        return "Support"

    # 5) Fallback
    return "No Relationship"


def free_cuda():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

def compute_max_length(input_dir, prefix_substring, safety_limit=512):
    max_len = 0
    files = [f for f in os.listdir(input_dir) if f.endswith(".csv") and prefix_substring in f]
    for fn in files:
        path = os.path.join(input_dir, fn)
        try:
            df = pd.read_csv(path)
        except Exception:
            continue
        if "SDGarg1" not in df.columns or "SDGarg2" not in df.columns:
            continue
        for a, b in zip(df["SDGarg1"], df["SDGarg2"]):
            a = preprocess_text(str(a) if pd.notna(a) else "")
            b = preprocess_text(str(b) if pd.notna(b) else "")
            ids = tokenizer(a, b, truncation=False, padding=False)["input_ids"]
            max_len = max(max_len, len(ids))
    if max_len == 0:
        max_len = 128
    return min(max_len, safety_limit)

def classify_relationships_deberta(input_dir, prefix_substring, model_tag=MODEL_TAG):
    files = [f for f in os.listdir(input_dir) if f.endswith(".csv") and prefix_substring in f]
    if not files:
        print(f"No CSVs found in '{input_dir}' containing '{prefix_substring}'.")
        return

    MAX_LENGTH = compute_max_length(input_dir, prefix_substring, safety_limit=512)
    print(f"Using MAX_LENGTH = {MAX_LENGTH}")

    rel_col = f"rel_{model_tag}"

    for fn in files:
        path = os.path.join(input_dir, fn)
        print(f"\nProcessing: {path}")
        df = pd.read_csv(path)

        if "SDGarg1" not in df.columns or "SDGarg2" not in df.columns:
            print(f"  Skipped (missing SDGarg1/SDGarg2): {fn}")
            continue

        df[rel_col] = ""

        n = len(df)
        total_done = 0
        first_examples = []

        batches = math.ceil(n / BATCH_SIZE)
        for bi in range(batches):
            s = bi * BATCH_SIZE
            e = min((bi + 1) * BATCH_SIZE, n)
            chunk = df.iloc[s:e]

            pairs = list(zip(chunk["SDGarg1"].astype(str).tolist(),
                             chunk["SDGarg2"].astype(str).tolist()))
            try:
                prob_f, prob_b = nli_probs(pairs, max_length=MAX_LENGTH)
                labels = []
                for i in range(len(pairs)):
                    pf = prob_f[i]; pb = prob_b[i]
                    p_ent_f, p_neu_f, p_con_f = pf[IDX_ENT], pf[IDX_NEU], pf[IDX_CON]
                    p_ent_b, p_neu_b, p_con_b = pb[IDX_ENT], pb[IDX_NEU], pb[IDX_CON]
                    lab = decide_label(p_ent_f, p_con_f, p_neu_f, p_ent_b, p_con_b, p_neu_b)
                    labels.append(lab)
            except Exception as ex:
                print(f"  Batch {bi+1}/{batches} error: {ex}. Marking 'No Relationship'.")
                labels = ["No Relationship"] * len(pairs)

            df.loc[chunk.index, rel_col] = labels

            # first 5 examples
            for (a1, a2), lab in zip(pairs, labels):
                if len(first_examples) < 5:
                    first_examples.append((a1, a2, lab))
                elif len(first_examples) == 5:
                    print("Sample predictions (first 5):\n")
                    for _a1, _a2, _lab in first_examples:
                        print(f"- Arg1: {_a1}\n- Arg2: {_a2}\n  Label: {_lab}\n")
                    first_examples.append((a1, a2, lab))

            total_done += len(pairs)
            if total_done % 100 < BATCH_SIZE:
                print(f"  Progress: {total_done}/{n} relations classified...")

        # Final label validation 
        mask_nan = df["SDGarg1"].isna() | df["SDGarg2"].isna()
        df.loc[mask_nan, rel_col] = "No Relationship"
        bad = ~df[rel_col].isin(VALID_OUT)
        if bad.any():
            df.loc[bad, rel_col] = "No Relationship"

        df.to_csv(path, index=False, encoding="utf-8")
        free_cuda()
        print(f"Saved: {path}")
    return df

## GLOBAL SDG 2023

#### Qwen2.5 3B extraction

In [4]:
prefix = "intra_goalGLOBAL_SGD2023_qwen2.5-3b"   

args_classified = classify_relationships_deberta(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_deberta"].value_counts()

Using MAX_LENGTH = 160

Processing: /kaggle/working/TFM/Data/Relationships No Keywords/intra_goalGLOBAL_SGD2023_qwen2.5-3b.csv
Sample predictions (first 5):

- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
- Arg2: According to major international studies, few teenagers can differentiate between a fact and an opinion.
  Label: No Relationship

- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
- Arg2: As the world’s nations prepare to meet in September to review the progress the world has made so far towards achieving the SDGs, at the midpoint of the 2030 Agenda, SDSN emphasizes six areas for immediate action.
  Label: No Relationship

- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
- Arg2: All UN Member States should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of 'leave no one behind'.
  Label: No Relationship

- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
- Arg2: The SDGs are not only a public policy framework; they are an ethical imperative. They are grounded in the Universal Declaration of Human Rights, which celebrates its 75th anniversary this year.
  Label: No Relationship

- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
- Arg2: The current loss of species rate is 1,000–10,000 times more than the natural extinction rate.
  Label: No Relationship

  Progress: 100/1058 relations classified...
  Progress: 200/1058 relations classified...
  Progress: 300/1058 relations classified...
  Progress: 400/1058 relations classified...
  Progress: 500/1058 relations classified...
  Progress: 600/1058 relations classified...
  Progress: 700/1058 relations classified...
  Progress: 800/1058 relations classified...
  Progress: 900/1058 relations classified...
  Progress: 1000/1058 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships No Keywords/intra_goalGLOBAL_SGD2023_qwen2.5-3b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_llama,rel_deberta
374,Although on average the world has made some pr...,"In response to feedback, since 2018 we have su...",0_15,0_30,NaN,No Relationship,No Relationship
891,"The interconnected environmental, social, and ...","The United States, as the world’s biggest econ...",13_3,13_5,NaN,Support,No Relationship
868,Today’s land-use practices and food systems ha...,"Yet the SDG Dashboards rate rich countries, in...",12_8,12_9,NaN,Support,No Relationship
935,"The GFA includes multilateral institutions, na...",47 countries have committed to submitting a VN...,16_3,16_7,NaN,No Relationship,No Relationship
405,Official high-level speeches and the preparati...,47 countries have submitted a VNR this year: o...,0_18,0_19,NaN,Support,No Relationship

rel_deberta
No Relationship    1046
Attack                6
Support               4
Rephrase              2
Name: count, dtype: int64

In [5]:
prefix = "cross_goalGLOBAL_SGD2023_qwen2.5-3b"   

args_classified = classify_relationships_deberta(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_deberta"].value_counts()

Using MAX_LENGTH = 172

Processing: /kaggle/working/TFM/Data/Relationships No Keywords/cross_goalGLOBAL_SGD2023_qwen2.5-3b.csv
Sample predictions (first 5):

- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
- Arg2: only limited progress is being made on the environmental and biodiversity goals, including SDG 12 (Responsible Consumption and Production), SDG 13 (Climate Action), SDG 14 (Life Below Water), and SDG 15 (Life on Land)
  Label: No Relationship

- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
- Arg2: And global cooperation has ebbed as geopolitical tensions have risen.
  Label: No Relationship

- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
- Arg2: The interconnected environmental, social, and health challenges can be characterized as a planetary health crisis, caused by human activities such as industrialization, urbanization, deforestation, and the burning of fossil fuels.
  Label: No Relationship

- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
- Arg2: 12. Sachs JD, Schmidt-Traub G., 2020. Speaking truth to power about the SDGs, Nature. https://www.nature.com/articles/d41586-020-02373-7
  Label: No Relationship

- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
- Arg2: Deep, chronic, and crippling under-investment in virtually all low-income countries (LICs) and lower-middle-income countries (LMICs). In 2022, Investment per person in the LICs averaged a meagre US$175 per person, compared with US$11,535 per person in the HICs. (Table 1.1)
  Label: No Relationship

  Progress: 100/11822 relations classified...
  Progress: 200/11822 relations classified...
  Progress: 300/11822 relations classified...
  Progress: 400/11822 relations classified...
  Progress: 500/11822 relations classified...
  Progress: 600/11822 relations classified...
  Progress: 700/11822 relations classified...
  Progress: 800/11822 relations classified...
  Progress: 900/11822 relations classified...
  Progress: 1000/11822 relations classified...
  Progress: 1100/11822 relations classified...
  Progress: 1200/11822 relations classified...
  Progress: 1300/11822 relations classified...
  Progress: 1400/11822 relations classified...
  Progress: 1500/11822 relations classified...
  Progress: 1600/11822 relations classified...
  Progress: 1700/11822 relations classified...
  Progress: 1800/11822 relations classified...
  Progress: 1900/11822 relations classified...
  Progress: 2000/11822 relations classified...
  Progress: 2100/11822 relations classified...
  Progress: 2200/11822 relations classified...
  Progress: 2300/11822 relations classified...
  Progress: 2400/11822 relations classified...
  Progress: 2500/11822 relations classified...
  Progress: 2600/11822 relations classified...
  Progress: 2700/11822 relations classified...
  Progress: 2800/11822 relations classified...
  Progress: 2900/11822 relations classified...
  Progress: 3000/11822 relations classified...
  Progress: 3100/11822 relations classified...
  Progress: 3200/11822 relations classified...
  Progress: 3300/11822 relations classified...
  Progress: 3400/11822 relations classified...
  Progress: 3500/11822 relations classified...
  Progress: 3600/11822 relations classified...
  Progress: 3700/11822 relations classified...
  Progress: 3800/11822 relations classified...
  Progress: 3900/11822 relations classified...
  Progress: 4000/11822 relations classified...
  Progress: 4100/11822 relations classified...
  Progress: 4200/11822 relations classified...
  Progress: 4300/11822 relations classified...
  Progress: 4400/11822 relations classified...
  Progress: 4500/11822 relations classified...
  Progress: 4600/11822 relations classified...
  Progress: 4700/11822 relations classified...
  Progress: 4800/11822 relations classified...
  Progress: 4900/11822 relations classified...
  Progress: 5000/11822 relations classified...
  Progress: 5100/11822 relations classified...
  Progress: 5200/11822 relations classified...
  Progress: 5300/11822 relations classified...
  Progress: 5400/11822 relations classified...
  Progress: 5500/11822 relations classified...
  Progress: 5600/11822 relations classified...
  Progress: 5700/11822 relations classified...
  Progress: 5800/11822 relations classified...
  Progress: 5900/11822 relations classified...
  Progress: 6000/11822 relations classified...
  Progress: 6100/11822 relations classified...
  Progress: 6200/11822 relations classified...
  Progress: 6300/11822 relations classified...
  Progress: 6400/11822 relations classified...
  Progress: 6500/11822 relations classified...
  Progress: 6600/11822 relations classified...
  Progress: 6700/11822 relations classified...
  Progress: 6800/11822 relations classified...
  Progress: 6900/11822 relations classified...
  Progress: 7000/11822 relations classified...
  Progress: 7100/11822 relations classified...
  Progress: 7200/11822 relations classified...
  Progress: 7300/11822 relations classified...
  Progress: 7400/11822 relations classified...
  Progress: 7500/11822 relations classified...
  Progress: 7600/11822 relations classified...
  Progress: 7700/11822 relations classified...
  Progress: 7800/11822 relations classified...
  Progress: 7900/11822 relations classified...
  Progress: 8000/11822 relations classified...
  Progress: 8100/11822 relations classified...
  Progress: 8200/11822 relations classified...
  Progress: 8300/11822 relations classified...
  Progress: 8400/11822 relations classified...
  Progress: 8500/11822 relations classified...
  Progress: 8600/11822 relations classified...
  Progress: 8700/11822 relations classified...
  Progress: 8800/11822 relations classified...
  Progress: 8900/11822 relations classified...
  Progress: 9000/11822 relations classified...
  Progress: 9100/11822 relations classified...
  Progress: 9200/11822 relations classified...
  Progress: 9300/11822 relations classified...
  Progress: 9400/11822 relations classified...
  Progress: 9500/11822 relations classified...
  Progress: 9600/11822 relations classified...
  Progress: 9700/11822 relations classified...
  Progress: 9800/11822 relations classified...
  Progress: 9900/11822 relations classified...
  Progress: 10000/11822 relations classified...
  Progress: 10100/11822 relations classified...
  Progress: 10200/11822 relations classified...
  Progress: 10300/11822 relations classified...
  Progress: 10400/11822 relations classified...
  Progress: 10500/11822 relations classified...
  Progress: 10600/11822 relations classified...
  Progress: 10700/11822 relations classified...
  Progress: 10800/11822 relations classified...
  Progress: 10900/11822 relations classified...
  Progress: 11000/11822 relations classified...
  Progress: 11100/11822 relations classified...
  Progress: 11200/11822 relations classified...
  Progress: 11300/11822 relations classified...
  Progress: 11400/11822 relations classified...
  Progress: 11500/11822 relations classified...
  Progress: 11600/11822 relations classified...
  Progress: 11700/11822 relations classified...
  Progress: 11800/11822 relations classified...
  Progress: 11822/11822 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships No Keywords/cross_goalGLOBAL_SGD2023_qwen2.5-3b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_llama,rel_deberta
4159,And global cooperation has ebbed as geopolitic...,Ensure healthy lives and promote well-being fo...,1_1,3_1,NaN,No Relationship,No Relationship
2874,The SDG Index serves as a conversation opener ...,Ensure sustainable consumption and production ...,0_28,12_2,NaN,No Relationship,No Relationship
9815,The world has made some progress in strengthen...,"To achieve this feat, countries have embarked ...",9_3,17_14,NaN,Support,No Relationship
2597,"At their core, the SDGs are an investment agen...","Provincial, metropolitan, and city governments...",0_0,12_5,NaN,No Relationship,No Relationship
1397,"By design, Transformation 5 calls for regional...",Zero-carbon energy systems,0_21,7_3,NaN,No Relationship,No Relationship

rel_deberta
No Relationship    11636
Attack                77
Rephrase              77
Support               32
Name: count, dtype: int64

#### Gemma3 27B extraction

In [6]:
prefix = "intra_goalGLOBAL_SGD2023_gemma3-27b"   
rel_col = f"rel_{model_name}"

args_classified = classify_relationships_deberta(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_deberta"].value_counts()

Using MAX_LENGTH = 201

Processing: /kaggle/working/TFM/Data/Relationships No Keywords/intra_goalGLOBAL_SGD2023_gemma3-27b.csv
Sample predictions (first 5):

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Despite this alarming development, the SDGs are still achievable.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: National governments must ensure both domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation – by building a global governance and financial architecture that delivers the SDGs.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Achieving the SDGs requires global cooperation guided by the United Nations Charter.
  Label: No Relationship

  Progress: 100/4188 relations classified...
  Progress: 200/4188 relations classified...
  Progress: 300/4188 relations classified...
  Progress: 400/4188 relations classified...
  Progress: 500/4188 relations classified...
  Progress: 600/4188 relations classified...
  Progress: 700/4188 relations classified...
  Progress: 800/4188 relations classified...
  Progress: 900/4188 relations classified...
  Progress: 1000/4188 relations classified...
  Progress: 1100/4188 relations classified...
  Progress: 1200/4188 relations classified...
  Progress: 1300/4188 relations classified...
  Progress: 1400/4188 relations classified...
  Progress: 1500/4188 relations classified...
  Progress: 1600/4188 relations classified...
  Progress: 1700/4188 relations classified...
  Progress: 1800/4188 relations classified...
  Progress: 1900/4188 relations classified...
  Progress: 2000/4188 relations classified...
  Progress: 2100/4188 relations classified...
  Progress: 2200/4188 relations classified...
  Progress: 2300/4188 relations classified...
  Progress: 2400/4188 relations classified...
  Progress: 2500/4188 relations classified...
  Progress: 2600/4188 relations classified...
  Progress: 2700/4188 relations classified...
  Progress: 2800/4188 relations classified...
  Progress: 2900/4188 relations classified...
  Progress: 3000/4188 relations classified...
  Progress: 3100/4188 relations classified...
  Progress: 3200/4188 relations classified...
  Progress: 3300/4188 relations classified...
  Progress: 3400/4188 relations classified...
  Progress: 3500/4188 relations classified...
  Progress: 3600/4188 relations classified...
  Progress: 3700/4188 relations classified...
  Progress: 3800/4188 relations classified...
  Progress: 3900/4188 relations classified...
  Progress: 4000/4188 relations classified...
  Progress: 4100/4188 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships No Keywords/intra_goalGLOBAL_SGD2023_gemma3-27b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_llama,rel_deberta
1764,"It aligns closely with SDG Target 3.8, achievi...","In the SDGs, universal health care (UHC) is co...",3_11,3_12,NaN,Support,No Relationship
1583,Questions explored policy measures to address ...,poor countries need help to combat poverty.,1_17,1_19,NaN,Support,No Relationship
3219,There is no hope for global peace unless there...,The Board’s 2023 report lists six areas for ac...,16_7,16_9,NaN,Support,No Relationship
2259,Global resource consumption assessments for ra...,Unsustainable consumption is strongly intercon...,12_0,12_13,NaN,Support,No Relationship
1570,Peace and global cooperation mean nothing less...,Disadvantaged communities have lower access to...,1_14,1_18,NaN,No Relationship,No Relationship

rel_deberta
No Relationship    4109
Attack               77
Support               1
Rephrase              1
Name: count, dtype: int64

In [7]:
prefix = "cross_goalGLOBAL_SGD2023_gemma3-27b"   

args_classified = classify_relationships_deberta(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_deberta"].value_counts()

Using MAX_LENGTH = 253

Processing: /kaggle/working/TFM/Data/Relationships No Keywords/cross_goalGLOBAL_SGD2023_gemma3-27b.csv
Sample predictions (first 5):

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: At the global level, averaging across countries, not a single SDG is currently projected to be met by 2030, with the poorest countries struggling the most.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: As called for by United Nations Secretary-General António Guterres, the SDG Stimulus plan has five main components:
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Greatly increased funding for national and subnational governments and private businesses in the emerging economies, especially the low-income countries (LICs) and lower-middle-income countries (LMICs), to carry out needed SDG actions;
  Label: Attack

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: According to the annual SDG Index, global achievement of the SDGs rose only slightly, from 64 percent in 2015 to 66 percent in 2019 – far too slowly to meet the goals by 2030, and with highly uneven progress within and between countries.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Then with the onset of the pandemic, progress stopped.
  Label: No Relationship

  Progress: 100/50097 relations classified...
  Progress: 200/50097 relations classified...
  Progress: 300/50097 relations classified...
  Progress: 400/50097 relations classified...
  Progress: 500/50097 relations classified...
  Progress: 600/50097 relations classified...
  Progress: 700/50097 relations classified...
  Progress: 800/50097 relations classified...
  Progress: 900/50097 relations classified...
  Progress: 1000/50097 relations classified...
  Progress: 1100/50097 relations classified...
  Progress: 1200/50097 relations classified...
  Progress: 1300/50097 relations classified...
  Progress: 1400/50097 relations classified...
  Progress: 1500/50097 relations classified...
  Progress: 1600/50097 relations classified...
  Progress: 1700/50097 relations classified...
  Progress: 1800/50097 relations classified...
  Progress: 1900/50097 relations classified...
  Progress: 2000/50097 relations classified...
  Progress: 2100/50097 relations classified...
  Progress: 2200/50097 relations classified...
  Progress: 2300/50097 relations classified...
  Progress: 2400/50097 relations classified...
  Progress: 2500/50097 relations classified...
  Progress: 2600/50097 relations classified...
  Progress: 2700/50097 relations classified...
  Progress: 2800/50097 relations classified...
  Progress: 2900/50097 relations classified...
  Progress: 3000/50097 relations classified...
  Progress: 3100/50097 relations classified...
  Progress: 3200/50097 relations classified...
  Progress: 3300/50097 relations classified...
  Progress: 3400/50097 relations classified...
  Progress: 3500/50097 relations classified...
  Progress: 3600/50097 relations classified...
  Progress: 3700/50097 relations classified...
  Progress: 3800/50097 relations classified...
  Progress: 3900/50097 relations classified...
  Progress: 4000/50097 relations classified...
  Progress: 4100/50097 relations classified...
  Progress: 4200/50097 relations classified...
  Progress: 4300/50097 relations classified...
  Progress: 4400/50097 relations classified...
  Progress: 4500/50097 relations classified...
  Progress: 4600/50097 relations classified...
  Progress: 4700/50097 relations classified...
  Progress: 4800/50097 relations classified...
  Progress: 4900/50097 relations classified...
  Progress: 5000/50097 relations classified...
  Progress: 5100/50097 relations classified...
  Progress: 5200/50097 relations classified...
  Progress: 5300/50097 relations classified...
  Progress: 5400/50097 relations classified...
  Progress: 5500/50097 relations classified...
  Progress: 5600/50097 relations classified...
  Progress: 5700/50097 relations classified...
  Progress: 5800/50097 relations classified...
  Progress: 5900/50097 relations classified...
  Progress: 6000/50097 relations classified...
  Progress: 6100/50097 relations classified...
  Progress: 6200/50097 relations classified...
  Progress: 6300/50097 relations classified...
  Progress: 6400/50097 relations classified...
  Progress: 6500/50097 relations classified...
  Progress: 6600/50097 relations classified...
  Progress: 6700/50097 relations classified...
  Progress: 6800/50097 relations classified...
  Progress: 6900/50097 relations classified...
  Progress: 7000/50097 relations classified...
  Progress: 7100/50097 relations classified...
  Progress: 7200/50097 relations classified...
  Progress: 7300/50097 relations classified...
  Progress: 7400/50097 relations classified...
  Progress: 7500/50097 relations classified...
  Progress: 7600/50097 relations classified...
  Progress: 7700/50097 relations classified...
  Progress: 7800/50097 relations classified...
  Progress: 7900/50097 relations classified...
  Progress: 8000/50097 relations classified...
  Progress: 8100/50097 relations classified...
  Progress: 8200/50097 relations classified...
  Progress: 8300/50097 relations classified...
  Progress: 8400/50097 relations classified...
  Progress: 8500/50097 relations classified...
  Progress: 8600/50097 relations classified...
  Progress: 8700/50097 relations classified...
  Progress: 8800/50097 relations classified...
  Progress: 8900/50097 relations classified...
  Progress: 9000/50097 relations classified...
  Progress: 9100/50097 relations classified...
  Progress: 9200/50097 relations classified...
  Progress: 9300/50097 relations classified...
  Progress: 9400/50097 relations classified...
  Progress: 9500/50097 relations classified...
  Progress: 9600/50097 relations classified...
  Progress: 9700/50097 relations classified...
  Progress: 9800/50097 relations classified...
  Progress: 9900/50097 relations classified...
  Progress: 10000/50097 relations classified...
  Progress: 10100/50097 relations classified...
  Progress: 10200/50097 relations classified...
  Progress: 10300/50097 relations classified...
  Progress: 10400/50097 relations classified...
  Progress: 10500/50097 relations classified...
  Progress: 10600/50097 relations classified...
  Progress: 10700/50097 relations classified...
  Progress: 10800/50097 relations classified...
  Progress: 10900/50097 relations classified...
  Progress: 11000/50097 relations classified...
  Progress: 11100/50097 relations classified...
  Progress: 11200/50097 relations classified...
  Progress: 11300/50097 relations classified...
  Progress: 11400/50097 relations classified...
  Progress: 11500/50097 relations classified...
  Progress: 11600/50097 relations classified...
  Progress: 11700/50097 relations classified...
  Progress: 11800/50097 relations classified...
  Progress: 11900/50097 relations classified...
  Progress: 12000/50097 relations classified...
  Progress: 12100/50097 relations classified...
  Progress: 12200/50097 relations classified...
  Progress: 12300/50097 relations classified...
  Progress: 12400/50097 relations classified...
  Progress: 12500/50097 relations classified...
  Progress: 12600/50097 relations classified...
  Progress: 12700/50097 relations classified...
  Progress: 12800/50097 relations classified...
  Progress: 12900/50097 relations classified...
  Progress: 13000/50097 relations classified...
  Progress: 13100/50097 relations classified...
  Progress: 13200/50097 relations classified...
  Progress: 13300/50097 relations classified...
  Progress: 13400/50097 relations classified...
  Progress: 13500/50097 relations classified...
  Progress: 13600/50097 relations classified...
  Progress: 13700/50097 relations classified...
  Progress: 13800/50097 relations classified...
  Progress: 13900/50097 relations classified...
  Progress: 14000/50097 relations classified...
  Progress: 14100/50097 relations classified...
  Progress: 14200/50097 relations classified...
  Progress: 14300/50097 relations classified...
  Progress: 14400/50097 relations classified...
  Progress: 14500/50097 relations classified...
  Progress: 14600/50097 relations classified...
  Progress: 14700/50097 relations classified...
  Progress: 14800/50097 relations classified...
  Progress: 14900/50097 relations classified...
  Progress: 15000/50097 relations classified...
  Progress: 15100/50097 relations classified...
  Progress: 15200/50097 relations classified...
  Progress: 15300/50097 relations classified...
  Progress: 15400/50097 relations classified...
  Progress: 15500/50097 relations classified...
  Progress: 15600/50097 relations classified...
  Progress: 15700/50097 relations classified...
  Progress: 15800/50097 relations classified...
  Progress: 15900/50097 relations classified...
  Progress: 16000/50097 relations classified...
  Progress: 16100/50097 relations classified...
  Progress: 16200/50097 relations classified...
  Progress: 16300/50097 relations classified...
  Progress: 16400/50097 relations classified...
  Progress: 16500/50097 relations classified...
  Progress: 16600/50097 relations classified...
  Progress: 16700/50097 relations classified...
  Progress: 16800/50097 relations classified...
  Progress: 16900/50097 relations classified...
  Progress: 17000/50097 relations classified...
  Progress: 17100/50097 relations classified...
  Progress: 17200/50097 relations classified...
  Progress: 17300/50097 relations classified...
  Progress: 17400/50097 relations classified...
  Progress: 17500/50097 relations classified...
  Progress: 17600/50097 relations classified...
  Progress: 17700/50097 relations classified...
  Progress: 17800/50097 relations classified...
  Progress: 17900/50097 relations classified...
  Progress: 18000/50097 relations classified...
  Progress: 18100/50097 relations classified...
  Progress: 18200/50097 relations classified...
  Progress: 18300/50097 relations classified...
  Progress: 18400/50097 relations classified...
  Progress: 18500/50097 relations classified...
  Progress: 18600/50097 relations classified...
  Progress: 18700/50097 relations classified...
  Progress: 18800/50097 relations classified...
  Progress: 18900/50097 relations classified...
  Progress: 19000/50097 relations classified...
  Progress: 19100/50097 relations classified...
  Progress: 19200/50097 relations classified...
  Progress: 19300/50097 relations classified...
  Progress: 19400/50097 relations classified...
  Progress: 19500/50097 relations classified...
  Progress: 19600/50097 relations classified...
  Progress: 19700/50097 relations classified...
  Progress: 19800/50097 relations classified...
  Progress: 19900/50097 relations classified...
  Progress: 20000/50097 relations classified...
  Progress: 20100/50097 relations classified...
  Progress: 20200/50097 relations classified...
  Progress: 20300/50097 relations classified...
  Progress: 20400/50097 relations classified...
  Progress: 20500/50097 relations classified...
  Progress: 20600/50097 relations classified...
  Progress: 20700/50097 relations classified...
  Progress: 20800/50097 relations classified...
  Progress: 20900/50097 relations classified...
  Progress: 21000/50097 relations classified...
  Progress: 21100/50097 relations classified...
  Progress: 21200/50097 relations classified...
  Progress: 21300/50097 relations classified...
  Progress: 21400/50097 relations classified...
  Progress: 21500/50097 relations classified...
  Progress: 21600/50097 relations classified...
  Progress: 21700/50097 relations classified...
  Progress: 21800/50097 relations classified...
  Progress: 21900/50097 relations classified...
  Progress: 22000/50097 relations classified...
  Progress: 22100/50097 relations classified...
  Progress: 22200/50097 relations classified...
  Progress: 22300/50097 relations classified...
  Progress: 22400/50097 relations classified...
  Progress: 22500/50097 relations classified...
  Progress: 22600/50097 relations classified...
  Progress: 22700/50097 relations classified...
  Progress: 22800/50097 relations classified...
  Progress: 22900/50097 relations classified...
  Progress: 23000/50097 relations classified...
  Progress: 23100/50097 relations classified...
  Progress: 23200/50097 relations classified...
  Progress: 23300/50097 relations classified...
  Progress: 23400/50097 relations classified...
  Progress: 23500/50097 relations classified...
  Progress: 23600/50097 relations classified...
  Progress: 23700/50097 relations classified...
  Progress: 23800/50097 relations classified...
  Progress: 23900/50097 relations classified...
  Progress: 24000/50097 relations classified...
  Progress: 24100/50097 relations classified...
  Progress: 24200/50097 relations classified...
  Progress: 24300/50097 relations classified...
  Progress: 24400/50097 relations classified...
  Progress: 24500/50097 relations classified...
  Progress: 24600/50097 relations classified...
  Progress: 24700/50097 relations classified...
  Progress: 24800/50097 relations classified...
  Progress: 24900/50097 relations classified...
  Progress: 25000/50097 relations classified...
  Progress: 25100/50097 relations classified...
  Progress: 25200/50097 relations classified...
  Progress: 25300/50097 relations classified...
  Progress: 25400/50097 relations classified...
  Progress: 25500/50097 relations classified...
  Progress: 25600/50097 relations classified...
  Progress: 25700/50097 relations classified...
  Progress: 25800/50097 relations classified...
  Progress: 25900/50097 relations classified...
  Progress: 26000/50097 relations classified...
  Progress: 26100/50097 relations classified...
  Progress: 26200/50097 relations classified...
  Progress: 26300/50097 relations classified...
  Progress: 26400/50097 relations classified...
  Progress: 26500/50097 relations classified...
  Progress: 26600/50097 relations classified...
  Progress: 26700/50097 relations classified...
  Progress: 26800/50097 relations classified...
  Progress: 26900/50097 relations classified...
  Progress: 27000/50097 relations classified...
  Progress: 27100/50097 relations classified...
  Progress: 27200/50097 relations classified...
  Progress: 27300/50097 relations classified...
  Progress: 27400/50097 relations classified...
  Progress: 27500/50097 relations classified...
  Progress: 27600/50097 relations classified...
  Progress: 27700/50097 relations classified...
  Progress: 27800/50097 relations classified...
  Progress: 27900/50097 relations classified...
  Progress: 28000/50097 relations classified...
  Progress: 28100/50097 relations classified...
  Progress: 28200/50097 relations classified...
  Progress: 28300/50097 relations classified...
  Progress: 28400/50097 relations classified...
  Progress: 28500/50097 relations classified...
  Progress: 28600/50097 relations classified...
  Progress: 28700/50097 relations classified...
  Progress: 28800/50097 relations classified...
  Progress: 28900/50097 relations classified...
  Progress: 29000/50097 relations classified...
  Progress: 29100/50097 relations classified...
  Progress: 29200/50097 relations classified...
  Progress: 29300/50097 relations classified...
  Progress: 29400/50097 relations classified...
  Progress: 29500/50097 relations classified...
  Progress: 29600/50097 relations classified...
  Progress: 29700/50097 relations classified...
  Progress: 29800/50097 relations classified...
  Progress: 29900/50097 relations classified...
  Progress: 30000/50097 relations classified...
  Progress: 30100/50097 relations classified...
  Progress: 30200/50097 relations classified...
  Progress: 30300/50097 relations classified...
  Progress: 30400/50097 relations classified...
  Progress: 30500/50097 relations classified...
  Progress: 30600/50097 relations classified...
  Progress: 30700/50097 relations classified...
  Progress: 30800/50097 relations classified...
  Progress: 30900/50097 relations classified...
  Progress: 31000/50097 relations classified...
  Progress: 31100/50097 relations classified...
  Progress: 31200/50097 relations classified...
  Progress: 31300/50097 relations classified...
  Progress: 31400/50097 relations classified...
  Progress: 31500/50097 relations classified...
  Progress: 31600/50097 relations classified...
  Progress: 31700/50097 relations classified...
  Progress: 31800/50097 relations classified...
  Progress: 31900/50097 relations classified...
  Progress: 32000/50097 relations classified...
  Progress: 32100/50097 relations classified...
  Progress: 32200/50097 relations classified...
  Progress: 32300/50097 relations classified...
  Progress: 32400/50097 relations classified...
  Progress: 32500/50097 relations classified...
  Progress: 32600/50097 relations classified...
  Progress: 32700/50097 relations classified...
  Progress: 32800/50097 relations classified...
  Progress: 32900/50097 relations classified...
  Progress: 33000/50097 relations classified...
  Progress: 33100/50097 relations classified...
  Progress: 33200/50097 relations classified...
  Progress: 33300/50097 relations classified...
  Progress: 33400/50097 relations classified...
  Progress: 33500/50097 relations classified...
  Progress: 33600/50097 relations classified...
  Progress: 33700/50097 relations classified...
  Progress: 33800/50097 relations classified...
  Progress: 33900/50097 relations classified...
  Progress: 34000/50097 relations classified...
  Progress: 34100/50097 relations classified...
  Progress: 34200/50097 relations classified...
  Progress: 34300/50097 relations classified...
  Progress: 34400/50097 relations classified...
  Progress: 34500/50097 relations classified...
  Progress: 34600/50097 relations classified...
  Progress: 34700/50097 relations classified...
  Progress: 34800/50097 relations classified...
  Progress: 34900/50097 relations classified...
  Progress: 35000/50097 relations classified...
  Progress: 35100/50097 relations classified...
  Progress: 35200/50097 relations classified...
  Progress: 35300/50097 relations classified...
  Progress: 35400/50097 relations classified...
  Progress: 35500/50097 relations classified...
  Progress: 35600/50097 relations classified...
  Progress: 35700/50097 relations classified...
  Progress: 35800/50097 relations classified...
  Progress: 35900/50097 relations classified...
  Progress: 36000/50097 relations classified...
  Progress: 36100/50097 relations classified...
  Progress: 36200/50097 relations classified...
  Progress: 36300/50097 relations classified...
  Progress: 36400/50097 relations classified...
  Progress: 36500/50097 relations classified...
  Progress: 36600/50097 relations classified...
  Progress: 36700/50097 relations classified...
  Progress: 36800/50097 relations classified...
  Progress: 36900/50097 relations classified...
  Progress: 37000/50097 relations classified...
  Progress: 37100/50097 relations classified...
  Progress: 37200/50097 relations classified...
  Progress: 37300/50097 relations classified...
  Progress: 37400/50097 relations classified...
  Progress: 37500/50097 relations classified...
  Progress: 37600/50097 relations classified...
  Progress: 37700/50097 relations classified...
  Progress: 37800/50097 relations classified...
  Progress: 37900/50097 relations classified...
  Progress: 38000/50097 relations classified...
  Progress: 38100/50097 relations classified...
  Progress: 38200/50097 relations classified...
  Progress: 38300/50097 relations classified...
  Progress: 38400/50097 relations classified...
  Progress: 38500/50097 relations classified...
  Progress: 38600/50097 relations classified...

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_llama,rel_deberta
47795,UN Member States should commit to accelerating...,Countries promote global cooperation for susta...,15_1,16_24,NaN,Support,No Relationship
49985,Countries promote global cooperation for susta...,All UN Member States and UN agencies can count...,16_24,17_8,NaN,Support,No Relationship
13112,The SDGs are facing strong headwinds.,Achieving the SDGs requires global cooperation...,0_13,17_31,NaN,Support,No Relationship
8291,Achieving the SDGs requires global cooperation...,The adoption of the SDGs and the Paris Climate...,0_5,13_27,NaN,Support,No Relationship
40963,Meeting the SDGs and the Paris Agreement goals...,There continues to be a major discrepancy betw...,11_9,13_21,NaN,Attack,No Relationship

rel_deberta
No Relationship    49345
Attack               643
Rephrase              92
Support               17
Name: count, dtype: int64

#### Gemma3 4B extraction

In [8]:
prefix = "intra_goalGLOBAL_SGD2023_gemma3-4b"   

args_classified = classify_relationships_deberta(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_deberta"].value_counts()

Using MAX_LENGTH = 268

Processing: /kaggle/working/TFM/Data/Relationships No Keywords/intra_goalGLOBAL_SGD2023_gemma3-4b.csv
Sample predictions (first 5):

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: None of their objectives are beyond our reach.
  Label: Attack

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: The SDGs are still achievable.
  Label: Attack

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: It is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Greatly increase funding to national and subnational governments and private businesses, especially in LICs and LMICs, to carry out needed SDG investments.
  Label: No Relationship

  Progress: 100/22914 relations classified...
  Progress: 200/22914 relations classified...
  Progress: 300/22914 relations classified...
  Progress: 400/22914 relations classified...
  Progress: 500/22914 relations classified...
  Progress: 600/22914 relations classified...
  Progress: 700/22914 relations classified...
  Progress: 800/22914 relations classified...
  Progress: 900/22914 relations classified...
  Progress: 1000/22914 relations classified...
  Progress: 1100/22914 relations classified...
  Progress: 1200/22914 relations classified...
  Progress: 1300/22914 relations classified...
  Progress: 1400/22914 relations classified...
  Progress: 1500/22914 relations classified...
  Progress: 1600/22914 relations classified...
  Progress: 1700/22914 relations classified...
  Progress: 1800/22914 relations classified...
  Progress: 1900/22914 relations classified...
  Progress: 2000/22914 relations classified...
  Progress: 2100/22914 relations classified...
  Progress: 2200/22914 relations classified...
  Progress: 2300/22914 relations classified...
  Progress: 2400/22914 relations classified...
  Progress: 2500/22914 relations classified...
  Progress: 2600/22914 relations classified...
  Progress: 2700/22914 relations classified...
  Progress: 2800/22914 relations classified...
  Progress: 2900/22914 relations classified...
  Progress: 3000/22914 relations classified...
  Progress: 3100/22914 relations classified...
  Progress: 3200/22914 relations classified...
  Progress: 3300/22914 relations classified...
  Progress: 3400/22914 relations classified...
  Progress: 3500/22914 relations classified...
  Progress: 3600/22914 relations classified...
  Progress: 3700/22914 relations classified...
  Progress: 3800/22914 relations classified...
  Progress: 3900/22914 relations classified...
  Progress: 4000/22914 relations classified...
  Progress: 4100/22914 relations classified...
  Progress: 4200/22914 relations classified...
  Progress: 4300/22914 relations classified...
  Progress: 4400/22914 relations classified...
  Progress: 4500/22914 relations classified...
  Progress: 4600/22914 relations classified...
  Progress: 4700/22914 relations classified...
  Progress: 4800/22914 relations classified...
  Progress: 4900/22914 relations classified...
  Progress: 5000/22914 relations classified...
  Progress: 5100/22914 relations classified...
  Progress: 5200/22914 relations classified...
  Progress: 5300/22914 relations classified...
  Progress: 5400/22914 relations classified...
  Progress: 5500/22914 relations classified...
  Progress: 5600/22914 relations classified...
  Progress: 5700/22914 relations classified...
  Progress: 5800/22914 relations classified...
  Progress: 5900/22914 relations classified...
  Progress: 6000/22914 relations classified...
  Progress: 6100/22914 relations classified...
  Progress: 6200/22914 relations classified...
  Progress: 6300/22914 relations classified...
  Progress: 6400/22914 relations classified...
  Progress: 6500/22914 relations classified...
  Progress: 6600/22914 relations classified...
  Progress: 6700/22914 relations classified...
  Progress: 6800/22914 relations classified...
  Progress: 6900/22914 relations classified...
  Progress: 7000/22914 relations classified...
  Progress: 7100/22914 relations classified...
  Progress: 7200/22914 relations classified...
  Progress: 7300/22914 relations classified...
  Progress: 7400/22914 relations classified...
  Progress: 7500/22914 relations classified...
  Progress: 7600/22914 relations classified...
  Progress: 7700/22914 relations classified...
  Progress: 7800/22914 relations classified...
  Progress: 7900/22914 relations classified...
  Progress: 8000/22914 relations classified...
  Progress: 8100/22914 relations classified...
  Progress: 8200/22914 relations classified...
  Progress: 8300/22914 relations classified...
  Progress: 8400/22914 relations classified...
  Progress: 8500/22914 relations classified...
  Progress: 8600/22914 relations classified...
  Progress: 8700/22914 relations classified...
  Progress: 8800/22914 relations classified...
  Progress: 8900/22914 relations classified...
  Progress: 9000/22914 relations classified...
  Progress: 9100/22914 relations classified...
  Progress: 9200/22914 relations classified...
  Progress: 9300/22914 relations classified...
  Progress: 9400/22914 relations classified...
  Progress: 9500/22914 relations classified...
  Progress: 9600/22914 relations classified...
  Progress: 9700/22914 relations classified...
  Progress: 9800/22914 relations classified...
  Progress: 9900/22914 relations classified...
  Progress: 10000/22914 relations classified...
  Progress: 10100/22914 relations classified...
  Progress: 10200/22914 relations classified...
  Progress: 10300/22914 relations classified...
  Progress: 10400/22914 relations classified...
  Progress: 10500/22914 relations classified...
  Progress: 10600/22914 relations classified...
  Progress: 10700/22914 relations classified...
  Progress: 10800/22914 relations classified...
  Progress: 10900/22914 relations classified...
  Progress: 11000/22914 relations classified...
  Progress: 11100/22914 relations classified...
  Progress: 11200/22914 relations classified...
  Progress: 11300/22914 relations classified...
  Progress: 11400/22914 relations classified...
  Progress: 11500/22914 relations classified...
  Progress: 11600/22914 relations classified...
  Progress: 11700/22914 relations classified...
  Progress: 11800/22914 relations classified...
  Progress: 11900/22914 relations classified...
  Progress: 12000/22914 relations classified...
  Progress: 12100/22914 relations classified...
  Progress: 12200/22914 relations classified...
  Progress: 12300/22914 relations classified...
  Progress: 12400/22914 relations classified...
  Progress: 12500/22914 relations classified...
  Progress: 12600/22914 relations classified...
  Progress: 12700/22914 relations classified...
  Progress: 12800/22914 relations classified...
  Progress: 12900/22914 relations classified...
  Progress: 13000/22914 relations classified...
  Progress: 13100/22914 relations classified...
  Progress: 13200/22914 relations classified...
  Progress: 13300/22914 relations classified...
  Progress: 13400/22914 relations classified...
  Progress: 13500/22914 relations classified...
  Progress: 13600/22914 relations classified...
  Progress: 13700/22914 relations classified...
  Progress: 13800/22914 relations classified...
  Progress: 13900/22914 relations classified...
  Progress: 14000/22914 relations classified...
  Progress: 14100/22914 relations classified...
  Progress: 14200/22914 relations classified...
  Progress: 14300/22914 relations classified...
  Progress: 14400/22914 relations classified...
  Progress: 14500/22914 relations classified...
  Progress: 14600/22914 relations classified...
  Progress: 14700/22914 relations classified...
  Progress: 14800/22914 relations classified...
  Progress: 14900/22914 relations classified...
  Progress: 15000/22914 relations classified...
  Progress: 15100/22914 relations classified...
  Progress: 15200/22914 relations classified...
  Progress: 15300/22914 relations classified...
  Progress: 15400/22914 relations classified...
  Progress: 15500/22914 relations classified...
  Progress: 15600/22914 relations classified...
  Progress: 15700/22914 relations classified...
  Progress: 15800/22914 relations classified...
  Progress: 15900/22914 relations classified...
  Progress: 16000/22914 relations classified...
  Progress: 16100/22914 relations classified...
  Progress: 16200/22914 relations classified...
  Progress: 16300/22914 relations classified...
  Progress: 16400/22914 relations classified...
  Progress: 16500/22914 relations classified...
  Progress: 16600/22914 relations classified...
  Progress: 16700/22914 relations classified...
  Progress: 16800/22914 relations classified...
  Progress: 16900/22914 relations classified...
  Progress: 17000/22914 relations classified...
  Progress: 17100/22914 relations classified...
  Progress: 17200/22914 relations classified...
  Progress: 17300/22914 relations classified...
  Progress: 17400/22914 relations classified...
  Progress: 17500/22914 relations classified...
  Progress: 17600/22914 relations classified...
  Progress: 17700/22914 relations classified...
  Progress: 17800/22914 relations classified...
  Progress: 17900/22914 relations classified...
  Progress: 18000/22914 relations classified...
  Progress: 18100/22914 relations classified...
  Progress: 18200/22914 relations classified...
  Progress: 18300/22914 relations classified...
  Progress: 18400/22914 relations classified...
  Progress: 18500/22914 relations classified...
  Progress: 18600/22914 relations classified...
  Progress: 18700/22914 relations classified...
  Progress: 18800/22914 relations classified...
  Progress: 18900/22914 relations classified...
  Progress: 19000/22914 relations classified...
  Progress: 19100/22914 relations classified...
  Progress: 19200/22914 relations classified...
  Progress: 19300/22914 relations classified...
  Progress: 19400/22914 relations classified...
  Progress: 19500/22914 relations classified...
  Progress: 19600/22914 relations classified...
  Progress: 19700/22914 relations classified...
  Progress: 19800/22914 relations classified...
  Progress: 19900/22914 relations classified...
  Progress: 20000/22914 relations classified...
  Progress: 20100/22914 relations classified...
  Progress: 20200/22914 relations classified...
  Progress: 20300/22914 relations classified...
  Progress: 20400/22914 relations classified...
  Progress: 20500/22914 relations classified...
  Progress: 20600/22914 relations classified...
  Progress: 20700/22914 relations classified...
  Progress: 20800/22914 relations classified...
  Progress: 20900/22914 relations classified...
  Progress: 21000/22914 relations classified...
  Progress: 21100/22914 relations classified...
  Progress: 21200/22914 relations classified...
  Progress: 21300/22914 relations classified...
  Progress: 21400/22914 relations classified...
  Progress: 21500/22914 relations classified...
  Progress: 21600/22914 relations classified...
  Progress: 21700/22914 relations classified...
  Progress: 21800/22914 relations classified...
  Progress: 21900/22914 relations classified...
  Progress: 22000/22914 relations classified...
  Progress: 22100/22914 relations classified...
  Progress: 22200/22914 relations classified...
  Progress: 22300/22914 relations classified...
  Progress: 22400/22914 relations classified...
  Progress: 22500/22914 relations classified...
  Progress: 22600/22914 relations classified...
  Progress: 22700/22914 relations classified...
  Progress: 22800/22914 relations classified...
  Progress: 22900/22914 relations classified...
  Progress: 22914/22914 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships No Keywords/intra_goalGLOBAL_SGD2023_gemma3-4b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_deberta
19582,The SDGs are seriously off track (Figure 1.1)....,SDSN recognizes this gap in the practical mean...,11_1,11_11,NaN,No Relationship
2621,"UN Member States should adopt an SDG Stimulus,...",Extreme poverty rates in LICs remain above pre...,0_16,0_102,NaN,No Relationship
15840,HICs are able to mobilize vast financial resou...,"The goals related to hunger, sustainable diets...",3_19,3_26,NaN,No Relationship
3518,"Creation of ambitious, internationally-agreed ...",Governments must take the lead in all six area...,0_22,0_120,NaN,No Relationship
4416,they are grounded in the Universal Declaration...,"Unless the SDGs are actively pursued, geophysi...",0_29,0_38,NaN,No Relationship

rel_deberta
No Relationship    22638
Attack               262
Rephrase               9
Support                5
Name: count, dtype: int64

In [9]:
prefix = "cross_goalGLOBAL_SGD2023_gemma3-4b"   

args_classified = classify_relationships_deberta(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_deberta"].value_counts()

Using MAX_LENGTH = 268

Processing: /kaggle/working/TFM/Data/Relationships No Keywords/cross_goalGLOBAL_SGD2023_gemma3-4b.csv
Sample predictions (first 5):

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: The world is off track, but that is all the more reason to double down on the SDGs.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: It is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Revise liquidity structures for LICs and LMICs, especially regarding sovereign debts, to forestall self-fulfilling banking and balance-of-payments crises.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Create ambitious, internationally-agreed upon criteria for sustainable finance that are mandatory for all public financial institutions.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Align private business investment flows with the SDGs, through improved national planning, regulation, reporting, and oversight.
  Label: Attack

  Progress: 100/225951 relations classified...
  Progress: 200/225951 relations classified...
  Progress: 300/225951 relations classified...
  Progress: 400/225951 relations classified...
  Progress: 500/225951 relations classified...
  Progress: 600/225951 relations classified...
  Progress: 700/225951 relations classified...
  Progress: 800/225951 relations classified...
  Progress: 900/225951 relations classified...
  Progress: 1000/225951 relations classified...
  Progress: 1100/225951 relations classified...
  Progress: 1200/225951 relations classified...
  Progress: 1300/225951 relations classified...
  Progress: 1400/225951 relations classified...
  Progress: 1500/225951 relations classified...
  Progress: 1600/225951 relations classified...
  Progress: 1700/225951 relations classified...
  Progress: 1800/225951 relations classified...
  Progress: 1900/225951 relations classified...
  Progress: 2000/225951 relations classified...
  Progress: 2100/225951 relations classified...
  Progress: 2200/225951 relations classified...
  Progress: 2300/225951 relations classified...
  Progress: 2400/225951 relations classified...
  Progress: 2500/225951 relations classified...
  Progress: 2600/225951 relations classified...
  Progress: 2700/225951 relations classified...
  Progress: 2800/225951 relations classified...
  Progress: 2900/225951 relations classified...
  Progress: 3000/225951 relations classified...
  Progress: 3100/225951 relations classified...
  Progress: 3200/225951 relations classified...
  Progress: 3300/225951 relations classified...
  Progress: 3400/225951 relations classified...
  Progress: 3500/225951 relations classified...
  Progress: 3600/225951 relations classified...
  Progress: 3700/225951 relations classified...
  Progress: 3800/225951 relations classified...
  Progress: 3900/225951 relations classified...
  Progress: 4000/225951 relations classified...
  Progress: 4100/225951 relations classified...
  Progress: 4200/225951 relations classified...
  Progress: 4300/225951 relations classified...
  Progress: 4400/225951 relations classified...
  Progress: 4500/225951 relations classified...
  Progress: 4600/225951 relations classified...
  Progress: 4700/225951 relations classified...
  Progress: 4800/225951 relations classified...
  Progress: 4900/225951 relations classified...
  Progress: 5000/225951 relations classified...
  Progress: 5100/225951 relations classified...
  Progress: 5200/225951 relations classified...
  Progress: 5300/225951 relations classified...
  Progress: 5400/225951 relations classified...
  Progress: 5500/225951 relations classified...
  Progress: 5600/225951 relations classified...
  Progress: 5700/225951 relations classified...
  Progress: 5800/225951 relations classified...
  Progress: 5900/225951 relations classified...
  Progress: 6000/225951 relations classified...
  Progress: 6100/225951 relations classified...
  Progress: 6200/225951 relations classified...
  Progress: 6300/225951 relations classified...
  Progress: 6400/225951 relations classified...
  Progress: 6500/225951 relations classified...
  Progress: 6600/225951 relations classified...
  Progress: 6700/225951 relations classified...
  Progress: 6800/225951 relations classified...
  Progress: 6900/225951 relations classified...
  Progress: 7000/225951 relations classified...
  Progress: 7100/225951 relations classified...
  Progress: 7200/225951 relations classified...
  Progress: 7300/225951 relations classified...
  Progress: 7400/225951 relations classified...
  Progress: 7500/225951 relations classified...
  Progress: 7600/225951 relations classified...
  Progress: 7700/225951 relations classified...
  Progress: 7800/225951 relations classified...
  Progress: 7900/225951 relations classified...
  Progress: 8000/225951 relations classified...
  Progress: 8100/225951 relations classified...
  Progress: 8200/225951 relations classified...
  Progress: 8300/225951 relations classified...
  Progress: 8400/225951 relations classified...
  Progress: 8500/225951 relations classified...
  Progress: 8600/225951 relations classified...
  Progress: 8700/225951 relations classified...
  Progress: 8800/225951 relations classified...
  Progress: 8900/225951 relations classified...
  Progress: 9000/225951 relations classified...
  Progress: 9100/225951 relations classified...
  Progress: 9200/225951 relations classified...
  Progress: 9300/225951 relations classified...
  Progress: 9400/225951 relations classified...
  Progress: 9500/225951 relations classified...
  Progress: 9600/225951 relations classified...
  Progress: 9700/225951 relations classified...
  Progress: 9800/225951 relations classified...
  Progress: 9900/225951 relations classified...
  Progress: 10000/225951 relations classified...
  Progress: 10100/225951 relations classified...
  Progress: 10200/225951 relations classified...
  Progress: 10300/225951 relations classified...
  Progress: 10400/225951 relations classified...
  Progress: 10500/225951 relations classified...
  Progress: 10600/225951 relations classified...
  Progress: 10700/225951 relations classified...
  Progress: 10800/225951 relations classified...
  Progress: 10900/225951 relations classified...
  Progress: 11000/225951 relations classified...
  Progress: 11100/225951 relations classified...
  Progress: 11200/225951 relations classified...
  Progress: 11300/225951 relations classified...
  Progress: 11400/225951 relations classified...
  Progress: 11500/225951 relations classified...
  Progress: 11600/225951 relations classified...
  Progress: 11700/225951 relations classified...
  Progress: 11800/225951 relations classified...
  Progress: 11900/225951 relations classified...
  Progress: 12000/225951 relations classified...
  Progress: 12100/225951 relations classified...
  Progress: 12200/225951 relations classified...
  Progress: 12300/225951 relations classified...
  Progress: 12400/225951 relations classified...
  Progress: 12500/225951 relations classified...
  Progress: 12600/225951 relations classified...
  Progress: 12700/225951 relations classified...
  Progress: 12800/225951 relations classified...
  Progress: 12900/225951 relations classified...
  Progress: 13000/225951 relations classified...
  Progress: 13100/225951 relations classified...
  Progress: 13200/225951 relations classified...
  Progress: 13300/225951 relations classified...
  Progress: 13400/225951 relations classified...
  Progress: 13500/225951 relations classified...
  Progress: 13600/225951 relations classified...
  Progress: 13700/225951 relations classified...
  Progress: 13800/225951 relations classified...
  Progress: 13900/225951 relations classified...
  Progress: 14000/225951 relations classified...
  Progress: 14100/225951 relations classified...
  Progress: 14200/225951 relations classified...
  Progress: 14300/225951 relations classified...
  Progress: 14400/225951 relations classified...
  Progress: 14500/225951 relations classified...
  Progress: 14600/225951 relations classified...
  Progress: 14700/225951 relations classified...
  Progress: 14800/225951 relations classified...
  Progress: 14900/225951 relations classified...
  Progress: 15000/225951 relations classified...
  Progress: 15100/225951 relations classified...
  Progress: 15200/225951 relations classified...
  Progress: 15300/225951 relations classified...
  Progress: 15400/225951 relations classified...
  Progress: 15500/225951 relations classified...
  Progress: 15600/225951 relations classified...
  Progress: 15700/225951 relations classified...
  Progress: 15800/225951 relations classified...
  Progress: 15900/225951 relations classified...
  Progress: 16000/225951 relations classified...
  Progress: 16100/225951 relations classified...
  Progress: 16200/225951 relations classified...
  Progress: 16300/225951 relations classified...
  Progress: 16400/225951 relations classified...
  Progress: 16500/225951 relations classified...
  Progress: 16600/225951 relations classified...
  Progress: 16700/225951 relations classified...
  Progress: 16800/225951 relations classified...
  Progress: 16900/225951 relations classified...
  Progress: 17000/225951 relations classified...
  Progress: 17100/225951 relations classified...
  Progress: 17200/225951 relations classified...
  Progress: 17300/225951 relations classified...
  Progress: 17400/225951 relations classified...
  Progress: 17500/225951 relations classified...
  Progress: 17600/225951 relations classified...
  Progress: 17700/225951 relations classified...
  Progress: 17800/225951 relations classified...
  Progress: 17900/225951 relations classified...
  Progress: 18000/225951 relations classified...
  Progress: 18100/225951 relations classified...
  Progress: 18200/225951 relations classified...
  Progress: 18300/225951 relations classified...
  Progress: 18400/225951 relations classified...
  Progress: 18500/225951 relations classified...
  Progress: 18600/225951 relations classified...
  Progress: 18700/225951 relations classified...
  Progress: 18800/225951 relations classified...
  Progress: 18900/225951 relations classified...
  Progress: 19000/225951 relations classified...
  Progress: 19100/225951 relations classified...
  Progress: 19200/225951 relations classified...
  Progress: 19300/225951 relations classified...
  Progress: 19400/225951 relations classified...
  Progress: 19500/225951 relations classified...
  Progress: 19600/225951 relations classified...
  Progress: 19700/225951 relations classified...
  Progress: 19800/225951 relations classified...
  Progress: 19900/225951 relations classified...
  Progress: 20000/225951 relations classified...
  Progress: 20100/225951 relations classified...
  Progress: 20200/225951 relations classified...
  Progress: 20300/225951 relations classified...
  Progress: 20400/225951 relations classified...
  Progress: 20500/225951 relations classified...
  Progress: 20600/225951 relations classified...
  Progress: 20700/225951 relations classified...
  Progress: 20800/225951 relations classified...
  Progress: 20900/225951 relations classified...
  Progress: 21000/225951 relations classified...
  Progress: 21100/225951 relations classified...
  Progress: 21200/225951 relations classified...
  Progress: 21300/225951 relations classified...
  Progress: 21400/225951 relations classified...
  Progress: 21500/225951 relations classified...
  Progress: 21600/225951 relations classified...
  Progress: 21700/225951 relations classified...
  Progress: 21800/225951 relations classified...
  Progress: 21900/225951 relations classified...
  Progress: 22000/225951 relations classified...
  Progress: 22100/225951 relations classified...
  Progress: 22200/225951 relations classified...
  Progress: 22300/225951 relations classified...
  Progress: 22400/225951 relations classified...
  Progress: 22500/225951 relations classified...
  Progress: 22600/225951 relations classified...
  Progress: 22700/225951 relations classified...
  Progress: 22800/225951 relations classified...
  Progress: 22900/225951 relations classified...
  Progress: 23000/225951 relations classified...
  Progress: 23100/225951 relations classified...
  Progress: 23200/225951 relations classified...
  Progress: 23300/225951 relations classified...
  Progress: 23400/225951 relations classified...
  Progress: 23500/225951 relations classified...
  Progress: 23600/225951 relations classified...
  Progress: 23700/225951 relations classified...
  Progress: 23800/225951 relations classified...
  Progress: 23900/225951 relations classified...
  Progress: 24000/225951 relations classified...
  Progress: 24100/225951 relations classified...
  Progress: 24200/225951 relations classified...
  Progress: 24300/225951 relations classified...
  Progress: 24400/225951 relations classified...
  Progress: 24500/225951 relations classified...
  Progress: 24600/225951 relations classified...
  Progress: 24700/225951 relations classified...
  Progress: 24800/225951 relations classified...
  Progress: 24900/225951 relations classified...
  Progress: 25000/225951 relations classified...
  Progress: 25100/225951 relations classified...
  Progress: 25200/225951 relations classified...
  Progress: 25300/225951 relations classified...
  Progress: 25400/225951 relations classified...
  Progress: 25500/225951 relations classified...
  Progress: 25600/225951 relations classified...
  Progress: 25700/225951 relations classified...
  Progress: 25800/225951 relations classified...
  Progress: 25900/225951 relations classified...
  Progress: 26000/225951 relations classified...
  Progress: 26100/225951 relations classified...
  Progress: 26200/225951 relations classified...
  Progress: 26300/225951 relations classified...
  Progress: 26400/225951 relations classified...
  Progress: 26500/225951 relations classified...
  Progress: 26600/225951 relations classified...
  Progress: 26700/225951 relations classified...
  Progress: 26800/225951 relations classified...
  Progress: 26900/225951 relations classified...
  Progress: 27000/225951 relations classified...
  Progress: 27100/225951 relations classified...
  Progress: 27200/225951 relations classified...
  Progress: 27300/225951 relations classified...
  Progress: 27400/225951 relations classified...
  Progress: 27500/225951 relations classified...
  Progress: 27600/225951 relations classified...
  Progress: 27700/225951 relations classified...
  Progress: 27800/225951 relations classified...
  Progress: 27900/225951 relations classified...
  Progress: 28000/225951 relations classified...
  Progress: 28100/225951 relations classified...
  Progress: 28200/225951 relations classified...
  Progress: 28300/225951 relations classified...
  Progress: 28400/225951 relations classified...
  Progress: 28500/225951 relations classified...
  Progress: 28600/225951 relations classified...
  Progress: 28700/225951 relations classified...
  Progress: 28800/225951 relations classified...
  Progress: 28900/225951 relations classified...
  Progress: 29000/225951 relations classified...
  Progress: 29100/225951 relations classified...
  Progress: 29200/225951 relations classified...
  Progress: 29300/225951 relations classified...
  Progress: 29400/225951 relations classified...
  Progress: 29500/225951 relations classified...
  Progress: 29600/225951 relations classified...
  Progress: 29700/225951 relations classified...
  Progress: 29800/225951 relations classified...
  Progress: 29900/225951 relations classified...
  Progress: 30000/225951 relations classified...
  Progress: 30100/225951 relations classified...
  Progress: 30200/225951 relations classified...
  Progress: 30300/225951 relations classified...
  Progress: 30400/225951 relations classified...
  Progress: 30500/225951 relations classified...
  Progress: 30600/225951 relations classified...
  Progress: 30700/225951 relations classified...
  Progress: 30800/225951 relations classified...
  Progress: 30900/225951 relations classified...
  Progress: 31000/225951 relations classified...
  Progress: 31100/225951 relations classified...
  Progress: 31200/225951 relations classified...
  Progress: 31300/225951 relations classified...
  Progress: 31400/225951 relations classified...
  Progress: 31500/225951 relations classified...
  Progress: 31600/225951 relations classified...
  Progress: 31700/225951 relations classified...
  Progress: 31800/225951 relations classified...
  Progress: 31900/225951 relations classified...
  Progress: 32000/225951 relations classified...
  Progress: 32100/225951 relations classified...
  Progress: 32200/225951 relations classified...
  Progress: 32300/225951 relations classified...
  Progress: 32400/225951 relations classified...
  Progress: 32500/225951 relations classified...
  Progress: 32600/225951 relations classified...
  Progress: 32700/225951 relations classified...
  Progress: 32800/225951 relations classified...
  Progress: 32900/225951 relations classified...
  Progress: 33000/225951 relations classified...
  Progress: 33100/225951 relations classified...
  Progress: 33200/225951 relations classified...
  Progress: 33300/225951 relations classified...
  Progress: 33400/225951 relations classified...
  Progress: 33500/225951 relations classified...
  Progress: 33600/225951 relations classified...
  Progress: 33700/225951 relations classified...
  Progress: 33800/225951 relations classified...
  Progress: 33900/225951 relations classified...
  Progress: 34000/225951 relations classified...
  Progress: 34100/225951 relations classified...
  Progress: 34200/225951 relations classified...
  Progress: 34300/225951 relations classified...
  Progress: 34400/225951 relations classified...
  Progress: 34500/225951 relations classified...
  Progress: 34600/225951 relations classified...
  Progress: 34700/225951 relations classified...
  Progress: 34800/225951 relations classified...
  Progress: 34900/225951 relations classified...
  Progress: 35000/225951 relations classified...
  Progress: 35100/225951 relations classified...
  Progress: 35200/225951 relations classified...
  Progress: 35300/225951 relations classified...
  Progress: 35400/225951 relations classified...
  Progress: 35500/225951 relations classified...
  Progress: 35600/225951 relations classified...
  Progress: 35700/225951 relations classified...
  Progress: 35800/225951 relations classified...
  Progress: 35900/225951 relations classified...
  Progress: 36000/225951 relations classified...
  Progress: 36100/225951 relations classified...
  Progress: 36200/225951 relations classified...
  Progress: 36300/225951 relations classified...
  Progress: 36400/225951 relations classified...
  Progress: 36500/225951 relations classified...
  Progress: 36600/225951 relations classified...
  Progress: 36700/225951 relations classified...
  Progress: 36800/225951 relations classified...
  Progress: 36900/225951 relations classified...
  Progress: 37000/225951 relations classified...
  Progress: 37100/225951 relations classified...
  Progress: 37200/225951 relations classified...
  Progress: 37300/225951 relations classified...
  Progress: 37400/225951 relations classified...
  Progress: 37500/225951 relations classified...
  Progress: 37600/225951 relations classified...
  Progress: 37700/225951 relations classified...
  Progress: 37800/225951 relations classified...
  Progress: 37900/225951 relations classified...
  Progress: 38000/225951 relations classified...
  Progress: 38100/225951 relations classified...

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_deberta
171612,globalized trade rules for ‘cleantech’ could a...,Revision of the credit-rating system and debt-...,7_13,9_5,NaN,No Relationship
142406,Governments are only now mapping out pathways ...,The capacity and healthy functioning of ecosys...,4_10,6_8,NaN,No Relationship
173067,They can also improve resource-use efficiencie...,Although all governments are in principle comm...,7_21,10_13,NaN,No Relationship
32609,Many EU member states demonstrate a high or mo...,global achievement of the SDGs rose only sligh...,0_53,7_2,NaN,No Relationship
5860,Each scorecard consists of a collection of hea...,Align private business investment flows with t...,0_122,1_4,NaN,No Relationship

rel_deberta
No Relationship    223413
Attack               1902
Rephrase              586
Support                50
Name: count, dtype: int64

#### Llama3.3 70B extraction

In [10]:
prefix = "intra_goalGLOBAL_SGD2023_llama3.3-70b"   

args_classified = classify_relationships_deberta(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_deberta"].value_counts()

Using MAX_LENGTH = 237

Processing: /kaggle/working/TFM/Data/Relationships No Keywords/intra_goalGLOBAL_SGD2023_llama3.3-70b.csv
Sample predictions (first 5):

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Since the outbreak of the pandemic in 2020 and other simultaneous crises, SDG progress has stalled globally.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: The world is off track, but that is all the more reason to double down on the SDGs.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.
  Label: No Relationship

  Progress: 100/12011 relations classified...
  Progress: 200/12011 relations classified...
  Progress: 300/12011 relations classified...
  Progress: 400/12011 relations classified...
  Progress: 500/12011 relations classified...
  Progress: 600/12011 relations classified...
  Progress: 700/12011 relations classified...
  Progress: 800/12011 relations classified...
  Progress: 900/12011 relations classified...
  Progress: 1000/12011 relations classified...
  Progress: 1100/12011 relations classified...
  Progress: 1200/12011 relations classified...
  Progress: 1300/12011 relations classified...
  Progress: 1400/12011 relations classified...
  Progress: 1500/12011 relations classified...
  Progress: 1600/12011 relations classified...
  Progress: 1700/12011 relations classified...
  Progress: 1800/12011 relations classified...
  Progress: 1900/12011 relations classified...
  Progress: 2000/12011 relations classified...
  Progress: 2100/12011 relations classified...
  Progress: 2200/12011 relations classified...
  Progress: 2300/12011 relations classified...
  Progress: 2400/12011 relations classified...
  Progress: 2500/12011 relations classified...
  Progress: 2600/12011 relations classified...
  Progress: 2700/12011 relations classified...
  Progress: 2800/12011 relations classified...
  Progress: 2900/12011 relations classified...
  Progress: 3000/12011 relations classified...
  Progress: 3100/12011 relations classified...
  Progress: 3200/12011 relations classified...
  Progress: 3300/12011 relations classified...
  Progress: 3400/12011 relations classified...
  Progress: 3500/12011 relations classified...
  Progress: 3600/12011 relations classified...
  Progress: 3700/12011 relations classified...
  Progress: 3800/12011 relations classified...
  Progress: 3900/12011 relations classified...
  Progress: 4000/12011 relations classified...
  Progress: 4100/12011 relations classified...
  Progress: 4200/12011 relations classified...
  Progress: 4300/12011 relations classified...
  Progress: 4400/12011 relations classified...
  Progress: 4500/12011 relations classified...
  Progress: 4600/12011 relations classified...
  Progress: 4700/12011 relations classified...
  Progress: 4800/12011 relations classified...
  Progress: 4900/12011 relations classified...
  Progress: 5000/12011 relations classified...
  Progress: 5100/12011 relations classified...
  Progress: 5200/12011 relations classified...
  Progress: 5300/12011 relations classified...
  Progress: 5400/12011 relations classified...
  Progress: 5500/12011 relations classified...
  Progress: 5600/12011 relations classified...
  Progress: 5700/12011 relations classified...
  Progress: 5800/12011 relations classified...
  Progress: 5900/12011 relations classified...
  Progress: 6000/12011 relations classified...
  Progress: 6100/12011 relations classified...
  Progress: 6200/12011 relations classified...
  Progress: 6300/12011 relations classified...
  Progress: 6400/12011 relations classified...
  Progress: 6500/12011 relations classified...
  Progress: 6600/12011 relations classified...
  Progress: 6700/12011 relations classified...
  Progress: 6800/12011 relations classified...
  Progress: 6900/12011 relations classified...
  Progress: 7000/12011 relations classified...
  Progress: 7100/12011 relations classified...
  Progress: 7200/12011 relations classified...
  Progress: 7300/12011 relations classified...
  Progress: 7400/12011 relations classified...
  Progress: 7500/12011 relations classified...
  Progress: 7600/12011 relations classified...
  Progress: 7700/12011 relations classified...
  Progress: 7800/12011 relations classified...
  Progress: 7900/12011 relations classified...
  Progress: 8000/12011 relations classified...
  Progress: 8100/12011 relations classified...
  Progress: 8200/12011 relations classified...
  Progress: 8300/12011 relations classified...
  Progress: 8400/12011 relations classified...
  Progress: 8500/12011 relations classified...
  Progress: 8600/12011 relations classified...
  Progress: 8700/12011 relations classified...
  Progress: 8800/12011 relations classified...
  Progress: 8900/12011 relations classified...
  Progress: 9000/12011 relations classified...
  Progress: 9100/12011 relations classified...
  Progress: 9200/12011 relations classified...
  Progress: 9300/12011 relations classified...
  Progress: 9400/12011 relations classified...
  Progress: 9500/12011 relations classified...
  Progress: 9600/12011 relations classified...
  Progress: 9700/12011 relations classified...
  Progress: 9800/12011 relations classified...
  Progress: 9900/12011 relations classified...
  Progress: 10000/12011 relations classified...
  Progress: 10100/12011 relations classified...
  Progress: 10200/12011 relations classified...
  Progress: 10300/12011 relations classified...
  Progress: 10400/12011 relations classified...
  Progress: 10500/12011 relations classified...
  Progress: 10600/12011 relations classified...
  Progress: 10700/12011 relations classified...
  Progress: 10800/12011 relations classified...
  Progress: 10900/12011 relations classified...
  Progress: 11000/12011 relations classified...
  Progress: 11100/12011 relations classified...
  Progress: 11200/12011 relations classified...
  Progress: 11300/12011 relations classified...
  Progress: 11400/12011 relations classified...
  Progress: 11500/12011 relations classified...
  Progress: 11600/12011 relations classified...
  Progress: 11700/12011 relations classified...
  Progress: 11800/12011 relations classified...
  Progress: 11900/12011 relations classified...
  Progress: 12000/12011 relations classified...
  Progress: 12011/12011 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships No Keywords/intra_goalGLOBAL_SGD2023_llama3.3-70b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_llama,rel_deberta
2572,Investing in the SDGs,The Nordic countries and European Union have s...,0_27,0_35,NaN,Support,No Relationship
952,"At the halfway mark to 2030, there remains a g...","Despite this ominous news, the SDGs are still ...",0_9,0_26,NaN,Support,No Relationship
11170,SDSN has joined the Group on Earth Observation...,SDG 17 (Partnerships for the Goals) calls for ...,17_26,17_47,NaN,Support,No Relationship
6060,Universal health access and coverage: an expan...,"In HICs and LICs, the pandemic and other crise...",3_0,3_10,NaN,No Relationship,No Relationship
9115,We emphasize that achieving the SDGs rests on ...,"Second, developed countries are not being held...",16_2,16_15,NaN,Attack,No Relationship

rel_deberta
No Relationship    11887
Attack               109
Support               13
Rephrase               2
Name: count, dtype: int64

In [11]:
prefix = "cross_goalGLOBAL_SGD2023_llama3.3-70b"   

args_classified = classify_relationships_deberta(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_deberta"].value_counts()

Using MAX_LENGTH = 200

Processing: /kaggle/working/TFM/Data/Relationships No Keywords/cross_goalGLOBAL_SGD2023_llama3.3-70b.csv
Sample predictions (first 5):

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: At the global level, averaging across countries, not a single SDG is currently projected to be met by 2030, with the poorest countries struggling the most.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: The grim reality is that at the midpoint of the 2030 Agenda, the SDGs are far off track.
  Label: Support

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Similarly, extreme poverty can lead to a collapse of tax revenues, followed by government bankruptcy and further economic collapse, a syndrome that now threatens dozens of poor countries.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: In 2022, Investment per person in the LICs averaged a meagre US$175 per person, compared with US$11,535 per person in the HICs. (Table 1.1). In fact, investment as a share of GDP was lower in the LICs (20.9%) than in all other income categories. The poor are consequently languishing in poverty.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Deep, chronic, and crippling under-investment in virtually all low-income countries (LICs) and lower-middle-income countries (LMICs).
  Label: No Relationship

  Progress: 100/17132 relations classified...
  Progress: 200/17132 relations classified...
  Progress: 300/17132 relations classified...
  Progress: 400/17132 relations classified...
  Progress: 500/17132 relations classified...
  Progress: 600/17132 relations classified...
  Progress: 700/17132 relations classified...
  Progress: 800/17132 relations classified...
  Progress: 900/17132 relations classified...
  Progress: 1000/17132 relations classified...
  Progress: 1100/17132 relations classified...
  Progress: 1200/17132 relations classified...
  Progress: 1300/17132 relations classified...
  Progress: 1400/17132 relations classified...
  Progress: 1500/17132 relations classified...
  Progress: 1600/17132 relations classified...
  Progress: 1700/17132 relations classified...
  Progress: 1800/17132 relations classified...
  Progress: 1900/17132 relations classified...
  Progress: 2000/17132 relations classified...
  Progress: 2100/17132 relations classified...
  Progress: 2200/17132 relations classified...
  Progress: 2300/17132 relations classified...
  Progress: 2400/17132 relations classified...
  Progress: 2500/17132 relations classified...
  Progress: 2600/17132 relations classified...
  Progress: 2700/17132 relations classified...
  Progress: 2800/17132 relations classified...
  Progress: 2900/17132 relations classified...
  Progress: 3000/17132 relations classified...
  Progress: 3100/17132 relations classified...
  Progress: 3200/17132 relations classified...
  Progress: 3300/17132 relations classified...
  Progress: 3400/17132 relations classified...
  Progress: 3500/17132 relations classified...
  Progress: 3600/17132 relations classified...
  Progress: 3700/17132 relations classified...
  Progress: 3800/17132 relations classified...
  Progress: 3900/17132 relations classified...
  Progress: 4000/17132 relations classified...
  Progress: 4100/17132 relations classified...
  Progress: 4200/17132 relations classified...
  Progress: 4300/17132 relations classified...
  Progress: 4400/17132 relations classified...
  Progress: 4500/17132 relations classified...
  Progress: 4600/17132 relations classified...
  Progress: 4700/17132 relations classified...
  Progress: 4800/17132 relations classified...
  Progress: 4900/17132 relations classified...
  Progress: 5000/17132 relations classified...
  Progress: 5100/17132 relations classified...
  Progress: 5200/17132 relations classified...
  Progress: 5300/17132 relations classified...
  Progress: 5400/17132 relations classified...
  Progress: 5500/17132 relations classified...
  Progress: 5600/17132 relations classified...
  Progress: 5700/17132 relations classified...
  Progress: 5800/17132 relations classified...
  Progress: 5900/17132 relations classified...
  Progress: 6000/17132 relations classified...
  Progress: 6100/17132 relations classified...
  Progress: 6200/17132 relations classified...
  Progress: 6300/17132 relations classified...
  Progress: 6400/17132 relations classified...
  Progress: 6500/17132 relations classified...
  Progress: 6600/17132 relations classified...
  Progress: 6700/17132 relations classified...
  Progress: 6800/17132 relations classified...
  Progress: 6900/17132 relations classified...
  Progress: 7000/17132 relations classified...
  Progress: 7100/17132 relations classified...
  Progress: 7200/17132 relations classified...
  Progress: 7300/17132 relations classified...
  Progress: 7400/17132 relations classified...
  Progress: 7500/17132 relations classified...
  Progress: 7600/17132 relations classified...
  Progress: 7700/17132 relations classified...
  Progress: 7800/17132 relations classified...
  Progress: 7900/17132 relations classified...
  Progress: 8000/17132 relations classified...
  Progress: 8100/17132 relations classified...
  Progress: 8200/17132 relations classified...
  Progress: 8300/17132 relations classified...
  Progress: 8400/17132 relations classified...
  Progress: 8500/17132 relations classified...
  Progress: 8600/17132 relations classified...
  Progress: 8700/17132 relations classified...
  Progress: 8800/17132 relations classified...
  Progress: 8900/17132 relations classified...
  Progress: 9000/17132 relations classified...
  Progress: 9100/17132 relations classified...
  Progress: 9200/17132 relations classified...
  Progress: 9300/17132 relations classified...
  Progress: 9400/17132 relations classified...
  Progress: 9500/17132 relations classified...
  Progress: 9600/17132 relations classified...
  Progress: 9700/17132 relations classified...
  Progress: 9800/17132 relations classified...
  Progress: 9900/17132 relations classified...
  Progress: 10000/17132 relations classified...
  Progress: 10100/17132 relations classified...
  Progress: 10200/17132 relations classified...
  Progress: 10300/17132 relations classified...
  Progress: 10400/17132 relations classified...
  Progress: 10500/17132 relations classified...
  Progress: 10600/17132 relations classified...
  Progress: 10700/17132 relations classified...
  Progress: 10800/17132 relations classified...
  Progress: 10900/17132 relations classified...
  Progress: 11000/17132 relations classified...
  Progress: 11100/17132 relations classified...
  Progress: 11200/17132 relations classified...
  Progress: 11300/17132 relations classified...
  Progress: 11400/17132 relations classified...
  Progress: 11500/17132 relations classified...
  Progress: 11600/17132 relations classified...
  Progress: 11700/17132 relations classified...
  Progress: 11800/17132 relations classified...
  Progress: 11900/17132 relations classified...
  Progress: 12000/17132 relations classified...
  Progress: 12100/17132 relations classified...
  Progress: 12200/17132 relations classified...
  Progress: 12300/17132 relations classified...
  Progress: 12400/17132 relations classified...
  Progress: 12500/17132 relations classified...
  Progress: 12600/17132 relations classified...
  Progress: 12700/17132 relations classified...
  Progress: 12800/17132 relations classified...
  Progress: 12900/17132 relations classified...
  Progress: 13000/17132 relations classified...
  Progress: 13100/17132 relations classified...
  Progress: 13200/17132 relations classified...
  Progress: 13300/17132 relations classified...
  Progress: 13400/17132 relations classified...
  Progress: 13500/17132 relations classified...
  Progress: 13600/17132 relations classified...
  Progress: 13700/17132 relations classified...
  Progress: 13800/17132 relations classified...
  Progress: 13900/17132 relations classified...
  Progress: 14000/17132 relations classified...
  Progress: 14100/17132 relations classified...
  Progress: 14200/17132 relations classified...
  Progress: 14300/17132 relations classified...
  Progress: 14400/17132 relations classified...
  Progress: 14500/17132 relations classified...
  Progress: 14600/17132 relations classified...
  Progress: 14700/17132 relations classified...
  Progress: 14800/17132 relations classified...
  Progress: 14900/17132 relations classified...
  Progress: 15000/17132 relations classified...
  Progress: 15100/17132 relations classified...
  Progress: 15200/17132 relations classified...
  Progress: 15300/17132 relations classified...
  Progress: 15400/17132 relations classified...
  Progress: 15500/17132 relations classified...
  Progress: 15600/17132 relations classified...
  Progress: 15700/17132 relations classified...
  Progress: 15800/17132 relations classified...
  Progress: 15900/17132 relations classified...
  Progress: 16000/17132 relations classified...
  Progress: 16100/17132 relations classified...
  Progress: 16200/17132 relations classified...
  Progress: 16300/17132 relations classified...
  Progress: 16400/17132 relations classified...
  Progress: 16500/17132 relations classified...
  Progress: 16600/17132 relations classified...
  Progress: 16700/17132 relations classified...
  Progress: 16800/17132 relations classified...
  Progress: 16900/17132 relations classified...
  Progress: 17000/17132 relations classified...
  Progress: 17100/17132 relations classified...
  Progress: 17132/17132 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships No Keywords/cross_goalGLOBAL_SGD2023_llama3.3-70b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_llama,rel_deberta
8303,"The key finding from this survey is that, seve...","In Finland, 46 percent of parliamentarians are...",0_75,5_5,NaN,No Relationship,No Relationship
8987,We estimate that on average only around 18 per...,"According to IMF estimates in 2019, the financ...",0_60,6_5,NaN,Support,No Relationship
10826,We firmly believe that international cooperati...,Unemployment rates in both HICs and LICs is ab...,0_24,8_0,NaN,No Relationship,No Relationship
13335,"Strategically, the SDSN is very much committed...",In the 2030 Agenda for Sustainable Development...,0_99,9_19,NaN,No Relationship,No Relationship
5173,SDSN’s new flagship initiative – the SDG Trans...,"Those related to hunger, sustainable diets, an...",0_106,3_7,NaN,No Relationship,No Relationship

rel_deberta
No Relationship    17066
Attack                55
Rephrase               7
Support                4
Name: count, dtype: int64

#### Deepseek r1 70B extraction

In [12]:
prefix = "intra_goalGLOBAL_SGD2023_deepseek-r1-70b"   

args_classified = classify_relationships_deberta(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_deberta"].value_counts()

Using MAX_LENGTH = 355

Processing: /kaggle/working/TFM/Data/Relationships No Keywords/intra_goalGLOBAL_SGD2023_deepseek-r1-70b.csv
Sample predictions (first 5):

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Despite this alarming development, the SDGs are still achievable. None of their objectives are beyond our reach.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: The world is off track, but that is all the more reason to double down on the SDGs.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: All countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national SDG strategies and commit to strengthening multilateralism.
  Label: No Relationship

  Progress: 100/17113 relations classified...
  Progress: 200/17113 relations classified...
  Progress: 300/17113 relations classified...
  Progress: 400/17113 relations classified...
  Progress: 500/17113 relations classified...
  Progress: 600/17113 relations classified...
  Progress: 700/17113 relations classified...
  Progress: 800/17113 relations classified...
  Progress: 900/17113 relations classified...
  Progress: 1000/17113 relations classified...
  Progress: 1100/17113 relations classified...
  Progress: 1200/17113 relations classified...
  Progress: 1300/17113 relations classified...
  Progress: 1400/17113 relations classified...
  Progress: 1500/17113 relations classified...
  Progress: 1600/17113 relations classified...
  Progress: 1700/17113 relations classified...
  Progress: 1800/17113 relations classified...
  Progress: 1900/17113 relations classified...
  Progress: 2000/17113 relations classified...
  Progress: 2100/17113 relations classified...
  Progress: 2200/17113 relations classified...
  Progress: 2300/17113 relations classified...
  Progress: 2400/17113 relations classified...
  Progress: 2500/17113 relations classified...
  Progress: 2600/17113 relations classified...
  Progress: 2700/17113 relations classified...
  Progress: 2800/17113 relations classified...
  Progress: 2900/17113 relations classified...
  Progress: 3000/17113 relations classified...
  Progress: 3100/17113 relations classified...
  Progress: 3200/17113 relations classified...
  Progress: 3300/17113 relations classified...
  Progress: 3400/17113 relations classified...
  Progress: 3500/17113 relations classified...
  Progress: 3600/17113 relations classified...
  Progress: 3700/17113 relations classified...
  Progress: 3800/17113 relations classified...
  Progress: 3900/17113 relations classified...
  Progress: 4000/17113 relations classified...
  Progress: 4100/17113 relations classified...
  Progress: 4200/17113 relations classified...
  Progress: 4300/17113 relations classified...
  Progress: 4400/17113 relations classified...
  Progress: 4500/17113 relations classified...
  Progress: 4600/17113 relations classified...
  Progress: 4700/17113 relations classified...
  Progress: 4800/17113 relations classified...
  Progress: 4900/17113 relations classified...
  Progress: 5000/17113 relations classified...
  Progress: 5100/17113 relations classified...
  Progress: 5200/17113 relations classified...
  Progress: 5300/17113 relations classified...
  Progress: 5400/17113 relations classified...
  Progress: 5500/17113 relations classified...
  Progress: 5600/17113 relations classified...
  Progress: 5700/17113 relations classified...
  Progress: 5800/17113 relations classified...
  Progress: 5900/17113 relations classified...
  Progress: 6000/17113 relations classified...
  Progress: 6100/17113 relations classified...
  Progress: 6200/17113 relations classified...
  Progress: 6300/17113 relations classified...
  Progress: 6400/17113 relations classified...
  Progress: 6500/17113 relations classified...
  Progress: 6600/17113 relations classified...
  Progress: 6700/17113 relations classified...
  Progress: 6800/17113 relations classified...
  Progress: 6900/17113 relations classified...
  Progress: 7000/17113 relations classified...
  Progress: 7100/17113 relations classified...
  Progress: 7200/17113 relations classified...
  Progress: 7300/17113 relations classified...
  Progress: 7400/17113 relations classified...
  Progress: 7500/17113 relations classified...
  Progress: 7600/17113 relations classified...
  Progress: 7700/17113 relations classified...
  Progress: 7800/17113 relations classified...
  Progress: 7900/17113 relations classified...
  Progress: 8000/17113 relations classified...
  Progress: 8100/17113 relations classified...
  Progress: 8200/17113 relations classified...
  Progress: 8300/17113 relations classified...
  Progress: 8400/17113 relations classified...
  Progress: 8500/17113 relations classified...
  Progress: 8600/17113 relations classified...
  Progress: 8700/17113 relations classified...
  Progress: 8800/17113 relations classified...
  Progress: 8900/17113 relations classified...
  Progress: 9000/17113 relations classified...
  Progress: 9100/17113 relations classified...
  Progress: 9200/17113 relations classified...
  Progress: 9300/17113 relations classified...
  Progress: 9400/17113 relations classified...
  Progress: 9500/17113 relations classified...
  Progress: 9600/17113 relations classified...
  Progress: 9700/17113 relations classified...
  Progress: 9800/17113 relations classified...
  Progress: 9900/17113 relations classified...
  Progress: 10000/17113 relations classified...
  Progress: 10100/17113 relations classified...
  Progress: 10200/17113 relations classified...
  Progress: 10300/17113 relations classified...
  Progress: 10400/17113 relations classified...
  Progress: 10500/17113 relations classified...
  Progress: 10600/17113 relations classified...
  Progress: 10700/17113 relations classified...
  Progress: 10800/17113 relations classified...
  Progress: 10900/17113 relations classified...
  Progress: 11000/17113 relations classified...
  Progress: 11100/17113 relations classified...
  Progress: 11200/17113 relations classified...
  Progress: 11300/17113 relations classified...
  Progress: 11400/17113 relations classified...
  Progress: 11500/17113 relations classified...
  Progress: 11600/17113 relations classified...
  Progress: 11700/17113 relations classified...
  Progress: 11800/17113 relations classified...
  Progress: 11900/17113 relations classified...
  Progress: 12000/17113 relations classified...
  Progress: 12100/17113 relations classified...
  Progress: 12200/17113 relations classified...
  Progress: 12300/17113 relations classified...
  Progress: 12400/17113 relations classified...
  Progress: 12500/17113 relations classified...
  Progress: 12600/17113 relations classified...
  Progress: 12700/17113 relations classified...
  Progress: 12800/17113 relations classified...
  Progress: 12900/17113 relations classified...
  Progress: 13000/17113 relations classified...
  Progress: 13100/17113 relations classified...
  Progress: 13200/17113 relations classified...
  Progress: 13300/17113 relations classified...
  Progress: 13400/17113 relations classified...
  Progress: 13500/17113 relations classified...
  Progress: 13600/17113 relations classified...
  Progress: 13700/17113 relations classified...
  Progress: 13800/17113 relations classified...
  Progress: 13900/17113 relations classified...
  Progress: 14000/17113 relations classified...
  Progress: 14100/17113 relations classified...
  Progress: 14200/17113 relations classified...
  Progress: 14300/17113 relations classified...
  Progress: 14400/17113 relations classified...
  Progress: 14500/17113 relations classified...
  Progress: 14600/17113 relations classified...
  Progress: 14700/17113 relations classified...
  Progress: 14800/17113 relations classified...
  Progress: 14900/17113 relations classified...
  Progress: 15000/17113 relations classified...
  Progress: 15100/17113 relations classified...
  Progress: 15200/17113 relations classified...
  Progress: 15300/17113 relations classified...
  Progress: 15400/17113 relations classified...
  Progress: 15500/17113 relations classified...
  Progress: 15600/17113 relations classified...
  Progress: 15700/17113 relations classified...
  Progress: 15800/17113 relations classified...
  Progress: 15900/17113 relations classified...
  Progress: 16000/17113 relations classified...
  Progress: 16100/17113 relations classified...
  Progress: 16200/17113 relations classified...
  Progress: 16300/17113 relations classified...
  Progress: 16400/17113 relations classified...
  Progress: 16500/17113 relations classified...
  Progress: 16600/17113 relations classified...
  Progress: 16700/17113 relations classified...
  Progress: 16800/17113 relations classified...
  Progress: 16900/17113 relations classified...
  Progress: 17000/17113 relations classified...
  Progress: 17100/17113 relations classified...
  Progress: 17113/17113 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships No Keywords/intra_goalGLOBAL_SGD2023_deepseek-r1-70b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_robertaL,rel_llama,rel_deberta
14312,Revise liquidity structures for LICs and LMICs...,The SDSN is now a global network of more than ...,17_1,17_51,NaN,No Relationship,No Relationship,No Relationship
6041,"In July 2023, the EU is set to present its fir...",From a simple linear projection of past growth...,0_52,0_88,NaN,Support,Attack,No Relationship
1064,Achieving the SDGs requires global cooperation...,A large majority of governments – 83 percent o...,0_7,0_106,NaN,Support,Support,No Relationship
16617,It is also vital to share fairly and globally ...,One of the consistent findings of the SDSN is ...,17_45,17_46,NaN,Support,Support,No Relationship
6641,Even the progress on consistent national repor...,"Overall, HICs tend to generate the largest neg...",0_59,0_93,NaN,No Relationship,No Relationship,No Relationship

rel_deberta
No Relationship    16948
Attack               142
Support               19
Rephrase               4
Name: count, dtype: int64

In [13]:
prefix = "cross_goalGLOBAL_SGD2023_deepseek-r1-70b"   

args_classified = classify_relationships_deberta(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_deberta"].value_counts()

/tmp/ipykernel_19/2617973462.py:72: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

Using MAX_LENGTH = 382

Processing: /kaggle/working/TFM/Data/Relationships No Keywords/cross_goalGLOBAL_SGD2023_deepseek-r1-70b.csv

/tmp/ipykernel_19/2617973462.py:100: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

Sample predictions (first 5):

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: The grim reality is that at the midpoint of the 2030 Agenda, the SDGs are far off track.
  Label: Support

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: At the global level, averaging across countries, not a single SDG is currently projected to be met by 2030, with the poorest countries struggling the most.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: 1. Increased funding from the multilateral develop-ment banks (MDBs) and public development banks (PDBs) to low- and middle-income countries, linked to investments in the SDGs;
  Label: Attack

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: 2. Enhancement of relief for countries facing debt distress;
  Label: No Relationship

  Progress: 100/118259 relations classified...
  Progress: 200/118259 relations classified...
  Progress: 300/118259 relations classified...
  Progress: 400/118259 relations classified...
  Progress: 500/118259 relations classified...
  Progress: 600/118259 relations classified...
  Progress: 700/118259 relations classified...
  Progress: 800/118259 relations classified...
  Progress: 900/118259 relations classified...
  Progress: 1000/118259 relations classified...
  Progress: 1100/118259 relations classified...
  Progress: 1200/118259 relations classified...
  Progress: 1300/118259 relations classified...
  Progress: 1400/118259 relations classified...
  Progress: 1500/118259 relations classified...
  Progress: 1600/118259 relations classified...
  Progress: 1700/118259 relations classified...
  Progress: 1800/118259 relations classified...
  Progress: 1900/118259 relations classified...
  Progress: 2000/118259 relations classified...
  Progress: 2100/118259 relations classified...
  Progress: 2200/118259 relations classified...
  Progress: 2300/118259 relations classified...
  Progress: 2400/118259 relations classified...
  Progress: 2500/118259 relations classified...
  Progress: 2600/118259 relations classified...
  Progress: 2700/118259 relations classified...
  Progress: 2800/118259 relations classified...
  Progress: 2900/118259 relations classified...
  Progress: 3000/118259 relations classified...
  Progress: 3100/118259 relations classified...
  Progress: 3200/118259 relations classified...
  Progress: 3300/118259 relations classified...
  Progress: 3400/118259 relations classified...
  Progress: 3500/118259 relations classified...
  Progress: 3600/118259 relations classified...
  Progress: 3700/118259 relations classified...
  Progress: 3800/118259 relations classified...
  Progress: 3900/118259 relations classified...
  Progress: 4000/118259 relations classified...
  Progress: 4100/118259 relations classified...
  Progress: 4200/118259 relations classified...
  Progress: 4300/118259 relations classified...
  Progress: 4400/118259 relations classified...
  Progress: 4500/118259 relations classified...
  Progress: 4600/118259 relations classified...
  Progress: 4700/118259 relations classified...
  Progress: 4800/118259 relations classified...
  Progress: 4900/118259 relations classified...
  Progress: 5000/118259 relations classified...
  Progress: 5100/118259 relations classified...
  Progress: 5200/118259 relations classified...
  Progress: 5300/118259 relations classified...
  Progress: 5400/118259 relations classified...
  Progress: 5500/118259 relations classified...
  Progress: 5600/118259 relations classified...
  Progress: 5700/118259 relations classified...
  Progress: 5800/118259 relations classified...
  Progress: 5900/118259 relations classified...
  Progress: 6000/118259 relations classified...
  Progress: 6100/118259 relations classified...
  Progress: 6200/118259 relations classified...
  Progress: 6300/118259 relations classified...
  Progress: 6400/118259 relations classified...
  Progress: 6500/118259 relations classified...
  Progress: 6600/118259 relations classified...
  Progress: 6700/118259 relations classified...
  Progress: 6800/118259 relations classified...
  Progress: 6900/118259 relations classified...
  Progress: 7000/118259 relations classified...
  Progress: 7100/118259 relations classified...
  Progress: 7200/118259 relations classified...
  Progress: 7300/118259 relations classified...
  Progress: 7400/118259 relations classified...
  Progress: 7500/118259 relations classified...
  Progress: 7600/118259 relations classified...
  Progress: 7700/118259 relations classified...
  Progress: 7800/118259 relations classified...
  Progress: 7900/118259 relations classified...
  Progress: 8000/118259 relations classified...
  Progress: 8100/118259 relations classified...
  Progress: 8200/118259 relations classified...
  Progress: 8300/118259 relations classified...
  Progress: 8400/118259 relations classified...
  Progress: 8500/118259 relations classified...
  Progress: 8600/118259 relations classified...
  Progress: 8700/118259 relations classified...
  Progress: 8800/118259 relations classified...
  Progress: 8900/118259 relations classified...
  Progress: 9000/118259 relations classified...
  Progress: 9100/118259 relations classified...
  Progress: 9200/118259 relations classified...
  Progress: 9300/118259 relations classified...
  Progress: 9400/118259 relations classified...
  Progress: 9500/118259 relations classified...
  Progress: 9600/118259 relations classified...
  Progress: 9700/118259 relations classified...
  Progress: 9800/118259 relations classified...
  Progress: 9900/118259 relations classified...
  Progress: 10000/118259 relations classified...
  Progress: 10100/118259 relations classified...
  Progress: 10200/118259 relations classified...
  Progress: 10300/118259 relations classified...
  Progress: 10400/118259 relations classified...
  Progress: 10500/118259 relations classified...
  Progress: 10600/118259 relations classified...
  Progress: 10700/118259 relations classified...
  Progress: 10800/118259 relations classified...
  Progress: 10900/118259 relations classified...
  Progress: 11000/118259 relations classified...
  Progress: 11100/118259 relations classified...
  Progress: 11200/118259 relations classified...
  Progress: 11300/118259 relations classified...
  Progress: 11400/118259 relations classified...
  Progress: 11500/118259 relations classified...
  Progress: 11600/118259 relations classified...
  Progress: 11700/118259 relations classified...
  Progress: 11800/118259 relations classified...
  Progress: 11900/118259 relations classified...
  Progress: 12000/118259 relations classified...
  Progress: 12100/118259 relations classified...
  Progress: 12200/118259 relations classified...
  Progress: 12300/118259 relations classified...
  Progress: 12400/118259 relations classified...
  Progress: 12500/118259 relations classified...
  Progress: 12600/118259 relations classified...
  Progress: 12700/118259 relations classified...
  Progress: 12800/118259 relations classified...
  Progress: 12900/118259 relations classified...
  Progress: 13000/118259 relations classified...
  Progress: 13100/118259 relations classified...
  Progress: 13200/118259 relations classified...
  Progress: 13300/118259 relations classified...
  Progress: 13400/118259 relations classified...
  Progress: 13500/118259 relations classified...
  Progress: 13600/118259 relations classified...
  Progress: 13700/118259 relations classified...
  Progress: 13800/118259 relations classified...
  Progress: 13900/118259 relations classified...
  Progress: 14000/118259 relations classified...
  Progress: 14100/118259 relations classified...
  Progress: 14200/118259 relations classified...
  Progress: 14300/118259 relations classified...
  Progress: 14400/118259 relations classified...
  Progress: 14500/118259 relations classified...
  Progress: 14600/118259 relations classified...
  Progress: 14700/118259 relations classified...
  Progress: 14800/118259 relations classified...
  Progress: 14900/118259 relations classified...
  Progress: 15000/118259 relations classified...
  Progress: 15100/118259 relations classified...
  Progress: 15200/118259 relations classified...
  Progress: 15300/118259 relations classified...
  Progress: 15400/118259 relations classified...
  Progress: 15500/118259 relations classified...
  Progress: 15600/118259 relations classified...
  Progress: 15700/118259 relations classified...
  Progress: 15800/118259 relations classified...
  Progress: 15900/118259 relations classified...
  Progress: 16000/118259 relations classified...
  Progress: 16100/118259 relations classified...
  Progress: 16200/118259 relations classified...
  Progress: 16300/118259 relations classified...
  Progress: 16400/118259 relations classified...
  Progress: 16500/118259 relations classified...
  Progress: 16600/118259 relations classified...
  Progress: 16700/118259 relations classified...
  Progress: 16800/118259 relations classified...
  Progress: 16900/118259 relations classified...
  Progress: 17000/118259 relations classified...
  Progress: 17100/118259 relations classified...
  Progress: 17200/118259 relations classified...
  Progress: 17300/118259 relations classified...
  Progress: 17400/118259 relations classified...
  Progress: 17500/118259 relations classified...
  Progress: 17600/118259 relations classified...
  Progress: 17700/118259 relations classified...
  Progress: 17800/118259 relations classified...
  Progress: 17900/118259 relations classified...
  Progress: 18000/118259 relations classified...
  Progress: 18100/118259 relations classified...
  Progress: 18200/118259 relations classified...
  Progress: 18300/118259 relations classified...
  Progress: 18400/118259 relations classified...
  Progress: 18500/118259 relations classified...
  Progress: 18600/118259 relations classified...
  Progress: 18700/118259 relations classified...
  Progress: 18800/118259 relations classified...
  Progress: 18900/118259 relations classified...
  Progress: 19000/118259 relations classified...
  Progress: 19100/118259 relations classified...
  Progress: 19200/118259 relations classified...
  Progress: 19300/118259 relations classified...
  Progress: 19400/118259 relations classified...
  Progress: 19500/118259 relations classified...
  Progress: 19600/118259 relations classified...
  Progress: 19700/118259 relations classified...
  Progress: 19800/118259 relations classified...
  Progress: 19900/118259 relations classified...
  Progress: 20000/118259 relations classified...
  Progress: 20100/118259 relations classified...
  Progress: 20200/118259 relations classified...
  Progress: 20300/118259 relations classified...
  Progress: 20400/118259 relations classified...
  Progress: 20500/118259 relations classified...
  Progress: 20600/118259 relations classified...
  Progress: 20700/118259 relations classified...
  Progress: 20800/118259 relations classified...
  Progress: 20900/118259 relations classified...
  Progress: 21000/118259 relations classified...
  Progress: 21100/118259 relations classified...
  Progress: 21200/118259 relations classified...
  Progress: 21300/118259 relations classified...
  Progress: 21400/118259 relations classified...
  Progress: 21500/118259 relations classified...
  Progress: 21600/118259 relations classified...
  Progress: 21700/118259 relations classified...
  Progress: 21800/118259 relations classified...
  Progress: 21900/118259 relations classified...
  Progress: 22000/118259 relations classified...
  Progress: 22100/118259 relations classified...
  Progress: 22200/118259 relations classified...
  Progress: 22300/118259 relations classified...
  Progress: 22400/118259 relations classified...
  Progress: 22500/118259 relations classified...
  Progress: 22600/118259 relations classified...
  Progress: 22700/118259 relations classified...
  Progress: 22800/118259 relations classified...
  Progress: 22900/118259 relations classified...
  Progress: 23000/118259 relations classified...
  Progress: 23100/118259 relations classified...
  Progress: 23200/118259 relations classified...
  Progress: 23300/118259 relations classified...
  Progress: 23400/118259 relations classified...
  Progress: 23500/118259 relations classified...
  Progress: 23600/118259 relations classified...
  Progress: 23700/118259 relations classified...
  Progress: 23800/118259 relations classified...
  Progress: 23900/118259 relations classified...
  Progress: 24000/118259 relations classified...
  Progress: 24100/118259 relations classified...
  Progress: 24200/118259 relations classified...
  Progress: 24300/118259 relations classified...
  Progress: 24400/118259 relations classified...
  Progress: 24500/118259 relations classified...
  Progress: 24600/118259 relations classified...
  Progress: 24700/118259 relations classified...
  Progress: 24800/118259 relations classified...
  Progress: 24900/118259 relations classified...
  Progress: 25000/118259 relations classified...
  Progress: 25100/118259 relations classified...
  Progress: 25200/118259 relations classified...
  Progress: 25300/118259 relations classified...
  Progress: 25400/118259 relations classified...
  Progress: 25500/118259 relations classified...
  Progress: 25600/118259 relations classified...
  Progress: 25700/118259 relations classified...
  Progress: 25800/118259 relations classified...
  Progress: 25900/118259 relations classified...
  Progress: 26000/118259 relations classified...
  Progress: 26100/118259 relations classified...
  Progress: 26200/118259 relations classified...
  Progress: 26300/118259 relations classified...
  Progress: 26400/118259 relations classified...
  Progress: 26500/118259 relations classified...
  Progress: 26600/118259 relations classified...
  Progress: 26700/118259 relations classified...
  Progress: 26800/118259 relations classified...
  Progress: 26900/118259 relations classified...
  Progress: 27000/118259 relations classified...
  Progress: 27100/118259 relations classified...
  Progress: 27200/118259 relations classified...
  Progress: 27300/118259 relations classified...
  Progress: 27400/118259 relations classified...
  Progress: 27500/118259 relations classified...
  Progress: 27600/118259 relations classified...
  Progress: 27700/118259 relations classified...
  Progress: 27800/118259 relations classified...
  Progress: 27900/118259 relations classified...
  Progress: 28000/118259 relations classified...
  Progress: 28100/118259 relations classified...
  Progress: 28200/118259 relations classified...
  Progress: 28300/118259 relations classified...
  Progress: 28400/118259 relations classified...
  Progress: 28500/118259 relations classified...
  Progress: 28600/118259 relations classified...
  Progress: 28700/118259 relations classified...
  Progress: 28800/118259 relations classified...
  Progress: 28900/118259 relations classified...
  Progress: 29000/118259 relations classified...
  Progress: 29100/118259 relations classified...
  Progress: 29200/118259 relations classified...
  Progress: 29300/118259 relations classified...
  Progress: 29400/118259 relations classified...
  Progress: 29500/118259 relations classified...
  Progress: 29600/118259 relations classified...
  Progress: 29700/118259 relations classified...
  Progress: 29800/118259 relations classified...
  Progress: 29900/118259 relations classified...
  Progress: 30000/118259 relations classified...
  Progress: 30100/118259 relations classified...
  Progress: 30200/118259 relations classified...
  Progress: 30300/118259 relations classified...
  Progress: 30400/118259 relations classified...
  Progress: 30500/118259 relations classified...
  Progress: 30600/118259 relations classified...
  Progress: 30700/118259 relations classified...
  Progress: 30800/118259 relations classified...
  Progress: 30900/118259 relations classified...
  Progress: 31000/118259 relations classified...
  Progress: 31100/118259 relations classified...
  Progress: 31200/118259 relations classified...
  Progress: 31300/118259 relations classified...
  Progress: 31400/118259 relations classified...
  Progress: 31500/118259 relations classified...
  Progress: 31600/118259 relations classified...
  Progress: 31700/118259 relations classified...
  Progress: 31800/118259 relations classified...
  Progress: 31900/118259 relations classified...
  Progress: 32000/118259 relations classified...
  Progress: 32100/118259 relations classified...
  Progress: 32200/118259 relations classified...
  Progress: 32300/118259 relations classified...
  Progress: 32400/118259 relations classified...
  Progress: 32500/118259 relations classified...
  Progress: 32600/118259 relations classified...
  Progress: 32700/118259 relations classified...
  Progress: 32800/118259 relations classified...
  Progress: 32900/118259 relations classified...
  Progress: 33000/118259 relations classified...
  Progress: 33100/118259 relations classified...
  Progress: 33200/118259 relations classified...
  Progress: 33300/118259 relations classified...
  Progress: 33400/118259 relations classified...
  Progress: 33500/118259 relations classified...
  Progress: 33600/118259 relations classified...
  Progress: 33700/118259 relations classified...
  Progress: 33800/118259 relations classified...
  Progress: 33900/118259 relations classified...
  Progress: 34000/118259 relations classified...
  Progress: 34100/118259 relations classified...
  Progress: 34200/118259 relations classified...
  Progress: 34300/118259 relations classified...
  Progress: 34400/118259 relations classified...
  Progress: 34500/118259 relations classified...
  Progress: 34600/118259 relations classified...
  Progress: 34700/118259 relations classified...
  Progress: 34800/118259 relations classified...
  Progress: 34900/118259 relations classified...
  Progress: 35000/118259 relations classified...
  Progress: 35100/118259 relations classified...
  Progress: 35200/118259 relations classified...
  Progress: 35300/118259 relations classified...
  Progress: 35400/118259 relations classified...
  Progress: 35500/118259 relations classified...
  Progress: 35600/118259 relations classified...
  Progress: 35700/118259 relations classified...
  Progress: 35800/118259 relations classified...
  Progress: 35900/118259 relations classified...
  Progress: 36000/118259 relations classified...
  Progress: 36100/118259 relations classified...
  Progress: 36200/118259 relations classified...
  Progress: 36300/118259 relations classified...
  Progress: 36400/118259 relations classified...
  Progress: 36500/118259 relations classified...
  Progress: 36600/118259 relations classified...
  Progress: 36700/118259 relations classified...
  Progress: 36800/118259 relations classified...
  Progress: 36900/118259 relations classified...
  Progress: 37000/118259 relations classified...
  Progress: 37100/118259 relations classified...
  Progress: 37200/118259 relations classified...
  Progress: 37300/118259 relations classified...
  Progress: 37400/118259 relations classified...
  Progress: 37500/118259 relations classified...
  Progress: 37600/118259 relations classified...
  Progress: 37700/118259 relations classified...
  Progress: 37800/118259 relations classified...
  Progress: 37900/118259 relations classified...
  Progress: 38000/118259 relations classified...
  Progress: 38100/118259 relations classified...
  Progress: 38200/118259 relations classified...
  Progress: 38300/118259 relations classified...
  Progress: 38400/118259 relations classified...
  Progress: 38500/118259 relations classified...

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_robertaL,rel_flanT5,rel_llama,rel_deberta
53786,"At the mid-point of the SDG agenda, we are far...","Working together with the IMF and the MDBs, th...",0_82,17_44,NaN,No Relationship,Support,NaN,No Relationship
81497,Governments are only now mapping out pathways ...,The SDSN is now a global network of more than ...,3_6,17_51,NaN,Support,Support,NaN,No Relationship
72972,The 2021 UN Food Systems Summit raised many ur...,Despite the world improving on average half a ...,2_1,15_14,NaN,Support,No Relationship,NaN,No Relationship
55223,The SDGs have a significant impact on public m...,We firmly believe that international cooperati...,0_101,17_18,NaN,Support,Support,NaN,No Relationship
24597,SDG transformations.,The report’s recommendations include calling f...,0_8,10_5,NaN,Support,Support,Support,No Relationship

rel_deberta
No Relationship    117438
Attack                655
Rephrase              111
Support                55
Name: count, dtype: int64