# TFM: Análisis de Políticas de Sostenibilidad mediante técnicas de Argumentacion Computacional

## Clasificación de relaciones con google/flan-t5-base

Model page: https://huggingface.co/google/flan-t5-base

# No keywords

In [1]:
import os
import re
import math
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import gc

process_rel_path = r"/kaggle/working/TFM/Data/Relationships Keywords"
hf_model_repo = "google/flan-t5-base"
model_name = "flanT5"  

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tokenizer = AutoTokenizer.from_pretrained(hf_model_repo)
model =AutoModelForSeq2SeqLM.from_pretrained(hf_model_repo).to(device)
model.eval()

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

2025-08-24 23:01:14.012122: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1756076474.369998      19 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1756076474.469660      19 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

model.safetensors:   0%|          | 0.00/990M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

T5ForConditionalGeneration(
  (shared): Embedding(32128, 768)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 768)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
              (relative_attention_bias): Embedding(32, 12)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=768, out_features=2048, bias=False)
              (wi_1): Linear(in_features=768, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): NewGELUActivation()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-11): 11 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=768, out_features=2048, bias=False)
              (wi_1): Linear(in_features=768, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): NewGELUActivation()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (decoder): T5Stack(
    (embed_tokens): Embedding(32128, 768)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
              (relative_attention_bias): Embedding(32, 12)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=768, out_features=2048, bias=False)
              (wi_1): Linear(in_features=768, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): NewGELUActivation()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-11): 11 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=768, out_features=2048, bias=False)
              (wi_1): Linear(in_features=768, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): NewGELUActivation()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (lm_head): Linear(in_features=768, out_features=32128, bias=False)
)

In [2]:
!git clone https://github.com/camipalo/TFM.git

Cloning into 'TFM'...
remote: Enumerating objects: 2313, done.
remote: Counting objects: 100% (74/74), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 2313 (delta 50), reused 55 (delta 33), pack-reused 2239 (from 2)
Receiving objects: 100% (2313/2313), 90.61 MiB | 13.86 MiB/s, done.
Resolving deltas: 100% (1940/1940), done.
Updating files: 100% (1052/1052), done.

In [3]:
def preprocess_text(s):
    if not isinstance(s, str):
        return ""
    s = s.lower()
    s = s.strip()
    s = re.sub(r"\s+", " ", s)
    return s

def build_prompt(arg1, arg2):
    return (
        "Classify the relationship between the following two arguments.\n"
        "Respond with exactly one label from: Support, Attack, Rephrase, No Relationship.\n\n"

        f"Argument 1: {arg1}\n"
        f"Argument 2: {arg2}\n\n"
        "Label:"
    )

def normalize_label(text):
    t = (text or "").strip().lower()
    if "support" == t or t.startswith("support"):
        return "Support"
    if "attack" == t or t.startswith("attack") or "conflict" in t:
        return "Attack"
    if "rephrase" == t or "paraphrase" in t or t.startswith("reph"):
        return "Rephrase"
    if "no relationship" == t or "no relation" in t or "none" == t:
        return "No Relationship"
    # fallbacks for short/partial tokens
    if t in {"support", "attack", "rephrase"}:
        return t.capitalize()
    return "No Relationship"

def compute_max_length_for_prompts(input_dir, prefix_substring, tokenizer, safety_limit=None):   
    if safety_limit is None:
        safety_limit = min(getattr(tokenizer, "model_max_length", 512) or 512, 512)

    max_len = 0
    files = [f for f in os.listdir(input_dir) if f.endswith(".csv") and prefix_substring in f]
    for fn in files:
        path = os.path.join(input_dir, fn)
        df = pd.read_csv(path)
        if "SDGarg1" not in df.columns or "SDGarg2" not in df.columns:
            continue
        for a, b in zip(df["SDGarg1"], df["SDGarg2"]):
            a = preprocess_text(str(a) if pd.notna(a) else "")
            b = preprocess_text(str(b) if pd.notna(b) else "")
            prompt = build_prompt(a, b)
            ids = tokenizer(prompt, truncation=False, padding=False)["input_ids"]
            max_len = max(max_len, len(ids))
    return min(max_len if max_len > 0 else 128, safety_limit)


def predict_labels_flan(prompts, max_length):
    enc = tokenizer(
        prompts, return_tensors="pt", padding=True, truncation=True, max_length=max_length
    ).to(device)

    outputs = model.generate(
        **enc,
        max_new_tokens=GEN_MAX_NEW_TOKENS,
        do_sample=False,              
        num_beams=1,
    )
    decoded = tokenizer.batch_decode(outputs, skip_special_tokens=True)
    labels = [normalize_label(x) for x in decoded]
    labels = [l if l in VALID_OUT else "No Relationship" for l in labels]
    return labels

def free_cuda():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

def classify_relationships_flan(input_dir, prefix_substring):
    files = [f for f in os.listdir(input_dir) if f.endswith(".csv") and prefix_substring in f]
    if not files:
        print(f"No CSVs found in '{input_dir}' containing '{prefix_substring}'.")
        return

    # compute a safe prompt max length once per run
    MAX_LENGTH = compute_max_length_for_prompts(input_dir, prefix_substring, tokenizer)
    print(f"Using MAX_LENGTH = {MAX_LENGTH}")

    for fn in files:
        path = os.path.join(input_dir, fn)
        print(f"\nProcessing: {path}")
        df = pd.read_csv(path)

        if "SDGarg1" not in df.columns or "SDGarg2" not in df.columns:
            print(f"  Skipped (missing SDGarg1/SDGarg2): {fn}")
            continue

        df[rel_col] = ""

        n = len(df)
        total_done = 0
        first_examples = []

        batches = math.ceil(n / BATCH_SIZE)
        for bi in range(batches):
            s = bi * BATCH_SIZE
            e = min((bi + 1) * BATCH_SIZE, n)
            chunk = df.iloc[s:e]

            prompts = []
            a1_list = []
            a2_list = []
            for a1, a2 in zip(chunk["SDGarg1"], chunk["SDGarg2"]):
                a1 = preprocess_text(str(a1) if pd.notna(a1) else "")
                a2 = preprocess_text(str(a2) if pd.notna(a2) else "")
                prompts.append(build_prompt(a1, a2))
                a1_list.append(a1)
                a2_list.append(a2)

            try:
                labels = predict_labels_flan(prompts, max_length=MAX_LENGTH)
            except Exception as ex:
                print(f"  Batch {bi+1}/{batches} error: {ex}. Marking 'No Relationship'.")
                labels = ["No Relationship"] * len(prompts)

            df.loc[chunk.index, rel_col] = labels

            for a1, a2, lab in zip(a1_list, a2_list, labels):
                if len(first_examples) < 5:
                    first_examples.append((a1, a2, lab))
                elif len(first_examples) == 5:
                    print("Sample predictions (first 5):\n")
                    for a1, a2, lab in first_examples:
                        print(f"- Arg1: {a1[:]}\n-Arg2: {a2[:]}\nLabel: {lab}\n\n")
                    first_examples.append((a1, a2, lab))                                        

            total_done += len(prompts)
            if total_done % 100 < BATCH_SIZE: 
                print(f"  Progress: {total_done}/{n} relations classified...")

        # handle missing args (safety)
        mask_nan = df["SDGarg1"].isna() | df["SDGarg2"].isna()
        df.loc[mask_nan, rel_col] = "No Relationship"

        # Ensure valid set
        bad = ~df[rel_col].isin(VALID_OUT)
        if bad.any():
            df.loc[bad, rel_col] = "No Relationship"

        df.to_csv(path, index=False, encoding="utf-8")
        free_cuda()
        print(f"Saved: {path}")
        return df

## GLOBAL SDG 2023

#### Qwen2.5 3B extraction

In [4]:
prefix = "intra_goalGLOBAL_SGD2023_qwen2.5-3b"   
rel_col = f"rel_{model_name}"
BATCH_SIZE = 250
GEN_MAX_NEW_TOKENS = 3                
TEMPERATURE = 0.0
VALID_OUT = {"Support", "Attack", "Rephrase", "No Relationship"}


args_classified = classify_relationships_flan(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_flanT5"].value_counts()

Using MAX_LENGTH = 192

Processing: /kaggle/working/TFM/Data/Relationships Keywords/intra_goalGLOBAL_SGD2023_qwen2.5-3b.csv
Sample predictions (first 5):

- Arg1: at their core, the sdgs are an investment agenda: it is critical that un member states adopt and implement the sdg stimulus and support a comprehensive reform of the global financial architecture.
-Arg2: investing in statistical capacity, science, and data literacy are important priorities for achieving the sdgs.
Label: Support


- Arg1: at their core, the sdgs are an investment agenda: it is critical that un member states adopt and implement the sdg stimulus and support a comprehensive reform of the global financial architecture.
-Arg2: at the global level, averaging across countries, not a single sdg is currently projected to be met by 2030, with the poorest countries struggling the most.
Label: No Relationship


- Arg1: at their core, the sdgs are an investment agenda: it is critical that un member states adopt and implement the sdg stimulus and support a comprehensive reform of the global financial architecture.
-Arg2: all un member states should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of ‘leave no one behind’.
Label: Support


- Arg1: at their core, the sdgs are an investment agenda: it is critical that un member states adopt and implement the sdg stimulus and support a comprehensive reform of the global financial architecture.
-Arg2: the sdgs are seriously off track. according to the annual sdg index, global achievement of the sdgs rose only slightly, from 64 percent in 2015 to 66 percent in 2019 – far too slowly to meet the goals by 2030, and with highly uneven progress within and between countries.
Label: Attack


- Arg1: at their core, the sdgs are an investment agenda: it is critical that un member states adopt and implement the sdg stimulus and support a comprehensive reform of the global financial architecture.
-Arg2: investing in the sdgs is an investment agenda. in the most basic terms, the world must devote an increased portion of current output to building up sustainable capital assets for the future, and must deploy such assets effectively.
Label: Support


  Progress: 250/507 relations classified...
  Progress: 500/507 relations classified...
  Progress: 507/507 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships Keywords/intra_goalGLOBAL_SGD2023_qwen2.5-3b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_flanT5
174,"The United States, as the world’s biggest econ...",The integration of the SDGs in national budget...,0_7,0_21,NaN,Support
19,"At their core, the SDGs are an investment agen...",A large majority of governments – 83 percent o...,0_0,0_20,NaN,Support
301,"First, that UN Member States, at the 2023 SDG ...",While comparable country-level data are not ye...,0_16,0_22,NaN,Support
212,All countries should use the half-way momentum...,"the SDG Index, including its regional and loca...",0_9,0_24,NaN,Support
34,"Investing in statistical capacity, science, an...",Most of the low-income and lower-middle income...,0_1,0_10,NaN,Support

rel_flanT5
Support            418
No Relationship     85
Attack               4
Name: count, dtype: int64

In [5]:
prefix = "cross_goalGLOBAL_SGD2023_qwen2.5-3b"   
rel_col = f"rel_{model_name}"
BATCH_SIZE = 250
GEN_MAX_NEW_TOKENS = 3                
TEMPERATURE = 0.0
VALID_OUT = {"Support", "Attack", "Rephrase", "No Relationship"}


args_classified = classify_relationships_flan(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_flanT5"].value_counts()

Using MAX_LENGTH = 209

Processing: /kaggle/working/TFM/Data/Relationships Keywords/cross_goalGLOBAL_SGD2023_qwen2.5-3b.csv
Sample predictions (first 5):

- Arg1: at their core, the sdgs are an investment agenda: it is critical that un member states adopt and implement the sdg stimulus and support a comprehensive reform of the global financial architecture.
-Arg2: increased funding from the multilateral development banks (mdbs) and public development banks (pdbs) to low- and middle-income countries, linked to investments in the sdgs;
Label: Support


- Arg1: at their core, the sdgs are an investment agenda: it is critical that un member states adopt and implement the sdg stimulus and support a comprehensive reform of the global financial architecture.
-Arg2: many of them lack an adequately high sdg commitment, and almost all lack access to the necessary financial means to implement the sdgs.
Label: No Relationship


- Arg1: at their core, the sdgs are an investment agenda: it is critical that un member states adopt and implement the sdg stimulus and support a comprehensive reform of the global financial architecture.
-Arg2: the sdg dashboards rate rich countries, including nordic countries, at ‘red’ on several sdgs – particularly those related to responsible consumption and production, climate action, and biodiversity – meaning major challenges remain (lafortune, sachs, and schmidt-traub 2020).
Label: No Relationship


- Arg1: investing in statistical capacity, science, and data literacy are important priorities for achieving the sdgs.
-Arg2: increased funding from the multilateral development banks (mdbs) and public development banks (pdbs) to low- and middle-income countries, linked to investments in the sdgs;
Label: Support


- Arg1: investing in statistical capacity, science, and data literacy are important priorities for achieving the sdgs.
-Arg2: many of them lack an adequately high sdg commitment, and almost all lack access to the necessary financial means to implement the sdgs.
Label: No Relationship


  Progress: 250/3958 relations classified...
  Progress: 500/3958 relations classified...
  Progress: 750/3958 relations classified...
  Progress: 1000/3958 relations classified...
  Progress: 1250/3958 relations classified...
  Progress: 1500/3958 relations classified...
  Progress: 1750/3958 relations classified...
  Progress: 2000/3958 relations classified...
  Progress: 2250/3958 relations classified...
  Progress: 2500/3958 relations classified...
  Progress: 2750/3958 relations classified...
  Progress: 3000/3958 relations classified...
  Progress: 3250/3958 relations classified...
  Progress: 3500/3958 relations classified...
  Progress: 3750/3958 relations classified...
  Progress: 3958/3958 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships Keywords/cross_goalGLOBAL_SGD2023_qwen2.5-3b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_flanT5
679,While comparable country-level data are not ye...,"Inclusive economic growth, full and productive...",0_22,8_2,NaN,Support
1547,"the SDG Index, including its regional and loca...",Countries promote global cooperation for susta...,0_24,16_8,NaN,Support
2208,The pandemic and other crises have led to subs...,Sustainable cities: urban infrastructure and s...,3_1,11_0,NaN,Support
1909,Many of them lack an adequately high SDG commi...,"The European Green Deal (EGD), which is exempl...",1_1,9_1,NaN,Support
145,All countries should use the half-way momentum...,The pandemic and other crises have led to subs...,0_9,3_1,NaN,No Relationship

rel_flanT5
Support            2848
No Relationship    1110
Name: count, dtype: int64

#### Gemma3 27B extraction

In [6]:
prefix = "intra_goalGLOBAL_SGD2023_gemma3-27b"   
rel_col = f"rel_{model_name}"
BATCH_SIZE = 250
GEN_MAX_NEW_TOKENS = 3                
TEMPERATURE = 0.0
VALID_OUT = {"Support", "Attack", "Rephrase", "No Relationship"}


args_classified = classify_relationships_flan(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_flanT5"].value_counts()

Using MAX_LENGTH = 230

Processing: /kaggle/working/TFM/Data/Relationships Keywords/intra_goalGLOBAL_SGD2023_gemma3-27b.csv
Sample predictions (first 5):

- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: despite this alarming development, the sdgs are still achievable.
Label: No Relationship


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: at their core, the sdgs are an investment agenda: it is critical that un member states adopt and implement the sdg stimulus and support a comprehensive reform of the global financial architecture.
Label: Support


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: to achieve the sdgs the world must both alter its current investment patterns and increase the overall volume of investments.
Label: Support


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: the stimulus’ urgent objective is to address the chronic shortfall of international sdg financing confronting the lics and lmics, and to ramp up financing flows by at least us$500 billion by 2025.
Label: Support


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: further investment is needed in statistical capacity and data literacy to support long-term pathways for key sdg transformations.
Label: Support


  Progress: 250/3354 relations classified...
  Progress: 500/3354 relations classified...
  Progress: 750/3354 relations classified...
  Progress: 1000/3354 relations classified...
  Progress: 1250/3354 relations classified...
  Progress: 1500/3354 relations classified...
  Progress: 1750/3354 relations classified...
  Progress: 2000/3354 relations classified...
  Progress: 2250/3354 relations classified...
  Progress: 2500/3354 relations classified...
  Progress: 2750/3354 relations classified...
  Progress: 3000/3354 relations classified...
  Progress: 3250/3354 relations classified...
  Progress: 3354/3354 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships Keywords/intra_goalGLOBAL_SGD2023_gemma3-27b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_flanT5
2600,Current geopolitical tensions are hindering SD...,Governments must take the lead in all six area...,16_1,16_14,NaN,No Relationship
1962,Unsustainable consumption is strongly intercon...,"Compared with other SDG monitoring reports, ho...",12_1,12_6,NaN,No Relationship
2492,the destruction of coastal wetland ecosystems;,"The Convention on Biological Diversity, adopte...",14_2,14_9,NaN,No Relationship
2653,to give all people the skills and knowledge to...,"There are no magic numbers, but rather a suite...",16_4,16_19,NaN,Support
2848,Achieving the SDGs requires global cooperation...,These fora are critical to encourage internati...,17_2,17_25,NaN,Support

rel_flanT5
Support            2406
No Relationship     860
Attack               88
Name: count, dtype: int64

In [7]:
prefix = "cross_goalGLOBAL_SGD2023_gemma3-27b"   
rel_col = f"rel_{model_name}"
BATCH_SIZE = 250
GEN_MAX_NEW_TOKENS = 3                
TEMPERATURE = 0.0
VALID_OUT = {"Support", "Attack", "Rephrase", "No Relationship"}


args_classified = classify_relationships_flan(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_flanT5"].value_counts()

Using MAX_LENGTH = 241

Processing: /kaggle/working/TFM/Data/Relationships Keywords/cross_goalGLOBAL_SGD2023_gemma3-27b.csv
Sample predictions (first 5):

- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: greatly increased funding for national and subnational governments and private businesses in the emerging economies, especially the low-income countries (lics) and lower-middle-income countries (lmics), to carry out needed sdg actions;
Label: No Relationship


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: to give all people the skills and knowledge to end poverty, protect the environment, and build peaceful and inclusive societies.
Label: Support


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: although all governments are in principle committed to economic justice as enshrined in the universal declaration of human rights, and to the sdg tenets of ‘leave no one behind’ and ‘reach the furthest behind first’, too few are living up to these commitments, especially as powerful groups block adequate public support for weaker groups.
Label: Attack


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: similarly, extreme poverty can lead to a collapse of tax revenues, followed by government bankruptcy and further economic collapse, a syndrome that now threatens dozens of poor countries.
Label: Attack


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: most of the low-income and lower-middle income countries, home to more than the half of humanity, face major challenges in achieving most of the sdgs by 2030.
Label: Attack


  Progress: 250/36832 relations classified...
  Progress: 500/36832 relations classified...
  Progress: 750/36832 relations classified...
  Progress: 1000/36832 relations classified...
  Progress: 1250/36832 relations classified...
  Progress: 1500/36832 relations classified...
  Progress: 1750/36832 relations classified...
  Progress: 2000/36832 relations classified...
  Progress: 2250/36832 relations classified...
  Progress: 2500/36832 relations classified...
  Progress: 2750/36832 relations classified...
  Progress: 3000/36832 relations classified...
  Progress: 3250/36832 relations classified...
  Progress: 3500/36832 relations classified...
  Progress: 3750/36832 relations classified...
  Progress: 4000/36832 relations classified...
  Progress: 4250/36832 relations classified...
  Progress: 4500/36832 relations classified...
  Progress: 4750/36832 relations classified...
  Progress: 5000/36832 relations classified...
  Progress: 5250/36832 relations classified...
  Progress: 5500/36832 relations classified...
  Progress: 5750/36832 relations classified...
  Progress: 6000/36832 relations classified...
  Progress: 6250/36832 relations classified...
  Progress: 6500/36832 relations classified...
  Progress: 6750/36832 relations classified...
  Progress: 7000/36832 relations classified...
  Progress: 7250/36832 relations classified...
  Progress: 7500/36832 relations classified...
  Progress: 7750/36832 relations classified...
  Progress: 8000/36832 relations classified...
  Progress: 8250/36832 relations classified...
  Progress: 8500/36832 relations classified...
  Progress: 8750/36832 relations classified...
  Progress: 9000/36832 relations classified...
  Progress: 9250/36832 relations classified...
  Progress: 9500/36832 relations classified...
  Progress: 9750/36832 relations classified...
  Progress: 10000/36832 relations classified...
  Progress: 10250/36832 relations classified...
  Progress: 10500/36832 relations classified...
  Progress: 10750/36832 relations classified...
  Progress: 11000/36832 relations classified...
  Progress: 11250/36832 relations classified...
  Progress: 11500/36832 relations classified...
  Progress: 11750/36832 relations classified...
  Progress: 12000/36832 relations classified...
  Progress: 12250/36832 relations classified...
  Progress: 12500/36832 relations classified...
  Progress: 12750/36832 relations classified...
  Progress: 13000/36832 relations classified...
  Progress: 13250/36832 relations classified...
  Progress: 13500/36832 relations classified...
  Progress: 13750/36832 relations classified...
  Progress: 14000/36832 relations classified...
  Progress: 14250/36832 relations classified...
  Progress: 14500/36832 relations classified...
  Progress: 14750/36832 relations classified...
  Progress: 15000/36832 relations classified...
  Progress: 15250/36832 relations classified...
  Progress: 15500/36832 relations classified...
  Progress: 15750/36832 relations classified...
  Progress: 16000/36832 relations classified...
  Progress: 16250/36832 relations classified...
  Progress: 16500/36832 relations classified...
  Progress: 16750/36832 relations classified...
  Progress: 17000/36832 relations classified...
  Progress: 17250/36832 relations classified...
  Progress: 17500/36832 relations classified...
  Progress: 17750/36832 relations classified...
  Progress: 18000/36832 relations classified...
  Progress: 18250/36832 relations classified...
  Progress: 18500/36832 relations classified...
  Progress: 18750/36832 relations classified...
  Progress: 19000/36832 relations classified...
  Progress: 19250/36832 relations classified...
  Progress: 19500/36832 relations classified...
  Progress: 19750/36832 relations classified...
  Progress: 20000/36832 relations classified...
  Progress: 20250/36832 relations classified...
  Progress: 20500/36832 relations classified...
  Progress: 20750/36832 relations classified...
  Progress: 21000/36832 relations classified...
  Progress: 21250/36832 relations classified...
  Progress: 21500/36832 relations classified...
  Progress: 21750/36832 relations classified...
  Progress: 22000/36832 relations classified...
  Progress: 22250/36832 relations classified...
  Progress: 22500/36832 relations classified...
  Progress: 22750/36832 relations classified...
  Progress: 23000/36832 relations classified...
  Progress: 23250/36832 relations classified...
  Progress: 23500/36832 relations classified...
  Progress: 23750/36832 relations classified...
  Progress: 24000/36832 relations classified...
  Progress: 24250/36832 relations classified...
  Progress: 24500/36832 relations classified...
  Progress: 24750/36832 relations classified...
  Progress: 25000/36832 relations classified...
  Progress: 25250/36832 relations classified...
  Progress: 25500/36832 relations classified...
  Progress: 25750/36832 relations classified...
  Progress: 26000/36832 relations classified...
  Progress: 26250/36832 relations classified...
  Progress: 26500/36832 relations classified...
  Progress: 26750/36832 relations classified...
  Progress: 27000/36832 relations classified...
  Progress: 27250/36832 relations classified...
  Progress: 27500/36832 relations classified...
  Progress: 27750/36832 relations classified...
  Progress: 28000/36832 relations classified...
  Progress: 28250/36832 relations classified...
  Progress: 28500/36832 relations classified...
  Progress: 28750/36832 relations classified...
  Progress: 29000/36832 relations classified...
  Progress: 29250/36832 relations classified...
  Progress: 29500/36832 relations classified...
  Progress: 29750/36832 relations classified...
  Progress: 30000/36832 relations classified...
  Progress: 30250/36832 relations classified...
  Progress: 30500/36832 relations classified...
  Progress: 30750/36832 relations classified...
  Progress: 31000/36832 relations classified...
  Progress: 31250/36832 relations classified...
  Progress: 31500/36832 relations classified...
  Progress: 31750/36832 relations classified...
  Progress: 32000/36832 relations classified...
  Progress: 32250/36832 relations classified...
  Progress: 32500/36832 relations classified...
  Progress: 32750/36832 relations classified...
  Progress: 33000/36832 relations classified...
  Progress: 33250/36832 relations classified...
  Progress: 33500/36832 relations classified...
  Progress: 33750/36832 relations classified...
  Progress: 34000/36832 relations classified...
  Progress: 34250/36832 relations classified...
  Progress: 34500/36832 relations classified...
  Progress: 34750/36832 relations classified...
  Progress: 35000/36832 relations classified...
  Progress: 35250/36832 relations classified...
  Progress: 35500/36832 relations classified...
  Progress: 35750/36832 relations classified...
  Progress: 36000/36832 relations classified...
  Progress: 36250/36832 relations classified...
  Progress: 36500/36832 relations classified...
  Progress: 36750/36832 relations classified...
  Progress: 36832/36832 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships Keywords/cross_goalGLOBAL_SGD2023_gemma3-27b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_flanT5
22747,"Unsustainable water management practices, incl...",Align private business investment flows with t...,6_2,8_1,NaN,No Relationship
31853,"Yet the SDG Dashboards rate rich countries, in...",Challenges such as decarbonization cannot be m...,12_5,13_14,NaN,No Relationship
20721,The HICs’ somewhat better performance on pilla...,The capacity and healthy functioning of ecosys...,4_15,14_6,NaN,Support
18630,"In HICs and LICs, the pandemic and other crise...","All countries, poorer and richer alike, should...",3_5,17_3,NaN,Support
15364,"Nonetheless, it is recognized as the birthplac...","Education builds human capital, which in turn ...",2_3,8_13,NaN,Support

rel_flanT5
Support            22406
No Relationship    13441
Attack               985
Name: count, dtype: int64

#### Gemma3 4B extraction

In [8]:
prefix = "intra_goalGLOBAL_SGD2023_gemma3-4b"   
rel_col = f"rel_{model_name}"
BATCH_SIZE = 250
GEN_MAX_NEW_TOKENS = 3                
TEMPERATURE = 0.0
VALID_OUT = {"Support", "Attack", "Rephrase", "No Relationship"}


args_classified = classify_relationships_flan(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_flanT5"].value_counts()

Using MAX_LENGTH = 297

Processing: /kaggle/working/TFM/Data/Relationships Keywords/intra_goalGLOBAL_SGD2023_gemma3-4b.csv
Sample predictions (first 5):

- Arg1: the sdgs are seriously off track
-Arg2: the sdgs are still achievable
Label: No Relationship


- Arg1: the sdgs are seriously off track
-Arg2: it is critical that un member states adopt and implement the sdg stimulus
Label: Support


- Arg1: the sdgs are seriously off track
-Arg2: to achieve the sdgs the world must both alter its current investment patterns and increase the overall volume of investments
Label: No Relationship


- Arg1: the sdgs are seriously off track
-Arg2: revise the credit rating system and debt sustainability metrics to facilitate long-term sustainable development
Label: No Relationship


- Arg1: the sdgs are seriously off track
-Arg2: align private business investment flows with the sdgs, through improved national planning, regulation, reporting, and oversight
Label: No Relationship


  Progress: 250/6976 relations classified...
  Progress: 500/6976 relations classified...
  Progress: 750/6976 relations classified...
  Progress: 1000/6976 relations classified...
  Progress: 1250/6976 relations classified...
  Progress: 1500/6976 relations classified...
  Progress: 1750/6976 relations classified...
  Progress: 2000/6976 relations classified...
  Progress: 2250/6976 relations classified...
  Progress: 2500/6976 relations classified...
  Progress: 2750/6976 relations classified...
  Progress: 3000/6976 relations classified...
  Progress: 3250/6976 relations classified...
  Progress: 3500/6976 relations classified...
  Progress: 3750/6976 relations classified...
  Progress: 4000/6976 relations classified...
  Progress: 4250/6976 relations classified...
  Progress: 4500/6976 relations classified...
  Progress: 4750/6976 relations classified...
  Progress: 5000/6976 relations classified...
  Progress: 5250/6976 relations classified...
  Progress: 5500/6976 relations classified...
  Progress: 5750/6976 relations classified...
  Progress: 6000/6976 relations classified...
  Progress: 6250/6976 relations classified...
  Progress: 6500/6976 relations classified...
  Progress: 6750/6976 relations classified...
  Progress: 6976/6976 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships Keywords/intra_goalGLOBAL_SGD2023_gemma3-4b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_flanT5
2709,SDSN is also supporting new partnerships betwe...,"UN Member States, at the 2023 SDG Summit and t...",0_43,0_44,NaN,Support
4677,The COVID-19 pandemic also severely depleted t...,universal health coverage (UHC) is considered ...,3_3,3_10,NaN,No Relationship
671,"UN Member States should adopt an SDG Stimulus,...",For governments to combine the objectives of e...,0_8,0_36,NaN,Support
4602,"Sustainable ecosystems, sustainable agricultur...",Food systems are also highly vulnerable to cli...,2_21,2_25,NaN,Support
1134,UN Member States should commit to accelerating...,The SDGs are not only a public policy framewor...,0_14,0_64,NaN,Support

rel_flanT5
Support            4439
No Relationship    2489
Attack               48
Name: count, dtype: int64

In [9]:
prefix = "cross_goalGLOBAL_SGD2023_gemma3-4b"   
rel_col = f"rel_{model_name}"
BATCH_SIZE = 250
GEN_MAX_NEW_TOKENS = 3                
TEMPERATURE = 0.0
VALID_OUT = {"Support", "Attack", "Rephrase", "No Relationship"}


args_classified = classify_relationships_flan(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_flanT5"].value_counts()

Using MAX_LENGTH = 317

Processing: /kaggle/working/TFM/Data/Relationships Keywords/cross_goalGLOBAL_SGD2023_gemma3-4b.csv
Sample predictions (first 5):

- Arg1: the sdgs are seriously off track
-Arg2: to achieve the sdgs the world must both alter its current investment patterns and increase the overall volume of investments.
Label: No Relationship


- Arg1: the sdgs are seriously off track
-Arg2: greatly increase funding to national and subnational governments and private businesses, especially in lics and lmics, to carry out needed sdg investments.
Label: Support


- Arg1: the sdgs are seriously off track
-Arg2: revise liquidity structures for lics and lmics, especially regarding sovereign debts, to forestall self-fulfilling banking and balance-of-payments crises;
Label: No Relationship


- Arg1: the sdgs are seriously off track
-Arg2: investing in statistical capacity, science, and data literacy are important priorities for achieving the sdgs
Label: No Relationship


- Arg1: the sdgs are seriously off track
-Arg2: increased funding from the multilateral development banks (mdbs) and public development banks (pdbs) to low- and middle-income countries, linked to investments in the sdgs
Label: No Relationship


  Progress: 250/71234 relations classified...
  Progress: 500/71234 relations classified...
  Progress: 750/71234 relations classified...
  Progress: 1000/71234 relations classified...
  Progress: 1250/71234 relations classified...
  Progress: 1500/71234 relations classified...
  Progress: 1750/71234 relations classified...
  Progress: 2000/71234 relations classified...
  Progress: 2250/71234 relations classified...
  Progress: 2500/71234 relations classified...
  Progress: 2750/71234 relations classified...
  Progress: 3000/71234 relations classified...
  Progress: 3250/71234 relations classified...
  Progress: 3500/71234 relations classified...
  Progress: 3750/71234 relations classified...
  Progress: 4000/71234 relations classified...
  Progress: 4250/71234 relations classified...
  Progress: 4500/71234 relations classified...
  Progress: 4750/71234 relations classified...
  Progress: 5000/71234 relations classified...
  Progress: 5250/71234 relations classified...
  Progress: 5500/71234 relations classified...
  Progress: 5750/71234 relations classified...
  Progress: 6000/71234 relations classified...
  Progress: 6250/71234 relations classified...
  Progress: 6500/71234 relations classified...
  Progress: 6750/71234 relations classified...
  Progress: 7000/71234 relations classified...
  Progress: 7250/71234 relations classified...
  Progress: 7500/71234 relations classified...
  Progress: 7750/71234 relations classified...
  Progress: 8000/71234 relations classified...
  Progress: 8250/71234 relations classified...
  Progress: 8500/71234 relations classified...
  Progress: 8750/71234 relations classified...
  Progress: 9000/71234 relations classified...
  Progress: 9250/71234 relations classified...
  Progress: 9500/71234 relations classified...
  Progress: 9750/71234 relations classified...
  Progress: 10000/71234 relations classified...
  Progress: 10250/71234 relations classified...
  Progress: 10500/71234 relations classified...
  Progress: 10750/71234 relations classified...
  Progress: 11000/71234 relations classified...
  Progress: 11250/71234 relations classified...
  Progress: 11500/71234 relations classified...
  Progress: 11750/71234 relations classified...
  Progress: 12000/71234 relations classified...
  Progress: 12250/71234 relations classified...
  Progress: 12500/71234 relations classified...
  Progress: 12750/71234 relations classified...
  Progress: 13000/71234 relations classified...
  Progress: 13250/71234 relations classified...
  Progress: 13500/71234 relations classified...
  Progress: 13750/71234 relations classified...
  Progress: 14000/71234 relations classified...
  Progress: 14250/71234 relations classified...
  Progress: 14500/71234 relations classified...
  Progress: 14750/71234 relations classified...
  Progress: 15000/71234 relations classified...
  Progress: 15250/71234 relations classified...
  Progress: 15500/71234 relations classified...
  Progress: 15750/71234 relations classified...
  Progress: 16000/71234 relations classified...
  Progress: 16250/71234 relations classified...
  Progress: 16500/71234 relations classified...
  Progress: 16750/71234 relations classified...
  Progress: 17000/71234 relations classified...
  Progress: 17250/71234 relations classified...
  Progress: 17500/71234 relations classified...
  Progress: 17750/71234 relations classified...
  Progress: 18000/71234 relations classified...
  Progress: 18250/71234 relations classified...
  Progress: 18500/71234 relations classified...
  Progress: 18750/71234 relations classified...
  Progress: 19000/71234 relations classified...
  Progress: 19250/71234 relations classified...
  Progress: 19500/71234 relations classified...
  Progress: 19750/71234 relations classified...
  Progress: 20000/71234 relations classified...
  Progress: 20250/71234 relations classified...
  Progress: 20500/71234 relations classified...
  Progress: 20750/71234 relations classified...
  Progress: 21000/71234 relations classified...
  Progress: 21250/71234 relations classified...
  Progress: 21500/71234 relations classified...
  Progress: 21750/71234 relations classified...
  Progress: 22000/71234 relations classified...
  Progress: 22250/71234 relations classified...
  Progress: 22500/71234 relations classified...
  Progress: 22750/71234 relations classified...
  Progress: 23000/71234 relations classified...
  Progress: 23250/71234 relations classified...
  Progress: 23500/71234 relations classified...
  Progress: 23750/71234 relations classified...
  Progress: 24000/71234 relations classified...
  Progress: 24250/71234 relations classified...
  Progress: 24500/71234 relations classified...
  Progress: 24750/71234 relations classified...
  Progress: 25000/71234 relations classified...
  Progress: 25250/71234 relations classified...
  Progress: 25500/71234 relations classified...
  Progress: 25750/71234 relations classified...
  Progress: 26000/71234 relations classified...
  Progress: 26250/71234 relations classified...
  Progress: 26500/71234 relations classified...
  Progress: 26750/71234 relations classified...
  Progress: 27000/71234 relations classified...
  Progress: 27250/71234 relations classified...
  Progress: 27500/71234 relations classified...
  Progress: 27750/71234 relations classified...
  Progress: 28000/71234 relations classified...
  Progress: 28250/71234 relations classified...
  Progress: 28500/71234 relations classified...
  Progress: 28750/71234 relations classified...
  Progress: 29000/71234 relations classified...
  Progress: 29250/71234 relations classified...
  Progress: 29500/71234 relations classified...
  Progress: 29750/71234 relations classified...
  Progress: 30000/71234 relations classified...
  Progress: 30250/71234 relations classified...
  Progress: 30500/71234 relations classified...
  Progress: 30750/71234 relations classified...
  Progress: 31000/71234 relations classified...
  Progress: 31250/71234 relations classified...
  Progress: 31500/71234 relations classified...
  Progress: 31750/71234 relations classified...
  Progress: 32000/71234 relations classified...
  Progress: 32250/71234 relations classified...
  Progress: 32500/71234 relations classified...
  Progress: 32750/71234 relations classified...
  Progress: 33000/71234 relations classified...
  Progress: 33250/71234 relations classified...
  Progress: 33500/71234 relations classified...
  Progress: 33750/71234 relations classified...
  Progress: 34000/71234 relations classified...
  Progress: 34250/71234 relations classified...
  Progress: 34500/71234 relations classified...
  Progress: 34750/71234 relations classified...
  Progress: 35000/71234 relations classified...
  Progress: 35250/71234 relations classified...
  Progress: 35500/71234 relations classified...
  Progress: 35750/71234 relations classified...
  Progress: 36000/71234 relations classified...
  Progress: 36250/71234 relations classified...
  Progress: 36500/71234 relations classified...
  Progress: 36750/71234 relations classified...
  Progress: 37000/71234 relations classified...
  Progress: 37250/71234 relations classified...
  Progress: 37500/71234 relations classified...
  Progress: 37750/71234 relations classified...
  Progress: 38000/71234 relations classified...
  Progress: 38250/71234 relations classified...
  Progress: 38500/71234 relations classified...
  Progress: 38750/71234 relations classified...
  Progress: 39000/71234 relations classified...
  Progress: 39250/71234 relations classified...
  Progress: 39500/71234 relations classified...
  Progress: 39750/71234 relations classified...
  Progress: 40000/71234 relations classified...
  Progress: 40250/71234 relations classified...
  Progress: 40500/71234 relations classified...
  Progress: 40750/71234 relations classified...
  Progress: 41000/71234 relations classified...
  Progress: 41250/71234 relations classified...
  Progress: 41500/71234 relations classified...
  Progress: 41750/71234 relations classified...
  Progress: 42000/71234 relations classified...
  Progress: 42250/71234 relations classified...
  Progress: 42500/71234 relations classified...
  Progress: 42750/71234 relations classified...
  Progress: 43000/71234 relations classified...
  Progress: 43250/71234 relations classified...
  Progress: 43500/71234 relations classified...
  Progress: 43750/71234 relations classified...
  Progress: 44000/71234 relations classified...
  Progress: 44250/71234 relations classified...
  Progress: 44500/71234 relations classified...
  Progress: 44750/71234 relations classified...
  Progress: 45000/71234 relations classified...
  Progress: 45250/71234 relations classified...
  Progress: 45500/71234 relations classified...
  Progress: 45750/71234 relations classified...
  Progress: 46000/71234 relations classified...
  Progress: 46250/71234 relations classified...
  Progress: 46500/71234 relations classified...
  Progress: 46750/71234 relations classified...
  Progress: 47000/71234 relations classified...
  Progress: 47250/71234 relations classified...
  Progress: 47500/71234 relations classified...
  Progress: 47750/71234 relations classified...
  Progress: 48000/71234 relations classified...
  Progress: 48250/71234 relations classified...
  Progress: 48500/71234 relations classified...
  Progress: 48750/71234 relations classified...
  Progress: 49000/71234 relations classified...
  Progress: 49250/71234 relations classified...
  Progress: 49500/71234 relations classified...
  Progress: 49750/71234 relations classified...
  Progress: 50000/71234 relations classified...
  Progress: 50250/71234 relations classified...
  Progress: 50500/71234 relations classified...
  Progress: 50750/71234 relations classified...
  Progress: 51000/71234 relations classified...
  Progress: 51250/71234 relations classified...
  Progress: 51500/71234 relations classified...
  Progress: 51750/71234 relations classified...
  Progress: 52000/71234 relations classified...
  Progress: 52250/71234 relations classified...
  Progress: 52500/71234 relations classified...
  Progress: 52750/71234 relations classified...
  Progress: 53000/71234 relations classified...
  Progress: 53250/71234 relations classified...
  Progress: 53500/71234 relations classified...
  Progress: 53750/71234 relations classified...
  Progress: 54000/71234 relations classified...
  Progress: 54250/71234 relations classified...
  Progress: 54500/71234 relations classified...
  Progress: 54750/71234 relations classified...
  Progress: 55000/71234 relations classified...
  Progress: 55250/71234 relations classified...
  Progress: 55500/71234 relations classified...
  Progress: 55750/71234 relations classified...
  Progress: 56000/71234 relations classified...
  Progress: 56250/71234 relations classified...
  Progress: 56500/71234 relations classified...
  Progress: 56750/71234 relations classified...
  Progress: 57000/71234 relations classified...
  Progress: 57250/71234 relations classified...
  Progress: 57500/71234 relations classified...
  Progress: 57750/71234 relations classified...
  Progress: 58000/71234 relations classified...
  Progress: 58250/71234 relations classified...
  Progress: 58500/71234 relations classified...
  Progress: 58750/71234 relations classified...
  Progress: 59000/71234 relations classified...
  Progress: 59250/71234 relations classified...
  Progress: 59500/71234 relations classified...
  Progress: 59750/71234 relations classified...
  Progress: 60000/71234 relations classified...
  Progress: 60250/71234 relations classified...
  Progress: 60500/71234 relations classified...
  Progress: 60750/71234 relations classified...
  Progress: 61000/71234 relations classified...
  Progress: 61250/71234 relations classified...
  Progress: 61500/71234 relations classified...
  Progress: 61750/71234 relations classified...
  Progress: 62000/71234 relations classified...
  Progress: 62250/71234 relations classified...
  Progress: 62500/71234 relations classified...
  Progress: 62750/71234 relations classified...
  Progress: 63000/71234 relations classified...
  Progress: 63250/71234 relations classified...
  Progress: 63500/71234 relations classified...
  Progress: 63750/71234 relations classified...
  Progress: 64000/71234 relations classified...
  Progress: 64250/71234 relations classified...
  Progress: 64500/71234 relations classified...
  Progress: 64750/71234 relations classified...
  Progress: 65000/71234 relations classified...
  Progress: 65250/71234 relations classified...
  Progress: 65500/71234 relations classified...
  Progress: 65750/71234 relations classified...
  Progress: 66000/71234 relations classified...
  Progress: 66250/71234 relations classified...
  Progress: 66500/71234 relations classified...
  Progress: 66750/71234 relations classified...
  Progress: 67000/71234 relations classified...
  Progress: 67250/71234 relations classified...
  Progress: 67500/71234 relations classified...
  Progress: 67750/71234 relations classified...
  Progress: 68000/71234 relations classified...
  Progress: 68250/71234 relations classified...
  Progress: 68500/71234 relations classified...
  Progress: 68750/71234 relations classified...
  Progress: 69000/71234 relations classified...
  Progress: 69250/71234 relations classified...
  Progress: 69500/71234 relations classified...
  Progress: 69750/71234 relations classified...
  Progress: 70000/71234 relations classified...
  Progress: 70250/71234 relations classified...
  Progress: 70500/71234 relations classified...
  Progress: 70750/71234 relations classified...
  Progress: 71000/71234 relations classified...
  Progress: 71234/71234 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships Keywords/cross_goalGLOBAL_SGD2023_gemma3-4b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_flanT5
33841,The SDGs incorporated from the start a strong ...,changes in natural land use configuration,1_30,15_2,NaN,No Relationship
29912,statistical capacity in the poorer and most vu...,Investments in research and development will a...,1_34,8_13,NaN,Support
37613,Today’s land-use practices and food systems ha...,"Expansion of private philanthropy, with focus ...",2_23,6_5,NaN,No Relationship
55978,globalized trade rules for ‘cleantech’ could a...,Achieving the SDGs requires more than ‘normal ...,8_6,13_12,NaN,No Relationship
71055,"To reduce inequalities, governments also need ...",The G20 should organize its financial cooperat...,16_29,17_13,NaN,Support

rel_flanT5
Support            39447
No Relationship    30309
Attack              1478
Name: count, dtype: int64

#### Llama3.3 70B extraction

In [10]:
prefix = "intra_goalGLOBAL_SGD2023_llama3.3-70b"   
rel_col = f"rel_{model_name}"
BATCH_SIZE = 250
GEN_MAX_NEW_TOKENS = 3                
TEMPERATURE = 0.0
VALID_OUT = {"Support", "Attack", "Rephrase", "No Relationship"}


args_classified = classify_relationships_flan(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_flanT5"].value_counts()

Using MAX_LENGTH = 293

Processing: /kaggle/working/TFM/Data/Relationships Keywords/intra_goalGLOBAL_SGD2023_llama3.3-70b.csv
Sample predictions (first 5):

- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: since the outbreak of the pandemic in 2020 and other simultaneous crises, sdg progress has stalled globally.
Label: Attack


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: the world is off track, but that is all the more reason to double down on the sdgs.
Label: Support


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: at their core, the sdgs are an investment agenda: it is critical that un member states adopt and implement the sdg stimulus and support a comprehensive reform of the global financial architecture.
Label: Support


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: to achieve the sdgs the world must both alter its current investment patterns and increase the overall volume of investments.
Label: Support


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: the stimulus’ urgent objective is to address the chronic shortfall of international sdg financing confronting the lics and lmics, and to ramp up financing flows by at least us$500 billion by 2025.
Label: Support


  Progress: 250/5951 relations classified...
  Progress: 500/5951 relations classified...
  Progress: 750/5951 relations classified...
  Progress: 1000/5951 relations classified...
  Progress: 1250/5951 relations classified...
  Progress: 1500/5951 relations classified...
  Progress: 1750/5951 relations classified...
  Progress: 2000/5951 relations classified...
  Progress: 2250/5951 relations classified...
  Progress: 2500/5951 relations classified...
  Progress: 2750/5951 relations classified...
  Progress: 3000/5951 relations classified...
  Progress: 3250/5951 relations classified...
  Progress: 3500/5951 relations classified...
  Progress: 3750/5951 relations classified...
  Progress: 4000/5951 relations classified...
  Progress: 4250/5951 relations classified...
  Progress: 4500/5951 relations classified...
  Progress: 4750/5951 relations classified...
  Progress: 5000/5951 relations classified...
  Progress: 5250/5951 relations classified...
  Progress: 5500/5951 relations classified...
  Progress: 5750/5951 relations classified...
  Progress: 5951/5951 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships Keywords/intra_goalGLOBAL_SGD2023_llama3.3-70b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_flanT5
5665,"Second, developed countries are not being held...",SDG 17 (Partnerships for the Goals) calls on a...,17_15,17_30,NaN,No Relationship
3720,While the high-income countries (HICs) and upp...,This is in sharp contrast to the pre-pandemic ...,10_10,10_14,NaN,No Relationship
3988,"Global spending on armaments, estimated at US$...","Yet the SDG Dashboards rate rich countries, in...",13_3,13_34,NaN,No Relationship
76,Since the outbreak of the pandemic in 2020 and...,To achieve the SDGs the world must both alter ...,0_1,0_4,NaN,Support
3013,1. Universal quality education and innovation-...,1. Universal quality education and innovation-...,4_3,4_7,NaN,Support

rel_flanT5
Support            4105
No Relationship    1674
Attack              172
Name: count, dtype: int64

In [11]:
prefix = "cross_goalGLOBAL_SGD2023_llama3.3-70b"   
rel_col = f"rel_{model_name}"
BATCH_SIZE = 250
GEN_MAX_NEW_TOKENS = 3                
TEMPERATURE = 0.0
VALID_OUT = {"Support", "Attack", "Rephrase", "No Relationship"}


args_classified = classify_relationships_flan(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_flanT5"].value_counts()

Using MAX_LENGTH = 359

Processing: /kaggle/working/TFM/Data/Relationships Keywords/cross_goalGLOBAL_SGD2023_llama3.3-70b.csv
Sample predictions (first 5):

- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: the grim reality is that at the midpoint of the 2030 agenda, the sdgs are far off track.
Label: Support


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: similarly, extreme poverty can lead to a collapse of tax revenues, followed by government bankruptcy and further economic collapse, a syndrome that now threatens dozens of poor countries.
Label: Attack


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: most of the low-income and lower-middle income countries, home to more than the half of humanity, face major challenges in achieving most of the sdgs by 2030.
Label: Attack


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: many of them lack an adequately high sdg commitment, and almost all lack access to the necessary financial means to implement the sdgs.
Label: Attack


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: deep, chronic, and crippling under-investment in virtually all low-income countries (lics) and lower-middle-income countries (lmics).
Label: Attack


  Progress: 250/58310 relations classified...
  Progress: 500/58310 relations classified...
  Progress: 750/58310 relations classified...
  Progress: 1000/58310 relations classified...
  Progress: 1250/58310 relations classified...
  Progress: 1500/58310 relations classified...
  Progress: 1750/58310 relations classified...
  Progress: 2000/58310 relations classified...
  Progress: 2250/58310 relations classified...
  Progress: 2500/58310 relations classified...
  Progress: 2750/58310 relations classified...
  Progress: 3000/58310 relations classified...
  Progress: 3250/58310 relations classified...
  Progress: 3500/58310 relations classified...
  Progress: 3750/58310 relations classified...
  Progress: 4000/58310 relations classified...
  Progress: 4250/58310 relations classified...
  Progress: 4500/58310 relations classified...
  Progress: 4750/58310 relations classified...
  Progress: 5000/58310 relations classified...
  Progress: 5250/58310 relations classified...
  Progress: 5500/58310 relations classified...
  Progress: 5750/58310 relations classified...
  Progress: 6000/58310 relations classified...
  Progress: 6250/58310 relations classified...
  Progress: 6500/58310 relations classified...
  Progress: 6750/58310 relations classified...
  Progress: 7000/58310 relations classified...
  Progress: 7250/58310 relations classified...
  Progress: 7500/58310 relations classified...
  Progress: 7750/58310 relations classified...
  Progress: 8000/58310 relations classified...
  Progress: 8250/58310 relations classified...
  Progress: 8500/58310 relations classified...
  Progress: 8750/58310 relations classified...
  Progress: 9000/58310 relations classified...
  Progress: 9250/58310 relations classified...
  Progress: 9500/58310 relations classified...
  Progress: 9750/58310 relations classified...
  Progress: 10000/58310 relations classified...
  Progress: 10250/58310 relations classified...
  Progress: 10500/58310 relations classified...
  Progress: 10750/58310 relations classified...
  Progress: 11000/58310 relations classified...
  Progress: 11250/58310 relations classified...
  Progress: 11500/58310 relations classified...
  Progress: 11750/58310 relations classified...
  Progress: 12000/58310 relations classified...
  Progress: 12250/58310 relations classified...
  Progress: 12500/58310 relations classified...
  Progress: 12750/58310 relations classified...
  Progress: 13000/58310 relations classified...
  Progress: 13250/58310 relations classified...
  Progress: 13500/58310 relations classified...
  Progress: 13750/58310 relations classified...
  Progress: 14000/58310 relations classified...
  Progress: 14250/58310 relations classified...
  Progress: 14500/58310 relations classified...
  Progress: 14750/58310 relations classified...
  Progress: 15000/58310 relations classified...
  Progress: 15250/58310 relations classified...
  Progress: 15500/58310 relations classified...
  Progress: 15750/58310 relations classified...
  Progress: 16000/58310 relations classified...
  Progress: 16250/58310 relations classified...
  Progress: 16500/58310 relations classified...
  Progress: 16750/58310 relations classified...
  Progress: 17000/58310 relations classified...
  Progress: 17250/58310 relations classified...
  Progress: 17500/58310 relations classified...
  Progress: 17750/58310 relations classified...
  Progress: 18000/58310 relations classified...
  Progress: 18250/58310 relations classified...
  Progress: 18500/58310 relations classified...
  Progress: 18750/58310 relations classified...
  Progress: 19000/58310 relations classified...
  Progress: 19250/58310 relations classified...
  Progress: 19500/58310 relations classified...
  Progress: 19750/58310 relations classified...
  Progress: 20000/58310 relations classified...
  Progress: 20250/58310 relations classified...
  Progress: 20500/58310 relations classified...
  Progress: 20750/58310 relations classified...
  Progress: 21000/58310 relations classified...
  Progress: 21250/58310 relations classified...
  Progress: 21500/58310 relations classified...
  Progress: 21750/58310 relations classified...
  Progress: 22000/58310 relations classified...
  Progress: 22250/58310 relations classified...
  Progress: 22500/58310 relations classified...
  Progress: 22750/58310 relations classified...
  Progress: 23000/58310 relations classified...
  Progress: 23250/58310 relations classified...
  Progress: 23500/58310 relations classified...
  Progress: 23750/58310 relations classified...
  Progress: 24000/58310 relations classified...
  Progress: 24250/58310 relations classified...
  Progress: 24500/58310 relations classified...
  Progress: 24750/58310 relations classified...
  Progress: 25000/58310 relations classified...
  Progress: 25250/58310 relations classified...
  Progress: 25500/58310 relations classified...
  Progress: 25750/58310 relations classified...
  Progress: 26000/58310 relations classified...
  Progress: 26250/58310 relations classified...
  Progress: 26500/58310 relations classified...
  Progress: 26750/58310 relations classified...
  Progress: 27000/58310 relations classified...
  Progress: 27250/58310 relations classified...
  Progress: 27500/58310 relations classified...
  Progress: 27750/58310 relations classified...
  Progress: 28000/58310 relations classified...
  Progress: 28250/58310 relations classified...
  Progress: 28500/58310 relations classified...
  Progress: 28750/58310 relations classified...
  Progress: 29000/58310 relations classified...
  Progress: 29250/58310 relations classified...
  Progress: 29500/58310 relations classified...
  Progress: 29750/58310 relations classified...
  Progress: 30000/58310 relations classified...
  Progress: 30250/58310 relations classified...
  Progress: 30500/58310 relations classified...
  Progress: 30750/58310 relations classified...
  Progress: 31000/58310 relations classified...
  Progress: 31250/58310 relations classified...
  Progress: 31500/58310 relations classified...
  Progress: 31750/58310 relations classified...
  Progress: 32000/58310 relations classified...
  Progress: 32250/58310 relations classified...
  Progress: 32500/58310 relations classified...
  Progress: 32750/58310 relations classified...
  Progress: 33000/58310 relations classified...
  Progress: 33250/58310 relations classified...
  Progress: 33500/58310 relations classified...
  Progress: 33750/58310 relations classified...
  Progress: 34000/58310 relations classified...
  Progress: 34250/58310 relations classified...
  Progress: 34500/58310 relations classified...
  Progress: 34750/58310 relations classified...
  Progress: 35000/58310 relations classified...
  Progress: 35250/58310 relations classified...
  Progress: 35500/58310 relations classified...
  Progress: 35750/58310 relations classified...
  Progress: 36000/58310 relations classified...
  Progress: 36250/58310 relations classified...
  Progress: 36500/58310 relations classified...
  Progress: 36750/58310 relations classified...
  Progress: 37000/58310 relations classified...
  Progress: 37250/58310 relations classified...
  Progress: 37500/58310 relations classified...
  Progress: 37750/58310 relations classified...
  Progress: 38000/58310 relations classified...
  Progress: 38250/58310 relations classified...
  Progress: 38500/58310 relations classified...
  Progress: 38750/58310 relations classified...
  Progress: 39000/58310 relations classified...
  Progress: 39250/58310 relations classified...
  Progress: 39500/58310 relations classified...
  Progress: 39750/58310 relations classified...
  Progress: 40000/58310 relations classified...
  Progress: 40250/58310 relations classified...
  Progress: 40500/58310 relations classified...
  Progress: 40750/58310 relations classified...
  Progress: 41000/58310 relations classified...
  Progress: 41250/58310 relations classified...
  Progress: 41500/58310 relations classified...
  Progress: 41750/58310 relations classified...
  Progress: 42000/58310 relations classified...
  Progress: 42250/58310 relations classified...
  Progress: 42500/58310 relations classified...
  Progress: 42750/58310 relations classified...
  Progress: 43000/58310 relations classified...
  Progress: 43250/58310 relations classified...
  Progress: 43500/58310 relations classified...
  Progress: 43750/58310 relations classified...
  Progress: 44000/58310 relations classified...
  Progress: 44250/58310 relations classified...
  Progress: 44500/58310 relations classified...
  Progress: 44750/58310 relations classified...
  Progress: 45000/58310 relations classified...
  Progress: 45250/58310 relations classified...
  Progress: 45500/58310 relations classified...
  Progress: 45750/58310 relations classified...
  Progress: 46000/58310 relations classified...
  Progress: 46250/58310 relations classified...
  Progress: 46500/58310 relations classified...
  Progress: 46750/58310 relations classified...
  Progress: 47000/58310 relations classified...
  Progress: 47250/58310 relations classified...
  Progress: 47500/58310 relations classified...
  Progress: 47750/58310 relations classified...
  Progress: 48000/58310 relations classified...
  Progress: 48250/58310 relations classified...
  Progress: 48500/58310 relations classified...
  Progress: 48750/58310 relations classified...
  Progress: 49000/58310 relations classified...
  Progress: 49250/58310 relations classified...
  Progress: 49500/58310 relations classified...
  Progress: 49750/58310 relations classified...
  Progress: 50000/58310 relations classified...
  Progress: 50250/58310 relations classified...
  Progress: 50500/58310 relations classified...
  Progress: 50750/58310 relations classified...
  Progress: 51000/58310 relations classified...
  Progress: 51250/58310 relations classified...
  Progress: 51500/58310 relations classified...
  Progress: 51750/58310 relations classified...
  Progress: 52000/58310 relations classified...
  Progress: 52250/58310 relations classified...
  Progress: 52500/58310 relations classified...
  Progress: 52750/58310 relations classified...
  Progress: 53000/58310 relations classified...
  Progress: 53250/58310 relations classified...
  Progress: 53500/58310 relations classified...
  Progress: 53750/58310 relations classified...
  Progress: 54000/58310 relations classified...
  Progress: 54250/58310 relations classified...
  Progress: 54500/58310 relations classified...
  Progress: 54750/58310 relations classified...
  Progress: 55000/58310 relations classified...
  Progress: 55250/58310 relations classified...
  Progress: 55500/58310 relations classified...
  Progress: 55750/58310 relations classified...
  Progress: 56000/58310 relations classified...
  Progress: 56250/58310 relations classified...
  Progress: 56500/58310 relations classified...
  Progress: 56750/58310 relations classified...
  Progress: 57000/58310 relations classified...
  Progress: 57250/58310 relations classified...
  Progress: 57500/58310 relations classified...
  Progress: 57750/58310 relations classified...
  Progress: 58000/58310 relations classified...
  Progress: 58250/58310 relations classified...
  Progress: 58310/58310 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships Keywords/cross_goalGLOBAL_SGD2023_llama3.3-70b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_flanT5
22550,"According to IMF estimates in 2019, the financ...",Although all governments are in principle comm...,1_7,10_3,NaN,No Relationship
29074,Multiple and overlapping health and geopolitic...,The COVID-19 pandemic also severely depleted t...,3_6,16_5,NaN,No Relationship
21023,The SDGs are not only a public policy framewor...,"In 2022, the United Nations Secretary-General ...",0_68,17_3,NaN,Support
8736,UN Member States should commit to accelerating...,to ensure equitable access to and resources fo...,0_19,10_12,NaN,Support
18914,UN Member States must endorse a deep and overd...,"First, implementation is largely left to the n...",0_15,17_14,NaN,No Relationship

rel_flanT5
Support            33288
No Relationship    22996
Attack              2026
Name: count, dtype: int64

#### Deepseek r1 70B extraction

In [12]:
prefix = "intra_goalGLOBAL_SGD2023_deepseek-r1-70b"   
rel_col = f"rel_{model_name}"
BATCH_SIZE = 250
GEN_MAX_NEW_TOKENS = 3                
TEMPERATURE = 0.0
VALID_OUT = {"Support", "Attack", "Rephrase", "No Relationship"}


args_classified = classify_relationships_flan(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_flanT5"].value_counts()

Using MAX_LENGTH = 280

Processing: /kaggle/working/TFM/Data/Relationships Keywords/intra_goalGLOBAL_SGD2023_deepseek-r1-70b.csv
Sample predictions (first 5):

- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: despite this alarming development, the sdgs are still achievable.
Label: No Relationship


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: the world is off track, but that is all the more reason to double down on the sdgs.
Label: Support


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: to achieve the sdgs the world must both alter its current investment patterns and increase the overall volume of investments.
Label: Support


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: all countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national sdg strategies and commit to strengthening multilateralism.
Label: Support


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: further investment is needed in statistical capacity and data literacy to support long-term pathways for key sdg transformations.
Label: Support


  Progress: 250/6537 relations classified...
  Progress: 500/6537 relations classified...
  Progress: 750/6537 relations classified...
  Progress: 1000/6537 relations classified...
  Progress: 1250/6537 relations classified...
  Progress: 1500/6537 relations classified...
  Progress: 1750/6537 relations classified...
  Progress: 2000/6537 relations classified...
  Progress: 2250/6537 relations classified...
  Progress: 2500/6537 relations classified...
  Progress: 2750/6537 relations classified...
  Progress: 3000/6537 relations classified...
  Progress: 3250/6537 relations classified...
  Progress: 3500/6537 relations classified...
  Progress: 3750/6537 relations classified...
  Progress: 4000/6537 relations classified...
  Progress: 4250/6537 relations classified...
  Progress: 4500/6537 relations classified...
  Progress: 4750/6537 relations classified...
  Progress: 5000/6537 relations classified...
  Progress: 5250/6537 relations classified...
  Progress: 5500/6537 relations classified...
  Progress: 5750/6537 relations classified...
  Progress: 6000/6537 relations classified...
  Progress: 6250/6537 relations classified...
  Progress: 6500/6537 relations classified...
  Progress: 6537/6537 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships Keywords/intra_goalGLOBAL_SGD2023_deepseek-r1-70b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_flanT5
6259,"United Nations agencies, multilateral organiza...",Multilateralism and investments in global capa...,17_19,17_42,NaN,Support
4765,3. Zero-carbon energy systems: the transition ...,UNEP estimates that 84 percent of Parties to t...,13_0,13_22,NaN,Support
6471,Both sides – importers and exporters – must wo...,The SDGs require long-term directed change and...,17_32,17_33,NaN,Support
3769,"The interconnected environmental, social, and ...",Extreme poverty rates in LICs remain above pre...,3_1,3_6,NaN,No Relationship
5466,Failures of global governance Achieving the SD...,Nation-states continue to hold the primary res...,16_10,16_22,NaN,No Relationship

rel_flanT5
Support            4454
No Relationship    1864
Attack              219
Name: count, dtype: int64

In [13]:
prefix = "cross_goalGLOBAL_SGD2023_deepseek-r1-70b"   
rel_col = f"rel_{model_name}"
BATCH_SIZE = 250
GEN_MAX_NEW_TOKENS = 3                
TEMPERATURE = 0.0
VALID_OUT = {"Support", "Attack", "Rephrase", "No Relationship"}


args_classified = classify_relationships_flan(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_flanT5"].value_counts()

Using MAX_LENGTH = 318

Processing: /kaggle/working/TFM/Data/Relationships Keywords/cross_goalGLOBAL_SGD2023_deepseek-r1-70b.csv
Sample predictions (first 5):

- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: the grim reality is that at the midpoint of the 2030 agenda, the sdgs are far off track.
Label: Support


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: at the global level, averaging across countries, not a single sdg is currently projected to be met by 2030, with the poorest countries struggling the most.
Label: Support


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: 1. increased funding from the multilateral develop-ment banks (mdbs) and public development banks (pdbs) to low- and middle-income countries, linked to investments in the sdgs;
Label: No Relationship


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: 2. enhancement of relief for countries facing debt distress;
Label: No Relationship


- Arg1: at the midpoint of the 2030 agenda, all of the sdgs are seriously off track.
-Arg2: 1. greatly increased funding for national and subnational governments and private businesses in the emerging economies, especially the low-income countries (lics) and lower-middle-income countries (lmics), to carry out needed sdg actions;
Label: No Relationship


  Progress: 250/60991 relations classified...
  Progress: 500/60991 relations classified...
  Progress: 750/60991 relations classified...
  Progress: 1000/60991 relations classified...
  Progress: 1250/60991 relations classified...
  Progress: 1500/60991 relations classified...
  Progress: 1750/60991 relations classified...
  Progress: 2000/60991 relations classified...
  Progress: 2250/60991 relations classified...
  Progress: 2500/60991 relations classified...
  Progress: 2750/60991 relations classified...
  Progress: 3000/60991 relations classified...
  Progress: 3250/60991 relations classified...
  Progress: 3500/60991 relations classified...
  Progress: 3750/60991 relations classified...
  Progress: 4000/60991 relations classified...
  Progress: 4250/60991 relations classified...
  Progress: 4500/60991 relations classified...
  Progress: 4750/60991 relations classified...
  Progress: 5000/60991 relations classified...
  Progress: 5250/60991 relations classified...
  Progress: 5500/60991 relations classified...
  Progress: 5750/60991 relations classified...
  Progress: 6000/60991 relations classified...
  Progress: 6250/60991 relations classified...
  Progress: 6500/60991 relations classified...
  Progress: 6750/60991 relations classified...
  Progress: 7000/60991 relations classified...
  Progress: 7250/60991 relations classified...
  Progress: 7500/60991 relations classified...
  Progress: 7750/60991 relations classified...
  Progress: 8000/60991 relations classified...
  Progress: 8250/60991 relations classified...
  Progress: 8500/60991 relations classified...
  Progress: 8750/60991 relations classified...
  Progress: 9000/60991 relations classified...
  Progress: 9250/60991 relations classified...
  Progress: 9500/60991 relations classified...
  Progress: 9750/60991 relations classified...
  Progress: 10000/60991 relations classified...
  Progress: 10250/60991 relations classified...
  Progress: 10500/60991 relations classified...
  Progress: 10750/60991 relations classified...
  Progress: 11000/60991 relations classified...
  Progress: 11250/60991 relations classified...
  Progress: 11500/60991 relations classified...
  Progress: 11750/60991 relations classified...
  Progress: 12000/60991 relations classified...
  Progress: 12250/60991 relations classified...
  Progress: 12500/60991 relations classified...
  Progress: 12750/60991 relations classified...
  Progress: 13000/60991 relations classified...
  Progress: 13250/60991 relations classified...
  Progress: 13500/60991 relations classified...
  Progress: 13750/60991 relations classified...
  Progress: 14000/60991 relations classified...
  Progress: 14250/60991 relations classified...
  Progress: 14500/60991 relations classified...
  Progress: 14750/60991 relations classified...
  Progress: 15000/60991 relations classified...
  Progress: 15250/60991 relations classified...
  Progress: 15500/60991 relations classified...
  Progress: 15750/60991 relations classified...
  Progress: 16000/60991 relations classified...
  Progress: 16250/60991 relations classified...
  Progress: 16500/60991 relations classified...
  Progress: 16750/60991 relations classified...
  Progress: 17000/60991 relations classified...
  Progress: 17250/60991 relations classified...
  Progress: 17500/60991 relations classified...
  Progress: 17750/60991 relations classified...
  Progress: 18000/60991 relations classified...
  Progress: 18250/60991 relations classified...
  Progress: 18500/60991 relations classified...
  Progress: 18750/60991 relations classified...
  Progress: 19000/60991 relations classified...
  Progress: 19250/60991 relations classified...
  Progress: 19500/60991 relations classified...
  Progress: 19750/60991 relations classified...
  Progress: 20000/60991 relations classified...
  Progress: 20250/60991 relations classified...
  Progress: 20500/60991 relations classified...
  Progress: 20750/60991 relations classified...
  Progress: 21000/60991 relations classified...
  Progress: 21250/60991 relations classified...
  Progress: 21500/60991 relations classified...
  Progress: 21750/60991 relations classified...
  Progress: 22000/60991 relations classified...
  Progress: 22250/60991 relations classified...
  Progress: 22500/60991 relations classified...
  Progress: 22750/60991 relations classified...
  Progress: 23000/60991 relations classified...
  Progress: 23250/60991 relations classified...
  Progress: 23500/60991 relations classified...
  Progress: 23750/60991 relations classified...
  Progress: 24000/60991 relations classified...
  Progress: 24250/60991 relations classified...
  Progress: 24500/60991 relations classified...
  Progress: 24750/60991 relations classified...
  Progress: 25000/60991 relations classified...
  Progress: 25250/60991 relations classified...
  Progress: 25500/60991 relations classified...
  Progress: 25750/60991 relations classified...
  Progress: 26000/60991 relations classified...
  Progress: 26250/60991 relations classified...
  Progress: 26500/60991 relations classified...
  Progress: 26750/60991 relations classified...
  Progress: 27000/60991 relations classified...
  Progress: 27250/60991 relations classified...
  Progress: 27500/60991 relations classified...
  Progress: 27750/60991 relations classified...
  Progress: 28000/60991 relations classified...
  Progress: 28250/60991 relations classified...
  Progress: 28500/60991 relations classified...
  Progress: 28750/60991 relations classified...
  Progress: 29000/60991 relations classified...
  Progress: 29250/60991 relations classified...
  Progress: 29500/60991 relations classified...
  Progress: 29750/60991 relations classified...
  Progress: 30000/60991 relations classified...
  Progress: 30250/60991 relations classified...
  Progress: 30500/60991 relations classified...
  Progress: 30750/60991 relations classified...
  Progress: 31000/60991 relations classified...
  Progress: 31250/60991 relations classified...
  Progress: 31500/60991 relations classified...
  Progress: 31750/60991 relations classified...
  Progress: 32000/60991 relations classified...
  Progress: 32250/60991 relations classified...
  Progress: 32500/60991 relations classified...
  Progress: 32750/60991 relations classified...
  Progress: 33000/60991 relations classified...
  Progress: 33250/60991 relations classified...
  Progress: 33500/60991 relations classified...
  Progress: 33750/60991 relations classified...
  Progress: 34000/60991 relations classified...
  Progress: 34250/60991 relations classified...
  Progress: 34500/60991 relations classified...
  Progress: 34750/60991 relations classified...
  Progress: 35000/60991 relations classified...
  Progress: 35250/60991 relations classified...
  Progress: 35500/60991 relations classified...
  Progress: 35750/60991 relations classified...
  Progress: 36000/60991 relations classified...
  Progress: 36250/60991 relations classified...
  Progress: 36500/60991 relations classified...
  Progress: 36750/60991 relations classified...
  Progress: 37000/60991 relations classified...
  Progress: 37250/60991 relations classified...
  Progress: 37500/60991 relations classified...
  Progress: 37750/60991 relations classified...
  Progress: 38000/60991 relations classified...
  Progress: 38250/60991 relations classified...
  Progress: 38500/60991 relations classified...
  Progress: 38750/60991 relations classified...
  Progress: 39000/60991 relations classified...
  Progress: 39250/60991 relations classified...
  Progress: 39500/60991 relations classified...
  Progress: 39750/60991 relations classified...
  Progress: 40000/60991 relations classified...
  Progress: 40250/60991 relations classified...
  Progress: 40500/60991 relations classified...
  Progress: 40750/60991 relations classified...
  Progress: 41000/60991 relations classified...
  Progress: 41250/60991 relations classified...
  Progress: 41500/60991 relations classified...
  Progress: 41750/60991 relations classified...
  Progress: 42000/60991 relations classified...
  Progress: 42250/60991 relations classified...
  Progress: 42500/60991 relations classified...
  Progress: 42750/60991 relations classified...
  Progress: 43000/60991 relations classified...
  Progress: 43250/60991 relations classified...
  Progress: 43500/60991 relations classified...
  Progress: 43750/60991 relations classified...
  Progress: 44000/60991 relations classified...
  Progress: 44250/60991 relations classified...
  Progress: 44500/60991 relations classified...
  Progress: 44750/60991 relations classified...
  Progress: 45000/60991 relations classified...
  Progress: 45250/60991 relations classified...
  Progress: 45500/60991 relations classified...
  Progress: 45750/60991 relations classified...
  Progress: 46000/60991 relations classified...
  Progress: 46250/60991 relations classified...
  Progress: 46500/60991 relations classified...
  Progress: 46750/60991 relations classified...
  Progress: 47000/60991 relations classified...
  Progress: 47250/60991 relations classified...
  Progress: 47500/60991 relations classified...
  Progress: 47750/60991 relations classified...
  Progress: 48000/60991 relations classified...
  Progress: 48250/60991 relations classified...
  Progress: 48500/60991 relations classified...
  Progress: 48750/60991 relations classified...
  Progress: 49000/60991 relations classified...
  Progress: 49250/60991 relations classified...
  Progress: 49500/60991 relations classified...
  Progress: 49750/60991 relations classified...
  Progress: 50000/60991 relations classified...
  Progress: 50250/60991 relations classified...
  Progress: 50500/60991 relations classified...
  Progress: 50750/60991 relations classified...
  Progress: 51000/60991 relations classified...
  Progress: 51250/60991 relations classified...
  Progress: 51500/60991 relations classified...
  Progress: 51750/60991 relations classified...
  Progress: 52000/60991 relations classified...
  Progress: 52250/60991 relations classified...
  Progress: 52500/60991 relations classified...
  Progress: 52750/60991 relations classified...
  Progress: 53000/60991 relations classified...
  Progress: 53250/60991 relations classified...
  Progress: 53500/60991 relations classified...
  Progress: 53750/60991 relations classified...
  Progress: 54000/60991 relations classified...
  Progress: 54250/60991 relations classified...
  Progress: 54500/60991 relations classified...
  Progress: 54750/60991 relations classified...
  Progress: 55000/60991 relations classified...
  Progress: 55250/60991 relations classified...
  Progress: 55500/60991 relations classified...
  Progress: 55750/60991 relations classified...
  Progress: 56000/60991 relations classified...
  Progress: 56250/60991 relations classified...
  Progress: 56500/60991 relations classified...
  Progress: 56750/60991 relations classified...
  Progress: 57000/60991 relations classified...
  Progress: 57250/60991 relations classified...
  Progress: 57500/60991 relations classified...
  Progress: 57750/60991 relations classified...
  Progress: 58000/60991 relations classified...
  Progress: 58250/60991 relations classified...
  Progress: 58500/60991 relations classified...
  Progress: 58750/60991 relations classified...
  Progress: 59000/60991 relations classified...
  Progress: 59250/60991 relations classified...
  Progress: 59500/60991 relations classified...
  Progress: 59750/60991 relations classified...
  Progress: 60000/60991 relations classified...
  Progress: 60250/60991 relations classified...
  Progress: 60500/60991 relations classified...
  Progress: 60750/60991 relations classified...
  Progress: 60991/60991 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships Keywords/cross_goalGLOBAL_SGD2023_deepseek-r1-70b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_flanT5
46563,"According to the OECD, only one in 10 students...","To reduce inequalities, governments also need ...",9_15,10_20,NaN,Support
35851,The International Commission on the Futures of...,"For all of these reasons and more, neighboring...",4_8,9_9,NaN,Support
34832,Some countries specifically refer to the SDGs ...,Building on close cooperation with SDSN nation...,3_8,17_35,NaN,Support
51876,Disadvantaged communities have lower access to...,Achieving the SDGs requires more than 'normal ...,10_23,16_17,NaN,No Relationship
33341,"Those related to hunger, sustainable diets, an...","The European Green Deal (EGD), which is exempl...",3_5,12_1,NaN,Support

rel_flanT5
Support            34941
No Relationship    22855
Attack              3195
Name: count, dtype: int64