# TFM: Análisis de Políticas de Sostenibilidad mediante técnicas de Argumentacion Computacional

## Clasificación de relaciones con MoritzLaurer/DeBERTa-v3-base-mnli-fever-anli from microsoft/DeBERTa-v3-base

Model page: https://huggingface.co/MoritzLaurer/DeBERTa-v3-base-mnli-fever-anli

Entailment is calculated in both directions (forward probs (Arg1->Arg2) and backward probs (Arg2->Arg1)), then the label is decided with the following criteria:
   
Bidirectional decision:
  - Rephrase: high entailment both ways, low contradiction
  - Attack: contradiction high either way
  - Support: entailment high at least one way, and not clearly neutral/contradictory
  - No Relationship: otherwise

#Keywords

In [1]:
import os
import re
import math
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import gc

process_rel_path = r"/kaggle/working/TFM/Data/Relationships Keywords"

model_name = "MoritzLaurer/DeBERTa-v3-base-mnli-fever-anli"
device = "cuda" if torch.cuda.is_available() else "cpu"
BATCH_SIZE = 50                 
MODEL_TAG = "deberta"      
VALID_OUT = {"Support", "Attack", "Rephrase", "No Relationship"}

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name).to(device)
model.eval()

# figure out label 
id2label = {int(k): v.lower() for k, v in model.config.id2label.items()}
label2id = {v: int(k) for k, v in id2label.items()}

print(f'DeBERTa v3 base mnli labels {label2id}')

IDX_ENT = label2id["entailment"]
IDX_CON = label2id["contradiction"]
IDX_NEU = label2id["neutral"]

# Heuristic thresholds 
ENT_THR       = 0.50   
CONTR_THR     = 0.50   
REPHRASE_THR  = 0.75  
MAX_NEUTRAL   = 0.70   

# Margins: “X wins by at least this much”
SUPPORT_MARGIN = 0.10  # p_ent - p_con must exceed this (either direction)
ATTACK_MARGIN  = 0.10  # p_con - p_ent must exceed this (either direction)

tokenizer_config.json: 0.00B [00:00, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/23.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/286 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

2025-08-25 11:32:56.085797: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1756121576.262452      19 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1756121576.312794      19 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

model.safetensors:   0%|          | 0.00/369M [00:00<?, ?B/s]

DeBERTa v3 base mnli labels {'entailment': 0, 'neutral': 1, 'contradiction': 2}

In [2]:
!git clone https://github.com/camipalo/TFM.git

Cloning into 'TFM'...
remote: Enumerating objects: 2459, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 2459 (delta 9), reused 6 (delta 5), pack-reused 2444 (from 2)
Receiving objects: 100% (2459/2459), 97.50 MiB | 19.08 MiB/s, done.
Resolving deltas: 100% (2065/2065), done.
Updating files: 100% (1061/1061), done.

In [3]:
def preprocess_text(s):
    if not isinstance(s, str):
        return ""
    s = s.strip().lower()
    s = re.sub(r"\s+", " ", s)
    return s

@torch.no_grad()
def nli_probs(pairs, max_length: int):
    if not pairs:
        return np.zeros((0,3)), np.zeros((0,3))

    a1 = [preprocess_text(x[0]) for x in pairs]
    a2 = [preprocess_text(x[1]) for x in pairs]

    # forward: premise=a1, hypothesis=a2
    enc_f = tokenizer(a1, a2, return_tensors="pt", padding=True, truncation=True,
                      max_length=max_length).to(device)
    logits_f = model(**enc_f).logits
    prob_f = torch.softmax(logits_f, dim=-1).detach().cpu().numpy()

    # backward: premise=a2, hypothesis=a1
    enc_b = tokenizer(a2, a1, return_tensors="pt", padding=True, truncation=True,
                      max_length=max_length).to(device)
    logits_b = model(**enc_b).logits
    prob_b = torch.softmax(logits_b, dim=-1).detach().cpu().numpy()

    return prob_f, prob_b

def decide_label(p_ent_f, p_con_f, p_neu_f, p_ent_b, p_con_b, p_neu_b):
    # 1) Hard guard: if both sides look very neutral, say NR
    if max(p_neu_f, p_neu_b) >= MAX_NEUTRAL:
        return "No Relationship"

    # 2) Rephrase: bi-directional entailment and low contradiction
    if min(p_ent_f, p_ent_b) >= REPHRASE_THR and max(p_con_f, p_con_b) <= (1 - REPHRASE_THR):
        return "Rephrase"

    # 3) Attack: contradiction wins with margin OR strong contradiction
    if (
        (p_con_f - p_ent_f) >= ATTACK_MARGIN or
        (p_con_b - p_ent_b) >= ATTACK_MARGIN or
        p_con_f >= CONTR_THR or
        p_con_b >= CONTR_THR
    ):
        return "Attack"

    # 4) Support: entailment wins with margin OR clears lowered threshold
    if (
        (p_ent_f - p_con_f) >= SUPPORT_MARGIN or
        (p_ent_b - p_con_b) >= SUPPORT_MARGIN or
        p_ent_f >= ENT_THR or
        p_ent_b >= ENT_THR
    ):
        return "Support"

    # 5) Fallback
    return "No Relationship"


def free_cuda():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

def compute_max_length(input_dir, prefix_substring, safety_limit=512):
    max_len = 0
    files = [f for f in os.listdir(input_dir) if f.endswith(".csv") and prefix_substring in f]
    for fn in files:
        path = os.path.join(input_dir, fn)
        try:
            df = pd.read_csv(path)
        except Exception:
            continue
        if "SDGarg1" not in df.columns or "SDGarg2" not in df.columns:
            continue
        for a, b in zip(df["SDGarg1"], df["SDGarg2"]):
            a = preprocess_text(str(a) if pd.notna(a) else "")
            b = preprocess_text(str(b) if pd.notna(b) else "")
            ids = tokenizer(a, b, truncation=False, padding=False)["input_ids"]
            max_len = max(max_len, len(ids))
    if max_len == 0:
        max_len = 128
    return min(max_len, safety_limit)

def classify_relationships_deberta(input_dir, prefix_substring, model_tag=MODEL_TAG):
    files = [f for f in os.listdir(input_dir) if f.endswith(".csv") and prefix_substring in f]
    if not files:
        print(f"No CSVs found in '{input_dir}' containing '{prefix_substring}'.")
        return

    MAX_LENGTH = compute_max_length(input_dir, prefix_substring, safety_limit=512)
    print(f"Using MAX_LENGTH = {MAX_LENGTH}")

    rel_col = f"rel_{model_tag}"

    for fn in files:
        path = os.path.join(input_dir, fn)
        print(f"\nProcessing: {path}")
        df = pd.read_csv(path)

        if "SDGarg1" not in df.columns or "SDGarg2" not in df.columns:
            print(f"  Skipped (missing SDGarg1/SDGarg2): {fn}")
            continue

        df[rel_col] = ""

        n = len(df)
        total_done = 0
        first_examples = []

        batches = math.ceil(n / BATCH_SIZE)
        for bi in range(batches):
            s = bi * BATCH_SIZE
            e = min((bi + 1) * BATCH_SIZE, n)
            chunk = df.iloc[s:e]

            pairs = list(zip(chunk["SDGarg1"].astype(str).tolist(),
                             chunk["SDGarg2"].astype(str).tolist()))
            try:
                prob_f, prob_b = nli_probs(pairs, max_length=MAX_LENGTH)
                labels = []
                for i in range(len(pairs)):
                    pf = prob_f[i]; pb = prob_b[i]
                    p_ent_f, p_neu_f, p_con_f = pf[IDX_ENT], pf[IDX_NEU], pf[IDX_CON]
                    p_ent_b, p_neu_b, p_con_b = pb[IDX_ENT], pb[IDX_NEU], pb[IDX_CON]
                    lab = decide_label(p_ent_f, p_con_f, p_neu_f, p_ent_b, p_con_b, p_neu_b)
                    labels.append(lab)
            except Exception as ex:
                print(f"  Batch {bi+1}/{batches} error: {ex}. Marking 'No Relationship'.")
                labels = ["No Relationship"] * len(pairs)

            df.loc[chunk.index, rel_col] = labels

            # first 5 examples
            for (a1, a2), lab in zip(pairs, labels):
                if len(first_examples) < 5:
                    first_examples.append((a1, a2, lab))
                elif len(first_examples) == 5:
                    print("Sample predictions (first 5):\n")
                    for _a1, _a2, _lab in first_examples:
                        print(f"- Arg1: {_a1}\n- Arg2: {_a2}\n  Label: {_lab}\n")
                    first_examples.append((a1, a2, lab))

            total_done += len(pairs)
            if total_done % 100 < BATCH_SIZE:
                print(f"  Progress: {total_done}/{n} relations classified...")

        # Final label validation 
        mask_nan = df["SDGarg1"].isna() | df["SDGarg2"].isna()
        df.loc[mask_nan, rel_col] = "No Relationship"
        bad = ~df[rel_col].isin(VALID_OUT)
        if bad.any():
            df.loc[bad, rel_col] = "No Relationship"

        df.to_csv(path, index=False, encoding="utf-8")
        free_cuda()
        print(f"Saved: {path}")
    return df

## GLOBAL SDG 2023

#### Qwen2.5 3B extraction

In [4]:
prefix = "intra_goalGLOBAL_SGD2023_qwen2.5-3b"   

args_classified = classify_relationships_deberta(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_deberta"].value_counts()

Using MAX_LENGTH = 140

Processing: /kaggle/working/TFM/Data/Relationships Keywords/intra_goalGLOBAL_SGD2023_qwen2.5-3b.csv
Sample predictions (first 5):

- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
- Arg2: Investing in statistical capacity, science, and data literacy are important priorities for achieving the SDGs.
  Label: No Relationship

- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
- Arg2: At the global level, averaging across countries, not a single SDG is currently projected to be met by 2030, with the poorest countries struggling the most.
  Label: No Relationship

- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
- Arg2: All UN Member States should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of ‘leave no one behind’.
  Label: No Relationship

- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
- Arg2: The SDGs are seriously off track. According to the annual SDG Index, global achievement of the SDGs rose only slightly, from 64 percent in 2015 to 66 percent in 2019 – far too slowly to meet the goals by 2030, and with highly uneven progress within and between countries.
  Label: No Relationship

- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
- Arg2: Investing in the SDGs is an investment agenda. In the most basic terms, the world must devote an increased portion of current output to building up sustainable capital assets for the future, and must deploy such assets effectively.
  Label: No Relationship

  Progress: 100/507 relations classified...
  Progress: 200/507 relations classified...
  Progress: 300/507 relations classified...
  Progress: 400/507 relations classified...
  Progress: 500/507 relations classified...
  Progress: 507/507 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships Keywords/intra_goalGLOBAL_SGD2023_qwen2.5-3b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_flanT5,rel_robertaL,rel_deberta
123,Investing in the SDGs is an investment agenda....,All countries should use the half-way momentum...,0_5,0_9,NaN,Support,Support,No Relationship
382,"All countries, poorer and richer alike, should...",industrial,8_0,8_4,NaN,No Relationship,No Relationship,No Relationship
42,"Investing in statistical capacity, science, an...",The SDGs require long-term directed change and...,0_1,0_18,NaN,Support,Support,No Relationship
414,"China has reiterated its support for the SDGs,...","Provincial, metropolitan, and city governments...",11_2,11_3,NaN,Support,Support,No Relationship
168,"The United States, as the world’s biggest econ...","We conclude by underscoring the vital, life-af...",0_7,0_15,NaN,Support,Support,No Relationship

rel_deberta
No Relationship    505
Attack               1
Rephrase             1
Name: count, dtype: int64

In [5]:
prefix = "cross_goalGLOBAL_SGD2023_qwen2.5-3b"   

args_classified = classify_relationships_deberta(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_deberta"].value_counts()

Using MAX_LENGTH = 149

Processing: /kaggle/working/TFM/Data/Relationships Keywords/cross_goalGLOBAL_SGD2023_qwen2.5-3b.csv
Sample predictions (first 5):

- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
- Arg2: Increased funding from the multilateral development banks (MDBs) and public development banks (PDBs) to low- and middle-income countries, linked to investments in the SDGs;
  Label: No Relationship

- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
- Arg2: Many of them lack an adequately high SDG commitment, and almost all lack access to the necessary financial means to implement the SDGs.
  Label: No Relationship

- Arg1: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
- Arg2: The SDG Dashboards rate rich countries, including Nordic countries, at ‘red’ on several SDGs – particularly those related to responsible consumption and production, climate action, and biodiversity – meaning major challenges remain (Lafortune, Sachs, and Schmidt-Traub 2020).
  Label: No Relationship

- Arg1: Investing in statistical capacity, science, and data literacy are important priorities for achieving the SDGs.
- Arg2: Increased funding from the multilateral development banks (MDBs) and public development banks (PDBs) to low- and middle-income countries, linked to investments in the SDGs;
  Label: No Relationship

- Arg1: Investing in statistical capacity, science, and data literacy are important priorities for achieving the SDGs.
- Arg2: Many of them lack an adequately high SDG commitment, and almost all lack access to the necessary financial means to implement the SDGs.
  Label: No Relationship

  Progress: 100/3958 relations classified...
  Progress: 200/3958 relations classified...
  Progress: 300/3958 relations classified...
  Progress: 400/3958 relations classified...
  Progress: 500/3958 relations classified...
  Progress: 600/3958 relations classified...
  Progress: 700/3958 relations classified...
  Progress: 800/3958 relations classified...
  Progress: 900/3958 relations classified...
  Progress: 1000/3958 relations classified...
  Progress: 1100/3958 relations classified...
  Progress: 1200/3958 relations classified...
  Progress: 1300/3958 relations classified...
  Progress: 1400/3958 relations classified...
  Progress: 1500/3958 relations classified...
  Progress: 1600/3958 relations classified...
  Progress: 1700/3958 relations classified...
  Progress: 1800/3958 relations classified...
  Progress: 1900/3958 relations classified...
  Progress: 2000/3958 relations classified...
  Progress: 2100/3958 relations classified...
  Progress: 2200/3958 relations classified...
  Progress: 2300/3958 relations classified...
  Progress: 2400/3958 relations classified...
  Progress: 2500/3958 relations classified...
  Progress: 2600/3958 relations classified...
  Progress: 2700/3958 relations classified...
  Progress: 2800/3958 relations classified...
  Progress: 2900/3958 relations classified...
  Progress: 3000/3958 relations classified...
  Progress: 3100/3958 relations classified...
  Progress: 3200/3958 relations classified...
  Progress: 3300/3958 relations classified...
  Progress: 3400/3958 relations classified...
  Progress: 3500/3958 relations classified...
  Progress: 3600/3958 relations classified...
  Progress: 3700/3958 relations classified...
  Progress: 3800/3958 relations classified...
  Progress: 3900/3958 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships Keywords/cross_goalGLOBAL_SGD2023_qwen2.5-3b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_flanT5,rel_robertaL,rel_deberta
92,Many of them lack an adequately high SDG commi...,Many rich countries also face a significant ch...,0_11,2_0,NaN,Support,Support,No Relationship
3055,"The United States, as the world’s biggest econ...",Sustainable cities: urban infrastructure and s...,8_1,11_0,NaN,Support,Support,No Relationship
2490,We see across societies that inequalities are ...,Reform current institutional frameworks and de...,4_1,17_4,NaN,Support,No Relationship,No Relationship
394,"By contrast, Lebanon, Yemen, Papua New Guinea,...",Although on average the world has made some pr...,0_17,6_2,NaN,No Relationship,Support,No Relationship
3271,"The European Green Deal (EGD), which is exempl...",The SDSN is highly committed to supporting glo...,9_1,15_2,NaN,Support,Support,No Relationship

rel_deberta
No Relationship    3909
Attack               24
Rephrase             21
Support               4
Name: count, dtype: int64

#### Gemma3 27B extraction

In [6]:
prefix = "intra_goalGLOBAL_SGD2023_gemma3-27b"   
rel_col = f"rel_{model_name}"

args_classified = classify_relationships_deberta(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_deberta"].value_counts()

Using MAX_LENGTH = 168

Processing: /kaggle/working/TFM/Data/Relationships Keywords/intra_goalGLOBAL_SGD2023_gemma3-27b.csv
Sample predictions (first 5):

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Despite this alarming development, the SDGs are still achievable.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Further investment is needed in statistical capacity and data literacy to support long-term pathways for key SDG transformations.
  Label: No Relationship

  Progress: 100/3354 relations classified...
  Progress: 200/3354 relations classified...
  Progress: 300/3354 relations classified...
  Progress: 400/3354 relations classified...
  Progress: 500/3354 relations classified...
  Progress: 600/3354 relations classified...
  Progress: 700/3354 relations classified...
  Progress: 800/3354 relations classified...
  Progress: 900/3354 relations classified...
  Progress: 1000/3354 relations classified...
  Progress: 1100/3354 relations classified...
  Progress: 1200/3354 relations classified...
  Progress: 1300/3354 relations classified...
  Progress: 1400/3354 relations classified...
  Progress: 1500/3354 relations classified...
  Progress: 1600/3354 relations classified...
  Progress: 1700/3354 relations classified...
  Progress: 1800/3354 relations classified...
  Progress: 1900/3354 relations classified...
  Progress: 2000/3354 relations classified...
  Progress: 2100/3354 relations classified...
  Progress: 2200/3354 relations classified...
  Progress: 2300/3354 relations classified...
  Progress: 2400/3354 relations classified...
  Progress: 2500/3354 relations classified...
  Progress: 2600/3354 relations classified...
  Progress: 2700/3354 relations classified...
  Progress: 2800/3354 relations classified...
  Progress: 2900/3354 relations classified...
  Progress: 3000/3354 relations classified...
  Progress: 3100/3354 relations classified...
  Progress: 3200/3354 relations classified...
  Progress: 3300/3354 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships Keywords/intra_goalGLOBAL_SGD2023_gemma3-27b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_flanT5,rel_robertaL,rel_deberta
2864,"All countries, poorer and richer alike, should...",national governments must also work with subna...,17_3,17_10,NaN,Support,Support,No Relationship
648,"Unless the SDGs are actively pursued, geophysi...","At their core, the SDGs are an investment agenda.",0_15,0_19,NaN,No Relationship,Support,No Relationship
1484,"And yet, the truth remains that hundreds of mi...",Governments are only now mapping out pathways ...,4_2,4_9,NaN,No Relationship,No Relationship,No Relationship
559,The SDGs are seriously off track (Figure 1.1).,"Second, UN Member States, starting with the G2...",0_12,0_38,NaN,Support,Support,No Relationship
2011,"4.\t Sustainable ecosystems, sustainable agric...",Others include slowing or stopping the global ...,13_1,13_9,NaN,No Relationship,Support,No Relationship

rel_deberta
No Relationship    3285
Attack               63
Support               3
Rephrase              3
Name: count, dtype: int64

In [7]:
prefix = "cross_goalGLOBAL_SGD2023_gemma3-27b"   

args_classified = classify_relationships_deberta(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_deberta"].value_counts()

Using MAX_LENGTH = 172

Processing: /kaggle/working/TFM/Data/Relationships Keywords/cross_goalGLOBAL_SGD2023_gemma3-27b.csv
Sample predictions (first 5):

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Greatly increased funding for national and subnational governments and private businesses in the emerging economies, especially the low-income countries (LICs) and lower-middle-income countries (LMICs), to carry out needed SDG actions;
  Label: Attack

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: to give all people the skills and knowledge to end poverty, protect the environment, and build peaceful and inclusive societies.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Although all governments are in principle committed to economic justice as enshrined in the Universal Declaration of Human Rights, and to the SDG tenets of ‘leave no one behind’ and ‘reach the furthest behind first’, too few are living up to these commitments, especially as powerful groups block adequate public support for weaker groups.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Similarly, extreme poverty can lead to a collapse of tax revenues, followed by government bankruptcy and further economic collapse, a syndrome that now threatens dozens of poor countries.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Most of the low-income and lower-middle income countries, home to more than the half of humanity, face major challenges in achieving most of the SDGs by 2030.
  Label: No Relationship

  Progress: 100/36832 relations classified...
  Progress: 200/36832 relations classified...
  Progress: 300/36832 relations classified...
  Progress: 400/36832 relations classified...
  Progress: 500/36832 relations classified...
  Progress: 600/36832 relations classified...
  Progress: 700/36832 relations classified...
  Progress: 800/36832 relations classified...
  Progress: 900/36832 relations classified...
  Progress: 1000/36832 relations classified...
  Progress: 1100/36832 relations classified...
  Progress: 1200/36832 relations classified...
  Progress: 1300/36832 relations classified...
  Progress: 1400/36832 relations classified...
  Progress: 1500/36832 relations classified...
  Progress: 1600/36832 relations classified...
  Progress: 1700/36832 relations classified...
  Progress: 1800/36832 relations classified...
  Progress: 1900/36832 relations classified...
  Progress: 2000/36832 relations classified...
  Progress: 2100/36832 relations classified...
  Progress: 2200/36832 relations classified...
  Progress: 2300/36832 relations classified...
  Progress: 2400/36832 relations classified...
  Progress: 2500/36832 relations classified...
  Progress: 2600/36832 relations classified...
  Progress: 2700/36832 relations classified...
  Progress: 2800/36832 relations classified...
  Progress: 2900/36832 relations classified...
  Progress: 3000/36832 relations classified...
  Progress: 3100/36832 relations classified...
  Progress: 3200/36832 relations classified...
  Progress: 3300/36832 relations classified...
  Progress: 3400/36832 relations classified...
  Progress: 3500/36832 relations classified...
  Progress: 3600/36832 relations classified...
  Progress: 3700/36832 relations classified...
  Progress: 3800/36832 relations classified...
  Progress: 3900/36832 relations classified...
  Progress: 4000/36832 relations classified...
  Progress: 4100/36832 relations classified...
  Progress: 4200/36832 relations classified...
  Progress: 4300/36832 relations classified...
  Progress: 4400/36832 relations classified...
  Progress: 4500/36832 relations classified...
  Progress: 4600/36832 relations classified...
  Progress: 4700/36832 relations classified...
  Progress: 4800/36832 relations classified...
  Progress: 4900/36832 relations classified...
  Progress: 5000/36832 relations classified...
  Progress: 5100/36832 relations classified...
  Progress: 5200/36832 relations classified...
  Progress: 5300/36832 relations classified...
  Progress: 5400/36832 relations classified...
  Progress: 5500/36832 relations classified...
  Progress: 5600/36832 relations classified...
  Progress: 5700/36832 relations classified...
  Progress: 5800/36832 relations classified...
  Progress: 5900/36832 relations classified...
  Progress: 6000/36832 relations classified...
  Progress: 6100/36832 relations classified...
  Progress: 6200/36832 relations classified...
  Progress: 6300/36832 relations classified...
  Progress: 6400/36832 relations classified...
  Progress: 6500/36832 relations classified...
  Progress: 6600/36832 relations classified...
  Progress: 6700/36832 relations classified...
  Progress: 6800/36832 relations classified...
  Progress: 6900/36832 relations classified...
  Progress: 7000/36832 relations classified...
  Progress: 7100/36832 relations classified...
  Progress: 7200/36832 relations classified...
  Progress: 7300/36832 relations classified...
  Progress: 7400/36832 relations classified...
  Progress: 7500/36832 relations classified...
  Progress: 7600/36832 relations classified...
  Progress: 7700/36832 relations classified...
  Progress: 7800/36832 relations classified...
  Progress: 7900/36832 relations classified...
  Progress: 8000/36832 relations classified...
  Progress: 8100/36832 relations classified...
  Progress: 8200/36832 relations classified...
  Progress: 8300/36832 relations classified...
  Progress: 8400/36832 relations classified...
  Progress: 8500/36832 relations classified...
  Progress: 8600/36832 relations classified...
  Progress: 8700/36832 relations classified...
  Progress: 8800/36832 relations classified...
  Progress: 8900/36832 relations classified...
  Progress: 9000/36832 relations classified...
  Progress: 9100/36832 relations classified...
  Progress: 9200/36832 relations classified...
  Progress: 9300/36832 relations classified...
  Progress: 9400/36832 relations classified...
  Progress: 9500/36832 relations classified...
  Progress: 9600/36832 relations classified...
  Progress: 9700/36832 relations classified...
  Progress: 9800/36832 relations classified...
  Progress: 9900/36832 relations classified...
  Progress: 10000/36832 relations classified...
  Progress: 10100/36832 relations classified...
  Progress: 10200/36832 relations classified...
  Progress: 10300/36832 relations classified...
  Progress: 10400/36832 relations classified...
  Progress: 10500/36832 relations classified...
  Progress: 10600/36832 relations classified...
  Progress: 10700/36832 relations classified...
  Progress: 10800/36832 relations classified...
  Progress: 10900/36832 relations classified...
  Progress: 11000/36832 relations classified...
  Progress: 11100/36832 relations classified...
  Progress: 11200/36832 relations classified...
  Progress: 11300/36832 relations classified...
  Progress: 11400/36832 relations classified...
  Progress: 11500/36832 relations classified...
  Progress: 11600/36832 relations classified...
  Progress: 11700/36832 relations classified...
  Progress: 11800/36832 relations classified...
  Progress: 11900/36832 relations classified...
  Progress: 12000/36832 relations classified...
  Progress: 12100/36832 relations classified...
  Progress: 12200/36832 relations classified...
  Progress: 12300/36832 relations classified...
  Progress: 12400/36832 relations classified...
  Progress: 12500/36832 relations classified...
  Progress: 12600/36832 relations classified...
  Progress: 12700/36832 relations classified...
  Progress: 12800/36832 relations classified...
  Progress: 12900/36832 relations classified...
  Progress: 13000/36832 relations classified...
  Progress: 13100/36832 relations classified...
  Progress: 13200/36832 relations classified...
  Progress: 13300/36832 relations classified...
  Progress: 13400/36832 relations classified...
  Progress: 13500/36832 relations classified...
  Progress: 13600/36832 relations classified...
  Progress: 13700/36832 relations classified...
  Progress: 13800/36832 relations classified...
  Progress: 13900/36832 relations classified...
  Progress: 14000/36832 relations classified...
  Progress: 14100/36832 relations classified...
  Progress: 14200/36832 relations classified...
  Progress: 14300/36832 relations classified...
  Progress: 14400/36832 relations classified...
  Progress: 14500/36832 relations classified...
  Progress: 14600/36832 relations classified...
  Progress: 14700/36832 relations classified...
  Progress: 14800/36832 relations classified...
  Progress: 14900/36832 relations classified...
  Progress: 15000/36832 relations classified...
  Progress: 15100/36832 relations classified...
  Progress: 15200/36832 relations classified...
  Progress: 15300/36832 relations classified...
  Progress: 15400/36832 relations classified...
  Progress: 15500/36832 relations classified...
  Progress: 15600/36832 relations classified...
  Progress: 15700/36832 relations classified...
  Progress: 15800/36832 relations classified...
  Progress: 15900/36832 relations classified...
  Progress: 16000/36832 relations classified...
  Progress: 16100/36832 relations classified...
  Progress: 16200/36832 relations classified...
  Progress: 16300/36832 relations classified...
  Progress: 16400/36832 relations classified...
  Progress: 16500/36832 relations classified...
  Progress: 16600/36832 relations classified...
  Progress: 16700/36832 relations classified...
  Progress: 16800/36832 relations classified...
  Progress: 16900/36832 relations classified...
  Progress: 17000/36832 relations classified...
  Progress: 17100/36832 relations classified...
  Progress: 17200/36832 relations classified...
  Progress: 17300/36832 relations classified...
  Progress: 17400/36832 relations classified...
  Progress: 17500/36832 relations classified...
  Progress: 17600/36832 relations classified...
  Progress: 17700/36832 relations classified...
  Progress: 17800/36832 relations classified...
  Progress: 17900/36832 relations classified...
  Progress: 18000/36832 relations classified...
  Progress: 18100/36832 relations classified...
  Progress: 18200/36832 relations classified...
  Progress: 18300/36832 relations classified...
  Progress: 18400/36832 relations classified...
  Progress: 18500/36832 relations classified...
  Progress: 18600/36832 relations classified...
  Progress: 18700/36832 relations classified...
  Progress: 18800/36832 relations classified...
  Progress: 18900/36832 relations classified...
  Progress: 19000/36832 relations classified...
  Progress: 19100/36832 relations classified...
  Progress: 19200/36832 relations classified...
  Progress: 19300/36832 relations classified...
  Progress: 19400/36832 relations classified...
  Progress: 19500/36832 relations classified...
  Progress: 19600/36832 relations classified...
  Progress: 19700/36832 relations classified...
  Progress: 19800/36832 relations classified...
  Progress: 19900/36832 relations classified...
  Progress: 20000/36832 relations classified...
  Progress: 20100/36832 relations classified...
  Progress: 20200/36832 relations classified...
  Progress: 20300/36832 relations classified...
  Progress: 20400/36832 relations classified...
  Progress: 20500/36832 relations classified...
  Progress: 20600/36832 relations classified...
  Progress: 20700/36832 relations classified...
  Progress: 20800/36832 relations classified...
  Progress: 20900/36832 relations classified...
  Progress: 21000/36832 relations classified...
  Progress: 21100/36832 relations classified...
  Progress: 21200/36832 relations classified...
  Progress: 21300/36832 relations classified...
  Progress: 21400/36832 relations classified...
  Progress: 21500/36832 relations classified...
  Progress: 21600/36832 relations classified...
  Progress: 21700/36832 relations classified...
  Progress: 21800/36832 relations classified...
  Progress: 21900/36832 relations classified...
  Progress: 22000/36832 relations classified...
  Progress: 22100/36832 relations classified...
  Progress: 22200/36832 relations classified...
  Progress: 22300/36832 relations classified...
  Progress: 22400/36832 relations classified...
  Progress: 22500/36832 relations classified...
  Progress: 22600/36832 relations classified...
  Progress: 22700/36832 relations classified...
  Progress: 22800/36832 relations classified...
  Progress: 22900/36832 relations classified...
  Progress: 23000/36832 relations classified...
  Progress: 23100/36832 relations classified...
  Progress: 23200/36832 relations classified...
  Progress: 23300/36832 relations classified...
  Progress: 23400/36832 relations classified...
  Progress: 23500/36832 relations classified...
  Progress: 23600/36832 relations classified...
  Progress: 23700/36832 relations classified...
  Progress: 23800/36832 relations classified...
  Progress: 23900/36832 relations classified...
  Progress: 24000/36832 relations classified...
  Progress: 24100/36832 relations classified...
  Progress: 24200/36832 relations classified...
  Progress: 24300/36832 relations classified...
  Progress: 24400/36832 relations classified...
  Progress: 24500/36832 relations classified...
  Progress: 24600/36832 relations classified...
  Progress: 24700/36832 relations classified...
  Progress: 24800/36832 relations classified...
  Progress: 24900/36832 relations classified...
  Progress: 25000/36832 relations classified...
  Progress: 25100/36832 relations classified...
  Progress: 25200/36832 relations classified...
  Progress: 25300/36832 relations classified...
  Progress: 25400/36832 relations classified...
  Progress: 25500/36832 relations classified...
  Progress: 25600/36832 relations classified...
  Progress: 25700/36832 relations classified...
  Progress: 25800/36832 relations classified...
  Progress: 25900/36832 relations classified...
  Progress: 26000/36832 relations classified...
  Progress: 26100/36832 relations classified...
  Progress: 26200/36832 relations classified...
  Progress: 26300/36832 relations classified...
  Progress: 26400/36832 relations classified...
  Progress: 26500/36832 relations classified...
  Progress: 26600/36832 relations classified...
  Progress: 26700/36832 relations classified...
  Progress: 26800/36832 relations classified...
  Progress: 26900/36832 relations classified...
  Progress: 27000/36832 relations classified...
  Progress: 27100/36832 relations classified...
  Progress: 27200/36832 relations classified...
  Progress: 27300/36832 relations classified...
  Progress: 27400/36832 relations classified...
  Progress: 27500/36832 relations classified...
  Progress: 27600/36832 relations classified...
  Progress: 27700/36832 relations classified...
  Progress: 27800/36832 relations classified...
  Progress: 27900/36832 relations classified...
  Progress: 28000/36832 relations classified...
  Progress: 28100/36832 relations classified...
  Progress: 28200/36832 relations classified...
  Progress: 28300/36832 relations classified...
  Progress: 28400/36832 relations classified...
  Progress: 28500/36832 relations classified...
  Progress: 28600/36832 relations classified...
  Progress: 28700/36832 relations classified...
  Progress: 28800/36832 relations classified...
  Progress: 28900/36832 relations classified...
  Progress: 29000/36832 relations classified...
  Progress: 29100/36832 relations classified...
  Progress: 29200/36832 relations classified...
  Progress: 29300/36832 relations classified...
  Progress: 29400/36832 relations classified...
  Progress: 29500/36832 relations classified...
  Progress: 29600/36832 relations classified...
  Progress: 29700/36832 relations classified...
  Progress: 29800/36832 relations classified...
  Progress: 29900/36832 relations classified...
  Progress: 30000/36832 relations classified...
  Progress: 30100/36832 relations classified...
  Progress: 30200/36832 relations classified...
  Progress: 30300/36832 relations classified...
  Progress: 30400/36832 relations classified...
  Progress: 30500/36832 relations classified...
  Progress: 30600/36832 relations classified...
  Progress: 30700/36832 relations classified...
  Progress: 30800/36832 relations classified...
  Progress: 30900/36832 relations classified...
  Progress: 31000/36832 relations classified...
  Progress: 31100/36832 relations classified...
  Progress: 31200/36832 relations classified...
  Progress: 31300/36832 relations classified...
  Progress: 31400/36832 relations classified...
  Progress: 31500/36832 relations classified...
  Progress: 31600/36832 relations classified...
  Progress: 31700/36832 relations classified...
  Progress: 31800/36832 relations classified...
  Progress: 31900/36832 relations classified...
  Progress: 32000/36832 relations classified...
  Progress: 32100/36832 relations classified...
  Progress: 32200/36832 relations classified...
  Progress: 32300/36832 relations classified...
  Progress: 32400/36832 relations classified...
  Progress: 32500/36832 relations classified...
  Progress: 32600/36832 relations classified...
  Progress: 32700/36832 relations classified...
  Progress: 32800/36832 relations classified...
  Progress: 32900/36832 relations classified...
  Progress: 33000/36832 relations classified...
  Progress: 33100/36832 relations classified...
  Progress: 33200/36832 relations classified...
  Progress: 33300/36832 relations classified...
  Progress: 33400/36832 relations classified...
  Progress: 33500/36832 relations classified...
  Progress: 33600/36832 relations classified...
  Progress: 33700/36832 relations classified...
  Progress: 33800/36832 relations classified...
  Progress: 33900/36832 relations classified...
  Progress: 34000/36832 relations classified...
  Progress: 34100/36832 relations classified...
  Progress: 34200/36832 relations classified...
  Progress: 34300/36832 relations classified...
  Progress: 34400/36832 relations classified...
  Progress: 34500/36832 relations classified...
  Progress: 34600/36832 relations classified...
  Progress: 34700/36832 relations classified...
  Progress: 34800/36832 relations classified...
  Progress: 34900/36832 relations classified...
  Progress: 35000/36832 relations classified...
  Progress: 35100/36832 relations classified...
  Progress: 35200/36832 relations classified...
  Progress: 35300/36832 relations classified...
  Progress: 35400/36832 relations classified...
  Progress: 35500/36832 relations classified...
  Progress: 35600/36832 relations classified...
  Progress: 35700/36832 relations classified...
  Progress: 35800/36832 relations classified...
  Progress: 35900/36832 relations classified...
  Progress: 36000/36832 relations classified...
  Progress: 36100/36832 relations classified...
  Progress: 36200/36832 relations classified...
  Progress: 36300/36832 relations classified...
  Progress: 36400/36832 relations classified...
  Progress: 36500/36832 relations classified...
  Progress: 36600/36832 relations classified...
  Progress: 36700/36832 relations classified...
  Progress: 36800/36832 relations classified...
  Progress: 36832/36832 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships Keywords/cross_goalGLOBAL_SGD2023_gemma3-27b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_flanT5,rel_robertaL,rel_deberta
36466,SDG 16 recognizes the vital role of peaceful a...,One of the consistent findings of the SDSN is ...,16_9,17_19,NaN,Support,Support,No Relationship
6046,The Stimulus’ urgent objective is to address t...,the “Code of Conduct on Responsible Food Busin...,0_4,12_0,NaN,Support,No Relationship,No Relationship
30842,the promotion of key enablers such as digital ...,SDG 17 (Partnerships for the Goals) calls on a...,10_8,17_28,NaN,Support,Rephrase,No Relationship
28824,2. Infrastructure: Energy production and distr...,"All countries, poorer and richer alike, should...",9_1,17_3,NaN,Support,Support,No Relationship
33833,"Global spending on armaments, estimated at US$...",Unifying international business ecosystems cou...,13_2,17_16,NaN,No Relationship,No Relationship,No Relationship

rel_deberta
No Relationship    36485
Attack               265
Rephrase              66
Support               16
Name: count, dtype: int64

#### Gemma3 4B extraction

In [8]:
prefix = "intra_goalGLOBAL_SGD2023_gemma3-4b"   

args_classified = classify_relationships_deberta(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_deberta"].value_counts()

Using MAX_LENGTH = 248

Processing: /kaggle/working/TFM/Data/Relationships Keywords/intra_goalGLOBAL_SGD2023_gemma3-4b.csv
Sample predictions (first 5):

- Arg1: the SDGs are seriously off track
- Arg2: the SDGs are still achievable
  Label: Attack

- Arg1: the SDGs are seriously off track
- Arg2: it is critical that UN Member States adopt and implement the SDG Stimulus
  Label: Attack

- Arg1: the SDGs are seriously off track
- Arg2: To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments
  Label: No Relationship

- Arg1: the SDGs are seriously off track
- Arg2: Revise the credit rating system and debt sustainability metrics to facilitate long-term sustainable development
  Label: No Relationship

- Arg1: the SDGs are seriously off track
- Arg2: Align private business investment flows with the SDGs, through improved national planning, regulation, reporting, and oversight
  Label: Attack

  Progress: 100/6976 relations classified...
  Progress: 200/6976 relations classified...
  Progress: 300/6976 relations classified...
  Progress: 400/6976 relations classified...
  Progress: 500/6976 relations classified...
  Progress: 600/6976 relations classified...
  Progress: 700/6976 relations classified...
  Progress: 800/6976 relations classified...
  Progress: 900/6976 relations classified...
  Progress: 1000/6976 relations classified...
  Progress: 1100/6976 relations classified...
  Progress: 1200/6976 relations classified...
  Progress: 1300/6976 relations classified...
  Progress: 1400/6976 relations classified...
  Progress: 1500/6976 relations classified...
  Progress: 1600/6976 relations classified...
  Progress: 1700/6976 relations classified...
  Progress: 1800/6976 relations classified...
  Progress: 1900/6976 relations classified...
  Progress: 2000/6976 relations classified...
  Progress: 2100/6976 relations classified...
  Progress: 2200/6976 relations classified...
  Progress: 2300/6976 relations classified...
  Progress: 2400/6976 relations classified...
  Progress: 2500/6976 relations classified...
  Progress: 2600/6976 relations classified...
  Progress: 2700/6976 relations classified...
  Progress: 2800/6976 relations classified...
  Progress: 2900/6976 relations classified...
  Progress: 3000/6976 relations classified...
  Progress: 3100/6976 relations classified...
  Progress: 3200/6976 relations classified...
  Progress: 3300/6976 relations classified...
  Progress: 3400/6976 relations classified...
  Progress: 3500/6976 relations classified...
  Progress: 3600/6976 relations classified...
  Progress: 3700/6976 relations classified...
  Progress: 3800/6976 relations classified...
  Progress: 3900/6976 relations classified...
  Progress: 4000/6976 relations classified...
  Progress: 4100/6976 relations classified...
  Progress: 4200/6976 relations classified...
  Progress: 4300/6976 relations classified...
  Progress: 4400/6976 relations classified...
  Progress: 4500/6976 relations classified...
  Progress: 4600/6976 relations classified...
  Progress: 4700/6976 relations classified...
  Progress: 4800/6976 relations classified...
  Progress: 4900/6976 relations classified...
  Progress: 5000/6976 relations classified...
  Progress: 5100/6976 relations classified...
  Progress: 5200/6976 relations classified...
  Progress: 5300/6976 relations classified...
  Progress: 5400/6976 relations classified...
  Progress: 5500/6976 relations classified...
  Progress: 5600/6976 relations classified...
  Progress: 5700/6976 relations classified...
  Progress: 5800/6976 relations classified...
  Progress: 5900/6976 relations classified...
  Progress: 6000/6976 relations classified...
  Progress: 6100/6976 relations classified...
  Progress: 6200/6976 relations classified...
  Progress: 6300/6976 relations classified...
  Progress: 6400/6976 relations classified...
  Progress: 6500/6976 relations classified...
  Progress: 6600/6976 relations classified...
  Progress: 6700/6976 relations classified...
  Progress: 6800/6976 relations classified...
  Progress: 6900/6976 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships Keywords/intra_goalGLOBAL_SGD2023_gemma3-4b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_flanT5,rel_robertaL,rel_deberta
5216,"UN Member States should adopt an SDG Stimulus,...","Deep, chronic, and crippling under-investment ...",10_3,10_9,NaN,Support,Rephrase,No Relationship
3677,"investing in statistical capacity, science, an...",The SDSN Framework of nearly 90% of global fis...,1_3,1_9,NaN,No Relationship,No Relationship,No Relationship
4804,Local governments have the front-line responsi...,SDSN is working closely with the UNESCO SDG 4 ...,4_7,4_9,NaN,Support,Support,No Relationship
3046,all UN Member States will have presented a VNR...,Each of these challenges requires large-scale ...,0_52,0_57,NaN,No Relationship,No Relationship,No Relationship
408,Revise the credit rating system and debt susta...,It is difficult to assess whether the adoption...,0_4,0_83,NaN,No Relationship,No Relationship,No Relationship

rel_deberta
No Relationship    6821
Attack              149
Rephrase              3
Support               3
Name: count, dtype: int64

In [9]:
prefix = "cross_goalGLOBAL_SGD2023_gemma3-4b"   

args_classified = classify_relationships_deberta(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_deberta"].value_counts()

Using MAX_LENGTH = 267

Processing: /kaggle/working/TFM/Data/Relationships Keywords/cross_goalGLOBAL_SGD2023_gemma3-4b.csv
Sample predictions (first 5):

- Arg1: the SDGs are seriously off track
- Arg2: To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.
  Label: Attack

- Arg1: the SDGs are seriously off track
- Arg2: Greatly increase funding to national and subnational governments and private businesses, especially in LICs and LMICs, to carry out needed SDG investments.
  Label: No Relationship

- Arg1: the SDGs are seriously off track
- Arg2: Revise liquidity structures for LICs and LMICs, especially regarding sovereign debts, to forestall self-fulfilling banking and balance-of-payments crises;
  Label: No Relationship

- Arg1: the SDGs are seriously off track
- Arg2: investing in statistical capacity, science, and data literacy are important priorities for achieving the SDGs
  Label: No Relationship

- Arg1: the SDGs are seriously off track
- Arg2: increased funding from the multilateral development banks (MDBs) and public development banks (PDBs) to low- and middle-income countries, linked to investments in the SDGs
  Label: Attack

  Progress: 100/71234 relations classified...
  Progress: 200/71234 relations classified...
  Progress: 300/71234 relations classified...
  Progress: 400/71234 relations classified...
  Progress: 500/71234 relations classified...
  Progress: 600/71234 relations classified...
  Progress: 700/71234 relations classified...
  Progress: 800/71234 relations classified...
  Progress: 900/71234 relations classified...
  Progress: 1000/71234 relations classified...
  Progress: 1100/71234 relations classified...
  Progress: 1200/71234 relations classified...
  Progress: 1300/71234 relations classified...
  Progress: 1400/71234 relations classified...
  Progress: 1500/71234 relations classified...
  Progress: 1600/71234 relations classified...
  Progress: 1700/71234 relations classified...
  Progress: 1800/71234 relations classified...
  Progress: 1900/71234 relations classified...
  Progress: 2000/71234 relations classified...
  Progress: 2100/71234 relations classified...
  Progress: 2200/71234 relations classified...
  Progress: 2300/71234 relations classified...
  Progress: 2400/71234 relations classified...
  Progress: 2500/71234 relations classified...
  Progress: 2600/71234 relations classified...
  Progress: 2700/71234 relations classified...
  Progress: 2800/71234 relations classified...
  Progress: 2900/71234 relations classified...
  Progress: 3000/71234 relations classified...
  Progress: 3100/71234 relations classified...
  Progress: 3200/71234 relations classified...
  Progress: 3300/71234 relations classified...
  Progress: 3400/71234 relations classified...
  Progress: 3500/71234 relations classified...
  Progress: 3600/71234 relations classified...
  Progress: 3700/71234 relations classified...
  Progress: 3800/71234 relations classified...
  Progress: 3900/71234 relations classified...
  Progress: 4000/71234 relations classified...
  Progress: 4100/71234 relations classified...
  Progress: 4200/71234 relations classified...
  Progress: 4300/71234 relations classified...
  Progress: 4400/71234 relations classified...
  Progress: 4500/71234 relations classified...
  Progress: 4600/71234 relations classified...
  Progress: 4700/71234 relations classified...
  Progress: 4800/71234 relations classified...
  Progress: 4900/71234 relations classified...
  Progress: 5000/71234 relations classified...
  Progress: 5100/71234 relations classified...
  Progress: 5200/71234 relations classified...
  Progress: 5300/71234 relations classified...
  Progress: 5400/71234 relations classified...
  Progress: 5500/71234 relations classified...
  Progress: 5600/71234 relations classified...
  Progress: 5700/71234 relations classified...
  Progress: 5800/71234 relations classified...
  Progress: 5900/71234 relations classified...
  Progress: 6000/71234 relations classified...
  Progress: 6100/71234 relations classified...
  Progress: 6200/71234 relations classified...
  Progress: 6300/71234 relations classified...
  Progress: 6400/71234 relations classified...
  Progress: 6500/71234 relations classified...
  Progress: 6600/71234 relations classified...
  Progress: 6700/71234 relations classified...
  Progress: 6800/71234 relations classified...
  Progress: 6900/71234 relations classified...
  Progress: 7000/71234 relations classified...
  Progress: 7100/71234 relations classified...
  Progress: 7200/71234 relations classified...
  Progress: 7300/71234 relations classified...
  Progress: 7400/71234 relations classified...
  Progress: 7500/71234 relations classified...
  Progress: 7600/71234 relations classified...
  Progress: 7700/71234 relations classified...
  Progress: 7800/71234 relations classified...
  Progress: 7900/71234 relations classified...
  Progress: 8000/71234 relations classified...
  Progress: 8100/71234 relations classified...
  Progress: 8200/71234 relations classified...
  Progress: 8300/71234 relations classified...
  Progress: 8400/71234 relations classified...
  Progress: 8500/71234 relations classified...
  Progress: 8600/71234 relations classified...
  Progress: 8700/71234 relations classified...
  Progress: 8800/71234 relations classified...
  Progress: 8900/71234 relations classified...
  Progress: 9000/71234 relations classified...
  Progress: 9100/71234 relations classified...
  Progress: 9200/71234 relations classified...
  Progress: 9300/71234 relations classified...
  Progress: 9400/71234 relations classified...
  Progress: 9500/71234 relations classified...
  Progress: 9600/71234 relations classified...
  Progress: 9700/71234 relations classified...
  Progress: 9800/71234 relations classified...
  Progress: 9900/71234 relations classified...
  Progress: 10000/71234 relations classified...
  Progress: 10100/71234 relations classified...
  Progress: 10200/71234 relations classified...
  Progress: 10300/71234 relations classified...
  Progress: 10400/71234 relations classified...
  Progress: 10500/71234 relations classified...
  Progress: 10600/71234 relations classified...
  Progress: 10700/71234 relations classified...
  Progress: 10800/71234 relations classified...
  Progress: 10900/71234 relations classified...
  Progress: 11000/71234 relations classified...
  Progress: 11100/71234 relations classified...
  Progress: 11200/71234 relations classified...
  Progress: 11300/71234 relations classified...
  Progress: 11400/71234 relations classified...
  Progress: 11500/71234 relations classified...
  Progress: 11600/71234 relations classified...
  Progress: 11700/71234 relations classified...
  Progress: 11800/71234 relations classified...
  Progress: 11900/71234 relations classified...
  Progress: 12000/71234 relations classified...
  Progress: 12100/71234 relations classified...
  Progress: 12200/71234 relations classified...
  Progress: 12300/71234 relations classified...
  Progress: 12400/71234 relations classified...
  Progress: 12500/71234 relations classified...
  Progress: 12600/71234 relations classified...
  Progress: 12700/71234 relations classified...
  Progress: 12800/71234 relations classified...
  Progress: 12900/71234 relations classified...
  Progress: 13000/71234 relations classified...
  Progress: 13100/71234 relations classified...
  Progress: 13200/71234 relations classified...
  Progress: 13300/71234 relations classified...
  Progress: 13400/71234 relations classified...
  Progress: 13500/71234 relations classified...
  Progress: 13600/71234 relations classified...
  Progress: 13700/71234 relations classified...
  Progress: 13800/71234 relations classified...
  Progress: 13900/71234 relations classified...
  Progress: 14000/71234 relations classified...
  Progress: 14100/71234 relations classified...
  Progress: 14200/71234 relations classified...
  Progress: 14300/71234 relations classified...
  Progress: 14400/71234 relations classified...
  Progress: 14500/71234 relations classified...
  Progress: 14600/71234 relations classified...
  Progress: 14700/71234 relations classified...
  Progress: 14800/71234 relations classified...
  Progress: 14900/71234 relations classified...
  Progress: 15000/71234 relations classified...
  Progress: 15100/71234 relations classified...
  Progress: 15200/71234 relations classified...
  Progress: 15300/71234 relations classified...
  Progress: 15400/71234 relations classified...
  Progress: 15500/71234 relations classified...
  Progress: 15600/71234 relations classified...
  Progress: 15700/71234 relations classified...
  Progress: 15800/71234 relations classified...
  Progress: 15900/71234 relations classified...
  Progress: 16000/71234 relations classified...
  Progress: 16100/71234 relations classified...
  Progress: 16200/71234 relations classified...
  Progress: 16300/71234 relations classified...
  Progress: 16400/71234 relations classified...
  Progress: 16500/71234 relations classified...
  Progress: 16600/71234 relations classified...
  Progress: 16700/71234 relations classified...
  Progress: 16800/71234 relations classified...
  Progress: 16900/71234 relations classified...
  Progress: 17000/71234 relations classified...
  Progress: 17100/71234 relations classified...
  Progress: 17200/71234 relations classified...
  Progress: 17300/71234 relations classified...
  Progress: 17400/71234 relations classified...
  Progress: 17500/71234 relations classified...
  Progress: 17600/71234 relations classified...
  Progress: 17700/71234 relations classified...
  Progress: 17800/71234 relations classified...
  Progress: 17900/71234 relations classified...
  Progress: 18000/71234 relations classified...
  Progress: 18100/71234 relations classified...
  Progress: 18200/71234 relations classified...
  Progress: 18300/71234 relations classified...
  Progress: 18400/71234 relations classified...
  Progress: 18500/71234 relations classified...
  Progress: 18600/71234 relations classified...
  Progress: 18700/71234 relations classified...
  Progress: 18800/71234 relations classified...
  Progress: 18900/71234 relations classified...
  Progress: 19000/71234 relations classified...
  Progress: 19100/71234 relations classified...
  Progress: 19200/71234 relations classified...
  Progress: 19300/71234 relations classified...
  Progress: 19400/71234 relations classified...
  Progress: 19500/71234 relations classified...
  Progress: 19600/71234 relations classified...
  Progress: 19700/71234 relations classified...
  Progress: 19800/71234 relations classified...
  Progress: 19900/71234 relations classified...
  Progress: 20000/71234 relations classified...
  Progress: 20100/71234 relations classified...
  Progress: 20200/71234 relations classified...
  Progress: 20300/71234 relations classified...
  Progress: 20400/71234 relations classified...
  Progress: 20500/71234 relations classified...
  Progress: 20600/71234 relations classified...
  Progress: 20700/71234 relations classified...
  Progress: 20800/71234 relations classified...
  Progress: 20900/71234 relations classified...
  Progress: 21000/71234 relations classified...
  Progress: 21100/71234 relations classified...
  Progress: 21200/71234 relations classified...
  Progress: 21300/71234 relations classified...
  Progress: 21400/71234 relations classified...
  Progress: 21500/71234 relations classified...
  Progress: 21600/71234 relations classified...
  Progress: 21700/71234 relations classified...
  Progress: 21800/71234 relations classified...
  Progress: 21900/71234 relations classified...
  Progress: 22000/71234 relations classified...
  Progress: 22100/71234 relations classified...
  Progress: 22200/71234 relations classified...
  Progress: 22300/71234 relations classified...
  Progress: 22400/71234 relations classified...
  Progress: 22500/71234 relations classified...
  Progress: 22600/71234 relations classified...
  Progress: 22700/71234 relations classified...
  Progress: 22800/71234 relations classified...
  Progress: 22900/71234 relations classified...
  Progress: 23000/71234 relations classified...
  Progress: 23100/71234 relations classified...
  Progress: 23200/71234 relations classified...
  Progress: 23300/71234 relations classified...
  Progress: 23400/71234 relations classified...
  Progress: 23500/71234 relations classified...
  Progress: 23600/71234 relations classified...
  Progress: 23700/71234 relations classified...
  Progress: 23800/71234 relations classified...
  Progress: 23900/71234 relations classified...
  Progress: 24000/71234 relations classified...
  Progress: 24100/71234 relations classified...
  Progress: 24200/71234 relations classified...
  Progress: 24300/71234 relations classified...
  Progress: 24400/71234 relations classified...
  Progress: 24500/71234 relations classified...
  Progress: 24600/71234 relations classified...
  Progress: 24700/71234 relations classified...
  Progress: 24800/71234 relations classified...
  Progress: 24900/71234 relations classified...
  Progress: 25000/71234 relations classified...
  Progress: 25100/71234 relations classified...
  Progress: 25200/71234 relations classified...
  Progress: 25300/71234 relations classified...
  Progress: 25400/71234 relations classified...
  Progress: 25500/71234 relations classified...
  Progress: 25600/71234 relations classified...
  Progress: 25700/71234 relations classified...
  Progress: 25800/71234 relations classified...
  Progress: 25900/71234 relations classified...
  Progress: 26000/71234 relations classified...
  Progress: 26100/71234 relations classified...
  Progress: 26200/71234 relations classified...
  Progress: 26300/71234 relations classified...
  Progress: 26400/71234 relations classified...
  Progress: 26500/71234 relations classified...
  Progress: 26600/71234 relations classified...
  Progress: 26700/71234 relations classified...
  Progress: 26800/71234 relations classified...
  Progress: 26900/71234 relations classified...
  Progress: 27000/71234 relations classified...
  Progress: 27100/71234 relations classified...
  Progress: 27200/71234 relations classified...
  Progress: 27300/71234 relations classified...
  Progress: 27400/71234 relations classified...
  Progress: 27500/71234 relations classified...
  Progress: 27600/71234 relations classified...
  Progress: 27700/71234 relations classified...
  Progress: 27800/71234 relations classified...
  Progress: 27900/71234 relations classified...
  Progress: 28000/71234 relations classified...
  Progress: 28100/71234 relations classified...
  Progress: 28200/71234 relations classified...
  Progress: 28300/71234 relations classified...
  Progress: 28400/71234 relations classified...
  Progress: 28500/71234 relations classified...
  Progress: 28600/71234 relations classified...
  Progress: 28700/71234 relations classified...
  Progress: 28800/71234 relations classified...
  Progress: 28900/71234 relations classified...
  Progress: 29000/71234 relations classified...
  Progress: 29100/71234 relations classified...
  Progress: 29200/71234 relations classified...
  Progress: 29300/71234 relations classified...
  Progress: 29400/71234 relations classified...
  Progress: 29500/71234 relations classified...
  Progress: 29600/71234 relations classified...
  Progress: 29700/71234 relations classified...
  Progress: 29800/71234 relations classified...
  Progress: 29900/71234 relations classified...
  Progress: 30000/71234 relations classified...
  Progress: 30100/71234 relations classified...
  Progress: 30200/71234 relations classified...
  Progress: 30300/71234 relations classified...
  Progress: 30400/71234 relations classified...
  Progress: 30500/71234 relations classified...
  Progress: 30600/71234 relations classified...
  Progress: 30700/71234 relations classified...
  Progress: 30800/71234 relations classified...
  Progress: 30900/71234 relations classified...
  Progress: 31000/71234 relations classified...
  Progress: 31100/71234 relations classified...
  Progress: 31200/71234 relations classified...
  Progress: 31300/71234 relations classified...
  Progress: 31400/71234 relations classified...
  Progress: 31500/71234 relations classified...
  Progress: 31600/71234 relations classified...
  Progress: 31700/71234 relations classified...
  Progress: 31800/71234 relations classified...
  Progress: 31900/71234 relations classified...
  Progress: 32000/71234 relations classified...
  Progress: 32100/71234 relations classified...
  Progress: 32200/71234 relations classified...
  Progress: 32300/71234 relations classified...
  Progress: 32400/71234 relations classified...
  Progress: 32500/71234 relations classified...
  Progress: 32600/71234 relations classified...
  Progress: 32700/71234 relations classified...
  Progress: 32800/71234 relations classified...
  Progress: 32900/71234 relations classified...
  Progress: 33000/71234 relations classified...
  Progress: 33100/71234 relations classified...
  Progress: 33200/71234 relations classified...
  Progress: 33300/71234 relations classified...
  Progress: 33400/71234 relations classified...
  Progress: 33500/71234 relations classified...
  Progress: 33600/71234 relations classified...
  Progress: 33700/71234 relations classified...
  Progress: 33800/71234 relations classified...
  Progress: 33900/71234 relations classified...
  Progress: 34000/71234 relations classified...
  Progress: 34100/71234 relations classified...
  Progress: 34200/71234 relations classified...
  Progress: 34300/71234 relations classified...
  Progress: 34400/71234 relations classified...
  Progress: 34500/71234 relations classified...
  Progress: 34600/71234 relations classified...
  Progress: 34700/71234 relations classified...
  Progress: 34800/71234 relations classified...
  Progress: 34900/71234 relations classified...
  Progress: 35000/71234 relations classified...
  Progress: 35100/71234 relations classified...
  Progress: 35200/71234 relations classified...
  Progress: 35300/71234 relations classified...
  Progress: 35400/71234 relations classified...
  Progress: 35500/71234 relations classified...
  Progress: 35600/71234 relations classified...
  Progress: 35700/71234 relations classified...
  Progress: 35800/71234 relations classified...
  Progress: 35900/71234 relations classified...
  Progress: 36000/71234 relations classified...
  Progress: 36100/71234 relations classified...
  Progress: 36200/71234 relations classified...
  Progress: 36300/71234 relations classified...
  Progress: 36400/71234 relations classified...
  Progress: 36500/71234 relations classified...
  Progress: 36600/71234 relations classified...
  Progress: 36700/71234 relations classified...
  Progress: 36800/71234 relations classified...
  Progress: 36900/71234 relations classified...
  Progress: 37000/71234 relations classified...
  Progress: 37100/71234 relations classified...
  Progress: 37200/71234 relations classified...
  Progress: 37300/71234 relations classified...
  Progress: 37400/71234 relations classified...
  Progress: 37500/71234 relations classified...
  Progress: 37600/71234 relations classified...
  Progress: 37700/71234 relations classified...
  Progress: 37800/71234 relations classified...
  Progress: 37900/71234 relations classified...
  Progress: 38000/71234 relations classified...
  Progress: 38100/71234 relations classified...
  Progress: 38200/71234 relations classified...
  Progress: 38300/71234 relations classified...
  Progress: 38400/71234 relations classified...
  Progress: 38500/71234 relations classified...
  Progress: 38600/71234 relations classified...
  Progress: 38700/71234 relations classified...
  Progress: 38800/71234 relations classified...
  Progress: 38900/71234 relations classified...
  Progress: 39000/71234 relations classified...
  Progress: 39100/71234 relations classified...
  Progress: 39200/71234 relations classified...
  Progress: 39300/71234 relations classified...

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_flanT5,rel_robertaL,rel_deberta
27204,trade more sustainable and more consistent wit...,Some countries specifically refer to the SDGs ...,1_25,2_19,NaN,Support,Support,No Relationship
55058,globalized trade rules for ‘cleantech’ could a...,Sustainable capital assets are long-lasting ca...,8_6,9_6,NaN,Support,Support,No Relationship
46396,achieving universal health coverage and ensuri...,This scorecard shows that many countries aroun...,3_11,16_30,NaN,Support,Support,No Relationship
55896,Increased funding from the multilateral develo...,"The EGD embraces an EU-wide set of goals, time...",8_2,13_10,NaN,Support,Rephrase,No Relationship
43762,Governments are only now mapping out pathways ...,actions by governments at all levels to ensure...,3_5,4_2,NaN,Support,Support,No Relationship

rel_deberta
No Relationship    70061
Attack              1025
Rephrase             129
Support               19
Name: count, dtype: int64

#### Llama3.3 70B extraction

In [10]:
prefix = "intra_goalGLOBAL_SGD2023_llama3.3-70b"   

args_classified = classify_relationships_deberta(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_deberta"].value_counts()

Using MAX_LENGTH = 216

Processing: /kaggle/working/TFM/Data/Relationships Keywords/intra_goalGLOBAL_SGD2023_llama3.3-70b.csv
Sample predictions (first 5):

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Since the outbreak of the pandemic in 2020 and other simultaneous crises, SDG progress has stalled globally.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: The world is off track, but that is all the more reason to double down on the SDGs.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.
  Label: No Relationship

  Progress: 100/5951 relations classified...
  Progress: 200/5951 relations classified...
  Progress: 300/5951 relations classified...
  Progress: 400/5951 relations classified...
  Progress: 500/5951 relations classified...
  Progress: 600/5951 relations classified...
  Progress: 700/5951 relations classified...
  Progress: 800/5951 relations classified...
  Progress: 900/5951 relations classified...
  Progress: 1000/5951 relations classified...
  Progress: 1100/5951 relations classified...
  Progress: 1200/5951 relations classified...
  Progress: 1300/5951 relations classified...
  Progress: 1400/5951 relations classified...
  Progress: 1500/5951 relations classified...
  Progress: 1600/5951 relations classified...
  Progress: 1700/5951 relations classified...
  Progress: 1800/5951 relations classified...
  Progress: 1900/5951 relations classified...
  Progress: 2000/5951 relations classified...
  Progress: 2100/5951 relations classified...
  Progress: 2200/5951 relations classified...
  Progress: 2300/5951 relations classified...
  Progress: 2400/5951 relations classified...
  Progress: 2500/5951 relations classified...
  Progress: 2600/5951 relations classified...
  Progress: 2700/5951 relations classified...
  Progress: 2800/5951 relations classified...
  Progress: 2900/5951 relations classified...
  Progress: 3000/5951 relations classified...
  Progress: 3100/5951 relations classified...
  Progress: 3200/5951 relations classified...
  Progress: 3300/5951 relations classified...
  Progress: 3400/5951 relations classified...
  Progress: 3500/5951 relations classified...
  Progress: 3600/5951 relations classified...
  Progress: 3700/5951 relations classified...
  Progress: 3800/5951 relations classified...
  Progress: 3900/5951 relations classified...
  Progress: 4000/5951 relations classified...
  Progress: 4100/5951 relations classified...
  Progress: 4200/5951 relations classified...
  Progress: 4300/5951 relations classified...
  Progress: 4400/5951 relations classified...
  Progress: 4500/5951 relations classified...
  Progress: 4600/5951 relations classified...
  Progress: 4700/5951 relations classified...
  Progress: 4800/5951 relations classified...
  Progress: 4900/5951 relations classified...
  Progress: 5000/5951 relations classified...
  Progress: 5100/5951 relations classified...
  Progress: 5200/5951 relations classified...
  Progress: 5300/5951 relations classified...
  Progress: 5400/5951 relations classified...
  Progress: 5500/5951 relations classified...
  Progress: 5600/5951 relations classified...
  Progress: 5700/5951 relations classified...
  Progress: 5800/5951 relations classified...
  Progress: 5900/5951 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships Keywords/intra_goalGLOBAL_SGD2023_llama3.3-70b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_flanT5,rel_robertaL,rel_deberta
2529,"We conclude by underscoring the vital, life-af...",As detailed in the Europe Sustainable Developm...,0_52,0_60,NaN,No Relationship,No Relationship,No Relationship
3006,SDSN’s mission was fourfold: (i) scholarly res...,SDG target 4.1 calls for universal access to 1...,4_2,4_16,NaN,Support,No Relationship,No Relationship
492,"All countries, poorer and richer alike, should...",International financing flows should be aligne...,0_6,0_70,NaN,Support,Support,No Relationship
2219,Long-term investment plans are essential for n...,"Provincial, metropolitan, and city governments...",0_41,0_47,NaN,Support,Support,No Relationship
198,"The world is off track, but that is all the mo...","Second, UN Member States, starting with the G2...",0_2,0_54,NaN,Support,Support,No Relationship

rel_deberta
No Relationship    5885
Attack               54
Support              10
Rephrase              2
Name: count, dtype: int64

In [11]:
prefix = "cross_goalGLOBAL_SGD2023_llama3.3-70b"   

args_classified = classify_relationships_deberta(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_deberta"].value_counts()

Using MAX_LENGTH = 281

Processing: /kaggle/working/TFM/Data/Relationships Keywords/cross_goalGLOBAL_SGD2023_llama3.3-70b.csv
Sample predictions (first 5):

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: The grim reality is that at the midpoint of the 2030 Agenda, the SDGs are far off track.
  Label: Support

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Similarly, extreme poverty can lead to a collapse of tax revenues, followed by government bankruptcy and further economic collapse, a syndrome that now threatens dozens of poor countries.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Most of the low-income and lower-middle income countries, home to more than the half of humanity, face major challenges in achieving most of the SDGs by 2030.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Many of them lack an adequately high SDG commitment, and almost all lack access to the necessary financial means to implement the SDGs.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Deep, chronic, and crippling under-investment in virtually all low-income countries (LICs) and lower-middle-income countries (LMICs).
  Label: No Relationship

  Progress: 100/58310 relations classified...
  Progress: 200/58310 relations classified...
  Progress: 300/58310 relations classified...
  Progress: 400/58310 relations classified...
  Progress: 500/58310 relations classified...
  Progress: 600/58310 relations classified...
  Progress: 700/58310 relations classified...
  Progress: 800/58310 relations classified...
  Progress: 900/58310 relations classified...
  Progress: 1000/58310 relations classified...
  Progress: 1100/58310 relations classified...
  Progress: 1200/58310 relations classified...
  Progress: 1300/58310 relations classified...
  Progress: 1400/58310 relations classified...
  Progress: 1500/58310 relations classified...
  Progress: 1600/58310 relations classified...
  Progress: 1700/58310 relations classified...
  Progress: 1800/58310 relations classified...
  Progress: 1900/58310 relations classified...
  Progress: 2000/58310 relations classified...
  Progress: 2100/58310 relations classified...
  Progress: 2200/58310 relations classified...
  Progress: 2300/58310 relations classified...
  Progress: 2400/58310 relations classified...
  Progress: 2500/58310 relations classified...
  Progress: 2600/58310 relations classified...
  Progress: 2700/58310 relations classified...
  Progress: 2800/58310 relations classified...
  Progress: 2900/58310 relations classified...
  Progress: 3000/58310 relations classified...
  Progress: 3100/58310 relations classified...
  Progress: 3200/58310 relations classified...
  Progress: 3300/58310 relations classified...
  Progress: 3400/58310 relations classified...
  Progress: 3500/58310 relations classified...
  Progress: 3600/58310 relations classified...
  Progress: 3700/58310 relations classified...
  Progress: 3800/58310 relations classified...
  Progress: 3900/58310 relations classified...
  Progress: 4000/58310 relations classified...
  Progress: 4100/58310 relations classified...
  Progress: 4200/58310 relations classified...
  Progress: 4300/58310 relations classified...
  Progress: 4400/58310 relations classified...
  Progress: 4500/58310 relations classified...
  Progress: 4600/58310 relations classified...
  Progress: 4700/58310 relations classified...
  Progress: 4800/58310 relations classified...
  Progress: 4900/58310 relations classified...
  Progress: 5000/58310 relations classified...
  Progress: 5100/58310 relations classified...
  Progress: 5200/58310 relations classified...
  Progress: 5300/58310 relations classified...
  Progress: 5400/58310 relations classified...
  Progress: 5500/58310 relations classified...
  Progress: 5600/58310 relations classified...
  Progress: 5700/58310 relations classified...
  Progress: 5800/58310 relations classified...
  Progress: 5900/58310 relations classified...
  Progress: 6000/58310 relations classified...
  Progress: 6100/58310 relations classified...
  Progress: 6200/58310 relations classified...
  Progress: 6300/58310 relations classified...
  Progress: 6400/58310 relations classified...
  Progress: 6500/58310 relations classified...
  Progress: 6600/58310 relations classified...
  Progress: 6700/58310 relations classified...
  Progress: 6800/58310 relations classified...
  Progress: 6900/58310 relations classified...
  Progress: 7000/58310 relations classified...
  Progress: 7100/58310 relations classified...
  Progress: 7200/58310 relations classified...
  Progress: 7300/58310 relations classified...
  Progress: 7400/58310 relations classified...
  Progress: 7500/58310 relations classified...
  Progress: 7600/58310 relations classified...
  Progress: 7700/58310 relations classified...
  Progress: 7800/58310 relations classified...
  Progress: 7900/58310 relations classified...
  Progress: 8000/58310 relations classified...
  Progress: 8100/58310 relations classified...
  Progress: 8200/58310 relations classified...
  Progress: 8300/58310 relations classified...
  Progress: 8400/58310 relations classified...
  Progress: 8500/58310 relations classified...
  Progress: 8600/58310 relations classified...
  Progress: 8700/58310 relations classified...
  Progress: 8800/58310 relations classified...
  Progress: 8900/58310 relations classified...
  Progress: 9000/58310 relations classified...
  Progress: 9100/58310 relations classified...
  Progress: 9200/58310 relations classified...
  Progress: 9300/58310 relations classified...
  Progress: 9400/58310 relations classified...
  Progress: 9500/58310 relations classified...
  Progress: 9600/58310 relations classified...
  Progress: 9700/58310 relations classified...
  Progress: 9800/58310 relations classified...
  Progress: 9900/58310 relations classified...
  Progress: 10000/58310 relations classified...
  Progress: 10100/58310 relations classified...
  Progress: 10200/58310 relations classified...
  Progress: 10300/58310 relations classified...
  Progress: 10400/58310 relations classified...
  Progress: 10500/58310 relations classified...
  Progress: 10600/58310 relations classified...
  Progress: 10700/58310 relations classified...
  Progress: 10800/58310 relations classified...
  Progress: 10900/58310 relations classified...
  Progress: 11000/58310 relations classified...
  Progress: 11100/58310 relations classified...
  Progress: 11200/58310 relations classified...
  Progress: 11300/58310 relations classified...
  Progress: 11400/58310 relations classified...
  Progress: 11500/58310 relations classified...
  Progress: 11600/58310 relations classified...
  Progress: 11700/58310 relations classified...
  Progress: 11800/58310 relations classified...
  Progress: 11900/58310 relations classified...
  Progress: 12000/58310 relations classified...
  Progress: 12100/58310 relations classified...
  Progress: 12200/58310 relations classified...
  Progress: 12300/58310 relations classified...
  Progress: 12400/58310 relations classified...
  Progress: 12500/58310 relations classified...
  Progress: 12600/58310 relations classified...
  Progress: 12700/58310 relations classified...
  Progress: 12800/58310 relations classified...
  Progress: 12900/58310 relations classified...
  Progress: 13000/58310 relations classified...
  Progress: 13100/58310 relations classified...
  Progress: 13200/58310 relations classified...
  Progress: 13300/58310 relations classified...
  Progress: 13400/58310 relations classified...
  Progress: 13500/58310 relations classified...
  Progress: 13600/58310 relations classified...
  Progress: 13700/58310 relations classified...
  Progress: 13800/58310 relations classified...
  Progress: 13900/58310 relations classified...
  Progress: 14000/58310 relations classified...
  Progress: 14100/58310 relations classified...
  Progress: 14200/58310 relations classified...
  Progress: 14300/58310 relations classified...
  Progress: 14400/58310 relations classified...
  Progress: 14500/58310 relations classified...
  Progress: 14600/58310 relations classified...
  Progress: 14700/58310 relations classified...
  Progress: 14800/58310 relations classified...
  Progress: 14900/58310 relations classified...
  Progress: 15000/58310 relations classified...
  Progress: 15100/58310 relations classified...
  Progress: 15200/58310 relations classified...
  Progress: 15300/58310 relations classified...
  Progress: 15400/58310 relations classified...
  Progress: 15500/58310 relations classified...
  Progress: 15600/58310 relations classified...
  Progress: 15700/58310 relations classified...
  Progress: 15800/58310 relations classified...
  Progress: 15900/58310 relations classified...
  Progress: 16000/58310 relations classified...
  Progress: 16100/58310 relations classified...
  Progress: 16200/58310 relations classified...
  Progress: 16300/58310 relations classified...
  Progress: 16400/58310 relations classified...
  Progress: 16500/58310 relations classified...
  Progress: 16600/58310 relations classified...
  Progress: 16700/58310 relations classified...
  Progress: 16800/58310 relations classified...
  Progress: 16900/58310 relations classified...
  Progress: 17000/58310 relations classified...
  Progress: 17100/58310 relations classified...
  Progress: 17200/58310 relations classified...
  Progress: 17300/58310 relations classified...
  Progress: 17400/58310 relations classified...
  Progress: 17500/58310 relations classified...
  Progress: 17600/58310 relations classified...
  Progress: 17700/58310 relations classified...
  Progress: 17800/58310 relations classified...
  Progress: 17900/58310 relations classified...
  Progress: 18000/58310 relations classified...
  Progress: 18100/58310 relations classified...
  Progress: 18200/58310 relations classified...
  Progress: 18300/58310 relations classified...
  Progress: 18400/58310 relations classified...
  Progress: 18500/58310 relations classified...
  Progress: 18600/58310 relations classified...
  Progress: 18700/58310 relations classified...
  Progress: 18800/58310 relations classified...
  Progress: 18900/58310 relations classified...
  Progress: 19000/58310 relations classified...
  Progress: 19100/58310 relations classified...
  Progress: 19200/58310 relations classified...
  Progress: 19300/58310 relations classified...
  Progress: 19400/58310 relations classified...
  Progress: 19500/58310 relations classified...
  Progress: 19600/58310 relations classified...
  Progress: 19700/58310 relations classified...
  Progress: 19800/58310 relations classified...
  Progress: 19900/58310 relations classified...
  Progress: 20000/58310 relations classified...
  Progress: 20100/58310 relations classified...
  Progress: 20200/58310 relations classified...
  Progress: 20300/58310 relations classified...
  Progress: 20400/58310 relations classified...
  Progress: 20500/58310 relations classified...
  Progress: 20600/58310 relations classified...
  Progress: 20700/58310 relations classified...
  Progress: 20800/58310 relations classified...
  Progress: 20900/58310 relations classified...
  Progress: 21000/58310 relations classified...
  Progress: 21100/58310 relations classified...
  Progress: 21200/58310 relations classified...
  Progress: 21300/58310 relations classified...
  Progress: 21400/58310 relations classified...
  Progress: 21500/58310 relations classified...
  Progress: 21600/58310 relations classified...
  Progress: 21700/58310 relations classified...
  Progress: 21800/58310 relations classified...
  Progress: 21900/58310 relations classified...
  Progress: 22000/58310 relations classified...
  Progress: 22100/58310 relations classified...
  Progress: 22200/58310 relations classified...
  Progress: 22300/58310 relations classified...
  Progress: 22400/58310 relations classified...
  Progress: 22500/58310 relations classified...
  Progress: 22600/58310 relations classified...
  Progress: 22700/58310 relations classified...
  Progress: 22800/58310 relations classified...
  Progress: 22900/58310 relations classified...
  Progress: 23000/58310 relations classified...
  Progress: 23100/58310 relations classified...
  Progress: 23200/58310 relations classified...
  Progress: 23300/58310 relations classified...
  Progress: 23400/58310 relations classified...
  Progress: 23500/58310 relations classified...
  Progress: 23600/58310 relations classified...
  Progress: 23700/58310 relations classified...
  Progress: 23800/58310 relations classified...
  Progress: 23900/58310 relations classified...
  Progress: 24000/58310 relations classified...
  Progress: 24100/58310 relations classified...
  Progress: 24200/58310 relations classified...
  Progress: 24300/58310 relations classified...
  Progress: 24400/58310 relations classified...
  Progress: 24500/58310 relations classified...
  Progress: 24600/58310 relations classified...
  Progress: 24700/58310 relations classified...
  Progress: 24800/58310 relations classified...
  Progress: 24900/58310 relations classified...
  Progress: 25000/58310 relations classified...
  Progress: 25100/58310 relations classified...
  Progress: 25200/58310 relations classified...
  Progress: 25300/58310 relations classified...
  Progress: 25400/58310 relations classified...
  Progress: 25500/58310 relations classified...
  Progress: 25600/58310 relations classified...
  Progress: 25700/58310 relations classified...
  Progress: 25800/58310 relations classified...
  Progress: 25900/58310 relations classified...
  Progress: 26000/58310 relations classified...
  Progress: 26100/58310 relations classified...
  Progress: 26200/58310 relations classified...
  Progress: 26300/58310 relations classified...
  Progress: 26400/58310 relations classified...
  Progress: 26500/58310 relations classified...
  Progress: 26600/58310 relations classified...
  Progress: 26700/58310 relations classified...
  Progress: 26800/58310 relations classified...
  Progress: 26900/58310 relations classified...
  Progress: 27000/58310 relations classified...
  Progress: 27100/58310 relations classified...
  Progress: 27200/58310 relations classified...
  Progress: 27300/58310 relations classified...
  Progress: 27400/58310 relations classified...
  Progress: 27500/58310 relations classified...
  Progress: 27600/58310 relations classified...
  Progress: 27700/58310 relations classified...
  Progress: 27800/58310 relations classified...
  Progress: 27900/58310 relations classified...
  Progress: 28000/58310 relations classified...
  Progress: 28100/58310 relations classified...
  Progress: 28200/58310 relations classified...
  Progress: 28300/58310 relations classified...
  Progress: 28400/58310 relations classified...
  Progress: 28500/58310 relations classified...
  Progress: 28600/58310 relations classified...
  Progress: 28700/58310 relations classified...
  Progress: 28800/58310 relations classified...
  Progress: 28900/58310 relations classified...
  Progress: 29000/58310 relations classified...
  Progress: 29100/58310 relations classified...
  Progress: 29200/58310 relations classified...
  Progress: 29300/58310 relations classified...
  Progress: 29400/58310 relations classified...
  Progress: 29500/58310 relations classified...
  Progress: 29600/58310 relations classified...
  Progress: 29700/58310 relations classified...
  Progress: 29800/58310 relations classified...
  Progress: 29900/58310 relations classified...
  Progress: 30000/58310 relations classified...
  Progress: 30100/58310 relations classified...
  Progress: 30200/58310 relations classified...
  Progress: 30300/58310 relations classified...
  Progress: 30400/58310 relations classified...
  Progress: 30500/58310 relations classified...
  Progress: 30600/58310 relations classified...
  Progress: 30700/58310 relations classified...
  Progress: 30800/58310 relations classified...
  Progress: 30900/58310 relations classified...
  Progress: 31000/58310 relations classified...
  Progress: 31100/58310 relations classified...
  Progress: 31200/58310 relations classified...
  Progress: 31300/58310 relations classified...
  Progress: 31400/58310 relations classified...
  Progress: 31500/58310 relations classified...
  Progress: 31600/58310 relations classified...
  Progress: 31700/58310 relations classified...
  Progress: 31800/58310 relations classified...
  Progress: 31900/58310 relations classified...
  Progress: 32000/58310 relations classified...
  Progress: 32100/58310 relations classified...
  Progress: 32200/58310 relations classified...
  Progress: 32300/58310 relations classified...
  Progress: 32400/58310 relations classified...
  Progress: 32500/58310 relations classified...
  Progress: 32600/58310 relations classified...
  Progress: 32700/58310 relations classified...
  Progress: 32800/58310 relations classified...
  Progress: 32900/58310 relations classified...
  Progress: 33000/58310 relations classified...
  Progress: 33100/58310 relations classified...
  Progress: 33200/58310 relations classified...
  Progress: 33300/58310 relations classified...
  Progress: 33400/58310 relations classified...
  Progress: 33500/58310 relations classified...
  Progress: 33600/58310 relations classified...
  Progress: 33700/58310 relations classified...
  Progress: 33800/58310 relations classified...
  Progress: 33900/58310 relations classified...
  Progress: 34000/58310 relations classified...
  Progress: 34100/58310 relations classified...
  Progress: 34200/58310 relations classified...
  Progress: 34300/58310 relations classified...
  Progress: 34400/58310 relations classified...
  Progress: 34500/58310 relations classified...
  Progress: 34600/58310 relations classified...
  Progress: 34700/58310 relations classified...
  Progress: 34800/58310 relations classified...
  Progress: 34900/58310 relations classified...
  Progress: 35000/58310 relations classified...
  Progress: 35100/58310 relations classified...
  Progress: 35200/58310 relations classified...
  Progress: 35300/58310 relations classified...
  Progress: 35400/58310 relations classified...
  Progress: 35500/58310 relations classified...
  Progress: 35600/58310 relations classified...
  Progress: 35700/58310 relations classified...
  Progress: 35800/58310 relations classified...
  Progress: 35900/58310 relations classified...
  Progress: 36000/58310 relations classified...
  Progress: 36100/58310 relations classified...
  Progress: 36200/58310 relations classified...
  Progress: 36300/58310 relations classified...
  Progress: 36400/58310 relations classified...
  Progress: 36500/58310 relations classified...
  Progress: 36600/58310 relations classified...
  Progress: 36700/58310 relations classified...
  Progress: 36800/58310 relations classified...
  Progress: 36900/58310 relations classified...
  Progress: 37000/58310 relations classified...
  Progress: 37100/58310 relations classified...
  Progress: 37200/58310 relations classified...
  Progress: 37300/58310 relations classified...
  Progress: 37400/58310 relations classified...
  Progress: 37500/58310 relations classified...
  Progress: 37600/58310 relations classified...
  Progress: 37700/58310 relations classified...
  Progress: 37800/58310 relations classified...
  Progress: 37900/58310 relations classified...
  Progress: 38000/58310 relations classified...
  Progress: 38100/58310 relations classified...
  Progress: 38200/58310 relations classified...
  Progress: 38300/58310 relations classified...
  Progress: 38400/58310 relations classified...
  Progress: 38500/58310 relations classified...
  Progress: 38600/58310 relations classified...
  Progress: 38700/58310 relations classified...
  Progress: 38800/58310 relations classified...

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_flanT5,rel_robertaL,rel_deberta
20179,One of the consistent findings of the SDSN is ...,"Thus, multilateralism and investments in globa...",0_46,17_39,NaN,Support,Support,No Relationship
10052,"According to major international studies, few ...",This metric is particularly useful for assessi...,0_11,11_9,NaN,No Relationship,No Relationship,No Relationship
14156,The SDGs are woefully underfunded at home and ...,Inland fisheries are also experiencing similar...,0_31,14_2,NaN,No Relationship,No Relationship,No Relationship
48553,HICs are able to mobilize vast financial resou...,Regional cooperation and sustainable developme...,10_9,17_20,NaN,Support,Support,No Relationship
11458,Further investment is needed in statistical ca...,"Moreover, regional cooperation is needed to pr...",0_9,13_25,NaN,Support,Support,No Relationship

rel_deberta
No Relationship    57952
Attack               251
Rephrase              94
Support               13
Name: count, dtype: int64

#### Deepseek r1 70B extraction

In [12]:
prefix = "intra_goalGLOBAL_SGD2023_deepseek-r1-70b"   

args_classified = classify_relationships_deberta(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_deberta"].value_counts()

Using MAX_LENGTH = 235

Processing: /kaggle/working/TFM/Data/Relationships Keywords/intra_goalGLOBAL_SGD2023_deepseek-r1-70b.csv
Sample predictions (first 5):

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Despite this alarming development, the SDGs are still achievable.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: The world is off track, but that is all the more reason to double down on the SDGs.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: All countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national SDG strategies and commit to strengthening multilateralism.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: Further investment is needed in statistical capacity and data literacy to support long-term pathways for key SDG transformations.
  Label: No Relationship

  Progress: 100/6537 relations classified...
  Progress: 200/6537 relations classified...
  Progress: 300/6537 relations classified...
  Progress: 400/6537 relations classified...
  Progress: 500/6537 relations classified...
  Progress: 600/6537 relations classified...
  Progress: 700/6537 relations classified...
  Progress: 800/6537 relations classified...
  Progress: 900/6537 relations classified...
  Progress: 1000/6537 relations classified...
  Progress: 1100/6537 relations classified...
  Progress: 1200/6537 relations classified...
  Progress: 1300/6537 relations classified...
  Progress: 1400/6537 relations classified...
  Progress: 1500/6537 relations classified...
  Progress: 1600/6537 relations classified...
  Progress: 1700/6537 relations classified...
  Progress: 1800/6537 relations classified...
  Progress: 1900/6537 relations classified...
  Progress: 2000/6537 relations classified...
  Progress: 2100/6537 relations classified...
  Progress: 2200/6537 relations classified...
  Progress: 2300/6537 relations classified...
  Progress: 2400/6537 relations classified...
  Progress: 2500/6537 relations classified...
  Progress: 2600/6537 relations classified...
  Progress: 2700/6537 relations classified...
  Progress: 2800/6537 relations classified...
  Progress: 2900/6537 relations classified...
  Progress: 3000/6537 relations classified...
  Progress: 3100/6537 relations classified...
  Progress: 3200/6537 relations classified...
  Progress: 3300/6537 relations classified...
  Progress: 3400/6537 relations classified...
  Progress: 3500/6537 relations classified...
  Progress: 3600/6537 relations classified...
  Progress: 3700/6537 relations classified...
  Progress: 3800/6537 relations classified...
  Progress: 3900/6537 relations classified...
  Progress: 4000/6537 relations classified...
  Progress: 4100/6537 relations classified...
  Progress: 4200/6537 relations classified...
  Progress: 4300/6537 relations classified...
  Progress: 4400/6537 relations classified...
  Progress: 4500/6537 relations classified...
  Progress: 4600/6537 relations classified...
  Progress: 4700/6537 relations classified...
  Progress: 4800/6537 relations classified...
  Progress: 4900/6537 relations classified...
  Progress: 5000/6537 relations classified...
  Progress: 5100/6537 relations classified...
  Progress: 5200/6537 relations classified...
  Progress: 5300/6537 relations classified...
  Progress: 5400/6537 relations classified...
  Progress: 5500/6537 relations classified...
  Progress: 5600/6537 relations classified...
  Progress: 5700/6537 relations classified...
  Progress: 5800/6537 relations classified...
  Progress: 5900/6537 relations classified...
  Progress: 6000/6537 relations classified...
  Progress: 6100/6537 relations classified...
  Progress: 6200/6537 relations classified...
  Progress: 6300/6537 relations classified...
  Progress: 6400/6537 relations classified...
  Progress: 6500/6537 relations classified...
  Progress: 6537/6537 relations classified...
Saved: /kaggle/working/TFM/Data/Relationships Keywords/intra_goalGLOBAL_SGD2023_deepseek-r1-70b.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_flanT5,rel_robertaL,rel_deberta
4409,"societal polarization, populism, and growing g...","To reduce inequalities, governments also need ...",10_2,10_20,NaN,Support,Support,No Relationship
1880,Dire shortfalls in meeting the SDGs,The SDGs are not only a public policy framewor...,0_26,0_74,NaN,Support,Support,No Relationship
1956,None of their objectives are beyond our reach....,Most of the low-income and lower-middle income...,0_28,0_39,NaN,Support,Support,No Relationship
2909,Our special emphasis is on pathway analysis to...,The SDGs require long-term directed change and...,0_49,0_68,NaN,No Relationship,Support,No Relationship
1242,Current geopolitical tensions are hindering SD...,The urgent objective of the SDG Stimulus is to...,0_16,0_51,NaN,Support,Support,No Relationship

rel_deberta
No Relationship    6408
Attack              112
Support              15
Rephrase              2
Name: count, dtype: int64

In [13]:
prefix = "cross_goalGLOBAL_SGD2023_deepseek-r1-70b"   

args_classified = classify_relationships_deberta(process_rel_path, prefix)
display(args_classified.sample(5))

args_classified["rel_deberta"].value_counts()

Using MAX_LENGTH = 255

Processing: /kaggle/working/TFM/Data/Relationships Keywords/cross_goalGLOBAL_SGD2023_deepseek-r1-70b.csv
Sample predictions (first 5):

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: The grim reality is that at the midpoint of the 2030 Agenda, the SDGs are far off track.
  Label: Support

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: At the global level, averaging across countries, not a single SDG is currently projected to be met by 2030, with the poorest countries struggling the most.
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: 1. Increased funding from the multilateral develop-ment banks (MDBs) and public development banks (PDBs) to low- and middle-income countries, linked to investments in the SDGs;
  Label: Attack

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: 2. Enhancement of relief for countries facing debt distress;
  Label: No Relationship

- Arg1: At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.
- Arg2: 1. Greatly increased funding for national and subnational governments and private businesses in the emerging economies, especially the low-income countries (LICs) and lower-middle-income countries (LMICs), to carry out needed SDG actions;
  Label: No Relationship

  Progress: 100/60991 relations classified...
  Progress: 200/60991 relations classified...
  Progress: 300/60991 relations classified...
  Progress: 400/60991 relations classified...
  Progress: 500/60991 relations classified...
  Progress: 600/60991 relations classified...
  Progress: 700/60991 relations classified...
  Progress: 800/60991 relations classified...
  Progress: 900/60991 relations classified...
  Progress: 1000/60991 relations classified...
  Progress: 1100/60991 relations classified...
  Progress: 1200/60991 relations classified...
  Progress: 1300/60991 relations classified...
  Progress: 1400/60991 relations classified...
  Progress: 1500/60991 relations classified...
  Progress: 1600/60991 relations classified...
  Progress: 1700/60991 relations classified...
  Progress: 1800/60991 relations classified...
  Progress: 1900/60991 relations classified...
  Progress: 2000/60991 relations classified...
  Progress: 2100/60991 relations classified...
  Progress: 2200/60991 relations classified...
  Progress: 2300/60991 relations classified...
  Progress: 2400/60991 relations classified...
  Progress: 2500/60991 relations classified...
  Progress: 2600/60991 relations classified...
  Progress: 2700/60991 relations classified...
  Progress: 2800/60991 relations classified...
  Progress: 2900/60991 relations classified...
  Progress: 3000/60991 relations classified...
  Progress: 3100/60991 relations classified...
  Progress: 3200/60991 relations classified...
  Progress: 3300/60991 relations classified...
  Progress: 3400/60991 relations classified...
  Progress: 3500/60991 relations classified...
  Progress: 3600/60991 relations classified...
  Progress: 3700/60991 relations classified...
  Progress: 3800/60991 relations classified...
  Progress: 3900/60991 relations classified...
  Progress: 4000/60991 relations classified...
  Progress: 4100/60991 relations classified...
  Progress: 4200/60991 relations classified...
  Progress: 4300/60991 relations classified...
  Progress: 4400/60991 relations classified...
  Progress: 4500/60991 relations classified...
  Progress: 4600/60991 relations classified...
  Progress: 4700/60991 relations classified...
  Progress: 4800/60991 relations classified...
  Progress: 4900/60991 relations classified...
  Progress: 5000/60991 relations classified...
  Progress: 5100/60991 relations classified...
  Progress: 5200/60991 relations classified...
  Progress: 5300/60991 relations classified...
  Progress: 5400/60991 relations classified...
  Progress: 5500/60991 relations classified...
  Progress: 5600/60991 relations classified...
  Progress: 5700/60991 relations classified...
  Progress: 5800/60991 relations classified...
  Progress: 5900/60991 relations classified...
  Progress: 6000/60991 relations classified...
  Progress: 6100/60991 relations classified...
  Progress: 6200/60991 relations classified...
  Progress: 6300/60991 relations classified...
  Progress: 6400/60991 relations classified...
  Progress: 6500/60991 relations classified...
  Progress: 6600/60991 relations classified...
  Progress: 6700/60991 relations classified...
  Progress: 6800/60991 relations classified...
  Progress: 6900/60991 relations classified...
  Progress: 7000/60991 relations classified...
  Progress: 7100/60991 relations classified...
  Progress: 7200/60991 relations classified...
  Progress: 7300/60991 relations classified...
  Progress: 7400/60991 relations classified...
  Progress: 7500/60991 relations classified...
  Progress: 7600/60991 relations classified...
  Progress: 7700/60991 relations classified...
  Progress: 7800/60991 relations classified...
  Progress: 7900/60991 relations classified...
  Progress: 8000/60991 relations classified...
  Progress: 8100/60991 relations classified...
  Progress: 8200/60991 relations classified...
  Progress: 8300/60991 relations classified...
  Progress: 8400/60991 relations classified...
  Progress: 8500/60991 relations classified...
  Progress: 8600/60991 relations classified...
  Progress: 8700/60991 relations classified...
  Progress: 8800/60991 relations classified...
  Progress: 8900/60991 relations classified...
  Progress: 9000/60991 relations classified...
  Progress: 9100/60991 relations classified...
  Progress: 9200/60991 relations classified...
  Progress: 9300/60991 relations classified...
  Progress: 9400/60991 relations classified...
  Progress: 9500/60991 relations classified...
  Progress: 9600/60991 relations classified...
  Progress: 9700/60991 relations classified...
  Progress: 9800/60991 relations classified...
  Progress: 9900/60991 relations classified...
  Progress: 10000/60991 relations classified...
  Progress: 10100/60991 relations classified...
  Progress: 10200/60991 relations classified...
  Progress: 10300/60991 relations classified...
  Progress: 10400/60991 relations classified...
  Progress: 10500/60991 relations classified...
  Progress: 10600/60991 relations classified...
  Progress: 10700/60991 relations classified...
  Progress: 10800/60991 relations classified...
  Progress: 10900/60991 relations classified...
  Progress: 11000/60991 relations classified...
  Progress: 11100/60991 relations classified...
  Progress: 11200/60991 relations classified...
  Progress: 11300/60991 relations classified...
  Progress: 11400/60991 relations classified...
  Progress: 11500/60991 relations classified...
  Progress: 11600/60991 relations classified...
  Progress: 11700/60991 relations classified...
  Progress: 11800/60991 relations classified...
  Progress: 11900/60991 relations classified...
  Progress: 12000/60991 relations classified...
  Progress: 12100/60991 relations classified...
  Progress: 12200/60991 relations classified...
  Progress: 12300/60991 relations classified...
  Progress: 12400/60991 relations classified...
  Progress: 12500/60991 relations classified...
  Progress: 12600/60991 relations classified...
  Progress: 12700/60991 relations classified...
  Progress: 12800/60991 relations classified...
  Progress: 12900/60991 relations classified...
  Progress: 13000/60991 relations classified...
  Progress: 13100/60991 relations classified...
  Progress: 13200/60991 relations classified...
  Progress: 13300/60991 relations classified...
  Progress: 13400/60991 relations classified...
  Progress: 13500/60991 relations classified...
  Progress: 13600/60991 relations classified...
  Progress: 13700/60991 relations classified...
  Progress: 13800/60991 relations classified...
  Progress: 13900/60991 relations classified...
  Progress: 14000/60991 relations classified...
  Progress: 14100/60991 relations classified...
  Progress: 14200/60991 relations classified...
  Progress: 14300/60991 relations classified...
  Progress: 14400/60991 relations classified...
  Progress: 14500/60991 relations classified...
  Progress: 14600/60991 relations classified...
  Progress: 14700/60991 relations classified...
  Progress: 14800/60991 relations classified...
  Progress: 14900/60991 relations classified...
  Progress: 15000/60991 relations classified...
  Progress: 15100/60991 relations classified...
  Progress: 15200/60991 relations classified...
  Progress: 15300/60991 relations classified...
  Progress: 15400/60991 relations classified...
  Progress: 15500/60991 relations classified...
  Progress: 15600/60991 relations classified...
  Progress: 15700/60991 relations classified...
  Progress: 15800/60991 relations classified...
  Progress: 15900/60991 relations classified...
  Progress: 16000/60991 relations classified...
  Progress: 16100/60991 relations classified...
  Progress: 16200/60991 relations classified...
  Progress: 16300/60991 relations classified...
  Progress: 16400/60991 relations classified...
  Progress: 16500/60991 relations classified...
  Progress: 16600/60991 relations classified...
  Progress: 16700/60991 relations classified...
  Progress: 16800/60991 relations classified...
  Progress: 16900/60991 relations classified...
  Progress: 17000/60991 relations classified...
  Progress: 17100/60991 relations classified...
  Progress: 17200/60991 relations classified...
  Progress: 17300/60991 relations classified...
  Progress: 17400/60991 relations classified...
  Progress: 17500/60991 relations classified...
  Progress: 17600/60991 relations classified...
  Progress: 17700/60991 relations classified...
  Progress: 17800/60991 relations classified...
  Progress: 17900/60991 relations classified...
  Progress: 18000/60991 relations classified...
  Progress: 18100/60991 relations classified...
  Progress: 18200/60991 relations classified...
  Progress: 18300/60991 relations classified...
  Progress: 18400/60991 relations classified...
  Progress: 18500/60991 relations classified...
  Progress: 18600/60991 relations classified...
  Progress: 18700/60991 relations classified...
  Progress: 18800/60991 relations classified...
  Progress: 18900/60991 relations classified...
  Progress: 19000/60991 relations classified...
  Progress: 19100/60991 relations classified...
  Progress: 19200/60991 relations classified...
  Progress: 19300/60991 relations classified...
  Progress: 19400/60991 relations classified...
  Progress: 19500/60991 relations classified...
  Progress: 19600/60991 relations classified...
  Progress: 19700/60991 relations classified...
  Progress: 19800/60991 relations classified...
  Progress: 19900/60991 relations classified...
  Progress: 20000/60991 relations classified...
  Progress: 20100/60991 relations classified...
  Progress: 20200/60991 relations classified...
  Progress: 20300/60991 relations classified...
  Progress: 20400/60991 relations classified...
  Progress: 20500/60991 relations classified...
  Progress: 20600/60991 relations classified...
  Progress: 20700/60991 relations classified...
  Progress: 20800/60991 relations classified...
  Progress: 20900/60991 relations classified...
  Progress: 21000/60991 relations classified...
  Progress: 21100/60991 relations classified...
  Progress: 21200/60991 relations classified...
  Progress: 21300/60991 relations classified...
  Progress: 21400/60991 relations classified...
  Progress: 21500/60991 relations classified...
  Progress: 21600/60991 relations classified...
  Progress: 21700/60991 relations classified...
  Progress: 21800/60991 relations classified...
  Progress: 21900/60991 relations classified...
  Progress: 22000/60991 relations classified...
  Progress: 22100/60991 relations classified...
  Progress: 22200/60991 relations classified...
  Progress: 22300/60991 relations classified...
  Progress: 22400/60991 relations classified...
  Progress: 22500/60991 relations classified...
  Progress: 22600/60991 relations classified...
  Progress: 22700/60991 relations classified...
  Progress: 22800/60991 relations classified...
  Progress: 22900/60991 relations classified...
  Progress: 23000/60991 relations classified...
  Progress: 23100/60991 relations classified...
  Progress: 23200/60991 relations classified...
  Progress: 23300/60991 relations classified...
  Progress: 23400/60991 relations classified...
  Progress: 23500/60991 relations classified...
  Progress: 23600/60991 relations classified...
  Progress: 23700/60991 relations classified...
  Progress: 23800/60991 relations classified...
  Progress: 23900/60991 relations classified...
  Progress: 24000/60991 relations classified...
  Progress: 24100/60991 relations classified...
  Progress: 24200/60991 relations classified...
  Progress: 24300/60991 relations classified...
  Progress: 24400/60991 relations classified...
  Progress: 24500/60991 relations classified...
  Progress: 24600/60991 relations classified...
  Progress: 24700/60991 relations classified...
  Progress: 24800/60991 relations classified...
  Progress: 24900/60991 relations classified...
  Progress: 25000/60991 relations classified...
  Progress: 25100/60991 relations classified...
  Progress: 25200/60991 relations classified...
  Progress: 25300/60991 relations classified...
  Progress: 25400/60991 relations classified...
  Progress: 25500/60991 relations classified...
  Progress: 25600/60991 relations classified...
  Progress: 25700/60991 relations classified...
  Progress: 25800/60991 relations classified...
  Progress: 25900/60991 relations classified...
  Progress: 26000/60991 relations classified...
  Progress: 26100/60991 relations classified...
  Progress: 26200/60991 relations classified...
  Progress: 26300/60991 relations classified...
  Progress: 26400/60991 relations classified...
  Progress: 26500/60991 relations classified...
  Progress: 26600/60991 relations classified...
  Progress: 26700/60991 relations classified...
  Progress: 26800/60991 relations classified...
  Progress: 26900/60991 relations classified...
  Progress: 27000/60991 relations classified...
  Progress: 27100/60991 relations classified...
  Progress: 27200/60991 relations classified...
  Progress: 27300/60991 relations classified...
  Progress: 27400/60991 relations classified...
  Progress: 27500/60991 relations classified...
  Progress: 27600/60991 relations classified...
  Progress: 27700/60991 relations classified...
  Progress: 27800/60991 relations classified...
  Progress: 27900/60991 relations classified...
  Progress: 28000/60991 relations classified...
  Progress: 28100/60991 relations classified...
  Progress: 28200/60991 relations classified...
  Progress: 28300/60991 relations classified...
  Progress: 28400/60991 relations classified...
  Progress: 28500/60991 relations classified...
  Progress: 28600/60991 relations classified...
  Progress: 28700/60991 relations classified...
  Progress: 28800/60991 relations classified...
  Progress: 28900/60991 relations classified...
  Progress: 29000/60991 relations classified...
  Progress: 29100/60991 relations classified...
  Progress: 29200/60991 relations classified...
  Progress: 29300/60991 relations classified...
  Progress: 29400/60991 relations classified...
  Progress: 29500/60991 relations classified...
  Progress: 29600/60991 relations classified...
  Progress: 29700/60991 relations classified...
  Progress: 29800/60991 relations classified...
  Progress: 29900/60991 relations classified...
  Progress: 30000/60991 relations classified...
  Progress: 30100/60991 relations classified...
  Progress: 30200/60991 relations classified...
  Progress: 30300/60991 relations classified...
  Progress: 30400/60991 relations classified...
  Progress: 30500/60991 relations classified...
  Progress: 30600/60991 relations classified...
  Progress: 30700/60991 relations classified...
  Progress: 30800/60991 relations classified...
  Progress: 30900/60991 relations classified...
  Progress: 31000/60991 relations classified...
  Progress: 31100/60991 relations classified...
  Progress: 31200/60991 relations classified...
  Progress: 31300/60991 relations classified...
  Progress: 31400/60991 relations classified...
  Progress: 31500/60991 relations classified...
  Progress: 31600/60991 relations classified...
  Progress: 31700/60991 relations classified...
  Progress: 31800/60991 relations classified...
  Progress: 31900/60991 relations classified...
  Progress: 32000/60991 relations classified...
  Progress: 32100/60991 relations classified...
  Progress: 32200/60991 relations classified...
  Progress: 32300/60991 relations classified...
  Progress: 32400/60991 relations classified...
  Progress: 32500/60991 relations classified...
  Progress: 32600/60991 relations classified...
  Progress: 32700/60991 relations classified...
  Progress: 32800/60991 relations classified...
  Progress: 32900/60991 relations classified...
  Progress: 33000/60991 relations classified...
  Progress: 33100/60991 relations classified...
  Progress: 33200/60991 relations classified...
  Progress: 33300/60991 relations classified...
  Progress: 33400/60991 relations classified...
  Progress: 33500/60991 relations classified...
  Progress: 33600/60991 relations classified...
  Progress: 33700/60991 relations classified...
  Progress: 33800/60991 relations classified...
  Progress: 33900/60991 relations classified...
  Progress: 34000/60991 relations classified...
  Progress: 34100/60991 relations classified...
  Progress: 34200/60991 relations classified...
  Progress: 34300/60991 relations classified...
  Progress: 34400/60991 relations classified...
  Progress: 34500/60991 relations classified...
  Progress: 34600/60991 relations classified...
  Progress: 34700/60991 relations classified...
  Progress: 34800/60991 relations classified...
  Progress: 34900/60991 relations classified...
  Progress: 35000/60991 relations classified...
  Progress: 35100/60991 relations classified...
  Progress: 35200/60991 relations classified...
  Progress: 35300/60991 relations classified...
  Progress: 35400/60991 relations classified...
  Progress: 35500/60991 relations classified...
  Progress: 35600/60991 relations classified...
  Progress: 35700/60991 relations classified...
  Progress: 35800/60991 relations classified...
  Progress: 35900/60991 relations classified...
  Progress: 36000/60991 relations classified...
  Progress: 36100/60991 relations classified...
  Progress: 36200/60991 relations classified...
  Progress: 36300/60991 relations classified...
  Progress: 36400/60991 relations classified...
  Progress: 36500/60991 relations classified...
  Progress: 36600/60991 relations classified...
  Progress: 36700/60991 relations classified...
  Progress: 36800/60991 relations classified...
  Progress: 36900/60991 relations classified...
  Progress: 37000/60991 relations classified...
  Progress: 37100/60991 relations classified...
  Progress: 37200/60991 relations classified...
  Progress: 37300/60991 relations classified...
  Progress: 37400/60991 relations classified...
  Progress: 37500/60991 relations classified...
  Progress: 37600/60991 relations classified...
  Progress: 37700/60991 relations classified...
  Progress: 37800/60991 relations classified...
  Progress: 37900/60991 relations classified...
  Progress: 38000/60991 relations classified...
  Progress: 38100/60991 relations classified...
  Progress: 38200/60991 relations classified...
  Progress: 38300/60991 relations classified...
  Progress: 38400/60991 relations classified...
  Progress: 38500/60991 relations classified...
  Progress: 38600/60991 relations classified...
  Progress: 38700/60991 relations classified...
  Progress: 38800/60991 relations classified...

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,SDGarg1,SDGarg2,id_arg1,id_arg2,rel,rel_flanT5,rel_robertaL,rel_deberta
47162,Governments generally finance basic scientific...,UNEP estimates that 84 percent of Parties to t...,9_3,13_22,NaN,Support,No Relationship,No Relationship
12744,Greatly increased funding for national and sub...,"The European Green Deal (EGD), which is exempl...",0_11,12_1,NaN,Support,Support,No Relationship
47169,The Horizon Europe program and EU Missions in ...,Even taking the net-zero pledges of many count...,9_4,13_5,NaN,No Relationship,No Relationship,No Relationship
50532,LICs and LMICs score more highly on political ...,"According to IMF estimates in 2019, the financ...",10_22,13_16,NaN,Support,Support,No Relationship
25407,Peace and global cooperation mean nothing less...,Each requires a financing strategy to underpin...,1_12,8_9,NaN,No Relationship,No Relationship,No Relationship

rel_deberta
No Relationship    60434
Attack               381
Rephrase             121
Support               55
Name: count, dtype: int64