# Generate unified .json with all extracted arguments 

- Clean duplicated arguments 
- Display summary statistics per SDG (totals/means, duplicates removed totals/means)
- Display summary statistics (same metrics over the whole set)

In [1]:
import os, re, json
from collections import OrderedDict
import pandas as pd
from typing import List, Optional, Tuple
import csv
import itertools

def process_sdg_runs(
    input_dir, output_dir, output_dir_stats,
    prefix,
    model_name,
    ods_range=(0, 17),
    unified_basename=None,
    interactive=True   # allow disabling manual review
):

    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(output_dir_stats, exist_ok=True)

    # 1. match files of interest
    model_part = re.escape(model_name) if model_name else r".+?"
    pattern = re.compile(rf"^{re.escape(prefix)}_ArgsSGD(\d+)_({model_part})\.json$")

    files = []
    for fn in os.listdir(input_dir):
        m = pattern.match(fn)
        if not m:
            continue
        ods_num = int(m.group(1))
        if ods_num < ods_range[0] or ods_num > ods_range[1]:
            continue
        files.append((ods_num, fn))

    if not files:
        raise FileNotFoundError(f"No files found in '{input_dir}' for prefix='{prefix}'"
                                + (f" and model='{model_name}'" if model_name else ""))

    # 2. Process per ODS (each .json file)
    files.sort(key=lambda x: (x[0], x[1]))

    unified_records = []
    per_sdg_stats = []

    for ods_num, fn in files:
        path = os.path.join(input_dir, fn)
        with open(path, "r", encoding="utf-8") as f:
            pages = json.load(f)

        seen_args = OrderedDict()
        not_valid_args = set()

        # Per-page stats
        page_counts_kept = []
        page_counts_removed = []
        page_counts_original = []
        page_counts_not_valid = []

        for item in pages:
            page = item.get("page")
            section = item.get("section")
            args: List[str] = item.get("arguments", []) or []

            def unique_in_order(seq):
                seen = set()
                out = []
                for s in seq:
                    if s not in seen:
                        out.append(s)
                        seen.add(s)
                return out

            args_original_unique = unique_in_order(args)
            page_original = len(args_original_unique)

            kept_args = []
            removed_here = 0
            not_valid_here = 0

            for a in args_original_unique:
                if a not in seen_args:
                    # manual revision
                    if interactive:
                        print(f"\n[ODS {ods_num} | page {page}] Argument candidate:\n  {a}")
                        resp = input("Keep this argument? (1=yes, 0=no): ").strip()
                        if resp == "0":
                            not_valid_args.add(a)
                            not_valid_here += 1
                            continue
                    kept_args.append(a)
                    seen_args[a] = True
                else:
                    removed_here += 1

            unified_records.append({
                "ods": ods_num,
                "page": page,
                "section": section,
                "arguments": kept_args,
                "source_file": fn,
            })

            page_counts_original.append(page_original)
            page_counts_kept.append(len(kept_args))
            page_counts_removed.append(removed_here)
            page_counts_not_valid.append(not_valid_here)

        # Per-SDG summary row
        pages_count = len(pages)
        total_kept = sum(page_counts_kept)
        total_removed = sum(page_counts_removed)
        total_original = sum(page_counts_original)
        total_not_valid = sum(page_counts_not_valid)

        per_sdg_stats.append({
            "prefix": prefix.replace("_", " ").strip(),
            "model": model_name,
            "ods": ods_num,
            "pages": pages_count,
            "total_args": total_original,
            "total_args_kept": total_kept,
            "total_dupes_removed": total_removed,
            "total_not_valid_args": total_not_valid,
        })

    per_sdg_df = pd.DataFrame(per_sdg_stats).sort_values(["ods"]).reset_index(drop=True)

    if unified_basename is None:
        unified_basename = f"{prefix}_AllArgs"

    unified_json_path = os.path.join(output_dir, f"{unified_basename}_{model_name}.json")
    per_sdg_csv_path = os.path.join(output_dir_stats, f"{unified_basename}_perSDG_summary.csv")

    # Save unified JSON
    with open(unified_json_path, "w", encoding="utf-8") as f:
        json.dump(unified_records, f, indent=2, ensure_ascii=False)

    # Append stats (instead of overwrite)
    if os.path.exists(per_sdg_csv_path):
        existing = pd.read_csv(per_sdg_csv_path)
        per_sdg_df = pd.concat([existing, per_sdg_df], ignore_index=True)
    per_sdg_df.to_csv(per_sdg_csv_path, index=False, encoding="utf-8")


    print(f"\nProcessed {len(per_sdg_df)} SDGs for prefix='{prefix}', model='{model_name}'")
    print(per_sdg_df.to_string(index=False))

    return {
        "unified_json": unified_json_path,
        "per_sdg_summary_csv": per_sdg_csv_path,
        "per_sdg_summary_df": per_sdg_df,
    }

import pandas as pd
import os

def save_overall_summary(res, output_dir_stats, model_name, unified_basename="AllArgs_overall_summary"):
    df = res["per_sdg_summary_df"]
    df = df[df["model"] == model_name]

    # Compute overall metrics
    overall_row = {
        "prefix": df["prefix"].iloc[0],
        "model": df["model"].iloc[0],
        "ods_max": df["ods"].max(),
        "pages_max": df["pages"].max(),
        "total_args": df["total_args"].sum(),
        "total_args_kept": df["total_args_kept"].sum(),
        "total_dupes_removed": df["total_dupes_removed"].sum(),
        "total_not_valid_args": df["total_not_valid_args"].sum(),
    }
    overall_df = pd.DataFrame([overall_row])
    overall_csv_path = os.path.join(output_dir_stats, f"{unified_basename}.csv")

    # Append if exists
    if os.path.exists(overall_csv_path):
        existing = pd.read_csv(overall_csv_path)
        overall_df = pd.concat([existing, overall_df], ignore_index=True)

    overall_df.to_csv(overall_csv_path, index=False, encoding="utf-8")

    print("\nUpdated overall summary:")

    return overall_df

def export_arguments_txt(json_path, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    # 1. Flat list of all arguments
    all_args = []
    for item in data:
        all_args.extend(item.get("arguments", []))

    flat_txt_path = os.path.join(output_dir, os.path.basename(json_path).replace(".json", "_arguments.txt"))
    with open(flat_txt_path, "w", encoding="utf-8") as f:
        for arg in all_args:
            f.write("'" + arg.strip() + "',\n")

    # 2. Dictionary by goal (ods)
    args_by_goal = {}
    for item in data:
        ods = item.get("ods")
        if ods not in args_by_goal:
            args_by_goal[ods] = []
        args_by_goal[ods].extend(item.get("arguments", []))

    dict_txt_path = os.path.join(output_dir, os.path.basename(json_path).replace(".json", "_by_goal.txt"))
    with open(dict_txt_path, "w", encoding="utf-8") as f:
        json.dump(args_by_goal, f, indent=2, ensure_ascii=False)

    print(f"Saved:\n - Flat arguments: {flat_txt_path}\n - Grouped by goal: {dict_txt_path}")
    return flat_txt_path, dict_txt_path


def create_relationship_csvs(path_by_goal, output_dir, model_name, prefix):
    # 1. Load arguments by goal
    with open(path_by_goal, "r", encoding="utf-8") as f:
        args_by_goal = json.load(f)

    os.makedirs(output_dir, exist_ok=True)

    # 2. Map args to unique IDs
    id_map = {}
    for goal, args in args_by_goal.items():
        for i, arg in enumerate(args):
            id_map[(goal, i)] = f"{goal}_{i}"

    intra_rows = []
    cross_rows = []

    # 3. Intra-goal relationships
    for goal, args in args_by_goal.items():
        for i, j in itertools.combinations(range(len(args)), 2):
            arg1, arg2 = args[i], args[j]
            id1, id2 = id_map[(goal, i)], id_map[(goal, j)]
            intra_rows.append([arg1, arg2, id1, id2, ""])

    # 4. Inter-goal relationships
    goals = list(args_by_goal.keys())
    for g1_idx in range(len(goals)):
        for g2_idx in range(g1_idx + 1, len(goals)):
            g1, g2 = goals[g1_idx], goals[g2_idx]
            for i, arg1 in enumerate(args_by_goal[g1]):
                for j, arg2 in enumerate(args_by_goal[g2]):
                    id1, id2 = id_map[(g1, i)], id_map[(g2, j)]
                    cross_rows.append([arg1, arg2, id1, id2, ""])

    # 5. Save CSVs
    intra_path = os.path.join(output_dir, "intra_goal" + prefix + model_name + ".csv")
    with open(intra_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["SDGarg1", "SDGarg2", "id_arg1", "id_arg2", "rel"])
        writer.writerows(intra_rows)

    cross_path = os.path.join(output_dir, "cross_goal" + prefix + model_name + ".csv")
    with open(cross_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["SDGarg1", "SDGarg2", "id_arg1", "id_arg2", "rel"])
        writer.writerows(cross_rows)

    print(f"Relationships intra-goal: {len(intra_rows)}")
    print(f"Relationships cross-goal: {len(cross_rows)}")

    return intra_path, cross_path

In [2]:
path_extracted_data = "..\\Data\\Extracted Arguments No Keywords (all text)\\"
path_output = "..\\Data\\Processed Arguments No Keywords\\"
path_output_stats = "..\\Data\\Processed Arguments No Keywords\\Stats\\"
path_output_txt = "..\\Data\\Processed Arguments No Keywords\\Args\\"
path_output_rels = "..\\Data\\Relationships No Keywords\\"

## GLOBAL SDG 2023 report

### Qwen2.5-3b

In [ ]:
prefix = 'GLOBAL_SGD2023_'
model_name="qwen2.5-3b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')

display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

Stats by SDG for qwen2.5-3b in document GLOBAL_SGD2023_:

,prefix,model,ods,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,0,53,42,32,0,10
1,GLOBAL SGD2023,qwen2.5-3b,1,53,21,9,0,12
2,GLOBAL SGD2023,qwen2.5-3b,2,53,14,2,0,12
3,GLOBAL SGD2023,qwen2.5-3b,3,53,17,12,0,5
4,GLOBAL SGD2023,qwen2.5-3b,4,53,16,5,0,11
5,GLOBAL SGD2023,qwen2.5-3b,5,53,10,2,0,8
6,GLOBAL SGD2023,qwen2.5-3b,6,53,11,7,0,4
7,GLOBAL SGD2023,qwen2.5-3b,7,53,15,10,0,5
8,GLOBAL SGD2023,qwen2.5-3b,8,53,12,9,0,3
9,GLOBAL SGD2023,qwen2.5-3b,9,53,7,4,0,3
10,GLOBAL SGD2023,qwen2.5-3b,10,53,19,13,0,6
11,GLOBAL SGD2023,qwen2.5-3b,11,53,10,8,0,2
12,GLOBAL SGD2023,qwen2.5-3b,12,53,11,10,0,1
13,GLOBAL SGD2023,qwen2.5-3b,13,53,10,9,0,1
14,GLOBAL SGD2023,qwen2.5-3b,14,53,4,3,0,1
15,GLOBAL SGD2023,qwen2.5-3b,15,53,1,1,0,0
16,GLOBAL SGD2023,qwen2.5-3b,16,53,14,10,0,4
17,GLOBAL SGD2023,qwen2.5-3b,17,53,17,15,0,2

Stats overall for qwen2.5-3b in document GLOBAL_SGD2023_:

Updated overall summary:

,prefix,model,ods_max,pages_max,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,17,53,251,161,0,90

### Gemma3 4B

In [ ]:
prefix = 'GLOBAL_SGD2023_'
model_name="gemma3-4b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')

display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

[ODS 0 | page 7] Argument candidate:
  At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.

[ODS 0 | page 7] Argument candidate:
  None of their objectives are beyond our reach.

[ODS 0 | page 7] Argument candidate:
  The SDGs are still achievable.

[ODS 0 | page 7] Argument candidate:
  It is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.

[ODS 0 | page 7] Argument candidate:
  To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.

[ODS 0 | page 7] Argument candidate:
  The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 7] Argument candidate:
  Greatly increase funding to national and subnational governments and private businesses, especially in LICs and LMICs, to carry out needed SDG investments.

[ODS 0 | page 7] Argument candidate:
  Revise the credit rating system and debt sustainability metrics to facilitate long-term sustainable development.

[ODS 0 | page 7] Argument candidate:
  Revise liquidity structures for LICs and LMICs, especially regarding sovereign debts, to forestall self-fulfilling banking and balance-of-payments crises

[ODS 0 | page 7] Argument candidate:
  Create ambitious, internationally-agreed upon criteria for sustainable finance that are mandatory for all public financial institutions.

[ODS 0 | page 7] Argument candidate:
  Align private business investment flows with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 7] Argument candidate:
  Reform current institutional frameworks and develop new mechanisms to improve the quality and speed of deployment of international cooperation, and monitor progress in an open and timely manner.

[ODS 0 | page 7] Argument candidate:
  All countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national SDG strategies and commit to strengthening multilateralism.

[ODS 0 | page 7] Argument candidate:
  National governments must ensure both domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation – by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 7] Argument candidate:
  Achieving the SDGs requires global cooperation guided by the United Nations Charter.

[ODS 0 | page 8] Argument candidate:
  Further investment is needed in statistical capacity and data literacy to support long-term pathways for key SDG transformations.

[ODS 0 | page 8] Argument candidate:
  At the halfway mark to 2030, there remains a great deal of work to be done to improve the data and methods underlying the SDG indicator framework.

[ODS 0 | page 8] Argument candidate:
  investing in statistical capacity, science, and data literacy are important priorities for achieving the SDGs.

[ODS 0 | page 8] Argument candidate:
  All UN Member States and UN agencies can count on the continued efforts and energies of the SDSN around the world to support all governments, businesses, and civil society in embracing and aligning with the SDGs

[ODS 0 | page 13] Argument candidate:
  UN Member States should adopt an SDG Stimulus, to close the massive financing gap faced by many developing economies.

[ODS 0 | page 13] Argument candidate:
  Increased funding from the multilateral development banks (MDBs) and public development banks (PDBs) to low- and middle-income countries, linked to investments in the SDGs;

[ODS 0 | page 13] Argument candidate:
  Enhancement of relief for countries facing debt distress;

[ODS 0 | page 13] Argument candidate:
  Expansion of liquidity by the International Monetary Fund (IMF) and major central banks;

[ODS 0 | page 13] Argument candidate:
  Empowerment and expansion of the specialized global funds;

[ODS 0 | page 13] Argument candidate:
  Expansion of private philanthropy with a focus on ultra-high-net-worth individuals.

[ODS 0 | page 13] Argument candidate:
  UN Member States must endorse a deep and overdue reform of the global financial architecture.

[ODS 0 | page 13] Argument candidate:
  Greatly increased funding for national and subnational governments and private businesses in the emerging economies, especially the low-income countries (LICs) and lower-middle-income countries (LMICs), to carry out needed SDG actions;

[ODS 0 | page 13] Argument candidate:
  Revision of the credit-rating system and debt-sustainability metrics to facilitate long-term sustainable development;

[ODS 0 | page 13] Argument candidate:
  Revision of the liquidity structures for LICs and LMICs, especially regarding sovereign debt, to forestall self-fulfilling banking and balance-of-payments crises;

[ODS 0 | page 13] Argument candidate:
  Creation of ambitious, internationally-agreed criteria for sustainable finance that are mandatory for all public financial institutions in high-income countries (HICs), middle-income countries (MICs), and LICs alike.

[ODS 0 | page 13] Argument candidate:
  Alignment of private business investment flows in all countries with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 13] Argument candidate:
  A reform of current institutional frameworks and development of new and innovative mechanisms to improve the quality and speed of deployment of international cooperation, and the monitoring of progress in an open and timely manner.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of ‘leave no one behind’.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should present, at regular intervals, their national SDG frameworks in the form of Voluntary National Reviews (VNRs).

[ODS 0 | page 14] Argument candidate:
  All UN Member States should recommit to peaceful cooperation, in the service of the SDGs and all other multilateral agreements.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should commit to accelerating SDG progress to 2030, and to setting even more ambitious SDG targets to 2050, incorporating the recent Kunming-Montreal Biodiversity Framework and the High Seas Treaty.

[ODS 0 | page 15] Argument candidate:
  national governments on all continents have fallen short in integrating the SDGs into national policies and public investments

[ODS 0 | page 15] Argument candidate:
  they are grounded in the Universal Declaration of Human Rights, which celebrates its 75th anniversary this year

[ODS 0 | page 15] Argument candidate:
  that "All human beings are born free and equal in dignity and rights … and should act towards one another in a spirit of brotherhood"

[ODS 0 | page 15] Argument candidate:
  that "it is essential to promote the development of friendly relations between nations"

[ODS 0 | page 15] Argument candidate:
  social justice and sustainable development require the full realization of the rights of all people

[ODS 0 | page 15] Argument candidate:
  includes equality of opportunities for girls and women (SDG 5)

[ODS 0 | page 15] Argument candidate:
  respect for the rights and voice of Indigenous peoples around the world

[ODS 0 | page 15] Argument candidate:
  a much larger role for young people, who will face the consequences of our (in)actions throughout the 21st century

[ODS 0 | page 15] Argument candidate:
  They are not only a public policy framework; they are an ethical imperative

[ODS 0 | page 15] Argument candidate:
  Members of the SDSN Leadership Council offer the following assessments and recommendations to the UN Member States, the United Nations Agencies, international finance institutions, business, and civil society, based on more than a decade of research, measurement, advising, and partnerships across the world

[ODS 0 | page 16] Argument candidate:
  Dire shortfalls in meeting the SDGs to reaching a disastrous 2.8°C warming by 2100.

[ODS 0 | page 16] Argument candidate:
  Current Nationally Determined Contribution (NDC) targets, if implemented, would still lead to around 2.4°C warming by 2100.

[ODS 0 | page 16] Argument candidate:
  Biodiversity targets (SDG 15 and targets agreed under the CBD) are also at grave risk.

[ODS 0 | page 16] Argument candidate:
  Global resource consumption assessments for rare earth elements are critical.

[ODS 0 | page 16] Argument candidate:
  Ocean goods and services (SDG 14 and the High Seas Treaty) are at severe risk due to full- to over-exploitation

[ODS 0 | page 17] Argument candidate:
  Providing quality education (SDG 4) for all children is perhaps the single most important key to achieving sustainable development in the long term.

[ODS 0 | page 17] Argument candidate:
  The UN General Assembly’s Transforming Education Summit held in September 2022 was a critical meeting to spur national and global efforts to transform education to give all people the skills and knowledge to end poverty, protect the environment, and build peaceful and inclusive societies.

[ODS 0 | page 17] Argument candidate:
  And yet, the truth remains that hundreds of millions of children are either out of school entirely or receiving such an under-funded and under-resourced education that they are failing to achieve basic literacy and numeracy even after several years of education.

[ODS 0 | page 18] Argument candidate:
  The latest scientific assessments indicate that six of the nine planetary boundaries have been breached.

[ODS 0 | page 18] Argument candidate:
  Scientists have identified a large number of extremely dangerous potential tipping points, with linkages and dependencies across the different planetary boundaries.

[ODS 0 | page 18] Argument candidate:
  Human-induced global warming could hit several tipping points that may in turn lead to further feedbacks (amplifications) of the warming.

[ODS 0 | page 19] Argument candidate:
  Unless the SDGs are actively pursued, geophysical tipping points combined with technological disruptions could ignite disastrous social conflicts within and between nations.

[ODS 0 | page 19] Argument candidate:
  We firmly believe that international cooperation together with the achievement of the SDGs is the best preventative to this dire and growing risk, and represent an opportunity to create positive social tipping points: for example, through equal access to high-quality education (SDG 4), and by fighting all forms of inequalities, including income and wealth inequalities (SDG 10).

[ODS 0 | page 19] Argument candidate:
  Although all governments are in principle committed to economic justice as enshrined in the Universal Declaration of Human Rights, and to the SDG tenets of ‘leave no one behind’ and ‘reach the furthest behind first’, too few are living up to these commitments, especially as powerful groups block adequate public support for weaker groups.

[ODS 0 | page 19] Argument candidate:
  The report’s recommendations include calling for more racially-disaggregated SDG indicators and for dialogue with stakeholders on how to use these indicators to better allocate resources and prioritize the inclusion of marginalized peoples.

[ODS 0 | page 20] Argument candidate:
  the SDGs are woefully underfunded at home and internationally

[ODS 0 | page 20] Argument candidate:
  None of their objectives are beyond our reach

[ODS 0 | page 20] Argument candidate:
  the world must devote an increased portion of current output to building up sustainable capital assets for the future

[ODS 0 | page 20] Argument candidate:
  the world must both shift its current investment patterns and increase the overall investment flow in order to build the future we want

[ODS 0 | page 20] Argument candidate:
  Human capital: The skills and health of a productive citizenry, supported by universal health access and coverage, quality education, shared data and knowledge, promotion of a culture of peace and non-violence, global citizenship, and the appreciation of cultural diversity

[ODS 0 | page 20] Argument candidate:
  Natural capital: The capacity and healthy functioning of ecosystems, to be protected by ending human-induced climate change, protecting biodiversity, sustainably managing freshwater resources, and eliminating toxic pollutants

[ODS 0 | page 21] Argument candidate:
  To achieve the SDGs, the world must invest boldly, amply, and consistently in all eight kinds of capital.

[ODS 0 | page 21] Argument candidate:
  Governments too must take the lead in protecting natural capital, while civil society especially must promote social and cultural capital, including mutual understanding across cultures and nations.

[ODS 0 | page 21] Argument candidate:
  Crucially, national government must also work with subnational governments to implement the SDG agenda at the local level, including sustainable urban infrastructure, delivery of social services, and ensuring safe communities.

[ODS 0 | page 21] Argument candidate:
  Virtually all governments of the world have embraced the SDGs in principle. 188 of 193 UN Member States have submitted VNRs for comment by the other nations.

[ODS 0 | page 21] Argument candidate:
  Only five countries, notably the United States, Haiti, Myanmar, South Sudan, and Yemen, have never presented VNRs.

[ODS 0 | page 22] Argument candidate:
  The greatest responsibility for achieving the SDGs and safeguarding the planetary boundaries lies with the G20 members.

[ODS 0 | page 22] Argument candidate:
  With the 2022 Inflation Reduction Act, the Biden government announced its intention to reduce carbon emissions by roughly 40 percent from 2005 levels by 2030, although there are growing concerns that outcomes will lag behind these goals, due in part to the legislation’s lack of an agreed national financing strategy other than tax credits.

[ODS 0 | page 22] Argument candidate:
  The European Union – the world’s second-largest economy and its major lignite producer – has produced the European Green Deal (EGD), which is exemplary in many regards.

[ODS 0 | page 22] Argument candidate:
  Many EU member states demonstrate a high or moderate SDG commitment.

[ODS 0 | page 22] Argument candidate:
  The EGD embraces an EU-wide set of goals, timelines to 2050, and financing strategies across major dimensions of the SDGs: energy decarbonization, climate resilience, circular economy (to cut pollution), sustainable agriculture (the ‘farm-to-fork’ strategy), digital access, and innovation.

[ODS 0 | page 22] Argument candidate:
  The European Regional Development Fund, which provides the EU cohesion funds, is also directed towards the EGD.

[ODS 0 | page 22] Argument candidate:
  The SDSN Framework in the context of international cooperation.

[ODS 0 | page 23] Argument candidate:
  China has reiterated its support for the SDGs, such as in greening its Belt and Road Initiative and launching the Global Development Initiative as a worldwide effort.

[ODS 0 | page 23] Argument candidate:
  At the midpoint of the 2030 Agenda, all countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national strategies, using the principles of the 2030 Agenda (transformative, integrated, inclusive, leaving no one behind) as a yardstick.

[ODS 0 | page 23] Argument candidate:
  Four basic failures stand out: First, implementation is largely left to the national level and on a voluntary basis, without effective multilateral enforcement mechanisms in place.

[ODS 0 | page 23] Argument candidate:
  Developed countries are not being held to account, neither for their adverse spillovers, nor for ensuring adequate flows of financing for sustainable development.

[ODS 0 | page 23] Argument candidate:
  There are no assessments or recommendations by the respective secretariats or decision-making bodies on the adequacy or further enhancement of national implementation, let alone measures of enforcement.

[ODS 0 | page 24] Argument candidate:
  Greatly increase funding to national and subnational governments and private businesses in the emerging economies, especially the LICs and LMICs, to carry out the needed investments.

[ODS 0 | page 24] Argument candidate:
  Revise liquidity structures for LICs,LMICs, and SIDS, especially regarding sovereign debts, to forestall self-fulfilling banking and balance-of-payments crises.

[ODS 0 | page 24] Argument candidate:
  Create ambitious and internationally-agreed upon criteria for sustainable finance that are mandatory for all public financial institutions in HICs, MICs, and LICs alike.

[ODS 0 | page 24] Argument candidate:
  Align private business investment flows in all countries with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 24] Argument candidate:
  Reform current institutional frameworks and develop new, innovative mechanisms to improve the quality and speed of deployment of international cooperation, and monitor progress in an open and timely manner.

[ODS 0 | page 25] Argument candidate:
  Overhauling global governance mechanisms and the global financial architecture is fundamental to unlocking needed investments for sustainable development and ending non-sustainable practices.

[ODS 0 | page 25] Argument candidate:
  The SDGs call for lasting, long-term, directed change.

[ODS 0 | page 25] Argument candidate:
  For governments to combine the objectives of economic development, social inclusion, transparency, energy decarbonization, climate adaptation, water resources and sanitation, biodiversity conservation, digital access, gender equality, circular economy, over-harvesting, universal education, is daunting.

[ODS 0 | page 26] Argument candidate:
  Long-term investment plans are essential for national success in meeting the SDGs.

[ODS 0 | page 26] Argument candidate:
  SDSN has recommended six inter-related long-term transformations: Universal quality education and innovation-based economy, Universal health access and coverage, Zero-carbon energy systems, Sustainable ecosystems, sustainable agriculture, and climate resilience, Sustainable cities, Transformation to universal digital access and services

[ODS 0 | page 26] Argument candidate:
  None can be solved by the private sector alone; indeed, governments will have to take the lead to design policy and financial frameworks within which business can profitably invest and innovate.

[ODS 0 | page 26] Argument candidate:
  The Sustainable Development Report 2023 identifies five levers to be deployed to bring about the necessary transformations: governance, economy and finance, individual and collective action, science and technology, and capacity building.

[ODS 0 | page 26] Argument candidate:
  Planning for the long term, however, illuminates the global financial architecture’s Achilles heel. While the high-income countries (HICs) and upper-middle income countries (UMICs) can and should, in principle, finance these transformations via a combination of budget outlays, public-sector borrowing, and private financing (equity and debt), this is surely not true of the low-Income countries (LICs) and the lower middle-income countries

[ODS 0 | page 27] Argument candidate:
  Increased funding from the Multilateral Development Banks (MDBs) and Public Development Banks (PDBs) to developing countries, linked to investments in the SDGs

[ODS 0 | page 27] Argument candidate:
  an additional US$500 billion per year by 2025 of SDG finance

[ODS 0 | page 27] Argument candidate:

,prefix,model,ods,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL_SGD2023_,qwen2.5-3b,0,53,42,32,0,10
1,GLOBAL_SGD2023_,qwen2.5-3b,1,53,21,9,0,12
2,GLOBAL_SGD2023_,qwen2.5-3b,2,53,14,2,0,12
3,GLOBAL_SGD2023_,qwen2.5-3b,3,53,17,12,0,5
4,GLOBAL_SGD2023_,qwen2.5-3b,4,53,16,5,0,11
5,GLOBAL_SGD2023_,qwen2.5-3b,5,53,10,2,0,8
6,GLOBAL_SGD2023_,qwen2.5-3b,6,53,11,7,0,4
7,GLOBAL_SGD2023_,qwen2.5-3b,7,53,15,10,0,5
8,GLOBAL_SGD2023_,qwen2.5-3b,8,53,12,9,0,3
9,GLOBAL_SGD2023_,qwen2.5-3b,9,53,7,4,0,3
10,GLOBAL_SGD2023_,qwen2.5-3b,10,53,19,13,0,6
11,GLOBAL_SGD2023_,qwen2.5-3b,11,53,10,8,0,2
12,GLOBAL_SGD2023_,qwen2.5-3b,12,53,11,10,0,1
13,GLOBAL_SGD2023_,qwen2.5-3b,13,53,10,9,0,1
14,GLOBAL_SGD2023_,qwen2.5-3b,14,53,4,3,0,1
15,GLOBAL_SGD2023_,qwen2.5-3b,15,53,1,1,0,0
16,GLOBAL_SGD2023_,qwen2.5-3b,16,53,14,10,0,4
17,GLOBAL_SGD2023_,qwen2.5-3b,17,53,17,15,0,2
18,GLOBAL SGD2023,gemma3-4b,0,53,304,167,1,136
19,GLOBAL SGD2023,gemma3-4b,1,53,199,48,0,151
20,GLOBAL SGD2023,gemma3-4b,2,53,248,27,0,221
21,GLOBAL SGD2023,gemma3-4b,3,53,228,36,0,192
22,GLOBAL SGD2023,gemma3-4b,4,53,229,27,1,201
23,GLOBAL SGD2023,gemma3-4b,5,53,181,23,0,158
24,GLOBAL SGD2023,gemma3-4b,6,53,221,26,0,195
25,GLOBAL SGD2023,gemma3-4b,7,53,246,26,0,220
26,GLOBAL SGD2023,gemma3-4b,8,53,252,36,0,216
27,GLOBAL SGD2023,gemma3-4b,9,53,241,37,0,204
28,GLOBAL SGD2023,gemma3-4b,10,53,229,46,0,183
29,GLOBAL SGD2023,gemma3-4b,11,53,247,19,0,228
30,GLOBAL SGD2023,gemma3-4b,12,53,239,24,0,215
31,GLOBAL SGD2023,gemma3-4b,13,53,168,36,0,132
32,GLOBAL SGD2023,gemma3-4b,14,53,221,21,0,200
33,GLOBAL SGD2023,gemma3-4b,15,53,182,19,0,163
34,GLOBAL SGD2023,gemma3-4b,16,53,220,41,0,179
35,GLOBAL SGD2023,gemma3-4b,17,53,238,47,0,191

Stats overall for gemma3-4b in document GLOBAL_SGD2023_:

Updated overall summary:

,prefix,model,ods_max,pages_max,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,17,53,251,161,0,90
1,GLOBAL_SGD2023_,qwen2.5-3b,17,53,4344,867,2,3475

In [46]:
save_overall_summary(res, path_output_stats, model_name)

Updated overall summary:

,prefix,model,ods_max,pages_max,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,17,53,251,161,0,90
1,GLOBAL SGD2023,gemma3-4b,17,53,4093,706,2,3385

### Gemma3 27B

In [ ]:
prefix = 'GLOBAL_SGD2023'
model_name="gemma3-27b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')
display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

[ODS 0 | page 7] Argument candidate:
  At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.

[ODS 0 | page 7] Argument candidate:
  Despite this alarming development, the SDGs are still achievable.

[ODS 0 | page 7] Argument candidate:
  None of their objectives are beyond our reach.

[ODS 0 | page 7] Argument candidate:
  The world is off track, but that is all the more reason to double down on the SDGs.

[ODS 0 | page 7] Argument candidate:
  At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.

[ODS 0 | page 7] Argument candidate:
  To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.

[ODS 0 | page 7] Argument candidate:
  The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 7] Argument candidate:
  All countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national SDG strategies and commit to strengthening multilateralism.

[ODS 0 | page 7] Argument candidate:
  National governments must ensure both domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation – by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 7] Argument candidate:
  Achieving the SDGs requires global cooperation guided by the United Nations Charter.

[ODS 0 | page 7] Argument candidate:
  SDG transformations.

[ODS 0 | page 8] Argument candidate:
  Further investment is needed in statistical capacity and data literacy to support long-term pathways for key SDG transformations.

[ODS 0 | page 8] Argument candidate:
  At the halfway mark to 2030, there remains a great deal of work to be done to improve the data and methods underlying the SDG indicator framework.

[ODS 0 | page 8] Argument candidate:
  The SDSN was created in 2012, soon after the Rio+20 Summit, to mobilize the world’s universities, think tanks, and national laboratories on behalf of the SDGs.

[ODS 0 | page 8] Argument candidate:
  Via science-based pathways and analytics, the SDSN supports discussions on SDG implementation at the global, regional, and national levels.

[ODS 0 | page 8] Argument candidate:
  All UN Member States and UN agencies can count on the continued efforts and energies of the SDSN around the world to support all governments, businesses, and civil society in embracing and aligning with the SDGs on sustainable development.

[ODS 0 | page 13] Argument candidate:
  At the midpoint of the 2030 Agenda, the SDGs are far off track.

[ODS 0 | page 13] Argument candidate:
  SDSN offers the following recommendations to accelerate progress over the remaining seven years to 2030, and to set even more ambitious targets to be achieved by 2050 under the SDG framework.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of ‘leave no one behind’.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should present, at regular intervals, their national SDG frameworks in the form of Voluntary National Reviews (VNRs).

[ODS 0 | page 14] Argument candidate:
  All UN Member States should recommit to peaceful cooperation, in the service of the SDGs and all other multilateral agreements.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should commit to accelerating SDG progress to 2030, and to setting even more ambitious SDG targets to 2050, incorporating the recent Kunming-Montreal Biodiversity Framework and the High Seas Treaty.

[ODS 0 | page 15] Argument candidate:
  The SDGs are facing strong headwinds.

[ODS 0 | page 15] Argument candidate:
  Despite significant efforts in some places, national governments on all continents have fallen short in integrating the SDGs into national policies and public investments.

[ODS 0 | page 15] Argument candidate:
  We emphasize that achieving the SDGs rests on five pillars of good governance:

[ODS 0 | page 15] Argument candidate:
  The SDGs are not only a public policy framework; they are an ethical imperative.

[ODS 0 | page 15] Argument candidate:
  The SDGs are seriously off track (Figure 1.1).

[ODS 0 | page 15] Argument candidate:
  According to the annual SDG Index, global achievement of the SDGs rose only slightly, from 64 percent in 2015 to 66 percent in 2019 – far too slowly to meet the goals by 2030, and with highly uneven progress within and between countries.

[ODS 0 | page 15] Argument candidate:
  At current trends, based on simple projections, there is a risk that the gap in SDG outcomes between HICs and LICs will be wider in 2030 (29 points) than it was in 2015 (28 points).

[ODS 0 | page 15] Argument candidate:
  The multiple geopolitical crises in the world today will no doubt place further obstacles on the path to 2030.

[ODS 0 | page 15] Argument candidate:
  If we look at each of the 17 individual SDGs, not a single SDG is projected to be met at the global level.

[ODS 0 | page 17] Argument candidate:
  The World Bank. 2017. Atlas of Sustainable Development Goals.

[ODS 0 | page 17] Argument candidate:
  Providing quality education (SDG 4) for all children is perhaps the single most important key to achieving sustainable development in the long term.

[ODS 0 | page 19] Argument candidate:
  Unless the SDGs are actively pursued, geophysical tipping points combined with technological disruptions could ignite disastrous social conflicts within and between nations.

[ODS 0 | page 19] Argument candidate:
  We firmly believe that international cooperation together with the achievement of the SDGs is the best preventative to this dire and growing risk, and represent an opportunity to create positive social tipping points.

[ODS 0 | page 19] Argument candidate:
  Although all governments are in principle committed to economic justice as enshrined in the Universal Declaration of Human Rights, and to the SDG tenets of ‘leave no one behind’ and ‘reach the furthest behind first’, too few are living up to these commitments.

[ODS 0 | page 19] Argument candidate:
  The report’s recommendations include calling for more racially-disaggregated SDG indicators and for dialogue with stakeholders on how to use these indicators to better allocate resources and prioritize the inclusion of marginalized peoples.

[ODS 0 | page 20] Argument candidate:
  Despite this ominous news, the SDGs are still achievable.

[ODS 0 | page 20] Argument candidate:
  None of their objectives are beyond our reach.

[ODS 0 | page 20] Argument candidate:
  Yes, the world is off-track, but that is all the more reason to double-down on the goals, rather than surrendering to human-made shortfalls in achieving them.

[ODS 0 | page 20] Argument candidate:
  At their core, the SDGs are an investment agenda.

[ODS 0 | page 20] Argument candidate:
  In the most basic terms, the world must devote an increased portion of current output to building up sustainable capital assets for the future, and must deploy such assets effectively.

[ODS 0 | page 21] Argument candidate:
  To achieve the SDGs, the world must invest boldly, amply, and consistently in all eight kinds of capital.

[ODS 0 | page 21] Argument candidate:
  In 2022, the United Nations Secretary-General appointed a High-Level Advisory Board on Effective Multilateralism, with a mandate to develop a list of concrete, actionable recommendations to improve international cooperation and advance the 2030 Agenda for Sustainable Development.

[ODS 0 | page 21] Argument candidate:
  Nation-states hold the primary responsibility for achieving the SDGs.

[ODS 0 | page 21] Argument candidate:
  They hold juridical responsibility for implementing treaty agreements and the rest of the United Nations architecture, including the United Nations Charter, the Universal Declaration of Human Rights, and the SDGs.

[ODS 0 | page 21] Argument candidate:
  Virtually all governments of the world have embraced the SDGs in principle.

[ODS 0 | page 21] Argument candidate:
  188 of 193 UN Member States have submitted VNRs for comment by the other nations.

[ODS 0 | page 22] Argument candidate:
  We call on the United States to formulate an SDG action plan and to present a VNR to the High-Level Political Forum.

[ODS 0 | page 22] Argument candidate:
  In July 2023, the EU is set to present its first Union-wide voluntary review at the United Nations.

[ODS 0 | page 22] Argument candidate:
  China has already presented two VNRs to the HLPF (2016 and 2021).

[ODS 0 | page 23] Argument candidate:
  Recently, China has reiterated its support for the SDGs, such as in greening its Belt and Road Initiative and launching the Global Development Initiative as a worldwide effort.

[ODS 0 | page 23] Argument candidate:
  A key measure for China will be the explicit integration of the SDGs’ domestic and international implementation into the 15th five-year plan (2026–2030).

[ODS 0 | page 23] Argument candidate:
  At the midpoint of the 2030 Agenda, all countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national strategies, using the principles of the 2030 Agenda (transformative, integrated, inclusive, leaving no one behind) as a yardstick.

[ODS 0 | page 23] Argument candidate:
  Achieving the SDGs will require a transformative global approach.

[ODS 0 | page 23] Argument candidate:
  Both the 2030 Agenda and the Paris Climate Agreement established mechanisms to encourage and monitor their implementation by nation-states.

[ODS 0 | page 23] Argument candidate:
  However, experience so far with VNRs and Nationally Determined Contributions (NDCs), respectively, demonstrate that these mechanisms – despite some progress – have not delivered the effort necessary to achieve global goals.

[ODS 0 | page 24] Argument candidate:
  International cooperation is trapped by bureaucratic institutional frameworks that reduce the speed, efficacy, and efficiency of funding to meet the SDGs, and that fail to provide the framework for large-scale SDG financing.

[ODS 0 | page 24] Argument candidate:
  Align private business investment flows in all countries with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 26] Argument candidate:
  Long-term investment plans are essential for national success in meeting the SDGs.

[ODS 0 | page 26] Argument candidate:
  SDSN has recommended six inter-related long-term transformations:20

[ODS 0 | page 26] Argument candidate:
  1. Universal quality education and innovation-based economy

[ODS 0 | page 26] Argument candidate:
  2. Universal health access and coverage

[ODS 0 | page 26] Argument candidate:
  3. Zero-carbon energy systems

[ODS 0 | page 26] Argument candidate:
  4. Sustainable ecosystems, sustainable agriculture, and climate resilience

[ODS 0 | page 26] Argument candidate:
  5. Sustainable cities

[ODS 0 | page 26] Argument candidate:
  6. Transformation to universal digital access and services

[ODS 0 | page 27] Argument candidate:
  In his opening address to the UN General Assembly on September 20, 2022, UN Secretary-General António Guterres called on the G20 to launch an “SDG Stimulus” to offset the deteriorating market conditions faced by developing countries and to accelerate progress towards the SDGs and the Paris Climate Agreement.

[ODS 0 | page 27] Argument candidate:
  The SDG Stimulus plan recommended by the High-Level Working Group and introduced by SG Guterres last February25 has five main components:

[ODS 0 | page 27] Argument candidate:
  Increased funding from the Multilateral Development Banks (MDBs) and Public Development Banks (PDBs) to developing countries, linked to investments in the SDGs, a need echoed in the 2023 report of the High-Level Advisory Board on Effective Multilateralism26

[ODS 0 | page 28] Argument candidate:
  All United Nations agencies should put the SDGs at the centerpiece of their strategies, programs, and reporting.

[ODS 0 | page 28] Argument candidate:
  The World Bank and the other MDBs should put the SDGs at the center of their financing strategies, performance reviews, and reporting.

[ODS 0 | page 28] Argument candidate:
  The IMF should build its national reviews (Article IV), debt sustainability framework (DSF), and country programming around the public policies and financing needed for national success in achieving the SDGs.

[ODS 0 | page 28] Argument candidate:
  The G20 should organize its financial cooperation, reporting, and metrics around the reform of the GFA, as needed to achieve the SDGs.

[ODS 0 | page 28] Argument candidate:
  All UN Member States should present VNRs at least once every three years.

[ODS 0 | page 28] Argument candidate:
  It is especially urgent that the five countries that have not yet presented VNRs should do so no later than 2024.

[ODS 0 | page 28] Argument candidate:
  United Nations agencies, multilateral organizations, and Member States need to increase investment in, and coordination of, national and international data and statistical systems and scientific capacity to assess SDG progress and support sustainable development decision making and investment, including disaggregated data by region, social stratification, and other criteria as helpful.

[ODS 0 | page 29] Argument candidate:
  SDSN is closely following and supporting the EU’s endeavors to achieve the SDGs, inter alia by the EU’s European Green Deal.

[ODS 0 | page 29] Argument candidate:
  SDSN is supporting the African Development Bank to develop a strategic plan to accelerate Africa’s sustainable development, with the aim of the African Union achieving high-income status and sustainable development by 2063, the 100th anniversary of the Organization of African Unity.

[ODS 0 | page 29] Argument candidate:
  SDSN is supporting the African Development Bank to develop a strategic plan to accelerate Africa’s sustainable development

[ODS 0 | page 29] Argument candidate:
  SDSN recognizes this gap in the practical means of implementation of city governments, and is currently working with the major urban think tanks and global urban networks (including the C40 and ICLEI) to address the challenge of sub-national financing of the SDGs.

[ODS 0 | page 30] Argument candidate:
  SDG 16 recognizes the vital role of peaceful and inclusive societies, and SDG 17 underscores the need for global outreach and cooperation to achieve the Goals.

[ODS 0 | page 30] Argument candidate:
  The SDSN was created in 2012, soon after the Rio+20 Summit which mobilized the world’s universities, think tanks, and national laboratories on behalf of the SDGs.

[ODS 0 | page 30] Argument candidate:
  We aim to ensure that institutions of higher learning and public policy research centres in all 193 UN Member States are actively part of the SDSN.

[ODS 0 | page 30] Argument candidate:
  SDSN is working closely with the UNESCO SDG 4 High-Level Steering Committee on these two major issues, via Mission 4.7 through an SDG Academy Partnership with the Open Education Resources Recommendation team at UNESCO.

[ODS 0 | page 31] Argument candidate:
  They are the work of the 21st century.

[ODS 0 | page 31] Argument candidate:
  These are signal achievements of humanity, to have come together across all nations to adopt a common set of challenges.

[ODS 0 | page 31] Argument candidate:
  At the mid-point of the SDG agenda, we are far off target.

[ODS 0 | page 32] Argument candidate:
  First, that UN Member States, at the 2023 SDG Summit and the 2024 Summit of the Future, recommit boldly, strongly, and proactively to the SDGs, accelerate progress to 2030, and adopt even more ambitious SDG targets and objectives to mid-century, also incorporating recent international agreements on oceans and biodiversity.

[ODS 0 | page 32] Argument candidate:
  Second, UN Member States, starting with the G20 meeting this September in India, should adopt an SDG Stimulus to accelerate progress towards the SDGs by 2030 and enhance global governance for enforcing the implementation of the SDGs by all countries.

[ODS 0 | page 34] Argument candidate:
  The SDG Index and Dashboards track the annual progress of all 193 UN Member States towards the SDGs.

[ODS 0 | page 34] Argument candidate:
  At the midpoint of the 2030 Agenda, however, the SDGs are far off track.

[ODS 0 | page 34] Argument candidate:
  The SDG Index is an assessment of each country’s overall performance on the 17 SDGs, giving equal weight to each Goal.

[ODS 0 | page 34] Argument candidate:
  The dashboard and trend arrows help identify priorities for further actions and indicate whether countries are on track or off track to achieve the goals and targets by 2030, based on latest trend data.

[ODS 0 | page 38] Argument candidate:
  As detailed in the Europe Sustainable Development Report 2022, trends on several leave-no-one-behind indicators are not heading in the right direction in many EU member states (Lafortune et al. 2022).

[ODS 0 | page 43] Argument candidate:
  The 2030 Agenda and the SDGs recognize the importance of international spillovers in several crucial ways.

[ODS 0 | page 43] Argument candidate:
  SDG 17 (Partnerships for the Goals) calls for ‘policy coherence’ for sustainable development.

[ODS 0 | page 43] Argument candidate:
  SDG 17 (Partnerships for the Goals) calls on all countries to enhance policy coherence for sustainable development (PCSD).

[ODS 0 | page 58] Argument candidate:
  There was no expectation in 2015, when the SDGs and Agenda 2030 were adopted, that all goals and targets would be achieved at their midpoint.

[ODS 0 | page 58] Argument candidate:
  By 2023, one would expect that most countries would have implemented ambitious policy, regulatory and investment frameworks compatible with achieving major SDG transformations.

[ODS 0 | page 58] Argument candidate:
  It could also be expected that all countries would have at least once documented their progress and their plans for achieving the SDGs in a Voluntary National Review (VNRs) presented at the United Nations.

[ODS 0 | page 58] Argument candidate:
  Nation-states continue to hold the primary responsibility for achieving the SDGs.

[ODS 0 | page 59] Argument candidate:
  By July 2023, all UN Member States will have presented a VNR except for Haiti, Myanmar, South Sudan, the United States and Yemen.

[ODS 0 | page 59] Argument candidate:
  Official high-level speeches and the preparation of VNRs (as the official government-led process to report on SDG progress, gaps, and policy efforts) provide relevant proxies to gauge political commitment to the SDGs.

[ODS 0 | page 62] Argument candidate:
  since 2016, 188 UN Member States have prepared VNRs (see Figure 3.2).

[ODS 0 | page 62] Argument candidate:
  At the midpoint of the 2030 Agenda, only five countries have never submitted a VNR, among them the United States (HLPF, 2023).

[ODS 0 | page 62] Argument candidate:
  Some countries take a mainstreaming approach, where SDGs are implemented by each government ministry within the scope of its mandate (instead of via an overarching national action plan).

[ODS 0 | page 62] Argument candidate:
  For many, this takes the form of a national sustainability strategy explicitly linked to the 2030 Agenda goals and targets.

[ODS 0 | page 62] Argument candidate:

,prefix,model,ods,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,gemma3-27b,0,53,160,53,0,107
1,GLOBAL SGD2023,gemma3-27b,1,53,40,21,0,19
2,GLOBAL SGD2023,gemma3-27b,2,53,32,12,0,20
3,GLOBAL SGD2023,gemma3-27b,3,53,30,16,0,14
4,GLOBAL SGD2023,gemma3-27b,4,53,33,16,0,17
5,GLOBAL SGD2023,gemma3-27b,5,53,10,6,0,4
6,GLOBAL SGD2023,gemma3-27b,6,53,19,7,0,12
7,GLOBAL SGD2023,gemma3-27b,7,53,16,7,0,9
8,GLOBAL SGD2023,gemma3-27b,8,53,23,14,0,9
9,GLOBAL SGD2023,gemma3-27b,9,53,34,10,0,24
10,GLOBAL SGD2023,gemma3-27b,10,53,23,15,0,8
11,GLOBAL SGD2023,gemma3-27b,11,53,23,11,0,12
12,GLOBAL SGD2023,gemma3-27b,12,53,37,18,0,19
13,GLOBAL SGD2023,gemma3-27b,13,53,58,31,0,27
14,GLOBAL SGD2023,gemma3-27b,14,53,15,7,0,8
15,GLOBAL SGD2023,gemma3-27b,15,53,27,19,1,7
16,GLOBAL SGD2023,gemma3-27b,16,53,47,27,0,20
17,GLOBAL SGD2023,gemma3-27b,17,53,81,40,0,41

Stats overall for gemma3-27b in document GLOBAL_SGD2023:

TypeError: save_overall_summary() missing 1 required positional argument: 'model_name'

In [49]:
print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

Stats overall for gemma3-27b in document GLOBAL_SGD2023:

Updated overall summary:

,prefix,model,ods_max,pages_max,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,17,53,251,161,0,90
1,GLOBAL SGD2023,gemma3-4b,17,53,4093,706,2,3385
2,GLOBAL SGD2023,gemma3-27b,17,53,708,330,1,377

### Llama 3.3 70B

In [ ]:
prefix = 'GLOBAL_SGD2023_'
model_name="llama3.3-70b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')
display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

[ODS 0 | page 7] Argument candidate:
  At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.

[ODS 0 | page 7] Argument candidate:
  Since the outbreak of the pandemic in 2020 and other simultaneous crises, SDG progress has stalled globally.

[ODS 0 | page 7] Argument candidate:
  The world is off track, but that is all the more reason to double down on the SDGs.

[ODS 0 | page 7] Argument candidate:
  At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.

[ODS 0 | page 7] Argument candidate:
  To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.

[ODS 0 | page 7] Argument candidate:
  The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 7] Argument candidate:
  All countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national SDG strategies and commit to strengthening multilateralism.

[ODS 0 | page 7] Argument candidate:
  National governments must ensure both domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation – by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 7] Argument candidate:
  Achieving the SDGs requires global cooperation guided by the United Nations Charter.

[ODS 0 | page 7] Argument candidate:
  We introduce in the report this year a pilot index of countries commitment to and support of multilateralism under the UN Charter. SDG transformations.

[ODS 0 | page 8] Argument candidate:
  Further investment is needed in statistical capacity and data literacy to support long-term pathways for key SDG transformations.

[ODS 0 | page 8] Argument candidate:
  At the halfway mark to 2030, there remains a great deal of work to be done to improve the data and methods underlying the SDG indicator framework.

[ODS 0 | page 8] Argument candidate:
  According to major international studies, few teenagers can differentiate between a fact and an opinion. As underlined during the United Nations World Data Forum 2023 and in the 27 April Hangzhou Declaration, investing in statistical capacity, science, and data literacy are important priorities for achieving the SDGs.

[ODS 0 | page 8] Argument candidate:
  The SDSN and its global network will double-down on efforts to implement the SDGs by 2030 and beyond.

[ODS 0 | page 8] Argument candidate:
  Via science-based pathways and analytics, the SDSN supports discussions on SDG implementation at the global, regional, and national levels.

[ODS 0 | page 8] Argument candidate:
  All UN Member States and UN agencies can count on the continued efforts and energies of the SDSN around the world to support all governments, businesses, and civil society in embracing and aligning with the SDGs on sustainable development.

[ODS 0 | page 13] Argument candidate:
  The grim reality is that at the midpoint of the 2030 Agenda, the SDGs are far off track.

[ODS 0 | page 13] Argument candidate:
  United Nations Secretary-General António Guterres has urged world leaders to come together at the 2023 SDG Summit in September to deliver a “Rescue Plan for People and Planet”

[ODS 0 | page 13] Argument candidate:
  As the world’s nations prepare to meet in September to review the progress the world has made so far towards achieving the SDGs, at the midpoint of the 2030 Agenda, SDSN emphasizes six areas for immediate action.

[ODS 0 | page 13] Argument candidate:
  Most urgently, UN Member States should adopt an SDG Stimulus, to close the massive financing gap faced by many developing economies.

[ODS 0 | page 13] Argument candidate:
  UN Member States must endorse a deep and overdue reform of the global financial architecture.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of ‘leave no one behind’.

[ODS 0 | page 14] Argument candidate:
  SDSN recommends that national pathways should include six key transformations:

[ODS 0 | page 14] Argument candidate:
  All UN Member States should present, at regular intervals, their national SDG frameworks in the form of Voluntary National Reviews (VNRs).

[ODS 0 | page 14] Argument candidate:
  To date, 188 of the 193 UN Member States have already presented VNRs.

[ODS 0 | page 14] Argument candidate:
  The report that follows offers SDSN’s update on the state of the SDGs at their mid-point, highlighting the growing dangers of adverse environmental, social, and economic “tipping points” and identifying key ways that the global community can and should accelerate SDG progress.

[ODS 0 | page 14] Argument candidate:
  UN Member States should commit to accelerating SDG progress to 2030, and to setting even more ambitious SDG targets to 2050, incorporating the recent Kunming-Montreal Biodiversity Framework and the High Seas Treaty.

[ODS 0 | page 15] Argument candidate:
  The SDGs are facing strong headwinds. Despite significant efforts in some places, national governments on all continents have fallen short in integrating the SDGs into national policies and public investments.

[ODS 0 | page 15] Argument candidate:
  We emphasize that achieving the SDGs rests on five pillars of good governance:

[ODS 0 | page 15] Argument candidate:
  The SDGs are not only a public policy framework; they are an ethical imperative.

[ODS 0 | page 15] Argument candidate:
  Dire shortfalls in meeting the SDGs The SDGs are seriously off track (Figure 1.1).

[ODS 0 | page 15] Argument candidate:
  According to the annual SDG Index, global achievement of the SDGs rose only slightly, from 64 percent in 2015 to 66 percent in 2019 – far too slowly to meet the goals by 2030, and with highly uneven progress within and between countries.

[ODS 0 | page 15] Argument candidate:
  The world is also seriously off track to meet the Paris agreement climate targets and SDG 13 (Figure 1.3).

[ODS 0 | page 16] Argument candidate:
  Dire shortfalls in meeting the SDGs

[ODS 0 | page 16] Argument candidate:
  SDG Index world average: pre-pandemic trend and trend needed to achieve the SDGs by 2030

[ODS 0 | page 16] Argument candidate:
  Trend needed to achieve the SDGs

[ODS 0 | page 17] Argument candidate:
  6 of nearly 90% of global fish stocks.6 The crises facing our oceans are unabated, multidimensional, and complex.

[ODS 0 | page 17] Argument candidate:
  The 2021 UN Food Systems Summit raised many urgent concerns around improving the sustainability, affordability, and quality of food across the world (SDG 2).

[ODS 0 | page 17] Argument candidate:
  Providing quality education (SDG 4) for all children is perhaps the single most important key to achieving sustainable development in the long term.

[ODS 0 | page 17] Argument candidate:
  Figure 1.2 Observed and projected gaps in SDG Index score between HICs and LICs (in percentage points)

[ODS 0 | page 17] Argument candidate:
  Part 1. How to Achieve the SDGs: The SDSN Framework planetary boundaries that regulate the Earth system.

[ODS 0 | page 19] Argument candidate:
  Unless the SDGs are actively pursued, geophysical tipping points combined with technological disruptions could ignite disastrous social conflicts within and between nations.

[ODS 0 | page 19] Argument candidate:
  We firmly believe that international cooperation together with the achievement of the SDGs is the best preventative to this dire and growing risk, and represent an opportunity to create positive social tipping points: for example, through equal access to high-quality education (SDG 4), and by fighting all forms of inequalities, including income and wealth inequalities (SDG 10).

[ODS 0 | page 19] Argument candidate:
  Although all governments are in principle committed to economic justice as enshrined in the Universal Declaration of Human Rights, and to the SDG tenets of ‘leave no one behind’ and ‘reach the furthest behind first’, too few are living up to these commitments, especially as powerful groups block adequate public support for weaker groups.

[ODS 0 | page 19] Argument candidate:
  In her 2022 report on the SDGs, E. Tendayi Achiume – UN Special Rapporteur on contemporary forms of racism, racial discrimination, xenophobia and related intolerance – noted that racism and racial discrimination are key barriers to sustainable development, and called attention to the failure of some States to collect disaggregated data on race, ethnicity, indigeneity, and migration status in the context of the 2030 Agenda.

[ODS 0 | page 19] Argument candidate:
  The report’s recommendations include calling for more racially-disaggregated SDG indicators and for dialogue with stakeholders on how to use these indicators to better allocate resources and prioritize the inclusion of marginalized peoples.

[ODS 0 | page 20] Argument candidate:
  Despite this ominous news, the SDGs are still achievable.

[ODS 0 | page 20] Argument candidate:
  Investing in the SDGs

[ODS 0 | page 20] Argument candidate:
  The world must devote an increased portion of current output to building up sustainable capital assets for the future, and must deploy such assets effectively.

[ODS 0 | page 20] Argument candidate:
  At their core, the SDGs are an investment agenda.

[ODS 0 | page 20] Argument candidate:
  Yes, the world is off-track, but that is all the more reason to double-down on the goals, rather than surrendering to human-made shortfalls in achieving them.

[ODS 0 | page 20] Argument candidate:
  The SDGs are woefully underfunded at home and internationally.

[ODS 0 | page 21] Argument candidate:
  To achieve the SDGs, the world must invest boldly, amply, and consistently in all eight kinds of capital.

[ODS 0 | page 21] Argument candidate:
  Parallel to investing in the SDGs, the world needs to stop investing in activities that threaten planetary boundaries, destroy human and natural capital, and harm social cohesion.

[ODS 0 | page 21] Argument candidate:
  In 2022, the United Nations Secretary-General appointed a High-Level Advisory Board on Effective Multilateralism, with a mandate to develop a list of concrete, actionable recommendations to improve international cooperation and advance the 2030 Agenda for Sustainable Development.

[ODS 0 | page 21] Argument candidate:
  National governments must ensure both the domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 21] Argument candidate:
  Virtually all governments of the world have embraced the SDGs in principle. 188 of 193 UN Member States have submitted VNRs for comment by the other nations.

[ODS 0 | page 21] Argument candidate:
  The Nordic countries and European Union have shown considerable support for the SDGs. So too have many developing countries in the G20.

[ODS 0 | page 22] Argument candidate:
  The greatest responsibility for achieving the SDGs and safeguarding the planetary boundaries lies with the G20 members.

[ODS 0 | page 22] Argument candidate:
  The United States, as the world’s biggest economy in terms of GDP at market prices and its biggest oil and gas producer, has a responsibility both to itself and to the rest of the world to immediately embark on an ambitious transformation towards the SDGs, as well as towards other global climate and biodiversity goals.

[ODS 0 | page 22] Argument candidate:
  We call on the United States to formulate an SDG action plan and to present a VNR to the High-Level Political Forum.

[ODS 0 | page 22] Argument candidate:
  The European Union – the world’s second-largest economy and its major lignite producer – has produced the European Green Deal (EGD), which is exemplary in many regards.

[ODS 0 | page 22] Argument candidate:
  However, the EGD and EU policies at large lack a comprehensive alignment to the SDGs, politically agreed targets for many SDG indicators, and clarity on how to achieve the SDGs.

[ODS 0 | page 22] Argument candidate:
  The EU has also highlighted the strategic role of the private sector in achieving the SDGs, by implementing a new directive asking companies to publish sustainability reports and, in particular in the food sector, by promoting the “Code of Conduct on Responsible Food Business and Marketing Practices”

[ODS 0 | page 22] Argument candidate:
  China intends to implement the SDGs by integrating them into its medium and long-term national development strategies, such as its five-year plans.

[ODS 0 | page 22] Argument candidate:
  China has already presented two VNRs to the HLPF (2016 and 2021).

[ODS 0 | page 22] Argument candidate:
  In July 2023, the EU is set to present its first Union-wide voluntary review at the United Nations.

[ODS 0 | page 22] Argument candidate:
  This presents a good opportunity for the EU to send a strong message to the international community, and to demonstrate its commitment to and leadership on the SDGs.

[ODS 0 | page 23] Argument candidate:
  A key measure for China will be the explicit integration of the SDGs’ domestic and international implementation into the 15th five-year plan (2026–2030).

[ODS 0 | page 23] Argument candidate:
  We urge all G20 governments to show the leadership required of them.

[ODS 0 | page 23] Argument candidate:
  At the midpoint of the 2030 Agenda, all countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national strategies, using the principles of the 2030 Agenda (transformative, integrated, inclusive, leaving no one behind) as a yardstick.

[ODS 0 | page 23] Argument candidate:
  Achieving the SDGs will require a transformative global approach.

[ODS 0 | page 23] Argument candidate:
  Both the 2030 Agenda and the Paris Climate Agreement established mechanisms to encourage and monitor their implementation by nation-states. However, experience so far with VNRs and Nationally Determined Contributions (NDCs), respectively, demonstrate that these mechanisms – despite some progress – have not delivered the effort necessary to achieve global goals.

[ODS 0 | page 23] Argument candidate:
  Even the progress on consistent national reporting on SDG indicators is inadequate.

[ODS 0 | page 24] Argument candidate:
  It is widely recognized that the world needs to overhaul the GFA. Such an overhaul should address the failures above and aim to achieve six objectives:

[ODS 0 | page 24] Argument candidate:
  International cooperation is trapped by bureaucratic institutional frameworks that reduce the speed, efficacy, and efficiency of funding to meet the SDGs, and that fail to provide the framework for large-scale SDG financing.

[ODS 0 | page 24] Argument candidate:
  Align private business investment flows in all countries with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 24] Argument candidate:
  Reform current institutional frameworks and develop new, innovative mechanisms to improve the quality and speed of deployment of international cooperation, and monitor progress in an open and timely manner.

[ODS 0 | page 25] Argument candidate:
  Overhauling global governance mechanisms and the global financial architecture is fundamental to unlocking needed investments for sustainable development and ending non-sustainable practices.

[ODS 0 | page 25] Argument candidate:
  The SDG policy agenda is complex. The SDGs call for lasting, long-term, directed change.

[ODS 0 | page 26] Argument candidate:
  SDSN’s strategy to achieve the SDGs

[ODS 0 | page 26] Argument candidate:
  Long-term investment plans are essential for national success in meeting the SDGs.

[ODS 0 | page 26] Argument candidate:
  SDSN has recommended six inter-related long-term transformations:

[ODS 0 | page 26] Argument candidate:
  Each of these challenges will require large-scale public and private investments to mid-century, technological transformation, and a sound financing strategy.

[ODS 0 | page 26] Argument candidate:
  The Sustainable Development Report 2023 identifies five levers to be deployed to bring about the necessary transformations: governance, economy and finance, individual and collective action, science and technology, and capacity building.

[ODS 0 | page 26] Argument candidate:
  Planning for the long term, however, illuminates the global financial architecture’s Achilles heel.

[ODS 0 | page 26] Argument candidate:
  SDSN has joined the Group on Earth Observations (GEO)19 as a Participating Organization, supporting the efforts of this voluntary intergovernmental community to focus national, international, and private sector investments in Earth observations on urgent SDG needs.

[ODS 0 | page 27] Argument candidate:
  To make sure that existing financial resources and the required additional resources are used for sustainable investments, international finance institutions must fully incorporate achieving the SDGs and safeguarding the planetary boundaries into their core mandates, and monitor these regarding all countries, poorer and richer alike.

[ODS 0 | page 27] Argument candidate:
  Global infrastructure programs like China’s Belt and Road, the EU’s Global Gateway, or the United States’ Build Back Better World initiatives must be much better aligned with the SDGs and coordinated with each other.

[ODS 0 | page 27] Argument candidate:
  In his opening address to the UN General Assembly on September 20, 2022, UN Secretary-General António Guterres called on the G20 to launch an “SDG Stimulus” to offset the deteriorating market conditions faced by developing countries and to accelerate progress towards the SDGs and the Paris Climate Agreement.

[ODS 0 | page 27] Argument candidate:
  SDSN provided the Secretariat of a High-Level Informal Working Group for the SDG Stimulus (HLIWG), that made the case for an SDG Stimulus of an additional US$500 billion per year by 2025 of SDG finance.

[ODS 0 | page 27] Argument candidate:
  The SDG Stimulus plan recommended by the High-Level Working Group and introduced by SG Guterres last February has five main components:

[ODS 0 | page 27] Argument candidate:
  According to IMF estimates in 2019, the financing gap facing 57 low-income developing countries (LICs and LMICs that are eligible for IMF concessional financing) to cover very basic investments in health, education, power, roads, and water and sanitation was in the order of US$300 billion to US$500 billion per year.

[ODS 0 | page 27] Argument candidate:
  Adding in these extra needs, the global SDG financing gap is perhaps US$1 trillion per year, or roughly 1% of gross world product (GWP) at market prices.

[ODS 0 | page 27] Argument candidate:
  As a rough rule of thumb based on work by SDSN and the IMF, the LICs need roughly 20% of their GDP in increased SDG investment outlays while the LMICs need roughly 10%, though precise amounts vary by country.

[ODS 0 | page 28] Argument candidate:
  The urgent objective of the SDG Stimulus is to address – in practical terms and at scale – the chronic shortfall of international SDG financing facing the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 28] Argument candidate:

NameError: name 'path_output_txt' is not defined

### Deepseek r1 70B

In [ ]:
prefix = 'GLOBAL_SGD2023'
model_name="deepseek-r1-70b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')
display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
dfGlobal2023 = save_overall_summary(res, path_output_stats, model_name).rename(columns={"pages_max": "pages"}).drop(columns=["ods_max"])
dfGlobal2023

[ODS 0 | page 7] Argument candidate:
  At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.

[ODS 0 | page 7] Argument candidate:
  Despite this alarming development, the SDGs are still achievable. None of their objectives are beyond our reach.

[ODS 0 | page 7] Argument candidate:
  The world is off track, but that is all the more reason to double down on the SDGs.

[ODS 0 | page 7] Argument candidate:
  At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.

[ODS 0 | page 7] Argument candidate:
  To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.

[ODS 0 | page 7] Argument candidate:
  The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 7] Argument candidate:
  All countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national SDG strategies and commit to strengthening multilateralism.

[ODS 0 | page 7] Argument candidate:
  National governments must ensure both domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation – by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 7] Argument candidate:
  Achieving the SDGs requires global cooperation guided by the United Nations Charter.

[ODS 0 | page 7] Argument candidate:
  SDG transformations.

[ODS 0 | page 8] Argument candidate:
  Further investment is needed in statistical capacity and data literacy to support long-term pathways for key SDG transformations.

[ODS 0 | page 8] Argument candidate:
  At the halfway mark to 2030, there remains a great deal of work to be done to improve the data and methods underlying the SDG indicator framework.

[ODS 0 | page 8] Argument candidate:
  Evidence suggests that since 2016 there has been only limited progress and convergence in countries’ statistical capacity, including LICs and LMICs, and that international funding for data and statistics fell between 2019 and 2021.

[ODS 0 | page 8] Argument candidate:
  Also, in an information-rich and post-truth environment, citizens and decision-makers need knowledge and tools to transform data and science into evidence, actions, and long-term policies.

[ODS 0 | page 8] Argument candidate:
  According to major international studies, few teenagers can differentiate between a fact and an opinion.

[ODS 0 | page 8] Argument candidate:
  As underlined during the United Nations World Data Forum 2023 and in the 27 April Hangzhou Declaration, investing in statistical capacity, science, and data literacy are important priorities for achieving the SDGs.

[ODS 0 | page 8] Argument candidate:
  The SDSN and its global network will double-down on efforts to implement the SDGs by 2030 and beyond.

[ODS 0 | page 8] Argument candidate:
  Via science-based pathways and analytics, the SDSN supports discussions on SDG implementation at the global, regional, and national levels.

[ODS 0 | page 8] Argument candidate:
  All UN Member States and UN agencies can count on the continued efforts and energies of the SDSN around the world to support all governments, businesses, and civil society in embracing and aligning with the SDGs on sustainable development.

[ODS 0 | page 13] Argument candidate:
  The grim reality is that at the midpoint of the 2030 Agenda, the SDGs are far off track.

[ODS 0 | page 13] Argument candidate:
  As the world’s nations prepare to meet in September to review the progress the world has made so far towards achieving the SDGs, at the midpoint of the 2030 Agenda, SDSN emphasizes six areas for immediate action.

[ODS 0 | page 13] Argument candidate:
  Most urgently, UN Member States should adopt an SDG Stimulus, to close the massive financing gap faced by many developing economies.

[ODS 0 | page 13] Argument candidate:
  UN Member States must endorse a deep and overdue reform of the global financial architecture.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of ‘leave no one behind’.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should present, at regular intervals, their national SDG frameworks in the form of Voluntary National Reviews (VNRs). To date, 188 of the 193 UN Member States have already presented VNRs. Five countries (Haiti, Myanmar, South Sudan, the United States, and Yemen) have yet to do so, and should prepare to do so with urgency.

[ODS 0 | page 14] Argument candidate:
  UN Member States should commit to accelerating SDG progress to 2030, and to setting even more ambitious SDG targets to 2050, incorporating the recent Kunming-Montreal Biodiversity Framework and the High Seas Treaty.

[ODS 0 | page 15] Argument candidate:
  The SDGs are facing strong headwinds. Despite significant efforts in some places, national governments on all continents have fallen short in integrating the SDGs into national policies and public investments.

[ODS 0 | page 15] Argument candidate:
  Moreover, societal polarization, populism, and growing geopolitical conflict are hindering the global cooperation needed to achieve the SDGs.

[ODS 0 | page 15] Argument candidate:
  The international financial architecture is failing to channel global savings to SDG investments at the needed pace and scale.

[ODS 0 | page 15] Argument candidate:
  We emphasize that achieving the SDGs rests on five pillars of good governance: 1. Preparing long-term SDG pathways to guide public policy; 2. Ensuring SDG financing at the necessary scale and timing; 3. Promoting global cooperation and reducing geopolitical conflict and tension; 4. Supporting innovation to broaden social inclusion and environmental sustainability; 5. Regular reporting on SDG progress and performance.

[ODS 0 | page 15] Argument candidate:
  The SDGs are not only a public policy framework; they are an ethical imperative.

[ODS 0 | page 15] Argument candidate:
  They are grounded in the Universal Declaration of Human Rights, which celebrates its 75th anniversary this year.

[ODS 0 | page 15] Argument candidate:
  As the Universal Declaration makes clear, and the SDGs make explicit, social justice and sustainable development require the full realization of the rights of all people.

[ODS 0 | page 15] Argument candidate:
  The UN Sustainable Development Solutions Network (SDSN) is dedicated to finding and amplifying practical solutions to achieve the SDGs and closely-related global goals (such as the Paris climate agreement and the Kunming-Montreal Biodiversity Framework).

[ODS 0 | page 15] Argument candidate:
  We emphasize that all these global goals are interrelated and must be achieved together.

[ODS 0 | page 15] Argument candidate:
  Dire shortfalls in meeting the SDGs The SDGs are seriously off track (Figure 1.1).

[ODS 0 | page 15] Argument candidate:
  SDG progress was already very slow in the five years to 2020.

[ODS 0 | page 15] Argument candidate:
  According to the annual SDG Index, global achievement of the SDGs rose only slightly, from 64 percent in 2015 to 66 percent in 2019 – far too slowly to meet the goals by 2030, and with highly uneven progress within and between countries.

[ODS 0 | page 15] Argument candidate:
  Then with the onset of the pandemic, progress stopped.

[ODS 0 | page 15] Argument candidate:
  As of 2022, the global SDG Index is below 67%. At current trends, based on simple projections, there is a risk that the gap in SDG outcomes between HICs and LICs will be wider in 2030 (29 points) than it was in 2015 (28 points).

[ODS 0 | page 15] Argument candidate:
  This means that we are at risk of losing a decade of progress towards convergence globally (Figure 1.2).

[ODS 0 | page 15] Argument candidate:
  The multiple geopolitical crises in the world today will no doubt place further obstacles on the path to 2030.

[ODS 0 | page 15] Argument candidate:
  If we look at each of the 17 individual SDGs, not a single SDG is projected to be met at the global level.

[ODS 0 | page 16] Argument candidate:
  Dire shortfalls in meeting the SDGs

[ODS 0 | page 16] Argument candidate:
  Current Nationally Determined Contribution (NDC) targets, if implemented, would still lead to around 2.4°C warming by 2100.

[ODS 0 | page 16] Argument candidate:
  Even taking the net-zero pledges of many countries into account, best-case scenarios given current pledges would lead to around 1.8°C warming by 2100.

[ODS 0 | page 16] Argument candidate:
  Water scarcity affects more than 40% of the world’s population.

[ODS 0 | page 16] Argument candidate:
  An estimated 1.8 billion people depend on drinking water contaminated by human waste.

[ODS 0 | page 16] Argument candidate:
  Unsustainable water management practices, including chemical discharges into water supply systems for irrigation, affect the functioning of ecosystems services.

[ODS 0 | page 16] Argument candidate:
  Global resource consumption assessments for rare earth elements are critical.

[ODS 0 | page 16] Argument candidate:
  Although reserves of these elements do not exist in concentrated clusters – which make them inefficient for mining – certain countries are quite dominant in this field, producing 98% of the world’s supply.

[ODS 0 | page 16] Argument candidate:
  As demand for rare earth elements is increasing tremendously, their scarcity is becoming more evident.

[ODS 0 | page 17] Argument candidate:
  The 2021 UN Food Systems Summit raised many urgent concerns around improving the sustainability, affordability, and quality of food across the world (SDG 2).

[ODS 0 | page 17] Argument candidate:
  Providing quality education (SDG 4) for all children is perhaps the single most important key to achieving sustainable development in the long term.

[ODS 0 | page 17] Argument candidate:
  The UN General Assembly’s Transforming Education Summit held in September 2022 was a critical meeting to spur national and global efforts to transform education to give all people the skills and knowledge to end poverty, protect the environment, and build peaceful and inclusive societies.

[ODS 0 | page 17] Argument candidate:
  Note: Projected gap by 2030 is based on extrapolation of annual growth rate on the SDG Index over the period 2019-2021. Pre-pandemic projected gap is based on an extrapolation of SDG Index annual growth rates over the period 2015-2019.

[ODS 0 | page 17] Argument candidate:
  Part 1. How to Achieve the SDGs: The SDSN Framework "planetary boundaries" that regulate the Earth system.

[ODS 0 | page 19] Argument candidate:
  Unless the SDGs are actively pursued, geophysical tipping points combined with technological disruptions could ignite disastrous social conflicts within and between nations.

[ODS 0 | page 19] Argument candidate:
  We firmly believe that international cooperation together with the achievement of the SDGs is the best preventative to this dire and growing risk, and represent an opportunity to create positive social tipping points: for example, through equal access to high-quality education (SDG 4), and by fighting all forms of inequalities, including income and wealth inequalities (SDG 10).

[ODS 0 | page 19] Argument candidate:
  Although all governments are in principle committed to economic justice as enshrined in the Universal Declaration of Human Rights, and to the SDG tenets of ‘leave no one behind’ and ‘reach the furthest behind first’, too few are living up to these commitments, especially as powerful groups block adequate public support for weaker groups.

[ODS 0 | page 19] Argument candidate:
  She noted however that, while disrupting the dynamic of racially discriminatory underdevelopment may require a greater transformation than is possible at this moment, the SDGs held untapped potential to advance both development and non-discrimination.

[ODS 0 | page 20] Argument candidate:
  Despite this ominous news, the SDGs are still achievable.

[ODS 0 | page 20] Argument candidate:
  None of their objectives are beyond our reach.12 Yes, the world is off-track, but that is all the more reason to double-down on the goals, rather than surrendering to human-made shortfalls in achieving them.

[ODS 0 | page 20] Argument candidate:
  At their core, the SDGs are an investment agenda.

[ODS 0 | page 21] Argument candidate:
  To achieve the SDGs, the world must invest boldly, amply, and consistently in all eight kinds of capital.

[ODS 0 | page 21] Argument candidate:
  These investments must involve both governments and corporations.

[ODS 0 | page 21] Argument candidate:
  For example, while business capital is mainly the purview of the private sector, human capital is mainly the purview of the public sector.

[ODS 0 | page 21] Argument candidate:
  Governments too must take the lead in protecting natural capital, while civil society especially must promote social and cultural capital, including mutual understanding across cultures and nations.

[ODS 0 | page 21] Argument candidate:
  Infrastructure capital and innovation capital tend to be financed roughly equally by the public and private sectors.

[ODS 0 | page 21] Argument candidate:
  For example, governments tend to finance power transmission grids, while the private sector tends to finance power generation.

[ODS 0 | page 21] Argument candidate:
  Governments generally finance basic scientific research, while businesses focus on applied R&D.

[ODS 0 | page 21] Argument candidate:
  Parallel to investing in the SDGs, the world needs to stop investing in activities that threaten planetary boundaries, destroy human and natural capital, and harm social cohesion.

[ODS 0 | page 21] Argument candidate:
  Curtailing the extraction and use of fossil fuels is of paramount importance.

[ODS 0 | page 21] Argument candidate:
  To curb harmful investments, regulatory measures, including fair and sustainable taxation and the dismantling of unsustainable subsidies, need to be an integral element of the SDG investment agenda.

[ODS 0 | page 21] Argument candidate:
  In 2022, the United Nations Secretary-General appointed a High-Level Advisory Board on Effective Multilateralism, with a mandate to develop a list of concrete, actionable recommendations to improve international cooperation and advance the 2030 Agenda for Sustainable Development.

[ODS 0 | page 21] Argument candidate:
  The Board’s 2023 report lists six areas for action that are directly aligned with the SDGs and SDSN’s recommendations: rebuilding trust in multilateralism, safeguarding our planet and its people, scaling up and improving the efficacy of global finance, improving data systems and their governance, and promoting peace.

[ODS 0 | page 21] Argument candidate:
  The most important level of decision-making remains the nation-state.

[ODS 0 | page 21] Argument candidate:
  Nation-states hold the primary responsibility for achieving the SDGs.

[ODS 0 | page 21] Argument candidate:
  They are members of the United Nations and the signatories of United Nations treaties.

[ODS 0 | page 21] Argument candidate:
  They hold juridical responsibility for implementing treaty agreements and the rest of the United Nations architecture, including the United Nations Charter, the Universal Declaration of Human Rights, and the SDGs.

[ODS 0 | page 21] Argument candidate:
  National governments must ensure both the domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 21] Argument candidate:
  Crucially, national government must also work with subnational governments to implement the SDG agenda at the local level, including sustainable urban infrastructure, delivery of social services, and ensuring safe communities.

[ODS 0 | page 21] Argument candidate:
  Virtually all governments of the world have embraced the SDGs in principle.

[ODS 0 | page 21] Argument candidate:
  188 of 193 UN Member States have submitted VNRs for comment by the other nations.

[ODS 0 | page 21] Argument candidate:
  Only five countries, notably the United States, Haiti, Myanmar, South Sudan, and Yemen, have never presented VNRs.

[ODS 0 | page 21] Argument candidate:
  Four of these countries are wracked by violence and poverty.

[ODS 0 | page 21] Argument candidate:
  The case of the United States stands as a glaring exception.

[ODS 0 | page 21] Argument candidate:
  The Nordic countries and European Union have shown considerable support for the SDGs.

[ODS 0 | page 21] Argument candidate:
  So too have many developing countries in the G20.

[ODS 0 | page 22] Argument candidate:
  Failures (and some successes) of national SDG governance

[ODS 0 | page 22] Argument candidate:
  The greatest responsibility for achieving the SDGs and safeguarding the planetary boundaries lies with the G20 members.

[ODS 0 | page 22] Argument candidate:
  The United States has so far shown very little commitment to the SDGs. We call on the United States to formulate an SDG action plan and to present a VNR to the High-Level Political Forum.

[ODS 0 | page 22] Argument candidate:
  The European Union – the world’s second-largest economy and its major lignite producer – has produced the European Green Deal (EGD), which is exemplary in many regards.

[ODS 0 | page 22] Argument candidate:
  In July 2023, the EU is set to present its first Union-wide voluntary review at the United Nations. This presents a good opportunity for the EU to send a strong message to the international community, and to demonstrate its commitment to and leadership on the SDGs.

[ODS 0 | page 23] Argument candidate:
  12th Five-Year Plan referred to the 2030 Agenda mainly in the context of international cooperation.

[ODS 0 | page 23] Argument candidate:
  China has reiterated its support for the SDGs, such as in greening its Belt and Road Initiative and launching the Global Development Initiative as a worldwide effort.

[ODS 0 | page 23] Argument candidate:
  A key measure for China will be the explicit integration of the SDGs’ domestic and international implementation into the 15th five-year plan (2026–2030).

[ODS 0 | page 23] Argument candidate:
  Some other G20 countries have shown weak commitments to the SDGs in recent years.

[ODS 0 | page 23] Argument candidate:
  Many of the poor performers, such as Brazil, recently elected new governments that have staked out a far more ambitious position vis-à-vis the SDGs.

[ODS 0 | page 23] Argument candidate:
  We urge all G20 governments to show the leadership required of them.

[ODS 0 | page 23] Argument candidate:
  Most of the low-income and lower-middle income countries, home to more than half of humanity, face major challenges in achieving most of the SDGs by 2030.

[ODS 0 | page 23] Argument candidate:
  Many of them lack an adequately high SDG commitment, and almost all lack access to the necessary financial means to implement the SDGs.

[ODS 0 | page 23] Argument candidate:
  At the midpoint of the 2030 Agenda, all countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national strategies, using the principles of the 2030 Agenda (transformative, integrated, inclusive, leaving no one behind) as a yardstick.

[ODS 0 | page 23] Argument candidate:

,prefix,model,ods,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,deepseek-r1-70b,0,53,374,142,0,232
1,GLOBAL SGD2023,deepseek-r1-70b,1,53,57,30,0,27
2,GLOBAL SGD2023,deepseek-r1-70b,2,53,20,13,0,7
3,GLOBAL SGD2023,deepseek-r1-70b,3,53,36,24,0,12
4,GLOBAL SGD2023,deepseek-r1-70b,4,53,41,27,1,13
5,GLOBAL SGD2023,deepseek-r1-70b,5,53,7,5,0,2
6,GLOBAL SGD2023,deepseek-r1-70b,6,53,8,7,0,1
7,GLOBAL SGD2023,deepseek-r1-70b,7,53,23,12,1,10
8,GLOBAL SGD2023,deepseek-r1-70b,8,53,74,31,1,42
9,GLOBAL SGD2023,deepseek-r1-70b,9,53,67,23,0,44
10,GLOBAL SGD2023,deepseek-r1-70b,10,53,40,21,0,19
11,GLOBAL SGD2023,deepseek-r1-70b,11,53,35,17,0,18
12,GLOBAL SGD2023,deepseek-r1-70b,12,53,27,18,0,9
13,GLOBAL SGD2023,deepseek-r1-70b,13,53,87,47,0,40
14,GLOBAL SGD2023,deepseek-r1-70b,14,53,14,10,0,4
15,GLOBAL SGD2023,deepseek-r1-70b,15,53,32,20,0,12
16,GLOBAL SGD2023,deepseek-r1-70b,16,53,68,29,0,39
17,GLOBAL SGD2023,deepseek-r1-70b,17,53,168,77,0,91

Stats overall for deepseek-r1-70b in document GLOBAL_SGD2023:

Updated overall summary:

,prefix,model,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,53,251,161,0,90
1,GLOBAL SGD2023,gemma3-4b,53,4093,706,2,3385
2,GLOBAL SGD2023,gemma3-27b,53,708,330,1,377
3,GLOBAL SGD2023,llama3.3-70b,53,817,477,4,336
4,GLOBAL SGD2023,deepseek-r1-70b,53,1178,553,3,622

## GLOBAL SDG 2024 report

### Qwen2.5-3b

In [3]:
prefix = 'GLOBAL_SGD2024_'
model_name="qwen2.5-3b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')

display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

[ODS 0 | page 6] Argument candidate:
  The world is severely off track to realize the 2030 Agenda. Of the 169 targets, only 17 percent display progress sufficient for achievement by 2030.

[ODS 0 | page 7] Argument candidate:
  Many countries still face challenges in building a robust statistical foundation with data from these three traditional sources.

[ODS 0 | page 8] Argument candidate:
  Ensuring that no one is left behind calls for more than just data disaggregation. Uncovering the intersectional disadvantages faced by the most marginalized groups demands additional efforts.

[ODS 0 | page 9] Argument candidate:
  In 2023, only 65 per cent of countries had fully funded and implemented national statistical plans.

[ODS 0 | page 30] Argument candidate:
  The proportion of people living below half the median income is falling globally, with social assistance programmes largely explaining reduced inequality during the pandemic.

[ODS 0 | page 31] Argument candidate:
  One in three people living in IDA countries are poorer than before the pandemic.

[ODS 0 | page 33] Argument candidate:
  Only 6 in 10 urban residents have convenient access to public transit, based on data collected in 2023 from 2,039 cities in 188 countries.

[ODS 0 | page 34] Argument candidate:
  The world wastes 1.05 billion metric tons of food even as hundreds of millions face hunger.

[ODS 0 | page 35] Argument candidate:
  From 2019 to 2023, 62 Member States and the European Union reported 516 policy instruments to accelerate the transition to sustainable consumption and production patterns.

[ODS 0 | page 36] Argument candidate:
  Total net anthropogenic greenhouse gas emissions, 1990–2022 (gigatons of CO2 equivalent): 37.9, 41.8, 51.6, 54.5, 57.4

[ODS 0 | page 37] Argument candidate:
  All regions saw higher subsidies between 2021 and 2022, with the highest in Europe and Northern America ($455 billion), followed by Northern Africa and Western Asia ($327 billion) and Central and Southern Asia ($322 billion).

[ODS 0 | page 38] Argument candidate:
  Efforts to address these mounting concerns remain uneven. Key actions include implementing sustainable fishing practices, expanding marine protected areas to safeguard key biodiversity areas, increasing capacities to monitor ocean health and addressing the pollution that is choking waterways.

[ODS 0 | page 40] Argument candidate:
  Globally, forest area continues to decline, primarily due to agricultural expansion, despite notable progress in sustainable forest management.

[ODS 0 | page 43] Argument candidate:
  In 2015, the global prison population rose to 11.1 million, while in 2022 it grew to 11.5 million, indicating a slower growth rate compared to the world population.

[ODS 0 | page 44] Argument candidate:
  In a landscape of declining international cooperation and rising geopolitical tensions, strengthened global partnerships and enhanced cooperation are urgently needed to address widening financing gaps, reinforce post-pandemic recovery and promote sustainable development, particularly in the LDCs and other vulnerable countries.

[ODS 0 | page 10] Argument candidate:
  In 2023, only 28.

[ODS 0 | page 12] Argument candidate:
  Achieving zero hunger requires intensified efforts to transform food systems so they are sustainable, resilient and equitable.

[ODS 0 | page 13] Argument candidate:
  Small-scale food producers are vital in fighting hunger but earn less than half the income of larger-scale operations.

[ODS 0 | page 14] Argument candidate:
  The maternal mortality ratio is largely stuck at a level more than three times the 2030 target.

[ODS 0 | page 15] Argument candidate:
  Skilled birth attendance has improved globally, rising from 80 per cent of births in 2015 to 86 per cent in 2023.

[ODS 0 | page 17] Argument candidate:
  Treatment reaches only marginal shares of people with drug and alcohol disorders.

[ODS 0 | page 18] Argument candidate:
  To meet national 2030 education targets, which have been scaled back compared to the original Goal 4 targets, countries must annually enrol 1.4 million children in early childhood education, admit a new child to school every two seconds until 2030 and triple annual progress in primary completion rates.

[ODS 0 | page 19] Argument candidate:
  Universal pre-primary education is hindered by inadequate legal guarantees and financial barriers.

[ODS 0 | page 21] Argument candidate:
  Over 230 million girls and women have undergone female genital mutilation. Some countries have made strides towards ending it, but new estimates show an increase of 30 million cases compared to eight years ago.

[ODS 0 | page 22] Argument candidate:
  Sustainable management of water resources underpins prosperity and peace for all. It demands increased funding; more data-driven decision-making; skilled workforce development; innovative technology, including artificial intelligence (AI); and robust cross-sector collaboration.

[ODS 0 | page 25] Argument candidate:
  Yet increases in renewable energy use remain constrained in the heating and transport sectors, which account for four fifths of total final energy consumption.

[ODS 0 | page 27] Argument candidate:
  Informal employment persisted most notably in the LDCs at 89.1 per cent in 2023, a rate nearly unchanged since 2015.

[ODS 0 | page 29] Argument candidate:
  Only a small share can obtain it

[ODS 0 | page 29] Argument candidate:
  access to credit, crucial for their survival, remains difficult

[ODS 1 | page 6] Argument candidate:
  Alarmingly, 18 per cent indicate stagnation and 17 per cent regression below the 2015 baseline levels.

[ODS 1 | page 30] Argument candidate:
  The proportion of people living below half the median income is falling globally

[ODS 1 | page 31] Argument candidate:
  One in three of these countries are poorer than before the pandemic.

[ODS 1 | page 34] Argument candidate:
  High rates of consumption and insufficient reuse or recycling are producing vast piles of e-waste.

[ODS 1 | page 37] Argument candidate:
  Fossil fuel subsidies reached a record high of $1.53 trillion in 2022, driven by rising energy prices post-pandemic and the impact of the Russian Federation’s invasion of Ukraine, which disrupted global energy markets.

[ODS 1 | page 42] Argument candidate:
  Civilian deaths in armed conflict saw the steepest rise since 2015.

[ODS 1 | page 45] Argument candidate:
  Rising borrowing costs have and will continue to divert scarce resources from critical development needs such as poverty reduction, climate action, health and education.

[ODS 1 | page 10] Argument candidate:
  The COVID-19 pandemic caused extreme poverty to rise in 2020 for the first time in decades, reversing global progress by three years. The share of the world’s population living in extreme poverty rose from 8.9 per cent in 2019 to 9.7 per cent in 2020, driven by increases in low- and lower-middle-income countries.

[ODS 1 | page 11] Argument candidate:
  Despite improvement, 7 in 10 children worldwide still lack social protection coverage In 2023, only 28.2 per cent of children aged 0 to 15 globally received child cash benefits, up from 22.1 per cent in 2015. This left 1.4 billion children without social protection coverage.

[ODS 1 | page 12] Argument candidate:
  Achieving zero hunger requires intensified efforts to transform food systems so they are sustainable, resilient and equitable.

[ODS 1 | page 13] Argument candidate:
  11 Small-scale food producers are vital in fighting hunger but earn less than half the income of larger-scale operations.

[ODS 1 | page 14] Argument candidate:
  The maternal mortality ratio is largely stuck at a level more than three times the 2030 target.

[ODS 1 | page 15] Argument candidate:
  The global maternal mortality ratio declined only marginally from 227 to 223 maternal deaths per 100,000 live births between 2015 and 2020.

[ODS 1 | page 17] Argument candidate:
  Only about 1 in 11 individuals with drug use disorders received related treatment in 2022.

[ODS 1 | page 18] Argument candidate:
  To meet national 2030 education targets, which have been scaled back compared to the original Goal 4 targets, countries must annually enrol 1.4 million children in early childhood education, admit a new child to school every two seconds until 2030 and triple annual progress in primary completion rates.

[ODS 1 | page 22] Argument candidate:
  In 2022, roughly half the world’s population experienced severe water scarcity for at least part of the year. One quarter faced ‘extremely high’ levels of water stress.

[ODS 1 | page 23] Argument candidate:
  High water stress can have devastating consequences for the environment and hinder or even reverse economic and social development.

[ODS 1 | page 24] Argument candidate:
  The number without clean cooking fuels declined from 2.8 billion to 2.1 billion over the same period.

[ODS 1 | page 25] Argument candidate:
  Developing countries witnessed substantial expansion from 155 to 293 renewable watts per capita.

[ODS 1 | page 27] Argument candidate:
  25
Substantial declines in labour rights plague all regions, worsening prospects for social justice

[ODS 2 | page 31] Argument candidate:
  One in three of these countries are poorer than before the pandemic.

[ODS 2 | page 34] Argument candidate:
  An alarming 19 per cent of all food at the retail or consumption stage was wasted in 2022, totalling 1.05 billion metric tons of all food available to consumers.

[ODS 2 | page 44] Argument candidate:
  In 2023, ODA from Development Assistance Committee members totalled $223.7 billion, representing 0.37 per cent of members' combined gross national income.

[ODS 2 | page 10] Argument candidate:
  The global extreme poverty rate increased in 2020 for the first time in decades, setting back progress by three years.

[ODS 2 | page 11] Argument candidate:
  In 2023, only 28.2 per cent of children aged 0 to 15 globally received child cash benefits, up from 22.1 per cent in 2015.

[ODS 2 | page 12] Argument candidate:
  In 2022, almost 60 per cent of countries worldwide faced moderately to abnormally high food prices due to the spillover effects of conflicts, such as disrupted supply chains.

[ODS 2 | page 13] Argument candidate:
  Nearly 60 per cent of countries faced moderately to abnormally high food prices in 2022

[ODS 2 | page 15] Argument candidate:
  The adolescent birth rate for women aged 15–19 years declined to 41.3 births per 1,000 women in 2023, from 47.2 in 2015 and 64.5 in 2000.

[ODS 2 | page 24] Argument candidate:
  Without faster progress, by 2030, around 1.8 billion people will still prepare meals using polluting stoves and fuels

[ODS 3 | page 6] Argument candidate:
  Alarmingly, 18 per cent indicate stagnation and 17 per cent regression below the 2015 baseline levels.

[ODS 3 | page 7] Argument candidate:
  The strong statistical foundation draws on both traditional and innovative data sources. Traditional data sources include censuses, surveys and administrative data.

[ODS 3 | page 8] Argument candidate:
  Uncovering the intersectional disadvantages faced by the most marginalized groups demands additional efforts.

[ODS 3 | page 33] Argument candidate:
  Each year, an estimated 4.2 million people die due to ambient air pollution.

[ODS 3 | page 33] Argument candidate:
  Globally, the population-weighted exposure to fine particulate matter (PM2.5) dropped from 39.1 µg/m³ in 2010–2014 to 35.7 µg/m³ in 2015–2019, a 9 per cent decline.

[ODS 3 | page 33] Argument candidate:
  Eastern and South-Eastern Asia markedly improved air quality in 2015–2019, after having the world’s second-highest PM2.5 concentrations in 2010–2014.

[ODS 3 | page 33] Argument candidate:
  Air pollution in sub-Saharan Africa and Northern Africa and Western Asia increased from 2010–2014 to 2015–2019.

[ODS 3 | page 34] Argument candidate:
  High rates of consumption and insufficient reuse or recycling are producing vast piles of e-waste.

[ODS 3 | page 37] Argument candidate:
  Fossil fuel subsidies reached a record high of $1.53 trillion in 2022, driven by rising energy prices post-pandemic and the impact of the Russian Federation’s invasion of Ukraine, which disrupted global energy markets.

[ODS 3 | page 38] Argument candidate:
  Overfishing, pollution, climate change and poor management drive continued declines in fish stocks

[ODS 3 | page 40] Argument candidate:
  Globally, small-scale farming caused 68 per cent of agriculture-driven deforestation, while large-scale farming contributed to 32 per cent.

[ODS 3 | page 10] Argument candidate:
  The global extreme poverty rate increased in 2020 for the first time in decades, setting back progress by three years.

[ODS 3 | page 11] Argument candidate:
  In 2023, only 28.2 per cent of children aged 0 to 15 globally received child cash benefits, up from 22.1 per cent in 2015.

[ODS 3 | page 12] Argument candidate:
  In 2023, about 733 million people faced hunger, and 2.33 billion people experienced moderate to severe food insecurity.

[ODS 3 | page 13] Argument candidate:
  In 95 per cent of countries with available data, the average annual income of small-scale producers is less than half that of larger-scale producers.

[ODS 3 | page 14] Argument candidate:
  The maternal mortality ratio is largely stuck at a level more than three times the 2030 target.

[ODS 3 | page 14] Argument candidate:
  Under-5 deaths reached an historic low in 2022, but progress has slowed. Without accelerated declines, 35 million children will not live to see their fifth birthday by 2030.

[ODS 3 | page 15] Argument candidate:
  Declines in maternal mortality have stalled, with wide disparities by region and income. Between 2015 and 2020, the global maternal mortality ratio declined only marginally from 227 to 223 maternal deaths per 100,000 live births, over three times higher than the 2030 target of 70.

[ODS 3 | page 15] Argument candidate:
  In sub-Saharan Africa, only 73 per cent of births were attended by skilled personnel in 2023, the lowest rate worldwide. In contrast, Eastern and South-Eastern Asia achieved a rate of 96 per cent.

[ODS 3 | page 15] Argument candidate:
  The adolescent birth rate for women aged 15–19 years declined to 41.3 births per 1,000 women in 2023, from 47.2 in 2015 and 64.5 in 2000. For girls aged 10–14 years, the rate fell from 3.3 births per 1,000 girls in 2000 to 1.8 in 2015 and 1.5 in 2023.

[ODS 3 | page 15] Argument candidate:
  The proportion of women of reproductive age (15–49 years) who have their need for family planning satisfied with modern methods has climbed from 76.5 per cent in 2015 to 77.6 per cent in 2024, corresponding to an additional 75 million women using modern contraceptive methods globally.

[ODS 3 | page 15] Argument candidate:
  Global under-5 deaths reached a historic low of 4.9 million in 2022, down from 9.9 million in 2000 and 6.0 million in 2015. Nearly half these deaths (2.3 million) occurred during the neonatal period.

[ODS 3 | page 15] Argument candidate:
  The under-5 mortality rate was 37 deaths per 1,000 live births in 2022, a 51 per cent reduction since 2000 and a 14 per cent reduction from 2015. The global neonatal mortality rate fell to 17 deaths per 1,000 live births in 2022, a 44 per cent reduction since 2000 and a 12 per cent reduction since 2015.

[ODS 3 | page 16] Argument candidate:
  HIV/AIDS: The world has made significant strides in combating HIV. In 2022, an estimated 1.3 million new infections represented a 27 per cent decrease since 2015 and a 38 per cent reduction since 2010.

[ODS 3 | page 17] Argument candidate:
  Twenty-one million children missed out on life- saving vaccines in 2022

[ODS 3 | page 17] Argument candidate:
  Coverage of two doses of the measles vaccine and three doses of the pneumococcal conjugate vaccine increased in 2022, reaching 74 per cent and 60 per cent, respectively, following stagnation in 2020–2021.

[ODS 3 | page 18] Argument candidate:
  Upper secondary school completion rate, 2015 and 2023 (percentage)
World
53
Eastern and South-Eastern Asia
63

[ODS 3 | page 21] Argument candidate:
  Harmful practices are declining but not at rates keeping up with population growth

[ODS 3 | page 21] Argument candidate:
  Child marriage and female genital mutilation violate the rights of girls and have lifelong consequences.

[ODS 3 | page 21] Argument candidate:
  Some countries have made strides towards ending female genital mutilation, but new estimates show an increase of 30 million cases compared to eight years ago.

[ODS 3 | page 21] Argument candidate:
  Over 230 million girls and women have undergone female genital mutilation.

[ODS 3 | page 21] Argument candidate:
  In Africa, over 144 million girls and women have undergone the practice, with notably high levels in Djibouti, Guinea and Somalia, where at least 90 per cent of girls and women are affected.

[ODS 3 | page 21] Argument candidate:
  Women’s political participation remains constrained. As of 1 January 2024, one in five girls was married before 18 today compared to one in four 25 years ago;

[ODS 3 | page 21] Argument candidate:
  In local government, women occupied 35.5 per cent of elected seats in 2023.

[ODS 3 | page 21] Argument candidate:
  Women’s empowerment in sexual and reproductive health decisions remains restricted globally, although positive strides are evident in some places.

[ODS 3 | page 22] Argument candidate:
  Despite some improvements, progress in water and sanitation remains insufficient. In 2030, 2 billion people will still live without safely managed drinking water, 3 billion without safely managed sanitation and 1.4 billion without basic hygiene services.

[ODS 3 | page 24] Argument candidate:
  In 2022, although the global electricity access rate held steady at 91 per cent, 685 million people still lacked electricity, 10 million more than in 2021 due to population growth. This marked the first such increase in a decade.

[ODS 4 | page 6] Argument candidate:
  18 per cent indicate stagnation and 17 per cent regression below the 2015 baseline levels.

[ODS 4 | page 8] Argument candidate:
  Ensuring that no one is left behind calls for more than just data disaggregation. Uncovering the intersectional disadvantages faced by the most marginalized groups demands additional efforts.

[ODS 4 | page 30] Argument candidate:
  The proportion of people living below half the median income is falling globally

[ODS 4 | page 33] Argument candidate:
  Only 6 in 10 urban residents have convenient access to public transit, based on data collected in 2023 from 2,039 cities in 188 countries.

[ODS 4 | page 34] Argument candidate:
  Only 1.7 kilograms per capita was collected and managed in an environmentally sound manner.

[ODS 4 | page 37] Argument candidate:
  The global mean near-surface temperature for each year from 2024 to 2028 is predicted to be 1.1°C to 1.9°C higher than the 1850–1900 baseline.

[ODS 4 | page 12] Argument candidate:
  In 2023, about 733 million people faced hunger and almost unchanged for three years.

[ODS 4 | page 13] Argument candidate:
  In 95 per cent of countries with available data, the average annual income of small-scale producers is less than half that of larger-scale producers.

[ODS 4 | page 15] Argument candidate:
  The adolescent birth rate for women aged 15–19 years declined to 41.3 births per 1,000 women in 2023, from 47.2 in 2015 and 64.5 in 2000.

[ODS 4 | page 18] Argument candidate:
  To meet national 2030 education targets, which have been scaled back compared to the original Goal 4 targets, countries must annually enrol 1.4 million children in early childhood education, admit a new child to school every two seconds until 2030 and triple annual progress in primary completion rates.

[ODS 4 | page 19] Argument candidate:

,prefix,model,ods,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2024,qwen2.5-3b,0,40,29,3,0,26
1,GLOBAL SGD2024,qwen2.5-3b,1,40,20,14,0,6
2,GLOBAL SGD2024,qwen2.5-3b,2,40,9,4,0,5
3,GLOBAL SGD2024,qwen2.5-3b,3,40,37,17,0,20
4,GLOBAL SGD2024,qwen2.5-3b,4,40,13,3,0,10
5,GLOBAL SGD2024,qwen2.5-3b,5,40,21,8,0,13
6,GLOBAL SGD2024,qwen2.5-3b,6,40,8,3,0,5
7,GLOBAL SGD2024,qwen2.5-3b,7,40,8,1,0,7
8,GLOBAL SGD2024,qwen2.5-3b,8,40,12,5,0,7
9,GLOBAL SGD2024,qwen2.5-3b,9,40,4,2,0,2
10,GLOBAL SGD2024,qwen2.5-3b,10,40,20,7,0,13
11,GLOBAL SGD2024,qwen2.5-3b,11,40,2,2,0,0
12,GLOBAL SGD2024,qwen2.5-3b,12,40,4,2,0,2
13,GLOBAL SGD2024,qwen2.5-3b,13,40,11,8,0,3
14,GLOBAL SGD2024,qwen2.5-3b,14,40,12,6,0,6
15,GLOBAL SGD2024,qwen2.5-3b,15,40,2,2,0,0
16,GLOBAL SGD2024,qwen2.5-3b,16,40,4,2,0,2
17,GLOBAL SGD2024,qwen2.5-3b,17,40,2,2,0,0

Stats overall for qwen2.5-3b in document GLOBAL_SGD2024_:

Updated overall summary:

,prefix,model,ods_max,pages_max,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,annotation,17,53,250,253,0,0
1,GLOBAL SGD2023,qwen2.5-3b,17,53,251,161,0,90
2,GLOBAL SGD2023,gemma3-4b,17,53,4093,706,2,3385
3,GLOBAL SGD2023,gemma3-27b,17,53,708,330,1,377
4,GLOBAL SGD2023,llama3.3-70b,17,53,817,477,4,336
5,GLOBAL SGD2023,deepseek-r1-70b,17,53,1178,553,3,622
6,GLOBAL SGD2024,qwen2.5-3b,17,40,218,91,0,127

### Gemma3 4B

In [4]:
prefix = 'GLOBAL_SGD2024_'
model_name="gemma3-4b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')

display(res['per_sdg_summary_df'])000


print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

[ODS 0 | page 6] Argument candidate:
  Accurate, timely and disaggregated data are vital for measuring progress towards the 17 Sustainable Development Goals (SDGs) and 169 associated targets.

[ODS 0 | page 6] Argument candidate:
  Without high-quality data providing an evidence base, it will be impossible to truly understand where we are succeeding and falling short on the SDGs.

[ODS 0 | page 6] Argument candidate:
  The current status of the SDGs: severely off track

[ODS 0 | page 6] Argument candidate:
  Despite commendable increases in data to monitor the SDGs, critical gaps persist

[ODS 0 | page 6] Argument candidate:
  major shortfalls in priority development areas, such as gender equality (Goal 5), climate action (Goal 13), and peace, justice and strong institutions (Goal 16)

[ODS 0 | page 6] Argument candidate:
  Approximately one third of indicators lack data for the past three years, hampering the ability of policymakers to make timely informed decisions and course corrections

[ODS 0 | page 7] Argument candidate:
  Population censuses provide crucial data for national and subnational planning and also serve as denominators for numerous SDG indicators.

[ODS 0 | page 7] Argument candidate:
  Data demand for SDG monitoring has spurred innovation and the integration of different data sources.

[ODS 0 | page 7] Argument candidate:
  Azerbaijan uses remote sensing to monitor the coverage of important sites for mountain biodiversity (SDG indicator 15.4.1).

[ODS 0 | page 7] Argument candidate:
  Colombia and Malaysia have integrated geospatial and population data to estimate the proportion of the rural population living within 2 kilometres of an all-season road (SDG indicator 9.1.1).

[ODS 0 | page 7] Argument candidate:
  Bangladesh has employed geospatial and survey data to generate local poverty estimates to inform government policies.

[ODS 0 | page 7] Argument candidate:
  Ghana and the United Kingdom have tapped into citizen science data to monitor marine litter (SDG indicator 14.1.1).

[ODS 0 | page 7] Argument candidate:
  Kyrgyzstan’s statistical office collaborates with a network of civil society organizations to explore how citizen data can support the Voluntary National Review.

[ODS 0 | page 7] Argument candidate:
  The Netherlands and Uruguay monitor air pollution with national networks of sensors (SDG indicator 11.6.2).

[ODS 0 | page 7] Argument candidate:
  Countries worldwide are recognizing the need to invest in national statistical systems to produce high-quality, timely data for SDG monitoring.

[ODS 0 | page 7] Argument candidate:
  Engaging citizens in data production is essential to leave no one behind

[ODS 0 | page 7] Argument candidate:
  A comprehensive review by the Gender Data Compass, however, revealed significant gaps in disaggregated data for key social, economic and environmental indicators disseminated online by national statistical offices (NSOs).

[ODS 0 | page 7] Argument candidate:
  Sex-disaggregated data were most available for indicators on demographics, migration, fertility and reproductive health (with a score of 83) and least available for environmental indicators (23).

[ODS 0 | page 8] Argument candidate:
  Ensuring that no one is left behind calls for more than just data disaggregation.

[ODS 0 | page 8] Argument candidate:
  Addressing these challenges and formulating relevant policies to overcome them is possible only when citizen data are collected with the active involvement and support of communities with firsthand knowledge of their own needs.

[ODS 0 | page 8] Argument candidate:
  The openness level was greater in high-income countries, with a score of 67 in 2022, compared to only 42 for low- or lower-middle income countries.

[ODS 0 | page 8] Argument candidate:
  Monitoring these dimensions has been challenging.

[ODS 0 | page 8] Argument candidate:
  Successful SDG monitoring requires NSOs to play a strong stewardship role within the national data ecosystem.

[ODS 0 | page 8] Argument candidate:
  Only 30 per cent of NSOs considered this aspect important in their data stewardship role.

[ODS 0 | page 8] Argument candidate:
  Only 50 per cent played a role in data security.

[ODS 0 | page 9] Argument candidate:
  an urgent and sustained increase in the level and scale of investments in data and statistics from domestic and international actors, from the public, private and philanthropic sectors, to strengthen statistical capacity in low-income countries and fragile states, close data gaps for vulnerable groups and enhance country resilience in the current context of economic crisis, conflict, climate change and increased food insecurity.

[ODS 0 | page 9] Argument candidate:
  partnerships between NSOs and civil society organizations stood at 37 per cent.

[ODS 0 | page 9] Argument candidate:
  an ambitious goals of the 2030 Agenda

[ODS 0 | page 9] Argument candidate:
  To strengthen statistical capacity in low-income countries and fragile states, close data gaps for vulnerable groups and enhance country resilience in the current context of economic crisis, conflict, climate change and increased food insecurity.

[ODS 0 | page 30] Argument candidate:
  Despite the economic disruptions of the pandemic, the global share of people living on less than half the median income has been declining

[ODS 0 | page 30] Argument candidate:
  two thirds of countries with data have reduced the proportion of their population living on less than half the median income

[ODS 0 | page 30] Argument candidate:
  Labour’s share of GDP returns to a long-term decline as capital returns increase

[ODS 0 | page 30] Argument candidate:
  earnings from work are particularly important for less well-off and vulnerable people

[ODS 0 | page 30] Argument candidate:
  rising labour productivity has not fully translated into higher labour compensation

[ODS 0 | page 31] Argument candidate:
  half of the most vulnerable countries face a widening income gap with the wealthiest economies

[ODS 0 | page 31] Argument candidate:
  One in three of these countries are poorer than before the pandemic

[ODS 0 | page 31] Argument candidate:
  Developing countries make up 74 per cent of United Nations General Assembly Members but have limited voice and participation in international economic decision-making

[ODS 0 | page 31] Argument candidate:
  The number of refugees has increased year-on-year for more than a decade and doubled in less than seven years

[ODS 0 | page 31] Argument candidate:
  Over the past decade, the cost of remittances has fallen significantly

[ODS 0 | page 31] Argument candidate:
  Digital remittance services could help reach the target faster

[ODS 0 | page 31] Argument candidate:
  Digital services comprised 30 per cent of all services in 2023

[ODS 0 | page 32] Argument candidate:
  Over half the world’s population currently resides in cities, yet urban areas confront myriad complex challenges.

[ODS 0 | page 32] Argument candidate:
  Globally, approximately one quarter of the urban population lives in slums, with the total slum population reaching 1.1 billion in 2022.

[ODS 0 | page 32] Argument candidate:
  The lack of equitable access to public transportation is a significant concern, particularly in LDCs, where only 4 in 10 individuals have convenient access.

[ODS 0 | page 32] Argument candidate:
  Nearly 70 per cent of the global population projected to reside in cities by 2050, the development of critical infrastructure, affordable housing, efficient transport systems and essential social services is imperative to create resilient and sustainable cities that meet the needs of all.

[ODS 0 | page 32] Argument candidate:
  Over 85 per cent of all slum dwellers in 2022 were in Eastern and South-Eastern Asia (362 million), Central and Southern Asia (334 million) and sub-Saharan Africa (265 million).

[ODS 0 | page 32] Argument candidate:
  Sub-Saharan Africa will experience the most substantial proportional increase, with an estimated 360 million slum dwellers by 2030 if current trends persist.

[ODS 0 | page 32] Argument candidate:
  Sustainable urban development calls for mitigating the adverse impacts of urban sprawl and achieving a balanced approach to urban growth.

[ODS 0 | page 32] Argument candidate:
  Cities sprawled or grew outwards up to 3.7 times faster than they densified or grew upward from 2000 to 2020, based on recent data from 1,217 cities in 185 countries.

[ODS 0 | page 33] Argument candidate:
  Public transit remains out of easy reach for 40 per cent of urban residents worldwide

[ODS 0 | page 33] Argument candidate:
  Ensuring equitable access to public transportation helps to reduce food insecurity, boost economies, empower women, and connect people to key health, education and financial services, especially vulnerable urban populations

[ODS 0 | page 33] Argument candidate:
  Only 6 in 10 urban residents have convenient access to public transit, based on data collected in 2023 from 2,039 cities in 188 countries

[ODS 0 | page 33] Argument candidate:
  The shortfall is particularly problematic in the LDCs, where less than 4 in 10 urban residents have accessible public transportation options, compared to 8 in 10 in more affluent regions

[ODS 0 | page 33] Argument candidate:
  This effort is essential to foster inclusive urban development and improve the livelihoods of the urban poor

[ODS 0 | page 33] Argument candidate:
  Open public spaces in urban areas foster inclusive and vibrant cities. Yet only 44 per cent of urban residents have an open public space conveniently located within a 400-metre walk, according to 2020 data from 1,365 cities across 187 countries

[ODS 0 | page 33] Argument candidate:
  This lack of access disproportionately impacts people in the LDCs, where less than 30 per cent of urban dwellers can conveniently access open public spaces

[ODS 0 | page 33] Argument candidate:
  Without concerted efforts, the majority of urban populations will struggle to access vital amenities, particularly the most vulnerable residents

[ODS 0 | page 34] Argument candidate:
  Only 9 of 193 countries had included food waste in their NDCs, revealing a significant gap in connecting this issue with climate action and the objective of halving food waste and reducing losses by 2030.

[ODS 0 | page 34] Argument candidate:
  E-waste generation rose from 6.3 to 7.8 kilograms per capita from 2015 to 2022, reaching a total of 62 million metric tons of e-waste in 2022.

[ODS 0 | page 34] Argument candidate:
  If all countries boost their collection rates to 60 per cent, 54 million metric tons of e-waste would be managed in an environmentally sound manner, with 30 million metric tons of metal resources viably recovered.

[ODS 0 | page 34] Argument candidate:
  This would also prevent 34,000 kilograms of mercury emissions and 209 million metric tons of CO2-equivalent emissions in 2030.

[ODS 0 | page 35] Argument candidate:
  A widening regional gap between the two indicators signifies varying environmental pressure from material consumption

[ODS 0 | page 35] Argument candidate:
  Monitoring tourism in line with sustainable development is progressing yet more is needed

[ODS 0 | page 35] Argument candidate:
  National monitoring based on the Tourism Satellite Accounts and the System of Environmental Economic Accounts provides a good indication of a country’s capacity to measure the economic and environmental sustainability of tourism

[ODS 0 | page 35] Argument candidate:
  National strategy/road map/plan

[ODS 0 | page 35] Argument candidate:
  Legal/regulatory instruments

[ODS 0 | page 35] Argument candidate:
  Voluntary instrument

[ODS 0 | page 35] Argument candidate:
  Economic/fiscal instrument

[ODS 0 | page 35] Argument candidate:
  Organizational policy

[ODS 0 | page 36] Argument candidate:
  Developed countries committed to mobilize $100 billion annually in climate finance for developing countries by 2020 and through 2025.

[ODS 0 | page 36] Argument candidate:
  The UNFCCC estimates that nearly $6 trillion is needed for developing countries’ climate action plans by 2030

[ODS 0 | page 36] Argument candidate:
  These must have increased ambition to close implementation gaps, cover entire economies and all greenhouse gases, and align with the target of limiting global temperature rise to no more than 1.5°C.

[ODS 0 | page 36] Argument candidate:
  Drastic reductions in global greenhouse gas emissions must take place by 2030 and reach net zero by 2050.

[ODS 0 | page 36] Argument candidate:
  Keeping warming to 1.5°C calls for a 42 per cent reduction in greenhouse gas emissions by 2030, requiring an 8.7 per cent annual decline.

[ODS 0 | page 36] Argument candidate:
  For a 2°C limit, a 28 per cent drop by 2030 is necessary or a 5.3 per cent annual decrease.

[ODS 0 | page 36] Argument candidate:
  Current national policies set the world on track for warming of 3°C.

[ODS 0 | page 36] Argument candidate:
  NDCs lower this to 2.5°C, while all net-zero pledges would put warming at 2°C

[ODS 0 | page 37] Argument candidate:
  As disasters become more probable, better preparedness has lowered mortality rates

[ODS 0 | page 37] Argument candidate:
  In LDCs, the disaster-affected population per 100,000 people is 20 per cent higher than the global average, and the mortality rate is 170 per cent higher

[ODS 0 | page 37] Argument candidate:
  Improved preparedness, including early warning systems and evacuation measures, have significantly reduced disaster mortality in recent years

[ODS 0 | page 37] Argument candidate:
  National long-term risk reduction strategies and plans, reported by 129 countries; the establishment of effective multi-hazard early warning systems, reported by 104 countries; and comprehensive resilience plans are key to minimizing disaster impacts on people and economies

[ODS 0 | page 38] Argument candidate:
  Ensuring that the Agreement on Fisheries Subsidies enters into force as soon as possible

[ODS 0 | page 38] Argument candidate:
  increasing participation in the Agreement on Port State Measures to combat illegal, unreported and unregulated fishing

[ODS 0 | page 38] Argument candidate:
  adopting a global plastic pollution instrument

[ODS 0 | page 38] Argument candidate:
  ensuring that the Agreement on Marine Biodiversity of Areas Beyond National Jurisdiction enters into force as soon as possible to ensure the long-term health and sustainability of oceans

[ODS 0 | page 38] Argument candidate:
  Overfishing can harm biodiversity, ecosystems and fisheries production, and imposes adverse social and economic costs

[ODS 0 | page 38] Argument candidate:
  Effective fisheries management can possibly reverse these effects (if they are driven by overfishing and not factors such as habitat degradation, pollution or climate change) and lead to optimal stock levels while supporting global food security and coastal communities

[ODS 0 | page 38] Argument candidate:
  The ongoing albeit decelerated decline in biologically sustainable fish stocks worldwide underscores the need for enhanced regulatory frameworks and efficient monitoring systems

[ODS 0 | page 39] Argument candidate:
  Rising ocean temperatures are raising new concerns for coral reefs, which support a quarter of marine species, provide resources for hundreds of millions of people in coastal communities and generate trillions of dollars in revenue annually.

[ODS 0 | page 39] Argument candidate:
  The Intergovernmental Panel on Climate Change warns that up to 90 per cent of corals could be lost by 2050 at 1.5°C of warming and up to 99 per cent at 2°C.

[ODS 0 | page 39] Argument candidate:
  As oceans continue to warm amid rising global temperatures, the frequency and severity of coral bleaching will likely increase.

[ODS 0 | page 39] Argument candidate:
  These measures provide sustained, positive conservation outcomes even if they are managed primarily for other purposes.

[ODS 0 | page 40] Argument candidate:
  efforts are under way to tackle these challenges, with countries advancing implementation of access and benefit-sharing instruments and integrating biodiversity values into national accounting systems

[ODS 0 | page 40] Argument candidate:
  Urgent action is imperative. Addressing pressing environmental challenges and their underlying drivers and interconnections – including climate change, biodiversity loss, pollution, desertification and deforestation – demands intensified, accelerated efforts, and a comprehensive and integrated approach at local, national and global levels.

[ODS 0 | page 40] Argument candidate:
  reducing deforestation depends on improving food security, income and land rights

[ODS 0 | page 40] Argument candidate:
  A national park manager surveys tree nursery saplings in a desert area of central Saudi Arabia that is being regreened to combat land degradation, desertification and drought.

[ODS 0 | page 41] Argument candidate:
  Stopping the ongoing decline in biodiversity is an urgent race against time

[ODS 0 | page 41] Argument candidate:
  illegal wildlife trade persists worldwide despite two decades of concerted action at international and national levels

[ODS 0 | page 41] Argument candidate:
  detrimental land cover changes are impacting mountain ecosystems

[ODS 0 | page 41] Argument candidate:
  Mountain ecosystem degradation threatens downstream water provision

[ODS 0 | page 41] Argument candidate:
  diminished forest and vegetation coverage increase soil erosion, heightening the risk of downstream landslides and flooding

[ODS 0 | page 42] Argument candidate:
  All SDGs depend on establishing lasting peace and preventing violent conflicts.

[ODS 0 | page 42] Argument candidate:
  The trend must be reversed, conflicts must end, and parties to conflicts must strictly abide by international humanitarian and human rights obligations to protect civilians’ lives.

[ODS 0 | page 42] Argument candidate:
  If this pattern persists, the rate is projected to be 5.1 per 100,000 population by 2030, an overall decrease of just 13 per cent since 2015.

[ODS 0 | page 42] Argument candidate:
  The two regions with the highest rates are Latin America and the Caribbean, which is plagued by organized crime and gang activities, and Africa, which has a large youth population, increased incidences of extreme heat and persistent inequality.

[ODS 0 | page 43] Argument candidate:
  Strong protection frameworks are needed to stem this trend, particularly in countries where violent conflict or social unrest erupts or escalates.

[ODS 0 | page 43] Argument candidate:
  Multiple crises emphasize the need for governments to better prepare for future emergencies.

[ODS 0 | page 43] Argument candidate:
  Governments across the world have found it difficult to return to pre-COVID-19 levels of budget reliability, in part due to new international challenges impacting economies, including global political instability, inflation and volatile resource prices.

[ODS 0 | page 44] Argument candidate:
  The trillions needed to achieve the SDGs require world leaders to rapidly scale up investments

[ODS 0 | page 44] Argument candidate:
  In 2023, ODA from Development Assistance Committee members totalled $223.7 billion, representing 0.37 per cent of members’ combined gross national income.

[ODS 0 | page 44] Argument candidate:
  Remittances have proven resilient. They have become the premier source of external finance for developing countries in the post-COVID-19 period.

[ODS 0 | page 44] Argument candidate:
  In 2023, the annual SDG investment gap in developing countries was estimated at about $4 trillion, with over half, or $2.2 trillion, needed for the energy transition alone.

[ODS 0 | page 44] Argument candidate:
  The SDGs require world leaders to rapidly scale up investments

[ODS 0 | page 45] Argument candidate:

,prefix,model,ods,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2024,qwen2.5-3b,0,40,29,3,0,26
1,GLOBAL SGD2024,qwen2.5-3b,1,40,20,14,0,6
2,GLOBAL SGD2024,qwen2.5-3b,2,40,9,4,0,5
3,GLOBAL SGD2024,qwen2.5-3b,3,40,37,17,0,20
4,GLOBAL SGD2024,qwen2.5-3b,4,40,13,3,0,10
5,GLOBAL SGD2024,qwen2.5-3b,5,40,21,8,0,13
6,GLOBAL SGD2024,qwen2.5-3b,6,40,8,3,0,5
7,GLOBAL SGD2024,qwen2.5-3b,7,40,8,1,0,7
8,GLOBAL SGD2024,qwen2.5-3b,8,40,12,5,0,7
9,GLOBAL SGD2024,qwen2.5-3b,9,40,4,2,0,2
10,GLOBAL SGD2024,qwen2.5-3b,10,40,20,7,0,13
11,GLOBAL SGD2024,qwen2.5-3b,11,40,2,2,0,0
12,GLOBAL SGD2024,qwen2.5-3b,12,40,4,2,0,2
13,GLOBAL SGD2024,qwen2.5-3b,13,40,11,8,0,3
14,GLOBAL SGD2024,qwen2.5-3b,14,40,12,6,0,6
15,GLOBAL SGD2024,qwen2.5-3b,15,40,2,2,0,0
16,GLOBAL SGD2024,qwen2.5-3b,16,40,4,2,0,2
17,GLOBAL SGD2024,qwen2.5-3b,17,40,2,2,0,0
18,GLOBAL SGD2024,gemma3-4b,0,40,303,23,0,280
19,GLOBAL SGD2024,gemma3-4b,1,40,232,20,0,212
20,GLOBAL SGD2024,gemma3-4b,2,40,236,19,0,217
21,GLOBAL SGD2024,gemma3-4b,3,40,229,33,0,196
22,GLOBAL SGD2024,gemma3-4b,4,40,205,15,0,190
23,GLOBAL SGD2024,gemma3-4b,5,40,194,32,0,162
24,GLOBAL SGD2024,gemma3-4b,6,40,214,18,0,196
25,GLOBAL SGD2024,gemma3-4b,7,40,202,8,0,194
26,GLOBAL SGD2024,gemma3-4b,8,40,212,22,0,190
27,GLOBAL SGD2024,gemma3-4b,9,40,196,10,0,186
28,GLOBAL SGD2024,gemma3-4b,10,40,227,24,0,203
29,GLOBAL SGD2024,gemma3-4b,11,40,225,17,0,208
30,GLOBAL SGD2024,gemma3-4b,12,40,218,11,0,207
31,GLOBAL SGD2024,gemma3-4b,13,40,149,18,0,131
32,GLOBAL SGD2024,gemma3-4b,14,40,223,15,0,208
33,GLOBAL SGD2024,gemma3-4b,15,40,213,23,0,190
34,GLOBAL SGD2024,gemma3-4b,16,40,209,24,0,185
35,GLOBAL SGD2024,gemma3-4b,17,40,190,10,0,180

Stats overall for gemma3-4b in document GLOBAL_SGD2024_:

Updated overall summary:

,prefix,model,ods_max,pages_max,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,annotation,17,53,250,253,0,0
1,GLOBAL SGD2023,qwen2.5-3b,17,53,251,161,0,90
2,GLOBAL SGD2023,gemma3-4b,17,53,4093,706,2,3385
3,GLOBAL SGD2023,gemma3-27b,17,53,708,330,1,377
4,GLOBAL SGD2023,llama3.3-70b,17,53,817,477,4,336
5,GLOBAL SGD2023,deepseek-r1-70b,17,53,1178,553,3,622
6,GLOBAL SGD2024,qwen2.5-3b,17,40,218,91,0,127
7,GLOBAL SGD2024,gemma3-4b,17,40,3877,342,0,3535

### Gemma3 27B

In [5]:
prefix = 'GLOBAL_SGD2024'
model_name="gemma3-27b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')
display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

[ODS 0 | page 6] Argument candidate:
  Overall progress across targets based on 2015–2024 global aggregate data

[ODS 0 | page 6] Argument candidate:
  Despite commendable increases in data to monitor the SDGs, critical gaps persist

[ODS 0 | page 7] Argument candidate:
  The overarching principle of the 2030 Agenda for Sustainable Development is to leave no one behind.

[ODS 0 | page 7] Argument candidate:
  Engaging citizens in data production is essential to leave no one behind.

[ODS 0 | page 8] Argument candidate:
  Ensuring that no one is left behind calls for more than just data disaggregation.

[ODS 0 | page 8] Argument candidate:
  Since the adoption of the 2030 Agenda, countries have made significant progress in opening up official statistics for public use.

[ODS 0 | page 9] Argument candidate:
  As more countries recognize the importance of adopting a “whole-of-society” approach to achieve the ambitious goals of the 2030 Agenda, increased efforts are being made to acknowledge the contributions of civil society.

[ODS 0 | page 9] Argument candidate:
  At the SDG Summit in September 2023, the High Impact Initiative on the Power of Data was launched.

[ODS 0 | page 9] Argument candidate:
  It aims to deliver data needed to achieve the SDGs by mobilizing political support and investments in national data systems, fostering unified national data strategies, and strengthening partnerships, collaboration and coordination.

[ODS 0 | page 9] Argument candidate:
  More countries and partners are encouraged to join this important effort to ensure that every government has data to monitor and drive SDG progress.

[ODS 0 | page 31] Argument candidate:
  This is still above the 3 per cent SDG target, however.

[ODS 0 | page 31] Argument candidate:
  To achieve the SDG target, stakeholders could leverage digitalization to reduce costs, increase efficiency and improve remittance accessibility.

[ODS 0 | page 39] Argument candidate:
  Reaching the 10 per cent SDG target by 2030 calls for effectively managing important sites covering an average additional 1.13 million square kilometres of ocean each year.

[ODS 0 | page 39] Argument candidate:
  The Kunming-Montreal Global Biodiversity Framework commits to establishing protected areas to safeguard areas of particular importance for biodiversity, adding up to cover 30 per cent of oceans by 2030.

[ODS 0 | page 42] Argument candidate:
  All SDGs depend on establishing lasting peace and preventing violent conflicts.

[ODS 0 | page 42] Argument candidate:
  Urgent action is needed to combat corruption and organized crime, strengthen the rule of law and access to justice, build effective and inclusive governance institutions, and protect rights and fundamental freedoms.

[ODS 0 | page 44] Argument candidate:
  At the SDG Summit in September 2023, Heads of State and Government committed to advancing the Secretary-General’s SDG Stimulus proposal of unlocking $500 billion in additional financing and investment annually.

[ODS 0 | page 45] Argument candidate:
  This resource insufficiency threatens the resilience of statistical systems and risks leaving vulnerable populations behind.

[ODS 0 | page 12] Argument candidate:
  To assess global progress in sustainable agriculture, the Inter-agency and Expert Group on SDG Indicators adopted a new set of seven subindicators covering economic, social and environmental dimensions.

[ODS 0 | page 12] Argument candidate:
  While more detailed analysis is required to investigate the root causes of varying rates of progress, evidence suggests that all regions urgently need to take sustained, concerted actions to improve productive and sustainable agriculture by 2030.

[ODS 0 | page 12] Argument candidate:
  They otherwise risk missing the target by a wide margin.

[ODS 0 | page 15] Argument candidate:
  Achieving the 2030 target requires an annual reduction rate of 11.6 per cent between 2021 and 2030.

[ODS 0 | page 15] Argument candidate:
  If all countries met the target for under-5 mortality, an estimated 9 million lives could be saved by 2030.

[ODS 0 | page 15] Argument candidate:
  As of 2022, 134 countries had already met the target.

[ODS 0 | page 18] Argument candidate:
  Globally, pre-primary education has stagnated since the SDGs were agreed.

[ODS 0 | page 25] Argument candidate:
  To meet the Goal 7 energy efficiency target by 2030, annual improvements must now average around 4 per cent.

[ODS 1 | page 7] Argument candidate:
  Bangladesh has employed geospatial and survey data to generate local poverty estimates to inform government policies.

[ODS 1 | page 30] Argument candidate:
  Despite the economic disruptions of the pandemic, the global share of people living on less than half the median income has been declining due to social assistance programmes.

[ODS 1 | page 30] Argument candidate:
  The proportion of people living below half the median income is falling globally

[ODS 1 | page 30] Argument candidate:
  Since 2000, two thirds of countries with data have reduced the proportion of their population living on less than half the median income.

[ODS 1 | page 30] Argument candidate:
  This trend continued during the pandemic.

[ODS 1 | page 30] Argument candidate:
  Data from 82 countries, representing 70 per cent of the world’s population, indicate a slight decline in the proportion of people living below half the median income post-2019 compared to 2015–2019, dropping from 12.8 to 12.1 per cent.

[ODS 1 | page 30] Argument candidate:
  Progress has occurred in all regions except Central and Southern Asia, where the proportion remains relatively low at 9 per cent.

[ODS 1 | page 30] Argument candidate:
  Social assistance programmes, particularly in wealthier countries, largely explain reduced inequality during the pandemic.

[ODS 1 | page 30] Argument candidate:
  Latin America and the Caribbean has high levels of within-country inequality with at least 18 per cent of the population living on less than half the median income.

[ODS 1 | page 31] Argument candidate:
  One in four people in IDA countries live on less than $2.15 a day, an extreme poverty rate that is more than eight times the mean for the rest of the world.

[ODS 1 | page 31] Argument candidate:
  This is still above the 3 per cent SDG target, however.

[ODS 1 | page 32] Argument candidate:
  In 2022, 24.8 per cent of the urban population lived in slums or informal settlements, slightly lower than 25 per cent in 2015 but higher than 24.2 per cent in 2020.

[ODS 1 | page 32] Argument candidate:
  The total slum population was 1.12 billion in 2022, 130 million more than in 2015, marking a reversal from the consistent decrease observed from 2000 to 2020.

[ODS 1 | page 32] Argument candidate:
  The setback was mainly in Eastern and South-Eastern Asia (from 21.7 per cent in 2020 to 24.8 per cent in 2022) and sub-Saharan Africa (from 50.2 per cent in 2020 to 53.6 per cent in 2022).

[ODS 1 | page 33] Argument candidate:
  Ensuring equitable access to public transportation helps to reduce food insecurity, boost economies, empower women, and connect people to key health, education and financial services, especially vulnerable urban populations.

[ODS 1 | page 33] Argument candidate:
  Accelerated investments are needed to extend public transit services to the most marginalized communities, both in developing regions and impoverished urban neighbourhoods in developed countries.

[ODS 1 | page 33] Argument candidate:
  This effort is essential to foster inclusive urban development and improve the livelihoods of the urban poor.

[ODS 1 | page 34] Argument candidate:
  The world wastes 1.05 billion metric tons of food even as hundreds of millions face hunger

[ODS 1 | page 34] Argument candidate:
  Globally, an estimated 1 billion meals of edible food are wasted every day, equivalent to 1.3 meals per person impacted by hunger per day, considering that 783 million people faced hunger in 2022.

[ODS 1 | page 44] Argument candidate:
  Developing countries face a $4 trillion annual investment gap to achieve the SDGs.

[ODS 1 | page 44] Argument candidate:
  Mobilizing financial resources is crucial for driving global recovery and achieving the SDGs.

[ODS 1 | page 44] Argument candidate:
  In 2023, the annual SDG investment gap in developing countries was estimated at about $4 trillion, with over half, or $2.2 trillion, needed for the energy transition alone.

[ODS 1 | page 44] Argument candidate:
  At the SDG Summit in September 2023, Heads of State and Government committed to advancing the Secretary-General’s SDG Stimulus proposal of unlocking $500 billion in additional financing and investment annually.

[ODS 1 | page 45] Argument candidate:
  Increasing borrowing costs have and will continue to divert scarce resources from critical development needs such as poverty reduction, climate action, health and education.

[ODS 1 | page 10] Argument candidate:
  The COVID-19 pandemic and subsequent shocks from 2020 to 2022 have hampered global efforts to eradicate extreme poverty.

[ODS 1 | page 10] Argument candidate:
  The global extreme poverty rate increased in 2020 for the first time in decades, setting back progress by three years.

[ODS 1 | page 10] Argument candidate:
  By 2030, 590 million people may still live in extreme poverty if current trends persist.

[ODS 1 | page 10] Argument candidate:
  Without a substantial acceleration in poverty reduction, fewer than 3 in 10 countries are expected to halve national poverty by 2030.

[ODS 1 | page 10] Argument candidate:
  Despite increasing efforts and commitments to expand social protection programmes, significant coverage gaps left 1.4 billion children uncovered in 2023.

[ODS 1 | page 10] Argument candidate:
  Climate change is hindering poverty reduction, and disasters result in millions of households becoming poor or remaining trapped in poverty.

[ODS 1 | page 10] Argument candidate:
  Extreme poverty rates have returned to pre-pandemic levels except in low-income countries

[ODS 1 | page 10] Argument candidate:
  The COVID-19 pandemic caused extreme poverty to rise in 2020 for the first time in decades, reversing global progress by three years.

[ODS 1 | page 10] Argument candidate:
  In 2022, 712 million people (or 9 per cent of the world’s population) lived in extreme poverty, an increase of 23 million people over 2019.

[ODS 1 | page 10] Argument candidate:
  Projections suggest that by 2030, 590 million people, or 6.9 per cent of the global population, may remain in extreme poverty if current trends persist.

[ODS 1 | page 10] Argument candidate:
  In the 75 most vulnerable countries, one in four people live on less than $2.15 a day – more than eight times the extreme poverty rate in the rest of the world.

[ODS 1 | page 10] Argument candidate:
  One in three of these countries are now poorer on average than before the pandemic.

[ODS 1 | page 10] Argument candidate:
  Working poverty has declined but still afflicts 241 million workers

[ODS 1 | page 10] Argument candidate:
  The global working poverty rate slightly increased to 7.7 per cent in 2020 before declining to 6.9 per cent in 2023.

[ODS 1 | page 10] Argument candidate:
  Despite progress, nearly 241 million workers globally still lived in extreme poverty in 2023.

[ODS 1 | page 10] Argument candidate:
  Despite a falling working poverty rate, more than half of workers living in extreme poverty were still in sub-Saharan Africa (145 million).

[ODS 1 | page 10] Argument candidate:
  Globally, youth are twice as likely as adults to be in working poverty.

[ODS 1 | page 10] Argument candidate:
  Women typically experience higher working poverty rates than men, with the most pronounced gender gap observed in the least developed countries (LDCs).

[ODS 1 | page 11] Argument candidate:
  Despite improvement, 7 in 10 children worldwide still lack social protection coverage.

[ODS 1 | page 11] Argument candidate:
  Significant regional variations were evident, and despite a near doubling of coverage from 4.5 per cent in 2015 to 8.7 per cent in 2023, low-income countries were still far from universal coverage.

[ODS 1 | page 11] Argument candidate:
  To guarantee at least basic social security for all children, upper- and lower-middle-income countries would need to invest an additional $98.1 billion and $88.8 billion, respectively.

[ODS 1 | page 11] Argument candidate:
  Low-income countries would require an additional $59.6 billion.

[ODS 1 | page 13] Argument candidate:
  In 95 per cent of countries with available data, the average annual income of small-scale producers is less than half that of larger-scale producers.

[ODS 1 | page 13] Argument candidate:
  Small-scale food producers headed by men typically generate higher incomes than those headed by women.

[ODS 1 | page 13] Argument candidate:
  The latter had incomes that were less than 70 per cent of those earned by the former in nearly 50 per cent of countries with available data.

[ODS 1 | page 14] Argument candidate:
  They included 1 billion people facing catastrophic health expenditures exceeding 10 per cent of their household budget and 344 million driven deeper into extreme poverty by health costs.

[ODS 1 | page 15] Argument candidate:
  If all countries met the target for under-5 mortality, an estimated 9 million lives could be saved by 2030.

[ODS 1 | page 19] Argument candidate:
  This particularly impacted the poorest children, as pre-primary education can mitigate disadvantages.

[ODS 1 | page 19] Argument candidate:
  Overall, children from the richest households are twice as likely to attend preschool compared to those from the least affluent households.

[ODS 1 | page 21] Argument candidate:
  Heavy burdens of unpaid domestic and care work trap women in poverty and inequality

[ODS 1 | page 21] Argument candidate:
  This disproportionate burden is amplified in lower-income households, contributing to poverty, inequality and precariousness, including by limiting labour-market participation.

[ODS 1 | page 24] Argument candidate:
  Without a change in course, an estimated 660 million people will still lack electricity access and around 1.8 billion will go without clean cooking fuels and technologies by 2030.

[ODS 1 | page 24] Argument candidate:
  With projections indicating that 660 million people globally will remain unserved by 2030, achieving universal electricity access will require a 1.08 per cent annual increase.

[ODS 1 | page 24] Argument candidate:
  Without faster progress, by 2030, around 1.8 billion people will still prepare meals using polluting stoves and fuels

[ODS 1 | page 24] Argument candidate:
  This still leaves around 2.1 billion people relying on polluting fuels and technologies, such as wood, charcoal, dung and crop waste, as their primary energy source for cooking.

[ODS 1 | page 24] Argument candidate:
  Without stepped-up interventions, around 1.8 billion people or 21 per cent of the world’s population could lack access to clean cooking by 2030.

[ODS 1 | page 26] Argument candidate:
  With about 269 million young people globally not in education or work in 2023, intensified efforts are needed to reduce NEET rates, particularly among young women.

[ODS 1 | page 27] Argument candidate:
  This suggests that widespread formalization is unlikely soon.

[ODS 1 | page 27] Argument candidate:
  Economic challenges are pushing workers into informal jobs without social protection, a significant barrier to social justice.

[ODS 1 | page 27] Argument candidate:
  Informal employment persisted most notably in the LDCs at 89.1 per cent in 2023, a rate nearly unchanged since 2015.

[ODS 1 | page 27] Argument candidate:
  Tourism remains crucial for jobs, local ecosystems, peacebuilding and poverty reduction through income generation and tax revenues.

[ODS 1 | page 29] Argument candidate:
  According to survey data from 2006 to 2023, only 16.9 per cent of small-scale manufacturing industries in sub-Saharan Africa received loans or lines of credit, well below the global average of 31 per cent.

[ODS 2 | page 7] Argument candidate:
  Health and nutrition

[ODS 2 | page 9] Argument candidate:
  In the Hangzhou declaration on accelerating progress on the Cape Town Global Action Plan for Sustainable Development Data, countries agreed on “an urgent and sustained increase in the level and scale of investments in data and statistics from domestic and international actors, from the public, private and philanthropic sectors, to strengthen statistical capacity in low-income countries and fragile states, close data gaps for vulnerable groups and enhance country resilience in the current context of economic crisis, conflict, climate change and increased food insecurity.”

[ODS 2 | page 31] Argument candidate:
  Ninety per cent of people facing hunger and malnutrition live in IDA countries, half of which are in debt distress or at high risk of it.

[ODS 2 | page 31] Argument candidate:
  This is still above the 3 per cent SDG target, however.

[ODS 2 | page 31] Argument candidate:
  To achieve the SDG target, stakeholders could leverage digitalization to reduce costs, increase efficiency and improve remittance accessibility.

[ODS 2 | page 34] Argument candidate:
  The world wastes 1.05 billion metric tons of food even as hundreds of millions face hunger

[ODS 2 | page 34] Argument candidate:
  In 2022, 13.2 per cent of food produced globally was lost after harvest and during transport, storage, wholesale and processing.

[ODS 2 | page 34] Argument candidate:
  An alarming 19 per cent of all food at the retail or consumption stage was wasted in 2022, totalling 1.05 billion metric tons of all food available to consumers.

[ODS 2 | page 34] Argument candidate:
  Globally, an estimated 1 billion meals of edible food are wasted every day, equivalent to 1.3 meals per person impacted by hunger per day, considering that 783 million people faced hunger in 2022.

[ODS 2 | page 38] Argument candidate:
  Effective fisheries management can possibly reverse these effects (if they are driven by overfishing and not factors such as habitat degradation, pollution or climate change) and lead to optimal stock levels while supporting global food security and coastal communities.

[ODS 2 | page 39] Argument candidate:
  Rising ocean temperatures are raising new concerns for coral reefs, which support a quarter of marine species, provide resources for hundreds of millions of people in coastal communities and generate trillions of dollars in revenue annually.

[ODS 2 | page 39] Argument candidate:
  The survival of coral reefs is vital for ocean health and humanity’s well-being.

[ODS 2 | page 40] Argument candidate:
  Reducing deforestation depends on improving food security, income and land rights.

[ODS 2 | page 40] Argument candidate:
  These findings suggest that efforts to reduce deforestation must tackle production system weaknesses while addressing critical needs such as food security, income and land tenure rights for local communities.

[ODS 2 | page 41] Argument candidate:
  Between 2015 and 2019, at least 100 million hectares of productive land were degraded annually, adversely impacting global food and water security.

[ODS 2 | page 44] Argument candidate:
  Remittances have proven resilient. They have become the premier source of external finance for developing countries in the post-COVID-19 period.

[ODS 2 | page 44] Argument candidate:
  In 2023, remittances to low- and middle-income countries reached an estimated $669 billion, reflecting a normalization of flows following the post-pandemic robust growth.

[ODS 2 | page 44] Argument candidate:
  The global average cost of sending a $200 remittance was 6.4 per cent in 2023, more than twice the SDG target of 3 per cent.

[ODS 2 | page 44] Argument candidate:

,prefix,model,ods,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2024,gemma3-27b,0,40,26,10,0,16
1,GLOBAL SGD2024,gemma3-27b,1,40,66,24,0,42
2,GLOBAL SGD2024,gemma3-27b,2,40,35,13,0,22
3,GLOBAL SGD2024,gemma3-27b,3,40,77,34,0,43
4,GLOBAL SGD2024,gemma3-27b,4,40,22,14,0,8
5,GLOBAL SGD2024,gemma3-27b,5,40,59,35,0,24
6,GLOBAL SGD2024,gemma3-27b,6,40,27,15,0,12
7,GLOBAL SGD2024,gemma3-27b,7,40,26,12,0,14
8,GLOBAL SGD2024,gemma3-27b,8,40,38,19,0,19
9,GLOBAL SGD2024,gemma3-27b,9,40,18,13,0,5
10,GLOBAL SGD2024,gemma3-27b,10,40,64,30,0,34
11,GLOBAL SGD2024,gemma3-27b,11,40,15,12,0,3
12,GLOBAL SGD2024,gemma3-27b,12,40,32,13,0,19
13,GLOBAL SGD2024,gemma3-27b,13,40,52,31,0,21
14,GLOBAL SGD2024,gemma3-27b,14,40,18,13,0,5
15,GLOBAL SGD2024,gemma3-27b,15,40,25,16,0,9
16,GLOBAL SGD2024,gemma3-27b,16,40,10,7,0,3
17,GLOBAL SGD2024,gemma3-27b,17,40,27,6,0,21

Stats overall for gemma3-27b in document GLOBAL_SGD2024:

Updated overall summary:

,prefix,model,ods_max,pages_max,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,annotation,17,53,250,253,0,0
1,GLOBAL SGD2023,qwen2.5-3b,17,53,251,161,0,90
2,GLOBAL SGD2023,gemma3-4b,17,53,4093,706,2,3385
3,GLOBAL SGD2023,gemma3-27b,17,53,708,330,1,377
4,GLOBAL SGD2023,llama3.3-70b,17,53,817,477,4,336
5,GLOBAL SGD2023,deepseek-r1-70b,17,53,1178,553,3,622
6,GLOBAL SGD2024,qwen2.5-3b,17,40,218,91,0,127
7,GLOBAL SGD2024,gemma3-4b,17,40,3877,342,0,3535
8,GLOBAL SGD2024,gemma3-27b,17,40,637,317,0,320

### Llama 3.3 70B

In [ ]:
prefix = 'GLOBAL_SGD2024_'
model_name="llama3.3-70b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')
display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

[ODS 0 | page 7] Argument candidate:
  At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.

[ODS 0 | page 7] Argument candidate:
  Since the outbreak of the pandemic in 2020 and other simultaneous crises, SDG progress has stalled globally.

[ODS 0 | page 7] Argument candidate:
  The world is off track, but that is all the more reason to double down on the SDGs.

[ODS 0 | page 7] Argument candidate:
  At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.

[ODS 0 | page 7] Argument candidate:
  To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.

[ODS 0 | page 7] Argument candidate:
  The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 7] Argument candidate:
  All countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national SDG strategies and commit to strengthening multilateralism.

[ODS 0 | page 7] Argument candidate:
  National governments must ensure both domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation – by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 7] Argument candidate:
  Achieving the SDGs requires global cooperation guided by the United Nations Charter.

[ODS 0 | page 7] Argument candidate:
  We introduce in the report this year a pilot index of countries commitment to and support of multilateralism under the UN Charter. SDG transformations.

[ODS 0 | page 8] Argument candidate:
  Further investment is needed in statistical capacity and data literacy to support long-term pathways for key SDG transformations.

[ODS 0 | page 8] Argument candidate:
  At the halfway mark to 2030, there remains a great deal of work to be done to improve the data and methods underlying the SDG indicator framework.

[ODS 0 | page 8] Argument candidate:
  According to major international studies, few teenagers can differentiate between a fact and an opinion. As underlined during the United Nations World Data Forum 2023 and in the 27 April Hangzhou Declaration, investing in statistical capacity, science, and data literacy are important priorities for achieving the SDGs.

[ODS 0 | page 8] Argument candidate:
  The SDSN and its global network will double-down on efforts to implement the SDGs by 2030 and beyond.

[ODS 0 | page 8] Argument candidate:
  Via science-based pathways and analytics, the SDSN supports discussions on SDG implementation at the global, regional, and national levels.

[ODS 0 | page 8] Argument candidate:
  All UN Member States and UN agencies can count on the continued efforts and energies of the SDSN around the world to support all governments, businesses, and civil society in embracing and aligning with the SDGs on sustainable development.

[ODS 0 | page 13] Argument candidate:
  The grim reality is that at the midpoint of the 2030 Agenda, the SDGs are far off track.

[ODS 0 | page 13] Argument candidate:
  United Nations Secretary-General António Guterres has urged world leaders to come together at the 2023 SDG Summit in September to deliver a “Rescue Plan for People and Planet”

[ODS 0 | page 13] Argument candidate:
  As the world’s nations prepare to meet in September to review the progress the world has made so far towards achieving the SDGs, at the midpoint of the 2030 Agenda, SDSN emphasizes six areas for immediate action.

[ODS 0 | page 13] Argument candidate:
  Most urgently, UN Member States should adopt an SDG Stimulus, to close the massive financing gap faced by many developing economies.

[ODS 0 | page 13] Argument candidate:
  UN Member States must endorse a deep and overdue reform of the global financial architecture.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of ‘leave no one behind’.

[ODS 0 | page 14] Argument candidate:
  SDSN recommends that national pathways should include six key transformations:

[ODS 0 | page 14] Argument candidate:
  All UN Member States should present, at regular intervals, their national SDG frameworks in the form of Voluntary National Reviews (VNRs).

[ODS 0 | page 14] Argument candidate:
  To date, 188 of the 193 UN Member States have already presented VNRs.

[ODS 0 | page 14] Argument candidate:
  The report that follows offers SDSN’s update on the state of the SDGs at their mid-point, highlighting the growing dangers of adverse environmental, social, and economic “tipping points” and identifying key ways that the global community can and should accelerate SDG progress.

[ODS 0 | page 14] Argument candidate:
  UN Member States should commit to accelerating SDG progress to 2030, and to setting even more ambitious SDG targets to 2050, incorporating the recent Kunming-Montreal Biodiversity Framework and the High Seas Treaty.

[ODS 0 | page 15] Argument candidate:
  The SDGs are facing strong headwinds. Despite significant efforts in some places, national governments on all continents have fallen short in integrating the SDGs into national policies and public investments.

[ODS 0 | page 15] Argument candidate:
  We emphasize that achieving the SDGs rests on five pillars of good governance:

[ODS 0 | page 15] Argument candidate:
  The SDGs are not only a public policy framework; they are an ethical imperative.

[ODS 0 | page 15] Argument candidate:
  Dire shortfalls in meeting the SDGs The SDGs are seriously off track (Figure 1.1).

[ODS 0 | page 15] Argument candidate:
  According to the annual SDG Index, global achievement of the SDGs rose only slightly, from 64 percent in 2015 to 66 percent in 2019 – far too slowly to meet the goals by 2030, and with highly uneven progress within and between countries.

[ODS 0 | page 15] Argument candidate:
  The world is also seriously off track to meet the Paris agreement climate targets and SDG 13 (Figure 1.3).

[ODS 0 | page 16] Argument candidate:
  Dire shortfalls in meeting the SDGs

[ODS 0 | page 16] Argument candidate:
  SDG Index world average: pre-pandemic trend and trend needed to achieve the SDGs by 2030

[ODS 0 | page 16] Argument candidate:
  Trend needed to achieve the SDGs

[ODS 0 | page 17] Argument candidate:
  6 of nearly 90% of global fish stocks.6 The crises facing our oceans are unabated, multidimensional, and complex.

[ODS 0 | page 17] Argument candidate:
  The 2021 UN Food Systems Summit raised many urgent concerns around improving the sustainability, affordability, and quality of food across the world (SDG 2).

[ODS 0 | page 17] Argument candidate:
  Providing quality education (SDG 4) for all children is perhaps the single most important key to achieving sustainable development in the long term.

[ODS 0 | page 17] Argument candidate:
  Figure 1.2 Observed and projected gaps in SDG Index score between HICs and LICs (in percentage points)

[ODS 0 | page 17] Argument candidate:
  Part 1. How to Achieve the SDGs: The SDSN Framework planetary boundaries that regulate the Earth system.

[ODS 0 | page 19] Argument candidate:
  Unless the SDGs are actively pursued, geophysical tipping points combined with technological disruptions could ignite disastrous social conflicts within and between nations.

[ODS 0 | page 19] Argument candidate:
  We firmly believe that international cooperation together with the achievement of the SDGs is the best preventative to this dire and growing risk, and represent an opportunity to create positive social tipping points: for example, through equal access to high-quality education (SDG 4), and by fighting all forms of inequalities, including income and wealth inequalities (SDG 10).

[ODS 0 | page 19] Argument candidate:
  Although all governments are in principle committed to economic justice as enshrined in the Universal Declaration of Human Rights, and to the SDG tenets of ‘leave no one behind’ and ‘reach the furthest behind first’, too few are living up to these commitments, especially as powerful groups block adequate public support for weaker groups.

[ODS 0 | page 19] Argument candidate:
  In her 2022 report on the SDGs, E. Tendayi Achiume – UN Special Rapporteur on contemporary forms of racism, racial discrimination, xenophobia and related intolerance – noted that racism and racial discrimination are key barriers to sustainable development, and called attention to the failure of some States to collect disaggregated data on race, ethnicity, indigeneity, and migration status in the context of the 2030 Agenda.

[ODS 0 | page 19] Argument candidate:
  The report’s recommendations include calling for more racially-disaggregated SDG indicators and for dialogue with stakeholders on how to use these indicators to better allocate resources and prioritize the inclusion of marginalized peoples.

[ODS 0 | page 20] Argument candidate:
  Despite this ominous news, the SDGs are still achievable.

[ODS 0 | page 20] Argument candidate:
  Investing in the SDGs

[ODS 0 | page 20] Argument candidate:
  The world must devote an increased portion of current output to building up sustainable capital assets for the future, and must deploy such assets effectively.

[ODS 0 | page 20] Argument candidate:
  At their core, the SDGs are an investment agenda.

[ODS 0 | page 20] Argument candidate:
  Yes, the world is off-track, but that is all the more reason to double-down on the goals, rather than surrendering to human-made shortfalls in achieving them.

[ODS 0 | page 20] Argument candidate:
  The SDGs are woefully underfunded at home and internationally.

[ODS 0 | page 21] Argument candidate:
  To achieve the SDGs, the world must invest boldly, amply, and consistently in all eight kinds of capital.

[ODS 0 | page 21] Argument candidate:
  Parallel to investing in the SDGs, the world needs to stop investing in activities that threaten planetary boundaries, destroy human and natural capital, and harm social cohesion.

[ODS 0 | page 21] Argument candidate:
  In 2022, the United Nations Secretary-General appointed a High-Level Advisory Board on Effective Multilateralism, with a mandate to develop a list of concrete, actionable recommendations to improve international cooperation and advance the 2030 Agenda for Sustainable Development.

[ODS 0 | page 21] Argument candidate:
  National governments must ensure both the domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 21] Argument candidate:
  Virtually all governments of the world have embraced the SDGs in principle. 188 of 193 UN Member States have submitted VNRs for comment by the other nations.

[ODS 0 | page 21] Argument candidate:
  The Nordic countries and European Union have shown considerable support for the SDGs. So too have many developing countries in the G20.

[ODS 0 | page 22] Argument candidate:
  The greatest responsibility for achieving the SDGs and safeguarding the planetary boundaries lies with the G20 members.

[ODS 0 | page 22] Argument candidate:
  The United States, as the world’s biggest economy in terms of GDP at market prices and its biggest oil and gas producer, has a responsibility both to itself and to the rest of the world to immediately embark on an ambitious transformation towards the SDGs, as well as towards other global climate and biodiversity goals.

[ODS 0 | page 22] Argument candidate:
  We call on the United States to formulate an SDG action plan and to present a VNR to the High-Level Political Forum.

[ODS 0 | page 22] Argument candidate:
  The European Union – the world’s second-largest economy and its major lignite producer – has produced the European Green Deal (EGD), which is exemplary in many regards.

[ODS 0 | page 22] Argument candidate:
  However, the EGD and EU policies at large lack a comprehensive alignment to the SDGs, politically agreed targets for many SDG indicators, and clarity on how to achieve the SDGs.

[ODS 0 | page 22] Argument candidate:
  The EU has also highlighted the strategic role of the private sector in achieving the SDGs, by implementing a new directive asking companies to publish sustainability reports and, in particular in the food sector, by promoting the “Code of Conduct on Responsible Food Business and Marketing Practices”

[ODS 0 | page 22] Argument candidate:
  China intends to implement the SDGs by integrating them into its medium and long-term national development strategies, such as its five-year plans.

[ODS 0 | page 22] Argument candidate:
  China has already presented two VNRs to the HLPF (2016 and 2021).

[ODS 0 | page 22] Argument candidate:
  In July 2023, the EU is set to present its first Union-wide voluntary review at the United Nations.

[ODS 0 | page 22] Argument candidate:
  This presents a good opportunity for the EU to send a strong message to the international community, and to demonstrate its commitment to and leadership on the SDGs.

[ODS 0 | page 23] Argument candidate:
  A key measure for China will be the explicit integration of the SDGs’ domestic and international implementation into the 15th five-year plan (2026–2030).

[ODS 0 | page 23] Argument candidate:
  We urge all G20 governments to show the leadership required of them.

[ODS 0 | page 23] Argument candidate:
  At the midpoint of the 2030 Agenda, all countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national strategies, using the principles of the 2030 Agenda (transformative, integrated, inclusive, leaving no one behind) as a yardstick.

[ODS 0 | page 23] Argument candidate:
  Achieving the SDGs will require a transformative global approach.

[ODS 0 | page 23] Argument candidate:
  Both the 2030 Agenda and the Paris Climate Agreement established mechanisms to encourage and monitor their implementation by nation-states. However, experience so far with VNRs and Nationally Determined Contributions (NDCs), respectively, demonstrate that these mechanisms – despite some progress – have not delivered the effort necessary to achieve global goals.

[ODS 0 | page 23] Argument candidate:
  Even the progress on consistent national reporting on SDG indicators is inadequate.

[ODS 0 | page 24] Argument candidate:
  It is widely recognized that the world needs to overhaul the GFA. Such an overhaul should address the failures above and aim to achieve six objectives:

[ODS 0 | page 24] Argument candidate:
  International cooperation is trapped by bureaucratic institutional frameworks that reduce the speed, efficacy, and efficiency of funding to meet the SDGs, and that fail to provide the framework for large-scale SDG financing.

[ODS 0 | page 24] Argument candidate:
  Align private business investment flows in all countries with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 24] Argument candidate:
  Reform current institutional frameworks and develop new, innovative mechanisms to improve the quality and speed of deployment of international cooperation, and monitor progress in an open and timely manner.

[ODS 0 | page 25] Argument candidate:
  Overhauling global governance mechanisms and the global financial architecture is fundamental to unlocking needed investments for sustainable development and ending non-sustainable practices.

[ODS 0 | page 25] Argument candidate:
  The SDG policy agenda is complex. The SDGs call for lasting, long-term, directed change.

[ODS 0 | page 26] Argument candidate:
  SDSN’s strategy to achieve the SDGs

[ODS 0 | page 26] Argument candidate:
  Long-term investment plans are essential for national success in meeting the SDGs.

[ODS 0 | page 26] Argument candidate:
  SDSN has recommended six inter-related long-term transformations:

[ODS 0 | page 26] Argument candidate:
  Each of these challenges will require large-scale public and private investments to mid-century, technological transformation, and a sound financing strategy.

[ODS 0 | page 26] Argument candidate:
  The Sustainable Development Report 2023 identifies five levers to be deployed to bring about the necessary transformations: governance, economy and finance, individual and collective action, science and technology, and capacity building.

[ODS 0 | page 26] Argument candidate:
  Planning for the long term, however, illuminates the global financial architecture’s Achilles heel.

[ODS 0 | page 26] Argument candidate:
  SDSN has joined the Group on Earth Observations (GEO)19 as a Participating Organization, supporting the efforts of this voluntary intergovernmental community to focus national, international, and private sector investments in Earth observations on urgent SDG needs.

[ODS 0 | page 27] Argument candidate:
  To make sure that existing financial resources and the required additional resources are used for sustainable investments, international finance institutions must fully incorporate achieving the SDGs and safeguarding the planetary boundaries into their core mandates, and monitor these regarding all countries, poorer and richer alike.

[ODS 0 | page 27] Argument candidate:
  Global infrastructure programs like China’s Belt and Road, the EU’s Global Gateway, or the United States’ Build Back Better World initiatives must be much better aligned with the SDGs and coordinated with each other.

[ODS 0 | page 27] Argument candidate:
  In his opening address to the UN General Assembly on September 20, 2022, UN Secretary-General António Guterres called on the G20 to launch an “SDG Stimulus” to offset the deteriorating market conditions faced by developing countries and to accelerate progress towards the SDGs and the Paris Climate Agreement.

[ODS 0 | page 27] Argument candidate:
  SDSN provided the Secretariat of a High-Level Informal Working Group for the SDG Stimulus (HLIWG), that made the case for an SDG Stimulus of an additional US$500 billion per year by 2025 of SDG finance.

[ODS 0 | page 27] Argument candidate:
  The SDG Stimulus plan recommended by the High-Level Working Group and introduced by SG Guterres last February has five main components:

[ODS 0 | page 27] Argument candidate:
  According to IMF estimates in 2019, the financing gap facing 57 low-income developing countries (LICs and LMICs that are eligible for IMF concessional financing) to cover very basic investments in health, education, power, roads, and water and sanitation was in the order of US$300 billion to US$500 billion per year.

[ODS 0 | page 27] Argument candidate:
  Adding in these extra needs, the global SDG financing gap is perhaps US$1 trillion per year, or roughly 1% of gross world product (GWP) at market prices.

[ODS 0 | page 27] Argument candidate:
  As a rough rule of thumb based on work by SDSN and the IMF, the LICs need roughly 20% of their GDP in increased SDG investment outlays while the LMICs need roughly 10%, though precise amounts vary by country.

[ODS 0 | page 28] Argument candidate:
  The urgent objective of the SDG Stimulus is to address – in practical terms and at scale – the chronic shortfall of international SDG financing facing the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 28] Argument candidate:

NameError: name 'path_output_txt' is not defined

### Deepseek r1 70B

In [ ]:
prefix = 'GLOBAL_SGD2024'
model_name="deepseek-r1-70b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')
display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
dfGlobal2023 = save_overall_summary(res, path_output_stats, model_name).rename(columns={"pages_max": "pages"}).drop(columns=["ods_max"])
dfGlobal2023

[ODS 0 | page 7] Argument candidate:
  At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.

[ODS 0 | page 7] Argument candidate:
  Despite this alarming development, the SDGs are still achievable. None of their objectives are beyond our reach.

[ODS 0 | page 7] Argument candidate:
  The world is off track, but that is all the more reason to double down on the SDGs.

[ODS 0 | page 7] Argument candidate:
  At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.

[ODS 0 | page 7] Argument candidate:
  To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.

[ODS 0 | page 7] Argument candidate:
  The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 7] Argument candidate:
  All countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national SDG strategies and commit to strengthening multilateralism.

[ODS 0 | page 7] Argument candidate:
  National governments must ensure both domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation – by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 7] Argument candidate:
  Achieving the SDGs requires global cooperation guided by the United Nations Charter.

[ODS 0 | page 7] Argument candidate:
  SDG transformations.

[ODS 0 | page 8] Argument candidate:
  Further investment is needed in statistical capacity and data literacy to support long-term pathways for key SDG transformations.

[ODS 0 | page 8] Argument candidate:
  At the halfway mark to 2030, there remains a great deal of work to be done to improve the data and methods underlying the SDG indicator framework.

[ODS 0 | page 8] Argument candidate:
  Evidence suggests that since 2016 there has been only limited progress and convergence in countries’ statistical capacity, including LICs and LMICs, and that international funding for data and statistics fell between 2019 and 2021.

[ODS 0 | page 8] Argument candidate:
  Also, in an information-rich and post-truth environment, citizens and decision-makers need knowledge and tools to transform data and science into evidence, actions, and long-term policies.

[ODS 0 | page 8] Argument candidate:
  According to major international studies, few teenagers can differentiate between a fact and an opinion.

[ODS 0 | page 8] Argument candidate:
  As underlined during the United Nations World Data Forum 2023 and in the 27 April Hangzhou Declaration, investing in statistical capacity, science, and data literacy are important priorities for achieving the SDGs.

[ODS 0 | page 8] Argument candidate:
  The SDSN and its global network will double-down on efforts to implement the SDGs by 2030 and beyond.

[ODS 0 | page 8] Argument candidate:
  Via science-based pathways and analytics, the SDSN supports discussions on SDG implementation at the global, regional, and national levels.

[ODS 0 | page 8] Argument candidate:
  All UN Member States and UN agencies can count on the continued efforts and energies of the SDSN around the world to support all governments, businesses, and civil society in embracing and aligning with the SDGs on sustainable development.

[ODS 0 | page 13] Argument candidate:
  The grim reality is that at the midpoint of the 2030 Agenda, the SDGs are far off track.

[ODS 0 | page 13] Argument candidate:
  As the world’s nations prepare to meet in September to review the progress the world has made so far towards achieving the SDGs, at the midpoint of the 2030 Agenda, SDSN emphasizes six areas for immediate action.

[ODS 0 | page 13] Argument candidate:
  Most urgently, UN Member States should adopt an SDG Stimulus, to close the massive financing gap faced by many developing economies.

[ODS 0 | page 13] Argument candidate:
  UN Member States must endorse a deep and overdue reform of the global financial architecture.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of ‘leave no one behind’.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should present, at regular intervals, their national SDG frameworks in the form of Voluntary National Reviews (VNRs). To date, 188 of the 193 UN Member States have already presented VNRs. Five countries (Haiti, Myanmar, South Sudan, the United States, and Yemen) have yet to do so, and should prepare to do so with urgency.

[ODS 0 | page 14] Argument candidate:
  UN Member States should commit to accelerating SDG progress to 2030, and to setting even more ambitious SDG targets to 2050, incorporating the recent Kunming-Montreal Biodiversity Framework and the High Seas Treaty.

[ODS 0 | page 15] Argument candidate:
  The SDGs are facing strong headwinds. Despite significant efforts in some places, national governments on all continents have fallen short in integrating the SDGs into national policies and public investments.

[ODS 0 | page 15] Argument candidate:
  Moreover, societal polarization, populism, and growing geopolitical conflict are hindering the global cooperation needed to achieve the SDGs.

[ODS 0 | page 15] Argument candidate:
  The international financial architecture is failing to channel global savings to SDG investments at the needed pace and scale.

[ODS 0 | page 15] Argument candidate:
  We emphasize that achieving the SDGs rests on five pillars of good governance: 1. Preparing long-term SDG pathways to guide public policy; 2. Ensuring SDG financing at the necessary scale and timing; 3. Promoting global cooperation and reducing geopolitical conflict and tension; 4. Supporting innovation to broaden social inclusion and environmental sustainability; 5. Regular reporting on SDG progress and performance.

[ODS 0 | page 15] Argument candidate:
  The SDGs are not only a public policy framework; they are an ethical imperative.

[ODS 0 | page 15] Argument candidate:
  They are grounded in the Universal Declaration of Human Rights, which celebrates its 75th anniversary this year.

[ODS 0 | page 15] Argument candidate:
  As the Universal Declaration makes clear, and the SDGs make explicit, social justice and sustainable development require the full realization of the rights of all people.

[ODS 0 | page 15] Argument candidate:
  The UN Sustainable Development Solutions Network (SDSN) is dedicated to finding and amplifying practical solutions to achieve the SDGs and closely-related global goals (such as the Paris climate agreement and the Kunming-Montreal Biodiversity Framework).

[ODS 0 | page 15] Argument candidate:
  We emphasize that all these global goals are interrelated and must be achieved together.

[ODS 0 | page 15] Argument candidate:
  Dire shortfalls in meeting the SDGs The SDGs are seriously off track (Figure 1.1).

[ODS 0 | page 15] Argument candidate:
  SDG progress was already very slow in the five years to 2020.

[ODS 0 | page 15] Argument candidate:
  According to the annual SDG Index, global achievement of the SDGs rose only slightly, from 64 percent in 2015 to 66 percent in 2019 – far too slowly to meet the goals by 2030, and with highly uneven progress within and between countries.

[ODS 0 | page 15] Argument candidate:
  Then with the onset of the pandemic, progress stopped.

[ODS 0 | page 15] Argument candidate:
  As of 2022, the global SDG Index is below 67%. At current trends, based on simple projections, there is a risk that the gap in SDG outcomes between HICs and LICs will be wider in 2030 (29 points) than it was in 2015 (28 points).

[ODS 0 | page 15] Argument candidate:
  This means that we are at risk of losing a decade of progress towards convergence globally (Figure 1.2).

[ODS 0 | page 15] Argument candidate:
  The multiple geopolitical crises in the world today will no doubt place further obstacles on the path to 2030.

[ODS 0 | page 15] Argument candidate:
  If we look at each of the 17 individual SDGs, not a single SDG is projected to be met at the global level.

[ODS 0 | page 16] Argument candidate:
  Dire shortfalls in meeting the SDGs

[ODS 0 | page 16] Argument candidate:
  Current Nationally Determined Contribution (NDC) targets, if implemented, would still lead to around 2.4°C warming by 2100.

[ODS 0 | page 16] Argument candidate:
  Even taking the net-zero pledges of many countries into account, best-case scenarios given current pledges would lead to around 1.8°C warming by 2100.

[ODS 0 | page 16] Argument candidate:
  Water scarcity affects more than 40% of the world’s population.

[ODS 0 | page 16] Argument candidate:
  An estimated 1.8 billion people depend on drinking water contaminated by human waste.

[ODS 0 | page 16] Argument candidate:
  Unsustainable water management practices, including chemical discharges into water supply systems for irrigation, affect the functioning of ecosystems services.

[ODS 0 | page 16] Argument candidate:
  Global resource consumption assessments for rare earth elements are critical.

[ODS 0 | page 16] Argument candidate:
  Although reserves of these elements do not exist in concentrated clusters – which make them inefficient for mining – certain countries are quite dominant in this field, producing 98% of the world’s supply.

[ODS 0 | page 16] Argument candidate:
  As demand for rare earth elements is increasing tremendously, their scarcity is becoming more evident.

[ODS 0 | page 17] Argument candidate:
  The 2021 UN Food Systems Summit raised many urgent concerns around improving the sustainability, affordability, and quality of food across the world (SDG 2).

[ODS 0 | page 17] Argument candidate:
  Providing quality education (SDG 4) for all children is perhaps the single most important key to achieving sustainable development in the long term.

[ODS 0 | page 17] Argument candidate:
  The UN General Assembly’s Transforming Education Summit held in September 2022 was a critical meeting to spur national and global efforts to transform education to give all people the skills and knowledge to end poverty, protect the environment, and build peaceful and inclusive societies.

[ODS 0 | page 17] Argument candidate:
  Note: Projected gap by 2030 is based on extrapolation of annual growth rate on the SDG Index over the period 2019-2021. Pre-pandemic projected gap is based on an extrapolation of SDG Index annual growth rates over the period 2015-2019.

[ODS 0 | page 17] Argument candidate:
  Part 1. How to Achieve the SDGs: The SDSN Framework "planetary boundaries" that regulate the Earth system.

[ODS 0 | page 19] Argument candidate:
  Unless the SDGs are actively pursued, geophysical tipping points combined with technological disruptions could ignite disastrous social conflicts within and between nations.

[ODS 0 | page 19] Argument candidate:
  We firmly believe that international cooperation together with the achievement of the SDGs is the best preventative to this dire and growing risk, and represent an opportunity to create positive social tipping points: for example, through equal access to high-quality education (SDG 4), and by fighting all forms of inequalities, including income and wealth inequalities (SDG 10).

[ODS 0 | page 19] Argument candidate:
  Although all governments are in principle committed to economic justice as enshrined in the Universal Declaration of Human Rights, and to the SDG tenets of ‘leave no one behind’ and ‘reach the furthest behind first’, too few are living up to these commitments, especially as powerful groups block adequate public support for weaker groups.

[ODS 0 | page 19] Argument candidate:
  She noted however that, while disrupting the dynamic of racially discriminatory underdevelopment may require a greater transformation than is possible at this moment, the SDGs held untapped potential to advance both development and non-discrimination.

[ODS 0 | page 20] Argument candidate:
  Despite this ominous news, the SDGs are still achievable.

[ODS 0 | page 20] Argument candidate:
  None of their objectives are beyond our reach.12 Yes, the world is off-track, but that is all the more reason to double-down on the goals, rather than surrendering to human-made shortfalls in achieving them.

[ODS 0 | page 20] Argument candidate:
  At their core, the SDGs are an investment agenda.

[ODS 0 | page 21] Argument candidate:
  To achieve the SDGs, the world must invest boldly, amply, and consistently in all eight kinds of capital.

[ODS 0 | page 21] Argument candidate:
  These investments must involve both governments and corporations.

[ODS 0 | page 21] Argument candidate:
  For example, while business capital is mainly the purview of the private sector, human capital is mainly the purview of the public sector.

[ODS 0 | page 21] Argument candidate:
  Governments too must take the lead in protecting natural capital, while civil society especially must promote social and cultural capital, including mutual understanding across cultures and nations.

[ODS 0 | page 21] Argument candidate:
  Infrastructure capital and innovation capital tend to be financed roughly equally by the public and private sectors.

[ODS 0 | page 21] Argument candidate:
  For example, governments tend to finance power transmission grids, while the private sector tends to finance power generation.

[ODS 0 | page 21] Argument candidate:
  Governments generally finance basic scientific research, while businesses focus on applied R&D.

[ODS 0 | page 21] Argument candidate:
  Parallel to investing in the SDGs, the world needs to stop investing in activities that threaten planetary boundaries, destroy human and natural capital, and harm social cohesion.

[ODS 0 | page 21] Argument candidate:
  Curtailing the extraction and use of fossil fuels is of paramount importance.

[ODS 0 | page 21] Argument candidate:
  To curb harmful investments, regulatory measures, including fair and sustainable taxation and the dismantling of unsustainable subsidies, need to be an integral element of the SDG investment agenda.

[ODS 0 | page 21] Argument candidate:
  In 2022, the United Nations Secretary-General appointed a High-Level Advisory Board on Effective Multilateralism, with a mandate to develop a list of concrete, actionable recommendations to improve international cooperation and advance the 2030 Agenda for Sustainable Development.

[ODS 0 | page 21] Argument candidate:
  The Board’s 2023 report lists six areas for action that are directly aligned with the SDGs and SDSN’s recommendations: rebuilding trust in multilateralism, safeguarding our planet and its people, scaling up and improving the efficacy of global finance, improving data systems and their governance, and promoting peace.

[ODS 0 | page 21] Argument candidate:
  The most important level of decision-making remains the nation-state.

[ODS 0 | page 21] Argument candidate:
  Nation-states hold the primary responsibility for achieving the SDGs.

[ODS 0 | page 21] Argument candidate:
  They are members of the United Nations and the signatories of United Nations treaties.

[ODS 0 | page 21] Argument candidate:
  They hold juridical responsibility for implementing treaty agreements and the rest of the United Nations architecture, including the United Nations Charter, the Universal Declaration of Human Rights, and the SDGs.

[ODS 0 | page 21] Argument candidate:
  National governments must ensure both the domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 21] Argument candidate:
  Crucially, national government must also work with subnational governments to implement the SDG agenda at the local level, including sustainable urban infrastructure, delivery of social services, and ensuring safe communities.

[ODS 0 | page 21] Argument candidate:
  Virtually all governments of the world have embraced the SDGs in principle.

[ODS 0 | page 21] Argument candidate:
  188 of 193 UN Member States have submitted VNRs for comment by the other nations.

[ODS 0 | page 21] Argument candidate:
  Only five countries, notably the United States, Haiti, Myanmar, South Sudan, and Yemen, have never presented VNRs.

[ODS 0 | page 21] Argument candidate:
  Four of these countries are wracked by violence and poverty.

[ODS 0 | page 21] Argument candidate:
  The case of the United States stands as a glaring exception.

[ODS 0 | page 21] Argument candidate:
  The Nordic countries and European Union have shown considerable support for the SDGs.

[ODS 0 | page 21] Argument candidate:
  So too have many developing countries in the G20.

[ODS 0 | page 22] Argument candidate:
  Failures (and some successes) of national SDG governance

[ODS 0 | page 22] Argument candidate:
  The greatest responsibility for achieving the SDGs and safeguarding the planetary boundaries lies with the G20 members.

[ODS 0 | page 22] Argument candidate:
  The United States has so far shown very little commitment to the SDGs. We call on the United States to formulate an SDG action plan and to present a VNR to the High-Level Political Forum.

[ODS 0 | page 22] Argument candidate:
  The European Union – the world’s second-largest economy and its major lignite producer – has produced the European Green Deal (EGD), which is exemplary in many regards.

[ODS 0 | page 22] Argument candidate:
  In July 2023, the EU is set to present its first Union-wide voluntary review at the United Nations. This presents a good opportunity for the EU to send a strong message to the international community, and to demonstrate its commitment to and leadership on the SDGs.

[ODS 0 | page 23] Argument candidate:
  12th Five-Year Plan referred to the 2030 Agenda mainly in the context of international cooperation.

[ODS 0 | page 23] Argument candidate:
  China has reiterated its support for the SDGs, such as in greening its Belt and Road Initiative and launching the Global Development Initiative as a worldwide effort.

[ODS 0 | page 23] Argument candidate:
  A key measure for China will be the explicit integration of the SDGs’ domestic and international implementation into the 15th five-year plan (2026–2030).

[ODS 0 | page 23] Argument candidate:
  Some other G20 countries have shown weak commitments to the SDGs in recent years.

[ODS 0 | page 23] Argument candidate:
  Many of the poor performers, such as Brazil, recently elected new governments that have staked out a far more ambitious position vis-à-vis the SDGs.

[ODS 0 | page 23] Argument candidate:
  We urge all G20 governments to show the leadership required of them.

[ODS 0 | page 23] Argument candidate:
  Most of the low-income and lower-middle income countries, home to more than half of humanity, face major challenges in achieving most of the SDGs by 2030.

[ODS 0 | page 23] Argument candidate:
  Many of them lack an adequately high SDG commitment, and almost all lack access to the necessary financial means to implement the SDGs.

[ODS 0 | page 23] Argument candidate:
  At the midpoint of the 2030 Agenda, all countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national strategies, using the principles of the 2030 Agenda (transformative, integrated, inclusive, leaving no one behind) as a yardstick.

[ODS 0 | page 23] Argument candidate:

,prefix,model,ods,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,deepseek-r1-70b,0,53,374,142,0,232
1,GLOBAL SGD2023,deepseek-r1-70b,1,53,57,30,0,27
2,GLOBAL SGD2023,deepseek-r1-70b,2,53,20,13,0,7
3,GLOBAL SGD2023,deepseek-r1-70b,3,53,36,24,0,12
4,GLOBAL SGD2023,deepseek-r1-70b,4,53,41,27,1,13
5,GLOBAL SGD2023,deepseek-r1-70b,5,53,7,5,0,2
6,GLOBAL SGD2023,deepseek-r1-70b,6,53,8,7,0,1
7,GLOBAL SGD2023,deepseek-r1-70b,7,53,23,12,1,10
8,GLOBAL SGD2023,deepseek-r1-70b,8,53,74,31,1,42
9,GLOBAL SGD2023,deepseek-r1-70b,9,53,67,23,0,44
10,GLOBAL SGD2023,deepseek-r1-70b,10,53,40,21,0,19
11,GLOBAL SGD2023,deepseek-r1-70b,11,53,35,17,0,18
12,GLOBAL SGD2023,deepseek-r1-70b,12,53,27,18,0,9
13,GLOBAL SGD2023,deepseek-r1-70b,13,53,87,47,0,40
14,GLOBAL SGD2023,deepseek-r1-70b,14,53,14,10,0,4
15,GLOBAL SGD2023,deepseek-r1-70b,15,53,32,20,0,12
16,GLOBAL SGD2023,deepseek-r1-70b,16,53,68,29,0,39
17,GLOBAL SGD2023,deepseek-r1-70b,17,53,168,77,0,91

Stats overall for deepseek-r1-70b in document GLOBAL_SGD2023:

Updated overall summary:

,prefix,model,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,53,251,161,0,90
1,GLOBAL SGD2023,gemma3-4b,53,4093,706,2,3385
2,GLOBAL SGD2023,gemma3-27b,53,708,330,1,377
3,GLOBAL SGD2023,llama3.3-70b,53,817,477,4,336
4,GLOBAL SGD2023,deepseek-r1-70b,53,1178,553,3,622

## GLOBAL SDG 2025 report

### Qwen2.5-3b

In [ ]:
prefix = 'GLOBAL_SGD2025_'
model_name="qwen2.5-3b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')

display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

Stats by SDG for qwen2.5-3b in document GLOBAL_SGD2023_:

,prefix,model,ods,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,0,53,42,32,0,10
1,GLOBAL SGD2023,qwen2.5-3b,1,53,21,9,0,12
2,GLOBAL SGD2023,qwen2.5-3b,2,53,14,2,0,12
3,GLOBAL SGD2023,qwen2.5-3b,3,53,17,12,0,5
4,GLOBAL SGD2023,qwen2.5-3b,4,53,16,5,0,11
5,GLOBAL SGD2023,qwen2.5-3b,5,53,10,2,0,8
6,GLOBAL SGD2023,qwen2.5-3b,6,53,11,7,0,4
7,GLOBAL SGD2023,qwen2.5-3b,7,53,15,10,0,5
8,GLOBAL SGD2023,qwen2.5-3b,8,53,12,9,0,3
9,GLOBAL SGD2023,qwen2.5-3b,9,53,7,4,0,3
10,GLOBAL SGD2023,qwen2.5-3b,10,53,19,13,0,6
11,GLOBAL SGD2023,qwen2.5-3b,11,53,10,8,0,2
12,GLOBAL SGD2023,qwen2.5-3b,12,53,11,10,0,1
13,GLOBAL SGD2023,qwen2.5-3b,13,53,10,9,0,1
14,GLOBAL SGD2023,qwen2.5-3b,14,53,4,3,0,1
15,GLOBAL SGD2023,qwen2.5-3b,15,53,1,1,0,0
16,GLOBAL SGD2023,qwen2.5-3b,16,53,14,10,0,4
17,GLOBAL SGD2023,qwen2.5-3b,17,53,17,15,0,2

Stats overall for qwen2.5-3b in document GLOBAL_SGD2023_:

Updated overall summary:

,prefix,model,ods_max,pages_max,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,17,53,251,161,0,90

### Gemma3 4B

In [ ]:
prefix = 'GLOBAL_SGD2025_'
model_name="gemma3-4b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')

display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

[ODS 0 | page 7] Argument candidate:
  At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.

[ODS 0 | page 7] Argument candidate:
  None of their objectives are beyond our reach.

[ODS 0 | page 7] Argument candidate:
  The SDGs are still achievable.

[ODS 0 | page 7] Argument candidate:
  It is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.

[ODS 0 | page 7] Argument candidate:
  To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.

[ODS 0 | page 7] Argument candidate:
  The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 7] Argument candidate:
  Greatly increase funding to national and subnational governments and private businesses, especially in LICs and LMICs, to carry out needed SDG investments.

[ODS 0 | page 7] Argument candidate:
  Revise the credit rating system and debt sustainability metrics to facilitate long-term sustainable development.

[ODS 0 | page 7] Argument candidate:
  Revise liquidity structures for LICs and LMICs, especially regarding sovereign debts, to forestall self-fulfilling banking and balance-of-payments crises

[ODS 0 | page 7] Argument candidate:
  Create ambitious, internationally-agreed upon criteria for sustainable finance that are mandatory for all public financial institutions.

[ODS 0 | page 7] Argument candidate:
  Align private business investment flows with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 7] Argument candidate:
  Reform current institutional frameworks and develop new mechanisms to improve the quality and speed of deployment of international cooperation, and monitor progress in an open and timely manner.

[ODS 0 | page 7] Argument candidate:
  All countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national SDG strategies and commit to strengthening multilateralism.

[ODS 0 | page 7] Argument candidate:
  National governments must ensure both domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation – by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 7] Argument candidate:
  Achieving the SDGs requires global cooperation guided by the United Nations Charter.

[ODS 0 | page 8] Argument candidate:
  Further investment is needed in statistical capacity and data literacy to support long-term pathways for key SDG transformations.

[ODS 0 | page 8] Argument candidate:
  At the halfway mark to 2030, there remains a great deal of work to be done to improve the data and methods underlying the SDG indicator framework.

[ODS 0 | page 8] Argument candidate:
  investing in statistical capacity, science, and data literacy are important priorities for achieving the SDGs.

[ODS 0 | page 8] Argument candidate:
  All UN Member States and UN agencies can count on the continued efforts and energies of the SDSN around the world to support all governments, businesses, and civil society in embracing and aligning with the SDGs

[ODS 0 | page 13] Argument candidate:
  UN Member States should adopt an SDG Stimulus, to close the massive financing gap faced by many developing economies.

[ODS 0 | page 13] Argument candidate:
  Increased funding from the multilateral development banks (MDBs) and public development banks (PDBs) to low- and middle-income countries, linked to investments in the SDGs;

[ODS 0 | page 13] Argument candidate:
  Enhancement of relief for countries facing debt distress;

[ODS 0 | page 13] Argument candidate:
  Expansion of liquidity by the International Monetary Fund (IMF) and major central banks;

[ODS 0 | page 13] Argument candidate:
  Empowerment and expansion of the specialized global funds;

[ODS 0 | page 13] Argument candidate:
  Expansion of private philanthropy with a focus on ultra-high-net-worth individuals.

[ODS 0 | page 13] Argument candidate:
  UN Member States must endorse a deep and overdue reform of the global financial architecture.

[ODS 0 | page 13] Argument candidate:
  Greatly increased funding for national and subnational governments and private businesses in the emerging economies, especially the low-income countries (LICs) and lower-middle-income countries (LMICs), to carry out needed SDG actions;

[ODS 0 | page 13] Argument candidate:
  Revision of the credit-rating system and debt-sustainability metrics to facilitate long-term sustainable development;

[ODS 0 | page 13] Argument candidate:
  Revision of the liquidity structures for LICs and LMICs, especially regarding sovereign debt, to forestall self-fulfilling banking and balance-of-payments crises;

[ODS 0 | page 13] Argument candidate:
  Creation of ambitious, internationally-agreed criteria for sustainable finance that are mandatory for all public financial institutions in high-income countries (HICs), middle-income countries (MICs), and LICs alike.

[ODS 0 | page 13] Argument candidate:
  Alignment of private business investment flows in all countries with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 13] Argument candidate:
  A reform of current institutional frameworks and development of new and innovative mechanisms to improve the quality and speed of deployment of international cooperation, and the monitoring of progress in an open and timely manner.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of ‘leave no one behind’.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should present, at regular intervals, their national SDG frameworks in the form of Voluntary National Reviews (VNRs).

[ODS 0 | page 14] Argument candidate:
  All UN Member States should recommit to peaceful cooperation, in the service of the SDGs and all other multilateral agreements.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should commit to accelerating SDG progress to 2030, and to setting even more ambitious SDG targets to 2050, incorporating the recent Kunming-Montreal Biodiversity Framework and the High Seas Treaty.

[ODS 0 | page 15] Argument candidate:
  national governments on all continents have fallen short in integrating the SDGs into national policies and public investments

[ODS 0 | page 15] Argument candidate:
  they are grounded in the Universal Declaration of Human Rights, which celebrates its 75th anniversary this year

[ODS 0 | page 15] Argument candidate:
  that "All human beings are born free and equal in dignity and rights … and should act towards one another in a spirit of brotherhood"

[ODS 0 | page 15] Argument candidate:
  that "it is essential to promote the development of friendly relations between nations"

[ODS 0 | page 15] Argument candidate:
  social justice and sustainable development require the full realization of the rights of all people

[ODS 0 | page 15] Argument candidate:
  includes equality of opportunities for girls and women (SDG 5)

[ODS 0 | page 15] Argument candidate:
  respect for the rights and voice of Indigenous peoples around the world

[ODS 0 | page 15] Argument candidate:
  a much larger role for young people, who will face the consequences of our (in)actions throughout the 21st century

[ODS 0 | page 15] Argument candidate:
  They are not only a public policy framework; they are an ethical imperative

[ODS 0 | page 15] Argument candidate:
  Members of the SDSN Leadership Council offer the following assessments and recommendations to the UN Member States, the United Nations Agencies, international finance institutions, business, and civil society, based on more than a decade of research, measurement, advising, and partnerships across the world

[ODS 0 | page 16] Argument candidate:
  Dire shortfalls in meeting the SDGs to reaching a disastrous 2.8°C warming by 2100.

[ODS 0 | page 16] Argument candidate:
  Current Nationally Determined Contribution (NDC) targets, if implemented, would still lead to around 2.4°C warming by 2100.

[ODS 0 | page 16] Argument candidate:
  Biodiversity targets (SDG 15 and targets agreed under the CBD) are also at grave risk.

[ODS 0 | page 16] Argument candidate:
  Global resource consumption assessments for rare earth elements are critical.

[ODS 0 | page 16] Argument candidate:
  Ocean goods and services (SDG 14 and the High Seas Treaty) are at severe risk due to full- to over-exploitation

[ODS 0 | page 17] Argument candidate:
  Providing quality education (SDG 4) for all children is perhaps the single most important key to achieving sustainable development in the long term.

[ODS 0 | page 17] Argument candidate:
  The UN General Assembly’s Transforming Education Summit held in September 2022 was a critical meeting to spur national and global efforts to transform education to give all people the skills and knowledge to end poverty, protect the environment, and build peaceful and inclusive societies.

[ODS 0 | page 17] Argument candidate:
  And yet, the truth remains that hundreds of millions of children are either out of school entirely or receiving such an under-funded and under-resourced education that they are failing to achieve basic literacy and numeracy even after several years of education.

[ODS 0 | page 18] Argument candidate:
  The latest scientific assessments indicate that six of the nine planetary boundaries have been breached.

[ODS 0 | page 18] Argument candidate:
  Scientists have identified a large number of extremely dangerous potential tipping points, with linkages and dependencies across the different planetary boundaries.

[ODS 0 | page 18] Argument candidate:
  Human-induced global warming could hit several tipping points that may in turn lead to further feedbacks (amplifications) of the warming.

[ODS 0 | page 19] Argument candidate:
  Unless the SDGs are actively pursued, geophysical tipping points combined with technological disruptions could ignite disastrous social conflicts within and between nations.

[ODS 0 | page 19] Argument candidate:
  We firmly believe that international cooperation together with the achievement of the SDGs is the best preventative to this dire and growing risk, and represent an opportunity to create positive social tipping points: for example, through equal access to high-quality education (SDG 4), and by fighting all forms of inequalities, including income and wealth inequalities (SDG 10).

[ODS 0 | page 19] Argument candidate:
  Although all governments are in principle committed to economic justice as enshrined in the Universal Declaration of Human Rights, and to the SDG tenets of ‘leave no one behind’ and ‘reach the furthest behind first’, too few are living up to these commitments, especially as powerful groups block adequate public support for weaker groups.

[ODS 0 | page 19] Argument candidate:
  The report’s recommendations include calling for more racially-disaggregated SDG indicators and for dialogue with stakeholders on how to use these indicators to better allocate resources and prioritize the inclusion of marginalized peoples.

[ODS 0 | page 20] Argument candidate:
  the SDGs are woefully underfunded at home and internationally

[ODS 0 | page 20] Argument candidate:
  None of their objectives are beyond our reach

[ODS 0 | page 20] Argument candidate:
  the world must devote an increased portion of current output to building up sustainable capital assets for the future

[ODS 0 | page 20] Argument candidate:
  the world must both shift its current investment patterns and increase the overall investment flow in order to build the future we want

[ODS 0 | page 20] Argument candidate:
  Human capital: The skills and health of a productive citizenry, supported by universal health access and coverage, quality education, shared data and knowledge, promotion of a culture of peace and non-violence, global citizenship, and the appreciation of cultural diversity

[ODS 0 | page 20] Argument candidate:
  Natural capital: The capacity and healthy functioning of ecosystems, to be protected by ending human-induced climate change, protecting biodiversity, sustainably managing freshwater resources, and eliminating toxic pollutants

[ODS 0 | page 21] Argument candidate:
  To achieve the SDGs, the world must invest boldly, amply, and consistently in all eight kinds of capital.

[ODS 0 | page 21] Argument candidate:
  Governments too must take the lead in protecting natural capital, while civil society especially must promote social and cultural capital, including mutual understanding across cultures and nations.

[ODS 0 | page 21] Argument candidate:
  Crucially, national government must also work with subnational governments to implement the SDG agenda at the local level, including sustainable urban infrastructure, delivery of social services, and ensuring safe communities.

[ODS 0 | page 21] Argument candidate:
  Virtually all governments of the world have embraced the SDGs in principle. 188 of 193 UN Member States have submitted VNRs for comment by the other nations.

[ODS 0 | page 21] Argument candidate:
  Only five countries, notably the United States, Haiti, Myanmar, South Sudan, and Yemen, have never presented VNRs.

[ODS 0 | page 22] Argument candidate:
  The greatest responsibility for achieving the SDGs and safeguarding the planetary boundaries lies with the G20 members.

[ODS 0 | page 22] Argument candidate:
  With the 2022 Inflation Reduction Act, the Biden government announced its intention to reduce carbon emissions by roughly 40 percent from 2005 levels by 2030, although there are growing concerns that outcomes will lag behind these goals, due in part to the legislation’s lack of an agreed national financing strategy other than tax credits.

[ODS 0 | page 22] Argument candidate:
  The European Union – the world’s second-largest economy and its major lignite producer – has produced the European Green Deal (EGD), which is exemplary in many regards.

[ODS 0 | page 22] Argument candidate:
  Many EU member states demonstrate a high or moderate SDG commitment.

[ODS 0 | page 22] Argument candidate:
  The EGD embraces an EU-wide set of goals, timelines to 2050, and financing strategies across major dimensions of the SDGs: energy decarbonization, climate resilience, circular economy (to cut pollution), sustainable agriculture (the ‘farm-to-fork’ strategy), digital access, and innovation.

[ODS 0 | page 22] Argument candidate:
  The European Regional Development Fund, which provides the EU cohesion funds, is also directed towards the EGD.

[ODS 0 | page 22] Argument candidate:
  The SDSN Framework in the context of international cooperation.

[ODS 0 | page 23] Argument candidate:
  China has reiterated its support for the SDGs, such as in greening its Belt and Road Initiative and launching the Global Development Initiative as a worldwide effort.

[ODS 0 | page 23] Argument candidate:
  At the midpoint of the 2030 Agenda, all countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national strategies, using the principles of the 2030 Agenda (transformative, integrated, inclusive, leaving no one behind) as a yardstick.

[ODS 0 | page 23] Argument candidate:
  Four basic failures stand out: First, implementation is largely left to the national level and on a voluntary basis, without effective multilateral enforcement mechanisms in place.

[ODS 0 | page 23] Argument candidate:
  Developed countries are not being held to account, neither for their adverse spillovers, nor for ensuring adequate flows of financing for sustainable development.

[ODS 0 | page 23] Argument candidate:
  There are no assessments or recommendations by the respective secretariats or decision-making bodies on the adequacy or further enhancement of national implementation, let alone measures of enforcement.

[ODS 0 | page 24] Argument candidate:
  Greatly increase funding to national and subnational governments and private businesses in the emerging economies, especially the LICs and LMICs, to carry out the needed investments.

[ODS 0 | page 24] Argument candidate:
  Revise liquidity structures for LICs,LMICs, and SIDS, especially regarding sovereign debts, to forestall self-fulfilling banking and balance-of-payments crises.

[ODS 0 | page 24] Argument candidate:
  Create ambitious and internationally-agreed upon criteria for sustainable finance that are mandatory for all public financial institutions in HICs, MICs, and LICs alike.

[ODS 0 | page 24] Argument candidate:
  Align private business investment flows in all countries with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 24] Argument candidate:
  Reform current institutional frameworks and develop new, innovative mechanisms to improve the quality and speed of deployment of international cooperation, and monitor progress in an open and timely manner.

[ODS 0 | page 25] Argument candidate:
  Overhauling global governance mechanisms and the global financial architecture is fundamental to unlocking needed investments for sustainable development and ending non-sustainable practices.

[ODS 0 | page 25] Argument candidate:
  The SDGs call for lasting, long-term, directed change.

[ODS 0 | page 25] Argument candidate:
  For governments to combine the objectives of economic development, social inclusion, transparency, energy decarbonization, climate adaptation, water resources and sanitation, biodiversity conservation, digital access, gender equality, circular economy, over-harvesting, universal education, is daunting.

[ODS 0 | page 26] Argument candidate:
  Long-term investment plans are essential for national success in meeting the SDGs.

[ODS 0 | page 26] Argument candidate:
  SDSN has recommended six inter-related long-term transformations: Universal quality education and innovation-based economy, Universal health access and coverage, Zero-carbon energy systems, Sustainable ecosystems, sustainable agriculture, and climate resilience, Sustainable cities, Transformation to universal digital access and services

[ODS 0 | page 26] Argument candidate:
  None can be solved by the private sector alone; indeed, governments will have to take the lead to design policy and financial frameworks within which business can profitably invest and innovate.

[ODS 0 | page 26] Argument candidate:
  The Sustainable Development Report 2023 identifies five levers to be deployed to bring about the necessary transformations: governance, economy and finance, individual and collective action, science and technology, and capacity building.

[ODS 0 | page 26] Argument candidate:
  Planning for the long term, however, illuminates the global financial architecture’s Achilles heel. While the high-income countries (HICs) and upper-middle income countries (UMICs) can and should, in principle, finance these transformations via a combination of budget outlays, public-sector borrowing, and private financing (equity and debt), this is surely not true of the low-Income countries (LICs) and the lower middle-income countries

[ODS 0 | page 27] Argument candidate:
  Increased funding from the Multilateral Development Banks (MDBs) and Public Development Banks (PDBs) to developing countries, linked to investments in the SDGs

[ODS 0 | page 27] Argument candidate:
  an additional US$500 billion per year by 2025 of SDG finance

[ODS 0 | page 27] Argument candidate:

,prefix,model,ods,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL_SGD2023_,qwen2.5-3b,0,53,42,32,0,10
1,GLOBAL_SGD2023_,qwen2.5-3b,1,53,21,9,0,12
2,GLOBAL_SGD2023_,qwen2.5-3b,2,53,14,2,0,12
3,GLOBAL_SGD2023_,qwen2.5-3b,3,53,17,12,0,5
4,GLOBAL_SGD2023_,qwen2.5-3b,4,53,16,5,0,11
5,GLOBAL_SGD2023_,qwen2.5-3b,5,53,10,2,0,8
6,GLOBAL_SGD2023_,qwen2.5-3b,6,53,11,7,0,4
7,GLOBAL_SGD2023_,qwen2.5-3b,7,53,15,10,0,5
8,GLOBAL_SGD2023_,qwen2.5-3b,8,53,12,9,0,3
9,GLOBAL_SGD2023_,qwen2.5-3b,9,53,7,4,0,3
10,GLOBAL_SGD2023_,qwen2.5-3b,10,53,19,13,0,6
11,GLOBAL_SGD2023_,qwen2.5-3b,11,53,10,8,0,2
12,GLOBAL_SGD2023_,qwen2.5-3b,12,53,11,10,0,1
13,GLOBAL_SGD2023_,qwen2.5-3b,13,53,10,9,0,1
14,GLOBAL_SGD2023_,qwen2.5-3b,14,53,4,3,0,1
15,GLOBAL_SGD2023_,qwen2.5-3b,15,53,1,1,0,0
16,GLOBAL_SGD2023_,qwen2.5-3b,16,53,14,10,0,4
17,GLOBAL_SGD2023_,qwen2.5-3b,17,53,17,15,0,2
18,GLOBAL SGD2023,gemma3-4b,0,53,304,167,1,136
19,GLOBAL SGD2023,gemma3-4b,1,53,199,48,0,151
20,GLOBAL SGD2023,gemma3-4b,2,53,248,27,0,221
21,GLOBAL SGD2023,gemma3-4b,3,53,228,36,0,192
22,GLOBAL SGD2023,gemma3-4b,4,53,229,27,1,201
23,GLOBAL SGD2023,gemma3-4b,5,53,181,23,0,158
24,GLOBAL SGD2023,gemma3-4b,6,53,221,26,0,195
25,GLOBAL SGD2023,gemma3-4b,7,53,246,26,0,220
26,GLOBAL SGD2023,gemma3-4b,8,53,252,36,0,216
27,GLOBAL SGD2023,gemma3-4b,9,53,241,37,0,204
28,GLOBAL SGD2023,gemma3-4b,10,53,229,46,0,183
29,GLOBAL SGD2023,gemma3-4b,11,53,247,19,0,228
30,GLOBAL SGD2023,gemma3-4b,12,53,239,24,0,215
31,GLOBAL SGD2023,gemma3-4b,13,53,168,36,0,132
32,GLOBAL SGD2023,gemma3-4b,14,53,221,21,0,200
33,GLOBAL SGD2023,gemma3-4b,15,53,182,19,0,163
34,GLOBAL SGD2023,gemma3-4b,16,53,220,41,0,179
35,GLOBAL SGD2023,gemma3-4b,17,53,238,47,0,191

Stats overall for gemma3-4b in document GLOBAL_SGD2023_:

Updated overall summary:

,prefix,model,ods_max,pages_max,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,17,53,251,161,0,90
1,GLOBAL_SGD2023_,qwen2.5-3b,17,53,4344,867,2,3475

### Gemma3 27B

In [ ]:
prefix = 'GLOBAL_SGD2025'
model_name="gemma3-27b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')
display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

[ODS 0 | page 7] Argument candidate:
  At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.

[ODS 0 | page 7] Argument candidate:
  Despite this alarming development, the SDGs are still achievable.

[ODS 0 | page 7] Argument candidate:
  None of their objectives are beyond our reach.

[ODS 0 | page 7] Argument candidate:
  The world is off track, but that is all the more reason to double down on the SDGs.

[ODS 0 | page 7] Argument candidate:
  At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.

[ODS 0 | page 7] Argument candidate:
  To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.

[ODS 0 | page 7] Argument candidate:
  The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 7] Argument candidate:
  All countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national SDG strategies and commit to strengthening multilateralism.

[ODS 0 | page 7] Argument candidate:
  National governments must ensure both domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation – by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 7] Argument candidate:
  Achieving the SDGs requires global cooperation guided by the United Nations Charter.

[ODS 0 | page 7] Argument candidate:
  SDG transformations.

[ODS 0 | page 8] Argument candidate:
  Further investment is needed in statistical capacity and data literacy to support long-term pathways for key SDG transformations.

[ODS 0 | page 8] Argument candidate:
  At the halfway mark to 2030, there remains a great deal of work to be done to improve the data and methods underlying the SDG indicator framework.

[ODS 0 | page 8] Argument candidate:
  The SDSN was created in 2012, soon after the Rio+20 Summit, to mobilize the world’s universities, think tanks, and national laboratories on behalf of the SDGs.

[ODS 0 | page 8] Argument candidate:
  Via science-based pathways and analytics, the SDSN supports discussions on SDG implementation at the global, regional, and national levels.

[ODS 0 | page 8] Argument candidate:
  All UN Member States and UN agencies can count on the continued efforts and energies of the SDSN around the world to support all governments, businesses, and civil society in embracing and aligning with the SDGs on sustainable development.

[ODS 0 | page 13] Argument candidate:
  At the midpoint of the 2030 Agenda, the SDGs are far off track.

[ODS 0 | page 13] Argument candidate:
  SDSN offers the following recommendations to accelerate progress over the remaining seven years to 2030, and to set even more ambitious targets to be achieved by 2050 under the SDG framework.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of ‘leave no one behind’.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should present, at regular intervals, their national SDG frameworks in the form of Voluntary National Reviews (VNRs).

[ODS 0 | page 14] Argument candidate:
  All UN Member States should recommit to peaceful cooperation, in the service of the SDGs and all other multilateral agreements.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should commit to accelerating SDG progress to 2030, and to setting even more ambitious SDG targets to 2050, incorporating the recent Kunming-Montreal Biodiversity Framework and the High Seas Treaty.

[ODS 0 | page 15] Argument candidate:
  The SDGs are facing strong headwinds.

[ODS 0 | page 15] Argument candidate:
  Despite significant efforts in some places, national governments on all continents have fallen short in integrating the SDGs into national policies and public investments.

[ODS 0 | page 15] Argument candidate:
  We emphasize that achieving the SDGs rests on five pillars of good governance:

[ODS 0 | page 15] Argument candidate:
  The SDGs are not only a public policy framework; they are an ethical imperative.

[ODS 0 | page 15] Argument candidate:
  The SDGs are seriously off track (Figure 1.1).

[ODS 0 | page 15] Argument candidate:
  According to the annual SDG Index, global achievement of the SDGs rose only slightly, from 64 percent in 2015 to 66 percent in 2019 – far too slowly to meet the goals by 2030, and with highly uneven progress within and between countries.

[ODS 0 | page 15] Argument candidate:
  At current trends, based on simple projections, there is a risk that the gap in SDG outcomes between HICs and LICs will be wider in 2030 (29 points) than it was in 2015 (28 points).

[ODS 0 | page 15] Argument candidate:
  The multiple geopolitical crises in the world today will no doubt place further obstacles on the path to 2030.

[ODS 0 | page 15] Argument candidate:
  If we look at each of the 17 individual SDGs, not a single SDG is projected to be met at the global level.

[ODS 0 | page 17] Argument candidate:
  The World Bank. 2017. Atlas of Sustainable Development Goals.

[ODS 0 | page 17] Argument candidate:
  Providing quality education (SDG 4) for all children is perhaps the single most important key to achieving sustainable development in the long term.

[ODS 0 | page 19] Argument candidate:
  Unless the SDGs are actively pursued, geophysical tipping points combined with technological disruptions could ignite disastrous social conflicts within and between nations.

[ODS 0 | page 19] Argument candidate:
  We firmly believe that international cooperation together with the achievement of the SDGs is the best preventative to this dire and growing risk, and represent an opportunity to create positive social tipping points.

[ODS 0 | page 19] Argument candidate:
  Although all governments are in principle committed to economic justice as enshrined in the Universal Declaration of Human Rights, and to the SDG tenets of ‘leave no one behind’ and ‘reach the furthest behind first’, too few are living up to these commitments.

[ODS 0 | page 19] Argument candidate:
  The report’s recommendations include calling for more racially-disaggregated SDG indicators and for dialogue with stakeholders on how to use these indicators to better allocate resources and prioritize the inclusion of marginalized peoples.

[ODS 0 | page 20] Argument candidate:
  Despite this ominous news, the SDGs are still achievable.

[ODS 0 | page 20] Argument candidate:
  None of their objectives are beyond our reach.

[ODS 0 | page 20] Argument candidate:
  Yes, the world is off-track, but that is all the more reason to double-down on the goals, rather than surrendering to human-made shortfalls in achieving them.

[ODS 0 | page 20] Argument candidate:
  At their core, the SDGs are an investment agenda.

[ODS 0 | page 20] Argument candidate:
  In the most basic terms, the world must devote an increased portion of current output to building up sustainable capital assets for the future, and must deploy such assets effectively.

[ODS 0 | page 21] Argument candidate:
  To achieve the SDGs, the world must invest boldly, amply, and consistently in all eight kinds of capital.

[ODS 0 | page 21] Argument candidate:
  In 2022, the United Nations Secretary-General appointed a High-Level Advisory Board on Effective Multilateralism, with a mandate to develop a list of concrete, actionable recommendations to improve international cooperation and advance the 2030 Agenda for Sustainable Development.

[ODS 0 | page 21] Argument candidate:
  Nation-states hold the primary responsibility for achieving the SDGs.

[ODS 0 | page 21] Argument candidate:
  They hold juridical responsibility for implementing treaty agreements and the rest of the United Nations architecture, including the United Nations Charter, the Universal Declaration of Human Rights, and the SDGs.

[ODS 0 | page 21] Argument candidate:
  Virtually all governments of the world have embraced the SDGs in principle.

[ODS 0 | page 21] Argument candidate:
  188 of 193 UN Member States have submitted VNRs for comment by the other nations.

[ODS 0 | page 22] Argument candidate:
  We call on the United States to formulate an SDG action plan and to present a VNR to the High-Level Political Forum.

[ODS 0 | page 22] Argument candidate:
  In July 2023, the EU is set to present its first Union-wide voluntary review at the United Nations.

[ODS 0 | page 22] Argument candidate:
  China has already presented two VNRs to the HLPF (2016 and 2021).

[ODS 0 | page 23] Argument candidate:
  Recently, China has reiterated its support for the SDGs, such as in greening its Belt and Road Initiative and launching the Global Development Initiative as a worldwide effort.

[ODS 0 | page 23] Argument candidate:
  A key measure for China will be the explicit integration of the SDGs’ domestic and international implementation into the 15th five-year plan (2026–2030).

[ODS 0 | page 23] Argument candidate:
  At the midpoint of the 2030 Agenda, all countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national strategies, using the principles of the 2030 Agenda (transformative, integrated, inclusive, leaving no one behind) as a yardstick.

[ODS 0 | page 23] Argument candidate:
  Achieving the SDGs will require a transformative global approach.

[ODS 0 | page 23] Argument candidate:
  Both the 2030 Agenda and the Paris Climate Agreement established mechanisms to encourage and monitor their implementation by nation-states.

[ODS 0 | page 23] Argument candidate:
  However, experience so far with VNRs and Nationally Determined Contributions (NDCs), respectively, demonstrate that these mechanisms – despite some progress – have not delivered the effort necessary to achieve global goals.

[ODS 0 | page 24] Argument candidate:
  International cooperation is trapped by bureaucratic institutional frameworks that reduce the speed, efficacy, and efficiency of funding to meet the SDGs, and that fail to provide the framework for large-scale SDG financing.

[ODS 0 | page 24] Argument candidate:
  Align private business investment flows in all countries with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 26] Argument candidate:
  Long-term investment plans are essential for national success in meeting the SDGs.

[ODS 0 | page 26] Argument candidate:
  SDSN has recommended six inter-related long-term transformations:20

[ODS 0 | page 26] Argument candidate:
  1. Universal quality education and innovation-based economy

[ODS 0 | page 26] Argument candidate:
  2. Universal health access and coverage

[ODS 0 | page 26] Argument candidate:
  3. Zero-carbon energy systems

[ODS 0 | page 26] Argument candidate:
  4. Sustainable ecosystems, sustainable agriculture, and climate resilience

[ODS 0 | page 26] Argument candidate:
  5. Sustainable cities

[ODS 0 | page 26] Argument candidate:
  6. Transformation to universal digital access and services

[ODS 0 | page 27] Argument candidate:
  In his opening address to the UN General Assembly on September 20, 2022, UN Secretary-General António Guterres called on the G20 to launch an “SDG Stimulus” to offset the deteriorating market conditions faced by developing countries and to accelerate progress towards the SDGs and the Paris Climate Agreement.

[ODS 0 | page 27] Argument candidate:
  The SDG Stimulus plan recommended by the High-Level Working Group and introduced by SG Guterres last February25 has five main components:

[ODS 0 | page 27] Argument candidate:
  Increased funding from the Multilateral Development Banks (MDBs) and Public Development Banks (PDBs) to developing countries, linked to investments in the SDGs, a need echoed in the 2023 report of the High-Level Advisory Board on Effective Multilateralism26

[ODS 0 | page 28] Argument candidate:
  All United Nations agencies should put the SDGs at the centerpiece of their strategies, programs, and reporting.

[ODS 0 | page 28] Argument candidate:
  The World Bank and the other MDBs should put the SDGs at the center of their financing strategies, performance reviews, and reporting.

[ODS 0 | page 28] Argument candidate:
  The IMF should build its national reviews (Article IV), debt sustainability framework (DSF), and country programming around the public policies and financing needed for national success in achieving the SDGs.

[ODS 0 | page 28] Argument candidate:
  The G20 should organize its financial cooperation, reporting, and metrics around the reform of the GFA, as needed to achieve the SDGs.

[ODS 0 | page 28] Argument candidate:
  All UN Member States should present VNRs at least once every three years.

[ODS 0 | page 28] Argument candidate:
  It is especially urgent that the five countries that have not yet presented VNRs should do so no later than 2024.

[ODS 0 | page 28] Argument candidate:
  United Nations agencies, multilateral organizations, and Member States need to increase investment in, and coordination of, national and international data and statistical systems and scientific capacity to assess SDG progress and support sustainable development decision making and investment, including disaggregated data by region, social stratification, and other criteria as helpful.

[ODS 0 | page 29] Argument candidate:
  SDSN is closely following and supporting the EU’s endeavors to achieve the SDGs, inter alia by the EU’s European Green Deal.

[ODS 0 | page 29] Argument candidate:
  SDSN is supporting the African Development Bank to develop a strategic plan to accelerate Africa’s sustainable development, with the aim of the African Union achieving high-income status and sustainable development by 2063, the 100th anniversary of the Organization of African Unity.

[ODS 0 | page 29] Argument candidate:
  SDSN is supporting the African Development Bank to develop a strategic plan to accelerate Africa’s sustainable development

[ODS 0 | page 29] Argument candidate:
  SDSN recognizes this gap in the practical means of implementation of city governments, and is currently working with the major urban think tanks and global urban networks (including the C40 and ICLEI) to address the challenge of sub-national financing of the SDGs.

[ODS 0 | page 30] Argument candidate:
  SDG 16 recognizes the vital role of peaceful and inclusive societies, and SDG 17 underscores the need for global outreach and cooperation to achieve the Goals.

[ODS 0 | page 30] Argument candidate:
  The SDSN was created in 2012, soon after the Rio+20 Summit which mobilized the world’s universities, think tanks, and national laboratories on behalf of the SDGs.

[ODS 0 | page 30] Argument candidate:
  We aim to ensure that institutions of higher learning and public policy research centres in all 193 UN Member States are actively part of the SDSN.

[ODS 0 | page 30] Argument candidate:
  SDSN is working closely with the UNESCO SDG 4 High-Level Steering Committee on these two major issues, via Mission 4.7 through an SDG Academy Partnership with the Open Education Resources Recommendation team at UNESCO.

[ODS 0 | page 31] Argument candidate:
  They are the work of the 21st century.

[ODS 0 | page 31] Argument candidate:
  These are signal achievements of humanity, to have come together across all nations to adopt a common set of challenges.

[ODS 0 | page 31] Argument candidate:
  At the mid-point of the SDG agenda, we are far off target.

[ODS 0 | page 32] Argument candidate:
  First, that UN Member States, at the 2023 SDG Summit and the 2024 Summit of the Future, recommit boldly, strongly, and proactively to the SDGs, accelerate progress to 2030, and adopt even more ambitious SDG targets and objectives to mid-century, also incorporating recent international agreements on oceans and biodiversity.

[ODS 0 | page 32] Argument candidate:
  Second, UN Member States, starting with the G20 meeting this September in India, should adopt an SDG Stimulus to accelerate progress towards the SDGs by 2030 and enhance global governance for enforcing the implementation of the SDGs by all countries.

[ODS 0 | page 34] Argument candidate:
  The SDG Index and Dashboards track the annual progress of all 193 UN Member States towards the SDGs.

[ODS 0 | page 34] Argument candidate:
  At the midpoint of the 2030 Agenda, however, the SDGs are far off track.

[ODS 0 | page 34] Argument candidate:
  The SDG Index is an assessment of each country’s overall performance on the 17 SDGs, giving equal weight to each Goal.

[ODS 0 | page 34] Argument candidate:
  The dashboard and trend arrows help identify priorities for further actions and indicate whether countries are on track or off track to achieve the goals and targets by 2030, based on latest trend data.

[ODS 0 | page 38] Argument candidate:
  As detailed in the Europe Sustainable Development Report 2022, trends on several leave-no-one-behind indicators are not heading in the right direction in many EU member states (Lafortune et al. 2022).

[ODS 0 | page 43] Argument candidate:
  The 2030 Agenda and the SDGs recognize the importance of international spillovers in several crucial ways.

[ODS 0 | page 43] Argument candidate:
  SDG 17 (Partnerships for the Goals) calls for ‘policy coherence’ for sustainable development.

[ODS 0 | page 43] Argument candidate:
  SDG 17 (Partnerships for the Goals) calls on all countries to enhance policy coherence for sustainable development (PCSD).

[ODS 0 | page 58] Argument candidate:
  There was no expectation in 2015, when the SDGs and Agenda 2030 were adopted, that all goals and targets would be achieved at their midpoint.

[ODS 0 | page 58] Argument candidate:
  By 2023, one would expect that most countries would have implemented ambitious policy, regulatory and investment frameworks compatible with achieving major SDG transformations.

[ODS 0 | page 58] Argument candidate:
  It could also be expected that all countries would have at least once documented their progress and their plans for achieving the SDGs in a Voluntary National Review (VNRs) presented at the United Nations.

[ODS 0 | page 58] Argument candidate:
  Nation-states continue to hold the primary responsibility for achieving the SDGs.

[ODS 0 | page 59] Argument candidate:
  By July 2023, all UN Member States will have presented a VNR except for Haiti, Myanmar, South Sudan, the United States and Yemen.

[ODS 0 | page 59] Argument candidate:
  Official high-level speeches and the preparation of VNRs (as the official government-led process to report on SDG progress, gaps, and policy efforts) provide relevant proxies to gauge political commitment to the SDGs.

[ODS 0 | page 62] Argument candidate:
  since 2016, 188 UN Member States have prepared VNRs (see Figure 3.2).

[ODS 0 | page 62] Argument candidate:
  At the midpoint of the 2030 Agenda, only five countries have never submitted a VNR, among them the United States (HLPF, 2023).

[ODS 0 | page 62] Argument candidate:
  Some countries take a mainstreaming approach, where SDGs are implemented by each government ministry within the scope of its mandate (instead of via an overarching national action plan).

[ODS 0 | page 62] Argument candidate:
  For many, this takes the form of a national sustainability strategy explicitly linked to the 2030 Agenda goals and targets.

[ODS 0 | page 62] Argument candidate:

,prefix,model,ods,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,gemma3-27b,0,53,160,53,0,107
1,GLOBAL SGD2023,gemma3-27b,1,53,40,21,0,19
2,GLOBAL SGD2023,gemma3-27b,2,53,32,12,0,20
3,GLOBAL SGD2023,gemma3-27b,3,53,30,16,0,14
4,GLOBAL SGD2023,gemma3-27b,4,53,33,16,0,17
5,GLOBAL SGD2023,gemma3-27b,5,53,10,6,0,4
6,GLOBAL SGD2023,gemma3-27b,6,53,19,7,0,12
7,GLOBAL SGD2023,gemma3-27b,7,53,16,7,0,9
8,GLOBAL SGD2023,gemma3-27b,8,53,23,14,0,9
9,GLOBAL SGD2023,gemma3-27b,9,53,34,10,0,24
10,GLOBAL SGD2023,gemma3-27b,10,53,23,15,0,8
11,GLOBAL SGD2023,gemma3-27b,11,53,23,11,0,12
12,GLOBAL SGD2023,gemma3-27b,12,53,37,18,0,19
13,GLOBAL SGD2023,gemma3-27b,13,53,58,31,0,27
14,GLOBAL SGD2023,gemma3-27b,14,53,15,7,0,8
15,GLOBAL SGD2023,gemma3-27b,15,53,27,19,1,7
16,GLOBAL SGD2023,gemma3-27b,16,53,47,27,0,20
17,GLOBAL SGD2023,gemma3-27b,17,53,81,40,0,41

Stats overall for gemma3-27b in document GLOBAL_SGD2023:

TypeError: save_overall_summary() missing 1 required positional argument: 'model_name'

### Llama 3.3 70B

In [ ]:
prefix = 'GLOBAL_SGD2025_'
model_name="llama3.3-70b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')
display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

[ODS 0 | page 7] Argument candidate:
  At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.

[ODS 0 | page 7] Argument candidate:
  Since the outbreak of the pandemic in 2020 and other simultaneous crises, SDG progress has stalled globally.

[ODS 0 | page 7] Argument candidate:
  The world is off track, but that is all the more reason to double down on the SDGs.

[ODS 0 | page 7] Argument candidate:
  At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.

[ODS 0 | page 7] Argument candidate:
  To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.

[ODS 0 | page 7] Argument candidate:
  The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 7] Argument candidate:
  All countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national SDG strategies and commit to strengthening multilateralism.

[ODS 0 | page 7] Argument candidate:
  National governments must ensure both domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation – by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 7] Argument candidate:
  Achieving the SDGs requires global cooperation guided by the United Nations Charter.

[ODS 0 | page 7] Argument candidate:
  We introduce in the report this year a pilot index of countries commitment to and support of multilateralism under the UN Charter. SDG transformations.

[ODS 0 | page 8] Argument candidate:
  Further investment is needed in statistical capacity and data literacy to support long-term pathways for key SDG transformations.

[ODS 0 | page 8] Argument candidate:
  At the halfway mark to 2030, there remains a great deal of work to be done to improve the data and methods underlying the SDG indicator framework.

[ODS 0 | page 8] Argument candidate:
  According to major international studies, few teenagers can differentiate between a fact and an opinion. As underlined during the United Nations World Data Forum 2023 and in the 27 April Hangzhou Declaration, investing in statistical capacity, science, and data literacy are important priorities for achieving the SDGs.

[ODS 0 | page 8] Argument candidate:
  The SDSN and its global network will double-down on efforts to implement the SDGs by 2030 and beyond.

[ODS 0 | page 8] Argument candidate:
  Via science-based pathways and analytics, the SDSN supports discussions on SDG implementation at the global, regional, and national levels.

[ODS 0 | page 8] Argument candidate:
  All UN Member States and UN agencies can count on the continued efforts and energies of the SDSN around the world to support all governments, businesses, and civil society in embracing and aligning with the SDGs on sustainable development.

[ODS 0 | page 13] Argument candidate:
  The grim reality is that at the midpoint of the 2030 Agenda, the SDGs are far off track.

[ODS 0 | page 13] Argument candidate:
  United Nations Secretary-General António Guterres has urged world leaders to come together at the 2023 SDG Summit in September to deliver a “Rescue Plan for People and Planet”

[ODS 0 | page 13] Argument candidate:
  As the world’s nations prepare to meet in September to review the progress the world has made so far towards achieving the SDGs, at the midpoint of the 2030 Agenda, SDSN emphasizes six areas for immediate action.

[ODS 0 | page 13] Argument candidate:
  Most urgently, UN Member States should adopt an SDG Stimulus, to close the massive financing gap faced by many developing economies.

[ODS 0 | page 13] Argument candidate:
  UN Member States must endorse a deep and overdue reform of the global financial architecture.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of ‘leave no one behind’.

[ODS 0 | page 14] Argument candidate:
  SDSN recommends that national pathways should include six key transformations:

[ODS 0 | page 14] Argument candidate:
  All UN Member States should present, at regular intervals, their national SDG frameworks in the form of Voluntary National Reviews (VNRs).

[ODS 0 | page 14] Argument candidate:
  To date, 188 of the 193 UN Member States have already presented VNRs.

[ODS 0 | page 14] Argument candidate:
  The report that follows offers SDSN’s update on the state of the SDGs at their mid-point, highlighting the growing dangers of adverse environmental, social, and economic “tipping points” and identifying key ways that the global community can and should accelerate SDG progress.

[ODS 0 | page 14] Argument candidate:
  UN Member States should commit to accelerating SDG progress to 2030, and to setting even more ambitious SDG targets to 2050, incorporating the recent Kunming-Montreal Biodiversity Framework and the High Seas Treaty.

[ODS 0 | page 15] Argument candidate:
  The SDGs are facing strong headwinds. Despite significant efforts in some places, national governments on all continents have fallen short in integrating the SDGs into national policies and public investments.

[ODS 0 | page 15] Argument candidate:
  We emphasize that achieving the SDGs rests on five pillars of good governance:

[ODS 0 | page 15] Argument candidate:
  The SDGs are not only a public policy framework; they are an ethical imperative.

[ODS 0 | page 15] Argument candidate:
  Dire shortfalls in meeting the SDGs The SDGs are seriously off track (Figure 1.1).

[ODS 0 | page 15] Argument candidate:
  According to the annual SDG Index, global achievement of the SDGs rose only slightly, from 64 percent in 2015 to 66 percent in 2019 – far too slowly to meet the goals by 2030, and with highly uneven progress within and between countries.

[ODS 0 | page 15] Argument candidate:
  The world is also seriously off track to meet the Paris agreement climate targets and SDG 13 (Figure 1.3).

[ODS 0 | page 16] Argument candidate:
  Dire shortfalls in meeting the SDGs

[ODS 0 | page 16] Argument candidate:
  SDG Index world average: pre-pandemic trend and trend needed to achieve the SDGs by 2030

[ODS 0 | page 16] Argument candidate:
  Trend needed to achieve the SDGs

[ODS 0 | page 17] Argument candidate:
  6 of nearly 90% of global fish stocks.6 The crises facing our oceans are unabated, multidimensional, and complex.

[ODS 0 | page 17] Argument candidate:
  The 2021 UN Food Systems Summit raised many urgent concerns around improving the sustainability, affordability, and quality of food across the world (SDG 2).

[ODS 0 | page 17] Argument candidate:
  Providing quality education (SDG 4) for all children is perhaps the single most important key to achieving sustainable development in the long term.

[ODS 0 | page 17] Argument candidate:
  Figure 1.2 Observed and projected gaps in SDG Index score between HICs and LICs (in percentage points)

[ODS 0 | page 17] Argument candidate:
  Part 1. How to Achieve the SDGs: The SDSN Framework planetary boundaries that regulate the Earth system.

[ODS 0 | page 19] Argument candidate:
  Unless the SDGs are actively pursued, geophysical tipping points combined with technological disruptions could ignite disastrous social conflicts within and between nations.

[ODS 0 | page 19] Argument candidate:
  We firmly believe that international cooperation together with the achievement of the SDGs is the best preventative to this dire and growing risk, and represent an opportunity to create positive social tipping points: for example, through equal access to high-quality education (SDG 4), and by fighting all forms of inequalities, including income and wealth inequalities (SDG 10).

[ODS 0 | page 19] Argument candidate:
  Although all governments are in principle committed to economic justice as enshrined in the Universal Declaration of Human Rights, and to the SDG tenets of ‘leave no one behind’ and ‘reach the furthest behind first’, too few are living up to these commitments, especially as powerful groups block adequate public support for weaker groups.

[ODS 0 | page 19] Argument candidate:
  In her 2022 report on the SDGs, E. Tendayi Achiume – UN Special Rapporteur on contemporary forms of racism, racial discrimination, xenophobia and related intolerance – noted that racism and racial discrimination are key barriers to sustainable development, and called attention to the failure of some States to collect disaggregated data on race, ethnicity, indigeneity, and migration status in the context of the 2030 Agenda.

[ODS 0 | page 19] Argument candidate:
  The report’s recommendations include calling for more racially-disaggregated SDG indicators and for dialogue with stakeholders on how to use these indicators to better allocate resources and prioritize the inclusion of marginalized peoples.

[ODS 0 | page 20] Argument candidate:
  Despite this ominous news, the SDGs are still achievable.

[ODS 0 | page 20] Argument candidate:
  Investing in the SDGs

[ODS 0 | page 20] Argument candidate:
  The world must devote an increased portion of current output to building up sustainable capital assets for the future, and must deploy such assets effectively.

[ODS 0 | page 20] Argument candidate:
  At their core, the SDGs are an investment agenda.

[ODS 0 | page 20] Argument candidate:
  Yes, the world is off-track, but that is all the more reason to double-down on the goals, rather than surrendering to human-made shortfalls in achieving them.

[ODS 0 | page 20] Argument candidate:
  The SDGs are woefully underfunded at home and internationally.

[ODS 0 | page 21] Argument candidate:
  To achieve the SDGs, the world must invest boldly, amply, and consistently in all eight kinds of capital.

[ODS 0 | page 21] Argument candidate:
  Parallel to investing in the SDGs, the world needs to stop investing in activities that threaten planetary boundaries, destroy human and natural capital, and harm social cohesion.

[ODS 0 | page 21] Argument candidate:
  In 2022, the United Nations Secretary-General appointed a High-Level Advisory Board on Effective Multilateralism, with a mandate to develop a list of concrete, actionable recommendations to improve international cooperation and advance the 2030 Agenda for Sustainable Development.

[ODS 0 | page 21] Argument candidate:
  National governments must ensure both the domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 21] Argument candidate:
  Virtually all governments of the world have embraced the SDGs in principle. 188 of 193 UN Member States have submitted VNRs for comment by the other nations.

[ODS 0 | page 21] Argument candidate:
  The Nordic countries and European Union have shown considerable support for the SDGs. So too have many developing countries in the G20.

[ODS 0 | page 22] Argument candidate:
  The greatest responsibility for achieving the SDGs and safeguarding the planetary boundaries lies with the G20 members.

[ODS 0 | page 22] Argument candidate:
  The United States, as the world’s biggest economy in terms of GDP at market prices and its biggest oil and gas producer, has a responsibility both to itself and to the rest of the world to immediately embark on an ambitious transformation towards the SDGs, as well as towards other global climate and biodiversity goals.

[ODS 0 | page 22] Argument candidate:
  We call on the United States to formulate an SDG action plan and to present a VNR to the High-Level Political Forum.

[ODS 0 | page 22] Argument candidate:
  The European Union – the world’s second-largest economy and its major lignite producer – has produced the European Green Deal (EGD), which is exemplary in many regards.

[ODS 0 | page 22] Argument candidate:
  However, the EGD and EU policies at large lack a comprehensive alignment to the SDGs, politically agreed targets for many SDG indicators, and clarity on how to achieve the SDGs.

[ODS 0 | page 22] Argument candidate:
  The EU has also highlighted the strategic role of the private sector in achieving the SDGs, by implementing a new directive asking companies to publish sustainability reports and, in particular in the food sector, by promoting the “Code of Conduct on Responsible Food Business and Marketing Practices”

[ODS 0 | page 22] Argument candidate:
  China intends to implement the SDGs by integrating them into its medium and long-term national development strategies, such as its five-year plans.

[ODS 0 | page 22] Argument candidate:
  China has already presented two VNRs to the HLPF (2016 and 2021).

[ODS 0 | page 22] Argument candidate:
  In July 2023, the EU is set to present its first Union-wide voluntary review at the United Nations.

[ODS 0 | page 22] Argument candidate:
  This presents a good opportunity for the EU to send a strong message to the international community, and to demonstrate its commitment to and leadership on the SDGs.

[ODS 0 | page 23] Argument candidate:
  A key measure for China will be the explicit integration of the SDGs’ domestic and international implementation into the 15th five-year plan (2026–2030).

[ODS 0 | page 23] Argument candidate:
  We urge all G20 governments to show the leadership required of them.

[ODS 0 | page 23] Argument candidate:
  At the midpoint of the 2030 Agenda, all countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national strategies, using the principles of the 2030 Agenda (transformative, integrated, inclusive, leaving no one behind) as a yardstick.

[ODS 0 | page 23] Argument candidate:
  Achieving the SDGs will require a transformative global approach.

[ODS 0 | page 23] Argument candidate:
  Both the 2030 Agenda and the Paris Climate Agreement established mechanisms to encourage and monitor their implementation by nation-states. However, experience so far with VNRs and Nationally Determined Contributions (NDCs), respectively, demonstrate that these mechanisms – despite some progress – have not delivered the effort necessary to achieve global goals.

[ODS 0 | page 23] Argument candidate:
  Even the progress on consistent national reporting on SDG indicators is inadequate.

[ODS 0 | page 24] Argument candidate:
  It is widely recognized that the world needs to overhaul the GFA. Such an overhaul should address the failures above and aim to achieve six objectives:

[ODS 0 | page 24] Argument candidate:
  International cooperation is trapped by bureaucratic institutional frameworks that reduce the speed, efficacy, and efficiency of funding to meet the SDGs, and that fail to provide the framework for large-scale SDG financing.

[ODS 0 | page 24] Argument candidate:
  Align private business investment flows in all countries with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 24] Argument candidate:
  Reform current institutional frameworks and develop new, innovative mechanisms to improve the quality and speed of deployment of international cooperation, and monitor progress in an open and timely manner.

[ODS 0 | page 25] Argument candidate:
  Overhauling global governance mechanisms and the global financial architecture is fundamental to unlocking needed investments for sustainable development and ending non-sustainable practices.

[ODS 0 | page 25] Argument candidate:
  The SDG policy agenda is complex. The SDGs call for lasting, long-term, directed change.

[ODS 0 | page 26] Argument candidate:
  SDSN’s strategy to achieve the SDGs

[ODS 0 | page 26] Argument candidate:
  Long-term investment plans are essential for national success in meeting the SDGs.

[ODS 0 | page 26] Argument candidate:
  SDSN has recommended six inter-related long-term transformations:

[ODS 0 | page 26] Argument candidate:
  Each of these challenges will require large-scale public and private investments to mid-century, technological transformation, and a sound financing strategy.

[ODS 0 | page 26] Argument candidate:
  The Sustainable Development Report 2023 identifies five levers to be deployed to bring about the necessary transformations: governance, economy and finance, individual and collective action, science and technology, and capacity building.

[ODS 0 | page 26] Argument candidate:
  Planning for the long term, however, illuminates the global financial architecture’s Achilles heel.

[ODS 0 | page 26] Argument candidate:
  SDSN has joined the Group on Earth Observations (GEO)19 as a Participating Organization, supporting the efforts of this voluntary intergovernmental community to focus national, international, and private sector investments in Earth observations on urgent SDG needs.

[ODS 0 | page 27] Argument candidate:
  To make sure that existing financial resources and the required additional resources are used for sustainable investments, international finance institutions must fully incorporate achieving the SDGs and safeguarding the planetary boundaries into their core mandates, and monitor these regarding all countries, poorer and richer alike.

[ODS 0 | page 27] Argument candidate:
  Global infrastructure programs like China’s Belt and Road, the EU’s Global Gateway, or the United States’ Build Back Better World initiatives must be much better aligned with the SDGs and coordinated with each other.

[ODS 0 | page 27] Argument candidate:
  In his opening address to the UN General Assembly on September 20, 2022, UN Secretary-General António Guterres called on the G20 to launch an “SDG Stimulus” to offset the deteriorating market conditions faced by developing countries and to accelerate progress towards the SDGs and the Paris Climate Agreement.

[ODS 0 | page 27] Argument candidate:
  SDSN provided the Secretariat of a High-Level Informal Working Group for the SDG Stimulus (HLIWG), that made the case for an SDG Stimulus of an additional US$500 billion per year by 2025 of SDG finance.

[ODS 0 | page 27] Argument candidate:
  The SDG Stimulus plan recommended by the High-Level Working Group and introduced by SG Guterres last February has five main components:

[ODS 0 | page 27] Argument candidate:
  According to IMF estimates in 2019, the financing gap facing 57 low-income developing countries (LICs and LMICs that are eligible for IMF concessional financing) to cover very basic investments in health, education, power, roads, and water and sanitation was in the order of US$300 billion to US$500 billion per year.

[ODS 0 | page 27] Argument candidate:
  Adding in these extra needs, the global SDG financing gap is perhaps US$1 trillion per year, or roughly 1% of gross world product (GWP) at market prices.

[ODS 0 | page 27] Argument candidate:
  As a rough rule of thumb based on work by SDSN and the IMF, the LICs need roughly 20% of their GDP in increased SDG investment outlays while the LMICs need roughly 10%, though precise amounts vary by country.

[ODS 0 | page 28] Argument candidate:
  The urgent objective of the SDG Stimulus is to address – in practical terms and at scale – the chronic shortfall of international SDG financing facing the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 28] Argument candidate:

NameError: name 'path_output_txt' is not defined

### Deepseek r1 70B

In [ ]:
prefix = 'GLOBAL_SGD2025'
model_name="deepseek-r1-70b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')
display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
dfGlobal2023 = save_overall_summary(res, path_output_stats, model_name).rename(columns={"pages_max": "pages"}).drop(columns=["ods_max"])
dfGlobal2023

[ODS 0 | page 7] Argument candidate:
  At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.

[ODS 0 | page 7] Argument candidate:
  Despite this alarming development, the SDGs are still achievable. None of their objectives are beyond our reach.

[ODS 0 | page 7] Argument candidate:
  The world is off track, but that is all the more reason to double down on the SDGs.

[ODS 0 | page 7] Argument candidate:
  At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.

[ODS 0 | page 7] Argument candidate:
  To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.

[ODS 0 | page 7] Argument candidate:
  The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 7] Argument candidate:
  All countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national SDG strategies and commit to strengthening multilateralism.

[ODS 0 | page 7] Argument candidate:
  National governments must ensure both domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation – by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 7] Argument candidate:
  Achieving the SDGs requires global cooperation guided by the United Nations Charter.

[ODS 0 | page 7] Argument candidate:
  SDG transformations.

[ODS 0 | page 8] Argument candidate:
  Further investment is needed in statistical capacity and data literacy to support long-term pathways for key SDG transformations.

[ODS 0 | page 8] Argument candidate:
  At the halfway mark to 2030, there remains a great deal of work to be done to improve the data and methods underlying the SDG indicator framework.

[ODS 0 | page 8] Argument candidate:
  Evidence suggests that since 2016 there has been only limited progress and convergence in countries’ statistical capacity, including LICs and LMICs, and that international funding for data and statistics fell between 2019 and 2021.

[ODS 0 | page 8] Argument candidate:
  Also, in an information-rich and post-truth environment, citizens and decision-makers need knowledge and tools to transform data and science into evidence, actions, and long-term policies.

[ODS 0 | page 8] Argument candidate:
  According to major international studies, few teenagers can differentiate between a fact and an opinion.

[ODS 0 | page 8] Argument candidate:
  As underlined during the United Nations World Data Forum 2023 and in the 27 April Hangzhou Declaration, investing in statistical capacity, science, and data literacy are important priorities for achieving the SDGs.

[ODS 0 | page 8] Argument candidate:
  The SDSN and its global network will double-down on efforts to implement the SDGs by 2030 and beyond.

[ODS 0 | page 8] Argument candidate:
  Via science-based pathways and analytics, the SDSN supports discussions on SDG implementation at the global, regional, and national levels.

[ODS 0 | page 8] Argument candidate:
  All UN Member States and UN agencies can count on the continued efforts and energies of the SDSN around the world to support all governments, businesses, and civil society in embracing and aligning with the SDGs on sustainable development.

[ODS 0 | page 13] Argument candidate:
  The grim reality is that at the midpoint of the 2030 Agenda, the SDGs are far off track.

[ODS 0 | page 13] Argument candidate:
  As the world’s nations prepare to meet in September to review the progress the world has made so far towards achieving the SDGs, at the midpoint of the 2030 Agenda, SDSN emphasizes six areas for immediate action.

[ODS 0 | page 13] Argument candidate:
  Most urgently, UN Member States should adopt an SDG Stimulus, to close the massive financing gap faced by many developing economies.

[ODS 0 | page 13] Argument candidate:
  UN Member States must endorse a deep and overdue reform of the global financial architecture.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of ‘leave no one behind’.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should present, at regular intervals, their national SDG frameworks in the form of Voluntary National Reviews (VNRs). To date, 188 of the 193 UN Member States have already presented VNRs. Five countries (Haiti, Myanmar, South Sudan, the United States, and Yemen) have yet to do so, and should prepare to do so with urgency.

[ODS 0 | page 14] Argument candidate:
  UN Member States should commit to accelerating SDG progress to 2030, and to setting even more ambitious SDG targets to 2050, incorporating the recent Kunming-Montreal Biodiversity Framework and the High Seas Treaty.

[ODS 0 | page 15] Argument candidate:
  The SDGs are facing strong headwinds. Despite significant efforts in some places, national governments on all continents have fallen short in integrating the SDGs into national policies and public investments.

[ODS 0 | page 15] Argument candidate:
  Moreover, societal polarization, populism, and growing geopolitical conflict are hindering the global cooperation needed to achieve the SDGs.

[ODS 0 | page 15] Argument candidate:
  The international financial architecture is failing to channel global savings to SDG investments at the needed pace and scale.

[ODS 0 | page 15] Argument candidate:
  We emphasize that achieving the SDGs rests on five pillars of good governance: 1. Preparing long-term SDG pathways to guide public policy; 2. Ensuring SDG financing at the necessary scale and timing; 3. Promoting global cooperation and reducing geopolitical conflict and tension; 4. Supporting innovation to broaden social inclusion and environmental sustainability; 5. Regular reporting on SDG progress and performance.

[ODS 0 | page 15] Argument candidate:
  The SDGs are not only a public policy framework; they are an ethical imperative.

[ODS 0 | page 15] Argument candidate:
  They are grounded in the Universal Declaration of Human Rights, which celebrates its 75th anniversary this year.

[ODS 0 | page 15] Argument candidate:
  As the Universal Declaration makes clear, and the SDGs make explicit, social justice and sustainable development require the full realization of the rights of all people.

[ODS 0 | page 15] Argument candidate:
  The UN Sustainable Development Solutions Network (SDSN) is dedicated to finding and amplifying practical solutions to achieve the SDGs and closely-related global goals (such as the Paris climate agreement and the Kunming-Montreal Biodiversity Framework).

[ODS 0 | page 15] Argument candidate:
  We emphasize that all these global goals are interrelated and must be achieved together.

[ODS 0 | page 15] Argument candidate:
  Dire shortfalls in meeting the SDGs The SDGs are seriously off track (Figure 1.1).

[ODS 0 | page 15] Argument candidate:
  SDG progress was already very slow in the five years to 2020.

[ODS 0 | page 15] Argument candidate:
  According to the annual SDG Index, global achievement of the SDGs rose only slightly, from 64 percent in 2015 to 66 percent in 2019 – far too slowly to meet the goals by 2030, and with highly uneven progress within and between countries.

[ODS 0 | page 15] Argument candidate:
  Then with the onset of the pandemic, progress stopped.

[ODS 0 | page 15] Argument candidate:
  As of 2022, the global SDG Index is below 67%. At current trends, based on simple projections, there is a risk that the gap in SDG outcomes between HICs and LICs will be wider in 2030 (29 points) than it was in 2015 (28 points).

[ODS 0 | page 15] Argument candidate:
  This means that we are at risk of losing a decade of progress towards convergence globally (Figure 1.2).

[ODS 0 | page 15] Argument candidate:
  The multiple geopolitical crises in the world today will no doubt place further obstacles on the path to 2030.

[ODS 0 | page 15] Argument candidate:
  If we look at each of the 17 individual SDGs, not a single SDG is projected to be met at the global level.

[ODS 0 | page 16] Argument candidate:
  Dire shortfalls in meeting the SDGs

[ODS 0 | page 16] Argument candidate:
  Current Nationally Determined Contribution (NDC) targets, if implemented, would still lead to around 2.4°C warming by 2100.

[ODS 0 | page 16] Argument candidate:
  Even taking the net-zero pledges of many countries into account, best-case scenarios given current pledges would lead to around 1.8°C warming by 2100.

[ODS 0 | page 16] Argument candidate:
  Water scarcity affects more than 40% of the world’s population.

[ODS 0 | page 16] Argument candidate:
  An estimated 1.8 billion people depend on drinking water contaminated by human waste.

[ODS 0 | page 16] Argument candidate:
  Unsustainable water management practices, including chemical discharges into water supply systems for irrigation, affect the functioning of ecosystems services.

[ODS 0 | page 16] Argument candidate:
  Global resource consumption assessments for rare earth elements are critical.

[ODS 0 | page 16] Argument candidate:
  Although reserves of these elements do not exist in concentrated clusters – which make them inefficient for mining – certain countries are quite dominant in this field, producing 98% of the world’s supply.

[ODS 0 | page 16] Argument candidate:
  As demand for rare earth elements is increasing tremendously, their scarcity is becoming more evident.

[ODS 0 | page 17] Argument candidate:
  The 2021 UN Food Systems Summit raised many urgent concerns around improving the sustainability, affordability, and quality of food across the world (SDG 2).

[ODS 0 | page 17] Argument candidate:
  Providing quality education (SDG 4) for all children is perhaps the single most important key to achieving sustainable development in the long term.

[ODS 0 | page 17] Argument candidate:
  The UN General Assembly’s Transforming Education Summit held in September 2022 was a critical meeting to spur national and global efforts to transform education to give all people the skills and knowledge to end poverty, protect the environment, and build peaceful and inclusive societies.

[ODS 0 | page 17] Argument candidate:
  Note: Projected gap by 2030 is based on extrapolation of annual growth rate on the SDG Index over the period 2019-2021. Pre-pandemic projected gap is based on an extrapolation of SDG Index annual growth rates over the period 2015-2019.

[ODS 0 | page 17] Argument candidate:
  Part 1. How to Achieve the SDGs: The SDSN Framework "planetary boundaries" that regulate the Earth system.

[ODS 0 | page 19] Argument candidate:
  Unless the SDGs are actively pursued, geophysical tipping points combined with technological disruptions could ignite disastrous social conflicts within and between nations.

[ODS 0 | page 19] Argument candidate:
  We firmly believe that international cooperation together with the achievement of the SDGs is the best preventative to this dire and growing risk, and represent an opportunity to create positive social tipping points: for example, through equal access to high-quality education (SDG 4), and by fighting all forms of inequalities, including income and wealth inequalities (SDG 10).

[ODS 0 | page 19] Argument candidate:
  Although all governments are in principle committed to economic justice as enshrined in the Universal Declaration of Human Rights, and to the SDG tenets of ‘leave no one behind’ and ‘reach the furthest behind first’, too few are living up to these commitments, especially as powerful groups block adequate public support for weaker groups.

[ODS 0 | page 19] Argument candidate:
  She noted however that, while disrupting the dynamic of racially discriminatory underdevelopment may require a greater transformation than is possible at this moment, the SDGs held untapped potential to advance both development and non-discrimination.

[ODS 0 | page 20] Argument candidate:
  Despite this ominous news, the SDGs are still achievable.

[ODS 0 | page 20] Argument candidate:
  None of their objectives are beyond our reach.12 Yes, the world is off-track, but that is all the more reason to double-down on the goals, rather than surrendering to human-made shortfalls in achieving them.

[ODS 0 | page 20] Argument candidate:
  At their core, the SDGs are an investment agenda.

[ODS 0 | page 21] Argument candidate:
  To achieve the SDGs, the world must invest boldly, amply, and consistently in all eight kinds of capital.

[ODS 0 | page 21] Argument candidate:
  These investments must involve both governments and corporations.

[ODS 0 | page 21] Argument candidate:
  For example, while business capital is mainly the purview of the private sector, human capital is mainly the purview of the public sector.

[ODS 0 | page 21] Argument candidate:
  Governments too must take the lead in protecting natural capital, while civil society especially must promote social and cultural capital, including mutual understanding across cultures and nations.

[ODS 0 | page 21] Argument candidate:
  Infrastructure capital and innovation capital tend to be financed roughly equally by the public and private sectors.

[ODS 0 | page 21] Argument candidate:
  For example, governments tend to finance power transmission grids, while the private sector tends to finance power generation.

[ODS 0 | page 21] Argument candidate:
  Governments generally finance basic scientific research, while businesses focus on applied R&D.

[ODS 0 | page 21] Argument candidate:
  Parallel to investing in the SDGs, the world needs to stop investing in activities that threaten planetary boundaries, destroy human and natural capital, and harm social cohesion.

[ODS 0 | page 21] Argument candidate:
  Curtailing the extraction and use of fossil fuels is of paramount importance.

[ODS 0 | page 21] Argument candidate:
  To curb harmful investments, regulatory measures, including fair and sustainable taxation and the dismantling of unsustainable subsidies, need to be an integral element of the SDG investment agenda.

[ODS 0 | page 21] Argument candidate:
  In 2022, the United Nations Secretary-General appointed a High-Level Advisory Board on Effective Multilateralism, with a mandate to develop a list of concrete, actionable recommendations to improve international cooperation and advance the 2030 Agenda for Sustainable Development.

[ODS 0 | page 21] Argument candidate:
  The Board’s 2023 report lists six areas for action that are directly aligned with the SDGs and SDSN’s recommendations: rebuilding trust in multilateralism, safeguarding our planet and its people, scaling up and improving the efficacy of global finance, improving data systems and their governance, and promoting peace.

[ODS 0 | page 21] Argument candidate:
  The most important level of decision-making remains the nation-state.

[ODS 0 | page 21] Argument candidate:
  Nation-states hold the primary responsibility for achieving the SDGs.

[ODS 0 | page 21] Argument candidate:
  They are members of the United Nations and the signatories of United Nations treaties.

[ODS 0 | page 21] Argument candidate:
  They hold juridical responsibility for implementing treaty agreements and the rest of the United Nations architecture, including the United Nations Charter, the Universal Declaration of Human Rights, and the SDGs.

[ODS 0 | page 21] Argument candidate:
  National governments must ensure both the domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 21] Argument candidate:
  Crucially, national government must also work with subnational governments to implement the SDG agenda at the local level, including sustainable urban infrastructure, delivery of social services, and ensuring safe communities.

[ODS 0 | page 21] Argument candidate:
  Virtually all governments of the world have embraced the SDGs in principle.

[ODS 0 | page 21] Argument candidate:
  188 of 193 UN Member States have submitted VNRs for comment by the other nations.

[ODS 0 | page 21] Argument candidate:
  Only five countries, notably the United States, Haiti, Myanmar, South Sudan, and Yemen, have never presented VNRs.

[ODS 0 | page 21] Argument candidate:
  Four of these countries are wracked by violence and poverty.

[ODS 0 | page 21] Argument candidate:
  The case of the United States stands as a glaring exception.

[ODS 0 | page 21] Argument candidate:
  The Nordic countries and European Union have shown considerable support for the SDGs.

[ODS 0 | page 21] Argument candidate:
  So too have many developing countries in the G20.

[ODS 0 | page 22] Argument candidate:
  Failures (and some successes) of national SDG governance

[ODS 0 | page 22] Argument candidate:
  The greatest responsibility for achieving the SDGs and safeguarding the planetary boundaries lies with the G20 members.

[ODS 0 | page 22] Argument candidate:
  The United States has so far shown very little commitment to the SDGs. We call on the United States to formulate an SDG action plan and to present a VNR to the High-Level Political Forum.

[ODS 0 | page 22] Argument candidate:
  The European Union – the world’s second-largest economy and its major lignite producer – has produced the European Green Deal (EGD), which is exemplary in many regards.

[ODS 0 | page 22] Argument candidate:
  In July 2023, the EU is set to present its first Union-wide voluntary review at the United Nations. This presents a good opportunity for the EU to send a strong message to the international community, and to demonstrate its commitment to and leadership on the SDGs.

[ODS 0 | page 23] Argument candidate:
  12th Five-Year Plan referred to the 2030 Agenda mainly in the context of international cooperation.

[ODS 0 | page 23] Argument candidate:
  China has reiterated its support for the SDGs, such as in greening its Belt and Road Initiative and launching the Global Development Initiative as a worldwide effort.

[ODS 0 | page 23] Argument candidate:
  A key measure for China will be the explicit integration of the SDGs’ domestic and international implementation into the 15th five-year plan (2026–2030).

[ODS 0 | page 23] Argument candidate:
  Some other G20 countries have shown weak commitments to the SDGs in recent years.

[ODS 0 | page 23] Argument candidate:
  Many of the poor performers, such as Brazil, recently elected new governments that have staked out a far more ambitious position vis-à-vis the SDGs.

[ODS 0 | page 23] Argument candidate:
  We urge all G20 governments to show the leadership required of them.

[ODS 0 | page 23] Argument candidate:
  Most of the low-income and lower-middle income countries, home to more than half of humanity, face major challenges in achieving most of the SDGs by 2030.

[ODS 0 | page 23] Argument candidate:
  Many of them lack an adequately high SDG commitment, and almost all lack access to the necessary financial means to implement the SDGs.

[ODS 0 | page 23] Argument candidate:
  At the midpoint of the 2030 Agenda, all countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national strategies, using the principles of the 2030 Agenda (transformative, integrated, inclusive, leaving no one behind) as a yardstick.

[ODS 0 | page 23] Argument candidate:

,prefix,model,ods,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,deepseek-r1-70b,0,53,374,142,0,232
1,GLOBAL SGD2023,deepseek-r1-70b,1,53,57,30,0,27
2,GLOBAL SGD2023,deepseek-r1-70b,2,53,20,13,0,7
3,GLOBAL SGD2023,deepseek-r1-70b,3,53,36,24,0,12
4,GLOBAL SGD2023,deepseek-r1-70b,4,53,41,27,1,13
5,GLOBAL SGD2023,deepseek-r1-70b,5,53,7,5,0,2
6,GLOBAL SGD2023,deepseek-r1-70b,6,53,8,7,0,1
7,GLOBAL SGD2023,deepseek-r1-70b,7,53,23,12,1,10
8,GLOBAL SGD2023,deepseek-r1-70b,8,53,74,31,1,42
9,GLOBAL SGD2023,deepseek-r1-70b,9,53,67,23,0,44
10,GLOBAL SGD2023,deepseek-r1-70b,10,53,40,21,0,19
11,GLOBAL SGD2023,deepseek-r1-70b,11,53,35,17,0,18
12,GLOBAL SGD2023,deepseek-r1-70b,12,53,27,18,0,9
13,GLOBAL SGD2023,deepseek-r1-70b,13,53,87,47,0,40
14,GLOBAL SGD2023,deepseek-r1-70b,14,53,14,10,0,4
15,GLOBAL SGD2023,deepseek-r1-70b,15,53,32,20,0,12
16,GLOBAL SGD2023,deepseek-r1-70b,16,53,68,29,0,39
17,GLOBAL SGD2023,deepseek-r1-70b,17,53,168,77,0,91

Stats overall for deepseek-r1-70b in document GLOBAL_SGD2023:

Updated overall summary:

,prefix,model,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,53,251,161,0,90
1,GLOBAL SGD2023,gemma3-4b,53,4093,706,2,3385
2,GLOBAL SGD2023,gemma3-27b,53,708,330,1,377
3,GLOBAL SGD2023,llama3.3-70b,53,817,477,4,336
4,GLOBAL SGD2023,deepseek-r1-70b,53,1178,553,3,622

## OCDE 2024 report

### Qwen2.5-3b

In [ ]:
prefix = 'OCDE_2024'
model_name="qwen2.5-3b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')

display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

Stats by SDG for qwen2.5-3b in document GLOBAL_SGD2023_:

,prefix,model,ods,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,0,53,42,32,0,10
1,GLOBAL SGD2023,qwen2.5-3b,1,53,21,9,0,12
2,GLOBAL SGD2023,qwen2.5-3b,2,53,14,2,0,12
3,GLOBAL SGD2023,qwen2.5-3b,3,53,17,12,0,5
4,GLOBAL SGD2023,qwen2.5-3b,4,53,16,5,0,11
5,GLOBAL SGD2023,qwen2.5-3b,5,53,10,2,0,8
6,GLOBAL SGD2023,qwen2.5-3b,6,53,11,7,0,4
7,GLOBAL SGD2023,qwen2.5-3b,7,53,15,10,0,5
8,GLOBAL SGD2023,qwen2.5-3b,8,53,12,9,0,3
9,GLOBAL SGD2023,qwen2.5-3b,9,53,7,4,0,3
10,GLOBAL SGD2023,qwen2.5-3b,10,53,19,13,0,6
11,GLOBAL SGD2023,qwen2.5-3b,11,53,10,8,0,2
12,GLOBAL SGD2023,qwen2.5-3b,12,53,11,10,0,1
13,GLOBAL SGD2023,qwen2.5-3b,13,53,10,9,0,1
14,GLOBAL SGD2023,qwen2.5-3b,14,53,4,3,0,1
15,GLOBAL SGD2023,qwen2.5-3b,15,53,1,1,0,0
16,GLOBAL SGD2023,qwen2.5-3b,16,53,14,10,0,4
17,GLOBAL SGD2023,qwen2.5-3b,17,53,17,15,0,2

Stats overall for qwen2.5-3b in document GLOBAL_SGD2023_:

Updated overall summary:

,prefix,model,ods_max,pages_max,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,17,53,251,161,0,90

### Gemma3 4B

In [ ]:
prefix = 'OCDE_2024'
model_name="gemma3-4b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')

display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

[ODS 0 | page 7] Argument candidate:
  At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.

[ODS 0 | page 7] Argument candidate:
  None of their objectives are beyond our reach.

[ODS 0 | page 7] Argument candidate:
  The SDGs are still achievable.

[ODS 0 | page 7] Argument candidate:
  It is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.

[ODS 0 | page 7] Argument candidate:
  To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.

[ODS 0 | page 7] Argument candidate:
  The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 7] Argument candidate:
  Greatly increase funding to national and subnational governments and private businesses, especially in LICs and LMICs, to carry out needed SDG investments.

[ODS 0 | page 7] Argument candidate:
  Revise the credit rating system and debt sustainability metrics to facilitate long-term sustainable development.

[ODS 0 | page 7] Argument candidate:
  Revise liquidity structures for LICs and LMICs, especially regarding sovereign debts, to forestall self-fulfilling banking and balance-of-payments crises

[ODS 0 | page 7] Argument candidate:
  Create ambitious, internationally-agreed upon criteria for sustainable finance that are mandatory for all public financial institutions.

[ODS 0 | page 7] Argument candidate:
  Align private business investment flows with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 7] Argument candidate:
  Reform current institutional frameworks and develop new mechanisms to improve the quality and speed of deployment of international cooperation, and monitor progress in an open and timely manner.

[ODS 0 | page 7] Argument candidate:
  All countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national SDG strategies and commit to strengthening multilateralism.

[ODS 0 | page 7] Argument candidate:
  National governments must ensure both domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation – by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 7] Argument candidate:
  Achieving the SDGs requires global cooperation guided by the United Nations Charter.

[ODS 0 | page 8] Argument candidate:
  Further investment is needed in statistical capacity and data literacy to support long-term pathways for key SDG transformations.

[ODS 0 | page 8] Argument candidate:
  At the halfway mark to 2030, there remains a great deal of work to be done to improve the data and methods underlying the SDG indicator framework.

[ODS 0 | page 8] Argument candidate:
  investing in statistical capacity, science, and data literacy are important priorities for achieving the SDGs.

[ODS 0 | page 8] Argument candidate:
  All UN Member States and UN agencies can count on the continued efforts and energies of the SDSN around the world to support all governments, businesses, and civil society in embracing and aligning with the SDGs

[ODS 0 | page 13] Argument candidate:
  UN Member States should adopt an SDG Stimulus, to close the massive financing gap faced by many developing economies.

[ODS 0 | page 13] Argument candidate:
  Increased funding from the multilateral development banks (MDBs) and public development banks (PDBs) to low- and middle-income countries, linked to investments in the SDGs;

[ODS 0 | page 13] Argument candidate:
  Enhancement of relief for countries facing debt distress;

[ODS 0 | page 13] Argument candidate:
  Expansion of liquidity by the International Monetary Fund (IMF) and major central banks;

[ODS 0 | page 13] Argument candidate:
  Empowerment and expansion of the specialized global funds;

[ODS 0 | page 13] Argument candidate:
  Expansion of private philanthropy with a focus on ultra-high-net-worth individuals.

[ODS 0 | page 13] Argument candidate:
  UN Member States must endorse a deep and overdue reform of the global financial architecture.

[ODS 0 | page 13] Argument candidate:
  Greatly increased funding for national and subnational governments and private businesses in the emerging economies, especially the low-income countries (LICs) and lower-middle-income countries (LMICs), to carry out needed SDG actions;

[ODS 0 | page 13] Argument candidate:
  Revision of the credit-rating system and debt-sustainability metrics to facilitate long-term sustainable development;

[ODS 0 | page 13] Argument candidate:
  Revision of the liquidity structures for LICs and LMICs, especially regarding sovereign debt, to forestall self-fulfilling banking and balance-of-payments crises;

[ODS 0 | page 13] Argument candidate:
  Creation of ambitious, internationally-agreed criteria for sustainable finance that are mandatory for all public financial institutions in high-income countries (HICs), middle-income countries (MICs), and LICs alike.

[ODS 0 | page 13] Argument candidate:
  Alignment of private business investment flows in all countries with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 13] Argument candidate:
  A reform of current institutional frameworks and development of new and innovative mechanisms to improve the quality and speed of deployment of international cooperation, and the monitoring of progress in an open and timely manner.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of ‘leave no one behind’.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should present, at regular intervals, their national SDG frameworks in the form of Voluntary National Reviews (VNRs).

[ODS 0 | page 14] Argument candidate:
  All UN Member States should recommit to peaceful cooperation, in the service of the SDGs and all other multilateral agreements.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should commit to accelerating SDG progress to 2030, and to setting even more ambitious SDG targets to 2050, incorporating the recent Kunming-Montreal Biodiversity Framework and the High Seas Treaty.

[ODS 0 | page 15] Argument candidate:
  national governments on all continents have fallen short in integrating the SDGs into national policies and public investments

[ODS 0 | page 15] Argument candidate:
  they are grounded in the Universal Declaration of Human Rights, which celebrates its 75th anniversary this year

[ODS 0 | page 15] Argument candidate:
  that "All human beings are born free and equal in dignity and rights … and should act towards one another in a spirit of brotherhood"

[ODS 0 | page 15] Argument candidate:
  that "it is essential to promote the development of friendly relations between nations"

[ODS 0 | page 15] Argument candidate:
  social justice and sustainable development require the full realization of the rights of all people

[ODS 0 | page 15] Argument candidate:
  includes equality of opportunities for girls and women (SDG 5)

[ODS 0 | page 15] Argument candidate:
  respect for the rights and voice of Indigenous peoples around the world

[ODS 0 | page 15] Argument candidate:
  a much larger role for young people, who will face the consequences of our (in)actions throughout the 21st century

[ODS 0 | page 15] Argument candidate:
  They are not only a public policy framework; they are an ethical imperative

[ODS 0 | page 15] Argument candidate:
  Members of the SDSN Leadership Council offer the following assessments and recommendations to the UN Member States, the United Nations Agencies, international finance institutions, business, and civil society, based on more than a decade of research, measurement, advising, and partnerships across the world

[ODS 0 | page 16] Argument candidate:
  Dire shortfalls in meeting the SDGs to reaching a disastrous 2.8°C warming by 2100.

[ODS 0 | page 16] Argument candidate:
  Current Nationally Determined Contribution (NDC) targets, if implemented, would still lead to around 2.4°C warming by 2100.

[ODS 0 | page 16] Argument candidate:
  Biodiversity targets (SDG 15 and targets agreed under the CBD) are also at grave risk.

[ODS 0 | page 16] Argument candidate:
  Global resource consumption assessments for rare earth elements are critical.

[ODS 0 | page 16] Argument candidate:
  Ocean goods and services (SDG 14 and the High Seas Treaty) are at severe risk due to full- to over-exploitation

[ODS 0 | page 17] Argument candidate:
  Providing quality education (SDG 4) for all children is perhaps the single most important key to achieving sustainable development in the long term.

[ODS 0 | page 17] Argument candidate:
  The UN General Assembly’s Transforming Education Summit held in September 2022 was a critical meeting to spur national and global efforts to transform education to give all people the skills and knowledge to end poverty, protect the environment, and build peaceful and inclusive societies.

[ODS 0 | page 17] Argument candidate:
  And yet, the truth remains that hundreds of millions of children are either out of school entirely or receiving such an under-funded and under-resourced education that they are failing to achieve basic literacy and numeracy even after several years of education.

[ODS 0 | page 18] Argument candidate:
  The latest scientific assessments indicate that six of the nine planetary boundaries have been breached.

[ODS 0 | page 18] Argument candidate:
  Scientists have identified a large number of extremely dangerous potential tipping points, with linkages and dependencies across the different planetary boundaries.

[ODS 0 | page 18] Argument candidate:
  Human-induced global warming could hit several tipping points that may in turn lead to further feedbacks (amplifications) of the warming.

[ODS 0 | page 19] Argument candidate:
  Unless the SDGs are actively pursued, geophysical tipping points combined with technological disruptions could ignite disastrous social conflicts within and between nations.

[ODS 0 | page 19] Argument candidate:
  We firmly believe that international cooperation together with the achievement of the SDGs is the best preventative to this dire and growing risk, and represent an opportunity to create positive social tipping points: for example, through equal access to high-quality education (SDG 4), and by fighting all forms of inequalities, including income and wealth inequalities (SDG 10).

[ODS 0 | page 19] Argument candidate:
  Although all governments are in principle committed to economic justice as enshrined in the Universal Declaration of Human Rights, and to the SDG tenets of ‘leave no one behind’ and ‘reach the furthest behind first’, too few are living up to these commitments, especially as powerful groups block adequate public support for weaker groups.

[ODS 0 | page 19] Argument candidate:
  The report’s recommendations include calling for more racially-disaggregated SDG indicators and for dialogue with stakeholders on how to use these indicators to better allocate resources and prioritize the inclusion of marginalized peoples.

[ODS 0 | page 20] Argument candidate:
  the SDGs are woefully underfunded at home and internationally

[ODS 0 | page 20] Argument candidate:
  None of their objectives are beyond our reach

[ODS 0 | page 20] Argument candidate:
  the world must devote an increased portion of current output to building up sustainable capital assets for the future

[ODS 0 | page 20] Argument candidate:
  the world must both shift its current investment patterns and increase the overall investment flow in order to build the future we want

[ODS 0 | page 20] Argument candidate:
  Human capital: The skills and health of a productive citizenry, supported by universal health access and coverage, quality education, shared data and knowledge, promotion of a culture of peace and non-violence, global citizenship, and the appreciation of cultural diversity

[ODS 0 | page 20] Argument candidate:
  Natural capital: The capacity and healthy functioning of ecosystems, to be protected by ending human-induced climate change, protecting biodiversity, sustainably managing freshwater resources, and eliminating toxic pollutants

[ODS 0 | page 21] Argument candidate:
  To achieve the SDGs, the world must invest boldly, amply, and consistently in all eight kinds of capital.

[ODS 0 | page 21] Argument candidate:
  Governments too must take the lead in protecting natural capital, while civil society especially must promote social and cultural capital, including mutual understanding across cultures and nations.

[ODS 0 | page 21] Argument candidate:
  Crucially, national government must also work with subnational governments to implement the SDG agenda at the local level, including sustainable urban infrastructure, delivery of social services, and ensuring safe communities.

[ODS 0 | page 21] Argument candidate:
  Virtually all governments of the world have embraced the SDGs in principle. 188 of 193 UN Member States have submitted VNRs for comment by the other nations.

[ODS 0 | page 21] Argument candidate:
  Only five countries, notably the United States, Haiti, Myanmar, South Sudan, and Yemen, have never presented VNRs.

[ODS 0 | page 22] Argument candidate:
  The greatest responsibility for achieving the SDGs and safeguarding the planetary boundaries lies with the G20 members.

[ODS 0 | page 22] Argument candidate:
  With the 2022 Inflation Reduction Act, the Biden government announced its intention to reduce carbon emissions by roughly 40 percent from 2005 levels by 2030, although there are growing concerns that outcomes will lag behind these goals, due in part to the legislation’s lack of an agreed national financing strategy other than tax credits.

[ODS 0 | page 22] Argument candidate:
  The European Union – the world’s second-largest economy and its major lignite producer – has produced the European Green Deal (EGD), which is exemplary in many regards.

[ODS 0 | page 22] Argument candidate:
  Many EU member states demonstrate a high or moderate SDG commitment.

[ODS 0 | page 22] Argument candidate:
  The EGD embraces an EU-wide set of goals, timelines to 2050, and financing strategies across major dimensions of the SDGs: energy decarbonization, climate resilience, circular economy (to cut pollution), sustainable agriculture (the ‘farm-to-fork’ strategy), digital access, and innovation.

[ODS 0 | page 22] Argument candidate:
  The European Regional Development Fund, which provides the EU cohesion funds, is also directed towards the EGD.

[ODS 0 | page 22] Argument candidate:
  The SDSN Framework in the context of international cooperation.

[ODS 0 | page 23] Argument candidate:
  China has reiterated its support for the SDGs, such as in greening its Belt and Road Initiative and launching the Global Development Initiative as a worldwide effort.

[ODS 0 | page 23] Argument candidate:
  At the midpoint of the 2030 Agenda, all countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national strategies, using the principles of the 2030 Agenda (transformative, integrated, inclusive, leaving no one behind) as a yardstick.

[ODS 0 | page 23] Argument candidate:
  Four basic failures stand out: First, implementation is largely left to the national level and on a voluntary basis, without effective multilateral enforcement mechanisms in place.

[ODS 0 | page 23] Argument candidate:
  Developed countries are not being held to account, neither for their adverse spillovers, nor for ensuring adequate flows of financing for sustainable development.

[ODS 0 | page 23] Argument candidate:
  There are no assessments or recommendations by the respective secretariats or decision-making bodies on the adequacy or further enhancement of national implementation, let alone measures of enforcement.

[ODS 0 | page 24] Argument candidate:
  Greatly increase funding to national and subnational governments and private businesses in the emerging economies, especially the LICs and LMICs, to carry out the needed investments.

[ODS 0 | page 24] Argument candidate:
  Revise liquidity structures for LICs,LMICs, and SIDS, especially regarding sovereign debts, to forestall self-fulfilling banking and balance-of-payments crises.

[ODS 0 | page 24] Argument candidate:
  Create ambitious and internationally-agreed upon criteria for sustainable finance that are mandatory for all public financial institutions in HICs, MICs, and LICs alike.

[ODS 0 | page 24] Argument candidate:
  Align private business investment flows in all countries with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 24] Argument candidate:
  Reform current institutional frameworks and develop new, innovative mechanisms to improve the quality and speed of deployment of international cooperation, and monitor progress in an open and timely manner.

[ODS 0 | page 25] Argument candidate:
  Overhauling global governance mechanisms and the global financial architecture is fundamental to unlocking needed investments for sustainable development and ending non-sustainable practices.

[ODS 0 | page 25] Argument candidate:
  The SDGs call for lasting, long-term, directed change.

[ODS 0 | page 25] Argument candidate:
  For governments to combine the objectives of economic development, social inclusion, transparency, energy decarbonization, climate adaptation, water resources and sanitation, biodiversity conservation, digital access, gender equality, circular economy, over-harvesting, universal education, is daunting.

[ODS 0 | page 26] Argument candidate:
  Long-term investment plans are essential for national success in meeting the SDGs.

[ODS 0 | page 26] Argument candidate:
  SDSN has recommended six inter-related long-term transformations: Universal quality education and innovation-based economy, Universal health access and coverage, Zero-carbon energy systems, Sustainable ecosystems, sustainable agriculture, and climate resilience, Sustainable cities, Transformation to universal digital access and services

[ODS 0 | page 26] Argument candidate:
  None can be solved by the private sector alone; indeed, governments will have to take the lead to design policy and financial frameworks within which business can profitably invest and innovate.

[ODS 0 | page 26] Argument candidate:
  The Sustainable Development Report 2023 identifies five levers to be deployed to bring about the necessary transformations: governance, economy and finance, individual and collective action, science and technology, and capacity building.

[ODS 0 | page 26] Argument candidate:
  Planning for the long term, however, illuminates the global financial architecture’s Achilles heel. While the high-income countries (HICs) and upper-middle income countries (UMICs) can and should, in principle, finance these transformations via a combination of budget outlays, public-sector borrowing, and private financing (equity and debt), this is surely not true of the low-Income countries (LICs) and the lower middle-income countries

[ODS 0 | page 27] Argument candidate:
  Increased funding from the Multilateral Development Banks (MDBs) and Public Development Banks (PDBs) to developing countries, linked to investments in the SDGs

[ODS 0 | page 27] Argument candidate:
  an additional US$500 billion per year by 2025 of SDG finance

[ODS 0 | page 27] Argument candidate:

,prefix,model,ods,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL_SGD2023_,qwen2.5-3b,0,53,42,32,0,10
1,GLOBAL_SGD2023_,qwen2.5-3b,1,53,21,9,0,12
2,GLOBAL_SGD2023_,qwen2.5-3b,2,53,14,2,0,12
3,GLOBAL_SGD2023_,qwen2.5-3b,3,53,17,12,0,5
4,GLOBAL_SGD2023_,qwen2.5-3b,4,53,16,5,0,11
5,GLOBAL_SGD2023_,qwen2.5-3b,5,53,10,2,0,8
6,GLOBAL_SGD2023_,qwen2.5-3b,6,53,11,7,0,4
7,GLOBAL_SGD2023_,qwen2.5-3b,7,53,15,10,0,5
8,GLOBAL_SGD2023_,qwen2.5-3b,8,53,12,9,0,3
9,GLOBAL_SGD2023_,qwen2.5-3b,9,53,7,4,0,3
10,GLOBAL_SGD2023_,qwen2.5-3b,10,53,19,13,0,6
11,GLOBAL_SGD2023_,qwen2.5-3b,11,53,10,8,0,2
12,GLOBAL_SGD2023_,qwen2.5-3b,12,53,11,10,0,1
13,GLOBAL_SGD2023_,qwen2.5-3b,13,53,10,9,0,1
14,GLOBAL_SGD2023_,qwen2.5-3b,14,53,4,3,0,1
15,GLOBAL_SGD2023_,qwen2.5-3b,15,53,1,1,0,0
16,GLOBAL_SGD2023_,qwen2.5-3b,16,53,14,10,0,4
17,GLOBAL_SGD2023_,qwen2.5-3b,17,53,17,15,0,2
18,GLOBAL SGD2023,gemma3-4b,0,53,304,167,1,136
19,GLOBAL SGD2023,gemma3-4b,1,53,199,48,0,151
20,GLOBAL SGD2023,gemma3-4b,2,53,248,27,0,221
21,GLOBAL SGD2023,gemma3-4b,3,53,228,36,0,192
22,GLOBAL SGD2023,gemma3-4b,4,53,229,27,1,201
23,GLOBAL SGD2023,gemma3-4b,5,53,181,23,0,158
24,GLOBAL SGD2023,gemma3-4b,6,53,221,26,0,195
25,GLOBAL SGD2023,gemma3-4b,7,53,246,26,0,220
26,GLOBAL SGD2023,gemma3-4b,8,53,252,36,0,216
27,GLOBAL SGD2023,gemma3-4b,9,53,241,37,0,204
28,GLOBAL SGD2023,gemma3-4b,10,53,229,46,0,183
29,GLOBAL SGD2023,gemma3-4b,11,53,247,19,0,228
30,GLOBAL SGD2023,gemma3-4b,12,53,239,24,0,215
31,GLOBAL SGD2023,gemma3-4b,13,53,168,36,0,132
32,GLOBAL SGD2023,gemma3-4b,14,53,221,21,0,200
33,GLOBAL SGD2023,gemma3-4b,15,53,182,19,0,163
34,GLOBAL SGD2023,gemma3-4b,16,53,220,41,0,179
35,GLOBAL SGD2023,gemma3-4b,17,53,238,47,0,191

Stats overall for gemma3-4b in document GLOBAL_SGD2023_:

Updated overall summary:

,prefix,model,ods_max,pages_max,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,17,53,251,161,0,90
1,GLOBAL_SGD2023_,qwen2.5-3b,17,53,4344,867,2,3475

### Gemma3 27B

In [ ]:
prefix = 'OCDE_2024'
model_name="gemma3-27b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')
display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

[ODS 0 | page 7] Argument candidate:
  At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.

[ODS 0 | page 7] Argument candidate:
  Despite this alarming development, the SDGs are still achievable.

[ODS 0 | page 7] Argument candidate:
  None of their objectives are beyond our reach.

[ODS 0 | page 7] Argument candidate:
  The world is off track, but that is all the more reason to double down on the SDGs.

[ODS 0 | page 7] Argument candidate:
  At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.

[ODS 0 | page 7] Argument candidate:
  To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.

[ODS 0 | page 7] Argument candidate:
  The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 7] Argument candidate:
  All countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national SDG strategies and commit to strengthening multilateralism.

[ODS 0 | page 7] Argument candidate:
  National governments must ensure both domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation – by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 7] Argument candidate:
  Achieving the SDGs requires global cooperation guided by the United Nations Charter.

[ODS 0 | page 7] Argument candidate:
  SDG transformations.

[ODS 0 | page 8] Argument candidate:
  Further investment is needed in statistical capacity and data literacy to support long-term pathways for key SDG transformations.

[ODS 0 | page 8] Argument candidate:
  At the halfway mark to 2030, there remains a great deal of work to be done to improve the data and methods underlying the SDG indicator framework.

[ODS 0 | page 8] Argument candidate:
  The SDSN was created in 2012, soon after the Rio+20 Summit, to mobilize the world’s universities, think tanks, and national laboratories on behalf of the SDGs.

[ODS 0 | page 8] Argument candidate:
  Via science-based pathways and analytics, the SDSN supports discussions on SDG implementation at the global, regional, and national levels.

[ODS 0 | page 8] Argument candidate:
  All UN Member States and UN agencies can count on the continued efforts and energies of the SDSN around the world to support all governments, businesses, and civil society in embracing and aligning with the SDGs on sustainable development.

[ODS 0 | page 13] Argument candidate:
  At the midpoint of the 2030 Agenda, the SDGs are far off track.

[ODS 0 | page 13] Argument candidate:
  SDSN offers the following recommendations to accelerate progress over the remaining seven years to 2030, and to set even more ambitious targets to be achieved by 2050 under the SDG framework.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of ‘leave no one behind’.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should present, at regular intervals, their national SDG frameworks in the form of Voluntary National Reviews (VNRs).

[ODS 0 | page 14] Argument candidate:
  All UN Member States should recommit to peaceful cooperation, in the service of the SDGs and all other multilateral agreements.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should commit to accelerating SDG progress to 2030, and to setting even more ambitious SDG targets to 2050, incorporating the recent Kunming-Montreal Biodiversity Framework and the High Seas Treaty.

[ODS 0 | page 15] Argument candidate:
  The SDGs are facing strong headwinds.

[ODS 0 | page 15] Argument candidate:
  Despite significant efforts in some places, national governments on all continents have fallen short in integrating the SDGs into national policies and public investments.

[ODS 0 | page 15] Argument candidate:
  We emphasize that achieving the SDGs rests on five pillars of good governance:

[ODS 0 | page 15] Argument candidate:
  The SDGs are not only a public policy framework; they are an ethical imperative.

[ODS 0 | page 15] Argument candidate:
  The SDGs are seriously off track (Figure 1.1).

[ODS 0 | page 15] Argument candidate:
  According to the annual SDG Index, global achievement of the SDGs rose only slightly, from 64 percent in 2015 to 66 percent in 2019 – far too slowly to meet the goals by 2030, and with highly uneven progress within and between countries.

[ODS 0 | page 15] Argument candidate:
  At current trends, based on simple projections, there is a risk that the gap in SDG outcomes between HICs and LICs will be wider in 2030 (29 points) than it was in 2015 (28 points).

[ODS 0 | page 15] Argument candidate:
  The multiple geopolitical crises in the world today will no doubt place further obstacles on the path to 2030.

[ODS 0 | page 15] Argument candidate:
  If we look at each of the 17 individual SDGs, not a single SDG is projected to be met at the global level.

[ODS 0 | page 17] Argument candidate:
  The World Bank. 2017. Atlas of Sustainable Development Goals.

[ODS 0 | page 17] Argument candidate:
  Providing quality education (SDG 4) for all children is perhaps the single most important key to achieving sustainable development in the long term.

[ODS 0 | page 19] Argument candidate:
  Unless the SDGs are actively pursued, geophysical tipping points combined with technological disruptions could ignite disastrous social conflicts within and between nations.

[ODS 0 | page 19] Argument candidate:
  We firmly believe that international cooperation together with the achievement of the SDGs is the best preventative to this dire and growing risk, and represent an opportunity to create positive social tipping points.

[ODS 0 | page 19] Argument candidate:
  Although all governments are in principle committed to economic justice as enshrined in the Universal Declaration of Human Rights, and to the SDG tenets of ‘leave no one behind’ and ‘reach the furthest behind first’, too few are living up to these commitments.

[ODS 0 | page 19] Argument candidate:
  The report’s recommendations include calling for more racially-disaggregated SDG indicators and for dialogue with stakeholders on how to use these indicators to better allocate resources and prioritize the inclusion of marginalized peoples.

[ODS 0 | page 20] Argument candidate:
  Despite this ominous news, the SDGs are still achievable.

[ODS 0 | page 20] Argument candidate:
  None of their objectives are beyond our reach.

[ODS 0 | page 20] Argument candidate:
  Yes, the world is off-track, but that is all the more reason to double-down on the goals, rather than surrendering to human-made shortfalls in achieving them.

[ODS 0 | page 20] Argument candidate:
  At their core, the SDGs are an investment agenda.

[ODS 0 | page 20] Argument candidate:
  In the most basic terms, the world must devote an increased portion of current output to building up sustainable capital assets for the future, and must deploy such assets effectively.

[ODS 0 | page 21] Argument candidate:
  To achieve the SDGs, the world must invest boldly, amply, and consistently in all eight kinds of capital.

[ODS 0 | page 21] Argument candidate:
  In 2022, the United Nations Secretary-General appointed a High-Level Advisory Board on Effective Multilateralism, with a mandate to develop a list of concrete, actionable recommendations to improve international cooperation and advance the 2030 Agenda for Sustainable Development.

[ODS 0 | page 21] Argument candidate:
  Nation-states hold the primary responsibility for achieving the SDGs.

[ODS 0 | page 21] Argument candidate:
  They hold juridical responsibility for implementing treaty agreements and the rest of the United Nations architecture, including the United Nations Charter, the Universal Declaration of Human Rights, and the SDGs.

[ODS 0 | page 21] Argument candidate:
  Virtually all governments of the world have embraced the SDGs in principle.

[ODS 0 | page 21] Argument candidate:
  188 of 193 UN Member States have submitted VNRs for comment by the other nations.

[ODS 0 | page 22] Argument candidate:
  We call on the United States to formulate an SDG action plan and to present a VNR to the High-Level Political Forum.

[ODS 0 | page 22] Argument candidate:
  In July 2023, the EU is set to present its first Union-wide voluntary review at the United Nations.

[ODS 0 | page 22] Argument candidate:
  China has already presented two VNRs to the HLPF (2016 and 2021).

[ODS 0 | page 23] Argument candidate:
  Recently, China has reiterated its support for the SDGs, such as in greening its Belt and Road Initiative and launching the Global Development Initiative as a worldwide effort.

[ODS 0 | page 23] Argument candidate:
  A key measure for China will be the explicit integration of the SDGs’ domestic and international implementation into the 15th five-year plan (2026–2030).

[ODS 0 | page 23] Argument candidate:
  At the midpoint of the 2030 Agenda, all countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national strategies, using the principles of the 2030 Agenda (transformative, integrated, inclusive, leaving no one behind) as a yardstick.

[ODS 0 | page 23] Argument candidate:
  Achieving the SDGs will require a transformative global approach.

[ODS 0 | page 23] Argument candidate:
  Both the 2030 Agenda and the Paris Climate Agreement established mechanisms to encourage and monitor their implementation by nation-states.

[ODS 0 | page 23] Argument candidate:
  However, experience so far with VNRs and Nationally Determined Contributions (NDCs), respectively, demonstrate that these mechanisms – despite some progress – have not delivered the effort necessary to achieve global goals.

[ODS 0 | page 24] Argument candidate:
  International cooperation is trapped by bureaucratic institutional frameworks that reduce the speed, efficacy, and efficiency of funding to meet the SDGs, and that fail to provide the framework for large-scale SDG financing.

[ODS 0 | page 24] Argument candidate:
  Align private business investment flows in all countries with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 26] Argument candidate:
  Long-term investment plans are essential for national success in meeting the SDGs.

[ODS 0 | page 26] Argument candidate:
  SDSN has recommended six inter-related long-term transformations:20

[ODS 0 | page 26] Argument candidate:
  1. Universal quality education and innovation-based economy

[ODS 0 | page 26] Argument candidate:
  2. Universal health access and coverage

[ODS 0 | page 26] Argument candidate:
  3. Zero-carbon energy systems

[ODS 0 | page 26] Argument candidate:
  4. Sustainable ecosystems, sustainable agriculture, and climate resilience

[ODS 0 | page 26] Argument candidate:
  5. Sustainable cities

[ODS 0 | page 26] Argument candidate:
  6. Transformation to universal digital access and services

[ODS 0 | page 27] Argument candidate:
  In his opening address to the UN General Assembly on September 20, 2022, UN Secretary-General António Guterres called on the G20 to launch an “SDG Stimulus” to offset the deteriorating market conditions faced by developing countries and to accelerate progress towards the SDGs and the Paris Climate Agreement.

[ODS 0 | page 27] Argument candidate:
  The SDG Stimulus plan recommended by the High-Level Working Group and introduced by SG Guterres last February25 has five main components:

[ODS 0 | page 27] Argument candidate:
  Increased funding from the Multilateral Development Banks (MDBs) and Public Development Banks (PDBs) to developing countries, linked to investments in the SDGs, a need echoed in the 2023 report of the High-Level Advisory Board on Effective Multilateralism26

[ODS 0 | page 28] Argument candidate:
  All United Nations agencies should put the SDGs at the centerpiece of their strategies, programs, and reporting.

[ODS 0 | page 28] Argument candidate:
  The World Bank and the other MDBs should put the SDGs at the center of their financing strategies, performance reviews, and reporting.

[ODS 0 | page 28] Argument candidate:
  The IMF should build its national reviews (Article IV), debt sustainability framework (DSF), and country programming around the public policies and financing needed for national success in achieving the SDGs.

[ODS 0 | page 28] Argument candidate:
  The G20 should organize its financial cooperation, reporting, and metrics around the reform of the GFA, as needed to achieve the SDGs.

[ODS 0 | page 28] Argument candidate:
  All UN Member States should present VNRs at least once every three years.

[ODS 0 | page 28] Argument candidate:
  It is especially urgent that the five countries that have not yet presented VNRs should do so no later than 2024.

[ODS 0 | page 28] Argument candidate:
  United Nations agencies, multilateral organizations, and Member States need to increase investment in, and coordination of, national and international data and statistical systems and scientific capacity to assess SDG progress and support sustainable development decision making and investment, including disaggregated data by region, social stratification, and other criteria as helpful.

[ODS 0 | page 29] Argument candidate:
  SDSN is closely following and supporting the EU’s endeavors to achieve the SDGs, inter alia by the EU’s European Green Deal.

[ODS 0 | page 29] Argument candidate:
  SDSN is supporting the African Development Bank to develop a strategic plan to accelerate Africa’s sustainable development, with the aim of the African Union achieving high-income status and sustainable development by 2063, the 100th anniversary of the Organization of African Unity.

[ODS 0 | page 29] Argument candidate:
  SDSN is supporting the African Development Bank to develop a strategic plan to accelerate Africa’s sustainable development

[ODS 0 | page 29] Argument candidate:
  SDSN recognizes this gap in the practical means of implementation of city governments, and is currently working with the major urban think tanks and global urban networks (including the C40 and ICLEI) to address the challenge of sub-national financing of the SDGs.

[ODS 0 | page 30] Argument candidate:
  SDG 16 recognizes the vital role of peaceful and inclusive societies, and SDG 17 underscores the need for global outreach and cooperation to achieve the Goals.

[ODS 0 | page 30] Argument candidate:
  The SDSN was created in 2012, soon after the Rio+20 Summit which mobilized the world’s universities, think tanks, and national laboratories on behalf of the SDGs.

[ODS 0 | page 30] Argument candidate:
  We aim to ensure that institutions of higher learning and public policy research centres in all 193 UN Member States are actively part of the SDSN.

[ODS 0 | page 30] Argument candidate:
  SDSN is working closely with the UNESCO SDG 4 High-Level Steering Committee on these two major issues, via Mission 4.7 through an SDG Academy Partnership with the Open Education Resources Recommendation team at UNESCO.

[ODS 0 | page 31] Argument candidate:
  They are the work of the 21st century.

[ODS 0 | page 31] Argument candidate:
  These are signal achievements of humanity, to have come together across all nations to adopt a common set of challenges.

[ODS 0 | page 31] Argument candidate:
  At the mid-point of the SDG agenda, we are far off target.

[ODS 0 | page 32] Argument candidate:
  First, that UN Member States, at the 2023 SDG Summit and the 2024 Summit of the Future, recommit boldly, strongly, and proactively to the SDGs, accelerate progress to 2030, and adopt even more ambitious SDG targets and objectives to mid-century, also incorporating recent international agreements on oceans and biodiversity.

[ODS 0 | page 32] Argument candidate:
  Second, UN Member States, starting with the G20 meeting this September in India, should adopt an SDG Stimulus to accelerate progress towards the SDGs by 2030 and enhance global governance for enforcing the implementation of the SDGs by all countries.

[ODS 0 | page 34] Argument candidate:
  The SDG Index and Dashboards track the annual progress of all 193 UN Member States towards the SDGs.

[ODS 0 | page 34] Argument candidate:
  At the midpoint of the 2030 Agenda, however, the SDGs are far off track.

[ODS 0 | page 34] Argument candidate:
  The SDG Index is an assessment of each country’s overall performance on the 17 SDGs, giving equal weight to each Goal.

[ODS 0 | page 34] Argument candidate:
  The dashboard and trend arrows help identify priorities for further actions and indicate whether countries are on track or off track to achieve the goals and targets by 2030, based on latest trend data.

[ODS 0 | page 38] Argument candidate:
  As detailed in the Europe Sustainable Development Report 2022, trends on several leave-no-one-behind indicators are not heading in the right direction in many EU member states (Lafortune et al. 2022).

[ODS 0 | page 43] Argument candidate:
  The 2030 Agenda and the SDGs recognize the importance of international spillovers in several crucial ways.

[ODS 0 | page 43] Argument candidate:
  SDG 17 (Partnerships for the Goals) calls for ‘policy coherence’ for sustainable development.

[ODS 0 | page 43] Argument candidate:
  SDG 17 (Partnerships for the Goals) calls on all countries to enhance policy coherence for sustainable development (PCSD).

[ODS 0 | page 58] Argument candidate:
  There was no expectation in 2015, when the SDGs and Agenda 2030 were adopted, that all goals and targets would be achieved at their midpoint.

[ODS 0 | page 58] Argument candidate:
  By 2023, one would expect that most countries would have implemented ambitious policy, regulatory and investment frameworks compatible with achieving major SDG transformations.

[ODS 0 | page 58] Argument candidate:
  It could also be expected that all countries would have at least once documented their progress and their plans for achieving the SDGs in a Voluntary National Review (VNRs) presented at the United Nations.

[ODS 0 | page 58] Argument candidate:
  Nation-states continue to hold the primary responsibility for achieving the SDGs.

[ODS 0 | page 59] Argument candidate:
  By July 2023, all UN Member States will have presented a VNR except for Haiti, Myanmar, South Sudan, the United States and Yemen.

[ODS 0 | page 59] Argument candidate:
  Official high-level speeches and the preparation of VNRs (as the official government-led process to report on SDG progress, gaps, and policy efforts) provide relevant proxies to gauge political commitment to the SDGs.

[ODS 0 | page 62] Argument candidate:
  since 2016, 188 UN Member States have prepared VNRs (see Figure 3.2).

[ODS 0 | page 62] Argument candidate:
  At the midpoint of the 2030 Agenda, only five countries have never submitted a VNR, among them the United States (HLPF, 2023).

[ODS 0 | page 62] Argument candidate:
  Some countries take a mainstreaming approach, where SDGs are implemented by each government ministry within the scope of its mandate (instead of via an overarching national action plan).

[ODS 0 | page 62] Argument candidate:
  For many, this takes the form of a national sustainability strategy explicitly linked to the 2030 Agenda goals and targets.

[ODS 0 | page 62] Argument candidate:

,prefix,model,ods,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,gemma3-27b,0,53,160,53,0,107
1,GLOBAL SGD2023,gemma3-27b,1,53,40,21,0,19
2,GLOBAL SGD2023,gemma3-27b,2,53,32,12,0,20
3,GLOBAL SGD2023,gemma3-27b,3,53,30,16,0,14
4,GLOBAL SGD2023,gemma3-27b,4,53,33,16,0,17
5,GLOBAL SGD2023,gemma3-27b,5,53,10,6,0,4
6,GLOBAL SGD2023,gemma3-27b,6,53,19,7,0,12
7,GLOBAL SGD2023,gemma3-27b,7,53,16,7,0,9
8,GLOBAL SGD2023,gemma3-27b,8,53,23,14,0,9
9,GLOBAL SGD2023,gemma3-27b,9,53,34,10,0,24
10,GLOBAL SGD2023,gemma3-27b,10,53,23,15,0,8
11,GLOBAL SGD2023,gemma3-27b,11,53,23,11,0,12
12,GLOBAL SGD2023,gemma3-27b,12,53,37,18,0,19
13,GLOBAL SGD2023,gemma3-27b,13,53,58,31,0,27
14,GLOBAL SGD2023,gemma3-27b,14,53,15,7,0,8
15,GLOBAL SGD2023,gemma3-27b,15,53,27,19,1,7
16,GLOBAL SGD2023,gemma3-27b,16,53,47,27,0,20
17,GLOBAL SGD2023,gemma3-27b,17,53,81,40,0,41

Stats overall for gemma3-27b in document GLOBAL_SGD2023:

TypeError: save_overall_summary() missing 1 required positional argument: 'model_name'

### Llama 3.3 70B

In [ ]:
prefix = 'OCDE_2024'
model_name="llama3.3-70b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')
display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

[ODS 0 | page 7] Argument candidate:
  At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.

[ODS 0 | page 7] Argument candidate:
  Since the outbreak of the pandemic in 2020 and other simultaneous crises, SDG progress has stalled globally.

[ODS 0 | page 7] Argument candidate:
  The world is off track, but that is all the more reason to double down on the SDGs.

[ODS 0 | page 7] Argument candidate:
  At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.

[ODS 0 | page 7] Argument candidate:
  To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.

[ODS 0 | page 7] Argument candidate:
  The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 7] Argument candidate:
  All countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national SDG strategies and commit to strengthening multilateralism.

[ODS 0 | page 7] Argument candidate:
  National governments must ensure both domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation – by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 7] Argument candidate:
  Achieving the SDGs requires global cooperation guided by the United Nations Charter.

[ODS 0 | page 7] Argument candidate:
  We introduce in the report this year a pilot index of countries commitment to and support of multilateralism under the UN Charter. SDG transformations.

[ODS 0 | page 8] Argument candidate:
  Further investment is needed in statistical capacity and data literacy to support long-term pathways for key SDG transformations.

[ODS 0 | page 8] Argument candidate:
  At the halfway mark to 2030, there remains a great deal of work to be done to improve the data and methods underlying the SDG indicator framework.

[ODS 0 | page 8] Argument candidate:
  According to major international studies, few teenagers can differentiate between a fact and an opinion. As underlined during the United Nations World Data Forum 2023 and in the 27 April Hangzhou Declaration, investing in statistical capacity, science, and data literacy are important priorities for achieving the SDGs.

[ODS 0 | page 8] Argument candidate:
  The SDSN and its global network will double-down on efforts to implement the SDGs by 2030 and beyond.

[ODS 0 | page 8] Argument candidate:
  Via science-based pathways and analytics, the SDSN supports discussions on SDG implementation at the global, regional, and national levels.

[ODS 0 | page 8] Argument candidate:
  All UN Member States and UN agencies can count on the continued efforts and energies of the SDSN around the world to support all governments, businesses, and civil society in embracing and aligning with the SDGs on sustainable development.

[ODS 0 | page 13] Argument candidate:
  The grim reality is that at the midpoint of the 2030 Agenda, the SDGs are far off track.

[ODS 0 | page 13] Argument candidate:
  United Nations Secretary-General António Guterres has urged world leaders to come together at the 2023 SDG Summit in September to deliver a “Rescue Plan for People and Planet”

[ODS 0 | page 13] Argument candidate:
  As the world’s nations prepare to meet in September to review the progress the world has made so far towards achieving the SDGs, at the midpoint of the 2030 Agenda, SDSN emphasizes six areas for immediate action.

[ODS 0 | page 13] Argument candidate:
  Most urgently, UN Member States should adopt an SDG Stimulus, to close the massive financing gap faced by many developing economies.

[ODS 0 | page 13] Argument candidate:
  UN Member States must endorse a deep and overdue reform of the global financial architecture.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of ‘leave no one behind’.

[ODS 0 | page 14] Argument candidate:
  SDSN recommends that national pathways should include six key transformations:

[ODS 0 | page 14] Argument candidate:
  All UN Member States should present, at regular intervals, their national SDG frameworks in the form of Voluntary National Reviews (VNRs).

[ODS 0 | page 14] Argument candidate:
  To date, 188 of the 193 UN Member States have already presented VNRs.

[ODS 0 | page 14] Argument candidate:
  The report that follows offers SDSN’s update on the state of the SDGs at their mid-point, highlighting the growing dangers of adverse environmental, social, and economic “tipping points” and identifying key ways that the global community can and should accelerate SDG progress.

[ODS 0 | page 14] Argument candidate:
  UN Member States should commit to accelerating SDG progress to 2030, and to setting even more ambitious SDG targets to 2050, incorporating the recent Kunming-Montreal Biodiversity Framework and the High Seas Treaty.

[ODS 0 | page 15] Argument candidate:
  The SDGs are facing strong headwinds. Despite significant efforts in some places, national governments on all continents have fallen short in integrating the SDGs into national policies and public investments.

[ODS 0 | page 15] Argument candidate:
  We emphasize that achieving the SDGs rests on five pillars of good governance:

[ODS 0 | page 15] Argument candidate:
  The SDGs are not only a public policy framework; they are an ethical imperative.

[ODS 0 | page 15] Argument candidate:
  Dire shortfalls in meeting the SDGs The SDGs are seriously off track (Figure 1.1).

[ODS 0 | page 15] Argument candidate:
  According to the annual SDG Index, global achievement of the SDGs rose only slightly, from 64 percent in 2015 to 66 percent in 2019 – far too slowly to meet the goals by 2030, and with highly uneven progress within and between countries.

[ODS 0 | page 15] Argument candidate:
  The world is also seriously off track to meet the Paris agreement climate targets and SDG 13 (Figure 1.3).

[ODS 0 | page 16] Argument candidate:
  Dire shortfalls in meeting the SDGs

[ODS 0 | page 16] Argument candidate:
  SDG Index world average: pre-pandemic trend and trend needed to achieve the SDGs by 2030

[ODS 0 | page 16] Argument candidate:
  Trend needed to achieve the SDGs

[ODS 0 | page 17] Argument candidate:
  6 of nearly 90% of global fish stocks.6 The crises facing our oceans are unabated, multidimensional, and complex.

[ODS 0 | page 17] Argument candidate:
  The 2021 UN Food Systems Summit raised many urgent concerns around improving the sustainability, affordability, and quality of food across the world (SDG 2).

[ODS 0 | page 17] Argument candidate:
  Providing quality education (SDG 4) for all children is perhaps the single most important key to achieving sustainable development in the long term.

[ODS 0 | page 17] Argument candidate:
  Figure 1.2 Observed and projected gaps in SDG Index score between HICs and LICs (in percentage points)

[ODS 0 | page 17] Argument candidate:
  Part 1. How to Achieve the SDGs: The SDSN Framework planetary boundaries that regulate the Earth system.

[ODS 0 | page 19] Argument candidate:
  Unless the SDGs are actively pursued, geophysical tipping points combined with technological disruptions could ignite disastrous social conflicts within and between nations.

[ODS 0 | page 19] Argument candidate:
  We firmly believe that international cooperation together with the achievement of the SDGs is the best preventative to this dire and growing risk, and represent an opportunity to create positive social tipping points: for example, through equal access to high-quality education (SDG 4), and by fighting all forms of inequalities, including income and wealth inequalities (SDG 10).

[ODS 0 | page 19] Argument candidate:
  Although all governments are in principle committed to economic justice as enshrined in the Universal Declaration of Human Rights, and to the SDG tenets of ‘leave no one behind’ and ‘reach the furthest behind first’, too few are living up to these commitments, especially as powerful groups block adequate public support for weaker groups.

[ODS 0 | page 19] Argument candidate:
  In her 2022 report on the SDGs, E. Tendayi Achiume – UN Special Rapporteur on contemporary forms of racism, racial discrimination, xenophobia and related intolerance – noted that racism and racial discrimination are key barriers to sustainable development, and called attention to the failure of some States to collect disaggregated data on race, ethnicity, indigeneity, and migration status in the context of the 2030 Agenda.

[ODS 0 | page 19] Argument candidate:
  The report’s recommendations include calling for more racially-disaggregated SDG indicators and for dialogue with stakeholders on how to use these indicators to better allocate resources and prioritize the inclusion of marginalized peoples.

[ODS 0 | page 20] Argument candidate:
  Despite this ominous news, the SDGs are still achievable.

[ODS 0 | page 20] Argument candidate:
  Investing in the SDGs

[ODS 0 | page 20] Argument candidate:
  The world must devote an increased portion of current output to building up sustainable capital assets for the future, and must deploy such assets effectively.

[ODS 0 | page 20] Argument candidate:
  At their core, the SDGs are an investment agenda.

[ODS 0 | page 20] Argument candidate:
  Yes, the world is off-track, but that is all the more reason to double-down on the goals, rather than surrendering to human-made shortfalls in achieving them.

[ODS 0 | page 20] Argument candidate:
  The SDGs are woefully underfunded at home and internationally.

[ODS 0 | page 21] Argument candidate:
  To achieve the SDGs, the world must invest boldly, amply, and consistently in all eight kinds of capital.

[ODS 0 | page 21] Argument candidate:
  Parallel to investing in the SDGs, the world needs to stop investing in activities that threaten planetary boundaries, destroy human and natural capital, and harm social cohesion.

[ODS 0 | page 21] Argument candidate:
  In 2022, the United Nations Secretary-General appointed a High-Level Advisory Board on Effective Multilateralism, with a mandate to develop a list of concrete, actionable recommendations to improve international cooperation and advance the 2030 Agenda for Sustainable Development.

[ODS 0 | page 21] Argument candidate:
  National governments must ensure both the domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 21] Argument candidate:
  Virtually all governments of the world have embraced the SDGs in principle. 188 of 193 UN Member States have submitted VNRs for comment by the other nations.

[ODS 0 | page 21] Argument candidate:
  The Nordic countries and European Union have shown considerable support for the SDGs. So too have many developing countries in the G20.

[ODS 0 | page 22] Argument candidate:
  The greatest responsibility for achieving the SDGs and safeguarding the planetary boundaries lies with the G20 members.

[ODS 0 | page 22] Argument candidate:
  The United States, as the world’s biggest economy in terms of GDP at market prices and its biggest oil and gas producer, has a responsibility both to itself and to the rest of the world to immediately embark on an ambitious transformation towards the SDGs, as well as towards other global climate and biodiversity goals.

[ODS 0 | page 22] Argument candidate:
  We call on the United States to formulate an SDG action plan and to present a VNR to the High-Level Political Forum.

[ODS 0 | page 22] Argument candidate:
  The European Union – the world’s second-largest economy and its major lignite producer – has produced the European Green Deal (EGD), which is exemplary in many regards.

[ODS 0 | page 22] Argument candidate:
  However, the EGD and EU policies at large lack a comprehensive alignment to the SDGs, politically agreed targets for many SDG indicators, and clarity on how to achieve the SDGs.

[ODS 0 | page 22] Argument candidate:
  The EU has also highlighted the strategic role of the private sector in achieving the SDGs, by implementing a new directive asking companies to publish sustainability reports and, in particular in the food sector, by promoting the “Code of Conduct on Responsible Food Business and Marketing Practices”

[ODS 0 | page 22] Argument candidate:
  China intends to implement the SDGs by integrating them into its medium and long-term national development strategies, such as its five-year plans.

[ODS 0 | page 22] Argument candidate:
  China has already presented two VNRs to the HLPF (2016 and 2021).

[ODS 0 | page 22] Argument candidate:
  In July 2023, the EU is set to present its first Union-wide voluntary review at the United Nations.

[ODS 0 | page 22] Argument candidate:
  This presents a good opportunity for the EU to send a strong message to the international community, and to demonstrate its commitment to and leadership on the SDGs.

[ODS 0 | page 23] Argument candidate:
  A key measure for China will be the explicit integration of the SDGs’ domestic and international implementation into the 15th five-year plan (2026–2030).

[ODS 0 | page 23] Argument candidate:
  We urge all G20 governments to show the leadership required of them.

[ODS 0 | page 23] Argument candidate:
  At the midpoint of the 2030 Agenda, all countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national strategies, using the principles of the 2030 Agenda (transformative, integrated, inclusive, leaving no one behind) as a yardstick.

[ODS 0 | page 23] Argument candidate:
  Achieving the SDGs will require a transformative global approach.

[ODS 0 | page 23] Argument candidate:
  Both the 2030 Agenda and the Paris Climate Agreement established mechanisms to encourage and monitor their implementation by nation-states. However, experience so far with VNRs and Nationally Determined Contributions (NDCs), respectively, demonstrate that these mechanisms – despite some progress – have not delivered the effort necessary to achieve global goals.

[ODS 0 | page 23] Argument candidate:
  Even the progress on consistent national reporting on SDG indicators is inadequate.

[ODS 0 | page 24] Argument candidate:
  It is widely recognized that the world needs to overhaul the GFA. Such an overhaul should address the failures above and aim to achieve six objectives:

[ODS 0 | page 24] Argument candidate:
  International cooperation is trapped by bureaucratic institutional frameworks that reduce the speed, efficacy, and efficiency of funding to meet the SDGs, and that fail to provide the framework for large-scale SDG financing.

[ODS 0 | page 24] Argument candidate:
  Align private business investment flows in all countries with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 24] Argument candidate:
  Reform current institutional frameworks and develop new, innovative mechanisms to improve the quality and speed of deployment of international cooperation, and monitor progress in an open and timely manner.

[ODS 0 | page 25] Argument candidate:
  Overhauling global governance mechanisms and the global financial architecture is fundamental to unlocking needed investments for sustainable development and ending non-sustainable practices.

[ODS 0 | page 25] Argument candidate:
  The SDG policy agenda is complex. The SDGs call for lasting, long-term, directed change.

[ODS 0 | page 26] Argument candidate:
  SDSN’s strategy to achieve the SDGs

[ODS 0 | page 26] Argument candidate:
  Long-term investment plans are essential for national success in meeting the SDGs.

[ODS 0 | page 26] Argument candidate:
  SDSN has recommended six inter-related long-term transformations:

[ODS 0 | page 26] Argument candidate:
  Each of these challenges will require large-scale public and private investments to mid-century, technological transformation, and a sound financing strategy.

[ODS 0 | page 26] Argument candidate:
  The Sustainable Development Report 2023 identifies five levers to be deployed to bring about the necessary transformations: governance, economy and finance, individual and collective action, science and technology, and capacity building.

[ODS 0 | page 26] Argument candidate:
  Planning for the long term, however, illuminates the global financial architecture’s Achilles heel.

[ODS 0 | page 26] Argument candidate:
  SDSN has joined the Group on Earth Observations (GEO)19 as a Participating Organization, supporting the efforts of this voluntary intergovernmental community to focus national, international, and private sector investments in Earth observations on urgent SDG needs.

[ODS 0 | page 27] Argument candidate:
  To make sure that existing financial resources and the required additional resources are used for sustainable investments, international finance institutions must fully incorporate achieving the SDGs and safeguarding the planetary boundaries into their core mandates, and monitor these regarding all countries, poorer and richer alike.

[ODS 0 | page 27] Argument candidate:
  Global infrastructure programs like China’s Belt and Road, the EU’s Global Gateway, or the United States’ Build Back Better World initiatives must be much better aligned with the SDGs and coordinated with each other.

[ODS 0 | page 27] Argument candidate:
  In his opening address to the UN General Assembly on September 20, 2022, UN Secretary-General António Guterres called on the G20 to launch an “SDG Stimulus” to offset the deteriorating market conditions faced by developing countries and to accelerate progress towards the SDGs and the Paris Climate Agreement.

[ODS 0 | page 27] Argument candidate:
  SDSN provided the Secretariat of a High-Level Informal Working Group for the SDG Stimulus (HLIWG), that made the case for an SDG Stimulus of an additional US$500 billion per year by 2025 of SDG finance.

[ODS 0 | page 27] Argument candidate:
  The SDG Stimulus plan recommended by the High-Level Working Group and introduced by SG Guterres last February has five main components:

[ODS 0 | page 27] Argument candidate:
  According to IMF estimates in 2019, the financing gap facing 57 low-income developing countries (LICs and LMICs that are eligible for IMF concessional financing) to cover very basic investments in health, education, power, roads, and water and sanitation was in the order of US$300 billion to US$500 billion per year.

[ODS 0 | page 27] Argument candidate:
  Adding in these extra needs, the global SDG financing gap is perhaps US$1 trillion per year, or roughly 1% of gross world product (GWP) at market prices.

[ODS 0 | page 27] Argument candidate:
  As a rough rule of thumb based on work by SDSN and the IMF, the LICs need roughly 20% of their GDP in increased SDG investment outlays while the LMICs need roughly 10%, though precise amounts vary by country.

[ODS 0 | page 28] Argument candidate:
  The urgent objective of the SDG Stimulus is to address – in practical terms and at scale – the chronic shortfall of international SDG financing facing the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 28] Argument candidate:

NameError: name 'path_output_txt' is not defined

### Deepseek r1 70B

In [ ]:
prefix = 'OCDE_2024'
model_name="deepseek-r1-70b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')
display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
dfGlobal2023 = save_overall_summary(res, path_output_stats, model_name).rename(columns={"pages_max": "pages"}).drop(columns=["ods_max"])
dfGlobal2023

[ODS 0 | page 7] Argument candidate:
  At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.

[ODS 0 | page 7] Argument candidate:
  Despite this alarming development, the SDGs are still achievable. None of their objectives are beyond our reach.

[ODS 0 | page 7] Argument candidate:
  The world is off track, but that is all the more reason to double down on the SDGs.

[ODS 0 | page 7] Argument candidate:
  At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.

[ODS 0 | page 7] Argument candidate:
  To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.

[ODS 0 | page 7] Argument candidate:
  The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 7] Argument candidate:
  All countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national SDG strategies and commit to strengthening multilateralism.

[ODS 0 | page 7] Argument candidate:
  National governments must ensure both domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation – by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 7] Argument candidate:
  Achieving the SDGs requires global cooperation guided by the United Nations Charter.

[ODS 0 | page 7] Argument candidate:
  SDG transformations.

[ODS 0 | page 8] Argument candidate:
  Further investment is needed in statistical capacity and data literacy to support long-term pathways for key SDG transformations.

[ODS 0 | page 8] Argument candidate:
  At the halfway mark to 2030, there remains a great deal of work to be done to improve the data and methods underlying the SDG indicator framework.

[ODS 0 | page 8] Argument candidate:
  Evidence suggests that since 2016 there has been only limited progress and convergence in countries’ statistical capacity, including LICs and LMICs, and that international funding for data and statistics fell between 2019 and 2021.

[ODS 0 | page 8] Argument candidate:
  Also, in an information-rich and post-truth environment, citizens and decision-makers need knowledge and tools to transform data and science into evidence, actions, and long-term policies.

[ODS 0 | page 8] Argument candidate:
  According to major international studies, few teenagers can differentiate between a fact and an opinion.

[ODS 0 | page 8] Argument candidate:
  As underlined during the United Nations World Data Forum 2023 and in the 27 April Hangzhou Declaration, investing in statistical capacity, science, and data literacy are important priorities for achieving the SDGs.

[ODS 0 | page 8] Argument candidate:
  The SDSN and its global network will double-down on efforts to implement the SDGs by 2030 and beyond.

[ODS 0 | page 8] Argument candidate:
  Via science-based pathways and analytics, the SDSN supports discussions on SDG implementation at the global, regional, and national levels.

[ODS 0 | page 8] Argument candidate:
  All UN Member States and UN agencies can count on the continued efforts and energies of the SDSN around the world to support all governments, businesses, and civil society in embracing and aligning with the SDGs on sustainable development.

[ODS 0 | page 13] Argument candidate:
  The grim reality is that at the midpoint of the 2030 Agenda, the SDGs are far off track.

[ODS 0 | page 13] Argument candidate:
  As the world’s nations prepare to meet in September to review the progress the world has made so far towards achieving the SDGs, at the midpoint of the 2030 Agenda, SDSN emphasizes six areas for immediate action.

[ODS 0 | page 13] Argument candidate:
  Most urgently, UN Member States should adopt an SDG Stimulus, to close the massive financing gap faced by many developing economies.

[ODS 0 | page 13] Argument candidate:
  UN Member States must endorse a deep and overdue reform of the global financial architecture.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of ‘leave no one behind’.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should present, at regular intervals, their national SDG frameworks in the form of Voluntary National Reviews (VNRs). To date, 188 of the 193 UN Member States have already presented VNRs. Five countries (Haiti, Myanmar, South Sudan, the United States, and Yemen) have yet to do so, and should prepare to do so with urgency.

[ODS 0 | page 14] Argument candidate:
  UN Member States should commit to accelerating SDG progress to 2030, and to setting even more ambitious SDG targets to 2050, incorporating the recent Kunming-Montreal Biodiversity Framework and the High Seas Treaty.

[ODS 0 | page 15] Argument candidate:
  The SDGs are facing strong headwinds. Despite significant efforts in some places, national governments on all continents have fallen short in integrating the SDGs into national policies and public investments.

[ODS 0 | page 15] Argument candidate:
  Moreover, societal polarization, populism, and growing geopolitical conflict are hindering the global cooperation needed to achieve the SDGs.

[ODS 0 | page 15] Argument candidate:
  The international financial architecture is failing to channel global savings to SDG investments at the needed pace and scale.

[ODS 0 | page 15] Argument candidate:
  We emphasize that achieving the SDGs rests on five pillars of good governance: 1. Preparing long-term SDG pathways to guide public policy; 2. Ensuring SDG financing at the necessary scale and timing; 3. Promoting global cooperation and reducing geopolitical conflict and tension; 4. Supporting innovation to broaden social inclusion and environmental sustainability; 5. Regular reporting on SDG progress and performance.

[ODS 0 | page 15] Argument candidate:
  The SDGs are not only a public policy framework; they are an ethical imperative.

[ODS 0 | page 15] Argument candidate:
  They are grounded in the Universal Declaration of Human Rights, which celebrates its 75th anniversary this year.

[ODS 0 | page 15] Argument candidate:
  As the Universal Declaration makes clear, and the SDGs make explicit, social justice and sustainable development require the full realization of the rights of all people.

[ODS 0 | page 15] Argument candidate:
  The UN Sustainable Development Solutions Network (SDSN) is dedicated to finding and amplifying practical solutions to achieve the SDGs and closely-related global goals (such as the Paris climate agreement and the Kunming-Montreal Biodiversity Framework).

[ODS 0 | page 15] Argument candidate:
  We emphasize that all these global goals are interrelated and must be achieved together.

[ODS 0 | page 15] Argument candidate:
  Dire shortfalls in meeting the SDGs The SDGs are seriously off track (Figure 1.1).

[ODS 0 | page 15] Argument candidate:
  SDG progress was already very slow in the five years to 2020.

[ODS 0 | page 15] Argument candidate:
  According to the annual SDG Index, global achievement of the SDGs rose only slightly, from 64 percent in 2015 to 66 percent in 2019 – far too slowly to meet the goals by 2030, and with highly uneven progress within and between countries.

[ODS 0 | page 15] Argument candidate:
  Then with the onset of the pandemic, progress stopped.

[ODS 0 | page 15] Argument candidate:
  As of 2022, the global SDG Index is below 67%. At current trends, based on simple projections, there is a risk that the gap in SDG outcomes between HICs and LICs will be wider in 2030 (29 points) than it was in 2015 (28 points).

[ODS 0 | page 15] Argument candidate:
  This means that we are at risk of losing a decade of progress towards convergence globally (Figure 1.2).

[ODS 0 | page 15] Argument candidate:
  The multiple geopolitical crises in the world today will no doubt place further obstacles on the path to 2030.

[ODS 0 | page 15] Argument candidate:
  If we look at each of the 17 individual SDGs, not a single SDG is projected to be met at the global level.

[ODS 0 | page 16] Argument candidate:
  Dire shortfalls in meeting the SDGs

[ODS 0 | page 16] Argument candidate:
  Current Nationally Determined Contribution (NDC) targets, if implemented, would still lead to around 2.4°C warming by 2100.

[ODS 0 | page 16] Argument candidate:
  Even taking the net-zero pledges of many countries into account, best-case scenarios given current pledges would lead to around 1.8°C warming by 2100.

[ODS 0 | page 16] Argument candidate:
  Water scarcity affects more than 40% of the world’s population.

[ODS 0 | page 16] Argument candidate:
  An estimated 1.8 billion people depend on drinking water contaminated by human waste.

[ODS 0 | page 16] Argument candidate:
  Unsustainable water management practices, including chemical discharges into water supply systems for irrigation, affect the functioning of ecosystems services.

[ODS 0 | page 16] Argument candidate:
  Global resource consumption assessments for rare earth elements are critical.

[ODS 0 | page 16] Argument candidate:
  Although reserves of these elements do not exist in concentrated clusters – which make them inefficient for mining – certain countries are quite dominant in this field, producing 98% of the world’s supply.

[ODS 0 | page 16] Argument candidate:
  As demand for rare earth elements is increasing tremendously, their scarcity is becoming more evident.

[ODS 0 | page 17] Argument candidate:
  The 2021 UN Food Systems Summit raised many urgent concerns around improving the sustainability, affordability, and quality of food across the world (SDG 2).

[ODS 0 | page 17] Argument candidate:
  Providing quality education (SDG 4) for all children is perhaps the single most important key to achieving sustainable development in the long term.

[ODS 0 | page 17] Argument candidate:
  The UN General Assembly’s Transforming Education Summit held in September 2022 was a critical meeting to spur national and global efforts to transform education to give all people the skills and knowledge to end poverty, protect the environment, and build peaceful and inclusive societies.

[ODS 0 | page 17] Argument candidate:
  Note: Projected gap by 2030 is based on extrapolation of annual growth rate on the SDG Index over the period 2019-2021. Pre-pandemic projected gap is based on an extrapolation of SDG Index annual growth rates over the period 2015-2019.

[ODS 0 | page 17] Argument candidate:
  Part 1. How to Achieve the SDGs: The SDSN Framework "planetary boundaries" that regulate the Earth system.

[ODS 0 | page 19] Argument candidate:
  Unless the SDGs are actively pursued, geophysical tipping points combined with technological disruptions could ignite disastrous social conflicts within and between nations.

[ODS 0 | page 19] Argument candidate:
  We firmly believe that international cooperation together with the achievement of the SDGs is the best preventative to this dire and growing risk, and represent an opportunity to create positive social tipping points: for example, through equal access to high-quality education (SDG 4), and by fighting all forms of inequalities, including income and wealth inequalities (SDG 10).

[ODS 0 | page 19] Argument candidate:
  Although all governments are in principle committed to economic justice as enshrined in the Universal Declaration of Human Rights, and to the SDG tenets of ‘leave no one behind’ and ‘reach the furthest behind first’, too few are living up to these commitments, especially as powerful groups block adequate public support for weaker groups.

[ODS 0 | page 19] Argument candidate:
  She noted however that, while disrupting the dynamic of racially discriminatory underdevelopment may require a greater transformation than is possible at this moment, the SDGs held untapped potential to advance both development and non-discrimination.

[ODS 0 | page 20] Argument candidate:
  Despite this ominous news, the SDGs are still achievable.

[ODS 0 | page 20] Argument candidate:
  None of their objectives are beyond our reach.12 Yes, the world is off-track, but that is all the more reason to double-down on the goals, rather than surrendering to human-made shortfalls in achieving them.

[ODS 0 | page 20] Argument candidate:
  At their core, the SDGs are an investment agenda.

[ODS 0 | page 21] Argument candidate:
  To achieve the SDGs, the world must invest boldly, amply, and consistently in all eight kinds of capital.

[ODS 0 | page 21] Argument candidate:
  These investments must involve both governments and corporations.

[ODS 0 | page 21] Argument candidate:
  For example, while business capital is mainly the purview of the private sector, human capital is mainly the purview of the public sector.

[ODS 0 | page 21] Argument candidate:
  Governments too must take the lead in protecting natural capital, while civil society especially must promote social and cultural capital, including mutual understanding across cultures and nations.

[ODS 0 | page 21] Argument candidate:
  Infrastructure capital and innovation capital tend to be financed roughly equally by the public and private sectors.

[ODS 0 | page 21] Argument candidate:
  For example, governments tend to finance power transmission grids, while the private sector tends to finance power generation.

[ODS 0 | page 21] Argument candidate:
  Governments generally finance basic scientific research, while businesses focus on applied R&D.

[ODS 0 | page 21] Argument candidate:
  Parallel to investing in the SDGs, the world needs to stop investing in activities that threaten planetary boundaries, destroy human and natural capital, and harm social cohesion.

[ODS 0 | page 21] Argument candidate:
  Curtailing the extraction and use of fossil fuels is of paramount importance.

[ODS 0 | page 21] Argument candidate:
  To curb harmful investments, regulatory measures, including fair and sustainable taxation and the dismantling of unsustainable subsidies, need to be an integral element of the SDG investment agenda.

[ODS 0 | page 21] Argument candidate:
  In 2022, the United Nations Secretary-General appointed a High-Level Advisory Board on Effective Multilateralism, with a mandate to develop a list of concrete, actionable recommendations to improve international cooperation and advance the 2030 Agenda for Sustainable Development.

[ODS 0 | page 21] Argument candidate:
  The Board’s 2023 report lists six areas for action that are directly aligned with the SDGs and SDSN’s recommendations: rebuilding trust in multilateralism, safeguarding our planet and its people, scaling up and improving the efficacy of global finance, improving data systems and their governance, and promoting peace.

[ODS 0 | page 21] Argument candidate:
  The most important level of decision-making remains the nation-state.

[ODS 0 | page 21] Argument candidate:
  Nation-states hold the primary responsibility for achieving the SDGs.

[ODS 0 | page 21] Argument candidate:
  They are members of the United Nations and the signatories of United Nations treaties.

[ODS 0 | page 21] Argument candidate:
  They hold juridical responsibility for implementing treaty agreements and the rest of the United Nations architecture, including the United Nations Charter, the Universal Declaration of Human Rights, and the SDGs.

[ODS 0 | page 21] Argument candidate:
  National governments must ensure both the domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 21] Argument candidate:
  Crucially, national government must also work with subnational governments to implement the SDG agenda at the local level, including sustainable urban infrastructure, delivery of social services, and ensuring safe communities.

[ODS 0 | page 21] Argument candidate:
  Virtually all governments of the world have embraced the SDGs in principle.

[ODS 0 | page 21] Argument candidate:
  188 of 193 UN Member States have submitted VNRs for comment by the other nations.

[ODS 0 | page 21] Argument candidate:
  Only five countries, notably the United States, Haiti, Myanmar, South Sudan, and Yemen, have never presented VNRs.

[ODS 0 | page 21] Argument candidate:
  Four of these countries are wracked by violence and poverty.

[ODS 0 | page 21] Argument candidate:
  The case of the United States stands as a glaring exception.

[ODS 0 | page 21] Argument candidate:
  The Nordic countries and European Union have shown considerable support for the SDGs.

[ODS 0 | page 21] Argument candidate:
  So too have many developing countries in the G20.

[ODS 0 | page 22] Argument candidate:
  Failures (and some successes) of national SDG governance

[ODS 0 | page 22] Argument candidate:
  The greatest responsibility for achieving the SDGs and safeguarding the planetary boundaries lies with the G20 members.

[ODS 0 | page 22] Argument candidate:
  The United States has so far shown very little commitment to the SDGs. We call on the United States to formulate an SDG action plan and to present a VNR to the High-Level Political Forum.

[ODS 0 | page 22] Argument candidate:
  The European Union – the world’s second-largest economy and its major lignite producer – has produced the European Green Deal (EGD), which is exemplary in many regards.

[ODS 0 | page 22] Argument candidate:
  In July 2023, the EU is set to present its first Union-wide voluntary review at the United Nations. This presents a good opportunity for the EU to send a strong message to the international community, and to demonstrate its commitment to and leadership on the SDGs.

[ODS 0 | page 23] Argument candidate:
  12th Five-Year Plan referred to the 2030 Agenda mainly in the context of international cooperation.

[ODS 0 | page 23] Argument candidate:
  China has reiterated its support for the SDGs, such as in greening its Belt and Road Initiative and launching the Global Development Initiative as a worldwide effort.

[ODS 0 | page 23] Argument candidate:
  A key measure for China will be the explicit integration of the SDGs’ domestic and international implementation into the 15th five-year plan (2026–2030).

[ODS 0 | page 23] Argument candidate:
  Some other G20 countries have shown weak commitments to the SDGs in recent years.

[ODS 0 | page 23] Argument candidate:
  Many of the poor performers, such as Brazil, recently elected new governments that have staked out a far more ambitious position vis-à-vis the SDGs.

[ODS 0 | page 23] Argument candidate:
  We urge all G20 governments to show the leadership required of them.

[ODS 0 | page 23] Argument candidate:
  Most of the low-income and lower-middle income countries, home to more than half of humanity, face major challenges in achieving most of the SDGs by 2030.

[ODS 0 | page 23] Argument candidate:
  Many of them lack an adequately high SDG commitment, and almost all lack access to the necessary financial means to implement the SDGs.

[ODS 0 | page 23] Argument candidate:
  At the midpoint of the 2030 Agenda, all countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national strategies, using the principles of the 2030 Agenda (transformative, integrated, inclusive, leaving no one behind) as a yardstick.

[ODS 0 | page 23] Argument candidate:

,prefix,model,ods,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,deepseek-r1-70b,0,53,374,142,0,232
1,GLOBAL SGD2023,deepseek-r1-70b,1,53,57,30,0,27
2,GLOBAL SGD2023,deepseek-r1-70b,2,53,20,13,0,7
3,GLOBAL SGD2023,deepseek-r1-70b,3,53,36,24,0,12
4,GLOBAL SGD2023,deepseek-r1-70b,4,53,41,27,1,13
5,GLOBAL SGD2023,deepseek-r1-70b,5,53,7,5,0,2
6,GLOBAL SGD2023,deepseek-r1-70b,6,53,8,7,0,1
7,GLOBAL SGD2023,deepseek-r1-70b,7,53,23,12,1,10
8,GLOBAL SGD2023,deepseek-r1-70b,8,53,74,31,1,42
9,GLOBAL SGD2023,deepseek-r1-70b,9,53,67,23,0,44
10,GLOBAL SGD2023,deepseek-r1-70b,10,53,40,21,0,19
11,GLOBAL SGD2023,deepseek-r1-70b,11,53,35,17,0,18
12,GLOBAL SGD2023,deepseek-r1-70b,12,53,27,18,0,9
13,GLOBAL SGD2023,deepseek-r1-70b,13,53,87,47,0,40
14,GLOBAL SGD2023,deepseek-r1-70b,14,53,14,10,0,4
15,GLOBAL SGD2023,deepseek-r1-70b,15,53,32,20,0,12
16,GLOBAL SGD2023,deepseek-r1-70b,16,53,68,29,0,39
17,GLOBAL SGD2023,deepseek-r1-70b,17,53,168,77,0,91

Stats overall for deepseek-r1-70b in document GLOBAL_SGD2023:

Updated overall summary:

,prefix,model,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,53,251,161,0,90
1,GLOBAL SGD2023,gemma3-4b,53,4093,706,2,3385
2,GLOBAL SGD2023,gemma3-27b,53,708,330,1,377
3,GLOBAL SGD2023,llama3.3-70b,53,817,477,4,336
4,GLOBAL SGD2023,deepseek-r1-70b,53,1178,553,3,622

## G20 2024 report

### Qwen2.5-3b

In [ ]:
prefix = 'G20_2024_'
model_name="qwen2.5-3b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')

display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

Stats by SDG for qwen2.5-3b in document GLOBAL_SGD2023_:

,prefix,model,ods,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,0,53,42,32,0,10
1,GLOBAL SGD2023,qwen2.5-3b,1,53,21,9,0,12
2,GLOBAL SGD2023,qwen2.5-3b,2,53,14,2,0,12
3,GLOBAL SGD2023,qwen2.5-3b,3,53,17,12,0,5
4,GLOBAL SGD2023,qwen2.5-3b,4,53,16,5,0,11
5,GLOBAL SGD2023,qwen2.5-3b,5,53,10,2,0,8
6,GLOBAL SGD2023,qwen2.5-3b,6,53,11,7,0,4
7,GLOBAL SGD2023,qwen2.5-3b,7,53,15,10,0,5
8,GLOBAL SGD2023,qwen2.5-3b,8,53,12,9,0,3
9,GLOBAL SGD2023,qwen2.5-3b,9,53,7,4,0,3
10,GLOBAL SGD2023,qwen2.5-3b,10,53,19,13,0,6
11,GLOBAL SGD2023,qwen2.5-3b,11,53,10,8,0,2
12,GLOBAL SGD2023,qwen2.5-3b,12,53,11,10,0,1
13,GLOBAL SGD2023,qwen2.5-3b,13,53,10,9,0,1
14,GLOBAL SGD2023,qwen2.5-3b,14,53,4,3,0,1
15,GLOBAL SGD2023,qwen2.5-3b,15,53,1,1,0,0
16,GLOBAL SGD2023,qwen2.5-3b,16,53,14,10,0,4
17,GLOBAL SGD2023,qwen2.5-3b,17,53,17,15,0,2

Stats overall for qwen2.5-3b in document GLOBAL_SGD2023_:

Updated overall summary:

,prefix,model,ods_max,pages_max,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,17,53,251,161,0,90

### Gemma3 4B

In [ ]:
prefix = 'G20_2024_'
model_name="gemma3-4b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')

display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

[ODS 0 | page 7] Argument candidate:
  At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.

[ODS 0 | page 7] Argument candidate:
  None of their objectives are beyond our reach.

[ODS 0 | page 7] Argument candidate:
  The SDGs are still achievable.

[ODS 0 | page 7] Argument candidate:
  It is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.

[ODS 0 | page 7] Argument candidate:
  To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.

[ODS 0 | page 7] Argument candidate:
  The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 7] Argument candidate:
  Greatly increase funding to national and subnational governments and private businesses, especially in LICs and LMICs, to carry out needed SDG investments.

[ODS 0 | page 7] Argument candidate:
  Revise the credit rating system and debt sustainability metrics to facilitate long-term sustainable development.

[ODS 0 | page 7] Argument candidate:
  Revise liquidity structures for LICs and LMICs, especially regarding sovereign debts, to forestall self-fulfilling banking and balance-of-payments crises

[ODS 0 | page 7] Argument candidate:
  Create ambitious, internationally-agreed upon criteria for sustainable finance that are mandatory for all public financial institutions.

[ODS 0 | page 7] Argument candidate:
  Align private business investment flows with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 7] Argument candidate:
  Reform current institutional frameworks and develop new mechanisms to improve the quality and speed of deployment of international cooperation, and monitor progress in an open and timely manner.

[ODS 0 | page 7] Argument candidate:
  All countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national SDG strategies and commit to strengthening multilateralism.

[ODS 0 | page 7] Argument candidate:
  National governments must ensure both domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation – by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 7] Argument candidate:
  Achieving the SDGs requires global cooperation guided by the United Nations Charter.

[ODS 0 | page 8] Argument candidate:
  Further investment is needed in statistical capacity and data literacy to support long-term pathways for key SDG transformations.

[ODS 0 | page 8] Argument candidate:
  At the halfway mark to 2030, there remains a great deal of work to be done to improve the data and methods underlying the SDG indicator framework.

[ODS 0 | page 8] Argument candidate:
  investing in statistical capacity, science, and data literacy are important priorities for achieving the SDGs.

[ODS 0 | page 8] Argument candidate:
  All UN Member States and UN agencies can count on the continued efforts and energies of the SDSN around the world to support all governments, businesses, and civil society in embracing and aligning with the SDGs

[ODS 0 | page 13] Argument candidate:
  UN Member States should adopt an SDG Stimulus, to close the massive financing gap faced by many developing economies.

[ODS 0 | page 13] Argument candidate:
  Increased funding from the multilateral development banks (MDBs) and public development banks (PDBs) to low- and middle-income countries, linked to investments in the SDGs;

[ODS 0 | page 13] Argument candidate:
  Enhancement of relief for countries facing debt distress;

[ODS 0 | page 13] Argument candidate:
  Expansion of liquidity by the International Monetary Fund (IMF) and major central banks;

[ODS 0 | page 13] Argument candidate:
  Empowerment and expansion of the specialized global funds;

[ODS 0 | page 13] Argument candidate:
  Expansion of private philanthropy with a focus on ultra-high-net-worth individuals.

[ODS 0 | page 13] Argument candidate:
  UN Member States must endorse a deep and overdue reform of the global financial architecture.

[ODS 0 | page 13] Argument candidate:
  Greatly increased funding for national and subnational governments and private businesses in the emerging economies, especially the low-income countries (LICs) and lower-middle-income countries (LMICs), to carry out needed SDG actions;

[ODS 0 | page 13] Argument candidate:
  Revision of the credit-rating system and debt-sustainability metrics to facilitate long-term sustainable development;

[ODS 0 | page 13] Argument candidate:
  Revision of the liquidity structures for LICs and LMICs, especially regarding sovereign debt, to forestall self-fulfilling banking and balance-of-payments crises;

[ODS 0 | page 13] Argument candidate:
  Creation of ambitious, internationally-agreed criteria for sustainable finance that are mandatory for all public financial institutions in high-income countries (HICs), middle-income countries (MICs), and LICs alike.

[ODS 0 | page 13] Argument candidate:
  Alignment of private business investment flows in all countries with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 13] Argument candidate:
  A reform of current institutional frameworks and development of new and innovative mechanisms to improve the quality and speed of deployment of international cooperation, and the monitoring of progress in an open and timely manner.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of ‘leave no one behind’.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should present, at regular intervals, their national SDG frameworks in the form of Voluntary National Reviews (VNRs).

[ODS 0 | page 14] Argument candidate:
  All UN Member States should recommit to peaceful cooperation, in the service of the SDGs and all other multilateral agreements.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should commit to accelerating SDG progress to 2030, and to setting even more ambitious SDG targets to 2050, incorporating the recent Kunming-Montreal Biodiversity Framework and the High Seas Treaty.

[ODS 0 | page 15] Argument candidate:
  national governments on all continents have fallen short in integrating the SDGs into national policies and public investments

[ODS 0 | page 15] Argument candidate:
  they are grounded in the Universal Declaration of Human Rights, which celebrates its 75th anniversary this year

[ODS 0 | page 15] Argument candidate:
  that "All human beings are born free and equal in dignity and rights … and should act towards one another in a spirit of brotherhood"

[ODS 0 | page 15] Argument candidate:
  that "it is essential to promote the development of friendly relations between nations"

[ODS 0 | page 15] Argument candidate:
  social justice and sustainable development require the full realization of the rights of all people

[ODS 0 | page 15] Argument candidate:
  includes equality of opportunities for girls and women (SDG 5)

[ODS 0 | page 15] Argument candidate:
  respect for the rights and voice of Indigenous peoples around the world

[ODS 0 | page 15] Argument candidate:
  a much larger role for young people, who will face the consequences of our (in)actions throughout the 21st century

[ODS 0 | page 15] Argument candidate:
  They are not only a public policy framework; they are an ethical imperative

[ODS 0 | page 15] Argument candidate:
  Members of the SDSN Leadership Council offer the following assessments and recommendations to the UN Member States, the United Nations Agencies, international finance institutions, business, and civil society, based on more than a decade of research, measurement, advising, and partnerships across the world

[ODS 0 | page 16] Argument candidate:
  Dire shortfalls in meeting the SDGs to reaching a disastrous 2.8°C warming by 2100.

[ODS 0 | page 16] Argument candidate:
  Current Nationally Determined Contribution (NDC) targets, if implemented, would still lead to around 2.4°C warming by 2100.

[ODS 0 | page 16] Argument candidate:
  Biodiversity targets (SDG 15 and targets agreed under the CBD) are also at grave risk.

[ODS 0 | page 16] Argument candidate:
  Global resource consumption assessments for rare earth elements are critical.

[ODS 0 | page 16] Argument candidate:
  Ocean goods and services (SDG 14 and the High Seas Treaty) are at severe risk due to full- to over-exploitation

[ODS 0 | page 17] Argument candidate:
  Providing quality education (SDG 4) for all children is perhaps the single most important key to achieving sustainable development in the long term.

[ODS 0 | page 17] Argument candidate:
  The UN General Assembly’s Transforming Education Summit held in September 2022 was a critical meeting to spur national and global efforts to transform education to give all people the skills and knowledge to end poverty, protect the environment, and build peaceful and inclusive societies.

[ODS 0 | page 17] Argument candidate:
  And yet, the truth remains that hundreds of millions of children are either out of school entirely or receiving such an under-funded and under-resourced education that they are failing to achieve basic literacy and numeracy even after several years of education.

[ODS 0 | page 18] Argument candidate:
  The latest scientific assessments indicate that six of the nine planetary boundaries have been breached.

[ODS 0 | page 18] Argument candidate:
  Scientists have identified a large number of extremely dangerous potential tipping points, with linkages and dependencies across the different planetary boundaries.

[ODS 0 | page 18] Argument candidate:
  Human-induced global warming could hit several tipping points that may in turn lead to further feedbacks (amplifications) of the warming.

[ODS 0 | page 19] Argument candidate:
  Unless the SDGs are actively pursued, geophysical tipping points combined with technological disruptions could ignite disastrous social conflicts within and between nations.

[ODS 0 | page 19] Argument candidate:
  We firmly believe that international cooperation together with the achievement of the SDGs is the best preventative to this dire and growing risk, and represent an opportunity to create positive social tipping points: for example, through equal access to high-quality education (SDG 4), and by fighting all forms of inequalities, including income and wealth inequalities (SDG 10).

[ODS 0 | page 19] Argument candidate:
  Although all governments are in principle committed to economic justice as enshrined in the Universal Declaration of Human Rights, and to the SDG tenets of ‘leave no one behind’ and ‘reach the furthest behind first’, too few are living up to these commitments, especially as powerful groups block adequate public support for weaker groups.

[ODS 0 | page 19] Argument candidate:
  The report’s recommendations include calling for more racially-disaggregated SDG indicators and for dialogue with stakeholders on how to use these indicators to better allocate resources and prioritize the inclusion of marginalized peoples.

[ODS 0 | page 20] Argument candidate:
  the SDGs are woefully underfunded at home and internationally

[ODS 0 | page 20] Argument candidate:
  None of their objectives are beyond our reach

[ODS 0 | page 20] Argument candidate:
  the world must devote an increased portion of current output to building up sustainable capital assets for the future

[ODS 0 | page 20] Argument candidate:
  the world must both shift its current investment patterns and increase the overall investment flow in order to build the future we want

[ODS 0 | page 20] Argument candidate:
  Human capital: The skills and health of a productive citizenry, supported by universal health access and coverage, quality education, shared data and knowledge, promotion of a culture of peace and non-violence, global citizenship, and the appreciation of cultural diversity

[ODS 0 | page 20] Argument candidate:
  Natural capital: The capacity and healthy functioning of ecosystems, to be protected by ending human-induced climate change, protecting biodiversity, sustainably managing freshwater resources, and eliminating toxic pollutants

[ODS 0 | page 21] Argument candidate:
  To achieve the SDGs, the world must invest boldly, amply, and consistently in all eight kinds of capital.

[ODS 0 | page 21] Argument candidate:
  Governments too must take the lead in protecting natural capital, while civil society especially must promote social and cultural capital, including mutual understanding across cultures and nations.

[ODS 0 | page 21] Argument candidate:
  Crucially, national government must also work with subnational governments to implement the SDG agenda at the local level, including sustainable urban infrastructure, delivery of social services, and ensuring safe communities.

[ODS 0 | page 21] Argument candidate:
  Virtually all governments of the world have embraced the SDGs in principle. 188 of 193 UN Member States have submitted VNRs for comment by the other nations.

[ODS 0 | page 21] Argument candidate:
  Only five countries, notably the United States, Haiti, Myanmar, South Sudan, and Yemen, have never presented VNRs.

[ODS 0 | page 22] Argument candidate:
  The greatest responsibility for achieving the SDGs and safeguarding the planetary boundaries lies with the G20 members.

[ODS 0 | page 22] Argument candidate:
  With the 2022 Inflation Reduction Act, the Biden government announced its intention to reduce carbon emissions by roughly 40 percent from 2005 levels by 2030, although there are growing concerns that outcomes will lag behind these goals, due in part to the legislation’s lack of an agreed national financing strategy other than tax credits.

[ODS 0 | page 22] Argument candidate:
  The European Union – the world’s second-largest economy and its major lignite producer – has produced the European Green Deal (EGD), which is exemplary in many regards.

[ODS 0 | page 22] Argument candidate:
  Many EU member states demonstrate a high or moderate SDG commitment.

[ODS 0 | page 22] Argument candidate:
  The EGD embraces an EU-wide set of goals, timelines to 2050, and financing strategies across major dimensions of the SDGs: energy decarbonization, climate resilience, circular economy (to cut pollution), sustainable agriculture (the ‘farm-to-fork’ strategy), digital access, and innovation.

[ODS 0 | page 22] Argument candidate:
  The European Regional Development Fund, which provides the EU cohesion funds, is also directed towards the EGD.

[ODS 0 | page 22] Argument candidate:
  The SDSN Framework in the context of international cooperation.

[ODS 0 | page 23] Argument candidate:
  China has reiterated its support for the SDGs, such as in greening its Belt and Road Initiative and launching the Global Development Initiative as a worldwide effort.

[ODS 0 | page 23] Argument candidate:
  At the midpoint of the 2030 Agenda, all countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national strategies, using the principles of the 2030 Agenda (transformative, integrated, inclusive, leaving no one behind) as a yardstick.

[ODS 0 | page 23] Argument candidate:
  Four basic failures stand out: First, implementation is largely left to the national level and on a voluntary basis, without effective multilateral enforcement mechanisms in place.

[ODS 0 | page 23] Argument candidate:
  Developed countries are not being held to account, neither for their adverse spillovers, nor for ensuring adequate flows of financing for sustainable development.

[ODS 0 | page 23] Argument candidate:
  There are no assessments or recommendations by the respective secretariats or decision-making bodies on the adequacy or further enhancement of national implementation, let alone measures of enforcement.

[ODS 0 | page 24] Argument candidate:
  Greatly increase funding to national and subnational governments and private businesses in the emerging economies, especially the LICs and LMICs, to carry out the needed investments.

[ODS 0 | page 24] Argument candidate:
  Revise liquidity structures for LICs,LMICs, and SIDS, especially regarding sovereign debts, to forestall self-fulfilling banking and balance-of-payments crises.

[ODS 0 | page 24] Argument candidate:
  Create ambitious and internationally-agreed upon criteria for sustainable finance that are mandatory for all public financial institutions in HICs, MICs, and LICs alike.

[ODS 0 | page 24] Argument candidate:
  Align private business investment flows in all countries with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 24] Argument candidate:
  Reform current institutional frameworks and develop new, innovative mechanisms to improve the quality and speed of deployment of international cooperation, and monitor progress in an open and timely manner.

[ODS 0 | page 25] Argument candidate:
  Overhauling global governance mechanisms and the global financial architecture is fundamental to unlocking needed investments for sustainable development and ending non-sustainable practices.

[ODS 0 | page 25] Argument candidate:
  The SDGs call for lasting, long-term, directed change.

[ODS 0 | page 25] Argument candidate:
  For governments to combine the objectives of economic development, social inclusion, transparency, energy decarbonization, climate adaptation, water resources and sanitation, biodiversity conservation, digital access, gender equality, circular economy, over-harvesting, universal education, is daunting.

[ODS 0 | page 26] Argument candidate:
  Long-term investment plans are essential for national success in meeting the SDGs.

[ODS 0 | page 26] Argument candidate:
  SDSN has recommended six inter-related long-term transformations: Universal quality education and innovation-based economy, Universal health access and coverage, Zero-carbon energy systems, Sustainable ecosystems, sustainable agriculture, and climate resilience, Sustainable cities, Transformation to universal digital access and services

[ODS 0 | page 26] Argument candidate:
  None can be solved by the private sector alone; indeed, governments will have to take the lead to design policy and financial frameworks within which business can profitably invest and innovate.

[ODS 0 | page 26] Argument candidate:
  The Sustainable Development Report 2023 identifies five levers to be deployed to bring about the necessary transformations: governance, economy and finance, individual and collective action, science and technology, and capacity building.

[ODS 0 | page 26] Argument candidate:
  Planning for the long term, however, illuminates the global financial architecture’s Achilles heel. While the high-income countries (HICs) and upper-middle income countries (UMICs) can and should, in principle, finance these transformations via a combination of budget outlays, public-sector borrowing, and private financing (equity and debt), this is surely not true of the low-Income countries (LICs) and the lower middle-income countries

[ODS 0 | page 27] Argument candidate:
  Increased funding from the Multilateral Development Banks (MDBs) and Public Development Banks (PDBs) to developing countries, linked to investments in the SDGs

[ODS 0 | page 27] Argument candidate:
  an additional US$500 billion per year by 2025 of SDG finance

[ODS 0 | page 27] Argument candidate:

,prefix,model,ods,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL_SGD2023_,qwen2.5-3b,0,53,42,32,0,10
1,GLOBAL_SGD2023_,qwen2.5-3b,1,53,21,9,0,12
2,GLOBAL_SGD2023_,qwen2.5-3b,2,53,14,2,0,12
3,GLOBAL_SGD2023_,qwen2.5-3b,3,53,17,12,0,5
4,GLOBAL_SGD2023_,qwen2.5-3b,4,53,16,5,0,11
5,GLOBAL_SGD2023_,qwen2.5-3b,5,53,10,2,0,8
6,GLOBAL_SGD2023_,qwen2.5-3b,6,53,11,7,0,4
7,GLOBAL_SGD2023_,qwen2.5-3b,7,53,15,10,0,5
8,GLOBAL_SGD2023_,qwen2.5-3b,8,53,12,9,0,3
9,GLOBAL_SGD2023_,qwen2.5-3b,9,53,7,4,0,3
10,GLOBAL_SGD2023_,qwen2.5-3b,10,53,19,13,0,6
11,GLOBAL_SGD2023_,qwen2.5-3b,11,53,10,8,0,2
12,GLOBAL_SGD2023_,qwen2.5-3b,12,53,11,10,0,1
13,GLOBAL_SGD2023_,qwen2.5-3b,13,53,10,9,0,1
14,GLOBAL_SGD2023_,qwen2.5-3b,14,53,4,3,0,1
15,GLOBAL_SGD2023_,qwen2.5-3b,15,53,1,1,0,0
16,GLOBAL_SGD2023_,qwen2.5-3b,16,53,14,10,0,4
17,GLOBAL_SGD2023_,qwen2.5-3b,17,53,17,15,0,2
18,GLOBAL SGD2023,gemma3-4b,0,53,304,167,1,136
19,GLOBAL SGD2023,gemma3-4b,1,53,199,48,0,151
20,GLOBAL SGD2023,gemma3-4b,2,53,248,27,0,221
21,GLOBAL SGD2023,gemma3-4b,3,53,228,36,0,192
22,GLOBAL SGD2023,gemma3-4b,4,53,229,27,1,201
23,GLOBAL SGD2023,gemma3-4b,5,53,181,23,0,158
24,GLOBAL SGD2023,gemma3-4b,6,53,221,26,0,195
25,GLOBAL SGD2023,gemma3-4b,7,53,246,26,0,220
26,GLOBAL SGD2023,gemma3-4b,8,53,252,36,0,216
27,GLOBAL SGD2023,gemma3-4b,9,53,241,37,0,204
28,GLOBAL SGD2023,gemma3-4b,10,53,229,46,0,183
29,GLOBAL SGD2023,gemma3-4b,11,53,247,19,0,228
30,GLOBAL SGD2023,gemma3-4b,12,53,239,24,0,215
31,GLOBAL SGD2023,gemma3-4b,13,53,168,36,0,132
32,GLOBAL SGD2023,gemma3-4b,14,53,221,21,0,200
33,GLOBAL SGD2023,gemma3-4b,15,53,182,19,0,163
34,GLOBAL SGD2023,gemma3-4b,16,53,220,41,0,179
35,GLOBAL SGD2023,gemma3-4b,17,53,238,47,0,191

Stats overall for gemma3-4b in document GLOBAL_SGD2023_:

Updated overall summary:

,prefix,model,ods_max,pages_max,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,17,53,251,161,0,90
1,GLOBAL_SGD2023_,qwen2.5-3b,17,53,4344,867,2,3475

### Gemma3 27B

In [ ]:
prefix = 'G20_2024_'
model_name="gemma3-27b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')
display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

[ODS 0 | page 7] Argument candidate:
  At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.

[ODS 0 | page 7] Argument candidate:
  Despite this alarming development, the SDGs are still achievable.

[ODS 0 | page 7] Argument candidate:
  None of their objectives are beyond our reach.

[ODS 0 | page 7] Argument candidate:
  The world is off track, but that is all the more reason to double down on the SDGs.

[ODS 0 | page 7] Argument candidate:
  At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.

[ODS 0 | page 7] Argument candidate:
  To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.

[ODS 0 | page 7] Argument candidate:
  The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 7] Argument candidate:
  All countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national SDG strategies and commit to strengthening multilateralism.

[ODS 0 | page 7] Argument candidate:
  National governments must ensure both domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation – by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 7] Argument candidate:
  Achieving the SDGs requires global cooperation guided by the United Nations Charter.

[ODS 0 | page 7] Argument candidate:
  SDG transformations.

[ODS 0 | page 8] Argument candidate:
  Further investment is needed in statistical capacity and data literacy to support long-term pathways for key SDG transformations.

[ODS 0 | page 8] Argument candidate:
  At the halfway mark to 2030, there remains a great deal of work to be done to improve the data and methods underlying the SDG indicator framework.

[ODS 0 | page 8] Argument candidate:
  The SDSN was created in 2012, soon after the Rio+20 Summit, to mobilize the world’s universities, think tanks, and national laboratories on behalf of the SDGs.

[ODS 0 | page 8] Argument candidate:
  Via science-based pathways and analytics, the SDSN supports discussions on SDG implementation at the global, regional, and national levels.

[ODS 0 | page 8] Argument candidate:
  All UN Member States and UN agencies can count on the continued efforts and energies of the SDSN around the world to support all governments, businesses, and civil society in embracing and aligning with the SDGs on sustainable development.

[ODS 0 | page 13] Argument candidate:
  At the midpoint of the 2030 Agenda, the SDGs are far off track.

[ODS 0 | page 13] Argument candidate:
  SDSN offers the following recommendations to accelerate progress over the remaining seven years to 2030, and to set even more ambitious targets to be achieved by 2050 under the SDG framework.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of ‘leave no one behind’.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should present, at regular intervals, their national SDG frameworks in the form of Voluntary National Reviews (VNRs).

[ODS 0 | page 14] Argument candidate:
  All UN Member States should recommit to peaceful cooperation, in the service of the SDGs and all other multilateral agreements.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should commit to accelerating SDG progress to 2030, and to setting even more ambitious SDG targets to 2050, incorporating the recent Kunming-Montreal Biodiversity Framework and the High Seas Treaty.

[ODS 0 | page 15] Argument candidate:
  The SDGs are facing strong headwinds.

[ODS 0 | page 15] Argument candidate:
  Despite significant efforts in some places, national governments on all continents have fallen short in integrating the SDGs into national policies and public investments.

[ODS 0 | page 15] Argument candidate:
  We emphasize that achieving the SDGs rests on five pillars of good governance:

[ODS 0 | page 15] Argument candidate:
  The SDGs are not only a public policy framework; they are an ethical imperative.

[ODS 0 | page 15] Argument candidate:
  The SDGs are seriously off track (Figure 1.1).

[ODS 0 | page 15] Argument candidate:
  According to the annual SDG Index, global achievement of the SDGs rose only slightly, from 64 percent in 2015 to 66 percent in 2019 – far too slowly to meet the goals by 2030, and with highly uneven progress within and between countries.

[ODS 0 | page 15] Argument candidate:
  At current trends, based on simple projections, there is a risk that the gap in SDG outcomes between HICs and LICs will be wider in 2030 (29 points) than it was in 2015 (28 points).

[ODS 0 | page 15] Argument candidate:
  The multiple geopolitical crises in the world today will no doubt place further obstacles on the path to 2030.

[ODS 0 | page 15] Argument candidate:
  If we look at each of the 17 individual SDGs, not a single SDG is projected to be met at the global level.

[ODS 0 | page 17] Argument candidate:
  The World Bank. 2017. Atlas of Sustainable Development Goals.

[ODS 0 | page 17] Argument candidate:
  Providing quality education (SDG 4) for all children is perhaps the single most important key to achieving sustainable development in the long term.

[ODS 0 | page 19] Argument candidate:
  Unless the SDGs are actively pursued, geophysical tipping points combined with technological disruptions could ignite disastrous social conflicts within and between nations.

[ODS 0 | page 19] Argument candidate:
  We firmly believe that international cooperation together with the achievement of the SDGs is the best preventative to this dire and growing risk, and represent an opportunity to create positive social tipping points.

[ODS 0 | page 19] Argument candidate:
  Although all governments are in principle committed to economic justice as enshrined in the Universal Declaration of Human Rights, and to the SDG tenets of ‘leave no one behind’ and ‘reach the furthest behind first’, too few are living up to these commitments.

[ODS 0 | page 19] Argument candidate:
  The report’s recommendations include calling for more racially-disaggregated SDG indicators and for dialogue with stakeholders on how to use these indicators to better allocate resources and prioritize the inclusion of marginalized peoples.

[ODS 0 | page 20] Argument candidate:
  Despite this ominous news, the SDGs are still achievable.

[ODS 0 | page 20] Argument candidate:
  None of their objectives are beyond our reach.

[ODS 0 | page 20] Argument candidate:
  Yes, the world is off-track, but that is all the more reason to double-down on the goals, rather than surrendering to human-made shortfalls in achieving them.

[ODS 0 | page 20] Argument candidate:
  At their core, the SDGs are an investment agenda.

[ODS 0 | page 20] Argument candidate:
  In the most basic terms, the world must devote an increased portion of current output to building up sustainable capital assets for the future, and must deploy such assets effectively.

[ODS 0 | page 21] Argument candidate:
  To achieve the SDGs, the world must invest boldly, amply, and consistently in all eight kinds of capital.

[ODS 0 | page 21] Argument candidate:
  In 2022, the United Nations Secretary-General appointed a High-Level Advisory Board on Effective Multilateralism, with a mandate to develop a list of concrete, actionable recommendations to improve international cooperation and advance the 2030 Agenda for Sustainable Development.

[ODS 0 | page 21] Argument candidate:
  Nation-states hold the primary responsibility for achieving the SDGs.

[ODS 0 | page 21] Argument candidate:
  They hold juridical responsibility for implementing treaty agreements and the rest of the United Nations architecture, including the United Nations Charter, the Universal Declaration of Human Rights, and the SDGs.

[ODS 0 | page 21] Argument candidate:
  Virtually all governments of the world have embraced the SDGs in principle.

[ODS 0 | page 21] Argument candidate:
  188 of 193 UN Member States have submitted VNRs for comment by the other nations.

[ODS 0 | page 22] Argument candidate:
  We call on the United States to formulate an SDG action plan and to present a VNR to the High-Level Political Forum.

[ODS 0 | page 22] Argument candidate:
  In July 2023, the EU is set to present its first Union-wide voluntary review at the United Nations.

[ODS 0 | page 22] Argument candidate:
  China has already presented two VNRs to the HLPF (2016 and 2021).

[ODS 0 | page 23] Argument candidate:
  Recently, China has reiterated its support for the SDGs, such as in greening its Belt and Road Initiative and launching the Global Development Initiative as a worldwide effort.

[ODS 0 | page 23] Argument candidate:
  A key measure for China will be the explicit integration of the SDGs’ domestic and international implementation into the 15th five-year plan (2026–2030).

[ODS 0 | page 23] Argument candidate:
  At the midpoint of the 2030 Agenda, all countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national strategies, using the principles of the 2030 Agenda (transformative, integrated, inclusive, leaving no one behind) as a yardstick.

[ODS 0 | page 23] Argument candidate:
  Achieving the SDGs will require a transformative global approach.

[ODS 0 | page 23] Argument candidate:
  Both the 2030 Agenda and the Paris Climate Agreement established mechanisms to encourage and monitor their implementation by nation-states.

[ODS 0 | page 23] Argument candidate:
  However, experience so far with VNRs and Nationally Determined Contributions (NDCs), respectively, demonstrate that these mechanisms – despite some progress – have not delivered the effort necessary to achieve global goals.

[ODS 0 | page 24] Argument candidate:
  International cooperation is trapped by bureaucratic institutional frameworks that reduce the speed, efficacy, and efficiency of funding to meet the SDGs, and that fail to provide the framework for large-scale SDG financing.

[ODS 0 | page 24] Argument candidate:
  Align private business investment flows in all countries with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 26] Argument candidate:
  Long-term investment plans are essential for national success in meeting the SDGs.

[ODS 0 | page 26] Argument candidate:
  SDSN has recommended six inter-related long-term transformations:20

[ODS 0 | page 26] Argument candidate:
  1. Universal quality education and innovation-based economy

[ODS 0 | page 26] Argument candidate:
  2. Universal health access and coverage

[ODS 0 | page 26] Argument candidate:
  3. Zero-carbon energy systems

[ODS 0 | page 26] Argument candidate:
  4. Sustainable ecosystems, sustainable agriculture, and climate resilience

[ODS 0 | page 26] Argument candidate:
  5. Sustainable cities

[ODS 0 | page 26] Argument candidate:
  6. Transformation to universal digital access and services

[ODS 0 | page 27] Argument candidate:
  In his opening address to the UN General Assembly on September 20, 2022, UN Secretary-General António Guterres called on the G20 to launch an “SDG Stimulus” to offset the deteriorating market conditions faced by developing countries and to accelerate progress towards the SDGs and the Paris Climate Agreement.

[ODS 0 | page 27] Argument candidate:
  The SDG Stimulus plan recommended by the High-Level Working Group and introduced by SG Guterres last February25 has five main components:

[ODS 0 | page 27] Argument candidate:
  Increased funding from the Multilateral Development Banks (MDBs) and Public Development Banks (PDBs) to developing countries, linked to investments in the SDGs, a need echoed in the 2023 report of the High-Level Advisory Board on Effective Multilateralism26

[ODS 0 | page 28] Argument candidate:
  All United Nations agencies should put the SDGs at the centerpiece of their strategies, programs, and reporting.

[ODS 0 | page 28] Argument candidate:
  The World Bank and the other MDBs should put the SDGs at the center of their financing strategies, performance reviews, and reporting.

[ODS 0 | page 28] Argument candidate:
  The IMF should build its national reviews (Article IV), debt sustainability framework (DSF), and country programming around the public policies and financing needed for national success in achieving the SDGs.

[ODS 0 | page 28] Argument candidate:
  The G20 should organize its financial cooperation, reporting, and metrics around the reform of the GFA, as needed to achieve the SDGs.

[ODS 0 | page 28] Argument candidate:
  All UN Member States should present VNRs at least once every three years.

[ODS 0 | page 28] Argument candidate:
  It is especially urgent that the five countries that have not yet presented VNRs should do so no later than 2024.

[ODS 0 | page 28] Argument candidate:
  United Nations agencies, multilateral organizations, and Member States need to increase investment in, and coordination of, national and international data and statistical systems and scientific capacity to assess SDG progress and support sustainable development decision making and investment, including disaggregated data by region, social stratification, and other criteria as helpful.

[ODS 0 | page 29] Argument candidate:
  SDSN is closely following and supporting the EU’s endeavors to achieve the SDGs, inter alia by the EU’s European Green Deal.

[ODS 0 | page 29] Argument candidate:
  SDSN is supporting the African Development Bank to develop a strategic plan to accelerate Africa’s sustainable development, with the aim of the African Union achieving high-income status and sustainable development by 2063, the 100th anniversary of the Organization of African Unity.

[ODS 0 | page 29] Argument candidate:
  SDSN is supporting the African Development Bank to develop a strategic plan to accelerate Africa’s sustainable development

[ODS 0 | page 29] Argument candidate:
  SDSN recognizes this gap in the practical means of implementation of city governments, and is currently working with the major urban think tanks and global urban networks (including the C40 and ICLEI) to address the challenge of sub-national financing of the SDGs.

[ODS 0 | page 30] Argument candidate:
  SDG 16 recognizes the vital role of peaceful and inclusive societies, and SDG 17 underscores the need for global outreach and cooperation to achieve the Goals.

[ODS 0 | page 30] Argument candidate:
  The SDSN was created in 2012, soon after the Rio+20 Summit which mobilized the world’s universities, think tanks, and national laboratories on behalf of the SDGs.

[ODS 0 | page 30] Argument candidate:
  We aim to ensure that institutions of higher learning and public policy research centres in all 193 UN Member States are actively part of the SDSN.

[ODS 0 | page 30] Argument candidate:
  SDSN is working closely with the UNESCO SDG 4 High-Level Steering Committee on these two major issues, via Mission 4.7 through an SDG Academy Partnership with the Open Education Resources Recommendation team at UNESCO.

[ODS 0 | page 31] Argument candidate:
  They are the work of the 21st century.

[ODS 0 | page 31] Argument candidate:
  These are signal achievements of humanity, to have come together across all nations to adopt a common set of challenges.

[ODS 0 | page 31] Argument candidate:
  At the mid-point of the SDG agenda, we are far off target.

[ODS 0 | page 32] Argument candidate:
  First, that UN Member States, at the 2023 SDG Summit and the 2024 Summit of the Future, recommit boldly, strongly, and proactively to the SDGs, accelerate progress to 2030, and adopt even more ambitious SDG targets and objectives to mid-century, also incorporating recent international agreements on oceans and biodiversity.

[ODS 0 | page 32] Argument candidate:
  Second, UN Member States, starting with the G20 meeting this September in India, should adopt an SDG Stimulus to accelerate progress towards the SDGs by 2030 and enhance global governance for enforcing the implementation of the SDGs by all countries.

[ODS 0 | page 34] Argument candidate:
  The SDG Index and Dashboards track the annual progress of all 193 UN Member States towards the SDGs.

[ODS 0 | page 34] Argument candidate:
  At the midpoint of the 2030 Agenda, however, the SDGs are far off track.

[ODS 0 | page 34] Argument candidate:
  The SDG Index is an assessment of each country’s overall performance on the 17 SDGs, giving equal weight to each Goal.

[ODS 0 | page 34] Argument candidate:
  The dashboard and trend arrows help identify priorities for further actions and indicate whether countries are on track or off track to achieve the goals and targets by 2030, based on latest trend data.

[ODS 0 | page 38] Argument candidate:
  As detailed in the Europe Sustainable Development Report 2022, trends on several leave-no-one-behind indicators are not heading in the right direction in many EU member states (Lafortune et al. 2022).

[ODS 0 | page 43] Argument candidate:
  The 2030 Agenda and the SDGs recognize the importance of international spillovers in several crucial ways.

[ODS 0 | page 43] Argument candidate:
  SDG 17 (Partnerships for the Goals) calls for ‘policy coherence’ for sustainable development.

[ODS 0 | page 43] Argument candidate:
  SDG 17 (Partnerships for the Goals) calls on all countries to enhance policy coherence for sustainable development (PCSD).

[ODS 0 | page 58] Argument candidate:
  There was no expectation in 2015, when the SDGs and Agenda 2030 were adopted, that all goals and targets would be achieved at their midpoint.

[ODS 0 | page 58] Argument candidate:
  By 2023, one would expect that most countries would have implemented ambitious policy, regulatory and investment frameworks compatible with achieving major SDG transformations.

[ODS 0 | page 58] Argument candidate:
  It could also be expected that all countries would have at least once documented their progress and their plans for achieving the SDGs in a Voluntary National Review (VNRs) presented at the United Nations.

[ODS 0 | page 58] Argument candidate:
  Nation-states continue to hold the primary responsibility for achieving the SDGs.

[ODS 0 | page 59] Argument candidate:
  By July 2023, all UN Member States will have presented a VNR except for Haiti, Myanmar, South Sudan, the United States and Yemen.

[ODS 0 | page 59] Argument candidate:
  Official high-level speeches and the preparation of VNRs (as the official government-led process to report on SDG progress, gaps, and policy efforts) provide relevant proxies to gauge political commitment to the SDGs.

[ODS 0 | page 62] Argument candidate:
  since 2016, 188 UN Member States have prepared VNRs (see Figure 3.2).

[ODS 0 | page 62] Argument candidate:
  At the midpoint of the 2030 Agenda, only five countries have never submitted a VNR, among them the United States (HLPF, 2023).

[ODS 0 | page 62] Argument candidate:
  Some countries take a mainstreaming approach, where SDGs are implemented by each government ministry within the scope of its mandate (instead of via an overarching national action plan).

[ODS 0 | page 62] Argument candidate:
  For many, this takes the form of a national sustainability strategy explicitly linked to the 2030 Agenda goals and targets.

[ODS 0 | page 62] Argument candidate:

,prefix,model,ods,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,gemma3-27b,0,53,160,53,0,107
1,GLOBAL SGD2023,gemma3-27b,1,53,40,21,0,19
2,GLOBAL SGD2023,gemma3-27b,2,53,32,12,0,20
3,GLOBAL SGD2023,gemma3-27b,3,53,30,16,0,14
4,GLOBAL SGD2023,gemma3-27b,4,53,33,16,0,17
5,GLOBAL SGD2023,gemma3-27b,5,53,10,6,0,4
6,GLOBAL SGD2023,gemma3-27b,6,53,19,7,0,12
7,GLOBAL SGD2023,gemma3-27b,7,53,16,7,0,9
8,GLOBAL SGD2023,gemma3-27b,8,53,23,14,0,9
9,GLOBAL SGD2023,gemma3-27b,9,53,34,10,0,24
10,GLOBAL SGD2023,gemma3-27b,10,53,23,15,0,8
11,GLOBAL SGD2023,gemma3-27b,11,53,23,11,0,12
12,GLOBAL SGD2023,gemma3-27b,12,53,37,18,0,19
13,GLOBAL SGD2023,gemma3-27b,13,53,58,31,0,27
14,GLOBAL SGD2023,gemma3-27b,14,53,15,7,0,8
15,GLOBAL SGD2023,gemma3-27b,15,53,27,19,1,7
16,GLOBAL SGD2023,gemma3-27b,16,53,47,27,0,20
17,GLOBAL SGD2023,gemma3-27b,17,53,81,40,0,41

Stats overall for gemma3-27b in document GLOBAL_SGD2023:

TypeError: save_overall_summary() missing 1 required positional argument: 'model_name'

### Llama 3.3 70B

In [ ]:
prefix = 'G20_2024_'
model_name="llama3.3-70b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')
display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
save_overall_summary(res, path_output_stats, model_name)

[ODS 0 | page 7] Argument candidate:
  At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.

[ODS 0 | page 7] Argument candidate:
  Since the outbreak of the pandemic in 2020 and other simultaneous crises, SDG progress has stalled globally.

[ODS 0 | page 7] Argument candidate:
  The world is off track, but that is all the more reason to double down on the SDGs.

[ODS 0 | page 7] Argument candidate:
  At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.

[ODS 0 | page 7] Argument candidate:
  To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.

[ODS 0 | page 7] Argument candidate:
  The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 7] Argument candidate:
  All countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national SDG strategies and commit to strengthening multilateralism.

[ODS 0 | page 7] Argument candidate:
  National governments must ensure both domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation – by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 7] Argument candidate:
  Achieving the SDGs requires global cooperation guided by the United Nations Charter.

[ODS 0 | page 7] Argument candidate:
  We introduce in the report this year a pilot index of countries commitment to and support of multilateralism under the UN Charter. SDG transformations.

[ODS 0 | page 8] Argument candidate:
  Further investment is needed in statistical capacity and data literacy to support long-term pathways for key SDG transformations.

[ODS 0 | page 8] Argument candidate:
  At the halfway mark to 2030, there remains a great deal of work to be done to improve the data and methods underlying the SDG indicator framework.

[ODS 0 | page 8] Argument candidate:
  According to major international studies, few teenagers can differentiate between a fact and an opinion. As underlined during the United Nations World Data Forum 2023 and in the 27 April Hangzhou Declaration, investing in statistical capacity, science, and data literacy are important priorities for achieving the SDGs.

[ODS 0 | page 8] Argument candidate:
  The SDSN and its global network will double-down on efforts to implement the SDGs by 2030 and beyond.

[ODS 0 | page 8] Argument candidate:
  Via science-based pathways and analytics, the SDSN supports discussions on SDG implementation at the global, regional, and national levels.

[ODS 0 | page 8] Argument candidate:
  All UN Member States and UN agencies can count on the continued efforts and energies of the SDSN around the world to support all governments, businesses, and civil society in embracing and aligning with the SDGs on sustainable development.

[ODS 0 | page 13] Argument candidate:
  The grim reality is that at the midpoint of the 2030 Agenda, the SDGs are far off track.

[ODS 0 | page 13] Argument candidate:
  United Nations Secretary-General António Guterres has urged world leaders to come together at the 2023 SDG Summit in September to deliver a “Rescue Plan for People and Planet”

[ODS 0 | page 13] Argument candidate:
  As the world’s nations prepare to meet in September to review the progress the world has made so far towards achieving the SDGs, at the midpoint of the 2030 Agenda, SDSN emphasizes six areas for immediate action.

[ODS 0 | page 13] Argument candidate:
  Most urgently, UN Member States should adopt an SDG Stimulus, to close the massive financing gap faced by many developing economies.

[ODS 0 | page 13] Argument candidate:
  UN Member States must endorse a deep and overdue reform of the global financial architecture.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of ‘leave no one behind’.

[ODS 0 | page 14] Argument candidate:
  SDSN recommends that national pathways should include six key transformations:

[ODS 0 | page 14] Argument candidate:
  All UN Member States should present, at regular intervals, their national SDG frameworks in the form of Voluntary National Reviews (VNRs).

[ODS 0 | page 14] Argument candidate:
  To date, 188 of the 193 UN Member States have already presented VNRs.

[ODS 0 | page 14] Argument candidate:
  The report that follows offers SDSN’s update on the state of the SDGs at their mid-point, highlighting the growing dangers of adverse environmental, social, and economic “tipping points” and identifying key ways that the global community can and should accelerate SDG progress.

[ODS 0 | page 14] Argument candidate:
  UN Member States should commit to accelerating SDG progress to 2030, and to setting even more ambitious SDG targets to 2050, incorporating the recent Kunming-Montreal Biodiversity Framework and the High Seas Treaty.

[ODS 0 | page 15] Argument candidate:
  The SDGs are facing strong headwinds. Despite significant efforts in some places, national governments on all continents have fallen short in integrating the SDGs into national policies and public investments.

[ODS 0 | page 15] Argument candidate:
  We emphasize that achieving the SDGs rests on five pillars of good governance:

[ODS 0 | page 15] Argument candidate:
  The SDGs are not only a public policy framework; they are an ethical imperative.

[ODS 0 | page 15] Argument candidate:
  Dire shortfalls in meeting the SDGs The SDGs are seriously off track (Figure 1.1).

[ODS 0 | page 15] Argument candidate:
  According to the annual SDG Index, global achievement of the SDGs rose only slightly, from 64 percent in 2015 to 66 percent in 2019 – far too slowly to meet the goals by 2030, and with highly uneven progress within and between countries.

[ODS 0 | page 15] Argument candidate:
  The world is also seriously off track to meet the Paris agreement climate targets and SDG 13 (Figure 1.3).

[ODS 0 | page 16] Argument candidate:
  Dire shortfalls in meeting the SDGs

[ODS 0 | page 16] Argument candidate:
  SDG Index world average: pre-pandemic trend and trend needed to achieve the SDGs by 2030

[ODS 0 | page 16] Argument candidate:
  Trend needed to achieve the SDGs

[ODS 0 | page 17] Argument candidate:
  6 of nearly 90% of global fish stocks.6 The crises facing our oceans are unabated, multidimensional, and complex.

[ODS 0 | page 17] Argument candidate:
  The 2021 UN Food Systems Summit raised many urgent concerns around improving the sustainability, affordability, and quality of food across the world (SDG 2).

[ODS 0 | page 17] Argument candidate:
  Providing quality education (SDG 4) for all children is perhaps the single most important key to achieving sustainable development in the long term.

[ODS 0 | page 17] Argument candidate:
  Figure 1.2 Observed and projected gaps in SDG Index score between HICs and LICs (in percentage points)

[ODS 0 | page 17] Argument candidate:
  Part 1. How to Achieve the SDGs: The SDSN Framework planetary boundaries that regulate the Earth system.

[ODS 0 | page 19] Argument candidate:
  Unless the SDGs are actively pursued, geophysical tipping points combined with technological disruptions could ignite disastrous social conflicts within and between nations.

[ODS 0 | page 19] Argument candidate:
  We firmly believe that international cooperation together with the achievement of the SDGs is the best preventative to this dire and growing risk, and represent an opportunity to create positive social tipping points: for example, through equal access to high-quality education (SDG 4), and by fighting all forms of inequalities, including income and wealth inequalities (SDG 10).

[ODS 0 | page 19] Argument candidate:
  Although all governments are in principle committed to economic justice as enshrined in the Universal Declaration of Human Rights, and to the SDG tenets of ‘leave no one behind’ and ‘reach the furthest behind first’, too few are living up to these commitments, especially as powerful groups block adequate public support for weaker groups.

[ODS 0 | page 19] Argument candidate:
  In her 2022 report on the SDGs, E. Tendayi Achiume – UN Special Rapporteur on contemporary forms of racism, racial discrimination, xenophobia and related intolerance – noted that racism and racial discrimination are key barriers to sustainable development, and called attention to the failure of some States to collect disaggregated data on race, ethnicity, indigeneity, and migration status in the context of the 2030 Agenda.

[ODS 0 | page 19] Argument candidate:
  The report’s recommendations include calling for more racially-disaggregated SDG indicators and for dialogue with stakeholders on how to use these indicators to better allocate resources and prioritize the inclusion of marginalized peoples.

[ODS 0 | page 20] Argument candidate:
  Despite this ominous news, the SDGs are still achievable.

[ODS 0 | page 20] Argument candidate:
  Investing in the SDGs

[ODS 0 | page 20] Argument candidate:
  The world must devote an increased portion of current output to building up sustainable capital assets for the future, and must deploy such assets effectively.

[ODS 0 | page 20] Argument candidate:
  At their core, the SDGs are an investment agenda.

[ODS 0 | page 20] Argument candidate:
  Yes, the world is off-track, but that is all the more reason to double-down on the goals, rather than surrendering to human-made shortfalls in achieving them.

[ODS 0 | page 20] Argument candidate:
  The SDGs are woefully underfunded at home and internationally.

[ODS 0 | page 21] Argument candidate:
  To achieve the SDGs, the world must invest boldly, amply, and consistently in all eight kinds of capital.

[ODS 0 | page 21] Argument candidate:
  Parallel to investing in the SDGs, the world needs to stop investing in activities that threaten planetary boundaries, destroy human and natural capital, and harm social cohesion.

[ODS 0 | page 21] Argument candidate:
  In 2022, the United Nations Secretary-General appointed a High-Level Advisory Board on Effective Multilateralism, with a mandate to develop a list of concrete, actionable recommendations to improve international cooperation and advance the 2030 Agenda for Sustainable Development.

[ODS 0 | page 21] Argument candidate:
  National governments must ensure both the domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 21] Argument candidate:
  Virtually all governments of the world have embraced the SDGs in principle. 188 of 193 UN Member States have submitted VNRs for comment by the other nations.

[ODS 0 | page 21] Argument candidate:
  The Nordic countries and European Union have shown considerable support for the SDGs. So too have many developing countries in the G20.

[ODS 0 | page 22] Argument candidate:
  The greatest responsibility for achieving the SDGs and safeguarding the planetary boundaries lies with the G20 members.

[ODS 0 | page 22] Argument candidate:
  The United States, as the world’s biggest economy in terms of GDP at market prices and its biggest oil and gas producer, has a responsibility both to itself and to the rest of the world to immediately embark on an ambitious transformation towards the SDGs, as well as towards other global climate and biodiversity goals.

[ODS 0 | page 22] Argument candidate:
  We call on the United States to formulate an SDG action plan and to present a VNR to the High-Level Political Forum.

[ODS 0 | page 22] Argument candidate:
  The European Union – the world’s second-largest economy and its major lignite producer – has produced the European Green Deal (EGD), which is exemplary in many regards.

[ODS 0 | page 22] Argument candidate:
  However, the EGD and EU policies at large lack a comprehensive alignment to the SDGs, politically agreed targets for many SDG indicators, and clarity on how to achieve the SDGs.

[ODS 0 | page 22] Argument candidate:
  The EU has also highlighted the strategic role of the private sector in achieving the SDGs, by implementing a new directive asking companies to publish sustainability reports and, in particular in the food sector, by promoting the “Code of Conduct on Responsible Food Business and Marketing Practices”

[ODS 0 | page 22] Argument candidate:
  China intends to implement the SDGs by integrating them into its medium and long-term national development strategies, such as its five-year plans.

[ODS 0 | page 22] Argument candidate:
  China has already presented two VNRs to the HLPF (2016 and 2021).

[ODS 0 | page 22] Argument candidate:
  In July 2023, the EU is set to present its first Union-wide voluntary review at the United Nations.

[ODS 0 | page 22] Argument candidate:
  This presents a good opportunity for the EU to send a strong message to the international community, and to demonstrate its commitment to and leadership on the SDGs.

[ODS 0 | page 23] Argument candidate:
  A key measure for China will be the explicit integration of the SDGs’ domestic and international implementation into the 15th five-year plan (2026–2030).

[ODS 0 | page 23] Argument candidate:
  We urge all G20 governments to show the leadership required of them.

[ODS 0 | page 23] Argument candidate:
  At the midpoint of the 2030 Agenda, all countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national strategies, using the principles of the 2030 Agenda (transformative, integrated, inclusive, leaving no one behind) as a yardstick.

[ODS 0 | page 23] Argument candidate:
  Achieving the SDGs will require a transformative global approach.

[ODS 0 | page 23] Argument candidate:
  Both the 2030 Agenda and the Paris Climate Agreement established mechanisms to encourage and monitor their implementation by nation-states. However, experience so far with VNRs and Nationally Determined Contributions (NDCs), respectively, demonstrate that these mechanisms – despite some progress – have not delivered the effort necessary to achieve global goals.

[ODS 0 | page 23] Argument candidate:
  Even the progress on consistent national reporting on SDG indicators is inadequate.

[ODS 0 | page 24] Argument candidate:
  It is widely recognized that the world needs to overhaul the GFA. Such an overhaul should address the failures above and aim to achieve six objectives:

[ODS 0 | page 24] Argument candidate:
  International cooperation is trapped by bureaucratic institutional frameworks that reduce the speed, efficacy, and efficiency of funding to meet the SDGs, and that fail to provide the framework for large-scale SDG financing.

[ODS 0 | page 24] Argument candidate:
  Align private business investment flows in all countries with the SDGs, through improved national planning, regulation, reporting, and oversight.

[ODS 0 | page 24] Argument candidate:
  Reform current institutional frameworks and develop new, innovative mechanisms to improve the quality and speed of deployment of international cooperation, and monitor progress in an open and timely manner.

[ODS 0 | page 25] Argument candidate:
  Overhauling global governance mechanisms and the global financial architecture is fundamental to unlocking needed investments for sustainable development and ending non-sustainable practices.

[ODS 0 | page 25] Argument candidate:
  The SDG policy agenda is complex. The SDGs call for lasting, long-term, directed change.

[ODS 0 | page 26] Argument candidate:
  SDSN’s strategy to achieve the SDGs

[ODS 0 | page 26] Argument candidate:
  Long-term investment plans are essential for national success in meeting the SDGs.

[ODS 0 | page 26] Argument candidate:
  SDSN has recommended six inter-related long-term transformations:

[ODS 0 | page 26] Argument candidate:
  Each of these challenges will require large-scale public and private investments to mid-century, technological transformation, and a sound financing strategy.

[ODS 0 | page 26] Argument candidate:
  The Sustainable Development Report 2023 identifies five levers to be deployed to bring about the necessary transformations: governance, economy and finance, individual and collective action, science and technology, and capacity building.

[ODS 0 | page 26] Argument candidate:
  Planning for the long term, however, illuminates the global financial architecture’s Achilles heel.

[ODS 0 | page 26] Argument candidate:
  SDSN has joined the Group on Earth Observations (GEO)19 as a Participating Organization, supporting the efforts of this voluntary intergovernmental community to focus national, international, and private sector investments in Earth observations on urgent SDG needs.

[ODS 0 | page 27] Argument candidate:
  To make sure that existing financial resources and the required additional resources are used for sustainable investments, international finance institutions must fully incorporate achieving the SDGs and safeguarding the planetary boundaries into their core mandates, and monitor these regarding all countries, poorer and richer alike.

[ODS 0 | page 27] Argument candidate:
  Global infrastructure programs like China’s Belt and Road, the EU’s Global Gateway, or the United States’ Build Back Better World initiatives must be much better aligned with the SDGs and coordinated with each other.

[ODS 0 | page 27] Argument candidate:
  In his opening address to the UN General Assembly on September 20, 2022, UN Secretary-General António Guterres called on the G20 to launch an “SDG Stimulus” to offset the deteriorating market conditions faced by developing countries and to accelerate progress towards the SDGs and the Paris Climate Agreement.

[ODS 0 | page 27] Argument candidate:
  SDSN provided the Secretariat of a High-Level Informal Working Group for the SDG Stimulus (HLIWG), that made the case for an SDG Stimulus of an additional US$500 billion per year by 2025 of SDG finance.

[ODS 0 | page 27] Argument candidate:
  The SDG Stimulus plan recommended by the High-Level Working Group and introduced by SG Guterres last February has five main components:

[ODS 0 | page 27] Argument candidate:
  According to IMF estimates in 2019, the financing gap facing 57 low-income developing countries (LICs and LMICs that are eligible for IMF concessional financing) to cover very basic investments in health, education, power, roads, and water and sanitation was in the order of US$300 billion to US$500 billion per year.

[ODS 0 | page 27] Argument candidate:
  Adding in these extra needs, the global SDG financing gap is perhaps US$1 trillion per year, or roughly 1% of gross world product (GWP) at market prices.

[ODS 0 | page 27] Argument candidate:
  As a rough rule of thumb based on work by SDSN and the IMF, the LICs need roughly 20% of their GDP in increased SDG investment outlays while the LMICs need roughly 10%, though precise amounts vary by country.

[ODS 0 | page 28] Argument candidate:
  The urgent objective of the SDG Stimulus is to address – in practical terms and at scale – the chronic shortfall of international SDG financing facing the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 28] Argument candidate:

NameError: name 'path_output_txt' is not defined

### Deepseek r1 70B

In [ ]:
prefix = 'G20_2024_'
model_name="deepseek-r1-70b"

res = process_sdg_runs(
    input_dir=path_extracted_data,
    output_dir=path_output,
    output_dir_stats=path_output_stats,
    prefix=prefix,
    model_name=model_name  
)

export_arguments_txt(
    json_path=res['unified_json'],
    output_dir=path_output_txt
)

create_relationship_csvs(path_output_txt + prefix + '_AllArgs_' + model_name + '_by_goal.txt', 
                         path_output_rels,
                         model_name,
                         prefix)

print(f'Stats by SDG for {model_name} in document {prefix}:')
display(res['per_sdg_summary_df'])

print(f'Stats overall for {model_name} in document {prefix}:')
dfGlobal2023 = save_overall_summary(res, path_output_stats, model_name).rename(columns={"pages_max": "pages"}).drop(columns=["ods_max"])
dfGlobal2023

[ODS 0 | page 7] Argument candidate:
  At the midpoint of the 2030 Agenda, all of the SDGs are seriously off track.

[ODS 0 | page 7] Argument candidate:
  Despite this alarming development, the SDGs are still achievable. None of their objectives are beyond our reach.

[ODS 0 | page 7] Argument candidate:
  The world is off track, but that is all the more reason to double down on the SDGs.

[ODS 0 | page 7] Argument candidate:
  At their core, the SDGs are an investment agenda: it is critical that UN Member States adopt and implement the SDG Stimulus and support a comprehensive reform of the global financial architecture.

[ODS 0 | page 7] Argument candidate:
  To achieve the SDGs the world must both alter its current investment patterns and increase the overall volume of investments.

[ODS 0 | page 7] Argument candidate:
  The Stimulus’ urgent objective is to address the chronic shortfall of international SDG financing confronting the LICs and LMICs, and to ramp up financing flows by at least US$500 billion by 2025.

[ODS 0 | page 7] Argument candidate:
  All countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national SDG strategies and commit to strengthening multilateralism.

[ODS 0 | page 7] Argument candidate:
  National governments must ensure both domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation – by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 7] Argument candidate:
  Achieving the SDGs requires global cooperation guided by the United Nations Charter.

[ODS 0 | page 7] Argument candidate:
  SDG transformations.

[ODS 0 | page 8] Argument candidate:
  Further investment is needed in statistical capacity and data literacy to support long-term pathways for key SDG transformations.

[ODS 0 | page 8] Argument candidate:
  At the halfway mark to 2030, there remains a great deal of work to be done to improve the data and methods underlying the SDG indicator framework.

[ODS 0 | page 8] Argument candidate:
  Evidence suggests that since 2016 there has been only limited progress and convergence in countries’ statistical capacity, including LICs and LMICs, and that international funding for data and statistics fell between 2019 and 2021.

[ODS 0 | page 8] Argument candidate:
  Also, in an information-rich and post-truth environment, citizens and decision-makers need knowledge and tools to transform data and science into evidence, actions, and long-term policies.

[ODS 0 | page 8] Argument candidate:
  According to major international studies, few teenagers can differentiate between a fact and an opinion.

[ODS 0 | page 8] Argument candidate:
  As underlined during the United Nations World Data Forum 2023 and in the 27 April Hangzhou Declaration, investing in statistical capacity, science, and data literacy are important priorities for achieving the SDGs.

[ODS 0 | page 8] Argument candidate:
  The SDSN and its global network will double-down on efforts to implement the SDGs by 2030 and beyond.

[ODS 0 | page 8] Argument candidate:
  Via science-based pathways and analytics, the SDSN supports discussions on SDG implementation at the global, regional, and national levels.

[ODS 0 | page 8] Argument candidate:
  All UN Member States and UN agencies can count on the continued efforts and energies of the SDSN around the world to support all governments, businesses, and civil society in embracing and aligning with the SDGs on sustainable development.

[ODS 0 | page 13] Argument candidate:
  The grim reality is that at the midpoint of the 2030 Agenda, the SDGs are far off track.

[ODS 0 | page 13] Argument candidate:
  As the world’s nations prepare to meet in September to review the progress the world has made so far towards achieving the SDGs, at the midpoint of the 2030 Agenda, SDSN emphasizes six areas for immediate action.

[ODS 0 | page 13] Argument candidate:
  Most urgently, UN Member States should adopt an SDG Stimulus, to close the massive financing gap faced by many developing economies.

[ODS 0 | page 13] Argument candidate:
  UN Member States must endorse a deep and overdue reform of the global financial architecture.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should adopt long-term sustainable development pathways that provide a stepwise and medium- to long-term approach to guide their sustainable development policies, not only to 2030 but to 2050, with particular focus on gender equality, social inclusion, and the principal of ‘leave no one behind’.

[ODS 0 | page 14] Argument candidate:
  All UN Member States should present, at regular intervals, their national SDG frameworks in the form of Voluntary National Reviews (VNRs). To date, 188 of the 193 UN Member States have already presented VNRs. Five countries (Haiti, Myanmar, South Sudan, the United States, and Yemen) have yet to do so, and should prepare to do so with urgency.

[ODS 0 | page 14] Argument candidate:
  UN Member States should commit to accelerating SDG progress to 2030, and to setting even more ambitious SDG targets to 2050, incorporating the recent Kunming-Montreal Biodiversity Framework and the High Seas Treaty.

[ODS 0 | page 15] Argument candidate:
  The SDGs are facing strong headwinds. Despite significant efforts in some places, national governments on all continents have fallen short in integrating the SDGs into national policies and public investments.

[ODS 0 | page 15] Argument candidate:
  Moreover, societal polarization, populism, and growing geopolitical conflict are hindering the global cooperation needed to achieve the SDGs.

[ODS 0 | page 15] Argument candidate:
  The international financial architecture is failing to channel global savings to SDG investments at the needed pace and scale.

[ODS 0 | page 15] Argument candidate:
  We emphasize that achieving the SDGs rests on five pillars of good governance: 1. Preparing long-term SDG pathways to guide public policy; 2. Ensuring SDG financing at the necessary scale and timing; 3. Promoting global cooperation and reducing geopolitical conflict and tension; 4. Supporting innovation to broaden social inclusion and environmental sustainability; 5. Regular reporting on SDG progress and performance.

[ODS 0 | page 15] Argument candidate:
  The SDGs are not only a public policy framework; they are an ethical imperative.

[ODS 0 | page 15] Argument candidate:
  They are grounded in the Universal Declaration of Human Rights, which celebrates its 75th anniversary this year.

[ODS 0 | page 15] Argument candidate:
  As the Universal Declaration makes clear, and the SDGs make explicit, social justice and sustainable development require the full realization of the rights of all people.

[ODS 0 | page 15] Argument candidate:
  The UN Sustainable Development Solutions Network (SDSN) is dedicated to finding and amplifying practical solutions to achieve the SDGs and closely-related global goals (such as the Paris climate agreement and the Kunming-Montreal Biodiversity Framework).

[ODS 0 | page 15] Argument candidate:
  We emphasize that all these global goals are interrelated and must be achieved together.

[ODS 0 | page 15] Argument candidate:
  Dire shortfalls in meeting the SDGs The SDGs are seriously off track (Figure 1.1).

[ODS 0 | page 15] Argument candidate:
  SDG progress was already very slow in the five years to 2020.

[ODS 0 | page 15] Argument candidate:
  According to the annual SDG Index, global achievement of the SDGs rose only slightly, from 64 percent in 2015 to 66 percent in 2019 – far too slowly to meet the goals by 2030, and with highly uneven progress within and between countries.

[ODS 0 | page 15] Argument candidate:
  Then with the onset of the pandemic, progress stopped.

[ODS 0 | page 15] Argument candidate:
  As of 2022, the global SDG Index is below 67%. At current trends, based on simple projections, there is a risk that the gap in SDG outcomes between HICs and LICs will be wider in 2030 (29 points) than it was in 2015 (28 points).

[ODS 0 | page 15] Argument candidate:
  This means that we are at risk of losing a decade of progress towards convergence globally (Figure 1.2).

[ODS 0 | page 15] Argument candidate:
  The multiple geopolitical crises in the world today will no doubt place further obstacles on the path to 2030.

[ODS 0 | page 15] Argument candidate:
  If we look at each of the 17 individual SDGs, not a single SDG is projected to be met at the global level.

[ODS 0 | page 16] Argument candidate:
  Dire shortfalls in meeting the SDGs

[ODS 0 | page 16] Argument candidate:
  Current Nationally Determined Contribution (NDC) targets, if implemented, would still lead to around 2.4°C warming by 2100.

[ODS 0 | page 16] Argument candidate:
  Even taking the net-zero pledges of many countries into account, best-case scenarios given current pledges would lead to around 1.8°C warming by 2100.

[ODS 0 | page 16] Argument candidate:
  Water scarcity affects more than 40% of the world’s population.

[ODS 0 | page 16] Argument candidate:
  An estimated 1.8 billion people depend on drinking water contaminated by human waste.

[ODS 0 | page 16] Argument candidate:
  Unsustainable water management practices, including chemical discharges into water supply systems for irrigation, affect the functioning of ecosystems services.

[ODS 0 | page 16] Argument candidate:
  Global resource consumption assessments for rare earth elements are critical.

[ODS 0 | page 16] Argument candidate:
  Although reserves of these elements do not exist in concentrated clusters – which make them inefficient for mining – certain countries are quite dominant in this field, producing 98% of the world’s supply.

[ODS 0 | page 16] Argument candidate:
  As demand for rare earth elements is increasing tremendously, their scarcity is becoming more evident.

[ODS 0 | page 17] Argument candidate:
  The 2021 UN Food Systems Summit raised many urgent concerns around improving the sustainability, affordability, and quality of food across the world (SDG 2).

[ODS 0 | page 17] Argument candidate:
  Providing quality education (SDG 4) for all children is perhaps the single most important key to achieving sustainable development in the long term.

[ODS 0 | page 17] Argument candidate:
  The UN General Assembly’s Transforming Education Summit held in September 2022 was a critical meeting to spur national and global efforts to transform education to give all people the skills and knowledge to end poverty, protect the environment, and build peaceful and inclusive societies.

[ODS 0 | page 17] Argument candidate:
  Note: Projected gap by 2030 is based on extrapolation of annual growth rate on the SDG Index over the period 2019-2021. Pre-pandemic projected gap is based on an extrapolation of SDG Index annual growth rates over the period 2015-2019.

[ODS 0 | page 17] Argument candidate:
  Part 1. How to Achieve the SDGs: The SDSN Framework "planetary boundaries" that regulate the Earth system.

[ODS 0 | page 19] Argument candidate:
  Unless the SDGs are actively pursued, geophysical tipping points combined with technological disruptions could ignite disastrous social conflicts within and between nations.

[ODS 0 | page 19] Argument candidate:
  We firmly believe that international cooperation together with the achievement of the SDGs is the best preventative to this dire and growing risk, and represent an opportunity to create positive social tipping points: for example, through equal access to high-quality education (SDG 4), and by fighting all forms of inequalities, including income and wealth inequalities (SDG 10).

[ODS 0 | page 19] Argument candidate:
  Although all governments are in principle committed to economic justice as enshrined in the Universal Declaration of Human Rights, and to the SDG tenets of ‘leave no one behind’ and ‘reach the furthest behind first’, too few are living up to these commitments, especially as powerful groups block adequate public support for weaker groups.

[ODS 0 | page 19] Argument candidate:
  She noted however that, while disrupting the dynamic of racially discriminatory underdevelopment may require a greater transformation than is possible at this moment, the SDGs held untapped potential to advance both development and non-discrimination.

[ODS 0 | page 20] Argument candidate:
  Despite this ominous news, the SDGs are still achievable.

[ODS 0 | page 20] Argument candidate:
  None of their objectives are beyond our reach.12 Yes, the world is off-track, but that is all the more reason to double-down on the goals, rather than surrendering to human-made shortfalls in achieving them.

[ODS 0 | page 20] Argument candidate:
  At their core, the SDGs are an investment agenda.

[ODS 0 | page 21] Argument candidate:
  To achieve the SDGs, the world must invest boldly, amply, and consistently in all eight kinds of capital.

[ODS 0 | page 21] Argument candidate:
  These investments must involve both governments and corporations.

[ODS 0 | page 21] Argument candidate:
  For example, while business capital is mainly the purview of the private sector, human capital is mainly the purview of the public sector.

[ODS 0 | page 21] Argument candidate:
  Governments too must take the lead in protecting natural capital, while civil society especially must promote social and cultural capital, including mutual understanding across cultures and nations.

[ODS 0 | page 21] Argument candidate:
  Infrastructure capital and innovation capital tend to be financed roughly equally by the public and private sectors.

[ODS 0 | page 21] Argument candidate:
  For example, governments tend to finance power transmission grids, while the private sector tends to finance power generation.

[ODS 0 | page 21] Argument candidate:
  Governments generally finance basic scientific research, while businesses focus on applied R&D.

[ODS 0 | page 21] Argument candidate:
  Parallel to investing in the SDGs, the world needs to stop investing in activities that threaten planetary boundaries, destroy human and natural capital, and harm social cohesion.

[ODS 0 | page 21] Argument candidate:
  Curtailing the extraction and use of fossil fuels is of paramount importance.

[ODS 0 | page 21] Argument candidate:
  To curb harmful investments, regulatory measures, including fair and sustainable taxation and the dismantling of unsustainable subsidies, need to be an integral element of the SDG investment agenda.

[ODS 0 | page 21] Argument candidate:
  In 2022, the United Nations Secretary-General appointed a High-Level Advisory Board on Effective Multilateralism, with a mandate to develop a list of concrete, actionable recommendations to improve international cooperation and advance the 2030 Agenda for Sustainable Development.

[ODS 0 | page 21] Argument candidate:
  The Board’s 2023 report lists six areas for action that are directly aligned with the SDGs and SDSN’s recommendations: rebuilding trust in multilateralism, safeguarding our planet and its people, scaling up and improving the efficacy of global finance, improving data systems and their governance, and promoting peace.

[ODS 0 | page 21] Argument candidate:
  The most important level of decision-making remains the nation-state.

[ODS 0 | page 21] Argument candidate:
  Nation-states hold the primary responsibility for achieving the SDGs.

[ODS 0 | page 21] Argument candidate:
  They are members of the United Nations and the signatories of United Nations treaties.

[ODS 0 | page 21] Argument candidate:
  They hold juridical responsibility for implementing treaty agreements and the rest of the United Nations architecture, including the United Nations Charter, the Universal Declaration of Human Rights, and the SDGs.

[ODS 0 | page 21] Argument candidate:
  National governments must ensure both the domestic implementation of the SDGs, including the reduction of negative spillovers, and international implementation by building a global governance and financial architecture that delivers the SDGs.

[ODS 0 | page 21] Argument candidate:
  Crucially, national government must also work with subnational governments to implement the SDG agenda at the local level, including sustainable urban infrastructure, delivery of social services, and ensuring safe communities.

[ODS 0 | page 21] Argument candidate:
  Virtually all governments of the world have embraced the SDGs in principle.

[ODS 0 | page 21] Argument candidate:
  188 of 193 UN Member States have submitted VNRs for comment by the other nations.

[ODS 0 | page 21] Argument candidate:
  Only five countries, notably the United States, Haiti, Myanmar, South Sudan, and Yemen, have never presented VNRs.

[ODS 0 | page 21] Argument candidate:
  Four of these countries are wracked by violence and poverty.

[ODS 0 | page 21] Argument candidate:
  The case of the United States stands as a glaring exception.

[ODS 0 | page 21] Argument candidate:
  The Nordic countries and European Union have shown considerable support for the SDGs.

[ODS 0 | page 21] Argument candidate:
  So too have many developing countries in the G20.

[ODS 0 | page 22] Argument candidate:
  Failures (and some successes) of national SDG governance

[ODS 0 | page 22] Argument candidate:
  The greatest responsibility for achieving the SDGs and safeguarding the planetary boundaries lies with the G20 members.

[ODS 0 | page 22] Argument candidate:
  The United States has so far shown very little commitment to the SDGs. We call on the United States to formulate an SDG action plan and to present a VNR to the High-Level Political Forum.

[ODS 0 | page 22] Argument candidate:
  The European Union – the world’s second-largest economy and its major lignite producer – has produced the European Green Deal (EGD), which is exemplary in many regards.

[ODS 0 | page 22] Argument candidate:
  In July 2023, the EU is set to present its first Union-wide voluntary review at the United Nations. This presents a good opportunity for the EU to send a strong message to the international community, and to demonstrate its commitment to and leadership on the SDGs.

[ODS 0 | page 23] Argument candidate:
  12th Five-Year Plan referred to the 2030 Agenda mainly in the context of international cooperation.

[ODS 0 | page 23] Argument candidate:
  China has reiterated its support for the SDGs, such as in greening its Belt and Road Initiative and launching the Global Development Initiative as a worldwide effort.

[ODS 0 | page 23] Argument candidate:
  A key measure for China will be the explicit integration of the SDGs’ domestic and international implementation into the 15th five-year plan (2026–2030).

[ODS 0 | page 23] Argument candidate:
  Some other G20 countries have shown weak commitments to the SDGs in recent years.

[ODS 0 | page 23] Argument candidate:
  Many of the poor performers, such as Brazil, recently elected new governments that have staked out a far more ambitious position vis-à-vis the SDGs.

[ODS 0 | page 23] Argument candidate:
  We urge all G20 governments to show the leadership required of them.

[ODS 0 | page 23] Argument candidate:
  Most of the low-income and lower-middle income countries, home to more than half of humanity, face major challenges in achieving most of the SDGs by 2030.

[ODS 0 | page 23] Argument candidate:
  Many of them lack an adequately high SDG commitment, and almost all lack access to the necessary financial means to implement the SDGs.

[ODS 0 | page 23] Argument candidate:
  At the midpoint of the 2030 Agenda, all countries, poorer and richer alike, should use the half-way momentum to self-critically review and revise their national strategies, using the principles of the 2030 Agenda (transformative, integrated, inclusive, leaving no one behind) as a yardstick.

[ODS 0 | page 23] Argument candidate:

,prefix,model,ods,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,deepseek-r1-70b,0,53,374,142,0,232
1,GLOBAL SGD2023,deepseek-r1-70b,1,53,57,30,0,27
2,GLOBAL SGD2023,deepseek-r1-70b,2,53,20,13,0,7
3,GLOBAL SGD2023,deepseek-r1-70b,3,53,36,24,0,12
4,GLOBAL SGD2023,deepseek-r1-70b,4,53,41,27,1,13
5,GLOBAL SGD2023,deepseek-r1-70b,5,53,7,5,0,2
6,GLOBAL SGD2023,deepseek-r1-70b,6,53,8,7,0,1
7,GLOBAL SGD2023,deepseek-r1-70b,7,53,23,12,1,10
8,GLOBAL SGD2023,deepseek-r1-70b,8,53,74,31,1,42
9,GLOBAL SGD2023,deepseek-r1-70b,9,53,67,23,0,44
10,GLOBAL SGD2023,deepseek-r1-70b,10,53,40,21,0,19
11,GLOBAL SGD2023,deepseek-r1-70b,11,53,35,17,0,18
12,GLOBAL SGD2023,deepseek-r1-70b,12,53,27,18,0,9
13,GLOBAL SGD2023,deepseek-r1-70b,13,53,87,47,0,40
14,GLOBAL SGD2023,deepseek-r1-70b,14,53,14,10,0,4
15,GLOBAL SGD2023,deepseek-r1-70b,15,53,32,20,0,12
16,GLOBAL SGD2023,deepseek-r1-70b,16,53,68,29,0,39
17,GLOBAL SGD2023,deepseek-r1-70b,17,53,168,77,0,91

Stats overall for deepseek-r1-70b in document GLOBAL_SGD2023:

Updated overall summary:

,prefix,model,pages,total_args,total_args_kept,total_dupes_removed,total_not_valid_args
0,GLOBAL SGD2023,qwen2.5-3b,53,251,161,0,90
1,GLOBAL SGD2023,gemma3-4b,53,4093,706,2,3385
2,GLOBAL SGD2023,gemma3-27b,53,708,330,1,377
3,GLOBAL SGD2023,llama3.3-70b,53,817,477,4,336
4,GLOBAL SGD2023,deepseek-r1-70b,53,1178,553,3,622